### ISSUE TITLE
mGBA State Bug

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1001]
Repro steps:

1. Load a GBA ROM into the mGBA core
2. Start TAStudio
3. Advance some frames
4. Hit '<<'

The game will no longer load.

**Comment by nattthebear** [comment]
Reproduce outside TASStudio:
1. Load a GBA ROM into the mGBA core.
2. Save state at Frame 0
3. Advance some frames
4. Load the Frame 0 savestate

The game will no longer load.

This is probably an upstream bug

**Comment by vadosnaprimer** [comment]
What about now?

**Comment by alyosha-tas** [comment]
Just tested, still broken.

**Comment by vadosnaprimer** [comment]
Some bug with frame 0 was fixed, and I think I updated the build, but this issue should be re-checked.

**Comment by YoshiRulz** [comment]
Still can't reproduce.
