### ISSUE TITLE
High RAM consumption and stuttering with rewind enabled in 2.x versions

### ISSUE THREAD

**Issue by ody1** [TASVideos/BizHawk#1002]
How to reproduce:
1. Load a Mega drive game.
2. Go to Menu -> Config -> Rewind & States.
     Enable Medium and Large savestates.
     Set Max buffer size to 1024 MB. (The higher, the more pronounced the effect)
3. As the game plays, monitor Bizhawk's RAM consumption in Task Manager.
     RAM consumption goes up quickly, then suddenly drops, then goes up again etc.
     This cycle is repeated every few seconds. If you set the Rewind frequency to every 1 frame it'll be faster.
     The stuttering happens the moment the RAM consumption drops.

This happens with Atari 2600, Mega drive, SNES (BSNES and Snes9x), 32X, Saturn and Neogeo pocket.
It does NOT happen with Gameboy, Gameboy advance (mGBA and VBA-Next), Lynx, Master system, NES (QuickNes and NesHawk) or PC-Engine.
The last version that didn't had this issue was v1.13.1.

**Comment by zeromus** [comment]
Short term: these cores need to manage a savestate buffer
Long term: the IStatable interfaces should be redesigned so the issue of buffer scavenging is explicitly dealt with

**Comment by alyosha-tas** [comment]
The stuttering in the A2600 core is caused by having the frame buffer as part of the state. 

If I remove it from the state, there will be some slight graphical corruption for one frame after loading due to the A2600 core enforcing a strict frame time even though the actual 2600 doesn't have this, so frame boundaries aren't always on VBL.

Alternatively I could just make frames only on VBL, which would lead to slightly inconsistent timing but no save state graphics corruption and a simpler overall core. I'm leaning towards this option.

**Comment by alyosha-tas** [comment]
I fixed the A2600 issues.

I'm not sure if this provides any guidance towards fixing the other cores, as all I did was remove the frame buffer from the state, so maybe the state was just too big?

**Comment by nattthebear** [comment]
I personally don't care too much anymore, but a lot of people have a lot of very strong opinions about the CFR/VFR debate.  You probably shouldn't have made that change without some discussion first.

**Comment by alyosha-tas** [comment]
Really? Well, revert as needed / desired, it just seemed like the cleanest solution to me.

**Comment by zeromus** [comment]
Alyosha, what's the status?

**Comment by alyosha-tas** [comment]
Oops, sorry I just noticed this question.

I only fixed A2600. I have no idea how to fix the other cores.

It looks like pretty much every core slowly leaks memory over time though, so maybe this issue should be renamed to 'BizHawk needs beter memory management' or something.

**Comment by nattthebear** [comment]
Untagged the waterbox cores.  Waterbox has larger savestates than some other cores, but we've done our best with that and there's not much more to squeeze.

That makes this just a sms issue?

**Comment by YoshiRulz** [comment]
Nope, I confused Mega Drive with Master System when tagging.
