### ISSUE TITLE
Glide64mk2 error when opening rom.

### ISSUE THREAD

**Issue by cheatfreak47** [TASVideos/BizHawk#1003]
I know this is generally the place for reporting issues, and both I and my friend here, are getting this error with the N64 support, and we have completely different hardware configurations as well.

I was trying to get Glide64mk2 to work, but when opening the rom, it just throws this error.

https://i.imgur.com/ZpvlIrv.png

I have no idea what the cause is, I tried tinkering away with it to no avail. Any idea what the problem is?

**Comment by cheatfreak47** [comment]
In order:

1. Bizhawk-Prereqs ran installer no problem, and everything else works fine
2. I have no security software at all actually, I even disabled Windows Defender via Group Policy
3. Just 7-Zip and WinRAR installed on my machine, my friend only has 7-Zip
4. That shouldn't be relevant. The location the program is being ran from has the full permissions of the user that is running it- in addition I did actually try what you said, and the error persists, safe to rule this out.
5. This is happening on a fresh copy of bizhawk straight from the releases section with no changes to settings at all- outside of changing the plugin for N64 to Glide64mk2.
6. I have no way of knowing what software could possibly interfere with Bizhawk- but nothing I have on my computer hooks into the software or anything of the sort, so I don't see how that could be possible. All the software on my machine is pretty standard, same goes for my friend.
7. I have a 64-bit OS (Windows 10 Pro build 15063), so I'm running the 64-bit version of Bizhawk.

For the record, all other functions of the software appear to be working, including other N64 plugins, I believe the issue is specific to the Glide64mk2 plugin, the other avaliable plugins for video (Rice, Glide64, and GLideN64) all work fine as far as I can tell. (They don't crash like this at least)

**Comment by cheatfreak47** [comment]
I went ahead and built Bizhawk myself, and tried again and this time, it gave me a more verbose error.
https://i.imgur.com/MFnIa5A.png
Perhaps this will be of use.

**Comment by zeromus** [comment]
I know what the problem is. the dll is built wrongly.

**Comment by phoenix1291** [comment]
You probably forgot something or made a mistake somewhere.
The games start well, but fall to 0fps shortly after,  Bizhawk freezes, unfreeze, freeze, unfreeze etc.
(Tested with Mario 64, F-Zero, OOT, etc, same issue)
[https://youtu.be/oBtDXRE0RXA](url)
Of course, no problem with other plugins.

**Comment by zeromus** [comment]
works fine for me.
