### ISSUE TITLE
PSX Esto es Futbol (Spain) [SCES 01704] Fails at loading

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#1004]
I didint tried the English version "This Is Football"

When loading onto the in-game football stadium, the loading gets stuck nearly the end.
Besides, i was having the most clean image possible.

**Comment by zeromus** [comment]
bug in mednafen upstream

**Comment by zeromus** [comment]
requires use of SBI file

**Comment by danylopez123** [comment]
Do i have to put the SBI file on the same folder as the bin/cue?

**Comment by zeromus** [comment]
yes, and it must have the same name as the cue

**Comment by danylopez123** [comment]
Alright then, thanks for helping me, i had no idea the SBI files would do something, that came from a mega pack of Pal PSX games i got
