### ISSUE TITLE
Crashing upon attempting to use the AVI writer

### ISSUE THREAD

**Issue by JBoughter** [TASVideos/BizHawk#1005]
I was attempting to record a TAS, and the AVI writer simply crashed the entire program whenever I tried to use it. This happens no matter what I'm doing, even if what I'm doing cannot really be recorded (such as not having a ROM open). I thought this was because of installing LAGS, however upon uninstalling it, the issue remained. I can't find any sort of answer upon googling my issue here, so I come here.

**Comment by zeromus** [comment]
uninstalling LAGS, whatever that is, may have left a broken codec or dll install. It's very possible for the problem you to be described by other faulty software. Ask google how to remove codecs from windows and then remove strange ones one by one until you find the culprit

**Comment by JBoughter** [comment]
It doesn't seem like this is the issue. I downloaded GSpot and I'm checking through my codecs, and there's nothing strange that I didn't install in here.

**Comment by zeromus** [comment]
it's the issue. what made you think it was because of installing LAGS? did it ever work before?

**Comment by nattthebear** [comment]
Just to rule out a bunch of potential issues:  Do any of the other video writers, like the ffmpeg writer for instance, work?

**Comment by JBoughter** [comment]
@zeromus I hadn't bothered to test prior, because I installed LAGS to render my TAS, and didn't have a reason to test prior since I didn't want to use lossy codecs.

@nattthebear It seems that the AVI writer is the only one with an issue, as all the others seem to work just fine.

I suppose I'll clarify my issue a bit more; it seems that even just going to "Record & Config" and then just trying to open the "AVI writer" menu crashes it, not because it attempted to record.

**Comment by zeromus** [comment]
we did release a version of bizhawk with that problem. maybe you're using that old version.

**Comment by JBoughter** [comment]
Nope. I am using Bizhawk 2.2...

**Comment by zeromus** [comment]
You may need to debug bizhawk when it crashes to see what dll it's crashing in (probably but not necessarily a bad codec). Alternatively, maybe you can find a tool to disable them one by one.

**Comment by JBoughter** [comment]
I wasn't able to figure out how to debug, as you seemed to assume I just know how to do that. Also, I failed to find any tool and you once again assumed I could just find a tool to disable codecs. Thanks, I guess. Still having this issue, despite looking for answers.

**Comment by JBoughter** [comment]
Seriously? That's literally all you had to tell me to do, just send me a guide to such a thing. I don't even give a shit for this issue anymore, the rudeness you have is just pitiful and I'm done even discussing here.

**Comment by zeromus** [comment]
We'll make a note and incorporate your degree of shit-giving about this issue in assessing any future issues.
