### ISSUE TITLE
SMSHawk: glitched text in Batman Forever (Game Gear)

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1007]
Text for Rocket Boots is always glitched.
[Batman Forever (W) corrupted text.zip](https://github.com/TASVideos/BizHawk/files/1335845/Batman.Forever.W.corrupted.text.zip)

**Comment by alyosha-tas** [comment]
Also occurs in this video:

https://www.youtube.com/watch?v=YmTffyEMUVk

Bad ROM? Does it happen on console?

**Comment by Reinc01** [comment]
Bizhawk says the ROM I used is a verified good dump. I don't know if the glitch happens on real Game Gear. I don't see why it would.

**Comment by zeromus** [comment]
bugged in bizhawk, bugged in kega fusion, two different emulators entirely. looks like a bug in the game to me. doesnt look like a bad rom.
