### ISSUE TITLE
Programs that hook DirectX fail to detect Emuhawk when in DirectX mode

### ISSUE THREAD

**Issue by danne2** [TASVideos/BizHawk#1010]
Exactly what the title says. Programs such as XSplit, OBS, and Rivatuner fail to detect Emuhawk when running in Direct3D9 mode. 
If you run in OpenGL mode, they're able to hook it, but there's an outstanding bug with XSplit with capturing Bizhawk in OpenGL mode which is why I've been using Direct3D mode.

This didn't happen in 1.11.9 which was the last version I was using before upgrading.

**Comment by zeromus** [comment]
Then those programs can't handle direct3d9 running in 64bits. Try changing config > display > window > Enable Windows Fullscreen Hacks
