### ISSUE TITLE
[request] RAM Watch - display BCD values

### ISSUE THREAD

**Issue by pwolf23** [TASVideos/BizHawk#1011]
I started TASing with BizHawk and find it to be a superb emulator with great debugging tools. I was wondering if someone could add this feature, as it seems to be not hard to implement:

When adding an address to the "RAM Watch" tool, one has the option to select the "Display Type" of the address as Unsigned/Signed/Hex/Binary/etc.. Since a lot of games seem to save highscores in a BCD format... would it be possible to add a BCD-Display Type?

Example:
A game saves your score in 2 Bytes...
Displayed Score (in game): 8690
Binary Representation (RAM Watch):  1000 0110 1001 0000
Unsigned Representation (RAM Watch):  34448
I would like to see a BCD representation for the RAM Watch, which would display the actual, displayed score.

Any thoughts on this?

**Comment by vadosnaprimer** [comment]
Print your values in whatever format you want using lua. It's there so that everyone could extend the standard behavior, I don't think BCD is a basic need for RAM Watch. Personally, I find lua hud way more handy and only use it instead of RAM Watch.

**Comment by zeromus** [comment]
This is straightforward to add (see our fixed point formats for something exotic) albeit a little annoying, but dont many games use "BCD"-like values pre-adjusted to tile numbers? Already BCD will not be widely used.. with this other consideration, it is even less widely used.... 

assigned myself, because I started doing this to see how hard it would be

**Comment by zeromus** [comment]
The very first game I checked, SMB, didn't even store BCD in the way I expected. There's no normal way to do this. At the very least, there's 3 ways: Call it TO (tens-ones) or OT (ones-tens) or XO (nothing-ones). There's probably more. I'm closing this as impractical. This would really only be feasible if we added some kind of custom scripted watching capabilities.
