### ISSUE TITLE
SMSHawk: The Simpsons: Bart vs. the Space Mutants crashes and glitches

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1013]
Frequent glitches and sometimes crashes in Bart vs. the Space Mutants for SMS. Bizhawk says I'm using a good ROM.

[crash and glitches.zip](https://github.com/TASVideos/BizHawk/files/1351684/crash.and.glitches.zip)

**Comment by zeromus** [comment]
dont hold your breath, this core is on life support

**Comment by alyosha-tas** [comment]
Hi Reinc01,

Can you send a movie that starts from power on? I would like to test with the new z80 core to see if there are any changes.

**Comment by Reinc01** [comment]
[full movie.zip](https://github.com/TASVideos/BizHawk/files/1384327/full.movie.zip)

**Comment by alyosha-tas** [comment]
Thanks, same glitches occur with the new core. Movie still syncs though so that is good.
I plan on re-working this core eventually, this will be a good test case for when I do.

**Comment by alyosha-tas** [comment]
It looks like the problem here is that this game should be played in PAL mode.

In all cases of glitches / crashes, the game is experiencing an interrupt at a time it is unable to handle causing strange results.

Probably the core should force the correct mode for games in the DB, but that is a seperate matter, but the emulation itself is not the issue.

**Comment by Reinc01** [comment]
I noticed that the same glitches happen in PAL as well, but much rarer (only seen one so far, wasn't able to replicate). No crashes so far.

**Comment by Reinc01** [comment]
I'm not sure if this is will help, but here is a minor example
[Bart vs. the Space Mutants (E) glitch.zip](https://github.com/TASVideos/BizHawk/files/1424179/Bart.vs.the.Space.Mutants.E.glitch.zip)

**Comment by Tastyfish** [comment]
Interesting that it's the sprite layer that has the glitches even though they're scrolling with the scene correctly. I assume there's supposed to be a sprite there then, maybe a tile pattern banking glitch? I don't know if that makes sense for the game's mapper.

**Comment by alyosha-tas** [comment]
We are really in need of hardware testing for SMS / GG, these kinds of unconfirmed edge cases are starting to stack up.

I'm still thinking this is a game bug though.
