### ISSUE TITLE
SMSHawk: World Series Baseball doesn't start

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1014]
World Series Baseball for Game Gear doesn't start. Bizhawk says I'm using a good ROM.

**Comment by alyosha-tas** [comment]
This game needs a serial eprom chip.

http://fms.komkon.org/MG/MG.html indicates the chip is called a 93C46.

Related games also need this chip. Not sure when I might get around to it but I'll add it to my list.

**Comment by Tastyfish** [comment]
@alyosha-tas Is it alright if I work on this? I found the datasheet and I think I can throw together an emulator for the chip.

**Comment by alyosha-tas** [comment]
Sure thing have at it!
Thanks for offering!
