### ISSUE TITLE
Suikoden 1 Freeze

### ISSUE THREAD

**Issue by LtRuff** [TASVideos/BizHawk#1022]
so im very new to emulators and working this stuff.  i was able to get the game running the other day and played a couple hours into the game.  saved my progress then hopped off.  i tried to play the game today and when i hit the continue button the game froze.  made it past the intro, hit start screen and when it asked to select new game or continue it freezes and stops playing music.  im using epsxe.  and advice would be great.  thanks

**Comment by LtRuff** [comment]
BTW when i hit new game, game loads up fine and off i go.  is there a special way to save games or something that im not aware of?

**Comment by zeromus** [comment]
epsxe is not bizhawk.
