### ISSUE TITLE
Albert Odyssey Text bug/glitch

### ISSUE THREAD

**Issue by Valis77** [TASVideos/BizHawk#1027]
I have a small issue, it's only minor. When i engage into battle, one of my characters would cast a spell or a skill and the text box will highlight it, but most of the text will glitch out as if it blocked most of the text. sometimes it happens when enemies cast a skill/spell as well. i have a link to the video regarding it. if there's a way to fix it that would be awesome. Thanks in advance.
![albert odyssey - legend of eldean usa re _0002_0000 avi_snapshot_00 04](https://user-images.githubusercontent.com/32915142/31773388-35e6c762-b4a8-11e7-80a7-681f0dad8d14.jpg)
http://www.viddler.com/v/132e4457

**Comment by zeromus** [comment]
please test in mednafen

**Comment by Valis77** [comment]
i did and i got the same results.

**Comment by zeromus** [comment]
which version of mednafen? what do we need to know to get to this point in the game speedily?

**Comment by Valis77** [comment]
how can i say this? When you play the game you need to go to town of Solace and meet Leos for the first time from there she will join your party. At that point in the game is where you control her in battle it was the first thing no noticed when she was using that skill. At times it happens to monsters that use skills/magic but i forgot which ones. it's just that one i noticed and happens the most.

**Comment by zeromus** [comment]
Can you please say which version of mednafen?

**Comment by Valis77** [comment]
bizhawk emulator 2.0.0(x64)
Mednafen core 0.9.44.1

**Comment by zeromus** [comment]
Ryphecha is aware of this. The problem seems thorny. We'll have to monitor upstream updates

**Comment by Valis77** [comment]
ok thanks!

**Comment by nattthebear** [comment]
This should be fixed in 2.5
