### ISSUE TITLE
[Issue/bug?][PS1]  Bug with PS1 emu not sure..  Memorycard for FFT is NOT writing to HDD..

### ISSUE THREAD

**Issue by MelchiorGaspar** [TASVideos/BizHawk#1029]
Even though I save to memory card in game and it takes it..
BizHawk/Octocore is NOT writing a SaveRAM combined memory card file...

plus using a single file for two memory cards.. is ick...  
While the memory card manager I have called  "MemcardRex.exe"
can read and write to only the first card out of two... so I can copy my existing
saves from ePSXe generated MCs ... it once picked up that save from file when I loaded FFT 
from within  BizHawk... but would not write back to that file..

FFT = Final Fantasy Tactics

memory card file saving seems to work for my other PS1 games
I dumped from my own disc as MDS/MDF and CCD 
then tried bin/cue... which BizHawk seemed to like more as it considered it a verified DUMP..

**Comment by zeromus** [comment]
How have you confirmed it is not writing a saveram combined memory card file? Are you using memcardrex.exe to confirm? Perhaps memcardrex.exe does not actually read the single file format that bizhawk uses.

Bizhawk will not be changing its file format.

**Comment by MelchiorGaspar** [comment]
memcardrex was used to look into the memory card files.. 
for ePSXe individual memory card files I can read/write it fully...
for BizHawk.. I can only see the  first card out of two...
I used it to copy the 3 + hour in progress save I had from ePSXe. Mem card file into the first card of 
the BizHawk mem.card file... it worked fine..
but for some reason. it picked it up and loaded fine one time in BizHawk.. but other times it said no save resent.. even on a new game with a new mc file... it says it would save.. soft reset. save present.. exit 
BizHawk and restart it again.. load FFT.. save not there... save states work fine...  =/


a double file is kinda.. meh.. but I submitted a feature update request with there GitHub oage..
so maybe they can support it..  if you could jump over there and provide specs on the format of 
your mc file.. like does it have a break of some kind after the end of the first card??


here is said issue ticket. ;-) 
https://github.com/ShendoXT/memcardrex/issues/5

**Comment by TheBlueTroll** [comment]
MemcardRex definitely cannot correctly read BizHawks combined memory card files. it can read the first one and (i assume) correctly change it, but it cannot the second one.
Its not likely to become supported either as every other format it reads assumes its only one memory card.
The good news (as i said on the MemcardRex ticket) is that it looks like Bizhawk's dual memory card is just the 2 memory cards written one after the other, and can easily be split at the middle to form the 2 individual parts to be read by MemcardRex. 

I would not recommend BizHawk change their format just to work with a ps1 editor, though i would recommend a tool to convert the dual save into 2 individual parts.

**Comment by zeromus** [comment]
I wouldn't support it, if I was memcardrex. As TheBlueTroll says, it's just the two files concatenated.
We will at some point offer an option to export the individual memory cards.

**Comment by MelchiorGaspar** [comment]
Whats the use of export the individual memory cards.??
if BizHawk will never support that format.. will it be able to recombine them into one for BizHawk to use??

and my use of rex to copy my saves over for use with is BESIDES THE POINT...
YOU closed my bug/issue ticket without having actually resolved anything..... >_< >_> :-/  :P 

BISHAWK is not writing saves  made to memory card to file for Final Fantasy Tactics...
my transfer of my Suikoden 1 save using rex worked just fine 
and is saving and loading correctly as far as I can tell...

**Comment by zeromus** [comment]
The mystery is solved. Split the file as @TheBlueTroll suggested. 
If you still have a bug with saving in FFT, please make a new bug ticket without involving rex because it is BESIDES THE POINT and I can't understand what you're saying when it's full of besides the point talk about rex. Report the bug in the form of reproducible steps.

Bizhawk may one day support importing individual memory cards as well. (but don't hold your breath)

**Comment by MelchiorGaspar** [comment]
@TheBlueTroll  SAID "though i would recommend a tool to convert the dual save into 2 individual parts."
so THERE IS NO tool to split said .SaveRAM files..  YET!
creating a NEW issue ticket now... it will take a while.. :P  :-/

**Comment by zeromus** [comment]
Tool to split said .saveram files: hex editor

**Comment by TheBlueTroll** [comment]
https://superuser.com/questions/80081/how-to-split-and-combine-files
@MelchiorGaspar
Case closed. Tool alredy exists. Split at 128kb mark

**Comment by gooseplus** [comment]
Sorry to post in a thread that is so old, but is there a step by step for how to split this exactly? I see the Hex Editor in tools but no split option nor do I know how I would split exactly at 128kb.

**Comment by zeromus** [comment]
external hex editor tool. for example, I use "hex workshop". not the one in bizhawk. there won't be a "split" option in there. You will have to improvise. It isn't hard. The post from TheBlueTroll also tells you how to split files with other tools. It's pretty step by step.
