### ISSUE TITLE
Cannot use the Rewind function in BizHawk

### ISSUE THREAD

**Issue by Mario3264** [TASVideos/BizHawk#1040]
As far as I know, it only works in the NES core for me; It is probably disabled in other systems to prevent massive performance losses when it is enabled and used.

**Comment by zeromus** [comment]
then use the config > rewind & states menu to change the settings

**Comment by Mario3264** [comment]
![currentsettingsworksonnesnotsnes](https://user-images.githubusercontent.com/16366524/32147565-dfab30f2-bca6-11e7-84f7-e01aeffcf120.png)
![rewindenablednes](https://user-images.githubusercontent.com/16366524/32147567-e16f9284-bca6-11e7-9ea9-a50c5ece72f1.png)
![rewinddisabledsnes](https://user-images.githubusercontent.com/16366524/32147569-e3836a0a-bca6-11e7-9cbc-bff8a5e3d04d.png)

**Comment by zeromus** [comment]
great, you found the config > rewind & states menu. now use it to change the settings.

**Comment by Mario3264** [comment]
change what settings within it?

**Comment by zeromus** [comment]
Whichever ones make it work. I suggest trying them one at a time.

**Comment by Mario3264** [comment]
Apparently, turning on Large Savestates makes rewind work in SNES :\

**Comment by Mario3264** [comment]
But I want it to be able to rewind every frame...

**Comment by zeromus** [comment]
No doubt.

**Comment by Mario3264** [comment]
I forgot to mention, GBC can also rewind with Small Savestates enabled only for me.

**Comment by FingPat** [comment]
Came across, this surprised how caustic someone can be.

**Comment by FingPat** [comment]
In any event, I had the same issue. Like the people above referenced enabling the Medium and Large savestates option gave me a "rewind enabled" dialog message and allowed me to rewind.

**Comment by nattthebear** [comment]
> Came across, this surprised how caustic someone can be.

This is a three year old issue, question asked and answered, original poster long gone.  Let's not start new arguments on it.  Locking as there's nothing more to be added to this.
