### ISSUE TITLE
Can't load Sega Saturn Games

### ISSUE THREAD

**Issue by PlayBoyMan** [TASVideos/BizHawk#1043]
When I try to load a Sega Saturn game, I get this major error:
![emuhawk_2017-10-29_21-38-54](https://user-images.githubusercontent.com/3860527/32151320-6d2cacbc-bcf2-11e7-952b-2c699c814c03.png)

I made sure I ripped the discs correctly.

**Comment by hegyak** [comment]
The CUE file is referring to that exact path.  If the BIN file is not that exact name, and Location, BizHawk will fail to load the file.

**Comment by zeromus** [comment]
Your cue is garbage. ~~Even if~~ especially if you rip it yourself.
