### ISSUE TITLE
NEW AutoSave feature.. interfering with regular SaveRAM saving to HDD.. ??

### ISSUE THREAD

**Issue by MelchiorGaspar** [TASVideos/BizHawk#1044]
trying out this new feature.. it seems to work but instead of saving the existing memory card 
SaveRAM files, it creates and updates NEW 
- **AutoSaveRAM.SaveRAM**  vs.  **.SaveRAM**

and once the timer hits for the auto save to save to disk.. I tried 10 sec after which
it clears the dirty bit thing and NEVER saves to the original/SaveRAM file at all..
but upon a soft-reset or core-reset.. there is a popup

- **AutoSaveRAM.SaveRAM** 
COULD be shortened to just
- **Auto.SaveRAM**

this new AUTO.Save feature should just write to the main SaveRAM and leave it at that..
the check and save would be better.. ie one a write to the SaveRAM in memory is detected
immediately write it to DISK. no need for a timer.. but extra work?

**Comment by zeromus** [comment]
I can't make any sense out of this, but it sounds like you just don't like it. Too bad, it works exactly as intended.
