### ISSUE TITLE
Picodrive (32x) Improperly Reports Endianess of the MD Cart Domain

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1048]
Despite 32x roms being big-endian, Picodrive misreports the MD Cart domain as little-endian instead of big-endian.

It seems to just be missing `MEMORYAREA_FLAGS_YUGEENDIAN` on line 256 of `waterbox/picodrive/bizhawk.c` but I can't verify that fix works (and doesn't break anything else) and submit it as a pull request as I'm unable to build Waterbox cores.

**Comment by nattthebear** [comment]
Woops!  While I'm in there, are you aware of any other Picodrive misflagged domains?

**Comment by NarryG** [comment]
I can't verify any other domains 100%. You'll probably want to see if you can ask someone who is familiar with the Genesis and 32X architecture.  I only noticed this as I was comparing the rom domain to the file on the disk and was getting a complete mismatch. 

I know for a fact MD Cart should always be Big Endian but that's the only one I can confirm. In fact, the Z80 is a little-endian CPU yet the Z80 Ram is flagged as Big Endian in GPGX but Little Endian in Picodrive.

You should probably poke someone who has knowledge of the system itself on this one as there are a bunch of inconsistencies.

Doing a direct comparison using GPGX  (Sonic 3 & Knuckles) and Picodrive (Knuckle's Chaotix)
These domains are all labelled Big Endian in GPGX but Little Endian in Picodrive.

- MD Cart
- Z80 Ram
- SRAM
- CRAM
- VSRAM
- 

These domains are labelled Little Endian in GPGX and Big Endian in Picodrive

- VRAM
