### ISSUE TITLE
Xbox 360 Pad Analogue Triggers not detected as Analogue.

### ISSUE THREAD

**Issue by Mad-Matty** [TASVideos/BizHawk#1054]
I've noticed that when setting up the Sega Saturn 3D Pad, The analogue triggers of my 360 pad are not detected when trying to setup the Analogue triggers of the emulated 3D pad.  I can use the triggers in the digital section if I want to assign them, but not analogue where they would be more useful.

If I use a PS4 pad, then assigning L2/R2 triggers works just fine when assigning to the emulated 3D pad triggers.

Also, I am not sure if the Vertical axis is the wrong way around.  Up/Down seems to be wrong way around in games.  (I don't have a real 3D pad to test) Recent games I have tested are Sega Rally Plus and Sky Target.  I can work around these issues, but it may still be something to look into.

**Comment by zeromus** [comment]
nah, you can investigate further if it's important.
