### ISSUE TITLE
Implement the Super Scope, Justifier, and Mouse in (SNES9x)

### ISSUE THREAD

**Issue by Testsr** [TASVideos/BizHawk#1056]
Snes9x 1.54.1 has full mouse and super scope support.

**Comment by Testsr** [comment]
Thank You!

**Comment by Testsr** [comment]
Needed for Yoshi's Safari and Sim Ant. Bsnes slows down to a crawl when active.

**Comment by heckez-sys** [comment]
@Testsr wtf this is still open HOW

**Comment by Testsr** [comment]
Testing for support.

**Comment by nattthebear** [comment]
SNES games with alternative input devices are a small minority.  If you need to play one of those, just use the BSNES core.

**Comment by Testsr** [comment]
At the time of the original request, the higan core was the only way to get mouse support. Higan was very power intensive  I posted this because I noted that Snes9x had the option, and the standalone Snes9x had full support for the mouse. Now, of course BSNES is better for this.
