### ISSUE TITLE
Sameboy is pitched up half a semitone

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1061]
When using Sameboy for SGB, all audio is pitched up by what appears to be half a semitone. I haven't verified exactly how pitched up it is, but doing it by ear it sounds like half a semitone.

[How it sounds in GBHawk (and how it's supposed to sound)](https://narry.land/PnSM9O.wav) 
[How it sounds in Sameboy](https://narry.land/9jBNdh.wav)

**Comment by nattthebear** [comment]
This is correct emulation.  The original SGB used the SNES clock for its clock reference, giving a clock rate 2.4% faster than a GB.  This will make audio sound 0.41 semitones higher.

**Comment by NarryG** [comment]
Then BSNES is wrong.
I probably should have done the comparison between BSNES and Sameboy. I assumed BSNES was correct as it matched Gambatte and I wasn't aware that the SGB ran a bit faster.

[How it sounds in BSNES](https://narry.land/Rqu9NA.wav)
[How it sounds in Sameboy](https://narry.land/9jBNdh.wav)

**Comment by nattthebear** [comment]
The SGB2 runs at the same speed as the GB, so doesn't have this issue.  BSNES may be emulating the SGB2?  That doesn't sound correct though, because it uses SGB1 bios files.

I guess I don't know what it's doing.
