### ISSUE TITLE
A corrupt config.ini can prevent Bizhawk from launching

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1063]
My config file became corrupt after quitting Bizhawk (if I can figure out how to reproduce I'll report that as its own bug) and when I went to re-open Bizhawk, it was unable to boot yet threw no exception. Removing the corrupt config file fixed the issue.

Here's a copy of the corrupt config file if it's of any use.
https://gist.github.com/NarryG/b1baf74e51aff0ca12476a8be6693585

**Comment by zeromus** [comment]
I guess someone should try-catch that

**Comment by Asnivor** [comment]
@zeromus This is already try/catched:

![image](https://user-images.githubusercontent.com/7911038/37761591-01876e4e-2db2-11e8-881b-db2e0240e3bf.png)

Its just that for some reason (maybe mainform isnt initialized properly yet) the exception thrown is completely unhandled and the program crashes.

It's obviously a simple fix if you want to just return default(T) when this happens, but I'm not sure that is the best outcome.
