### ISSUE TITLE
GameBoy: GPU Viewer: Gambatte displays garbage

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1068]
Using the GPU Viewer causes a crash with all cores on the intro screen of Kirby's Dream Land. 

It looks like it's somehow related to 'tall' sprites. 
GPU Viewer is otherwise broken in general as well. 

Doesn't occur in 1.13, so possibly related to the move to 64 bit?

**Comment by alyosha-tas** [comment]
Looks like it's this: 

  322:                  DrawTileHv((byte*)((int)tile ^ 16), dest + pitch * 8, pitch, thispal, hflip, vflip);

(byte*)((int)tile ^ 16) 

should be just

tile + 16

xor can put the destination below the the memory range of the pointer. How did this not crash in the past?

This fixes Sameboy and I got GBHawk working with it so I'll update the issue to just be Gambatte.

**Comment by alyosha-tas** [comment]
Well I at least kind of figured out the problem for Gambatte.

It actually is receiveing the correct information to each pointer, the problem is that the palette info needs to be in the form 0xFFxxxxxx but it gets it in the form 0x00xxxxxx

So, that needs to happen somehow. ither write it to the memory location pointed to, do it by default in Gambatte, or create a new pointer which contains the correct palette info. I'm not sure which to do yet.

**Comment by zeromus** [comment]
why not just mask everything off but xxxxxx?

**Comment by alyosha-tas** [comment]
The upper byte needs to be set so it doesn't appear as transparent when thebitmap is drawn I think.

Anyway I just set the required byte to 0xFF in the GPU Viwer so this is fixed and all 3 cores can now use the GPU Viewer
