### ISSUE TITLE
Multiple issues exist with the prerequisite checker leading to crashes despite the prereq checker passing

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1069]
There are currently multiple issues with the prerequisite checker. I went through manually to check the various configurations and these are the results. I intentionally avoided the prereq installer as the goal was detecting issues with the checker built into Bizhawk.
All of this was tested on 2.2.1 release & Windows 10 Creator's Update.

Issue 1: 
Mis-detects the presence of VC2015. If all other dependencies are met, this results in the emulator seeming to work until you try launching certain cores (for example N64) where it'll proceed to crash on you.
![fkgh1gn](https://user-images.githubusercontent.com/3047793/33236176-e5ec757a-d218-11e7-9cf3-f67a49e03c2c.png)  

Issue 2: 
Even with all of the dependencies seemingly installed (according to the prereq checker), Bizhawk still failed to launch (crashed while launching). 
As it turns out, the culprit was that DirectX wasn't fully installed. The prereq checker thought that Direct3D9 was in place, but in reality it was most likely detecting the bundled Windows 10 DLLs and not the full runtime. This resulted with a crash at launch (no error message or anything, just a silent crash).
You can see in the image posted before that it thought that Direct3D9 was installed despite the full DirectX runtime not being installed. Manually installing the full runtime fixed it.  

Issue 3: 
It doesn't check for VC2013. According to the prereq installer, this is required for Bizhawk to run properly. I didn't run into any issues without 2013 in place, but I did a very quick check. I didn't do a full runthrough of all cores and features.

**Comment by zeromus** [comment]
1. NOPE: I doubt your method for confirming the vc2015 runtime is installed is correct; in a newer OS it's likely to be a core part of the OS not listed anywhere. I also doubt this is what makes "certain" cores crash. I can't diagnose "certain". Provide more details instead of jumping to conclusions. Your vc2015 runtime may have been broken. About the only version mupen doesn't require right now is 2015. 

2. NOPE: Bizhawk will fall back to gdi+ if direct3d9 can't startup. Since that didn't happen in your case, it's more likely your direct3d9 was broken, and manually installing the full runtime repaired the brokenness. We can't detect a 100% fully operational direct3d runtime, otherwise our detector would crash the same way bizhawk did.

3. Mupen supposedly requires 2013, but maybe only for one plugin, I don't know. I mean, I'm looking at its dlls right here and it's demanding 2013. It's also demanding 2012 and 2010. What a mess. We use prebuilt dlls delivered by mupen that need 2013, so that's not likely to change. I think we need to fix the remaining mismatches though

**Comment by hegyak** [comment]
I can try and setup a Stock Windows 10 but I need to KNOW what version of Windows 10 to check against.  So I can verify these issues.

**Comment by NarryG** [comment]
The version I was using here was Creator's Update.

**Comment by hegyak** [comment]
The First Creator Update, or the Second one?  1703 or 1709?

**Comment by NarryG** [comment]
Creator's Update, not Fall Creator's Update, so 1703.

**Comment by NarryG** [comment]
Just reinstalled Windows and yeah, it was other software installing incomplete versions of the various prerequisites.

The fresh Fall Creator's Update install of Windows 10 fails on all of the tests except .net Apologies for the mistake in the original report. I didn't expect other software to installl half-complete versions of the redist into the Windows folder.
That eliminates 1 and 2 as issues that are easily fixable.

**Comment by YoshiRulz** [comment]
see also #1265?

**Comment by YoshiRulz** [comment]
After #1438, don't worry about breaking anything in the prereq code as it will only run on Windows.

Because our copy of mupen is built from source, can we figure out exactly where it requires the 2013 runtime?

**Comment by zeromus** [comment]
Last I checked a number of the vcxprojs were in disrepair and rebuilding all the dlls is not a small project. a big problem is there are multiple vcxproj choices and it isnt clear which one (or which configuration) to use, but it should all be possible. 

We need to refresh our standards for which vc runtime to use. I can't remember whether or not we support XP. Either way, we should wait for vs2019 to come out and evaluate that in light of whether it's a turd, whether it runs on windows 7 at all, and whether it supports xp toolchain (without requiring additional VS install) if xp support is still important. If someone's gonna rebuild all these dlls we may as well start on a new platform. (Even though, if we ever update mupen, we should probably use whatever upstream is using)

**Comment by NarryG** [comment]
- 2.0 dropped support for XP.

- 2019 released the other day, supports Win7 SP1 (I've been using the preview build for months and have had no issues personally, but I'm on Win10)

-Upstream still uses 2013

**Comment by vadosnaprimer** [comment]
> 
> 
> After #1438, don't worry about breaking anything in the prereq code as it will only run on Windows.
> 
> Because our copy of mupen is built from source, can we figure out exactly where it requires the 2013 runtime?

I tried and failed. Feel free to try.

**Comment by YoshiRulz** [comment]
DirectX is no longer required on startup (60b7858fb), so I'm closing this.
