### ISSUE TITLE
Bizhawk Fails to Run Movie

### ISSUE THREAD

**Issue by yoshiweegee** [TASVideos/BizHawk#1070]
I wanted to try running the Banjo-Kazooie TAS movie in Bizhawk, specifically the Bizhawk movie (BK2) file from TASVideos' publication.

After hitting OK to presumably begin the playback, a dialog pops up titled "N64 load error" with the following error message:

```
A core accepted the rom, but threw an exception while loading it:

System.NullReferenceException: Object reference not set to an instance of an object.
    at Bizhawk.Emulation.Cores.Nintendo.N64.N64SyncSettings.GetVPS(GameInfo game, Int32 videoSizeX, Int32 videoSizeY)
    at BizHawk.Emulation.Cores.Nintendo.N64.N64..ctor(CoreComm comm, GameInfo game, Byte[] file, Object syncSettings)
```

I have run the pre-req executable, so I am not certain why this file is not be playing. My only lead is that the movie was produced with Bizhawk 1.10.0, but the movie version is v2.0.0, so I'm not sure if this matters. I have also searched for this issue, but I could not find anything.

**Comment by zeromus** [comment]
edit the movie to specify a different graphics plugin in the sync settings. it's probably done on jabo, which can't work in 64bits, which bizhawk now is

**Comment by yoshiweegee** [comment]
How do I edit the movie's sync settings? If it's with TAStudio, loading the movie there also causes the same error to occur.

**Comment by NarryG** [comment]
bk2 files are just zip archives. Extract it with the archive manager of your choice, open SyncSettings.json, look for any references to Jabo, replace them with one of the other plugins (GlideN64)

**Comment by yoshiweegee** [comment]
Alright, that seems to have worked! Thank you for your help!
