### ISSUE TITLE
Controller Button Not Working

### ISSUE THREAD

**Issue by SnackVenom** [TASVideos/BizHawk#1076]
The other day I went to Walmart, and got a cord that connects my Xbox One controller to my computer's USB port. I was playing some Mario Party 5 and a couple of other games, and it was working fine there. Then when I got BizHawk I tried to use the controller, and when I hover over the config tab the controller section is grayed out. So I can't connect my controller. Any help 👌 💯 👌 👌 💯 👌 👌 💯 👌 👌 💯 👌 👌 💯 👌 😂

**Comment by synnae** [comment]
For all your controller needs, use JoyToKey.
https://joytokey.net/en/

**Comment by NarryG** [comment]
Don 't use Joy2Key. Bizhawk has native Dinput and XInput support.

The "controllers" tab is the generic controls section. As Bizhawk uses per-core controls, the configuration is grayed out until you launch a core. Once you launch a core, you'll be able to set the config for that specific core.

**Comment by adelikat** [comment]
NarryG's comments are accurate and will resolve this issue.
