### ISSUE TITLE
socket = require("socket")

### ISSUE THREAD

**Issue by zmarotrix** [TASVideos/BizHawk#1077]
On Windows, socket = require("socket") causes an error saying;

```
NLua.Exceptions.LuaScriptException: error loading module 'socket.core' from file '.\socket\core.dll':
    dynamic libraries not enabled; check your Lua installation
```

I've recompiled my Lua interpreter and made sure they are enabled. Does Bizhawk have a built-in Lua interpreter? If so, how can I update it?

**Comment by vadosnaprimer** [comment]
Try luainterface instead of nlua. Somewhere in advanced config.

**Comment by zmarotrix** [comment]
I got the same error.

**Comment by zmarotrix** [comment]
Nevermind, I reloaded the Emulator and now I'm getting this:

NLua.Exceptions.LuaScriptException: error loading module 'socket.core' from file '.\socket\core.dll':
	%1 is not a valid Win32 application.

**Comment by vadosnaprimer** [comment]
You're obviously still using nlua, you need luainterface.

https://i.imgur.com/Dlc71c3.png

**Comment by zmarotrix** [comment]
Weird, I have that option checked, restarted the emulator and all. I'm not sure what's going on.

**Comment by zmarotrix** [comment]
Here are my settings 
https://i.imgur.com/zc8tf4T.png

Here is the output
https://i.imgur.com/u8WDzXG.png

**Comment by vadosnaprimer** [comment]
Yeah this is stupid. It seems to need @zeromus.

**Comment by zeromus** [comment]
You cant just slop random lua plugins into bizhawk. See here for all the annoying complexities:

https://stackoverflow.com/questions/33428382/add-luasocket-to-program-bizhawk-shipped-with-own-lua-environment

Sounds like your bug is due to using a 32bit dll, anyway

**Comment by udoheld** [comment]
I followed the instructions given on SO e.g.
- download http://files.luaforge.net/releases/luasocket/luasocket/luasocket-2.0.2/luasocket-2.0.2-lua-5.1.2-Win32-vc8.zip
- use the following structure
> /emuhawk.exe
/Lua (untouched)
/Socket/ftp.lua,http.lua,etc.
/ltn12.lua,socket.lua,mime.lua
/lua5.1.dll
/mytest.lua

I get the following error leaving out the "core.dll" as described:

>  NLua.Exceptions.LuaScriptException:
 [string "main"]:2: module 'socket.core' not found:
	no field package.preload['socket.core']
	no file '.\socket\core.lua'
	no file 'D:\emu\BizHawk-2.2.1\lua\socket\core.lua'
	no file 'D:\emu\BizHawk-2.2.1\lua\socket\core\init.lua'
	no file 'D:\emu\BizHawk-2.2.1\socket\core.lua'
	no file 'D:\emu\BizHawk-2.2.1\socket\core\init.lua'
	no file 'd:\Program Files (x86)\Lua\5.1\lua\socket\core.luac'
	no file '.\socket\core.dll'
	no file 'D:\emu\BizHawk-2.2.1\socket\core.dll'
	no file 'D:\emu\BizHawk-2.2.1\loadall.dll'
	no file '.\socket.dll'
	no file 'D:\emu\BizHawk-2.2.1\socket.dll'
	no file 'D:\emu\BizHawk-2.2.1\loadall.dll'

If I do put the "core.dll" from the download above into the socket folder it will complain:

> NLua.Exceptions.LuaScriptException: error loading module 'socket.core' from file '.\socket\core.dll':
	%1 is not a valid Win32 application.

**Comment by zeromus** [comment]
You must also change the bizhawk setting to use luainterface instead of nlua

**Comment by udoheld** [comment]
I changed that already and the config.ini reads (for both of my release and dev versions)

> "UseNLua": false,

and when trying the current dev version it seems to pull load "LuaInterface.dll" at "EmuHawk.exe!BizHawk.Client.EmuHawk.Program.CurrentDomain_AssemblyResolve(object sender, System.ResolveEventArgs args) Line 347"
so I'd say it does that. And it should be the same for the released version.

The message is slightly different:

> NLua.Exceptions.LuaScriptException:
 error loading module 'socket.core' from file '.\socket\core.dll':
	The specified module could not be found.

**Comment by udoheld** [comment]
Ok. I noticed for dev the file structure has to be put into the "output" directory, but it now prints

> NLua.Exceptions.LuaScriptException: error loading module 'socket.core' from file '.\socket\core.dll':
%1 is not a valid Win32 application.

as well.

**Comment by zeromus** [comment]
ok, NOW the instructions on stackoverflow works.
Looks like even when you use luainterface all the errors and stuff say nlua, because lame reasons

**Comment by udoheld** [comment]
Thx, it works for me now. @zmarotrix you may want to retry the daily build.
