### ISSUE TITLE
[N64] San Francisco Rush 2049 - No Sound

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#1081]
Before moving to BizHawk 2.0, on the N64 plugins options there was the option to change Rsp Plugin, i set it to Z64 Hle Video and there is sound (But not perfect, it can be a little glitchy)

But now, on BizHawk 2.X the Rsp Plugin option is removed and i cant have sound on SFR 2049 anymore.

Also, i think this also happens for Top Gear Rally, ecept is completly muted even in Z64 Hle Video.

**Comment by NarryG** [comment]
This option was removed with the 64 bit port. I'd assume it was a compatability issue. The changelog says "Cxd64-rsp-lle plugin support dropped (possibly temporarily)"
Based on the "unofficial todo list", someone seemed to want to implement it back in for 2.3, but no idea if anyone is actually doing that or not.

**Comment by YoshiRulz** [comment]
Could not reproduce on BizHawk 2.3, OS: Win10 Home 1709.

**Comment by YoshiRulz** [comment]
@danylopez123 ping

If your sound is still broken, comment with more detail or join IRC.
