### ISSUE TITLE
Gambatte Sprites not rendering

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#1083]
To Reproduce:
Load Pokémon Red
Wait for the Introduction animation battle to begin.  Sprites glitch as attached.

This only appears to effect GameBoy games in Gambatte, not GBC Games.
Tested against:
https://github.com/TASVideos/BizHawk/commit/1f0c9f2be883ab1c9d5dc23589217cbd4248c29e

![pokemon - red version usa europe 2017-12-29 09 29 07](https://user-images.githubusercontent.com/5711691/34443016-1185ae28-ec7b-11e7-8f1f-18defbc70725.png)

**Comment by alyosha-tas** [comment]
Hmmm, actually the sprites are fine, it's the background that isn't being displayed. I'll look into it.

It only appears to effect GB games playing in GBC mode.

**Comment by alyosha-tas** [comment]
Turns out Gambatte wasn't intially able to load GB games in GBC mode at all. This capability was a side effect of having BIOS support.

Honestly, I forgot I even did that. 

So I've reverted the behaviour back to where GB games will not load in gambatte in GBC mode.
