### ISSUE TITLE
Nes Tas studio not loading/giving load errors.

### ISSUE THREAD

**Issue by GokuBlackSSJR** [TASVideos/BizHawk#1084]
When loading Super Mario bros, the game loads but when I try to open Tas studio it gives me thease issues. 
![capture](https://user-images.githubusercontent.com/24611684/34459204-ebf0e488-edb6-11e7-8dde-c9dd9a705e72.PNG)

Not sure if this will help but when I click details this is what it gives me.

Any help will be greatly appreciated.

**Comment by alyosha-tas** [comment]
Try this:

load super mario bros

In the menues go to NES -> Core -> QuickNES (click it)

then go to Emulation -> Reboot Core and reboot

This will set BizHawk to usde QuickNES, which it looks like your movie is made in.

Then try loading TAStudio again.

**Comment by GokuBlackSSJR** [comment]
Worked except I had to switch to NesHawk emulator. Thanks for the help.
