### ISSUE TITLE
[N64] GLide N64 crashes bizhawk on Intel Sandybridge GPU

### ISSUE THREAD

**Issue by Yadokingu** [TASVideos/BizHawk#1085]
Once you load an N64 ROM on an Intel Sandybridge GPU, with GLideN64 set as your graphics plugin, bizhawk crashes. Afaik there is nothing that can be done to fix this, since the OpenGL implementation on Sandybridge is shoddy, but maybe it could fail a bit more gracefully than just crashing. Maybe even prevent the user from loading an N64 ROM with this plugin when they are on Sandybridge, display an error message and fall back to a different plugin.

Bizhawk 2.2.1

Error messages here: http://tasvideos.org/forum/viewtopic.php?p=463237#463237

**Comment by YoshiRulz** [comment]
If this is a problem with the iGPU drivers, it doesn't belong here.

**Comment by YoshiRulz** [comment]
Warning users about HW support is not our problem. If you *really* want OpenGL with that iGPU, try Linux ([Intel GPU feature matrix](https://wiki.gentoo.org/wiki/Intel#Feature_support)).
