### ISSUE TITLE
Cannot speed up games

### ISSUE THREAD

**Issue by artschell** [TASVideos/BizHawk#1087]
I have been trying to speed up my game (SMB1) to go faster than 100% speed, but the emulator will not go above 60fps. I've tried everything I know of - unthrottled, turbo, and normal speed change. Everything just sets the speed at 100% or 60 frames per second. I can use these speed features to slow down the game. Is there a setting somewhere for frame limiting?

**Comment by alyosha-tas** [comment]
NESHawk is slow. It's possible it's already goiing as fast as it can go.

The other core in BizHawk is QuickNES. 

Load the game, and then in the menues go to NES -> Core -> QuickNES

Then in the menues go to Emulation -> Reboot Core

It should now say 'QuickNES' at the bottom of the BizHawk winbdow.

Try changing the speed now.

**Comment by alyosha-tas** [comment]
I can't find any actual bug here, so closing. Feel free to reopen if you are having trouble even with QuickNES

**Comment by artschell** [comment]
When I open the emulator, it says "Unable to open QuickNes, using NesHawk instead".

**Comment by alyosha-tas** [comment]
That means your game is unsupported by QuickNES (it has limited mapper support and is a bit glitchy.)

Looks like you are basically stuck at 60 fps. 

Another fast core is gambatte, maybe try some GameBoy games and see how fast you can get them to run? It should be a few thousand fps.
