### ISSUE TITLE
Update GlideN64 to the latest release

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#1089]
The release is very recent, no commits ahead of it, it makes a lot of sense to update to that for the next bizhawk release too, because stability:
https://github.com/gonetz/GLideN64/releases/tag/Public_Release_3_0

Their master is equal to that release so far.

**Comment by omgatree6** [comment]
I would like this too.
I've been having some issues TASing with GlideN64 related to frame buffer emulation.  The release notes for the latest version say they made some major modifications to frame buffer emulation, so I'm hoping that might help.

**Comment by Yadokingu** [comment]
Thirded, especially since it seems to fix some problems with Majora's Mask.

**Comment by vadosnaprimer** [comment]
Done.
