### ISSUE TITLE
TAStudio : annoyance with follow cursor

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#1090]
When TASing with follow cursor open, (and follow cursor in middle) it makes small adjustments impossible since the cursor will auto update. thus is you need to add *one* button press, you need to undo the option each time. Otherwise, the auto update will make you press a string of button. Since the frames is dragging with the auto update.

The fix would be to update the things when we release the button on the mouse.

**Comment by vadosnaprimer** [comment]
You're using "Always Scroll"?

**Comment by vadosnaprimer** [comment]
Tell me if it helps.
