### ISSUE TITLE
How do I use this on Mac?

### ISSUE THREAD

**Issue by theandrewk27** [TASVideos/BizHawk#1092]
I am a fan of old games and would like to run Bizhawk and the RTC on my mac, but I am having to go through a painfully long (and what I think is unnecessary) install process for something that doesn't even come with NESHawk and the other stuff (I may have unknowingly downloaded a bootleg but who knows?). Could someone please help me solve my predicament?

**Comment by Sappharad** [comment]
Download 1.13.1 here:
http://tasvideos.org/forum/viewtopic.php?t=12659&start=175
When you try to run it, it will prompt you to install Mono if you don't already have this.

NES, FDS, SNES, SMS, Game Gear, PCE/TG16, Atari 2600, Atari 7800, Atari Lynx, ColecoVision, Genesis/MegaDrive, Sega CD, Gameboy, Gameboy Color, GBA, Wonderswan are all supported. In that version, N64 and Saturn were the only two systems available on Windows and not supported on macOS, if I recall correctly.

I don't know what RTC stands for.

**Comment by lsthiros** [comment]
If you are interested in building on Mac, follow these steps:

1. First download Visual Studio For Mac (formerly Mono Develop)
2. Switch to the mono-portable branch
3. In the project root, run this one-liner on the terminal to remove the WINDOWS designations from the project file: sed -E "s/(<DefineConstants>[A-Z0-9;]*);WINDOWS/\1/" $(find . -name \*.csproj)
4. Build and run the BizHawk.sln project in visual studio

You will still need to compile each core separately, and place it in the 'dll' folder. I have been able to successfully run the SNES emulator using libsnes after compiling the core with the included Xcode project.

**Comment by Sappharad** [comment]
You shouldn't need to do step 3.
1.13.1 was built from the branch as-is, the pre-processor directives are set up to ignore WINDOWS when it is supposed to be ignored. The only exception is the 64-bit build configuration, which wasn't set up correctly because 64-bit isn't supported by WinForms on macOS.

**Comment by lsthiros** [comment]
I must have had it set to an incorrect target when I was originally building the solution. I removed the incorrect portion of my response.

**Comment by theandrewk27** [comment]
Thx, I'll give it a shot. Btw Sappharad, RTC stands for Real Time Corruptor.

**Comment by theandrewk27** [comment]
This is still open because I will not close this until I can verify that the solution worked.

**Comment by theandrewk27** [comment]
@Sappharad It works! not how do I run games?

**Comment by Sappharad** [comment]
Open ROM from the File menu?
If it's a newer system like PSX, you have to configure Firmware first from the firmware dialog.

**Comment by NarryG** [comment]
The "RTC" he's referring to is the Real Time Corrupter Mod, a modification for Bizhawk designed for corrupting games,

theandrewk27, [as we told you over at your issue on the repo for the Real Time Corrupter](https://github.com/ircluzar/RTC3/issues/5) it doesn't support Mac.  While there are builds of stock Bizhawk which support Mac, there's platform specific code in the RTC mod so we can't build it for Mac.

**Comment by Sappharad** [comment]
Closing this, since you can still reply once it is closed. Typically the issue tracker is for reporting bugs, not asking how to use the software.

**Comment by theandrewk27** [comment]
got it. I will turn to the wiki.
