### ISSUE TITLE
mGBA soft reset desync for Golden Sun, Fire Emblem, possibly other games as well

### ISSUE THREAD

**Issue by ruadath** [TASVideos/BizHawk#1101]
To see the issue, try running the attached file for the japanese version of golden sun. You will get a desync a bit past frame 50000 when trying to load the game after saving and performing a soft reset.

However, if at any point before the soft reset you create a save state and then try and run from the save state, you will not desync. This makes it quite difficult to TAS, since getting the reset to behave correctly requires syncing from the beginning of the movie every time a change needs to be made.

Hopefully someone can figure out what is causing this issue and provide a fix! From what I can tell, the desync just appears to affect the boot up time of the console after the soft reset

[Ougon no Taiyou - Hirakareshi Fuuin (Japan).zip](https://github.com/TASVideos/BizHawk/files/1648645/Ougon.no.Taiyou.-.Hirakareshi.Fuuin.Japan.zip)

**Comment by vadosnaprimer** [comment]
Why closed?
