### ISSUE TITLE
BizHawk doesn't Start on Windows 10

### ISSUE THREAD

**Issue by danielh05** [TASVideos/BizHawk#1102]
I am trying to make a tas in BizHawk but every time i try to start it nothing happens, i am on the newest version. Any help would be nice

**Comment by synnae** [comment]
Have you downloaded and ran the Prereqs first?
https://github.com/TASVideos/BizHawk-Prereqs/releases

**Comment by danielh05** [comment]
oh my god i didnt even know this existed, thanks man
