### ISSUE TITLE
Wonder Boy in Monster World Korean BIOS (Master System)

### ISSUE THREAD

**Issue by The8bitbeast** [TASVideos/BizHawk#1108]
gamedb forces Wonder Boy in Monster World to use European BIOS rather than Korean BIOS. Korean BIOS is the only legitimate way to play this game on NTSC.

Also would it be possible to add Korean BIOS in the menu with Export and Japan?

**Comment by alyosha-tas** [comment]
Added korea to region selection. Keeping ROM designation in the DB unchanged though.
