### ISSUE TITLE
PXM converter problems

### ISSUE THREAD

**Issue by cleartonic** [TASVideos/BizHawk#1109]
I believe PXM converter does not work properly in Bizhawk version 2.2.1. 

Steps taken: 
Downloaded .pxm file (tasvideos.org/2626S.html) 
Loaded .cue into Bizhawk for game 
File -> Movie -> Import Movies... 
Loaded .pxm file, .bk2 was created 
Opened TAStudio, loaded .bk2 

I then opened the .pxm file in TAS Movie Editor and compared to what was in TAStudio (the newly created .bk2 file) 

The below album shows the discrepancies 

https://imgur.com/a/EMXpO 

I don't know much about this conversion process but I attempted to find any semblance of a pattern among the two files- I didn't find any

**Comment by alyosha-tas** [comment]
I think I fixed it. @cleartonic please try it in the dev build and make sure.

**Comment by cleartonic** [comment]
This worked. Thank you very much @alyosha-tas
