### ISSUE TITLE
Add mGBA Tools > Game Overrides as a Sync Setting

### ISSUE THREAD

**Issue by ProjectRevoTPP** [TASVideos/BizHawk#1112]
Reduces a lot of headaches for getting homebrew, rom hacks, and other such things working immediately for little effort without modifying the game database.

**Comment by YoshiRulz** [comment]
https://github.com/TASVideos/BizHawk/blob/143c172cf0143efa6e535afb0be754938d91abb8/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.cs#L146-L149

Nothing in [gamedb_gba.txt](https://github.com/TASVideos/BizHawk/blob/143c172cf0143efa6e535afb0be754938d91abb8/Assets/gamedb/gamedb_gba.txt) uses `mgbaNeedsOverrides=1`. If you're overriding something to get a homebrew title working then you'd be adding your own gamedb entry anyway; what purpose does the extra UI serve?

**Comment by hegyak** [comment]
@YoshiRulz I think the user is looking for a way to modify the Sync Settings outside of the GameDB file.  

Example:
Pokemon Liquid Crystal (A hack of Pokemon Fire Red) can run in mGBA but you need to enable a particular save type to actually save in game.  The game also can use a Real Time Clock for features in the game.  Both of these are Sync Settings.

**Comment by hegyak** [comment]
Further thoughts on this:

Making a Quick GUI for this may be what we need here.  Probably a drop down ComboBox for Save Type, a Check Box for RTC.  I don't know if FlashSize needs to be set as well.  Proably does, but I don't know the options that are needed off the top of my head.  I also think using the NeedsOverrides is necessary for the GameDB.

The GUI would give the user options they can set for the currently loaded ROM file, and then when the user saves those options, the GUI will put those settings and the ROM's Hash into the gamedb_user.txt file.  This should only be necessary for GBA ROM files?

Potential issues:
There needs to be a way to confirm the gamedb_user.txt file exists, and that the entry is not being duplicated.  Using the Game's Hash should help with some of those issues.

Example of my Pokemon Liquid Crystal GameDB_User Entry:
[gamedb_user.txt](https://github.com/TASVideos/BizHawk/files/2833196/gamedb_user.txt)

That is the settings that Pokemon Liquid Crystal expects/needs to run properly in BizHawk.

I may get some time and set the GUI and writer up myself and make a Pull Request.  I could in theory just push my changes but rather have it get checked over and done up nice.

**Comment by YoshiRulz** [comment]
...what

**Comment by RetroEdit** [comment]
This is probably not high-priority, unless someone can come forth with a compelling rationale for needing this. Most games should work, but some ROM hacks may have problems. mGBA's detection heuristics should work well.

It is a feature that upstream mGBA has that we're lacking. The title is confusing because it refers to a menu item in mGBA's Qt frontend.

**Comment by endrift** [comment]
It would be useful for Pokemon Ruby/Sapphire runs which sometimes use a dead battery intentionally for RNG reasons. Other than that there's no major use for it.

**Comment by RetroEdit** [comment]
@endrift I think the dead battery support specifically is a different issue, #1870. I was more referring to save type detection.

**Comment by endrift** [comment]
Ah. mGBA lumps save type overrides in with additional cartridge hardware into the same "overrides" settings.
