### ISSUE TITLE
[N64] Crash While Loading mupen64plus.dll

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#1114]
As of https://github.com/TASVideos/BizHawk/commit/1ff0cc1e0ca86da198b298cb1973fe3741e248ac mupen64plus.dll was recompiled using the VC++ 2012 runtime (previously 2010), but the 2012 runtime is not included in the BizHawk prerequisite installer.

If a user is unlucky enough not to have it installed by some other program on their system, BizHawk 2.2.1 and interim as of https://github.com/TASVideos/BizHawk/commit/3ed707b703aef51d6ac3185fdfb62cf5d83e89d5 will crash while loading mupen64plus.dll with a less than helpful error message

**Comment by vadosnaprimer** [comment]
@zeromus I was absolutely unable to even launch bizhawk without 2012 runtime, no matter what and how I rebuild or how far back I check out. It's needed in the prereqs indeed.

**Comment by zeromus** [comment]
I have a test build of an installer with 2012 for either of you to test, find me on irc

**Comment by Isotarge** [comment]
I have tried the test build of the updated prerequisite installer and can confirm that it installed the 2012 runtime successfully on a system without it.

**Comment by zeromus** [comment]
ok, posting new prereq installer to fix
