### ISSUE TITLE
mapper iNES #124 (Super Game Mega Type 3 Pirate arcade board)

### ISSUE THREAD

**Issue by alphadeltabravo** [TASVideos/BizHawk#1117]
Add it to Bizhawk, guys.

Documentation about it, files, rom etc. can be found in description of this video
https://www.youtube.com/watch?v=re9O388mtJU
http://blog.kevtris.org/blogfiles/Super%20Game%20Mega%20Type%20III.rar

**Comment by alyosha-tas** [comment]
I added this to the existing issue of NESHawk's missing mappers / boards. (#860)

Pirate boards like this are pretty low priority though so probably won't be worked on any time soon.
