### ISSUE TITLE
Lua with TAStudio (two host threads bug)

### ISSUE THREAD

**Issue by Azreally** [TASVideos/BizHawk#1119]
Hi,

When I worked with lua script and TAStudio I get this error message (in lua console next screen):

![lua_tastudio_2_host_threads_bug](https://user-images.githubusercontent.com/36796272/36632434-747d19b6-193b-11e8-823f-855c1aef7c36.png)

In lua console I saw this error:

![lua_console_error_message](https://user-images.githubusercontent.com/36796272/36632550-bf94b5b6-193c-11e8-9214-3b1168e588a2.png)

Description the steps:
When you run a rom just run lua script (could be a simple script, it should be running all time). Next run TAStudio and insert 1000 frames (should be white frames). Scroll down to the end (best way) and click exactly the same as the first screen shot.

That's all.

P.S. I using this emulator version:

![bizhawk_ver](https://user-images.githubusercontent.com/36796272/36632738-3edb3668-193f-11e8-86fd-d9255a424c93.png)

Best regards,
Azzy

**Comment by vadosnaprimer** [comment]
Switching to luainterface doesn't fix this, right?
config - customize - advanced

**Comment by Azreally** [comment]
Yes, the same problem :(.

**Comment by Azreally** [comment]
This script should reconstruct the problem:
[lua_GBA_crash_test_script.zip](https://github.com/TASVideos/BizHawk/files/1755832/lua_GBA_crash_test_script.zip)

**Comment by Azreally** [comment]
Something "more" known about this bug right now?. Any progress on this? This issue blocks working with lua and TAStudio.

**Comment by vadosnaprimer** [comment]
If there was progress, we would tell you. Will hopefully fix this within a week.

**Comment by vadosnaprimer** [comment]
@zeromus I don't understand what's wrong with this. Letting it run for a few frames and then sending emulation to any frame within the movie (with turbo seek on) causes this exception. But it indeed happens on the lua side, and the error is too cryptic.

**Comment by vadosnaprimer** [comment]
@Azreally you can work around this is you disable running scripts during turbo, in customize dialog.

**Comment by Azreally** [comment]
It possible to fix that bug anyway? Maybe I'll ask Xadro to fix this? (I hope that he'll).

**Comment by vadosnaprimer** [comment]
It's not fixed???
