### ISSUE TITLE
AviWriter AviDump issue

### ISSUE THREAD

**Issue by Valis77** [TASVideos/BizHawk#1120]
Whenever i tried to use aviwriter it crashes bizhawk. My default codecs is Techsmith and the video compression wont display it would crash the emulator.

the other ones do work but i don't wanna use them for my dumping.

**Comment by nattthebear** [comment]
What's the error message?

**Comment by Valis77** [comment]
https://www.youtube.com/watch?v=JBDLwjqAWUM&feature=youtu.be i'll show you via youtube.

**Comment by nattthebear** [comment]
It's unlikely we can do anything for that.  At this step, Bizhawk is just asking VFW to show the codec selection dialog; there's not much we can do if you have some codec installed that is barfing at that step.

**Comment by Valis77** [comment]
I see then i'll just gave to use that other method; the ffmpeg codecs which is ok so until them i'll stick to that.

**Comment by nattthebear** [comment]
If you're interested in investigating it, you could look at all of the 64 bit VFW codecs you have installed:

In regedit, go to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Drivers32 and look for all names that start with "VIDC" (any case).  One of them is probably your issue.

**Comment by vadosnaprimer** [comment]
Yeah it will probably not be able to _use_ the plugin that crashes it, but it'd be nice if we could prevent the crash itself.

**Comment by nattthebear** [comment]
How would you recommend we do that?  We're just calling AviSaveOptions

**Comment by Valis77** [comment]
Ok! i found all vidc codecs you mentioned. How do i know which ones are the cause of the problem?

**Comment by Valis77** [comment]
OMG! I found it! NVM i fixed the problem like you said there was a 64.dll files i removed and it fixed the problem. Thanks!

**Comment by nattthebear** [comment]
Can you tell us the exact name of the dll that was causing an issue?  This might help us with future users.

**Comment by Valis77** [comment]
Sure thing. https://www.youtube.com/watch?v=InQalmWSugw here my video on this matter and how i fixed it.
 it's vidc.1420 (lvcod64.dll) <--- Yeah somehow that codecs

**Comment by nattthebear** [comment]
Logitech ships garbage?  Whoda thunked it.  Looks like we aren't the first ones with a problem:

https://github.com/opentoonz/opentoonz/issues/46
https://community.logitech.com/s/question/0D55A00006yWZUfSAO/lvcod64dll-causing-crashes-in-obs-c920

Since your issue is resolved I doubt any mere mortal could ever make Logitech do... well, anything, closing.

**Comment by Valis77** [comment]
thanks?
