### ISSUE TITLE
Context menu in Lua Functions window

### ISSUE THREAD

**Issue by Azreally** [TASVideos/BizHawk#1122]
Hi,

I wanna to introduce my concept about new functionality in "Lua Function" window.
I think that my descripted steps are easily to understand (probably not,... hehe). Okey let's started!.

When windows shows just select first one record from function list. Next click RPM (right press mouse button) on selected item and now should shows context menu with item _**"Copy"**_. This _**"Copy"**_ item means that in clipboard should be stored selected function with example like eg.:
For **GBA rom** and selected item **joypad.set( ... )** (from list) I suggest that copied data (in clipboard), should looks like this: 

`joypad.set( [ "A" ] = true, [ "B" ] = true );`

(for this example I mean)
This feature will help ya with making lua scripts (I guess..).

eg:
![context_menu_in_lua_func_wnd_by_rpm](https://user-images.githubusercontent.com/36796272/36640161-bc540d7e-19ce-11e8-983a-b3bf5fd407fc.PNG)

Thanks, a lot! and have a nice day.

**Comment by zeromus** [comment]
It's a decent idea and easy to implement.
However in the given example it really should look like this:
```
//note: use this mechanism to determine what buttons are available first
//(code snippet to print all buttons)
joypad.set( [ "A" ] = true, [ "B" ] = true );
```

**Comment by Azreally** [comment]
Ye, you right this should be universal mechanism for all supported platforms I think. So I give u a examples for all functions but you have to make mechanism that will add parameters right the current opened core is.

**Comment by zeromus** [comment]
No, the parameters will not be right for the current opened core. _That_ is not going to happen. Read what I wrote in the comments carefully. I said we should give the user a way to find out what the parameters should be.

**Comment by Azreally** [comment]
I can't add files to the project, there is a problem (I made new branch):
> remote: Permission to TASVideos/BizHawk.git denied to Azreally.
> fatal: unable to access 'https://github.com/TASVideos/BizHawk.git/': The request
> ed URL returned error: 403

**Comment by zeromus** [comment]
it's git. You must do more paperwork. Fork it and add the file in your fork.

**Comment by Azreally** [comment]
So, now I can simply close issue?

**Comment by zeromus** [comment]
No, because this PR is no good. This autogenerated string full of garbage parameters as a template for calling the function is messy, not scalable, and doesnt work in every case. Does it even give useful results for the joypad.set case? I can't double check it right now because github isn't working.  The proper way to do this is with documentation written by a human on each and every lua function.

**Comment by Azreally** [comment]
Okay. I think that I know how to do it myself I guess. I'll clean last changes and try make it in different way.

**Comment by Azreally** [comment]
About **joypad.set**, I know that it works with all cores I guess (you can check it yourself).

**Comment by Azreally** [comment]
How about that?. Sorry if I failed in some cases, but I don't have enough knowledge to correct them all. Now I have to ask you to implement mechanism into emulator to do.

Here is a list:
[func_eg_list.txt](https://github.com/TASVideos/BizHawk/files/1777960/func_eg_list.txt)

**Comment by zeromus** [comment]
ok, it seems like you have the right idea. But youll be entering these into the c# files yourself. I will be editing the code so you have a way to enter it into c# and showing you examples. Give me seven days or less.

**Comment by Azreally** [comment]
I'll make my own branch and I'll add cs file into it. Next using commit and pull request (I guess), I will pass the source code to you. Can I add this examples into a table?

**Comment by zeromus** [comment]
What you do with that table is up to you. I'm not using it. You'll be entering these into _existing_ c# files

**Comment by Azreally** [comment]
But still I don't know how to fix some cases like:

> __emu.disassemble__%%%

> * object emu.disassemble(uint  pc, ["Name" = ])

> * Returns the disassembly object (disasm string and length int) for the given PC address. Uses System Bus domain if no domain name provided

**Comment by zeromus** [comment]
Yes, that, precisely. This is more work than the automatic example generation he made, his stuff was not acceptable, so it doesn't matter. This is the only acceptable way to do it.

Keep in mind that entering a multi-line example may be kind of.. massively ugly. We may want to make a new attribute for examples so that you can do this:

[LuaMethod("name", "a long description")
[LuaMethodExample("Line one")]
[LuaMethodExample("Line two")]
void name() {}

**Comment by zeromus** [comment]
"fix"? what's there to fix? I dont see anything special about this.

**Comment by Azreally** [comment]
or it this:

> __joypad.setfrommnemonicstr__%%%

> * void joypad.setfrommnemonicstr(string inputlogentry)

> * sets the given buttons to their provided values for the current frame, string will be interpretted the same way an entry from a movie input log would be

**Comment by zeromus** [comment]
or in what? whats special about this? I dont see anything special about this. What does %%% mean?

**Comment by Azreally** [comment]
I mean in examples, how to add special example in this case. Something like this enough?:

> joypad.setfrommnemonicstr( "Input log entry name" );

**Comment by zeromus** [comment]
that's your problem, not mine, but that looks pretty pathetic. it seems obvious to me it should be an example taken from an actual working script, NES for instance

**Comment by Azreally** [comment]
I see, I preferred to ask you before I add (about your conception about this cases).

**Comment by Azreally** [comment]
Okay, what you think about this:
![new_class](https://user-images.githubusercontent.com/36796272/36943991-e7dbbde2-1f47-11e8-815a-701205035958.PNG)

and next step by step (right that):
![like_this](https://user-images.githubusercontent.com/36796272/36943998-f844ac16-1f47-11e8-9698-985bfc993a46.PNG)

**Comment by Azreally** [comment]
If it will be okay. I'll make it for all.

**Comment by Azreally** [comment]
Okay. I add last one in this branch: https://github.com/Azreally/BizHawk/tree/Azzy. Some cases don't have any information how to use, so I skipped it.

**Comment by zeromus** [comment]
OK, I've finished merging all this stuff. A lot of the examples are of dubious quality, but now that the stuff is all merged, we can tidy them up as we go

**Comment by Azreally** [comment]
Some examples should be repaired yet. My next commit will be contains notes and next examples by new documentation (mainly TAS functions). When all functions will looks good, I send to you next pull request.
