### ISSUE TITLE
Autofire Hotkey broken

### ISSUE THREAD

**Issue by Tompala** [TASVideos/BizHawk#1126]
With BizHawk 2.2, the Autofire hotkey will be displayed the same on the input display as if you were using Autohold, making it impossible to tell which frame the button is being pressed on, though it's still active. The HUD text will also have the same text displayed, despite one button being Autofire and the other Autohold
![autofire](https://user-images.githubusercontent.com/37029172/36940147-b61a9986-1f3d-11e8-94f8-602b0f68ee94.png)

If you start up TAStudio, Autofire will stop working completely and have the same function as Autohold.

Furthermore, to make the Configure Hotkeys nicer, Autofire should be moved to be next to Autohold and Clear Autohold; which should probably be renamed to Clear Autohold/Autofire or similar.
![hotkeys](https://user-images.githubusercontent.com/37029172/37218250-29ba9d42-23c0-11e8-9c56-80dcca0db83e.png)

**Comment by vadosnaprimer** [comment]
I grouped them together in the dialog, but failed to fix the main bug.

**Comment by vadosnaprimer** [comment]
@Tompala test latest dev build please!
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Tompala** [comment]
Seems to be working fine!
