### ISSUE TITLE
Unable to poke more than 500 bytes above 0x4020 in the NESHawk System Bus

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1127]
NESHawk uses game genie cheats when poking any address above 0x4020
`else
{
	ApplyGameGenie(addr, value, null); //Apply a cheat to the remaining regions since they have no direct access, this may not be the best way to handle this situation
}`
There's a hard limit on the number of cheats applied through ApplyGameGenie()
`public int[] cheat_indexes = new int[500];`

Could this limit be raised to allow for more than 500?  I don't see any real reason to limit it at 500 when the domain itself is 64k

**Comment by alyosha-tas** [comment]
What is the use case here?

I originally put that in as a stop gap so cheats would turn off properly once disposed of. I guess there is no reason not to raise the limit, but maybe there is a better way.

**Comment by NarryG** [comment]
Practical use case: none.
Entertainment use case: memory corruption

I was hoping to be able to work entirely on the bus rather than with the separate domains so I could use pre-existing game genie codes to seed some addresses

**Comment by alyosha-tas** [comment]
Ok I raised the cap to include the entire bus size (0x10000) since this doesn't affect performance as long as no cheats are active. Just be warned that as you add higher numbers of cheats things might slow down.
