### ISSUE TITLE
A7800Hawk: Jr. Pac-Man is completely broken

### ISSUE THREAD

**Issue by Techokami** [TASVideos/BizHawk#1129]
So, there's a homebrew game for the Atari 7800, [a really stellar port of Jr. Pac-Man.](https://atariage.com/store/index.php?l=product_detail&p=899) I decided to try and play it in BizHawk tonight. Last time I played a 7800 game, the core was EMU7800, and it properly played the game. Now the core is A7800Hawk, and...
![jr pac-man 2018-03-09 21 46 20](https://user-images.githubusercontent.com/1530728/37237629-f13d4cd4-23e3-11e8-927c-ba9eaa62cb29.png)
This is not how the game should look. Or play, since the player and the ghosts cannot move much in the jumbled mess.

**Comment by alyosha-tas** [comment]
fixed. thanks for the report

**Comment by Techokami** [comment]
Awesome, thank you!
