### ISSUE TITLE
Can't load savestates made with GBC bios

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1135]
Open a GBC game, enable bios, restart core to make the changes effective, then play and save a state. If you close and re-open BizHawk, attempting to load that savestate will result in a crash, even with TAStudio states or if trying to play a save-anchored movie. This bug is not encountered unless you close BizHawk after having saved the states or saved the progress of your .tasproj file.

**Comment by alyosha-tas** [comment]
Is this using the Dev Build? Enabling BIOS isn't even an option anymore and all such issues should be resolved.

**Comment by ThunderAxe31** [comment]
Indeed, the interim does not have this bug.
