### ISSUE TITLE
RAM Watch window doesn't keep custom column setting anymore

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1137]
In 1.11.9.1 if you sort, resize, remove, add columns and then close and reopen BizHawk you will have them exactly as they were left. In 2.2.1 this stopped working: now it will reset any change every time you close the program.

**Comment by alyosha-tas** [comment]
RamWatch.cs line 82:

public ColumnList Columns { get; }

It used to be { get; set; } but the 'set' part was removed in 8f3d161.

I don't know why, typo? Any reason not to restore the 'set' to make this work again?

**Comment by ThunderAxe31** [comment]
I asked adelikat and told me it's a mistake, and it can be restored right away.
