### ISSUE TITLE
FPS all of a sudden lower?

### ISSUE THREAD

**Issue by ThatAnonymousGuy1** [TASVideos/BizHawk#1139]
Been playing a game boy title for the past couple of weeks. It's played just fine at 60fps. Today the game just randomly decided to start capping at 45fps. I checked some other games (SNES) and it's also capping at 45fps (used to get 60fps on everything too). I made no changes to the settings and not sure where to even begin looking. Any suggestions?

**Comment by Asnivor** [comment]
Check the bizhawk display settings and make sure your client hasn't switched to GDI+ mode somehow (default is D3D).

This was the problem I had a couple of days back.

**Comment by ThatAnonymousGuy1** [comment]
D3D9 is still selected. Even when I go in and select something else and then back to D3D it still shows 45fps.

**Comment by Asnivor** [comment]
an exactly 25% drop is suspicious. goto menu config > speed/skip and make sure 'speed' is not set to 75%.

Even if it is set to 100%, change it to something else, then back to 100%.

**Comment by ThatAnonymousGuy1** [comment]
@Asnivor That was the problem. No clue how it got set to 75%. Works just fine now. Is there maybe a keyboard shortcut that I inadvertently hit to change this?

**Comment by ThunderAxe31** [comment]
There is a keyboard shortcut indeed. Go in Configure Hotkeys and check Increase Speed and Decrease Speed.

**Comment by ThatAnonymousGuy1** [comment]
@ThunderAxe31 found it. I know what I did now to change the game speed. Thanks again to you and @Asnivor for your help!
