### ISSUE TITLE
Gambatte requires bios despite previous commit implying it should no longer support bios

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1148]
According to this commit, Gambatte shouldn't be using the bios at all 
https://github.com/TASVideos/BizHawk/commit/c18298c8a5915abc5abefb3fb2420259e464cead

As of 2.2.2, Gamebatte is FORCING the bios rather than leaving it as an option. If you don't have the file in place, it refuses to launch.

**Comment by alyosha-tas** [comment]
That's an old commit, current version of gambatte and GBhawk do force BIOS loading. Maybe in the future an option can be added back for BIOS optional. At the moment I'm not sure how practical it is though.
