### ISSUE TITLE
[TAStudio] Marker & Branch Control Scaling Issues on High-DPI Screens

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#1151]
Resolution: 1920x1080
Screen size: 14"
Windows text scaling setting: 125%

![tastudio_dpi](https://user-images.githubusercontent.com/6367891/37639470-6c540aa4-2c61-11e8-99da-d7d5cf4a4217.png)

The branches & markers controls don't appear to be scaling or anchoring properly on this machine. Oddly enough, changing the text/app scaling setting to 100% doesn't seem to fix it either (see second screenshot). Maybe there's a secondary scaling setting in the original control panel I'm missing or something, Windows 10 is pretty cryptic with this stuff.

![tastudio_dpi_100](https://user-images.githubusercontent.com/6367891/37639476-7541b292-2c61-11e8-9f65-dd49b40db5ff.png)

**Comment by vadosnaprimer** [comment]
This is exclusive to _some_ win10 machines, and we don't know yet which setting is to blame. If you somehow manage to find a fix for it that doesn't break other users, I'd greatly appreciate it. I can't, since I don't have win10.

**Comment by Asnivor** [comment]
@vadosnaprimer might be something to do with this maybe:

https://blogs.windows.com/buildingapps/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/

**Automatic DPI scaling for dialogs**

Win32 dialogs (dialogs that are created from a dialog template via the CreateDialog* functions) did not DPI scale previous to the Creators Update. 
With PMv2 these dialogs will automatically DPI scale when the DPI changes. **If any of your dialog layout is controlled by code you’ll need to make sure that your code doesn’t conflict with the automatic scaling that is being done by Windows. You can use the SetDialogControlDpiChangeBehavior and/or the SetDialogDpiChangeBehavior APIs in this case to tell Windows how you’d like it to handle DPI scaling of your controls or of the whole dialog**.

**Comment by vadosnaprimer** [comment]
Thank you. I can't work on it right now though. @adelikat probably?

**Comment by vadosnaprimer** [comment]
There's another weird thing that looks related to how font is measured?

![Capture](https://user-images.githubusercontent.com/7092625/72386811-22819980-3733-11ea-91c2-d0abd7474144.PNG)

@jdpurcell do you have any ideas?
