### ISSUE TITLE
client.unpause_av() crashes the emu

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#1154]
As seen in [this thread](http://tasvideos.org/forum/viewtopic.php?p=467389#467389), when trying to resume A/V capture with **client.unpause_av()** the emu crashes, with the following reports:
![](https://i.imgur.com/AmcZoud.png)

I used this script with Yoshi's Island (Snes) in BizHawk v2.2.2 to reproduce this crash, it should pause the recording when I pause the game and resume the recording when I unpause it 
```lua
local prevent_1st_frame = true
local is_paused_prev -- to call client.pause_av()/unpause_av() only once when pausing/unpausing the game
local is_paused

while true do

  is_paused = mainmemory.read_u8(0x0B10) == 1 -- Yoshi's Island (Snes) pause flag

  if not prevent_1st_frame then
  
    if is_paused and is_paused ~= is_paused_prev then
      client.pause_av()
    end
    
    if not is_paused and is_paused ~= is_paused_prev then
      client.unpause_av()
    end
    
  end
  prevent_1st_frame = false
  
  is_paused_prev = is_paused
  
  emu.frameadvance()
end
```

**Comment by vadosnaprimer** [comment]
If the emu is already paused, why pause av? Also, does it die the same with normal avi capture?

**Comment by brunovalads** [comment]
> If the emu is already paused,

The emu is not paused, the game that is, in this case, but this is irrelevant anyways. The crash occurs when you resume AV recording with `client.unpause_av()`. You can test that with any game just by doing this:
```lua
client.pause_av()
print("Paused!")
client.unpause_av()
print("Unpaused!")
```
This will reach the end (printing "Unpaused!" in the console), but will throw that exception.

> Also, does it die the same with normal avi capture?

There's is no command to **Pause** the AV recording, just a "Stop".

**Comment by vadosnaprimer** [comment]
Both scrip[ts work perfectly on my end (aside from the fact that the address is 0x0B12.

**Comment by brunovalads** [comment]
Hmmm it's "working" with AVI writer, not FFmpeg writer (at least for me in v2.X). By "working" I mean it doesn't crash, but the recording just freezes a frame instead of cutting out the paused part.
Also, I checked with v1.13.1 and FFmpeg writer works with this script (v2.2.2. doesn't, it crashes like the images I sent).

**Comment by YoshiRulz** [comment]
@brunovalads ping

If you ever reproduce this, comment with more detail or join IRC.
