### ISSUE TITLE
ZX Spectrum: ZXHawk bugs

### ISSUE THREAD

**Issue by Asnivor** [TASVideos/BizHawk#1158]
Pre-release bug tracking and wip features.

**Core Issues**

- [x] Beeper implementation has gone wrong somewhere. Playback is slower than it should be and lower in frequency

- [x] Better TZX file detection needed (so that errors in parsing do not just get ignored and the tape isn't just serialized as TAP format)

- [x]  Some TZX images throwing exceptions when serializing - examples: Operation Wolf & Operation Thunderbolt. Both use the 'Paul Owens' loading/protection scheme so this might have something to do with it.

- [x]  Implement correct parsing (if not implementation, just block length) for ALL valid TZX blocks. Some are still missing

- [x] Emulated TapeDevice should be separated from the normal (ear) beeper device (like it would be on a real spectrum). This would lead to more accurate tape timing emulation.

- [x]  Contended memory timings not accurate

- [x]  Floating memory bus implementation not accurate (although may be once contended memory is fixed)
- [x]  Hard/Soft reset client menu options still greyed out

- [x] Tape AutoLoad mode should be a sync setting

- [x] AY-3-8912 volume control does not work correctly with values under 50

- [x] Has been reported that tape auto-load mode if forced when recording a video

- [x] Reported that when switching tapes the first block is skipped on the new tape (in auto mode)

- [x] After recording a movie the movie details pane shows 60FPS rather than 50 - https://i.imgur.com/ttXOrlL.png

- [x]  +3 floppy controller and disk emulation

**Reported software glitches**

- [x]  Power Drift (on 128k machine) text corruption after first championship completed

~~- [ ] Wonderboy (128k) gfx corruption at Area1 Lvl4~~ (not emu issue. same happens in FUSE - https://i.imgur.com/ttLEXgU.png)

- [x] ZX Spectrum 128k: "The Deep" Demo (2018) not rendering correctly

- [x]  Top Gun (spain) locks up after pressing fire to start

- [x]  Star Farce (48k) not showing title screen checkerboard border effect

- [x] Altered Beast (Europe).tzx - Stage2 - character moves by himself with no keypresses

- [x] Beeper audio in Oriental Hero is off for some reason

**Tape Media Issues**

- [x] Golden Axe 128k TZX loading not completing

- [x] Throws exception when parsing the tape image: Live and let die tzx, Red Heat tzx

- [x] Exception thrown when launching Op. Wolf tap file

**Disk Media Issues**

- [x]  Castlevania (Spectral Interlude) dsk - game hangs on start (because UPD write commands are not yet implemented)

- [x]  Iron Lord stalls after title screen

- [ ]  Shadow of the Beast fails to load

**Potential things to do post-release**

- [ ]  +3 disk drive timing emulation

- [ ]  +3 disk controller persistent write operations & SCAN functions

- [ ]  Pentagon clone emulation

- [ ]  Beta disk / TRDOS emulation

- [ ]  DISCiPLE Interface

- [ ] Pentagon gigascreen mod emulation

- [ ]  Currah MicroSpeech implementation

- [ ]  Kempston Mouse

- [ ] Multiface emulation

**Comment by vadosnaprimer** [comment]
Did I just accidentally screw up some checkboxes? O_O

**Comment by Asnivor** [comment]
Nope, was just a dose of the strikethrough overkill.

Meh.

**Comment by Asnivor** [comment]
Core is now released. Will deal with any bugs etc as they come in.
