### ISSUE TITLE
TAStudio input dropping frames

### ISSUE THREAD

**Issue by cratty79** [TASVideos/BizHawk#1162]
Hello! The TAStudio tool has a problem where it drops a frame, messing up the TAS I make. It happens around 30 seconds from bootup of the game. I can give any information you need, just ask. But thanks!

**Comment by vadosnaprimer** [comment]
Hi. Ideally, post 3 things:
- exact steps how to trigger the problem
- video of you triggering the problem
- tasproject that you trigger it in (if you can show how to trigger it right away regardless of game and system, this one isn't needed).

**Comment by cratty79** [comment]
Well, it's happening no matter what (I can't get the video until Monday, and it's probably going to be sped up significantly until it is there), and it happened in Sonic 1-3, I'll get more information on Monday since that's when I can easily use my computer now.

**Comment by vadosnaprimer** [comment]
You might even record vocal comments so we don't rely on my guessing abilities.

**Comment by cratty79** [comment]
Weird, it doesn't seem to trigger this issue on another computer...
