### ISSUE TITLE
SGB BIOS boot screen is completely wrong

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1164]
From when BizHawk switched to SameBoy for SGB emulation, the BIOS screen did became the same as GB.

**Comment by alyosha-tas** [comment]
There is currently no code path that loads the SGB Bios in SameBoy. It looks pretty simple to do though so I'll look into it.

**Comment by alyosha-tas** [comment]
Even adding the code path for SGB bios doesn't do anyhting, looks like the core simply doesn't support it at this time.

**Comment by ThunderAxe31** [comment]
However, the previous core used by BizHawk did support BIOS just fine.

**Comment by NarryG** [comment]
You can override the SGB core back to BSNES in the configuration. Config > Cores > SGB > BSNES.

**Comment by ThunderAxe31** [comment]
Thanks NarryG. By the way, I think BSNES should be made default.

**Comment by alyosha-tas** [comment]
Unfortunately BSNES has it's share of problems too. (Try Donkey Kong Land for example.)

**Comment by nattthebear** [comment]
I don't think there's anything actionable here.  Bizhawk's Sameboy core is intentionally used for SGB only and while quite accurate in some aspects, doesn't make any attempt to exactly match how a real SGB boots.  Adding in the bios would be like polishing a turd.
