### ISSUE TITLE
PSX Ape Escape (Spain) - Foward movement issue

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#1166]
Not sure if this will also affect for the other versions of Ape Escape but...

When you are moving foward, it always walk, like the analog stick is not fully pressed foward while i WAS doing that, same affects for the right analog stick.

Any other direction is fine.

**Comment by danylopez123** [comment]
I was going to make a TAS from this game, but then i saw this issue, pretty sure is from the emulator itself

**Comment by vadosnaprimer** [comment]
Check with mednafen.

**Comment by danylopez123** [comment]
On Mednafen is working fine

**Comment by YoshiRulz** [comment]
Holding the stick up causes the virtual controller's stick to have a Y value of 1, the game's developers used the minimum of 0. Workaround: do [this](https://i.imgur.com/relJhCB.png) or use the Virtual Pad (or, in TAStudio, the piano roll).

**Comment by zeromus** [comment]
Yuck, that's a bug that needs fixing. Floating point math errors on the range deep in the umpteen layers of stick processing?

**Comment by alyosha-tas** [comment]
I tracked down this bug to line 90 in ControllerBinding.cs:

```
// zero 09-mar-2015 - not sure if adding + 1 here is correct.. but... maybe?
output = (((input * multiplier) + 10000.0f) * (range.Max - range.Min + 1) / 20000.0f) + range.Min;
```

This is not correct for range.Max < range.Min, which it is in the case of "P1 LStick Y" being [255 0] instead of [0 255] which it is for the X axis.

I'm not sure if Max being less then Min is intentional due to wanting to flip the axis or not or where this is initialized, but this is ultimately what's wrong.

**Comment by YoshiRulz** [comment]
In that case, this issue is dependent on #1200.

**Comment by alyosha-tas** [comment]
I think it might be the other way around. In the above case the physical controller input is -10000 full up and 10000 full down. This is correctly represented by the Y axis being [255 0]. However the above code inadvertantly flips this to [1 255]. So I think I just need to add an if statement to process things correctly and then maybe the other issue will just kind of resolve itself. I'll look into it.
