### ISSUE TITLE
TAStudio + Virtual Pad Bug

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1171]
Repro Steps:

Load a game (The bug works at least on NES, A2600, N64)
Open TAStudio
Open Virtual Pad
Advance one Frame
hit '<<'

Result:
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.VirtualPadButton.Set(IController controller) in C:\Users\BizHawk\BizHawk.Client.EmuHawk\tools\VirtualPads\controls\VirtualPadButton.cs:line 48

**Comment by vadosnaprimer** [comment]
This was posted before probably, virtualpad and tastudio weren't designed to co-work. Does it die when Recording mode is on?

**Comment by alyosha-tas** [comment]
It gives the same error whether or not recording mode is on.

**Comment by alyosha-tas** [comment]
This seems to be fixed by some combination of recent changes, closing.
