### ISSUE TITLE
Lua Sockets Erroring Out on Windows

### ISSUE THREAD

**Issue by Netbrian** [TASVideos/BizHawk#1174]
When trying to use the TestCommunication_All.lua (with the Python server running in the background), I get the following errors when it runs the socket commands comm.socketServerScreenShot() and comm.socketServerScreenShotResponse() (the HTTP and memory mapped file commands worked as expected).  This happens with both LUA engines, and on both the current stable build and the latest dev build (a5eca362c).  I'm using the latest version of Windows 10 for my testing.

NLua.Exceptions.LuaScriptException: KopiLua.LuaNativeFunction

NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_resume(lua_State* , Int32 )
   at BizHawk.Client.EmuHawk.EmuLuaLibrary.ResumeScript(Lua script)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass55_0.<ResumeScripts>b__1()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)

**Comment by vadosnaprimer** [comment]
@Ashafix halp

**Comment by ajbradberry96** [comment]
I'm getting an identical error using LuaSocket after the script has been running for around an hour or so.

**Comment by Ashafix** [comment]
@Netbrian, @vadosnaprimer : apologies, the email totally totally slipped my attention.
My guess is that either the IP or the port was wrong.
I updated the PyEmuhawk file on Github. Now you can find the command line parameters needed for Emuhawk in the output.
https://github.com/Ashafix/PyEmuHawk

The lua test file was also updated.
[TestCommunication_All.txt](https://github.com/TASVideos/BizHawk/files/2873426/TestCommunication_All.txt)

I'll try to carve out some time to work on better error messages.

@ajbradberry96 : I also encountered random disconnects but I couldn't figure out why it happened, sometimes the socket connection was stable for hours and sometimes it stopped after an hour. At the end I'm using the HTTP connection because it was easier to use and the delay was minimal compared to the time needed for the calculations.

**Comment by Netbrian** [comment]
> 
> 
> @Netbrian, @vadosnaprimer : apologies, the email totally totally slipped my attention.
> My guess is that either the IP or the port was wrong.
> I updated the PyEmuhawk file on Github. Now you can find the command line parameters needed for Emuhawk in the output.
> https://github.com/Ashafix/PyEmuHawk
> 
> The lua test file was also updated.
> [TestCommunication_All.txt](https://github.com/TASVideos/BizHawk/files/2873426/TestCommunication_All.txt)

I'm sorry for taking so long to reply.

When I ran it with the latest dev version, I got the following error message: 

NLua.Exceptions.LuaScriptException: KopiLua.LuaNativeFunction

The Python server didn't show any sign of communications.

**Comment by Ashafix** [comment]
@Netbrian : Can you add more details? Which OS, Python version, etc.? Also please post the output of the Python script. Thanks!

**Comment by Netbrian** [comment]
> 
> 
> @Netbrian : Can you add more details? Which OS, Python version, etc.? Also please post the output of the Python script. Thanks!

Sure!

I'm running updated Windows 10.
Bizhawk is the latest dev version, be0f5f81c or something.
Python is version 3.6.
LUA output when I run the test communications all script (unmodified) is --

Baseline:            1.659 secs
NLua.Exceptions.LuaScriptException: KopiLua.LuaNativeFunction

Python Output is 

Starting HTTP server
Running HTTP server at: 0.0.0.0:9876
HTTP server address is 0.0.0.0, probably you can use localhost or 192.168.0.107 as its IP address
Starting socket server
Socket server running at 192.168.0.107:9990

Settings for Emuhawk:
--socket_ip=192.168.0.107 --socket_port=9990 --url_get=http://192.168.0.107:9876/get --url_post=http://192.168.0.107:9876/post

establishing connection
waiting for connection

It eventually gives up and disconnects.

Do you need any further information from my end?

**Comment by Ashafix** [comment]
Thanks for the info!

Can you check two more things
a) open a browser, go to http://192.168.0.107:9876/get and check if it says "hi!"
b) after starting PyEmuhawk.py, open another Python console and try the following script
```
import socket
s = socket.create_connection(('192.168.0.107', 9990))
s.send(b'hello\r\n')
```
PyEmuhawk should print `SOCKET received` and above some details about the incoming connection.

I just want to make sure that the problem is actually with the Emuhawk part and not with the Python server.

If both tests from above work, please restart PyEmuhawk and then open Emuhawk from the command line via `Emuhawk.exe  --socket_ip=192.168.0.107 --socket_port=9990`. (or whatever the output from PyEmuhawk says).

Then go to Tools --> Lua Console and run the following commands:

```
comm.socketServerGetInfo()
comm.socketServerScreenShot()
```
The first command should give you the IP and port again.
The second command should return `Screenshot was sent` in the Lua log and a `SOCKET received` message in the PyEmuhawk window.

**Comment by Netbrian** [comment]
OK!

PyEmuHawk --

a.  The message displayed correctly.
b.  Socket received was printed.

Bizhawk:

I ran it as suggested.

comm.socketServerGetInfo() returned "NLua.Exceptions.LuaScriptException: [string "chunk"]:1: attempt to call field 'socketServerGetInfo' (a nil value)"

comm.socketServerScreenShot() seems to have worked fine. PyEmuHawk acknowledged receiving something.

**Comment by Ashafix** [comment]
Thanks!

I think I found the problem. `socketServerScreenShot` checks whether the connection is already established and creates a new connection if none exists. `socketServerSend` does not. Therefore calling  `socketServerScreenShot` before `socketServerSend` works but only `socketServerSend` does not.

The code was changed accordingly. Can you try the commit in my fork? https://github.com/Ashafix/BizHawk/commit/5b981da4e5a48dab8f4bfde7dfcc172efd568282

If this doesn't work either on your system or you need the compiled exe file, feel free to email me.

**Comment by Netbrian** [comment]
Oh great!

I e-mailed you regarding the Windows binaries too.  Thank you!

**Comment by Netbrian** [comment]
OK, looks like we've made progress.  It looks like it's expecting a parameter for a memory mapped file, but it doesn't look like PyHawk is set up to feed one in.

On the LUA end --

Baseline:            1.657 secs
Socket server:       -0.015 secs
Memory mapped file was not initialized, please initialize it via the command line
NLua.Exceptions.LuaScriptException: KopiLua.LuaNativeFunction

On the Python End --

"C:\Users\Brian Trautman\PycharmProjects\Emuhawk\venv\Scripts\python.exe" "C:/Users/Brian Trautman/PycharmProjects/Emuhawk/hawk.py"
Starting HTTP server
Running HTTP server at: 0.0.0.0:9876
HTTP server address is 0.0.0.0, probably you can use localhost or 192.168.0.107 as its IP address
Starting socket server
Socket server running at 192.168.0.107:9990

Settings for Emuhawk:
--socket_ip=192.168.0.107 --socket_port=9990 --url_get=http://192.168.0.107:9876/get --url_post=http://192.168.0.107:9876/post

establishing connection
waiting for connection
<socket.socket fd=940, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.107', 9990), raddr=('192.168.0.107', 51715)>, ('192.168.0.107', 51715)connection finished
SOCKET received

**Comment by Ashafix** [comment]
Can you add `--mmf=temp.mmf` to your Emuhawk command line call? This command should get rid of the memory mapped error.
http://tasvideos.org/Bizhawk/CommandLine.html

**Comment by Netbrian** [comment]
Looks like we're good now!  

I actually checked that page beforehand, but I don't see where it documents arguments like mmf or socket_ip.  Is there a different site for the dev version to check?

Baseline:            1.657 secs
Socket server:       -0.022 secs
Memory mapped files: -0.001 secs
Testing HTTP server
HTTP get:            -0.007 secs
HTTP post:           0.001 secs
#####################
Testing HTTP server response
HTTP GET looks fine: No errors occurred
HTTP POST looks fine: No errors occurred
Trying to find minimal timeout for Socket server
Best timeout: 1 msecs
Best time:    0.003 secs

**Comment by vadosnaprimer** [comment]
WHat's the current status of this?

**Comment by Netbrian** [comment]
I tested and verified it worked on the extra build posted.  I don't know if that's been committed to the main Bizhawk or not -- when that happens, I can retest, and close this out.

You might also want to update the documentation on the commandline options -- it doesn't seem to include information on the socket stuff.

**Comment by YoshiRulz** [comment]
opened #1583 ([link to build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/25146371/artifacts))
