### ISSUE TITLE
[Request]  Add a sleep LUA command

### ISSUE THREAD

**Issue by Netbrian** [TASVideos/BizHawk#1177]
The Bizhawk implantation of Lua does not seem to include a "sleep" command, and there isn't one built-in to the language.  I'd like to request one be added.

The most common use case would be for use with the comm functions, such as sockets or HTTP requests.  Being able to sleep while waiting for socket communications without changing emulator state would be useful.

The LUA sockets library should already have a sleep command built in if Bizhawk uses that.

**Comment by Ashafix** [comment]
When you call `comm.socketServerSend(message)` (or a related function) the emulator is frozen until one of the following conditions occurs
* the function returns something as expected
* the function times out
* the function crashes

You can set the time out via `comm.socketServerSetTimeout()` and `comm.httpSetTimeout()`.

@Netbrian : Is that what you were looking for?

**Comment by Netbrian** [comment]
I was looking for a generic sleep function, for cases when I'm using a socket library other than what Bizhawk has built in (for instance, ZMQ).
