### ISSUE TITLE
Fast export of frames

### ISSUE THREAD

**Issue by Rocketknight1** [TASVideos/BizHawk#1179]
Hey, sorry if this is a weird one! I'm an AI developer, and I've been using EmuHawk for a hobby project where a bot learns to play various emulated games just from seeing the raw screen pixels. I hacked a couple of functions into the EmuHawk source to open a socket and pass framebuffers out and receive control inputs back, and then used that as an interface to Python running neural nets with Tensorflow.

There's one issue, though - I've been using GlobalWin.MainForm.CurrentFrameBuffer() to get the current displayed frame, but the byte array that returns seems to be a PNG image rather than a BMP, and I'm not familiar enough with BizHawk or C# to figure out where the conversion is happening. I can see that CurrentFrameBuffer() calls ToSysdrawingBitmap() from BitmapBuffer.cs, but I can't figure out where the PNG conversion is happening in there.

This isn't critical (Python is able to decode the PNG on the other end of the socket), but it's slowing things down, and the faster I can run the emulator the faster the bot can learn. Is there any function to get an uncompressed frame ASAP, or can you hint at what I'd need to change if I wanted to write my own?

**Comment by NarryG** [comment]
ImageConverter saves to png as far as I can tell.
You should be able to use .Save to save it into a memorystream as a bmp and then send that.

This should work
```public MemoryStream CurrentFrameBufferMemoryStream(bool captureOSD)
{
	using (var bb = captureOSD ? CaptureOSD() : MakeScreenshotImage())
	{
		using (var img = bb.ToSysdrawingBitmap())
		{
			MemoryStream memoryStream = new MemoryStream();
			img.Save(memoryStream, ImageFormat.Bmp);
			return memoryStream;
		}
	}
}```

This will get it for you as a MemoryStream in bmp format which you can then send.

**Comment by Rocketknight1** [comment]
Update: Success! With no access to Genesis RAM, the bot has navigated Sonic to the end of the level.

![image](https://user-images.githubusercontent.com/12866554/38886396-c3422180-426d-11e8-996a-3e360887c0b3.png)

Do you want me to close this now?
