### ISSUE TITLE
NeoGeo Pocket/Color does not verify rom dump status

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/BizHawk#1182]
GoodTools has a list for Neo Geo Pocket/Color yet bizhawk does not implement it.

**Comment by Asnivor** [comment]
This has now been added to master (dev)  based on the latest TOSEC and NOINTRO dats.

If you can provide a goodtools DAT then we can look at parsing that as well, but the combination of tosec and nointro should be good enough to catch all good and bad dumps and flag them accordingly.

4d92a9f04a5dffb724157555312fb8ab64ff3c26
