### ISSUE TITLE
[Request] Apple II joystick implementation

### ISSUE THREAD

**Issue by phoenix1291** [TASVideos/BizHawk#1186]
Some games can only be played with the apple II joystick. (Can't found a list, sadly)
So is it possible to implement support for it?

I take this opportunity to ask another question, is support for.nib file format planned? Many games are only in this format and conversion software like dsk2nib doesn't really seem to work in the nib->dsk direction.

**Comment by alyosha-tas** [comment]
I'll add the .nib file extension to the existing issue #1121 

The joystick is already there.
