### ISSUE TITLE
Problem with Emu.IsLagged function

### ISSUE THREAD

**Issue by Azreally** [TASVideos/BizHawk#1190]
Hi,

When I run this script with emulation, function "Emu.IsLagged" stops working?
(this script: [bugcode.zip](https://github.com/TASVideos/BizHawk/files/1976233/bugcode.zip)).

I don't know why :-(.

The issue shows when you close the rom and load next one.

**Comment by vadosnaprimer** [comment]
Works perfectly
```
while true do
	if emu.islagged() then
		gui.text(50, 50, "LAG")
	else
		gui.text(50, 50, "")
	end
	emu.frameadvance()
end
```
