### ISSUE TITLE
mGBA Audio Keeps Playing Notes after Rewind

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1195]
With the latest developer build, some GBA audio channels appear to not be properly cutting off when using rewind.

Example with Mario & Luigi Superstar Saga
https://streamable.com/lv1f1

This issue does not exist in the latest 0.6.X build of mGBA standalone.

**Comment by NarryG** [comment]
Tagging @nattthebear as I know he deals with the mGBA core.

**Comment by vadosnaprimer** [comment]
Updated mgba. Still bugged?

**Comment by NarryG** [comment]
This commit appears to have actually broken the core completely
![image](https://user-images.githubusercontent.com/3047793/41801758-6841c7c0-764a-11e8-8d81-a614159351ea.png)

**Comment by nattthebear** [comment]
Why did we revert the palette changes?  What's going on here?

**Comment by vadosnaprimer** [comment]
It was only reverted in my 1.x only fork. tasvideos/mgba is fine, and it's what I used to build our current mgba.dll.

**Comment by NarryG** [comment]
The issue has been fixed upstream in the 0.7 branch. I requested endrift backport to 0.6.X
https://github.com/mgba-emu/mgba/issues/1107

**Comment by NarryG** [comment]
It has been backported so it's now just a matter of updating the fork again.

**Comment by vadosnaprimer** [comment]
Test
https://yadi.sk/d/nAbEFtVr3XZPDh
