### ISSUE TITLE
Cannot see anything but can still hear audio after opening ROM

### ISSUE THREAD

**Issue by InkyKat** [TASVideos/BizHawk#1196]
Hi,
I don't know if this is the right place to post this issue, but I might need some help.
I'm new to BizHawk, and there's this particular issue I'm currently dealing with while opening one of the ROMS I got. Basically, as the title says, whenever I open the ROM, I cannot even see anything (screen is black) and I could only hear the audio, but slowed down. I checked the Display options and it seems like it's doing fine. I'm guessing is it because it is a .n64 file and not a ROM file? I'm not entirely sure on that.

**Comment by InkyKat** [comment]
Just tried that, it still doesn't work and remains the same.

**Comment by NarryG** [comment]
What version of Windows are you on? I've talked to a few people who said they had a black screen on Win7.  Try Rice as that worked in those situations.

**Comment by InkyKat** [comment]
I have Windows 7. I switched the plugin to Rice as you said, but I still can't see anything at all :/

**Comment by InkyKat** [comment]
Oh yeah, just recently I also tried it with another ROM, like a .NES file, and I still can't see anything like the other .n64 file I have over there.

**Comment by Etrainquandt17** [comment]
I have been having the same issue. Except it's happening with all systems.

**Comment by NarryG** [comment]
Have you installed the pre-reqs?

**Comment by Etrainquandt17** [comment]
Yes I have

**Comment by Etrainquandt17** [comment]
I found out that most of my emulators come up with a blank screen
