### ISSUE TITLE
Super Mario RPG - Legend of the Seven Stars issue

### ISSUE THREAD

**Issue by lomaxgames** [TASVideos/BizHawk#1197]
Bizhawk crashing when you level up in Super Mario RPG (developer build and 2.2.2 version). Doesn't crashing in BSNES core, only in Snes9x

Super Mario RPG - Legend of the Seven Stars (USA)
SHA1:A4F7539054C359FE3F360B0E6B72E394439FE9DF
MD5:D0B68D68D9EFC0558242F5476D1C5B81

**Comment by hegyak** [comment]
This is probably due to Super Mario RPG using the SA1 Enhancement Chip.  Which SNES9x may not be emulating correctly.

Most likely fix:
Force Super Mario RPG into a BSNES Core.

**Comment by nattthebear** [comment]
Yes, some of the enhancement chips crash.  It's not a snes9x issue but an issue of the embedding of snes9x into Bizhawk.  We decided not to fix it because it wasn't worth much effort since we have a much better core that handles those games perfectly.

I don't know offhand if SA1 is one of those chips.  If so, then all SA1 games should be overridden to always land in the bsnes core.

**Comment by lomaxgames** [comment]
List of SA1 games for SNES (source: http://yoyofr.proboards.com/thread/2130/list-special-chipsets-games)

Augusta Masters 3 New World Golf (J) 
Bass Fishing No.1 (US) 
Derby Jockey 2 (J) 
Idaten (J) 
Igo Daidou (J) 
J-League '96 Dream Stadium (J) 
Jumpin' Derby (J) 
Kakinoki Shogi (J) 
Kato Hifumi9dan Shogi (J) 
Kirby 3 (J) 
Kirby Super Deluxe (J) 
Kirby Super Star (US) 
Kirby's Dream Land 3 (US) 
Kishi no Hanamichi (J) 
Marvelous (J) 
Masoukishin - Super Robot Wars Gaiden - Lord of Elemental (J) 
Mini Yonku Shining Scorpion Let's & Go!! (J) 
Parodius 3 - Jikkyou Oshaberi Parodius (J) 
Pebble Beach New Tournament Edition (J) 
PGA European Tour (US) 
PGA Tour 96 (E) 
PGA Tour 96 (US) 
Saban's Power Rangers Zeo Battle Racers (US) 
SD F1 Grand Prix (J) 
SD Gundam GNext (J) 
Shogi Saikyou 2 (J) 
Super Mario RPG (US) 
Super Mario RPG (J) 
Super Shogi 3 (J) 
War in Europe Expert WW II (J)

**Comment by Testsr** [comment]
What do you mean by crash?

**Comment by Testsr** [comment]
And to the OP, did you test older versions of Bizhawk?

**Comment by Testsr** [comment]
Japanese Version of Super Mario RPG does it as well.

**Comment by nattthebear** [comment]
The probable result of this will be us blacklisting those roms for SNES9x core, but I need to dig into it first just to be sure.

**Comment by Testsr** [comment]
Still Crashs.

**Comment by nattthebear** [comment]
3bc1ed4bbca0f4c81c5
