### ISSUE TITLE
Analog Y axis is flipped between various cores depending on input method

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1200]
Summary:
* DInput has positive **right** and **down**
* XInput has positive **right** and **up**
* libinput has positive **?** and **?**
* Genesis has positive **?** and **?** (mouse) - #1602
* N64 has positive **right** and **up** (standard controller)
* Saturn has positive **?** and **?** (3D controller)
* PSX has positive **right** and **down** (analog controller)
* Vectrex has positive **right** and **up** (standard controller)

So we should only be negating DInput Y and virtual PSX Y.

***

The same physical controller will be Y-inverted when switching between DInput and XInput (has this been fixed? --yoshi).
Before #1202, Octoshock was Y-inverted compared to Mupen and Saturnus.

see also #137

**Comment by NarryG** [comment]
Base on Microsoft's documentation
DInput: `The value returned for the x-axis is greater as the stick moves to the right, and the value for the y-axis increases as the stick moves toward the user.`
Xinput:  `Negative values signify down or to the left. Positive values signify up or to the right. `

It appears Microsoft flipped the Y axis between the two.

Even so, the inconsistencies between cores and the defaults should be fixed.

**Comment by YoshiRulz** [comment]
see also #137

**Comment by YoshiRulz** [comment]
Finding docs is hard.

From [cen64](https://github.com/n64dev/cen64/blob/8b89df2fdca20eec2d735e2b3db80b0b8199879f/os/common/input.c#L35-L53), it looks like right and up are positive on the N64. I also found [this](http://n64devkit.square7.ch/pro-man/pro26/26-02.htm#04-01) which includes the specs of the octagonal hardware limit in the controller's case, and [this](https://sites.google.com/site/consoleprotocols/home/nintendo-joy-bus-documentation/n64-specific/standardcontroller) similarly interesting-yet-unhelpful document. I did remember that in my research on Rayman 2 (U), I found that 0x0CF590-0x0CF593 mirror the input. Sure enough, right and up positive.

From [this programmers' guide](http://www.playvectrex.com/designit/chrissalo/joystick.htm), Vectrex also has right and up as positive.

I've edited this into the issue desc.

**Comment by iamgreaser** [comment]
Alright, as requested:

According to psx-spx: http://problemkaputt.de/psx-spx.htm#controllersstandarddigitalanalogcontrollers
On a real PSX analogue controller, +X is right and +Y is down for both sticks.
For completeness IIRC PS2 follows suit.

**Comment by alyosha-tas** [comment]
I fixed the bug that was causing errors in physical controller input (not 100% sure about XInput though since I can't test that.)

I also fixed the analog controller in Vectrex.

What is left to do in this issue?

**Comment by YoshiRulz** [comment]
TIL we emulate a lot more than 5 controllers with axes.

I've closed this now that "direction" has a single source of truth, though it's possible I've missed a bug in one of the more obscure tools. I'll fix any if and when they come up. In the end, DirectInput wasn't a concern at all because it's been commented-out in `master` since 60b7858fb.
