### ISSUE TITLE
joypad.set doesn't accept certain button combinations

### ISSUE THREAD

**Issue by ktwo123** [TASVideos/BizHawk#1206]
The following should press all directions on the D-pad (written for an NES-game in bizhawk) on the same frame:
```
while true do
joypad.set({Left=1},1)
joypad.set({Right=1},1)
joypad.set({Up=1},1)
joypad.set({Down=1},1)
emu.frameadvance()
end
```
However, it will only result in up+left being pressed. Is this a know problem? Is there a way around it?

**Comment by NarryG** [comment]
In control options, do you have "U+D/L+R" set to "Allow"?

**Comment by ktwo123** [comment]
You're absolutely right, problem solved. I was working in TAStudio, which wasn't affected by this, so I didn't consider there could be an option somewhere for this case. Thanks!
