### ISSUE TITLE
Missing audio and crashes when changing output device

### ISSUE THREAD

**Issue by Amphitryon0** [TASVideos/BizHawk#1212]
When playing a game through headphones, removing them from the computer sometimes (about 70 percent of the time) results in no game audio playing through my speakers, and no game audio plays through my headphones when I plug them back in.  I can re-enable sound by opening the sound configuration dialog and clicking OK with headphones in, but this crashes the program if I do it without headphones in when the sound is not working. This crash results in the following dialog.
![2018-06-09t23_20_22-bizhawk_error_cropped](https://user-images.githubusercontent.com/17864580/41198647-5a6ca0b8-6c48-11e8-97b7-9d98ab8b57de.png)
I am using DirectSound with the sound device set to \<default\> and a buffer size of 100 ms.
This issue happens on both the latest stable version (2.2.2) and the latest development version I compiled (173bb2a50).

**Comment by Asnivor** [comment]
It sounds like your soundcard maybe has two disparate logical sound devices internally. When you unplug the headphones, the soundcard disables the one that is 'wired' to the headphone jack socket, and enables the the one 'wired' to your speaker/lineout jack socket. Or the soundcard is just temporarily re-initialising its buffer when this happens.

Regardless, SlimDX is initialised when a core loads. Unless someone can figure out how to catch this exception in the bizhawk audio-subsystem and re-init the sound provider (if this is even possible/recommended), then I'm not sure how to fix it.

Are you able to try the other output method options in Bizhawk (config -> sound configuration) and see if the error still happens?

![image](https://user-images.githubusercontent.com/7911038/44195159-1c4b5000-a130-11e8-84af-3d57d67eea4e.png)

**Comment by Asnivor** [comment]
I wouldn't know if it were a common problem or not. But there are certainly many machines with onboard sound where this is a possibility (for whatever unknown reason).

**Comment by Asnivor** [comment]
@Amphitryon0 did you get any further with this?

**Comment by YoshiRulz** [comment]
It would be very easy to catch a `DirectSoundException` in [here somewhere](https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Client.EmuHawk/Sound/Output/DirectSoundSoundOutput.cs), but is this bug our problem? I can't even follow the stacktrace.

**Comment by zeromus** [comment]
actually what probably needs to be done is proper handling of the return errors to look for the device lost status. the most annoying part of directx programming, by far
