### ISSUE TITLE
TAStudio "oops"

### ISSUE THREAD

**Issue by imdangerous21** [TASVideos/BizHawk#1217]
Ok, so i am trying to TAS the game "Super Mario Bros" for the NES, and everytime I try opening TAStudio, I keep getting this message http://prntscr.com/jtvqmy is there a way to fix this? Thanks, imdangerous21

**Comment by vadosnaprimer** [comment]
Describe all the steps exactly, also which bizhawk version?

**Comment by imdangerous21** [comment]
alright, So it's BizHawk version 2.2., And I load up the Rom, Open TAStudio, and then click "file," then "open" and I click on my TAS file, and when I try and click anywhere to add a frame of input, That pops up and I have to force close bizhawk.

**Comment by vadosnaprimer** [comment]
Save it as another name. Also export as bk2. If those won't open, upload it somewhere and post the link.

**Comment by adelikat** [comment]
Yes, please upload the exported bk2
