### ISSUE TITLE
Lua Set Input Lagged proposal

### ISSUE THREAD

**Issue by Azreally** [TASVideos/BizHawk#1219]
Hi,

I wanna introduce concept to add **tastudio.setimputlag** function to lua. This function should sets lagged inputs if I using this function like this:
E.g.

`while true do`
`local fc = emu.framecount();`
`if ( fc >= 2104 ) and ( fc <= 2109 ) then`
`tastudio.setimputlag( "A" ); --this shall change green colored input frame (box) to red in range 2104-2109`
`end;`
`if ( fc > 2110 ) then`
`break;`
`end;`
`emu.frameadvance();`
`end;`

I think that It'll looks like this after using the function with TAStudio:
![inputlag](https://user-images.githubusercontent.com/36796272/41560412-cf5f5866-72fb-11e8-9b0c-78e718e4d86f.PNG)

You can mark jumps, directions etc. by this.

**Comment by vadosnaprimer** [comment]
**void tastudio.onqueryitembg(nluafunc luaf)** 

called during the background draw event of the tastudio listview. luaf must be a function that takes 2 params: index, column. The first is the integer row index of the listview, and the 2nd is the string column name. luaf should return a value that can be parsed into a .NET Color object (string color name, or integer value)
