### ISSUE TITLE
TAStudio.OnQueryItemBg transparency color problem solved

### ISSUE THREAD

**Issue by OrgThing** [TASVideos/BizHawk#1221]
When you make script with passing integer value as color and this integer value contains transparency color above then 0x7F value, then **ColorTranslator.FromHtml** function returns wrong value and just you see it in this screenshot:
![argb_problem](https://user-images.githubusercontent.com/40444125/41694226-c82aaa1a-74f8-11e8-8e0f-30a7e65c0b04.png)
So I suggest to change this to:
![50ticks_argb](https://user-images.githubusercontent.com/40444125/41694423-c9f21760-74f9-11e8-99ac-0359814bd2f1.png)
Not only that solve this problem then do his job much more faster compered to this one:
![150ticks_string](https://user-images.githubusercontent.com/40444125/41694323-496b46de-74f9-11e8-8de3-082db6a4b49f.png)

**Comment by NarryG** [comment]
Just submit a pull request with the changes. Looking at the reference source, they used Convert.ToInt32 for some reason.

**Comment by Azreally** [comment]
I will. I know this problem because I'm using this function to mark jumps. When you make function return integer like this (e. g.):
tastudio.onqueryitembg(
function ( current_index, current_input )
if ( current_input == "A" ) then
return 0xCF1F2F3F;
end;
end ) );
Input color will gone! I'll fix this.

**Comment by Azreally** [comment]
Done. https://github.com/TASVideos/BizHawk/pull/1222

**Comment by vadosnaprimer** [comment]
They parse alpha channel as a signed byte? Are they fucking insane?
