### ISSUE TITLE
gamesdb ignored?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1223]
Ive been trying to edit gamesdb for certain core over rides I prefer but the behavior is like my edits dont matter.

am I missing something?

**Comment by hegyak** [comment]
The GamesDB txt file will read gamedb_user.txt and attempt to apply settings from there as well.  However, I don't know if user settings can override pre-existing settings.

**Comment by jjfmz42015** [comment]
works! thank you. as a test I ran some genisis roms via pico drive!!!
