### ISSUE TITLE
pcehawk crash using Ballistic USA during attract mode

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1231]
pcehawk crash using Ballistic USA during attract mode

Does not happen in mednaffen, ootake or magic engine.

**Comment by Asnivor** [comment]
@jjfmz42015 I think this might be fixed now. Can you please test in the latest dev build and let us know?

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Asnivor** [comment]
Confirmed, this is still happening. Emulation just hangs at some point after 50K frames

**Comment by nattthebear** [comment]
Reopen if the nyma core didn't fix this
