### ISSUE TITLE
Sega Saturn / Saturnus Update Core

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#1232]
Hawk's last Saturn core is back at 0.9.44 (March 17th 2017) and it continues to get updates to the core to this day with improvements so far so that the last update to the core was in the latest release 1.21.3 (24th April 2018).

**Comment by Spikestuff** [comment]
A bit of an update. The most current core for it is now in 1.22-Unstable's version (Dec 22nd 2018's) which features some additions.

**Comment by YoshiRulz** [comment]
natt just updated Saturnus f14dace4a
