### ISSUE TITLE
Links awakening music goes off pitch

### ISSUE THREAD

**Issue by EvilThorn** [TASVideos/BizHawk#1238]
for a few seconds, music from links awakening goes off pitch, then after, goes back on pitch. Any reason for this?

**Comment by NarryG** [comment]
Is this with Gambatte or GBHawk?

**Comment by EvilThorn** [comment]
Both, seems like GBHawk is even worse.

**Comment by NarryG** [comment]
Are you set to sync by audio or sync by clock?

**Comment by EvilThorn** [comment]
Wheres that?

**Comment by Asnivor** [comment]
![image](https://user-images.githubusercontent.com/7911038/42319660-8a18943c-804a-11e8-9223-756ec778161a.png)

**Comment by EvilThorn** [comment]
Im using clock throttle.

**Comment by EvilThorn** [comment]
Nope

**Comment by EvilThorn** [comment]
i hear some popping while transitioning though
