### ISSUE TITLE
NES load error

### ISSUE THREAD

**Issue by jakanz** [TASVideos/BizHawk#1239]
Whenever I'm go on BizHawk, go to 'Recent ROM' in the 'File' selection menu and go to my SMB1 rom, go to TASstudio, and next thing I know this pops up: https://imgur.com/a/Aqz4N7W

I don't know what this means, and probably never will.
I've already updated to 2.3 and deleted config.ini and reopened BizHawk, NOTHING WORKED. I didn't have this problem earlier in my 'TAS career' and I don't know what to do.

If you know what to do, please let me know.
Thanks in advance!
~jakanz

**Comment by alyosha-tas** [comment]
you are in QuickNES core when tastudio is expecting NESHawk.

After you load the rom, go to Config -> Cores -> NES -> NESHawk
Then go to Emulation -> Reboot Core

Should work now

**Comment by jakanz** [comment]
Danke (German for thank you)

:)

**Comment by Madsans** [comment]
Hi @jakanz 

I'm a little desperate. Would you know to tell me what kind of mistake this is? I would appreciate your help as a professional :)

![Captura de pantalla (62)](https://user-images.githubusercontent.com/49731375/56314088-64ee5980-6154-11e9-9dd3-f0752d90af4e.png)

Thanks a lot!

**Comment by jakanz** [comment]
What do you do to cause the error? Usually if an error for BizHawk shows up, I restart my computer to fix it. :D

**Comment by nattthebear** [comment]
Looks like you're trying to run a busted Saturn game.  Probably should be a new issue (or nothing at all, because 99% chance the problem is your cue file is busted)
