### ISSUE TITLE
Dumping Issues.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#1244]
[An echo of my comment I made on TASVideos.](http://tasvideos.org/forum/viewtopic.php?p=472500#472500)
---
Somehow in 2.3 when dumping games it will double the resolution for an unknown reason (tested with SNES) where this issue wasn't a case in the previous version (2.2.2).
Yes there are cases where SNES games are double res (_Lufia II_ for example) but in the game example it is 256x224. You can test with _Super Mario World_ if you please but the result will be the same issue.

Dumping Virtual Boy from frame 0 lands into the screen on being squished in comparison where it normally just dumps without the squish. Dumping Virtual Boy frames later makes it have the same double resolution issue as SNES.

Note: Screenshots on the other hand are perfectly fine.

SNES dumped on 2.2.2 (correct):
![](https://i.imgur.com/0KeBD6q.png)

SNES dumped on 2.3:
![](https://i.imgur.com/pw1hjhX.png)

Virtual Boy dumped on 2.2.2 (correct):
![](https://i.imgur.com/tlEcXPX.png)

Virtual Boy dumped from frame 0 on 2.3:
![](https://i.imgur.com/xEmbyJ9.png)
**[Dumping a few frames after 0.](https://i.imgur.com/UcKrZkh.png)**

**Comment by nattthebear** [comment]
Make sure stretch settings and capture osd are off?

**Comment by Spikestuff** [comment]
This is from a clean version of 2.3. Nothing has been done to it except setting the path of the Firmware.

I did ask fsvgm about it and he himself doesn't actually get these issues so I don't know.

**Comment by fsvgm777** [comment]
Okay, so I can only reproduce the bug when dumping AVI via "Record AVI/WAV". However, it's fine when dumping via "Config and Record AVI/WAV".

This is on a clean 2.3 config.

**Comment by vadosnaprimer** [comment]
I confirm that "Record AVI/WAV" magically upscales the video not only for VFW AVI, but even for ffmpeg, while "Config and Record AVI/WAV" doesn't.

**Comment by vadosnaprimer** [comment]
Here's the cause of death: https://github.com/TASVideos/BizHawk/commit/db8b051b0089a36ba9c53591020d334bb1751dcd
