### ISSUE TITLE
Robot Wars: Extreme Destruction won't advance past the title screen

### ISSUE THREAD

**Issue by Shima33** [TASVideos/BizHawk#1245]
It displays the opening credits and language select just fine, as well as playing music, but once you get to the title screen, the copyright information and the "PRESS START" text never appear. Opening the TAS Studio reveals that all frames after the opening animation are all lag frames, oddly.

Using the VBA-Next core resolves this issue, so it's an issue with the mGBA core.

**Comment by NarryG** [comment]
Have you checked against mGBA master and mGBA 0.6.X upstream?

**Comment by Shima33** [comment]
No, I only used the latest version of Bizhawk - in fact, I upgraded to the
newest version after my older copy of Bizhawk didn't work, and neither of
them pulled it off.

**Comment by Shima33** [comment]
Just tested - still doesn't display the "PRESS START" text, still unable to advance.

**Comment by RetroEdit** [comment]
Alright, after a bit more digging, I think this issue is long fixed, having been acknowledged by endrift fixed in 0.8: https://github.com/mgba-emu/mgba/issues/1208

Since BizHawk has incorporated mGBA 0.8 since version 2.3.3, this issue should be closed.
