### ISSUE TITLE
Incorrect platform label in header file for Sonic Labyrinth Movies

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/BizHawk#1246]
In all current Bizhawk versions, if you record a movie file for Sonic Labyrinth, the header file will list the platform as SMS, when the game is in fact Game Gear. When you go to Play Movie and look at the header information, SMS will be marked in red because it is incorrect. I'm able to reproduce this in both 1.13.2 and 2.3. This may affect other Game Gear games as well but I am not certain.

**Comment by Asnivor** [comment]
PR #1277 

@MemoryTAS This actually affects all GG (and I think SG) games.

**Comment by vadosnaprimer** [comment]
It doesn't affect anything. For whatever reason, when system info is dumped to the header, for GG it's written as SMS, with IsGameGear flag set. Similarly for SG1000 - SMS and IsSG1000 flag. But when these are looked up in the DB, their platform is GG and SG respectively, while the header has SMS. They are loaded just fine, and even the emuhawk caption tells the system correctly. Just this tiny check in PlayMovie is wrong.

**Comment by vadosnaprimer** [comment]
Here's the proper fix that I'm not applying, because there's no official decision to dump GG/SG to movie header.
[proper-gg-sg-fix.zip](https://github.com/TASVideos/BizHawk/files/2406890/proper-gg-sg-fix.zip)
