### ISSUE TITLE
PS1 Games not running

### ISSUE THREAD

**Issue by CamManCraft2001** [TASVideos/BizHawk#1247]
Hello, I have tried to open a PS1 game onto this emulator. I have gotten the ps-30a.bin file, when I try to load the game, the RTC emulator does not load the game at all. I have also tried running the bios file as well, but that just crashes the emulator. Is there anyway to run PS1 games on this emulator? I would like to know so that I can corrupt my favorite PS1 games. Thanks!

**Comment by vadosnaprimer** [comment]
Are you feeding the .cue file to the emu, or .bin? The latter won't work.

**Comment by CamManCraft2001** [comment]
I haven’t done anything with the cue file, so how would I feed to cue file to the emu?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by CamManCraft2001** [comment]
Ok , so I got the game to work, but the emulation is very slow and laggy, what can I do to fix this?

**Comment by vadosnaprimer** [comment]
Disable everything in the Config - Rewind dialog. Don't think you can speed it up otherwise.

**Comment by CamManCraft2001** [comment]
Still laggy and slow, can you tell me what exactly to disable in the config?
