### ISSUE TITLE
PS1 Game Laggy and Slow

### ISSUE THREAD

**Issue by CamManCraft2001** [TASVideos/BizHawk#1249]
Hello, I have gotten my PS1 game to work on this emulator. The only thing was that it is laggy and slow. I was told to disable everything in the config, but that didn't seem to help much. If anybody can tell me what to disable or any other way to make the game less laggy or stabilize the frames at 60 fps that will be great. I have another PS1 emulator that works fine on my computer, so I don' know why this emulator is not working as well.

**Comment by Spikestuff** [comment]
What's your computer's specs.
The game runs perfectly fine and the emulator for that matter so it's your hardware that's the issue.

**Comment by CamManCraft2001** [comment]
AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G, 12.0GB RAM, AMD Radeon R6 Graphics

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by vadosnaprimer** [comment]
Not a bug.
