### ISSUE TITLE
Option for disable AVI split per 2 Gb

### ISSUE THREAD

**Issue by QuakerRUS** [TASVideos/BizHawk#1253]
Can you implement option for disable AVI split per 2 Gb? I'm recording long 1080p AVI and I have NTFS file system and I want have one video file. Thanks.

**Comment by vadosnaprimer** [comment]
It will break after 2GB if you don't split, if you use a regular VideoForWindows coder (first option in the dumper. Use Lossless AVI via ffmpeg instead, already provided with the needed command line somewhere in the dumper config. Doesn't need to split the video on 2GB mark.

**Comment by vadosnaprimer** [comment]
Exactly, see the "vfw" part of the codec name. It is literally impossible to avoid 2GB split without breaking the video. If you want lossy dump, then use the lossy command for ffmpeg writer.

![3](https://user-images.githubusercontent.com/7092625/43482195-b48ee8f8-9510-11e8-944f-7c133fea71bd.png)
