### ISSUE TITLE
Fix aspect ratio option of Resize video option (Config and Record AVI/WAV)

### ISSUE THREAD

**Issue by QuakerRUS** [TASVideos/BizHawk#1254]
I want to record 1920x1080 video, but with resize video option aspect ratio of video changes. Can you add option to fix aspect ratio and fills unused space by black color? Thanks.

**Comment by QuakerRUS** [comment]
This options breaks aspect ratio too. If aspect ratio is fixed then result will have left and right black unused areas.

**Comment by vadosnaprimer** [comment]
Since "maintain aspect ratio" is checked, I guess it preserves it instead? Try unchecking.

**Comment by QuakerRUS** [comment]
Tried - same. With this option aspect ratio changes. It works like resize video option, but works not only for recording videos, but for display too.

**Comment by nattthebear** [comment]
The stretch option for video output does stretch to whatever you asked it for, and does no special AR calculations.

If you want to take something as crappy as a ZX Spectrum movie and blow it up to 1080p, then there's really only one workflow that makes sense:

1) Dump original res lossless video out of the emulator.
2) Blow it up in the video editing tools of your choice.

The options in the video dumping system are geared around two things; supporting the lossless workflow, and providing some half-decent options for casual users to get half-decent videos in one go.

Your use case is very atypical; why do you want the black bars recorded in the video?  Better to stretch to 1440x1080 (or whatever the precise appropriate width is for that console) and let your video playback program pillarbox it.

Another problem that you'll probably run into is that the resizer algorithms for upscaling are not smart or high tech.  Best to just use real video editing software.

**Comment by QuakerRUS** [comment]
I use TASEncodingPackage now, so it's not so important for me. Just a flexible option.

**Comment by vadosnaprimer** [comment]
I don't understand what your problem is anymore. Aspect ratio for old computers is always 4:3, and setting the window resolution to exactly that can't be breaking it. If you want to preserve 1:1 pixel aspect ratio, just force the corresponding size that upscales everything equally.

**Comment by QuakerRUS** [comment]
I have no problem anymore. I created in Sony Vegas 1920x1080 videos of old games with x264vfw codec and 4x3 aspect ratio, and blake rectangle areas left and right of screen, because on YouTube it has better quality than 1440x1080 videos. Now I don't need this option, but maby anybody want to do same, because they don't have your encoder package or any other reason. Implement this. if you want. or close issue - it's no difference for me now.

**Comment by vadosnaprimer** [comment]
So I guess the actual thing you meant was allowing black bars to pad the video in a certain way?

**Comment by QuakerRUS** [comment]
Yeah. Custom resolution with fixed aspect ratio.

**Comment by vadosnaprimer** [comment]
It's called letterboxing. And I don't know if there's any interested in this among devs.

**Comment by nattthebear** [comment]
> I have no problem anymore.

Doubt anyone else would ever want this, so sweep sweep
