### ISSUE TITLE
[Request] Minor QOL changes to RAM Watch

### ISSUE THREAD

**Issue by GabrielSorensen** [TASVideos/BizHawk#1257]
Two minor changes that would help out in ram watch.

1. Adding a menu option to send the selected watch to the top or bottom of the list. 
2. The ability to add notes to row separators, to act as section headings.

(1.5) Really I would like to be able to send the watch to the next line separator, but I feel this would just end up adding visual clutter to the menus.

**Comment by Asnivor** [comment]
I've created a PR that handles 1. and 2. It may or may not get accepted.
