### ISSUE TITLE
[FEATURE REQUEST] Wisdom Tree unl mapper in Gambatte core support

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1260]
they used custom 32K banking mapper so does not work in bizhawk

**Comment by alyosha-tas** [comment]
Where can I find some information about this?

**Comment by Asnivor** [comment]
@alyosha-tas The internet has this as the 'Wisdom Tree' mapper I think.

The mame codebase has a brief description:

https://github.com/mamedev/mame/blob/master/src/mame/drivers/gb.cpp#L266

> Wisdom Tree mapper
> ==================
> The Wisdom Tree mapper is triggered by writes in the 0x0000-0x3FFF area. The
> address written to determines the bank to switch in in the 0x000-0x7FFF address
> space. This mapper uses 32KB sized banks.

The implementation within mame looks fairly straightforward (to my uneducated mind):

https://github.com/mamedev/mame/blob/4263a71e64377db11392c458b580c5ae83556bc7/src/devices/bus/gameboy/rom.cpp#L260

**Comment by alyosha-tas** [comment]
Cool thanks. Simple enough. Do you know if those games have the same value at 0x147? If so I can just add that identifier and commit the mapper.

**Comment by Asnivor** [comment]
Yup, they all appear to have 0x00 at 0x147.

**Comment by Asnivor** [comment]
Hmm, i'm just using a hex editor though. Is there some kind of rom header that I need to take account of first?

**Comment by Asnivor** [comment]
Ok, it's 0x00 at 0x147 on all roms (using the hex editor within bizhawk)

**Comment by alyosha-tas** [comment]
Ok then I'll need the hash of each of the rom's to add, since 0x00 is the no-mapper default. It's a bit annoying but I guess wisdom tree didn't bother with such things.

**Comment by Asnivor** [comment]
Ok, looks like they are all in the gamesdb somewhere already (although named slightly differently in some cases):

```
Joshua (USA) (Unl)
SHA1:019B4B0E76336E2613AE6E8B415B5C65F6D465A5
MD5:2C07CAEE51A1F0C91C72C7C6F380B0F6
```

```
Spiritual Warfare (USA) (Unl)
SHA1:6E6AE5DBD8FF8B8F41B8411EF119E96E4ECF763F
MD5:37E017C8D1A45BAB609FB5B43FB64337
```

```
Exodus (USA) (Unl)
SHA1:685D5A47A1FC386D7B451C8B2733E654B7779B71
MD5:AB1FA0ED0207B1D0D5F401F0CD17BEBF
```

```
Holy Bible, The - King James Version (USA) (Unl)
SHA1:6362FDE9DCB08242A64F2FBEA33DE93D1776A6E0
MD5:BA2AC3587B3E1B36DE52E740274071B0
```

```
Holy Bible, The - New International Version (USA) (Unl)
SHA1:136CF97A8C3560EC9DB3D8F354D91B7DE27E0743
MD5:8CDDB8B2DCD3EC1A3FDD770DF8BDA07C
```

**Comment by Asnivor** [comment]
Yup, done.

@g0me3 This game (and others by Wisdom Tree) are now working in the dev build:

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by g0me3** [comment]
King James Bible does boot but doesn't work properly. you cannot read something. also there is at least one goodness rom marked as [!] different from no-intro version so it is not hawk db and not recognized so doesn't boot.

**Comment by g0me3** [comment]
or wait. it should work only in GBHawk core, right?

**Comment by g0me3** [comment]
ok, fine, I see. but the problem is still here ;) GB hawk core does not have Code/Data logger and I can't log it with Gambatte which still does not support such mapper ;)

**Comment by g0me3** [comment]
can't rename issue for some reason...

**Comment by Asnivor** [comment]
I am able to boot King James Bible, controls work and I can read it.
Does your ROM have a different hash? The one that has been added to bizhawk is:
```
Holy Bible, The - King James Version (USA) (Unl)
SHA1:6362FDE9DCB08242A64F2FBEA33DE93D1776A6E0
MD5:BA2AC3587B3E1B36DE52E740274071B0
```
If different, can you provide your hash? 

Also, did you definitely try the dev build linked above (and extracted it to a new folder)?

> ...also there is at least one goodness rom marked as [!] different from no-intro version so it is not hawk db and not recognized so doesn't boot

Can you provide this romname and hash?

**Comment by g0me3** [comment]
as I mentioned above, this works only in GBHawk core, not in gambatte core (what I actually needed since gbhawk does not have code-data logger at all).

There is another version of Joshua in goodness different from no-intro version
SHA1: 9b24df812bc071e6702c0e11523e0443d01e0575
MD5: 4905f2156e597da6e6519c0cbbb1f884

**Comment by alyosha-tas** [comment]
I added the above hash to GBHawk DB.

CDL and Gambatte are low priority for me. A PR would probably be the fastest way to get either of those two things done. Depending on what you need CDL for maybe a LUA script of some sort would be quicker to make work.

**Comment by alyosha-tas** [comment]
With CDL in GBHawk now, and me having no intention of adding things to gambatte, I'll close this one.

**Comment by CasualPokePlayer** [comment]
https://github.com/TASVideos/gambatte-speedrun/pull/7

So years after this issue Gambatte is getting support for the Wisdom Tree mapper.
