### ISSUE TITLE
[FEATURE REQUEST] Tamagotchi 3 (J) [S] for GB support

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1261]
I see there is a kind of complex mapper thus it were somehow hooked up in mame at least so I hope this is not a big problem to at least get it running propertly without maybe extra features...

**Comment by Asnivor** [comment]
This is apparently the Bandai TAMA5 mapper. Looks like it is only partially supported in mame.

@alyosha-tas mame docs are here if you are interested: https://github.com/mamedev/mame/blob/master/src/mame/drivers/gb.cpp#L130

**Comment by alyosha-tas** [comment]
This mapper is now working in GBHawk.

The RTC doesn't work entirely correctly, although most of the groundwork is done.
You can still play the game in non-RTC mode though.

I'll close this issue and add the RTC to the other main GBHawk issue, as it's a minor note at this point.
