### ISSUE TITLE
[FEATURE REQUEST] Option to disable usage of internal ROM information for running roms for Game Boy

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1262]
this may be like option to use some generic default settings for booting the rom (using the ROM size for banks number limit, most common MMC1 and generic WRAM/SRAM amount...

i'd like to run some Sachen games but most of originals need to be hacked first sometimes its is pain in ass... (most of currently available working roms in the net are modified already) but there a few original dumps with no modifications that does not run properly here

**Comment by hegyak** [comment]
You should be able to use the gamedb_user.txt file to set the ROM(s) to use the features/functions you want them to use.

Example for Pokemon Liquid Crystal (GBA)
7ACF9D4C14B570A375402CB4DD2619F910A8A45B	!	Pokemon - Liquid Crystal 3.3.00512	GBA		flashSize=131072;saveType=3;rtcEnabled=1;mgbaNeedsOverrides=1

You may also need to edit gamedb.txt to have #include gamedb_user.txt in the file as well.

**Comment by alyosha-tas** [comment]
Sachen  games should run properly in GBHawk. If there is a specific one that is not working please report it.

**Comment by alyosha-tas** [comment]
Closing as I see nothing to do here. I'll address this only if a specific game is behaving incorrectly.
