### ISSUE TITLE
ZXHawk: Request to be able to change the core background color

### ISSUE THREAD

**Issue by Asnivor** [TASVideos/BizHawk#1263]
by @QuakerRUS

**Comment by Asnivor** [comment]
@QuakerRUS - this is now implemented in the latest dev build and can be found in the core menu:

ZXSpectrum > Non-sync settings.

You basically have a color picker (with the bottom custom colors being from the actual spectrum palette). There is also a checkbox which overrides color selection and paints the background with the last core-generated border color. 

Note: because the background is only updated every frame, this override is fairly seizure inducing with anything that generates rasterbars in the border area (i.e., tape loading and 0.001% of games).

**Comment by QuakerRUS** [comment]
Thanks!

**Comment by QuakerRUS** [comment]
Just tested, works perfectly!
