### ISSUE TITLE
SMSHawk: Golvellius garbled graphics in 2.3 (was fine in 2.2.2)

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#1264]
When booting Golvellius (both UE and J) on 2.3 the graphics are garbled, was working fine in 2.2.2
Originally reported by "GamersTavern" on the TASVideos forums http://tasvideos.org/forum/viewtopic.php?t=20383

US Version:
SHA1:CB8C2DE9A8E91C0E4E60E5D4D9958E671D84DA4C

Japanese Version:
SHA1:F62C5C9DEA4368E6475517C4220A62E40FEDD35D

![golvellius ue 2018-08-08 16 14 16](https://user-images.githubusercontent.com/6367891/43820700-298c72e0-9b26-11e8-821a-dfb9e42d77f9.png)

**Comment by Asnivor** [comment]
This may be to do with the Z80 accuracy improvements that were introduced in 2.3.

Unfortunately we may have to wait for @alyosha-tas to return from hiatus until this can be resolved.

**Comment by Asnivor** [comment]
Fixed in master branch
