### ISSUE TITLE
Visual c++ 2010 Sp1 Fail

### ISSUE THREAD

**Issue by Catupiry** [TASVideos/BizHawk#1265]
So, I Installed, Re-intalled and repaired visual c++ but nothing happens, it just gives me the same fail, again and again, and i can't download the pre req because it is slow and stops in the middle, so what can i do?

**Comment by GabrielSorensen** [comment]
@Catupiry 
Do you have any error codes or screenshots of the error?
I can also give you links to the individual requisites if you want to try installing each individually.

**Comment by Catupiry** [comment]
No, i don't have any error codes, just the usual pop-up, if you can send me the individual requisites i would like to

**Comment by GabrielSorensen** [comment]
Here you go, if any of these error out you at least have a better chance of finding the problem.
Good Luck.

[https://www.microsoft.com/en-us/download/details.aspx?id=49077](https://www.microsoft.com/en-us/download/details.aspx?id=49077) (KB2999226)
[https://www.microsoft.com/en-us/download/details.aspx?id=13523](https://www.microsoft.com/en-us/download/details.aspx?id=13523) (C++ Redist 2010 SP1 x64)
[https://www.microsoft.com/en-us/download/details.aspx?id=30679](https://www.microsoft.com/en-us/download/details.aspx?id=30679) (C++ Redist 2012 U4)
[https://www.microsoft.com/en-us/download/details.aspx?id=40784](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (C++ Redist 2013)
[https://www.microsoft.com/en-us/download/details.aspx?id=48145](https://www.microsoft.com/en-us/download/details.aspx?id=48145) (C++ Redist 2015)
[https://www.microsoft.com/en-us/download/details.aspx?id=49981](https://www.microsoft.com/en-us/download/details.aspx?id=49981) (.net 4.6.1 web installer)
[https://www.microsoft.com/en-us/download/details.aspx?id=35](https://www.microsoft.com/en-us/download/details.aspx?id=35) (DirectX web installer)

**Comment by hegyak** [comment]
This also should have all the BizHawk prerequisites:
https://github.com/TASVideos/BizHawk-Prereqs/releases

**Comment by Asnivor** [comment]
@Catupiry did you get this resolved?

**Comment by Asnivor** [comment]
@Catupiry ?

**Comment by YoshiRulz** [comment]
see also #1069?

**Comment by YoshiRulz** [comment]
@Catupiry ping

If the suggested fix didn't work, comment with more detail or join IRC.
