### ISSUE TITLE
SMS R-Type's title screen is broken in 2.3 (looks correct in 2.2.2)

### ISSUE THREAD

**Issue by synnae** [TASVideos/BizHawk#1267]
I already posted this in the tasvideos bug reporting thread but decided to repost it here so it will be tracked.

Title says all, so there's not much else to add for a description.

2.3:
![0m0dvjc](https://user-images.githubusercontent.com/24638400/43988608-c44a29a4-9d0f-11e8-993e-7c7091d7843e.png)

2.2.2:
![vyfcdis](https://user-images.githubusercontent.com/24638400/43988609-cb087ffc-9d0f-11e8-871d-a0f7879b8603.png)

**Comment by Asnivor** [comment]
fixed in master branch
