### ISSUE TITLE
TAStudio locks up after ~30 mins usage in 2.3 (fine in 2.2.2)

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#1269]
After about 30 minutes using N64 + TAStudio in 2.3 (was fine in 2.2.2), TAStudio locks up completely and BizHawk goes into “not responding” mode, possibly a UI blocking infinite loop somewhere.

Originally I was thinking it was related to RSP HLE/GlideN64 updates but @Spikestuff reported the same issue with mGBA + TAStudio in 2.3 (also fine in 2.2.2) which leads me to believe it’s not core specific.

This issue is keeping me on 2.2.2 for now, hope to see it fixed for a 2.3.1 hotifx release. If it can’t be tracked down by looking at commit history I can compile a dev build and try to get a stack trace.

Cheers.

**Comment by vadosnaprimer** [comment]
I don't even have a VS installed atm. Please run it from the IDE, I don't know when I get around to this.

**Comment by Spikestuff** [comment]
To expand on it. It's not just the mGBA & N64 cores running with TAStudio.
Octoshock, BSNES (I've dropped a project due to this), NESHawk and GBHawk have all crashed on me with use on TAStudio in 2.3.
(Basically the ones I've tested / screw around with)

This is just to point out it's definitely not core specific.

N?K has also pointed out during his work on Pepsiman, BizHawk liked to "not respond everytime around 15-20 minutes"

**Comment by vadosnaprimer** [comment]
Does it happen with cores where tastudio saves states every frame? I think there's only one thing in tastudio that could cause this, and in a sense, cores do make a bit of a difference.

**Comment by Isotarge** [comment]
Okay I ran it again for an hour and got a repro on the lockup after placing some inputs and seeking around, it seems to be getting stuck in this terrifying looking loop:
![loopstuck](https://user-images.githubusercontent.com/6367891/44001580-15dd8b3e-9e74-11e8-8e6b-f123646983b2.png)

**Comment by vadosnaprimer** [comment]
Exactly as expected. Could **please** see why it can't exit the loop?

**Comment by Isotarge** [comment]
Yeah I'll step through and see if I can spot anything

**Comment by Isotarge** [comment]
This RemoveState() call is failing with forwardFrame 0x62, _step 0x10, not sure if that's supposed to happen
![removestate_failing](https://user-images.githubusercontent.com/6367891/44001757-ba5b9622-9e76-11e8-85e6-ec4147710565.png)

**Comment by vadosnaprimer** [comment]
Sorry for asking so much, but could you post a video of how you trigger it? Does it still require hours of usage?

**Comment by Isotarge** [comment]
Okay it's trying to call RemoveState(0x620) and the closest state to that is 0x628 (there's no state on 0x620). I guess maybe creating a state on frame that isn't mod _step and seeking back/forward far enough to clear that state on triggers it?
![state0x628](https://user-images.githubusercontent.com/6367891/44001851-94852966-9e78-11e8-9e1b-c80ac7351d8b.png)
I don't have a reliable way to repro the lockup yet so I don't think I can get a video but I think we're getting closer here!

**Comment by vadosnaprimer** [comment]
Please test the latest build.

**Comment by Isotarge** [comment]
Yo sorry about the delay, I've been busy with work. I ran the dev build for another 40 mins frantically placing and removing inputs and seeking around in the N64 core and so far there's no lockups to report.

This tweet from @Spikestuff paints a different picture however https://twitter.com/Spikestuff/status/1032948051227246592

Do you have a reliable way to reproduce this lockup Spike? I'm hesitant to say it's 100% for sure fixed while we don't have a consistent repro.

**Comment by Isotarge** [comment]
Left it running overnight, ~4million frames. Seeked back to the start and started hammering inputs and still no lockups. It looks promising 👍
