### ISSUE TITLE
Tetris doesn't work on neshawk

### ISSUE THREAD

**Issue by William-Carter** [TASVideos/BizHawk#1270]
I have a tetris rom that runs fine on quicknes but not neshawk. I'm planning on tasing the game so I need to be running neshawk.
```
Dump:
------
BEGIN NES rom analysis:
Found iNES header:
pr=128,ch=128,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER065,sys=
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: sha1:CD047C09BA3FC5DB978163F841B7FD2B816D12A0
headerless rom hash:  md5:2FC353DE3736AC0614A10D3D4BFF9845
Could not locate game in bizhawk gamedb
Could not locate game in nescartdb
Attempting inference from iNES header
Chose board from iNES heuristics:
pr=128,ch=128,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER065,sys=
Final game detection results:
pr=128,ch=128,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER065,sys=
""
Implemented by: class Irem_H3001
END NES rom analysis
------


```

**Comment by William-Carter** [comment]
Also here are screenshots for neshawk and quicknes, respectively.
<img width="295" alt="neshawk" src="https://user-images.githubusercontent.com/38170230/44098488-afcee2aa-a023-11e8-8374-4ca2c7b0bdf4.PNG">
<img width="291" alt="quicknes" src="https://user-images.githubusercontent.com/38170230/44098490-b0166896-a023-11e8-8893-5adab909e724.PNG">

**Comment by g0me3** [comment]
this is a bad dump of unknown origin and seems hacked for different mapper or mapper set wrong. this game should use mapper 1 and only 48kb in size originally.

PRG ROM:    2 x 16KiB
 CHR ROM:    2 x  8KiB
 ROM CRC32:  0x1394f57e
 ROM MD5:  0x5b0e571558c8c796937b96af469561c6
 Mapper #:  1
 Mapper name: MMC1
 Mirroring: Horizontal
 Battery-backed: No
 Trained: No

**Comment by g0me3** [comment]
original GOOD verified dump works just fine. use it instead of this weid one
