### ISSUE TITLE
TAStudio Locks up during autosaves on 2.3

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/BizHawk#1273]
I noticed that I was getting freezes on bizhawk 2.3 every so often when using TAStudio. I turned off autosave and it stopped happening.

**Comment by MemoryTAS** [comment]
It seems to occur when the emulator is unpaused or frame advancing during an auto save. If you have yet to select a file to save to yet, it does not freeze, but if you have, then it will freeze consistently.

**Comment by Spikestuff** [comment]
I've had autosave disabled since day dot (cause I always disable tastudio autosave). Crashing still occurs.
