### ISSUE TITLE
25 fps in the nes game.

### ISSUE THREAD

**Issue by kirch56** [TASVideos/BizHawk#1281]
25 fps in the nes game. Тried everything does not help.
![image](https://user-images.githubusercontent.com/42459162/44247248-8ee22b80-a215-11e8-805c-695b417fc5b4.png)

**Comment by NarryG** [comment]
What are your PC specs?

Try swapping to QuickNES

**Comment by kirch56** [comment]
All the same
![image](https://user-images.githubusercontent.com/42459162/44247312-1af45300-a216-11e8-842d-20d949e9bd54.png)
Graphics Cards: Nvidia GTX 210
CPU: Amd Athlon(tm) 64 x2 Dual Core Processor 3800+
Motherboard: I do not know

**Comment by NarryG** [comment]
You're still in NESHawk. Is this a normal Super Mario Bros rom? I'm seeing the good dump icon. SMB should work fine in QuickNES.

**Comment by Spikestuff** [comment]
You didn't switch to QuickNES. You're still running under NESHawk as you have not restarted the core to switch.

Try running it back at a window size of x1 or x2 and give the results of what you gathered with that. It may be due to the resolution you desire to play at.
