### ISSUE TITLE
Use sameboy for GBC core

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/BizHawk#1282]
Current gambatte core cannot run GBVideoPlayer tech demo
that works on real hardware:

https://youtu.be/QWG_b57rltQ
https://github.com/LIJI32/GBVideoPlayer

**Comment by TiKevin83** [comment]
Commenting to add that SameBoy recently accounted for the gameboy's undocumented instruction prefetch and now accurately emulates Pokemon Red and Yellow's RNG.
https://github.com/LIJI32/SameBoy/commits/master
SameBoy passes a much wider library of accuracy tests than Gambatte or GBHawk, making it more likely that its accuracy with Pokemon will extend to being able to console verify other games.  A specific example would be Mickey's Dangerous Chase which relies on sprite timings which are only emulated by SameBoy.

**Comment by alyosha-tas** [comment]
What tests are these? Are there a batch of tests I’m not aware of ?

**Comment by TiKevin83** [comment]
I found through testing that GBHawk does not pass many of WilbertPol's tests, specifically the GPU (PPU?) related tests which are likely needed for Mickey's Dangerous Chase.

https://github.com/wilbertpol/mooneye-gb/tree/master/tests/acceptance/gpu

https://docs.google.com/spreadsheets/d/1T4BH72RQf8DT1YrpK1y4zizJn33rBf7BUZi2mVOKMnU/edit?usp=drivesdk

**Comment by alyosha-tas** [comment]
Hmmm, GBHawk should be passing all of gekkios tests at least in GB mode. I’ll have to take a look at what happened when I get a laptop again .

Thanks for bringing other tests to my attention though.

**Comment by alyosha-tas** [comment]
Ok that makes sense thanks. As for sameboy that’s up to natt

**Comment by alyosha-tas** [comment]
Are Wilbert Pol's variants compiled anywhere? That would help me a lot to have.

**Comment by alyosha-tas** [comment]
So the video player relies on the ‘OAM stat bit can trigger a VBL stat interrupt’ effect.

Obviously since it’s not working I have this implemented incorrectly. Hopefully I can work out the proper behavior.

**Comment by zeromus** [comment]
If the reason for using another core is predicated on issues alyosha can fix, then we can close this bug. Open new bug with better reasons if you need a new core, although I might organize it into a "new cores wishlist" thread
