### ISSUE TITLE
Initial SaveRAM value for BSNES SGB should be 0xFF, not 0x00

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#1285]
This matches the other gameboy cores, as well as being more accurate to real-world cartridges.

Not making a pull request as I haven't figured out the current build setup but I'm 99% sure the fix is to just add 0xFF as an argument here:
https://github.com/TASVideos/BizHawk/blob/7c5c3482e7fdddc213ee8aaffde3b7e592d9b93f/waterbox/libsnes/bsnes/gameboy/cartridge/cartridge.cpp#L62

**Comment by nattthebear** [comment]
@vadosnaprimer @adelikat Do the gods on high want this?

**Comment by vadosnaprimer** [comment]
I don't have knowledge on this matter, but the things mentioned in OP look fair. Can this be made optional?

As for gods, @TiKevin83

**Comment by TiKevin83** [comment]
Yes this would be preferred.  0xFFs tends to match dead battery behavior most of the time, is used as a clean wipe state by many games, and also matches the behavior modeled in the Gambatte core.

**Comment by YoshiRulz** [comment]
This is for the SGB though. Should we just assume that Nintendo followed their own spec and used `0xFF`, or has someone tested it?

**Comment by nattthebear** [comment]
Think physically:  A Superb Game Boy was a real Game Boy that was hacked up to connect to a SNES.  The cart you put in it was a real Game Boy cart, and the saveram that's exposed is the real battery backed ram on the real game boy cart.

**Comment by nattthebear** [comment]
@vadosnaprimer Since there was already a libsnes change in the pipeline, I put this on that branch (since there'd be no way to git automerge the built wbx files).  Merge at your lesiure.

1aab361569e09fe7619e505e01
