### ISSUE TITLE
Lost World Jurassic Park Saturn crashes on third level

### ISSUE THREAD

**Issue by arkiandruski** [TASVideos/BizHawk#1286]
Playing the Saturn version of Lost World: Jurassic Park. When I get to the third level, music plays, but the screen is black and it doesn't accept input.

**Comment by Spikestuff** [comment]
Mednafen runs the game back fine on the latest version.
Might be related to [the core needing a desperate update](https://github.com/TASVideos/BizHawk/issues/1232).

**Comment by nattthebear** [comment]
Reopen if it's not working in 2.5.x
