### ISSUE TITLE
Legendary Axe II does not work

### ISSUE THREAD

**Issue by EvilThorn** [TASVideos/BizHawk#1287]
for some reason, all i can do in Legendary Axe II is stand in place, pressing buttons do nothing,

**Comment by NarryG** [comment]
Are your controls fully bound?

**Comment by Asnivor** [comment]
Confirmed.

The Legendary Axe II (U)
SHA1:3D537FBD2A7181639D297B829CE3F7D7556E831B
MD5:FBCBB34F678F6F70795BDE96D295BC2F

Game appears to stall straight after pressing start (although music does continue for a short while)

**Comment by Asnivor** [comment]
@EvilThorn This looks to be fixed now. Can you please test in the latest dev build?

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by EvilThorn** [comment]
@Asnivor it indeed works now. thank you.
