### ISSUE TITLE
Octoshock doesn't properly dispose of itself resulting in a memory leak

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1298]
The Octoshock PSX core does not appear to properly dispose of itself when it's supposed to. This results in a memory leak and if there's excessive re-loading of the core (such as in my case), this memory leak shows.

![image](https://user-images.githubusercontent.com/3047793/44636724-4cd68980-a97b-11e8-81d0-03fc5b97046d.png)

**Comment by NarryG** [comment]
Turns out it's just downright not implemented.

Looking inside the Octoshock core
```
EW_EXPORT s32 shock_Destroy(void* psx)
{
	//TODO
	return SHOCK_OK;
}```

**Comment by YoshiRulz** [comment]
moved to #1299
