### ISSUE TITLE
SlimDX.DirectInput.DirectInputException

### ISSUE THREAD

**Issue by Sephirothspawn666** [TASVideos/BizHawk#1300]
SlimDX.DirectInput.DirectInputException: E_NOTIMPL: The function called is not supported at this time (-2147467263)
   à SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   à SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   à SlimDX.DirectInput.Device.SetCooperativeLevel(IntPtr handle, CooperativeLevel flags)
   à BizHawk.Client.EmuHawk.KeyInput.Initialize()
   à BizHawk.Client.EmuHawk.Input.Initialize()
   à BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   à BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by Asnivor** [comment]
You didn't provide much background information, but assuming you are using the latest release of BizHawk, are you sure you have installed the dependencies?

https://github.com/TASVideos/BizHawk-Prereqs/releases/tag/2.1

That exception smacks of dependencies not being installed, or another (conflicting) version of SlimDX having been installed at some point.

**Comment by Asnivor** [comment]
@Sephirothspawn666 Are you still having problems or can we close this out?
