### ISSUE TITLE
bizhawk load save state bug

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1301]
when you load save state error pull save buffer size mismatch
![img_20180827_200957](https://user-images.githubusercontent.com/42782548/44742894-9694b080-aaf0-11e8-929a-2c8996802713.jpg) new bug to fix

**Comment by DarkLegend1987** [comment]
when you load save state error pull save buffer size mismatch
![img_20180827_200957](https://user-images.githubusercontent.com/42782548/44743510-40287180-aaf2-11e8-9cb2-9973c251e8f5.jpg)

**Comment by NarryG** [comment]
What version of Bizhawk was this savestate made in and what version are you loading it in?

Also, did you change the controller in use in-between saving and loading the state?

**Comment by DarkLegend1987** [comment]
that was 2.3 lastest and im using ps2 dualshock controller for ps1 play and im set Dpad in the analong stick
'

**Comment by zeromus** [comment]
he probably did change the controller configuration. We should probably fix this, but not with this incomprehensible bug.
