### ISSUE TITLE
[PSX] Incredible Crisis (Both European and USA) Hangs up at "Etusko and the Golden Pig"

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#1304]
I don't know if anyone knows this game, but it hangs up everytime it reaches the minigame "Etusko and the Golden Pig" it was suposted to play music but because it never does, the game hangs up there and won't continue.

**Comment by Spikestuff** [comment]
Obvious Question to ask. Is this working fine on mednafen?

**Comment by danylopez123** [comment]
Ok so, i finally got to that part and... it also Hangs up.
I tried this first with the European version but i feel like i dont have to do this with the USA version.

And besides, i used the most clean image possible, i got this from a PSX Re-dump pack.

**Comment by Spikestuff** [comment]
So it's an error on Mednafen's half. An upstream issue.

**Comment by Asnivor** [comment]
Yes, this is a known upstream bug in Mednafen:

https://forum.fobby.net/index.php?t=msg&goto=5043&&srch=incredible+crisis#msg_5043

Providing that you are using the latest version of mednafen, it looks like this hasnt been resolved yet.

**Comment by danylopez123** [comment]
Problem is still present in BizHawk 2.3.1

Tested with Mednafen v1.22.0-U x64 and it seems to be Fixed

**Comment by Spikestuff** [comment]
Yeah, latest updates to Octoshock didn't get implemented in BizHawk as the current version of mednafen came out a few days before release (iirc my dates correctly).
Don't worry. The PS1 core isn't the only one that needs a desperate update that's within mednafen.

**Comment by danylopez123** [comment]
Oh, ok then.
But will the Octoshock core get updated for the next BizHawk version?

**Comment by Spikestuff** [comment]
For what the bug's asking about, it's fixed in the devbuilds:
![incrediblecrisis](https://user-images.githubusercontent.com/12412764/80796688-37e7da00-8be3-11ea-88e0-6e854099b489.png)

**Comment by YoshiRulz** [comment]
How does that compare to upstream?

**Comment by Spikestuff** [comment]
1. Damn me for not providing a memory card save. Here's a raw save that hits [Bear Wars](https://github.com/TASVideos/BizHawk/files/4567112/BASLUS-01225.zip).
2. Upstream ran it without issue.
3. Hawk's latest update to the core now runs this one fine...

I'm going to finish up this game to see if it's all fine.
I'll edit this comment in a bit.
