### ISSUE TITLE
Basic Bot has problems with N64

### ISSUE THREAD

**Issue by Heath123** [TASVideos/BizHawk#1305]
The Basic Bot does not support values of over ~~8 hex digits (32 bits)~~ 6 hex digits (24 bits) for memory addresses, whereas the N64 requires ~~16 digits (64 bits)~~ 8 digits (32 bits). This crashes the Mupen64 core. If I attempt to hack in a higher value into the .bot XML file it complains that it is not an Int32. It only works if the value is hardcoded into the source itself. It also does not support floats.

The RAM Watch tool has no problems with these and properly pads addresses to the right size so code may need to be ported from this.

**Comment by zeromus** [comment]
The memory domain is set to rdram. the core is crashing because you dont understand what memory domains mean and youre probing the wrong memory with the wrong values.
if you're still working on this and need floats, add a new issue for a float enhancement request.
