### ISSUE TITLE
Bizhawk 2.3 Gambatte stops rendering frames

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#1306]
A bug in "Rubble Saver (J).gb" causes memory corruption and also - sometimes - causes the core to stop rendering new frames. It stays black even after loading a state or hard resetting. The only way to fix it is to reboot the core.

http://dehacked.2y.net/microstorage.php/info/1071068601/Rubble%20Saver%20%28Japan%292.bk2
This movie which starts from a state will cause the issue.

The bug that I'm doing is basicly: using up too many object slots. The boss in Stage 6 produces new enemies and the game fails to set a limit. Memory gets used up until it runs beyond what is normal object slot memory. This is visible at around address $C500 (System Bus).

**Comment by zeromus** [comment]
Is there any way you can test this on gambatte upstream? It seems almost impossible that this isn't an upstream core bug. There's probably no way you can test it there though.

**Comment by vadosnaprimer** [comment]
Has the recent update fixed this?

**Comment by TiKevin83** [comment]
can this be retested now that interim bizhawk is back in line with upstream?

**Comment by TiKevin83** [comment]
closing as inactive - we'd need a fresh TAS of this on devel bizhawk and not from a savestate to have any idea of whether it's still an issue

**Comment by mugg91** [comment]
I tested this for a bit in Bizhawk 2.9.1 on the Gambatte-core, first in GBC mode with official BIOS, then in GB mode without BIOS.
But I could not reproduce the issue with the screen not updating, so it must have been fixed at some point between Bizhawk 2.3 and 2.9.1.
