### ISSUE TITLE
SameBoy SGB - Left+Right and Up+Down should be banned.

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#1308]
The Super Game Boy firmware filters these inputs using the following scheme:

L+R -> no directional input
L+R+U -> only up
L+R+D -> only down
U+D -> no directional input
U+D+L -> only left
U+D+R -> only right
U+D+L+R -> no directional input

**Comment by Spikestuff** [comment]
Even though it's actually 100% possible to actually do L+R / U+D on an official controller (just extremely difficult).

And you want to know the added benefit about this era? We can check with a console verified run and can determine that these actually work on [actual hardware](http://tasvideos.org/ConsoleVerifiedMovies.html).

Also this is an emulator used for TASing. Every limitation a human has is not a limitation for TASing.
And it's down to a game by game case:
- Yoshi's Island: you can get straight to another level as a factor of the amount of coins you have. (ie you can go straight to Baby Bowser)
- Super Mario World: P-Balloons allows you to fly faster and through walls.
- Kirby Super Star: Ladders are broken.

**Comment by nattthebear** [comment]
I agree.  With the SGB part being HLE'd, it's on us to handle behaviors like this.

**Comment by zeromus** [comment]
It doesnt seem to use the same approach mrcheeze listed though. When someone addresses it in the c# code, we'll need to make sure what sameboy does, doesnt conflict

**Comment by nattthebear** [comment]
@MrCheeze I have implemented the behavior.  Are there any games that I can easily test this on, that would show some distinctive observable effect when U+D/L+R was allowed to reach game code?

**Comment by MrCheeze** [comment]
I don't have such an example, since I was using it for low level ACE stuff... should at least be easy to check that holding opposite directions always causes no movement in any game, with the fix applied, though.
