### ISSUE TITLE
Unable to configure tilt controls in GBHawk

### ISSUE THREAD

**Issue by Anonmoosekaab** [TASVideos/BizHawk#1309]
Just got BizHawk 2.3 installed and noticed that I'm unable to configure controls for GBHawk's tilt controls from "Config -> Controllers..."  Tilt controls are also missing from the Virtual Pad and TAStudio.  Is this just because they aren't fully implemented yet or is this an actual issue that needs addressing?

I did notice that BizHawk's console specific drop down menu says "GB" even though Kirby Tilt n Tumble is a GBC game, I'm not sure if this is normal behavior since I haven't used BizHawk in a while but maybe it's not letting me configure tilt controls because the menu mistakenly thinks it's a GB game instead of GBC?

**Comment by alyosha-tas** [comment]
In order for tilt controls to show up in the config->controllers menu you first need to go to the controller menu in the “GB” menu .

Select the ‘normal + tilt ‘ controller and then reboot the core.

Now you can configure tilt controls under ‘analog controls’ in Config->Controller

Please reply back if this is working for you

**Comment by alyosha-tas** [comment]
I’ll look into that in a couple weeks. I think I just forgot about it.

**Comment by alyosha-tas** [comment]
This should be fixed now. If anything else needs to be addressed with tilt controls feel free to re-open.
