### ISSUE TITLE
Updating blip_buf?

### ISSUE THREAD

**Issue by NWPlayer123** [TASVideos/BizHawk#1312]
Was poking around earlier, any reason blip_buf(fer) was never updated to the C++ version/replaced/made more versatile? Even using Wayback Machine, the site it comes from only has the C++ version.

**Comment by zeromus** [comment]
any reason it needs updating?

**Comment by Asnivor** [comment]
Looking at the changelog (https://github.com/eriser/blip-buffer/blob/master/changes.txt) the standout things between the latest version (0.4.0) and our version (0.1.0) are:

* Improved sound quality by rewriting library to use 32-bit internal sample
buffer, higher phase resolution, and a properly windowed filter kernel. Current
user code should work without changes
* Implemented workaround for MSVC++ 6 compiler limitations, allowing it to work
on that compiler again
* Added several multi-channel buffers that do panning and stereo echo
* Added sample clamping to Blip_Buffer::read_samples(), allowing higher volume
with little distortion

There are also some API and value type changes by the looks of it. Although I don't think our wrapper is implementing any of the EQ-related stuff anyways (as far as I recall), nor the BlipSynth/BlipWave generator stuff. So a transition may not be too tricky.

Sounds like it might be a good thing (to be executed by someone who has the first clue about compiling c++ and creating wrappers for unmanaged DLLs).

**Comment by zeromus** [comment]
the API is now c++, there is no C, and the APU is _considerably_ different. this isn't worth the trouble unless someone comes up with a compelling reason. they can open another ticket later, unless @NWPlayer123  has a compelling reason, then reply here
