### ISSUE TITLE
SMSHawk - Double Dragon (GG) badly glitched

### ISSUE THREAD

**Issue by Asnivor** [TASVideos/BizHawk#1320]
In master branch - probably the result of the recent Z80 accuracy improvements.

Moved from #1297

Example: 

![image](https://user-images.githubusercontent.com/7911038/45482463-0be5bf80-b746-11e8-8480-bde95204260f.png)

Double Dragon (UE)
SHA1:BAEBE28FC7549CBB06C94FCB36A3C40231933C01
MD5:B45D73E40CE8F6E76DCED24EE921871A

**Comment by Asnivor** [comment]
Duplicate of #1157

**Comment by alyosha-tas** [comment]
It is very highly likely that the game just needs to be given some cart ram in the gameDB. I just never got around to it.

**Comment by Asnivor** [comment]
ive tried adding: SRAM=8192 in the right place in the gamedb_sega_gg.txt file (in the correct place), but this doesnt seem to make any difference.

Unless I am doing something wrong?:
![image](https://user-images.githubusercontent.com/7911038/45548579-b8927080-b81c-11e8-9e61-7c79ad5c804b.png)

**Comment by alyosha-tas** [comment]
Are you sure in looks like that in the local game DB file and not just the project file? I only ask because I made that mistake many times.

I tried looking online but there doesn’t seem to be anything special about Double Dragon, and a plain background is indicative of missing SRAM.

**Comment by Asnivor** [comment]
Yup, you were right (although I was SURE i was editing in the right place - although clearly not).

This is now working
