### ISSUE TITLE
Space Invaders (N64) won't boot

### ISSUE THREAD

**Issue by Shima33** [TASVideos/BizHawk#1329]
Hangs on a black screen at 38 frames with the verified good ROM, unverified ROM's continue onwards but either have all of their frames as lag frames or half of their frames as lag frames. None of them advance past a black screen on boot.

Tested with the latest DEV build.

The PS1 version of the game works, so it's an issue with the N64 version.

**Comment by Glitcholog** [comment]
Can confirm , its simply a black screen (game doesn't boot)

**Comment by Shima33** [comment]
It seems like the latest Mupen64Plus core has resolved this issue - now it's just waiting for the devs to transfer the latest Mupen core over to Bizhawk.

**Comment by vadosnaprimer** [comment]
Test in dev build please.

**Comment by Shima33** [comment]
This has been fixed ever since the latest Bizhawk version.
