### ISSUE TITLE
PCEHawk now blinks constantly while unthrottled (Doesn't happen in 2.2.2)

### ISSUE THREAD

**Issue by synnae** [TASVideos/BizHawk#1333]
Pressing Turbo (or Toggle Throttle) now causes PCEHawk to blink/flicker constantly as of version 2.3.

Steps to reproduce:
1. Load any PCE game.
2. Press Turbo (default key combo is Shift+Tab), or Toggle Throttle.
3. Watch as the game flickers repeatedly.

This doesn't happen in 2.2.2 or any version under it.

And yes, already tested in the latest dev build (2018-09-19 as of the time of this post). Still the same.

**Comment by Asnivor** [comment]
Bisect shows that it is this commit again:

https://github.com/TASVideos/BizHawk/commit/aa7cee1bb7d123f5ed9c136554bb8fae7d9d9b37

**Comment by Asnivor** [comment]
I've done the revert locally and tested and it appears to have fixed all the issues caused.

I'll push to master and ask users to test in the other tickets

**Comment by Asnivor** [comment]
@synnae This looks OK to me know. Please test in the latest dev build:

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by synnae** [comment]
@Asnivor I tested it and everything seems fine now. Thanks for the fix!
