### ISSUE TITLE
Robopon doesnt load

### ISSUE THREAD

**Issue by EvilThorn** [TASVideos/BizHawk#1335]
Robopon Sun Version fails multiple attempts to load the rom. Tried it on another emulator and it worked fine.

**Comment by Glitcholog** [comment]
Just so people know, Robopon Sun Version is a Japanese only Game Boy Color game. I can confirm that this game and its other version (Robopon Moon version and Robopon Star Version) quit before the game even start with the following error, but bizhawk doesn't crash

![fffffffffffffffffe](https://user-images.githubusercontent.com/24578279/46116117-6b24e480-c1c8-11e8-91b9-45cb92e9e955.PNG)

**Comment by EvilThorn** [comment]
It still doesnt work with GBHawk.
how can i tell what mapper it uses?

**Comment by Asnivor** [comment]
The libretro docs site also list this game as not working in gambatte:

> Robopon: Sun/Star/Moon Version | Crashes on start. Unemulated HuC3 mapper.

https://docs.libretro.com/library/gambatte/

I see a mapper file for the HuC3 in GBHawk, but it's insides kind of look like the default mapper (to my untrained eye), so perhaps it isnt implemented yet/correctly (or something else is wrong)?

**Comment by alyosha-tas** [comment]
Knowing that it’s huc3 will help me get it implemented thanks .

**Comment by alyosha-tas** [comment]
HuC3 is now implemented. I haven't tested the RTC thoroughly, and IR functions are missing entirely, but the basics are there for testing.
