### ISSUE TITLE
GB in GBC becomes monocrome when loading a state

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1337]
Just as the title says. Also happens in DualGambatte.

How to trigger it:
1. Open a GB game
2. GB > Settings... > Console Mode > GBC
3. Reboot core
4. Play the game until the GBC BIOS screen has finished displaying
5. Save a state
6. Load that state.

This doesn't cause any emulation problem, it's a purely aesthetic bug, though I personally find it annoying while I work on a movie. I hope that it will be easy to fix.

**Comment by alyosha-tas** [comment]
I am unable to reproduce this. I tested with the homebrew game retroid.gb
Does this only happen for specific games?

**Comment by alyosha-tas** [comment]
I have found no conditions under which I can reproduce this bug, please reopen with more details if this still happens in the dev build
