### ISSUE TITLE
BizHawk won't start on Windows 10.

### ISSUE THREAD

**Issue by mrtmaxim** [TASVideos/BizHawk#1338]
It worked fine before, but after an update 1809 EmuHawk.exe just won't open.

**Comment by Sappharad** [comment]
Microsoft pulled the 1809 update because it was deleting people's files.

Have you tried re-installing the prerequisite installer and re-downloading BizHawk? It's possible something you needed got deleted by the updating.

**Comment by mrtmaxim** [comment]
Yes I have, but without result.

**Comment by Glitcholog** [comment]
I tried bizhawk after the recent update and didn't have any issues. What exactly happen when you open it (an explanation or a screenshot would be useful)

**Comment by mrtmaxim** [comment]
The point is that nothing happens. BizHawk process just appears in Task Manager for a moment and that's all.

**Comment by Sappharad** [comment]
Open "Event Viewer" (open the start menu and start typing) and look at the error message. If it's not obvious, then paste the error here.

**Comment by mrtmaxim** [comment]
![error](https://user-images.githubusercontent.com/43931457/46585772-bd45ef80-ca7d-11e8-976d-5c51e5dd8dcc.png)

**Comment by NarryG** [comment]
Have you updated your gpu drivers since you updated? Without digging into the code, a dx9 exception screams a compatibility issue (assuming you reinstalled the prereqs to ensure dx9 into place)

**Comment by mrtmaxim** [comment]
I have an old radeon hd 5870, so I haven't updated gpu drivers recently. I've reinstalled the prereqs several times.

**Comment by zeromus** [comment]
This can be caused by having a garbage slimdx installed in system32. Delete any slimdx found anywhere on your system that isn't in a subdirectory of a games-ish software.
