### ISSUE TITLE
[FEATURE REQUEST] more code/data loggers for more cores

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1343]
Code/Data Logger for GBHawk/SameBoy cores (currently available only for Gambatte/BSNES) cores respectively).

**Comment by g0me3** [comment]
I can use BSNES core for both SNES and GB in SGB mode, but GB in SGB mode on BSNES way too slow even on my gaming pc.

**Comment by Asnivor** [comment]
SameBoy looks like a waterbox core, so not sure if it presents anything that a CodeDataLogger implementation could use.

GBHawk should be possible and NESHawk also has a non working CodeDataLogger implementation #1274

I did take a quick look at the NESHawk one a while ago but its still a little beyond my scope (and time) at the minute.

**Comment by g0me3** [comment]
NESHawk does not needed, since there is a FCEUX with full functionality..

**Comment by zeromus** [comment]
Why do you need gbhawk? You already have gambatte.
I know why you need sameboy, it's because GB on SGB on BSNES is too slow.

**Comment by zeromus** [comment]
What if I just fix CDL for neshawk? Will that make you happy?

**Comment by g0me3** [comment]
that is what me exactly requested in this issue ;)

**Comment by zeromus** [comment]
Ughhhh. This has to be done for every mapper. Tell me what mappers you need so I can set it up just for those and we can leave it as an exercise for future people to set up mappers they need based on the given examples. The mapping logic is basically an exact replica of the ReadPRG and similar functions in each of 1000 mappers, but that's too many files to touch now.

**Comment by g0me3** [comment]
if you mean game boy and gambatte core then i'd like t o have all mappers (5-6 in total). if you mean NEShawk, then don't bother, FCEUX does it just fine already, no need to add logger to NES here.

**Comment by g0me3** [comment]
gbhawk core*

**Comment by g0me3** [comment]
not gambatte sorry ) but  I asked for GBhawk core cdl support, not NEShawk..

**Comment by g0me3** [comment]
seems working, but as soon I disabled the data base wisdom three roms aren't load even in gbhawk core lol.

**Comment by alyosha-tas** [comment]
I don’t get what you mean. What are you doing and what behavior are you expecting? Right now the wisdom tree roms are hard coded into GBHawk since they didn’t give their mapper a unique identifier in the header , is that what you are disabling somehow?

**Comment by g0me3** [comment]
then I have no idea why my Joshua rom does not start and just hangs after bios logo. The same for both Gambatte and GBHawk cores. I thought when I commented out the GB/GBC databases in confog, they aren't recognized, but now I see some hardcoded checksum tests inside the code. Maybe my Joshua rom not in the list of hardcoded hashes...

**Comment by zeromus** [comment]
Joshua Rom is a cool name for a band

**Comment by g0me3** [comment]
got it lol. md5 hash is UPPER case, but my particular hardcoded hash in code is lower case lol and does not pass the test. https://www.dropbox.com/s/92tjsurk8n0912p/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-11-15%2016.01.23.png?dl=0

**Comment by g0me3** [comment]
Also I'd like to reopen this issue, because I still need the same boy core for GB in SGB mode since the BSNES still crashes with when CDL active.

**Comment by g0me3** [comment]
fixed case for hash of my Joshua rom but still have no get it running. log for some reason writes "using wisdom tree mapper" then "Mapper MBC1" and hangs after bios...

**Comment by g0me3** [comment]
probably my Joshua rom is actually bad... need to find the regular one from no-intro then
