### ISSUE TITLE
[FEATURE REQUEST] Hex Editor "Options-Memory Domains" setting save

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1345]
Currently this setting does not stored in config file and always reset to default option "WRAM"

**Comment by g0me3** [comment]
done it myself lol, closed

**Comment by g0me3** [comment]
whoops wrong issue lol

**Comment by Asnivor** [comment]
Related to this kinda: https://github.com/TASVideos/BizHawk/issues/508

I guess some way to store tool prefs on an individual basis might be a good thing.

**Comment by g0me3** [comment]
the easiest way I see here is to make "System Bus" option default instead of WRAM. most of the time this only option is used at least by me and allow to access any cpu area address without need to switch them and actually by its full proper address not the cropped offset...

**Comment by vadosnaprimer** [comment]
I'd prefer to simply remember the last used domain.
