### ISSUE TITLE
[FEATURE REQUEST] Code-Data Logger auto load existing .CDL file 

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1346]
there is an auto-start feature for CD Logger already, auto save feature for CDL file, but does not have auto load CDL file at start like it implemented in fceux.

file name to load may be auto selected by the current rom file name (<rom name>.cdl) or base on the data base entry name...

**Comment by vadosnaprimer** [comment]
File - Recent - Autoload.

**Comment by g0me3** [comment]
also note, I'm running files from explorer as associated with emuhawk by double click. in this case auto start for cd logger works properly.
if you start emuhawk first then open any rom with "Open File" option, cd logger does not start automatically even if all autoload checkers are on. so does the same with recent option if you start cd logger manually after that lol it won't autoload.

**Comment by vadosnaprimer** [comment]
Crashing is better than total lack of some functionality, because it's usually trivial to reproduce and fix. I'll look into it, but can't guarantee the timeframe. You might want to speed this up by running hawk in visual studio when this happens. May be easier to fix than we think.

**Comment by g0me3** [comment]
ok, https://imgur.com/a/7OPQ2ku see crashes because of path variable cannot be empty for some reason, but it is empty if accessed via autoload, not manual load

**Comment by g0me3** [comment]
as I said, recent-autoload option not for load cdl file for current gb rom by name lol it is for load last recent cdl file used... where there are no used files, the path is empty so it will crash.

so for sure this option is not an option for me, sorry for каламбур лол

**Comment by g0me3** [comment]
it seems even if there is a file in recent list and autoload option is on, the actual data isn't loaded or maybe cleared when the cd logger starting..

**Comment by g0me3** [comment]
the mess is just because I tried to answer the questions by feos lol

the main issue is clear enough in the main topic

the auto start option for CDL just activates the logger with an empty data file.

I request the feature like in fceux. whenever I load the NES file via fceux it fetch the file name I open, and tries to open the .cdl file with the same name for the CDL logger started also automatically...

bizhawk does not work the same. it just opens the CD logger and activates is. no files are loaded...

**Comment by zeromus** [comment]
errrr.. let me know if this isnt working well enough for you now

**Comment by zeromus** [comment]
I don't want to add a special feature just for this tool which guesses to open a CDL file based on the name of the current rom. Do any other tools in bizhawk work this way? I know that's how bizhawk works, but we decided in bizhawk to not have the strict association between roms and debug documents.

If you want that special feature, what the hell are we going to call it? We already have two autoloads and an autostart. AutoOpen Specially Named CDL File Just For This Rom?

**Comment by g0me3** [comment]
call it "auto resume" just like in FCEUX. what I'm asked before is just to continue logging automatically if there is a cdl file already with it. don't know why you added all these auto-load options that does not load anything anyway lol. remove all these and just give me auto resume logging feature I used to have in FCEUX.

**Comment by zeromus** [comment]
I didn't add those features, they get added by our tool framework. This works the same as any other tool. They just werent working before due to some small misadjustments. Now they work the way they were intended to.

**Comment by zeromus** [comment]
ok as requested, "auto resume" added to "auto load" "autoload" "auto start" and "auto open"

**Comment by g0me3** [comment]
can't see any difference. option does nothing. if recent files auto load unckecked no cdl files loaded. also when closing emu this stores "null" name in recent cdl files and then throw an exception every time you try to open the recent menu unless you manually remove this "null" name from configs, then it read it again lol

**Comment by g0me3** [comment]
"then it write it again"*

**Comment by g0me3** [comment]
seems fixed now
