### ISSUE TITLE
[TAStudio] [Lua request] Lua function to clear TAStudio's Greenzone

### ISSUE THREAD

**Issue by nlburgin** [TASVideos/BizHawk#1347]
It would be nice if there was a function you could call from a Lua script to clear the greenzone, instead of this action being only accessible from the GUI.

Since TAStudio occasionally hangs when the greenzone is full and old states need to be culled to make new ones, at least on N64 (I'm assuming this is a known issue, but if not I could try putting together a separate bug report for that), it would be nice if I could just make a workaround script that ensures this won't come into play when doing long, unattended syncs under TAStudio. 

I assume there'd be other uses for this as well, though I admit I can't think of any offhand.

**Comment by vadosnaprimer** [comment]
Correct, it's fixed in the dev build that's available from the main page of the repo.
