### ISSUE TITLE
Emulator crashes when SM64 rom is loaded

### ISSUE THREAD

**Issue by ofhl** [TASVideos/BizHawk#1352]
I'm new so I don't know why, the file is compatible with BizHawk (.z64)

**Comment by zeromus** [comment]
Have you tried ANY other game? Either the file you're loading is garbage, or you are unable to load any n64 game due to bad GPU drivers and the default n64 GPU plugin. Change the default N64 GPU plugin in bizhawk, or change config > display > display method to avoid provoking a broken GPU driver.
