### ISSUE TITLE
[Feature Request] Default NESHawk over QuickNES

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#1353]
We're at Hawk 2.3 and we still default to QuickNES after all this time with the more accurate/better core being behind Config > Cores > NES (as we all know).

People (and those out of the loop) are only using QuickNES for TASing because they think that the default is the recommended one.

There's two methods.
Obviously default the core to NESHawk or do what you have when users are running snes9x and not BSNES.
![image](https://user-images.githubusercontent.com/12412764/47100616-ab392d80-d283-11e8-802c-9c0e6fe74a4e.png)

**Comment by synnae** [comment]
I'd recommend doing it in the sytle of the Snes9x/BSNES warning. Keeping QuickNES as default is good to prevent BizHawk newcomers from coming here and complaining that NES is too slow. Lots of people (the masses) use the emulator only to play casually, and if they really want to TAS, then the warning should be enough to ensure no mistakes.

**Comment by zeromus** [comment]
Yes, we should do that

**Comment by adelikat** [comment]
Until we FIX the dialog back to where you can choose snes9x (or quicknes), I reject this idea and will revert any attempts to do this.

There's good reasons to use quicknes, TAS movies like http://tasvideos.org/3184M.html would have taken many years to complete on Neshawk.  Meanwhile it doesn't suffer from any noticeable emulator differences (maybe a few frames of lag are different here and there).

It's one thing to put in nags for the benefit of tasvideos ideology but it is another to outright reject using emulators that are perfectly capable of making a recording (both of these cores have rock solid savestates and decent emulation).

**Comment by adelikat** [comment]
Ok, So I added the nag for quicknes but I also fixed it so that you can continue to record snes9x and quicknes movies.
