### ISSUE TITLE
keep losing saves

### ISSUE THREAD

**Issue by MissKitten** [TASVideos/BizHawk#1356]
i'm not that great with computers and such but i did somehow manage to get bizhawk and get the zoot randomizer working. i'm not sure what i'm doing wrong but have the time the saves work and other times it doesn't save and i lose my data from the day before. i don't know if i doing something wrong but i really need help i don't want to have to keep replaying parts because it didn't save properly.

**Comment by vadosnaprimer** [comment]
What and how exactly are you saving?

**Comment by GabrielSorensen** [comment]
I'm going to add this here. But I'm also experiencing this occasionally but seemingly random with tastudio saves, usually after getting this exception but not always. I haven't been able to track down the cause.

Using the dev build from 2018-10-10.

[TAStudioException11-15.txt](https://github.com/TASVideos/BizHawk/files/2587875/TAStudioException11-15.txt)

**Comment by vadosnaprimer** [comment]
@MissKitten and @GabrielSorensen, your bugs are different. Are they still happening with the dev build (linked from the [readme](https://github.com/TASVideos/BizHawk))? If so, please record a video, I won't be able to reproduce it otherwise.

**Comment by vadosnaprimer** [comment]
Can't figure out what the original problem is or how to reproduce it. The second problem is a dup of #1581.
