### ISSUE TITLE
I lost all of my firmware

### ISSUE THREAD

**Issue by maxsize213** [TASVideos/BizHawk#1358]
I tried to do the same thing that fixed for months (by using the zip file) and it didn't work. I wanted to try and play Sonic 1 on the Master System, but it didn't work and now I can't play ROMs.

**Comment by hegyak** [comment]
The Firmwares are Copyrighted Material, and as such can't be distributed legally with BizHawk.

**Comment by vadosnaprimer** [comment]
I have absolutely no idea what this issue is about.

**Comment by Glitcholog** [comment]
Im guessing this has to do with the fact that the he might have a problem that bizhawk reset the path of his/her firmware and he's not able to play his game anymore because he can't use the zip method anymore? (ZIP are not working on my side either, but the image or bin itself does)
