### ISSUE TITLE
Bizhawk crashes when loading a movie for Link's Awakening

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1361]
with no explanation, loading a movie for both versions of Link's Awakening (both GB and GBC versions) instantly crashes bizhawk.  No error message pops up or anything.

**Comment by zeromus** [comment]
don't bother to supply the movie that crashes it. the input that makes something crash can't possibly be helpful in investigating the crash

**Comment by alyosha-tas** [comment]
I'll assume this is related to the post here, which uses a glitchy Gambatte version:

http://tasvideos.org/forum/viewtopic.php?p=476457#476457

If this still happens in the dev build please reopen with more details.
