### ISSUE TITLE
PCEHawk can crash due to invalid DMA resulting in an out of range read

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1363]
![image](https://narry.land/zwKLaA.png)

Call stack (old version of Bizhawk but the code in question hasn't changed)
``` 	
BizHawk.Emulation.Cores.dll!BizHawk.Emulation.Cores.PCEngine.VDC.UpdatePatternData(ushort addr) Line 271	C#
 	BizHawk.Emulation.Cores.dll!BizHawk.Emulation.Cores.PCEngine.VDC.RunDmaForScanline() Line 231	C#
 	BizHawk.Emulation.Cores.dll!BizHawk.Emulation.Cores.PCEngine.VDC.ExecFrame(bool render) Line 95	C#
	BizHawk.Emulation.Cores.dll!BizHawk.Emulation.Cores.PCEngine.PCEngine.FrameAdvance(BizHawk.Emulation.Common.IController controller, bool render, bool rendersound) Line 28	C#
```  

Note: To cause this, I had to override read-only on the 21-bit bus and then I fuzzed it. That doesn't mean a buggy game couldn't cause the behavior though.

**Comment by zeromus** [comment]
one of you guys ought to be able to fix this pretty easy...

**Comment by zeromus** [comment]
More likely it needs to be masked down by 1 bit

**Comment by Asnivor** [comment]
Ahh ok. Thats a much better idea as its almost certainly what would happen on real hardware.

**Comment by Asnivor** [comment]
This should now be fixed in the latest dev build.

@NarryG If you do happen to be able to break this in the same way as before, please reopen this issue.
