### ISSUE TITLE
Arkanoid paddle not working.

### ISSUE THREAD

**Issue by WDude** [TASVideos/BizHawk#1366]
Version: 2.2.2
Neither NesHawk nor QuickNES are simulating Arkanoid's controller via mouse input.

Yes, I looked through the forum to see if this has been addressed, nothing pops up with "Arkanoid" as the keyword.
Yes, I keep rebooting the core to try out other ports.
Yes, I have the paddle configured for port 2
The game manual explicitly states it should be plugged in port 2.

Oddly enough, when I go to the menu: View >> Display Input, the mouse input is being recognized, and shows the X Coordinate of the wheel/knob and left mouse click shows the paddle button being tapped.

In addition, I can run Arkanoid fine with FCEUX with the paddle.

**Comment by zeromus** [comment]
Works fine for me in neshawk. Right out of the box, in fact, with mouse X and click bindings. Once switched to neshawk and port 2 changed to paddle, tht is. Of course, it can't work in quicknes; I can't even see how you would have set the arkanoid paddle for quicknes.

**Comment by zeromus** [comment]
I tested on 2.2.2 and wrote the exact steps I did. I didn't have to set the famicom expansion, or check the famicom box. 

Those extra options at the bottom work. I have no idea why they don't work for you.
