### ISSUE TITLE
GBS and GBCS bios in GBHawk

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#1369]
What are these bioses? Theyre not in the firmware DB. Did you forget to commit firmware DB file?

**Comment by alyosha-tas** [comment]
Oops, my bad. Those are the sameboy bioses that I use for my internal testing since they are faster. I didn't intend them to get into the official builds.

Maybe down the road I'll add support for unofficial BIOSes (A7800 and Coleco would benefit from this for casual play) but not now.
