### ISSUE TITLE
Minor TAStudio Bugs

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1370]
I noticed a couple minor bugs in TAStudio that I thought I would write down before I forget them.

Although they are minor the solutions to them are probably non-trivial (or at least they are to me since I couldn't figure out how to fix them.)

1. When controller buttons are tied to left mouse button. they can get stuck when pressing the 'recording mode' check box. This happens after pressing the left mouse button back in the main window. I tried briefly to debug but I have no idea what's going on.

~~2. When placing inputs by click and drag, it silently disables recording mode without unchecking the box. I have no idea how the heck to access the box to uncheck it.~~

~~3. When you are on frame 1, you cannot hit '<' to go back to frame 0. I don't know how I never noticed that before.~~

**Comment by alyosha-tas** [comment]
3 comes from MainForm.cs here (line 4443):

```
runFrame = true; // TODO: the master should be deciding this!
Master.Rewind();
```

Guess that's why it has a TODO. runFrame needs to be false when you want to be at frame 0

**Comment by vadosnaprimer** [comment]
Pretty sure #3 was broken by https://github.com/TASVideos/BizHawk/commit/d4a48a8ee1cd9bc5a08b236c5afce6f0a57bf54c which should just be reverted. See if you have the bug before that commit.

**Comment by alyosha-tas** [comment]
Nope that's not it. The bug exists both in 2.3 and 2.2.2.

I mocked up a solution like this: Master.rewind(ref runFrame) where runFrame would be set to false if the result of rewinding puts as at frame 0 and that worked as expected.

Once again though it touches a lot of things, so i'm not overly eager to commit anything.

**Comment by vadosnaprimer** [comment]
>     1. When controller buttons are tied to left mouse button. they can get stuck when pressing the 'recording mode' check box. This happens after pressing the left mouse button back in the main window. I tried briefly to debug but I have no idea what's going on.

I can't imagine a way to fix it, you can't productively control tastudio without mouse clicks. Similarly you could bind all mouse buttons (and movement) to game controls and wonder why nothing works in tastudio.

**Comment by alyosha-tas** [comment]
It seems to be a bug caused by change of window focus. BizHawk recognizes the start of the click as happening in the game window, but if the click is on another BizHawk window, the focus changes and the system doesn't recognize the end of the click to end input.

As the title indicates it's a minor bug, if it's too intractable to solve feel free to close it.

**Comment by vadosnaprimer** [comment]
If it's now only about one bug, please fix the issue name, since I have to open it and read the whole thing every time I forget what it is about.

**Comment by alyosha-tas** [comment]
This isn't a TAStudio specific issue, so I'll close this and make a new issue
