### ISSUE TITLE
YoshiRulz portability commit broke opengl display method

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#1384]
@YoshiRulz 

https://github.com/TASVideos/BizHawk/commit/ca021d96cc89235df272c067ce6a2d8abeba22ec

This commit broke opengl display method because you didnt update OpenTK.GLControl.dll at the same time you updated OpenTK.dll. Please update the GLControl dll and fix whatever bugs appear consequently

**Comment by YoshiRulz** [comment]
Does it work now?

**Comment by zeromus** [comment]
seems to
