### ISSUE TITLE
Bizhawk 2.3 ArgumentException was thrown: The sum of offset and count is greater than the buffer length.

### ISSUE THREAD

**Issue by tommai78101** [TASVideos/BizHawk#1385]
System Specs:

* Windows 10 Pro 1803 (Non-Insider)  
* Nvidia GeForce GTX 860m   
* Intel Core i5-4210U
* 8GB of RAM

Game being emulated:

* River City Ransom EX (GBA)

Emulated Core:

* Using mGBA

Bizhawk version:

* Version 2.3.0 (x64), June 23, 2018.
* Commit af9d1bd

How to reproduce:

* It appears sporadically, but it seems to be affected by the audio. It depends on how far I am to playing the audio while the emulation is running, and it would appear pretty soon after that.

![image](https://user-images.githubusercontent.com/6444116/49334668-1e370300-f5a9-11e8-9ad0-551b43ad304a.png)

> System.ArgumentException: The sum of offset and count is greater than the buffer length.
   at SlimDX.Utilities.CheckBounds(Int32 lowerBound, Int32 size, Int32 offset, Int32& count)
   at SlimDX.DirectSound.SoundBuffer.Write[T](T[] data, Int32 startIndex, Int32 count, Int32 bufferOffset, LockFlags flags)
   at BizHawk.Client.EmuHawk.DirectSoundSoundOutput.WriteSamples(Int16[] samples, Int32 sampleCount)
   at BizHawk.Client.EmuHawk.Sound.UpdateSound(Single atten)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by tommai78101** [comment]
Wait, so I can't report stable build issues anymore?

**Comment by vadosnaprimer** [comment]
Well that's not how bizhawk happens to work. We do release hotfix versions if the thing that's broken is critical to the workflow of tasing or is just otherwise really damaging (like deleting your files), but that doesn't happen too often.

**Comment by tommai78101** [comment]
I see now. Will try the dev build then.

**Comment by tommai78101** [comment]
Even tried rebooting the PC, Bizhawk doesn't run nor open at all on the latest dev build.

**Comment by adelikat** [comment]
Are you trying to reuse an old config file? I think the new version isn't compatible with 2.3 configs

**Comment by zeromus** [comment]
@nattthebear Are we still having weird issues where cores can send us enormous numbers of samples in one burst? Was it gambatte that did this or was it always mgba? I dont know how we fixed it in those old cases.. but an easy "fix" for now is to have the sound output modules discard writes which exceed the entire buffer size

**Comment by nattthebear** [comment]
Any not-completely-garbage sound output system could handle this trivially.  Just buffer the remaining data until it's time to output it.

**Comment by zeromus** [comment]
It's not clear that's the correct behaviour. What if the samples are excess, rather than just unexpectedly bursty? Buffering them would just add irrevocable latency

**Comment by tommai78101** [comment]
@zeromus I didn't get really far. Very near the intro to the River City Ransom EX game, within 5 seconds of running the emulator.

**Comment by zeromus** [comment]
works fine for me on latest. use buildbot build. mgba core has been updated since 2.3

**Comment by NarryG** [comment]
Last time I ran into this it was the result of me lowering the audio buffer to the point where it actually underflowed.

**Comment by zeromus** [comment]
Yeah, I think due to the sensitivity involved, using non-default buffer sizes voids your warranty. In this case natt is right, though; it could be corrected.. most simply probably by catching it, panicking, and increasing the buffer size beyond the user's specifications after all

**Comment by nattthebear** [comment]
Just to make sure I'm understanding the situation right, we should have two sound modes; sync to audio, and don't sync to audio.  If "too much" data comes in on sync to audio mode, then the audio output should block until that extra audio is output and we're back down to normal buffer levels internally.  If "too much" data comes in on unsynced mode, then the audio driver should silently drop it.

In either case, if not enough data comes in, the audio driver must insert silence.

**Comment by tommai78101** [comment]
@zeromus Thanks. Will do.
