### ISSUE TITLE
TAStudio exception on open in latest dev build

### ISSUE THREAD

**Issue by Asnivor** [TASVideos/BizHawk#1388]
Happens with any core I try. I load the ROM, then Tools -> TAStudio

![image](https://user-images.githubusercontent.com/7911038/49441903-c9210a00-f7bf-11e8-9b6d-d3cada947a1a.png)

If I click continue TAStudio opens.

When debugging in VS2017 Pro the same thing happens (although I cannot continue past the error).

![image](https://user-images.githubusercontent.com/7911038/49442310-0d60da00-f7c1-11e8-9481-4953ddd7aadd.png)

At this point TASMenu.Items contains:

![image](https://user-images.githubusercontent.com/7911038/49442463-7e07f680-f7c1-11e8-92cd-cc160ffa02b4.png)

and the DropDownItems property of {&Settings} is:

![image](https://user-images.githubusercontent.com/7911038/49442594-db9c4300-f7c1-11e8-8b97-7d48361d790b.png)

@vadosnaprimer 
It looks to me as if 'SettingsSubMenu' has been changed to '&Settings' at some point and the Tastudio_Load() method not updated to reflect this. But its TAStudio, so I aint touching nothing until this is confirmed correct :)

**Comment by Asnivor** [comment]
Although, I can find nothing in blame. Maybe this has always been here but I am only noticing since upgrading to Windows 10 and VS2017 Pro?

**Comment by vadosnaprimer** [comment]
Heh I did change `Settings` to `View`.

**Comment by Asnivor** [comment]
Ok, bisect shows this as the problem commit:

```
731584344d7dda790a9346f5ecc0b46b9c0be6cf is the first bad commit
commit 731584344d7dda790a9346f5ecc0b46b9c0be6cf
Author: feos <feos-theos@yandex.ru>
Date:   Mon Dec 3 22:33:42 2018 +0300

    tastudio: BranchesRestoreEntireMovie and LoadBranchOnDoubleclick

:040000 040000 a92cbe46eb1701ef30972c44e7763e3e64fa5f82 8c1f6e8a75b04bd0df67a7ddb795fdd3af81ce97 M  BizHawk.Client.EmuHawk
```
