### ISSUE TITLE
Streets of Rage (5 in 1 SEGA classics) freezes on level 5 boss

### ISSUE THREAD

**Issue by kossmikman** [TASVideos/BizHawk#1390]
The game will lock up when the level 5 boss is supposed to spawn, similar to this issue brought up [here](https://bitbucket.org/eke/genesis-plus-gx/issues/425/problem-with-sega-sega-classics-arcade).
The issue seems the have been [fixed](https://bitbucket.org/eke/genesis-plus-gx/commits/56f3d64265b33ad654d24f44b76d7b37af525e38) yet it still occurs in BizHawk using the Genplus-gx core.

**Comment by Asnivor** [comment]
The upstream issue was resolved with something like "couldn't replicate the issue", so its potentially still a problem in either place.

**Comment by kossmikman** [comment]
That's odd. It has happened to me every time (i tried 3 times) on various disc images. I was using Blaze as the character, so maybe it has something to do with it since level 5 bosses are just palette-swaps. I will try with other characters.

**Comment by Sun-in-jang** [comment]
Freezes also on the level 3

Sega Classics Arcade Collection (USA) (RE) (4-in-1)
