### ISSUE TITLE
Filetype class desc. does not match filter in open rom window

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#1392]
The one example I found was `.d64` files being hidden when showing only Commodore 64 roms. Obviously the list of extensions should reflect what's being filtered for.

OS: Win10 Home 1709; Manjaro kernel `4.19.4-1-MANJARO`.

**Comment by Asnivor** [comment]
I suspect something got lost when moving C64Hawk from dev to release (as there are separate extension lists for each for some reason).

Should be a very simple fix. I'll take a look tomorrow if someone doesn't beat me to it.

**Comment by Asnivor** [comment]
Hmm, looks there there are actually more than two places (maybe more than 3) where rom extensions are set. Bizarre. Means I might have to check my own core as well to see if I missed something...
