### ISSUE TITLE
window too small to use

### ISSUE THREAD

**Issue by nanogram** [TASVideos/BizHawk#1400]
I am attempting to run marI/O neural network lua on bizhawk. but an issue i am running into is it launches an extremely unscalable window(image below)
[https://imgur.com/a/0TNsepb](url)
is this a bug or something? not sure why it cant be scaled at all

**Comment by vadosnaprimer** [comment]
High DPI? Win10 fuckes up a few of our dialogs in some cases
https://github.com/TASVideos/BizHawk/issues/1151

**Comment by zeromus** [comment]
strip it down to a minimal test case that doesnt require the full bulk of mari/o so it's an actual bizhawk bug and not "I can't make mari/o work" user error
