### ISSUE TITLE
GBHawk doesn't find default binds

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1403]
Looks like at one point the controller was changed from ~~Standard~~ Gameboy Controller to ~~Standard~~ 
 Gameboy Controller H and the default binds weren't updated alongside it for GBHawk.

**Comment by nattthebear** [comment]
"Standard Controller H"?  Hi-C?  Happy?  Horus?

**Comment by nattthebear** [comment]
The entire point of changing the `Name` is to change all of the binds so they aren't stored together.  It sounds like the GBHawk controller (and all variants) should probably just have the normal Gameboy Controller name.

**Comment by alyosha-tas** [comment]
It originally was the same. I changed it because something in virtual pad broke if I remember right.
