### ISSUE TITLE
[CDL] SNES (BSNES core) does wrong flagged logs sometimes

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1409]
I'm not sure whether this is not an internal SNES core specific "error" or actually a bug in logger code. But I see some portions of data marked with FirstExec (01) flags sequentially. It seems this flag somehow mistakenly overwritten with either the wrong log flag or maybe even just wrong value for flags. sometimes it gets value 02 (also sequentially) and even 03 or 07 which are not a valid flags combinations....

example, log Lawnmower USA ROM, then check 0x38000, 0xA0000 or 0xB4000 (there are more of them)…

**Comment by g0me3** [comment]
bumping this since there is a possibility to compile waterbox cores now...

**Comment by zeromus** [comment]
I tried 0x38000 in lawnmower man and got a nice series of "01020202 0102 01020202"
the other addresses were all clear.
I did not see any 03 or 07 until I got to WRAM. Of course the game may rewrite the contents of WRAM with multiple subroutines or data so you could have any kind of mess in there.

Even with cartrom I don't agree that this is strictly an invalid combination--a game that's going nuts at bootup and possibly recovering may accidentally execute code wrongly. 

Maybe I fixed it with some of the other commits I'm about to do?

Do any other games exhibit this problem? If not, it would be indicative of a game going nuts and flirting with crashing as I mentioned for CARTROM in this case

**Comment by g0me3** [comment]
ok, i see something is changed definitely, maybe it fixed already by some other fixes... will try carefully and reopen the issue if I find it again after adding a new XM flags to my ida script and will see if the code now is disasmed just fine.

**Comment by g0me3** [comment]
Ok, rechecked this...
https://www.dropbox.com/s/53ec9h2h94wo1d2/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202020-01-22%2020.26.16.png?dl=0
here what I mean. see, this is a data bank, but I see series of 01 wich is must be opcode, but all opcodes should be 1-byte long, since there are no 02 (operand) flags there. anyway, there are no code at all. 

as I checked before, there some places in bsnes core where cdl flags does not reinitialize when updating the data byte. so it get the previous initialized flag value. this may be the dma data or data read by some indirect operand, but the flags set is what appears to be last operand used flags not the actual data read flags.

**Comment by g0me3** [comment]
also note, there is an end of previous bank empty rom filler marked with 02 flags (operand) only lol. last used byte in this bank is an opcode operand. so it seems instead of clearing the flags the cdl ogger used last initialized operand flag till the end of a bank.

**Comment by g0me3** [comment]
as I see any log store operation need the flags be set first. sometimes this is not happen and previous flag value is used.

**Comment by zeromus** [comment]
So tell me what those places are. They're hard to find. dma_read and dma_write probably both need it.  Any others?

**Comment by g0me3** [comment]
i hardly understand the core code lol so i may assume they are exists but cant see where nor debug it since i have no full toolchain for it. also im not too confident with c# oop so it is hard to me sometimes to track the code flow. so i started this issue ;)

**Comment by zeromus** [comment]
OK, so how do I repro this bug? Your lawnmower man case didn't work for me

**Comment by g0me3** [comment]
you said 38000 has a perfect 010202010202 but this is not a code bank there must not be any code. how do you got it? my picture above is from exacthe that region. so you may see it has wrong codes here.

**Comment by zeromus** [comment]
I went to offset $38000 in the CDL file. Did you mean $38000 in some bank in particular inside the CDL file which would be at a different offset in the CDL file?

**Comment by g0me3** [comment]
yes it is 38000 at cdl file and i have here exactly this 
https://www.dropbox.com/s/9khfpsdpeue921t/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202020-01-22%2023.05.46.png?dl=0
which is not right, because this is not a code bank and there are no OPC (02) flags also.

**Comment by zeromus** [comment]
and yet here I have this
![image](https://user-images.githubusercontent.com/102701/72930213-72f78900-3d29-11ea-92f2-dcfd3f9b84bd.png)

**Comment by g0me3** [comment]
so it seems your cdl is alwo wrong somehow lol there are no code at 38000 location. see bank 87 has no code, only data, starts with zeroes. hardly believe there are some opcodes above the zero data. are we talking about SNES game? ;)

**Comment by zeromus** [comment]
I don't know how you get from $38000 to bank 87, but $38000 should be near the END of a bank, due to the $2E bytes header. A bank should be beginning ~2 lines down from there, and you do indeed see a mountain of 00 00 00 00 there since there was no code at that point.

**Comment by zeromus** [comment]
Why did we put the header in the CDL file anyway? should have done it as a footer so things stay nicely aligned...

**Comment by g0me3** [comment]
38000 is exactly the SNES ROM offset, CDL file offset is 38000 plus the header of course

**Comment by g0me3** [comment]
i don't care about the header, ida parce it and start with the CARTROM area as 0, so starting from this area the address in a question is at exactly 38000

**Comment by g0me3** [comment]
lawnmower is a lo rom cart, so all banks are 32K in size, all started from 8000 in memory. 8x is a ROM bank number, so X is a number or 32K bank. 32*(8)7 = 229376 decimal which is 38000 in hex exactly

**Comment by zeromus** [comment]
OK, we're not getting anywhere.
Obviously you are doing something differently in lawnmower man to get the different results.
Can you tell me WHAT you are doing?

**Comment by g0me3** [comment]
1. open it with bizhawk.
2. start cdl log
3. play a while
4. save cdl file
5. open file in any hex editor.
6. go to exactly hex offset 0x380000
7. see the picture above

if not i don't know how you do het yours lol

**Comment by zeromus** [comment]
Can you define PLAY A WHILE?
I started the game with the left player, jumped, and shot.
How long do i have to play in order to see what you see?

**Comment by g0me3** [comment]
i played demo, two 3d levels and dies somewhere after that
but I can't see if this is important. if your log is fine, it shows another results but all there are also WRONG. there are no code at 38000. ca't be 01 02 at all not in my run nor in yours

**Comment by zeromus** [comment]
I don't know anything about SNES banks since it's all confusing and I'm never ramped up on it.

So I may be naive, but here's what I see. 

$38000 in CDL file is $37FD2 offset in CARTROM, is $37FD2 offset in SFC file.
That seems like it is the middle of an opcode. Next opcode is 2 bytes away (judging from my CDL file)
That would give me 
22 00 80 86 (JSL)
C6 63 (DEC)
D0 F4 (BNE)
A9 80 00 (LDA)
8D 27 5C (STA)
5C 03 F6 81 (JMP)
FF FF FF FF FF FF ....................
---- END OF BANK ----
00 00 00 00 (etc)

And so, in my CDL I have
01 02 02 02
01 02
01 02
01 02 02
01 02 02
01 02 02 02
00 00 00 00 00....

and as you can see, those opcode lengths in CDL match the instructions

everything checks out perfectly.

**Comment by g0me3** [comment]
and from this point check the same way bytes past your -END OF BANK- which are all zeroes and belong to a bank 87 at a 38000 offset in cartrom (also rom file) im talking about.

**Comment by zeromus** [comment]
ok thank you for finally establishing it's $38000 in the CARTROM you're talking about and not $38000 in the CDL FILE.
