### ISSUE TITLE
[Feature Request] Parameter to disable smoothing in LuaCanvas.drawText

### ISSUE THREAD

**Issue by HeyItsLollie** [TASVideos/BizHawk#1411]
LuaCanvas.drawText adds smoothing to fonts, which is undesirable when using pixel fonts. There's currently no LuaCanvas equivalent for gui.pixelText to work around this - though, gui.pixelText doesn't currently allow for custom pixel fonts (only fceux and gens). With that in mind, I'd like to see a true/false parameter added to LuaCanvas.drawText, to enable/disable pixel text rendering (keep smooth text rendering as default behavior).

![Screenshot of current LuaCanvas.drawText VS desired result (at 3x scale)](https://user-images.githubusercontent.com/30498581/50503560-74696a00-0ab3-11e9-9ba1-8269d9194c1f.png)
Current LuaCanvas.drawText VS the desired result (at 3x scale)

-----

Context for how I'm trying to use LuaCanvas here:
I'm using BizHawk's Lua Console to create a live 16:9 info-border for Pokemon Red/Blue (at 640x360), with the intention of combining the emulator and the LuaCanvas border in OBS, and scaling both elements up by 300%. This unfortunately means that the text smoothing becomes very visible, and so the text ends up looking weirdly smeared.

I originally tried creating this border directly on top of the emulator via gui.***, as gui.drawText renders this pixel font cleanly. But BizHawk renders gui draw calls at the emulator core's output resolution - in this case: I'm limited to 256x224 for Same Boy + SGB, with no room for resolution-independent elements (everything renders at 1:1 pixel scale), or anything that extends past the output res (elements get cut off at the sides, so this border would be limited to 8:7 ratio).

**Comment by zeromus** [comment]
can you build the code? change LuaPictureBox.cs code

```
			Rectangle rect = new Rectangle(new Point(x, y), sizeOfText);
			boxBackground = Graphics.FromImage(Image);
			boxBackground.FillRectangle(GetBrush(backcolor ?? _defaultTextBackground.Value), rect);
			boxBackground = Graphics.FromImage(Image);
			boxBackground.TextRenderingHint = System.Drawing.Text.TextRenderingHint.SingleBitPerPixelGridFit;
			boxBackground = Graphics.FromImage(Image);
			boxBackground.DrawString(message, font, new SolidBrush(forecolor ?? Color.Black), x, y);
```

to

```
			Rectangle rect = new Rectangle(new Point(x, y), sizeOfText);
			boxBackground = Graphics.FromImage(Image);
			boxBackground.FillRectangle(GetBrush(backcolor ?? _defaultTextBackground.Value), rect);
			boxBackground = Graphics.FromImage(Image);
			boxBackground.TextRenderingHint = System.Drawing.Text.TextRenderingHint.SingleBitPerPixelGridFit;
			boxBackground.DrawString(message, font, new SolidBrush(forecolor ?? Color.Black), x, y);
```

**Comment by zeromus** [comment]
"works for the time being" or "fixes it totally"?

**Comment by zeromus** [comment]
The code was broken. The mucking is fixing.
