### ISSUE TITLE
Gameboy Advance - Skip Bios not working

### ISSUE THREAD

**Issue by Sun-in-jang** [TASVideos/BizHawk#1432]
Load any game, then go to "GBA - Settings... - Sync Settings - Skip Bios: True"

Bios shouldn't loading, but looks like the Bizhawk (* - not sure what is) ignoring that setting

In zip-archive video with issue. Tested on Bizhawk Developer build, commit b9fb6d3f7 and on Bizhawk 2.3.1

[bandicam 2019-01-07 22-25-41-793.zip](https://github.com/TASVideos/BizHawk/files/2734197/bandicam.2019-01-07.22-25-41-793.zip)

**Comment by Asnivor** [comment]
I think I may have caused this. Will do a PR shortly.

**Comment by Asnivor** [comment]
This is fixed in the latest dev build

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Llaurence** [comment]
The bios is not skipped when playing from TAStudio (Tools > TAStudio > Middle mouse button), even in the dev version.
