### ISSUE TITLE
TAStudio "New From -> Now" creates double file extension

### ISSUE THREAD

**Issue by Winning117** [TASVideos/BizHawk#1443]
Steps to reproduce:
1) Open up EmuHawk and load any .n64 game
2) Go to Tools -> TAStudio
3) In TAStudio go to "File -> New From -> Now"
4) Let the game run for any number of frames as long as it is greater than 0 (this will allow you to run New From -> Now)
5) Look at the name of your project file, if it was previously "default.tasproj" it will now be "default.tasproj.tasproj"
6) Let the game run for at least 1 frame
7) In TAStudio go to "File -> New From -> Now" and be greeted with the Unhandled exception

This is an issue because it will throw the following exception if you attempt to do "File -> New From -> Now" from within the .tasproj.tasproj file

![image](https://user-images.githubusercontent.com/15934200/51079205-06f33700-1678-11e9-9f8b-f414bec689e3.png)

Here's a pastebin of the exception log since I couldn't find dumps anywhere https://pastebin.com/CUWGSE1F

It should be noted that renaming the file to remove the extra ".tasproj" does not resolve the problem, it will still throw the exception.

**Comment by alyosha-tas** [comment]
I'm not sure the file extension is a big deal, but the exception comes from here:

`StateManagerState power = _states.Values.First(s => s.Frame == 0);`

when a savestate anchored movie doesn't contain a frame 0 the exception will be thrown. New from now wasn't intended to be used twice in a row it seems. 

It's easy enough to rewrite the check, but I'm not sure if there will be any unintended consequences.

**Comment by alyosha-tas** [comment]
I can make the file extesntion something indicating it's an anchored movie if it will make things a bit cleaner.

Something like: name.nfn.tasproj (as in new from now)
Then subsequent iterations will be name.nfn.nfn.tasproj etc.

Any opinions on this?

**Comment by Winning117** [comment]
That sounds good to me! Does that mean creating multiple nfn will be possible now?

**Comment by alyosha-tas** [comment]
I did some testing and it seems like it works for multiple yeah.

I'll look things over a bit more before I make any commits though.

**Comment by Winning117** [comment]
Great, thanks!

**Comment by alyosha-tas** [comment]
Ok I think it's fixed. 

I also fixed some similar errors in 'new from saveram' while I was there
