### ISSUE TITLE
[ZXS]Kong Strikes Back loading error

### ISSUE THREAD

**Issue by Fortranm** [TASVideos/BizHawk#1446]
http://tasvideos.org/forum/viewtopic.php?p=479376&highlight=#479376
This still happens on 2.3.1.

**Comment by Asnivor** [comment]
This looks like an issue with the Speedlock 1 protection used in the *.tzx release. I'll look into this when I have a chance.

**Comment by Asnivor** [comment]
Still havent had a chance to look at this yet. Hopefully soon.
