### ISSUE TITLE
TAStudio records joystick movement in read-only mode

### ISSUE THREAD

**Issue by Winning117** [TASVideos/BizHawk#1447]
Tested on BizHawk 2.3.1

Steps to reproduce:
1) Open EmuHawk
2) File -> Open ROM -> Open any .n64 game
3) Tools -> TAStudio
4) Unpause the game (default press Pause on the keyboard)
5) Move your joystick and you will see in TAStudio that it still accepts aX and aY as input even though it is in read-only mode. It doesn't seem to allow input from any other buttons.

**Comment by vadosnaprimer** [comment]
I don't have a joystick to test this on. It could be tested on Virtual Pad, but I know they don't work well with tastudio.

**Comment by alyosha-tas** [comment]
It can also be demonstrated with mouse input. Only happens for new frames, not already recorded inputs.

**Comment by vadosnaprimer** [comment]
I guess I only patched away binary buttons in this codepath, didn't know analogs are shoved in separately :/
