### ISSUE TITLE
BizHawk PCE Emulator Arcade Card Help

### ISSUE THREAD

**Issue by GoldenPhilemon** [TASVideos/BizHawk#1450]
Hi,

I currently have BizHawk installed to play PC Engine games.

However, when trying to play Tengai Makyou - Kabuki Ittouryoudan, which is a game that requires an Arcade Card, it brings up screen in Japanese saying I need an Arcade Card.

![1](https://user-images.githubusercontent.com/46737136/51227058-5f8c3380-1907-11e9-9f72-2b1d3e09c606.png)

Will there be PCE Arcade Card functionality to run Arcade Card based games to run on BizHawk in the future?

Thank you in advance for the help! :)

**Comment by YoshiRulz** [comment]
Confirm there's a checkmark in the status bar (when you show it), and that when you open the Hex Editor and go to `Options` > `Memory Domains`, "Arcade Card RAM" is one of the options? The game is [set](https://github.com/TASVideos/BizHawk/blob/f6dd99a3cecff43ca0ee32a31e8811840c9fdf87/Assets/gamedb/gamedb_pce_cd.txt#L119) to use the Arcade Card.

**Comment by YoshiRulz** [comment]
You have a different copy of the game, so BizHawk doesn't know to enable the Arcade Card. Click the ?-block in the status bar to get the SHA1 hash of the rom, the one I linked is `35777493304690A0E260FE2525410C53`. A temporary workaround would be to duplicate that line in `gamedb/gamedb_pce_cd.txt` but changing the hash (which might not work if it's actually a different rom).

**Comment by GoldenPhilemon** [comment]
Yay! Got it to work by changing the line in gamedb_pce_cd.txt to match the hash of the ROM I have :)

Thanks again for all your help troubleshooting!

**Comment by YoshiRulz** [comment]
Could we have the hash please?

**Comment by GoldenPhilemon** [comment]
Sure thing!

It's 525663A5CEBBA3D3A3738E1B77075FD5 :)
