### ISSUE TITLE
Bizhawk 2.3.1 will sometimes crash when autosaving

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1452]
when the emulator goes to autosave, it will freeze as it's saving, but what ends up happening is sometimes it will never unfreeze, causing me to close and reopen it back up.

**Comment by EZGames69** [comment]
also should probably mention that this happens in the developer build too

**Comment by alyosha-tas** [comment]
I tried for a bit but couldn't get a crash. Will need more detailed repro conditions.

**Comment by EZGames69** [comment]
That’s because I stuck with 2.2.1.  I rarely used 2.3.

**Comment by vadosnaprimer** [comment]
How is 2.3 related? After 2.3 the bug was fixed in the interim. No one reported it since then and it was released, then instantly you found it again.

**Comment by vadosnaprimer** [comment]
Somebody please test the dev build.

**Comment by EZGames69** [comment]
Apologies for not seeing this sooner.

it seems like the issue is fixed, but I've now noticed an additional problem.

whever you move the mouse inside tastudio when a movie is playing, it causes the playback to drop at 11 fps.  I'm not sure if this is related to the fix that was made.

**Comment by vadosnaprimer** [comment]
Just see if the slowdown in present in previous releases.

**Comment by EZGames69** [comment]
nevermind then, apparently it's also a thing with 2.3.1

in that case it seems like this crashing issue was in fact fixed.
