### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Kawesome06** [TASVideos/BizHawk#1454]
I'm having trouble installing BizHawk. When I try and open the compressed folder, It says:
"The compressed (zipped) folder is invalid."
Does anyone know how to fix this? Thanks!

**Comment by hegyak** [comment]
Try redownloading the latest Release (2.3.1)  I just checked it and it worked for me.  How are you opening the archive?  Using Windows?  7Zip?  WinRar?  Something else?

**Comment by Kawesome06** [comment]
I've tried all of these methods, but I'm using Windows right now for the sake of the annoyance I've experienced with the other programs. The most recent I've tried was around 2 hours ago.

**Comment by Kawesome06** [comment]
![capture](https://user-images.githubusercontent.com/40643546/51418250-68bc1100-1b50-11e9-835d-1b7d4611f3fa.PNG)

**Comment by hegyak** [comment]
Access Denied is a Personal User issue.  What may be happening is your Anti-Virus program is having a false postive with BizHawk and is preventing you from accessing the archive.  What windows are you using?

**Comment by Kawesome06** [comment]
Thats a good possibility. Every time I download the file, the anti-virus shows a possible threat. I'll look into this and try it.  (Windows 10 by the way)

**Comment by hegyak** [comment]
That's the solution then.  Closing this out.  I hope you can resolve it from here.

**Comment by Asnivor** [comment]
Interestingly enough, windows defender (on 10) now also throws a virus warning for the bizhawk 2.1 prereqs for me. Although 2.0 is fine. I'm presuming this is a defender false-positive issue as ESET has no such problem.
