### ISSUE TITLE
TAStudio export to bk2 doesn't ask for confirmation and will overwrite files

### ISSUE THREAD

**Issue by Winning117** [TASVideos/BizHawk#1455]
Tested on BizHawk 2.3.1

Steps to reproduce:
1) Open EmuHawk
2) File -> Open ROM -> Open any .n64 game
3) Tools -> TAStudio
4) Open a .tasproj and go to "File -> Export to Bk2" and you will see that it exports to bk2 without a confirmation. If you already had a .bk2 file with the same name it will now be overwritten

**Comment by alyosha-tas** [comment]
Done and updated the displayed message
