### ISSUE TITLE
GBHawk - Sound Issues with Dark Duel Stories

### ISSUE THREAD

**Issue by lightgod87** [TASVideos/BizHawk#1457]
Good day,

The motive for this ticket is about an issue regarding Yu-Gi-Oh! Dark Duel Stories with the GBHawk core. For some reason, the audio in the game behaves oddly during blank transitions in a duel and it gets messed up, which screws with the timings, so it causes the sound pitch to act oddly. I tested this on Gambatte and it didn't behave that way at all, so it makes me think it's an issue with GBHawk.

BizHawk version: 2.3.1
GB core used: GBHawk

And if I have to assume, maybe there's more affected games by this matter.

Keep in mind I'm using BizHawk casually, so dumping movies and such aren't related to this matter at all.

I'll be waiting for an answer regarding this situation.

**Comment by alyosha-tas** [comment]
Yes this will happen when audio is playing while the screen is turned off. GBHawk only updates frames when a vblank occurs so when the screen is off multiple audio frames get compressed into one video frame . 

For games that do this a lot like Yu-Gi-Oh evidently does , you’re better off just using Gambatte for casual play.

**Comment by lightgod87** [comment]
Alright, so GBHawk works like that, but that begs the question... what's the purpose of GBHawk? If you're aiming for accuracy, why does frame updating works like that? That deters the usage of GBHawk for casual players. Asking to use Gambatte for casual play is a fair suggestion, I agree. I had to do that myself.

In another tangent, NESHawk, which is another self-made core for BizHawk, it can be used casually and it doesn't have the kind of issues that GBHawk does, which leaves me scratching my head about why GBHawk works like that, which messes up in some scenarios, but I'm digressing.

I'm just adding my two cents.

**Comment by lightgod87** [comment]
Alright, that sounds fine and dandy, but... why does precisely affects the sounds and the pitch when those frame updates happen in blank segments in GBHawk? AFAIK, in a normal Game Boy, the sounds aren't affected by the frame refresh.

**Comment by alyosha-tas** [comment]
That is because GBHawk tells BizHawk that only one real time frame has passed while the screen is off, even when in reality more time then that has actually passed (can be several frames worth.)

So the audio from that time, get's squished to fit into one frame.

It's purely a matter of how I designed the core and is not related to what happens in reality.

I did it this way to simplify the development process, and while certainly not ideal form a player's perspective, it has saved me countless hours of debugging headaches.

Maybe as the core matures I can work on a setting to run the audio correctly in real time, but it's not there yet.

**Comment by lightgod87** [comment]
Ah, okay. That makes sense. Thanks for your insights, Alyosha. At least it can be assured that the audio is going to work in real time when the core gets in a more mature and nourished state.

For the time being, I'll run the GB / GBC games through Gambatte, as it said. It's just a matter of waiting until the GBHawk core blossoms into an even better and more accurate core than Gambatte.
