### ISSUE TITLE
controls are wack

### ISSUE THREAD

**Issue by DragonTrance** [TASVideos/BizHawk#1459]
So, I'm currently having a problem with the controls.
![image](https://user-images.githubusercontent.com/26515331/51444783-0f1f2800-1cb1-11e9-8ab5-9800798ca10d.png)
The normal controls only have those 2 options. When I switch cores, the controls go back to my previously saved ones (i.e. moving controls) but doesnt happen when I switch back.

So uh yeh i need help cause the other core is laggy, lol

(and yes, i'm using vsauce's RTC)

**Comment by NarryG** [comment]
For RTC issues please don't poke the Bizhawk devs. They don't support the fork/project. If you need help with it, come poke us (https://github.com/ircluzar/RTC3/issues/4).
