### ISSUE TITLE
Calling C/C++ from the packaged lua interpreter

### ISSUE THREAD

**Issue by tunstek** [TASVideos/BizHawk#1460]
As the title suggests I'm trying to call C/C++ code from lua in Bizhawk.

I've taken the lua52.dll file from the output/dll directory of this repo and added it as a dependency in a Visual Studio 2017 project. 

When I attempt to build the project I get the following error:
```
lua51.dll : fatal error LNK1302: only support linking safe .netmodules; unable to link ijw/native .netmodule
```

I've looked up this error and from what I can gather I should be adding a .lib file as a dependency instead of the .dll. Indeed I tested this by grabbing a lua51.lib file from my system lua install, adding it as a dependency and the code compiled correctly.

Would it be possible to make such a .lib file available? Or would you have any suggestions on what I could do?

---

As an extra note, I attempted to load the successfully compiled dll in Bizhawks lua (using require) but I get the following error:
```
error loading module 'mathlib' from file '.\mathlib.dll':
	dynamic libraries not enabled; check your Lua installation
```

I'm aware that the packaged lua in Bizhawk is modified but this error seems to suggest that what I'm trying to do is not possible with Bizhawks lua?

**Comment by zeromus** [comment]
There is no lua52.dll in the output/dll directory of bizhawk. you must mean 51.
Build your c++ code into the lua514.vcxproj contained in this repository, then build the luainterface project which sould output to the right location for bizhawk

**Comment by tunstek** [comment]
@zeromus Thanks for your reply.

I've attempted to do as you suggested and created a test C file, it's contents follow the layout in lmathlib.c 
I then appended to the lualibs array in linit.c, included my C file in luaglue.cpp and added the luaopen_ function to lualib.h

Bizhawk and LuaInterface successfully compiled but the lua interpreter in Bizhawk errors out with 
```
module 'mytest' not found
```

Have I missed anything? Would you have any suggestions on how I might proceed?

**Comment by Sappharad** [comment]
Didn’t you ditch the unmanaged lua implementation in 2.0 and switch to a pure .NET version? What’s the native code for?

**Comment by zeromus** [comment]
1. Build LUAINTERFACE
2. config > customize > advanced > lua core -- change it

**Comment by zeromus** [comment]
the luaperks build configuration on luainterface should have already built into output/dll

**Comment by tunstek** [comment]
Yes. I had tried that previously but it was giving me errors. All working now.

I notice that printf does not print to Bizhawk lua console. Any ideas on why that might be?

**Comment by zeromus** [comment]
Because it isn't hooked up. use lua's print, which has been hooked up. use lua API to get it from global table.
