### ISSUE TITLE
Kaze no Klonoa - Moonlight Museum bug

### ISSUE THREAD

**Issue by Sun-in-jang** [TASVideos/BizHawk#1463]
Small graphic bug - gray line near 3 hearts (in the both Bizhawk Developer build and Bizhawk 2.3.1). Different settings in "WonderSwan - Settings..." has give no effect

![kaze no klonoa - moonlight museum japan 2019-01-24 20 12 49](https://user-images.githubusercontent.com/38378342/51699083-8a1b7200-2014-11e9-8e68-1d6b3af01f95.png)

Kaze no Klonoa - Moonlight Museum (Japan)
SHA1:207A3CEB9A09EABCA6E455DEEB7035E7E04C9795
MD5:5E907DD88B3CFB2855A18FB1BF689860

**Comment by Spikestuff** [comment]
@YoshiRulz I want to point out that this is also an issue on the 32bit version of Hawk which we know also gets the updates, albeit slower these days.

Only writing this and pinging you mainly for that label that was placed on it which to me only focuses on one half of Hawk.

**Comment by Sun-in-jang** [comment]
Is there any news when is core update? I can't record this game due to the bug with gray line.

**Comment by medigi** [comment]
I still have hope that one day this core get update, like mgba

**Comment by nattthebear** [comment]
6e6f800f0ee3ff73b5891d99d

**Comment by Spikestuff** [comment]
Image to show it's fixed:
![Kaze no Klonoa](https://user-images.githubusercontent.com/12412764/83341305-39f9a180-a325-11ea-88b6-bea1d6e22705.png)
