### ISSUE TITLE
Windows size is changing from 3x to 2x and back when playing ROM.

### ISSUE THREAD

**Issue by eToThePi-i** [TASVideos/BizHawk#1467]
Steps to reproduce:

1. Open a copy of BizHawk Version 2.3.1 (x64) (tested on a fresh download, but worked for me with existing preferences)
2. Change the window size to 3x using `View > Window Size > 3x`
3. Open _Donkey Kong Country_ (USA 1.0) (SHA-1: `0FCEE45D9AF5D2F62995ED4B04D22146B906C86B`)
4. Observe the window size change from 3x to 2x on frame 352, and back again on frame 668.

This is independent of the core used.

**Comment by NarryG** [comment]
This is actually intended behavior. You can stop it from happening by checking "Always use double-size frame buffer" within the snes settings.

**Comment by eToThePi-i** [comment]
That's very interesting. I didn't realize the SNES was capable of changing resolution like that.
