### ISSUE TITLE
StarCraft 64 graphics breaks after upgrading to BizHawk 2.3.1

### ISSUE THREAD

**Issue by Prcuvu** [TASVideos/BizHawk#1470]
Running StarCraft 64 by default settings, BizHawk 2.3 displays the main menu as:
![starcraft 64 usa 2019-01-29 00 59 32](https://user-images.githubusercontent.com/7923857/51852539-4486de00-2361-11e9-9cb8-204cb2899b11.png)
While BizHawk 2.3.1 displays as:
![starcraft 64 usa 2019-01-29 01 02 14](https://user-images.githubusercontent.com/7923857/51852684-8adc3d00-2361-11e9-8dc9-606e5881ae82.png)
After entering the first tutorial, BizHawk 2.3 displays as:
![starcraft 64 usa 2019-01-29 01 04 25](https://user-images.githubusercontent.com/7923857/51852906-0f2ec000-2362-11e9-9299-bc05b9029c06.png)
While BizHawk 2.3.1 displays as:
![starcraft 64 usa 2019-01-29 01 07 10](https://user-images.githubusercontent.com/7923857/51853002-40a78b80-2362-11e9-80d4-e542ffb74bf0.png)
Changing rendering resolution to 640 x 480 does not help. It should be something wrong with GlideN64.

**Comment by vadosnaprimer** [comment]
Try the updated dev build
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Prcuvu** [comment]
I tried a clean copy of the dev build just now, still broken.

**Comment by YoshiRulz** [comment]
Could not reproduce with a clean config on 2.3.1, Win10 *Home* 1709. Rom hash is `SHA1:A36D91B5AAC7BB95DF0D7DE5F9814F5270E25C2B`.

**Comment by zeromus** [comment]
Update about this: "Recently I switched to a new computer, on which with NVIDIA RTX 2070 graphics card the problem did not appear. Seems that the problem is exclusive to Intel HD Graphics 5500 (packed with Intel Core i5-5200U CPU)."
