### ISSUE TITLE
"Bang!" demo (VCS) doesn't work properly

### ISSUE THREAD

**Issue by Cyorter** [TASVideos/BizHawk#1473]
I played this demo in some emulators, and it doesn't work in BizHawk, same way like EMU7800 (but we're not talking about EMU7800).
First, Edith Piaf (hope I wrote well) its divided in two halves, that's how it should, but the second half os greately corrupted.
Second, the Chapter 1: "Side-to-Side Scroller" is eternally looped, even when demo should end and begin again, BizHawk is still in the Chapter 1.
Sounds are ok (I think).
https://xayax.net/bang!/
![bang 2019-01-31 21 46 05](https://user-images.githubusercontent.com/42274825/52098164-45f41880-25a4-11e9-84a9-94dccfe58b44.png)

![bang 2019-01-31 21 46 07](https://user-images.githubusercontent.com/42274825/52098167-47254580-25a4-11e9-8e18-14e22ee56201.png)

![bang 2019-01-31 21 47 37](https://user-images.githubusercontent.com/42274825/52098171-4be9f980-25a4-11e9-9579-379567c89633.png)

**Comment by alyosha-tas** [comment]
The issues around the scroller were due to having the wrong mapper picked. This is now fixed.

The other issues are HMove related. this is already a known issue, so I'll close this and add Bang! to the list of HMove things to test.
