### ISSUE TITLE
Can't record MP4 due to libvo_aacenc exception

### ISSUE THREAD

**Issue by Winning117** [TASVideos/BizHawk#1474]
Tested on BizHawk 2.3.1 release

Steps to reproduce:
1) Launch EmuHawk
2) File -> Open ROM -> Open a game, I chose an .n64 file
3) File -> AVI/WAV -> Config and Record AVI/WAV
4) Select FFmpeg writer
5) Select MP4
6) Name your file whatever you want, ex: "test.mp4" and click Save

You'll be greeted by the following exception:
![1](https://user-images.githubusercontent.com/15934200/52170288-8d8db800-26fc-11e9-9df5-594a423b5804.PNG)

And upon clicking "OK" you'll be greeted by:
![2](https://user-images.githubusercontent.com/15934200/52170310-ce85cc80-26fc-11e9-9a50-c4391eccc927.PNG)

It appears that FFmpeg [removed support for this in 2016](https://git.videolan.org/?p=ffmpeg.git;a=commit;h=e07e88cd82f78644ddcb10d7d3e0dd624fffe274)

**Comment by vadosnaprimer** [comment]
Was fixed in dev build, try it instead.

**Comment by Winning117** [comment]
Oh great, thanks.
