### ISSUE TITLE
Debugger - Dissassembler Broken

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#1475]
The disassembler (when available) is supposed to have an infinite scroll style scrolling mechanism.  It currently doesn't work.  I investigated it, and it is because the scroll event is never being fired.

At some point this definitely worked, not sure when it was broken, further investigation is needed.

**Comment by alyosha-tas** [comment]
The scrolling happens as expected when you click on the arrows on the scroll bar. As far as I can tell that's the only way to scroll it. 

I added mouse wheel scrolling as well, assuming that's probably what you meant.
