### ISSUE TITLE
Can't record AVI with Microsoft RLE compressor

### ISSUE THREAD

**Issue by Winning117** [TASVideos/BizHawk#1476]
Tested on BizHawk dev 0.0.0.2832 release

Steps to reproduce:
1) Launch EmuHawk
2) File -> Open ROM -> Open a game, I chose an .n64 file
3) File -> AVI/WAV -> Config and Record AVI/WAV
4) Select AVI writer
5) Set the Compressor to "Microsoft RLE" (Compression quality doesn't matter)

You'll be greeted by the following exception:
![image](https://user-images.githubusercontent.com/15934200/52191294-d62a9b80-27f8-11e9-87d7-97452800f539.png)

And upon clicking "OK" you'll be greeted by:
![image](https://user-images.githubusercontent.com/15934200/52191302-e2165d80-27f8-11e9-9e01-aa034f24f4e7.png)

**Comment by zeromus** [comment]
this codec is so useless, let's just forget about it. if AVI in general, or more useful codecs are broken, then that's a problem
