### ISSUE TITLE
Forward and backward controls reversed on N64

### ISSUE THREAD

**Issue by maith1** [TASVideos/BizHawk#1481]
I was attempting to play Super Mario 64 today when I noticed something strange. Whenever I would attempt to walk forward from a complete stop, it would instantly make Mario do a 180 degree turn on the spot and then he would proceed to walk around to face the way the joystick was aiming in the first place. (i.e. I am facing forward and attempt to walk forward by pushing the left joystick up. Mario instantly spins around 180 degrees on the spot and then does his normal turn around walk.) This is really annoying as I can hardly complete any platforming since he just walks off attempting to turn around. It doesn't happen when I jump first and then start moving but that isn't always an option. I don't know if this is a problem with BizHawk itself or with Super Mario 64 but my friends are saying that they never encountered this on other emulators. Any help would be appreciated. Thanks!

**Comment by YoshiRulz** [comment]
Try increasing the deadzone.

**Comment by maith1** [comment]
Increasing the deadzone did not fix the issue. I tried it again but this time slowly moving my joy stick forward (to walk forward). It makes me walk backwards until the joystick reaches the area where it would make Mario run and then he turns around and walks the correct way. So basically, walking controls are inverted but running controls are not which is making the game unplayable. Would this be SM64 or BizHawk?

**Comment by YoshiRulz** [comment]
Have you accidentally bound both of these? You'd be surprised.

![analogs](https://i.imgur.com/mZk0Nb1.png)

**Comment by maith1** [comment]
That seems to have fixed it. I didn't even know that was a thing. There should be some kind of warning text or something added. Thanks!

**Comment by YoshiRulz** [comment]
see also #787
