### ISSUE TITLE
Issue with BizHawk wont open my rom

### ISSUE THREAD

**Issue by 9math7** [TASVideos/BizHawk#1489]
Hi, i had an issue with bizhawk, first after download it, and yes i download the prerequisite, and the latest dev build, the black screen is DK64 game wich work in my project 64 , and the colored screen turn to black its my oot rom, maybe i did something wrong i need help please there is some screenshot of my files and of the issue
![bizhawk 2](https://user-images.githubusercontent.com/47719035/52915838-a70b3400-32a6-11e9-9a8e-a937559e7027.png)
![bizhawk 3](https://user-images.githubusercontent.com/47719035/52915839-a70b3400-32a6-11e9-9897-ea73986c0e28.png)
![bizhawk issue](https://user-images.githubusercontent.com/47719035/52915840-a70b3400-32a6-11e9-9579-6e11547ea2f9.png)

**Comment by 9math7** [comment]
thanks @YoshiRulz  i already read this, and it didnt help that much :(

**Comment by YoshiRulz** [comment]
Bottom screenshot is of known good DK64, please attach a screenshot of `N64` > `Plugin Settings...` because it should be working with the default settings.

**Comment by 9math7** [comment]
![aaa2](https://user-images.githubusercontent.com/47719035/52916006-bd19f400-32a8-11e9-8140-f113111d25d3.png)

**Comment by 9math7** [comment]
![aaa1](https://user-images.githubusercontent.com/47719035/52916013-ca36e300-32a8-11e9-84e5-57e3ed670a42.png)

**Comment by 9math7** [comment]
![aaaa333](https://user-images.githubusercontent.com/47719035/52916079-6a8d0780-32a9-11e9-8376-3c4ed167aff6.png)

**Comment by 9math7** [comment]
I just turned on the Alternate i tried without

**Comment by YoshiRulz** [comment]
See where it says "May have trouble ith OpenGL-based cores (N64)"? Try the OpenGL method, most GPUs made in the last decade will see similar performance.

**Comment by 9math7** [comment]
![asasas](https://user-images.githubusercontent.com/47719035/52916143-00289700-32aa-11e9-94a1-dd56f32c3ef8.png)

**Comment by 9math7** [comment]
Still not working :(

**Comment by YoshiRulz** [comment]
You'll have to close BizHawk completely for it to actually switch.

**Comment by 9math7** [comment]
I do its still not doing it

**Comment by adelikat** [comment]
Try some non-n64 roms if you have them, preferably NES

**Comment by 9math7** [comment]
I dont have any, and cant find a secure link to download one

**Comment by YoshiRulz** [comment]
I can't legally tell you where rom dump sites are, but I just tested [this free tech demo](http://nesdev.com/rstrdemo.zip) and it drew a nice mirror thing, so show us that working.

**Comment by 9math7** [comment]
![aaaaaaassssaaaaaa](https://user-images.githubusercontent.com/47719035/52916343-40891480-32ac-11e9-9326-c23e4a1fd29f.png)

**Comment by 9math7** [comment]
The nes game is working,

**Comment by 9math7** [comment]
![ssssssss](https://user-images.githubusercontent.com/47719035/52916368-7af2b180-32ac-11e9-949a-231feb711542.png)

**Comment by 9math7** [comment]
this is mario kart 64 , it only shows some not completely

**Comment by adelikat** [comment]
It looks like your system poorly supports opengl.  opengl is required for N64 rendering, regardless of your display type (unfortunately n64 emulators rely on plugins and plugins choose this).

You can try fixing your opengl, it looks like your system maybe can support it but is in a bad state.

Or you can try project64 since it supports jabo which uses directx.  BizHawk can not support jabo since it is 32bit only and closed source so we can't modify it to add support.

**Comment by 9math7** [comment]
My pc can handle it thats why im here ahah

**Comment by YoshiRulz** [comment]
@9math7 Not saying we can't or won't help you, but this isn't the place. You can try updating your drivers yourself: [NVIDIA](https://www.nvidia.com/Download/index.aspx?lang=en-gb), [AMD](https://www.amd.com/en/support). Failing that, join [IRC/Matrix](https://github.com/TASVideos/BizHawk#support-and-troubleshooting).
