### ISSUE TITLE
Suggestion: Improving Lua performance by making it a "seperate instance"?

### ISSUE THREAD

**Issue by ezBeanie** [TASVideos/BizHawk#1491]
I am working on a neural network project revolving around an N64 title and i run into some performance issues while executing my Lua script(s). I noticed, that Lua and BizHawk both share a single core/thread and the emulator uses rougly 66% (of said core/thread) by itselfy leaving not much room for Lua and good performance. (I own an i5 4690k @ 4.5 Ghz)

**Comment by YoshiRulz** [comment]
workaround: use external tool instead, [example in C#](https://github.com/upthorn/Ecco_BizHawkTool)

**Comment by zeromus** [comment]
No. Lua and emulation are a synchronous process. use yoshirulz workaround or make your own solution (IPC or threads or process invokes from lua) for parallelizing.
