### ISSUE TITLE
Refactor Away IAsyncSoundProvider from Cores

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1493]
Needed as a stepping stone for SMS subframe implementation.

The only cores that use IAsyncSoundProvider are SMS and PCE.  I'm working on figuring out YM2413 enough to fix SMS. 

If someone can take up the challenge of PCE we can finally do away with the IAsyncSound stuff.

This should hopefully make VRC7 sound on the NES sound better too since it currently does not have a proper time synced sound output for the YM2413.

**Comment by alyosha-tas** [comment]
SMS refactor is done enough to get rid of IAsyncSound. Still needs a second look to clean things up and work in YM2413 better. Same with NES.

All that's left is PCE.

**Comment by adelikat** [comment]
IAsyncSoundProvider has theoretically useful advantages for cores down the road.  So please don't completely delete the interface or infrastructure around it.

It does make sense to refactor cores like SMS and PCE that are using it, since they aren't even good candidates for this approach.

**Comment by alyosha-tas** [comment]
What uses do you have in mind? Sound that isn't temporally synced seems undesirable.

**Comment by nattthebear** [comment]
Some systems can generate as much or as little sound as needed without compromising quality.  HLE of Gamecube and PSX; Doom as a direct core (not likely to happen at this point) are two I can think of off the top of my head.  They're more fringe uses for sure

**Comment by zeromus** [comment]
Although keep in mind as emulation science advances, some of these cases can be proven non-deterministic. This was originally one of the rationales for the nondeterminism flags. It can be nicer for user experience if audio flows smoother when cores are running too fast or slow (or close to the target but not perfect) but the CPU can detect the glitch in the matrix.

**Comment by nattthebear** [comment]
Depends upon the core; sometimes, the behavior is non-observable by the main CPU.

**Comment by alyosha-tas** [comment]
Ok, if ASync is sticking around I'll go ahead and close this then since I accomplished what I needed for SMS.
