### ISSUE TITLE
Tales of Phantasia + English patch by Phantasian Productions

### ISSUE THREAD

**Issue by Gimlao** [TASVideos/BizHawk#1494]
[Edit] It works with Mednafen, but BizHawk will show this : 

"**No core could load the rom.**" =(

**Comment by Spikestuff** [comment]
Check Upstream next time like #1304 did:
![image](https://i.imgur.com/B79bbJM.png)

**Comment by Gimlao** [comment]
Also tested with Mednafen, actually, I was just wondering if my game was actually working with anything else than BizHawk.

I don't know what is "upstream", by the way.

So, If I understand ... we just have to wait for a update of Octoshock in the next release of BizHawk ?

**Comment by zeromus** [comment]
"no core could load the rom" doesnt sound like something that would be fixed by waiting for an octoshock update. It sounds like something about the patch does something very bad to the disc. The disk is read by bizhawk, not mednafen. Try loading the disc image in other disc image inspection tools and see if they blow up also. 
Octoshock won't necessarily be updated in the next release of bizhawk (probably won't be)

**Comment by Gimlao** [comment]
I don't know, I can read the disc image fine with other emulators, only BizHawk has trouble with it. =/

**Comment by zeromus** [comment]
can bizhawk read the disc BEFORE it's patched?

**Comment by Gimlao** [comment]
The original japanese disc image works fine, even with the Absolute Zero patch.
BizHawk only has trouble with the Phantasian Productions patch.

**Comment by zeromus** [comment]
stop loading .bin files. just because your patch modified the .bin file doesnt mean you get to load the .bin in bizhawk. you must modify the cue to point to the patched bin, and then load the cue.

works for me

**Comment by Gimlao** [comment]
I'm always using cue files ...

**Comment by zeromus** [comment]
![image](https://user-images.githubusercontent.com/102701/53306850-55434a80-3860-11e9-921e-1bd0845b1ba9.png)

**Comment by Gimlao** [comment]
I'm always using cue files with BizHawk...
Also, my games are stored in multiple folders, I'm not mixing files from other games.
The cue file is only pointing to that patched bin.

![image](https://user-images.githubusercontent.com/841935/53306912-4d50ce00-3893-11e9-8c02-72ab1d398fb2.png)

**Comment by zeromus** [comment]
your cue isnt referencing the bin, or youre loading the bin, or your xdelta is broken
```
    File: ToP patched.bin
  CRC-32: c1cfd288
     MD5: ff902e033894910b26944cfc2a4cc3fc
   SHA-1: 459f4b7ac8b4f38d5aa7fb09cae088ff724356a8
 SHA-256: f867b13608f8a6776b8a2481489478422a61a062474168cde6e15669667ea5d4
 SHA-512: 3ca20bc0217c269873b35a87257e4fc7b12e6374586a59a75b3b6dc163de4e3aae5493e060c38c83ea2f4c96ae23cec538dc94f844c24b8f80dad82dc97c0367
```

**Comment by Gimlao** [comment]
I'm using this : https://fantasyanime.com/legacy/top_downloads.htm

Also tested with other sources, it's the same ...

Now I'm wondering how you managed to get it to work with BizHawk... =(

Which original bin are you using, with which patch ?..

**Comment by zeromus** [comment]
You're using hacked warez from mysterious sources. Disc images that can't be verified. You shouldnt expect them to work. 
This version hacks identification signatures in the disc header so that it's no longer recognizable as a PSX game. Unless someone proves otherwise, I'm going to assert this wouldnt run on an actual PSX.
Mednafen goes to greater lengths to recognize PSX games than we do. I'll open a ticket but this won't be changed in the near future

see more at https://github.com/libretro/beetle-psx-libretro/issues/151

**Comment by Gimlao** [comment]
The "hacked warez from mysterious sources" is actually the same here : https://www.romhacking.net/translations/1787/

But since tales-cless.org is dead, I was unable to test other patches.

Now I used the patch from @Awakened0 upload on Dropbox, and now I'm getting the same CRC-32 as you. <3

Thanks a lot for the link to libretro/beetle-psx-libretro#151

**Comment by Gimlao** [comment]
Ok so ...

My original japanese image disc was the good one.

The "hacked warez from mysterious sources" patch was actually the same as here : 
https://www.romhacking.net/translations/1787/ (original patches from Phantasian Productions, nothing mysteriously hacked here)

I wasn't able to test other patches since http://www.tales-cless.org/ is dead.

I needed this version of the patch : http://www.tales-cless.org/patches/ToP%20test%20fix.7z (still dead)

Thanks to your link to libretro/beetle-psx-libretro#151 I found @Awakened0 uploaded it on Dropbox : 
https://www.dropbox.com/s/w1h6y5vay4n0mex/ToP%20test%20fix.7z?dl=0

And now I'm getting the same CRC-32 (c1cfd288) as you. <3

Bye !

**Comment by Gimlao** [comment]
By the way : 

1. I love BizHawk a lot <3
2. I know that we must not load bin files ~~
3. I know how works cue files ~~
