### ISSUE TITLE
Invalid URI: A Dos path must be rooted, for example, `c:\`

### ISSUE THREAD

**Issue by coreyog** [TASVideos/BizHawk#1497]
Image of JIT error dialog:
![JIT Error](https://i.imgur.com/kEyfw05.png)

While trying to get BizHawk to work with EmoTracker's new AutoTracking capabilities I did the following:

0) EmoTracker is installed and up to date (both the application as well as the package for LttPR) and BizHawkPreReqs are installed
1) Open BizHawk 2.3.1 (x64) on Windows 10 x64
2) Open the Lua Console
3) Click the yellow envelope on the menu bar to open a script
4) Browse to "C:\Program Files (x86)\EmoTracker\Connectors\bizhawk\connector.lua"
5) Selecting the file results in the above error dialog.

edit: fixed link --yoshi

**Comment by zeromus** [comment]
You are running bizhawk from a weird location. Don't run bizhawk from a weird location. Run it from a directory on your desktop if you dont know what constitutes weird
Did emotracker really tell you to load this lua script this way? That doesn't make sense based on my reading of the script

**Comment by coreyog** [comment]
You were right, moved it to a better location.

**Comment by vadosnaprimer** [comment]
What was the bad location again?

**Comment by bigbass1997** [comment]
Just for future reference, while helping someone with an Archipelago setup, we encountered this exact issue on BizHawk v2.8, Windows. In this case, bizhawk was being run from the `D:\` drive. Moving to the `C:\` drive fixed it.
