### ISSUE TITLE
Commodore 64 Authenticity Concern in BizHawk

### ISSUE THREAD

**Issue by DrD2k9** [TASVideos/BizHawk#1500]
In addition to the various media images that can be mounted for the C64 core, BizHawk also allows mounting of .prg files.  This file type however is not an image of any particular media type, it is the actual commodore 64 program file that would be present on the disk, tape, or cartridge media.

When mounted, BizHawk treats the .prg file as if it's on a disk in the disk drive (device 8).  

The issue lies primarily in TASing of games using the .prg format: 
For casual gaming, there's not really an issue. 
For TASing it's a potential problem.  
The type of C64 media image (disk vs. tape vs. cartridge) has been discussed fairly recently with the consensus being that C64 TASes should be made using a media image that is authentic for the game's release, and conversion between formats using modern PC software isn't allowed.

So, if the .prg file was extracted from a disk image, then it should behave appropriately within BizHawk when mounted.
**However**, if the .prg file was extracted from a tape, having BizHawk consider it a disk results in a faster (but inaccurate) loading time.  This dilutes the authenticity.

If it's decided that the ability to mount .prg files needs to be retained for casual gaming, then perhaps the TASVideos community needs to implement a new rule disallowing TASes made from a .prg mount as it's impossible to know which media type the program was extracted from.

**Comment by SaxxonPike** [comment]
We can't really tell if a .PRG came from a tape or a disk. The format itself doesn't discern this, it's a blob of binary data. Games generally don't come in this format unless they're one-file scene releases, which would be invalid for running games anyway. I think it would be safe to say, PRG should not be considered standard media and exists solely for ease of debugging (as a lot of intros that exercise the machine are conveniently provided in this way)

**Comment by nattthebear** [comment]
I like the concern and attention to detail, but it seems like there's not much to be done here.  Bizhawk is just the tool to enable TASers as well as casuals.  If the TASVideos community comes to some consensus on this, the most Bizhawk could do would be to... flag them as potentially suspect?

**Comment by SaxxonPike** [comment]
This is more a Tasvideos concern than a Bizhawk concern, methinks. I'd like to close this, make things clear on the C64 Tasvideos guide, and let judging take it from here. I believe it works this way for other systems already.

**Comment by vadosnaprimer** [comment]
Thanks for the input guys.
