### ISSUE TITLE
no longer opens

### ISSUE THREAD

**Issue by punchoutplayerpenguin** [TASVideos/BizHawk#1502]
it used to work fine, but recently it refuses to open, I'll click on it, it'll pretend its gonna open, (the icon glows) and then it never opens I did install the prerequisites when i already had it for a while, did this cause it? I still was able to use it for a while after, but i can't anymore

**Comment by YoshiRulz** [comment]
1. What version of Windows are you using and did Windows Update break it?
2. Are you sure you haven't moved the BizHawk folder without updating the taskbar shortcut?

**Comment by g0me3** [comment]
once again. delet old config file and restart.

**Comment by YoshiRulz** [comment]
@punchoutplayerpenguin ping

If the suggested fix didn't work, comment with more detail or join IRC.
