### ISSUE TITLE
Request - Update mGBA core to 0.7.2

### ISSUE THREAD

**Issue by Sun-in-jang** [TASVideos/BizHawk#1512]
Currently mGBA in Bizhawk 0.6.3 version, maybe it's time ot update it one day.

**Comment by vadosnaprimer** [comment]
Yeah I planned to update to stable, then it took a while to see it released. Should be updated for the next hawk release.

**Comment by Sun-in-jang** [comment]
mGBA updated to 0.7.2 , waiting bizhawk to update too on that version.

**Comment by vadosnaprimer** [comment]
@Sun-in-jang please test the dev build https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts
