### ISSUE TITLE
Noticable Graphical bugs with SGX in PCEHawk

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1523]
this was an issue reported awhile ago: https://github.com/TASVideos/BizHawk/issues/1303

but it is still present in 2.3.1

this is what it looks like in 2.2.1: https://raw.githubusercontent.com/EZGames69/EZGames/master/Daimakaimura%20(J).2019-03-21%2019.48.27.png

and this is what it looks like in 2.3.1 AND the recent dev build: https://raw.githubusercontent.com/EZGames69/EZGames/master/Daimakaimura%20(J).2019-03-21%2019.48.22.png

(sorry for the large links)

**Comment by YoshiRulz** [comment]
Thanks for reproducing this. Closing as #1303 is still open so it's best to not split discussion.
