### ISSUE TITLE
 N64 games are messed up visually and lag heavily

### ISSUE THREAD

**Issue by littlelum** [TASVideos/BizHawk#1526]
Whenever I load an N64 game, many textures are missing, 3D models are solid colors, and some 2-dimensional objects don't appear at all. Also, there appears to be plenty of lag. NES games work fine, so it's probably due to the N64 emulation and not the program as a whole. I'm using default settings, except that I'm using openGL instead of Direct3D (I've tried both)
![Capture_](https://user-images.githubusercontent.com/25493246/54892284-38556380-4e6e-11e9-90cb-9bde3cb3b5af.PNG)

**Comment by zeromus** [comment]
you need to change your n64 video plugin (the choice of opengl or direct3d you made has nothing to do with what the n64 emulator core does). Or repair/upgrade/downgrade your system's GPU drivers, or set your laptop to use discrete gpu instead of integrated.
