### ISSUE TITLE
[Genesis-plus-GX] Nuked OPN2 (YM2612) cycle-accurate core

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/BizHawk#1528]
http://nukeykt.retrohost.net/
Can you import Nuked OPN2 (YM2612) core from lastest genesis-plus-gx official branch?
It has nearly-perfect "ladder effect" emulation.

https://www.youtube.com/watch?v=PuK_Rjf20iE

**Comment by zeromus** [comment]
no. we will import it along with all the rest of gpgx when we update gpgx
