### ISSUE TITLE
Window Frame mode causes OBS to not recognize EmuHawk.exe

### ISSUE THREAD

**Issue by codemann8** [TASVideos/BizHawk#1529]
As many streamers do, they want to have as low profile as a window as possible to save on the valuable screen real estate.  However, when you change the Window Frame mode to Thin or None, EmuHawk.exe disappears from the list of selectable windows to choose from in OBS.  I'm guessing this is throwing off Aero, or whatever mechanism OBS uses to filter out non-windowed processes.

**Comment by zeromus** [comment]
file a ticket with OBS if their software can't detect a program, or link to useful discussion of how to get a .net program working with a no-borders mode in a way that's compatible with OBS, so that we can add it with a label that will be "OBS Bugs Workaround For Borderless Window Mode"
