### ISSUE TITLE
Message options/config

### ISSUE THREAD

**Issue by codemann8** [TASVideos/BizHawk#1530]
As a suggestion, I'm wondering how hard it would be to implement a couple things as it pertains to Messages:
1) Length of time on-screen (I'm coding a crowd control app that sends messages, but they show for too short of time to actually see what it says, I'm wondering if there can be some kind of option to set the milliseconds that this displays for)
2) Size of the font (It is a bit small, but I understand the default messaging that occurs makes sense for it to be that small, but can there me an option to change this?)
3) Style/family of the font (Very much more optionally, changing the font family would be a nice change)

Having said that, I think it would be fine to have one single global option for these 3 new options, as opposed to 4 different ones for the 4 different message types, as that would spam the config window quite a bit.

**Comment by zeromus** [comment]
use lua. if you're already using lua, use different apis which can render every frame and pick fonts, etc.

**Comment by codemann8** [comment]
@zeromus Thanks for the tip. I have to admit, I'm quite new to Lua, do you know of a good resource that explains a good amount of the options available for emulators? I'm struggling to find good documentation on interactions with emulators.

**Comment by zeromus** [comment]
google bizhawk lua scripts and check our repository for examples, scour tasvideos.org

**Comment by YoshiRulz** [comment]
Suggestion 1) was [added in 2.8](https://github.com/TASEmulators/BizHawk/commit/267f48eebde6da92846f8e8805efde0a2e27b639) (only for C# though), for 2) see #2605, and we won't do 3) because the OSD doesn't use normal TrueType font rendering, it's a bitmap font for speed. The `gui.drawString` function has a parameter with which you can pick any font installed on the system.
