### ISSUE TITLE
Pokemon Stadium Freezing At The Start Of Battle

### ISSUE THREAD

**Issue by yugioh2king** [TASVideos/BizHawk#1535]
So I have been testing different pokemon stadium 1 roms and it keeps freezing at the start of battle. I downloaded the lastest version of bizhawk 2.3.1. does this mean it's unplayable?

**Comment by YoshiRulz** [comment]
Is there a green checkmark in the status bar? If not, that particular dump isn't "good" and crashing is expected.

**Comment by zeromus** [comment]
it's broken for real

**Comment by NarryG** [comment]
It'll work under 1.X with the CPU mode set to Dynarec. It doesn't work on Interpreter or Pure Interpreter.

**Comment by yugioh2king** [comment]
Ok so how do I set it to dynarec is this in the display menu or on the n64 core plugin?

**Comment by zeromus** [comment]
you use 1.x bizhawk and then you should be able to figure it out from there.

**Comment by yugioh2king** [comment]
is that an older version or something else please explain.

**Comment by zeromus** [comment]
that is an older version

**Comment by yugioh2king** [comment]
oh okay thanks I will check the other versions like you said. thanks for help.
just a quick question does that mean on the newer versions of bizhawk pokemon stadium is unplayable right?

**Comment by zeromus** [comment]
Possibilities:
1. Yes; use 1.x
2. No; wait for someone who knows how to show up and tell you how

**Comment by yugioh2king** [comment]
Ok thanks for your help. will try the first option.

**Comment by YoshiRulz** [comment]
May also affect "Cruis'n Exotica".
