### ISSUE TITLE
BizHawk 2.3.1 (x64) crashes before start

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1537]
I launch BizHawk in network drive (non mapped/unmounted drive) and I got this crash:

> Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EmuHawk.exe
  Problem Signature 02:	2.3.1.1
  Problem Signature 03:	5c3247d3
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.3062.0
  Problem Signature 06:	5ab95381
  Problem Signature 07:	421e
  Problem Signature 08:	12
  Problem Signature 09:	System.IO.FileLoadException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	e6e6
  Additional Information 2:	e6e6c208b90db2aa028f8f653cabbf23
  Additional Information 3:	214c
  Additional Information 4:	214c7288052fd3ef9b0eee68c6291e8f

I can't run BH (it's just stops!):
![bh_crash](https://user-images.githubusercontent.com/49565819/56055276-a2b04400-5d48-11e9-9935-7691203a6349.PNG)

I have installed:
[vcredist_x64.exe|https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe](url)
[https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe](url)
and [https://download.microsoft.com/download/1/7/1/1718CCC4-6315-4D8E-9543-8E28A4E18C4C/dxwebsetup.exe](url)

What should I do to run BH at the network drive?

**Comment by zeromus** [comment]
check diffs in that commit to figure out how to fix your 2.3.1

**Comment by Croopper** [comment]
I installed dot net framework too [https://download.microsoft.com/download/0/5/C/05C1EC0E-D5EE-463B-BFE3-9311376A6809/NDP472-KB4054531-Web.exe](url) It not works!

**Comment by Spikestuff** [comment]
Can you just verify which OS bit you're on.
Are you certain you're x64 and not x86?
