### ISSUE TITLE
[NESHawk and QuickNES] List of games having bugs or crashing as of Lastest Bizhawk Dev

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#1538]
Theses lists excludes prototypes, demo, pirated and homebrew games that do not have a physical release

This issues will be updated is test more games

Sound related :
- [x] Rollergames : The sounds of cheerings at the intro and team selection is weird on NESHawk. QuickNES doesn't have this problem.

Game crashing or not booting :
- [x] Donkey Kong Classics : Doesn't boot at all on NESHawk. On QuickNES, the title screen is badly glitched, but both game work correctly without graphical issues.

**Comment by YoshiRulz** [comment]
see also https://github.com/TASVideos/BizHawk/issues/860#issuecomment-348698182

**Comment by alyosha-tas** [comment]
Donkey kong classics works fine for me. What mapper is it loading with?

**Comment by alyosha-tas** [comment]
I fixed Rollergames. Good ear finding that one.

Donkey Kong Classics works fine as far as  Ican tell, so I'll close this.
