### ISSUE TITLE
Random exception error when trying to record a movie?

### ISSUE THREAD

**Issue by jakanz** [TASVideos/BizHawk#1543]
When I try to record my Super Mario Bros. AISSON movie, I get the following error:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.TAStudio.RefreshTasView()
   at BizHawk.Client.EmuHawk.TAStudio.RefreshDialog(Boolean refreshTasView)
   at BizHawk.Client.EmuHawk.TAStudio.TasView_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at BizHawk.Client.EmuHawk.InputRoll.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Sorry if it seems like a lot, but this started just today. Don't know where it came from, and don't know what it means. If someone could tell me what this means and how to fix it, that'd be great!

Thanks in advance!
~jakanz

**Comment by zeromus** [comment]
delete your ini file, see if that helps. (make a backup first)

**Comment by jakanz** [comment]
deleting my config.ini file didn't seem to work, unfortunately.

**Comment by zeromus** [comment]
reboot your computer. if it happened today and not yesterday, _something_ must have changed

**Comment by jakanz** [comment]
nothing happened. im not sure what happened, but maybe reinstalling bizhawk may work, so i'll try that.

**Comment by jakanz** [comment]
even that didn't work. something is failing and i dont know what. please can someone tell me what the exception text means?  thanks!

**Comment by zeromus** [comment]
the exception text means nothing useful except that you must be doing something differently than you were before, if you've discovered that nothing on your disk has changed. Is this the first time you tried to record a movie for Super Mario Bros. AISSON? Try it on another computer perhaps

**Comment by vadosnaprimer** [comment]
Is that with a release or a dev build?

**Comment by YoshiRulz** [comment]
In `RefreshTasView`, things that could throw NREs are:
* `CurrentTasMovie`, null iff `Global.MovieSession.Movie` is not a `TasMovie`, `Global.MovieSession.Movie` is never null;
* `Emulator`, which Rider can't analyse; and
* `TasView`, set in the auto-generated `InitializeComponent`.

**Comment by jakanz** [comment]
*vadosnaprimer* it is with a release. i use the latest version (2.3.1) and not a dev build. if you guys would like me to use a dev build, i'd be happy to.
*YoshiRulz* I'm not sure how to check if CurrentTasMovie or Global.MovieSession.Movie is null or not a movie. Hopefully you can help me on that (if you want to. im kinda a newbie at making tases so i may sound a little dumb)

**Comment by YoshiRulz** [comment]
Please try reproducing this in the [dev build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/23952015/artifacts). If you'd like to be more helpful after that, clone the repo, get Visual Studio, and debug the `BizHawk.Client.Emuhawk` project.

**Comment by jakanz** [comment]
I tried reproducing the glitch in the dev build and I got the exact same error when I hovered over the inputs in TAStudio. Also, when getting Visual Studio, do I get the Community version? I'm assuming that and debugging the project.

**Comment by jakanz** [comment]
Debugging couldn't work. It seems as though my cheat code is interfering but if I remove it, the TAS would be off.

**Comment by zeromus** [comment]
Cool, new details about something special you're doing that you haven't shared until now. Keep going.

**Comment by jakanz** [comment]
here's a video of what i'm doing: https://streamable.com/ovzsq
note: near the end where the error pops up, i hovered over the inputs in tastudio, causing the error.

**Comment by zeromus** [comment]
LOL. details
1. Open tastudio
2. Start recording a movie
3. Move mouse over tastudio

easy workaround: don't have tastudio open when trying to record a movie.
