### ISSUE TITLE
Problem with delete a breakpoint in Debugger

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1548]
There is a little problem with deleting break-point. I can't select any break point of list and just delete it. Take a look:
![how_2_del_bp_in_bh](https://user-images.githubusercontent.com/49565819/56459982-268eaf80-638b-11e9-8fd5-6d7a4e5f0815.png)

What should I do to delete it?

**Comment by vadosnaprimer** [comment]
The main problem with breakpoints is that they won't ever break. Bizhawk can't pause mid-frame, and no one knows it if ever learns how. Use lua hooks instead.
