### ISSUE TITLE
Ram Search Go to Address... exception: "Value was either too large or too small for an Int32"

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1549]
When I was searching special values in GBA ram I found many possibilities in memory.
Deep analyzing gave me only two results (I thought so..?). Only this 2 seems to be right values but it was a little problem to take a look at together in **RAM Search** window at once.
I had to scroll up and down every time to check if my condition and founded values are correct (I used method frame by frame).
I was trying to rescan many times with directly possible existing values in special frames (in the special game moments), what I thought that it was a correct state and in next step by frame but nothing found at all.
I think that I skipped too many values and then probably I got no results (I'm bad with this things, I think..?)
Then I'd an idea to go fast between found values (possibly best results for me) and I used for this **Go to Address** option to switch between positions (in this moment I was directly in ram address 4B40 but I wanna return back to 2020 then I enter -2000 and next I clicked **OK** button).
-2000 in hex is FFFFFFFFFFFFF830 (I copied it to clipboard from calculator and I paste it to the **Go to Address** then exception showed up!).
I make screenshot:
![gba_ram_srch_ex](https://user-images.githubusercontent.com/49565819/56461249-f05b2b00-639e-11e9-9118-13bae7ab9db5.png)

It's possible to select only chosen part of memory to scan/search? (for example only between 1000 to 2000 and 3000 to 4000 at once)

**Comment by YoshiRulz** [comment]
Leaving this open because I assume that UX isn't acceptable.

**Comment by zeromus** [comment]
I think the UX is acceptable. This is a rare case where the built-in exception handler does the job well enough, since the state of the application is perfectly valid afterwards. All we'd accomplish with more code is a less scary error message.
For @Croopper: click DWord in the windows calculator

**Comment by Croopper** [comment]
Ah... I see now! Some hex editor like **wxHexEditor** or **HxD** have option **Go to Address** from current point (not only from beginning like it is here) but this is much more simpler (I guess?) because it's only works for exactly passed address and you cannot go up and down with minus or plus address from current selected.

For @zeromus: **DWord** is okay.

**Comment by vadosnaprimer** [comment]
Setting the range sounds like a nice to have feature that we lack.

**Comment by Croopper** [comment]
I'm trying, but something's wrong. Probably the same value I can get in another addresses too but only some of them are correct. It's less probability that my value could change address dynamically (it's dev fake trick, maybe?). But I think that I just do it wrong. However in turn value seems to be somewhere else (it's possible in GBA rom?). Anyway forget it, this is only game. Always we can change the rom.
