### ISSUE TITLE
Does it make sense to have/leave tastudio open when recording a traditional movie?

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#1550]
see #1543
If the tastudio project is dirty it will prompt to save it before recording the movie. As if it's about to clobber the movie state (sensibly; it is). But it should probably close tastudio too.

**Comment by vadosnaprimer** [comment]
I'd close this until we find a person who explicitly needs this and can express in human language why.

**Comment by vadosnaprimer** [comment]
It'd be really stupid and annoying to implement logic in tastudio that'd make it properly restart when movie recording starts, and I'm not gonna do it ever. What I can do is forcing it to close when movie recording (or playback?) starts in emuhawk.

**Comment by adelikat** [comment]
This was fixed by disabling the ability to start a new movie with tastudio open, some months ago
