### ISSUE TITLE
Double right click on Branches list in TAStudio cause an exception: "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1551]
SS with exception:
![missclick](https://user-images.githubusercontent.com/49565819/56470591-88a4ee80-6437-11e9-9eb4-31728cd9abfd.PNG)

**Comment by Croopper** [comment]
Okay I know how to do it. It seems that BizHawk don't like me anyway, I guess. Basically to reproduce it you have to click twice right mouse button and open twice menu context on Branches list.

**Comment by YoshiRulz** [comment]
FYI you can copy the text from the crash dialogs.
