### ISSUE TITLE
Unreadable frame value in TAStudio

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1552]
It's possible to make it readable? I suggest to add value for example per 6 frames or 8 (it could be configurable why not?). I leave the decision to you as it'll be done.
SS:
![unreadableframes](https://user-images.githubusercontent.com/49565819/56496361-a0887b00-64e8-11e9-861e-dc5f2a77efe3.PNG)

**Comment by YoshiRulz** [comment]
Pivot the display so frames are the rows.

**Comment by vadosnaprimer** [comment]
This view mode will not be maintained so yeah, use the vertical one.
