### ISSUE TITLE
TAStudio Auto Hold/Fire Set Customs... Insert cause an exception: "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1553]
When I'm trying to insert a new pattern then I got this:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Client.EmuHawk.PatternsForm.GetPattern()
   at BizHawk.Client.EmuHawk.PatternsForm.ButtonBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

SS:
![autoholdexception](https://user-images.githubusercontent.com/49565819/56497142-e561e100-64eb-11e9-9153-34b7c7fe9a56.PNG)

**Comment by alyosha-tas** [comment]
I can't tell what the intent of "Default Bool Auto-Fire" is.

When auto fired patterns are first initialized, their size is #BoolButtons+2 

The part of the code at error here is using an index of #Boolbuttons+3 which obviously is wrong. 

Probably all the places that say: 
`index = _tastudio.BoolPatterns.Length + 1`
should instead be -1, but even if I do that I don't see what the point is. is it just showing the user what the default should be?

**Comment by alyosha-tas** [comment]
I went ahead and committed a fix for this. It at least makes sense now and doesn't throw an error, but I still am not sure what the original intent was. So maybe it will need an update at some point in the future, but probably no one has ever tried to do anything with it until now so i doubt it.
