### ISSUE TITLE
Add colour picker to Color field in TAStudio's subtitles editor

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1554]
I suggest to add color window here because I don't know what exactly color is here.

SS:
![colorsuggestion](https://user-images.githubusercontent.com/49565819/56498122-e137c280-64ef-11e9-99ef-5135683fd5b2.PNG)

**Comment by Spikestuff** [comment]
[Here this will help you.](https://htmlcolorcodes.com/)
It's ARGB. Always keep the first part FF and then add whatever.

**Comment by Croopper** [comment]
Thanks! That's helpful.

**Comment by vadosnaprimer** [comment]
It won't be limited to tastudio because it's not the primary keeper of subtitles. They are separate and their editor is separate.
