### ISSUE TITLE
visual c++ 2010 sp1 fail

### ISSUE THREAD

**Issue by Krideq** [TASVideos/BizHawk#1556]
I already tried to repair, uninstall and install, install the prerequisites reinstall and still nothing works anyone could help me?

**Comment by YoshiRulz** [comment]
Duplicate of #1265 which was closed due to inactivity.

I recall @zeromus commenting somewhere that badly-written programs can install a broken copy of the runtime where it shouldn't be, preventing you from installing it properly.

**Comment by zeromus** [comment]
delete (make backups, just in case) c:\windows\system32\msvc*100*.dll and c:\windows\syswow64\msvc*100*.dll
rerun prereq installer
you may also wish to install manually visual c++ 2010 sp1 redistributable (x86 and x64 both) from microsoft in case you have problems with any other programs, rather than copy from the (likely to be broken) backups

**Comment by Krideq** [comment]
i did that
and still don't work ;/

**Comment by zeromus** [comment]
Elaborate "nothing works"

**Comment by Krideq** [comment]
these things i tried it didn't worked, it's like i don't have vc 2010 but i have it, it's a weird issue and others peoples alredy tried to help me if you want i could get you screenshots

**Comment by zeromus** [comment]
Elaborate "didn't work"

**Comment by Krideq** [comment]
still with the same issue
says that vc is missing

**Comment by zeromus** [comment]
"same"? that's the first time you wrote "vc is missing".
WHAT said? And whatever "it" is, I don't think that's what "it" said.

**Comment by Krideq** [comment]
let me just send a screenshot

**Comment by Krideq** [comment]
![image](https://user-images.githubusercontent.com/49878344/56626873-de38f100-6619-11e9-80cb-623ae77d76ea.png)

**Comment by zeromus** [comment]
If you want, and you come on irc.freenode.net #bizhawk I will teamviewer to you and figure out what's wrong

**Comment by Krideq** [comment]
ok

**Comment by Krideq** [comment]
send me the link

**Comment by zeromus** [comment]
let me google that for your irc.freenode.net #bizhawk

**Comment by Krideq** [comment]
ok

**Comment by Krideq** [comment]
nvm i found it

**Comment by zeromus** [comment]
(SOLVED
broken visual c++ 2010 runtimes, as usual.
I'm attaching them here for future reference. They don't appear to be malware, just strange garbage. Why are they different? If they're legit (but variants) why can't our detector detect it?

https://www.virustotal.com/#/file/b2ad109c15eaa92079582787b7772ba0a2f034f7d075907ff87028df0eaea671/relations
https://www.virustotal.com/#/file/8793353461826fbd48f25ea8b835be204b758ce7510db2af631b28850355bd18/relations)
