### ISSUE TITLE
N64 save doesn't load after opening TAStudio

### ISSUE THREAD

**Issue by Capthowdy12301** [TASVideos/BizHawk#1561]
During gameplay I opened TAStudio and pressed the play button. The game went to the start screen and stayed there. I tried  to exit TAStudio and clicked "no" when asked about saving changes. Since them my save files are still in the save folder but don't show up in game. The in game menu acts as if I've never played.

**Comment by YoshiRulz** [comment]
The SaveRAM you see in the folder isn't your progress, it was made when you closed TAStudio. The only real issue is being able to open TAStudio without writing the SaveRAM to disk.

**Comment by Capthowdy12301** [comment]
Either way, I need to know how to get my saves back on the game.

**Comment by Capthowdy12301** [comment]
I opened TAStudio trying to rewind my game back a few seconds. Other than that I use this as a normal emulator.

**Comment by YoshiRulz** [comment]
Rewind is Shift+R by default. I'm afraid you'll have to replay up to where you were, there's nothing to undelete because the file was never made.

**Comment by Capthowdy12301** [comment]
So TAS deleted my previous save in the in-game menu? Where was that save
stored?

**Comment by YoshiRulz** [comment]
In memory (RAM).

**Comment by Capthowdy12301** [comment]
Thank you. I'll recover it from there.

**Comment by vadosnaprimer** [comment]
If the talk is about a SRAM file (or whatever in-game save it is), you have to manually tell it to put it on disk whenever the game creates it. I don't remember if it automatically creates itself. Putting on disk something that was in memory is called flushing. So when the Save RAM menu in bizhawk becomes bold, use Flush Save Ram option to put it on disk.
