### ISSUE TITLE
Issue with N64 controller on bizhawk Z button is spamming

### ISSUE THREAD

**Issue by 9math7** [TASVideos/BizHawk#1562]
Hi, i had an issue when setting up my N64 controller to bizhawk when i press the Z button it won't hold it's only spamming the button even if i hold it, please help!  in controller settings i put it in 
P1 Z the button is working but not holding thank you!

**Comment by vadosnaprimer** [comment]
Check autofire bindings.

**Comment by 9math7** [comment]
I can't find any bindings excepts for the joystick, i mean i set my controller in ''autofire controls'' instead of''Normal controls'', no many options there or im blind lol

**Comment by 9math7** [comment]
![bh1](https://user-images.githubusercontent.com/47719035/57556876-3e33d500-7346-11e9-8d4b-385ab9b4a5fe.png)
![bh2](https://user-images.githubusercontent.com/47719035/57556877-3e33d500-7346-11e9-9321-14cebfd7ea75.png)
![bh3](https://user-images.githubusercontent.com/47719035/57556878-3e33d500-7346-11e9-8abc-fc37a526cde4.png)

**Comment by 9math7** [comment]
Well i fugure out the problem, it was the hotkey, my Z was at fast forward so it was lagging, my other problem is when i press start it laggs, and rainbow colors everywhere until i unpause but thanks for your help any way!

**Comment by YoshiRulz** [comment]
OoT pause menu is #1372.
