### ISSUE TITLE
Need help for Glide64Mk2

### ISSUE THREAD

**Issue by 9math7** [TASVideos/BizHawk#1564]
Hi, i need some help, my setting was perfect on glide64mk2 like zero lagg or issue, and for an unknown reason, they didn't save, and i can't find the ''perfect settings'' anymore, like, my fps drops, sound is lagging, and certain zone in the game is more lagging than others now, sorry for the bad english, hope someone can help! Thanks you

**Comment by zeromus** [comment]
1. figure out how to save settings
2. take notes
3. save them
4. make backups
5. carry on, and write back here if the settings disappear again or you are unable to complete step 1

**Comment by 9math7** [comment]
1.Don't be mad 
2.Say something helpfull or say nothing
3.Don't be a D lol

**Comment by 9math7** [comment]
Never seen someone rude for nothing like that

**Comment by zeromus** [comment]
this thread's history has been rewritten so this thread is trashed. for N64 information about "perfect settings" is filed under the name of the game you're trying to find settings for.

**Comment by YoshiRulz** [comment]
@9math7 Please join IRC so we can teach you how to use BizHawk without you opening dozens of issues.
