### ISSUE TITLE
Add ability to parse JSON to Lua Commands

### ISSUE THREAD

**Issue by Netbrian** [TASVideos/BizHawk#1567]
Bizhawk has been great at adding features like sockets, memory mapped files, and other features to allow it to be controlled with external programs, such as Python.

When doing this, we'd want the ability to have the external program command Bizhawk to do certain things.  One of the easiest ways I've found to do this is to use JSON to encode communications to and from the client.  However, you need to install an external library to encode and decode the JSONs on the Bizhawk end.

I'd like to request making this functionality built-in.  There are existing libraries under open-source licenses, such as JSON.lua ( https://github.com/rxi/json.lua ) that could be integrated, so we don't end up rolling our own.

I'm completely open to serialization formats (YAML, MessagePack, etc), but JSON seems like the simplest place to start.

**Comment by zeromus** [comment]
No. bring your own json.lua. We don't include things which can be trivially included by the lua users, only things which are difficult for the lua users to bring themselves.

**Comment by Netbrian** [comment]
Fair enough, thank you very much!
