### ISSUE TITLE
corrupted ROM causes apphang in gbhawk

### ISSUE THREAD

**Issue by ReaperMan02** [TASVideos/BizHawk#1570]
When running a corrupted Gameboy ROM, unexpected execution causes bizhawk to app hang

Steps to reproduce:

1. Use attached patch to patch pokemon - blue version (ue) [s][!].gb (md5: 50927e843568814f7ed45ec4f944bd8b).
[pokemon blue corrupted.zip](https://github.com/TASVideos/BizHawk/files/3208627/pokemon.blue.corrupted.zip)
2. Run in emulator using gbhawk as the core.
3. Start a new game.
4. Once you gain control of the character, move in any direction.

**Comment by Asnivor** [comment]
test

**Comment by Asnivor** [comment]
test

**Comment by Asnivor** [comment]
Ok, so with the latest build (master branch) emuhawk does not actually hang for me when debugging - i can open menus and observe the framecounter incrementing.

The rom itself does crash out to a black screen though.

This is also the same when running emuhawk directly (not debugging through VS).

So I would say this is probably normal behaviour for a corrupted ROM?

**Comment by ReaperMan02** [comment]
Are you sure you aren't using Gambatte/Sameboy(running gb in sgb mode)?  It crashes out just fine on those.

**Comment by Asnivor** [comment]
Haha, schoolboy error. Yup. I'll try with gbhawk

**Comment by Asnivor** [comment]
Ok, so the core is getting stuck in this while loop:

https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBHawk.IEmulator.cs#L122

as vblank_rise is never flipping to true- and hence the frame never ends. This would explain the lockup.

Not sure why it would be doing this though. Probably one for @alyosha-tas . At the very least I would imagine vblanks to be happening regardless of the ROM data that is presented to the core.

**Comment by Asnivor** [comment]
Hmmm, so if I remember correctly, the LR35902 is basically a Z80 with a smaller instruction set. I guess it's conceivable that the corrupted ROM is presenting opcodes that would be ignored by the LR35902, but *are* actually being interpreted by our Z80A core?

**Comment by zeromus** [comment]
"gameboy frames can be variable lengths"
This emulator is working according to specifications: some corruptions can cause the frame to never end. Not a bug. I understand why reaperman doesn't like that. This could be "solved" by adding a watchdog timeout to the emulation, but we don't have the right infrastructure for that (distinguishing infinite emulation loops from a long time spent debugging, or running lua callbacks, or updating tools is impossible to do in a clean way). Therefore, we shouldn't solve this. Maybe reaperman can modify his randomizing scripts to test in another process and put a timeout on that.

**Comment by alyosha-tas** [comment]
I have a basic debug line commented out where if cpu execution goes over like 1000000 cycles it will throw an exception, but I'm not sure what enabling it would help. Are you trying to accomplish / test something specific with this patch? What is the goal here?

**Comment by zeromus** [comment]
Reaperman randomly corrupts roms and records videos if anything interesting happens. The emulator hanging interrupts his workflow. He doesn't expect many guarantees beyond that. As long as he could catch that exception, it would be OK. Thought of another idea, maybe we could add a hack to this core (since this one is under our control at least) which just times out the frame after 6000 frames or so (no properly functioning game should ever turn off that long.. unless it halted, I guess). Reaperman's fuzz-testing has been helpful before, even if it's usually turning up stuff way too obscure for us to want to deal with. So this could be worth the investment if it's simple to "fix" just to see what else he finds

**Comment by NarryG** [comment]
I think you're thinking of me @zeromus. I maintain a project named the RTC (Real-Time Corruptor) and for a while, it was built on top of Bizhawk (we've recently reworked the corruption code into a set of libraries but Bizhawk is still one of the implementations of the library).

@ReaperMan02 Are you using the RTC by any chance? In the fork of Bizhawk we use for the RTC, I've manually handled some edge-cases such as this. I could easily add handling of this to the RTC fork to keep weird hacks out of Bizhawk master.

**Comment by zeromus** [comment]
No, I'm thinking of reaperman. He's been fuzzing our emulators with one corruptor or another (I dont know which one(s)) for like 10 years.

**Comment by alyosha-tas** [comment]
Ok I added a 10 second timeout. I've never seen anything even near that long in my testing, so it should be enough for this type of work.

**Comment by ReaperMan02** [comment]
So, now that I have a bit of time, I would like to answer a question or two, as well as ask one of my own.
First off, since this was asked about my work, I use my own written script for corrupting games.  I do acknowledge RTC as a great tool for those without programming expertise to get their feet wet in ROM corruption.
With that said, since apparently the GB has the capability of having variable frame times, how exactly does the AVI writer handle this? I would assume that AVIs must have a fixed frame rate.

**Comment by vadosnaprimer** [comment]
CFR is the only way that we have for now. In the future it should split the segments on fps changes.

**Comment by ReaperMan02** [comment]
So I guess it just captures the frame at 60Hz intervals?
