### ISSUE TITLE
C64 games that take advantage of VSP will crash when starting

### ISSUE THREAD

**Issue by switchhacks** [TASVideos/BizHawk#1571]
Any game that uses VSP to scroll the screen crash on startup, and cannot be played. This is especially annoying because BizHawk is the only Commodore emulator that has movie recording and playback for TAS.

**Comment by hegyak** [comment]
Can you tell us what game(s) have issues?

**Comment by SaxxonPike** [comment]
VSP support is definitely lacking. It's not something that is explicitly supported, rather it is a function of how the VIC works.

I did a bit of research and found some small yet potentially helpful VSP resources that showed up a few months ago:
https://github.com/chris73it/C64_Scrolling_PAL

**Comment by SaxxonPike** [comment]
Oh, I'll take this one. Forgot to mention that.

**Comment by SaxxonPike** [comment]
This intro from JCB is the simplest demonstration of the effect. I've extracted it from the source T64 (as we don't support that format currently)
[vsp-ik.zip](https://github.com/TASVideos/BizHawk/files/3360201/vsp-ik.zip)

**Comment by SaxxonPike** [comment]
These updates should resolve much of the VSP problems, once they're more fully vetted.

https://github.com/TASVideos/BizHawk/pull/1607

**Comment by SaxxonPike** [comment]
VSP effects all seem to be working with that commit, including the examples in that Github repo. I'm closing this as fixed.
