### ISSUE TITLE
Cheats window crashes an emulator

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1577]
When you'll launched rom (in my case it's GBA rom), and cheats window'd be shown too, then you have to freeze any of cheat item. Now you just try to close the rom and this exception'd show up:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EmuHawk.exe
  Problem Signature 02:	2.3.1.1
  Problem Signature 03:	5c3247d3
  Problem Signature 04:	BizHawk.Emulation.Common
  Problem Signature 05:	2.3.1.1
  Problem Signature 06:	5c3247cb
  Problem Signature 07:	70
  Problem Signature 08:	0
  Problem Signature 09:	System.AccessViolationException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	5260
  Additional Information 2:	52607ad1eda597f38530f499b98c0411
  Additional Information 3:	0497
  Additional Information 4:	04974f193e1364a76617b68ee816f59b

**Comment by YoshiRulz** [comment]
Please try with [this dev build](https://send.firefox.com/download/1dfbb500127d4da0/#NZypv8e4kvQzZAtrZO-uYg) ([source](https://github.com/YoshiRulz/BizHawk/tree/custom1577a)).

**Comment by Croopper** [comment]
I can't look:
![ss_29_05_2019_05_57_35](https://user-images.githubusercontent.com/49565819/58559019-b983fa80-8211-11e9-816e-f76a82ae67fa.png)

**Comment by YoshiRulz** [comment]
Uhh, close EmuHawk and delete `config.ini`. That's from my computer (oops) so it's almost certainly messing with things.

**Comment by Croopper** [comment]
I delete it but it was the same problem. I know now why this error is, because in your emulator catalogue it was not found "Firmware" directory (I added it). It seems to that main problem is figured out in your version, but still I think that you should add this catalogue to release or automake it before copy new firmware's.

**Comment by YoshiRulz** [comment]
So you can play GBA games now?

**Comment by Croopper** [comment]
Yes for now :-). Heh... I just forgot that in the first place I copied entire Firmware directory to new downloaded emulator. By the way when can I expected new release of emulator?

**Comment by YoshiRulz** [comment]
> when can I expect a new release

¯\\\_(ツ)\_/¯
