### ISSUE TITLE
PCEHawk may be missing an audio channel.

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1580]
I was comparing my TAS for Splatterhouse on PCE to an actual console and I noticed somthing about the first level in particular. 

On console it seems like there are more Percussion sound effects playing.  On Bizhawk, however, it just sounds like it's playing Hi-Hats.

here's what it sounds like on [Console](https://www.youtube.com/watch?v=tO29L4841A4)

and here's what it sounds like on [bizhawk](https://www.youtube.com/watch?v=wsNv-qpXKf4)(my TAS)

if you compare the music from the first level, you can definitely tell that BizHawk is either missing sound effects or it's not playing the correct sounds.  I also believe the audio is accurate on PCEjin.

**Comment by jjfmz42015** [comment]
PCEHawk is a lost cause


Use OoTake or Mednafen..... Or even old magic engine.

**Comment by EZGames69** [comment]
Use those for TASing?  I dont think those emulators are allowed for TASVideos anymore.

**Comment by alyosha-tas** [comment]
PCEHawk is certainly our weakest core, but I wouldn't say it's a lost cause, it's more just that we don't have the coding manpower to fix it. No one has the time / interest. And by no one I basically mean me.

But there is an unimplemented part of the PSG in PCEHawk that might be causing your problem.

```
case 8: // LFO
					// TODO: implement LFO
					break;
				case 9: // LFO Control
					if ((value & 0x80) == 0 && (value & 3) != 0)
					{
						Console.WriteLine("****************      LFO ON !!!!!!!!!!       *****************");
						Channels[1].Enabled = false;
					}
					else
					{
						Channels[1].Enabled = true;
					}
					break;
```

This is not implemented. If you open the console window in Bizhawk (View -> Display log Window, then restart bizhawk completely.) And you see the LFO ON!!!!! text appear when the drums should be playing, you know where your problem is.

Here is a great resource for the PCE PSG:

http://www.magicengine.com/mkit/doc_hard_psg.html

If the LFO is indeed your problem, why not take a shot at implementing it? It looks pretty easy and should be tractable even for a beginner.

**Comment by EZGames69** [comment]
I should impliment it?  I dont know the first thing about coding for emulators.  I could at least see if that text is showing up like you said.

**Comment by jjfmz42015** [comment]
Why would mednafen or ootake be banned from TASsing. they are cycle accurate. the pcehawk core is garbage.

**Comment by EZGames69** [comment]
Well we can assume it is due to better emulation, but this is the only resource I can find right now: http://tasvideos.org/Bizhawk/PCE.html

If a TASVideos Staff member wants to explain it then that would be appreciated.

**Comment by jjfmz42015** [comment]
That link is dated. Better emulation lol. Not even comparable let alone better. The two I mentioned are cycle accurate. The bizhawk pce core is hot garage and not even close to accurate. Also note the other two currently hold 100% compatibility while being cycle accurate. You can't be better than 100% especially when your missing sound channels and full of graphical glitches. Bizhawk is awesome but it's pce core is horrendous by today's standards

**Comment by EZGames69** [comment]
I’d like to see a source for this 100% number your getting.

**Comment by alyosha-tas** [comment]
Pcejin is still accepted for tases. 

Yeah that link should be edited, PCEHawk has not aged well at all.

An issue for porting a different core (ex mednafen) has been open for a while now, I think it will remain open for a while longer. Realistically we don’t have enough people to keep BizHawk updated. PCE and Apple II  are the hardest hit but even gba is long overdue for an update.

**Comment by Sonia-7** [comment]
And that's why I refrain from making movies on pcehawk until the mednafen core gets ported over, or, if by some miracle pcehawk gets fixed to the point it becomes as accurate as mednafen (which would probably be far more difficult).

By the way, I'm curious about something. Would porting mednafen's pce core be that much harder than say, the Saturn or PS1 ones (both of which have been already available in bizhawk for a while)?

**Comment by alyosha-tas** [comment]
For what it's worth I removed the language in the Bizhawk section of TASVideos about PCEHawk being better then other emulators.

**Comment by alyosha-tas** [comment]
> 
> 
> And that's why I refrain from making movies on pcehawk until the mednafen core gets ported over, or, if by some miracle pcehawk gets fixed to the point it becomes as accurate as mednafen (which would probably be far more difficult).
> 
> By the way, I'm curious about something. Would porting mednafen's pce core be that much harder than say, the Saturn or PS1 ones (both of which have been already available in bizhawk for a while)?

Probably not, but once again it's a matter of interest and time. Fixing PCEHawk wouldn't be more difficult necessarily, since a lot of underlying infrastructure works already. I think PCEHawk isn't as broken as is perceived, it just doesn't have anyone who wants to work on it.

@EZGames69 Did you check whether or not the message pops up for the missing LFO stuff?

**Comment by EZGames69** [comment]
I haven’t yet and I probably wont be able to do it for the next few days.

**Comment by EZGames69** [comment]
The message does not pop up.

**Comment by jjfmz42015** [comment]
Would it be possible to allow the emulator to do a core overide for pce and use the mednafen sgx liberto core dll to be used?

**Comment by YoshiRulz** [comment]
Not currently, for the simple reason of "overcomplication" given in #1375.

**Comment by EZGames69** [comment]
I have tested Splatterhouse in the new waterboxed core and it sounds closer to what it should be on console.

**Comment by jjfmz42015** [comment]
> I have tested Splatterhouse in the new waterboxed core and it sounds closer to what it should be on console.

2.4.2 and last appveyor build i tried still use pce hawk. I havnt been online alot, life got crazy. But im dead curious is this waterbox core you speak of mednafen??? If so it is the accurate core or fast? This is exciting.

**Comment by EZGames69** [comment]
It’s in the latest dev build.

When you get it, go to config->cores->PCE->TerboGrapic(it’s a weird spelling), then reboot the core.  You should be able to use it then.

**Comment by jjfmz42015** [comment]
Awesome, gonna test a bit yay!

**Comment by jjfmz42015** [comment]
Im loving this. Is this based on the latest accurate mednafen core? Seems like it

**Comment by jjfmz42015** [comment]
1.24.3 yay wow awesome!!!

**Comment by jjfmz42015** [comment]
In my current testing i see one thing they forgot when water boxing this, ability to set autofire rate (mednafen core supports this) all other important things there

**Comment by nattthebear** [comment]
> In my current testing i see one thing they forgot when water boxing this, ability to set autofire rate (mednafen core supports this) all other important things there

Separate issue please, this is about audio problems in a different core

**Comment by jjfmz42015** [comment]
Its been a Turbografx 16 aka PCEngine weekend here and they waterboxed core is running perfect!! So happy this core was waterboxed!

**Comment by nattthebear** [comment]
Well, if it works there I'm canning this issue

**Comment by adelikat** [comment]
Autofire rate is handed with config -> autofire, and is not core dependent

**Comment by jjfmz42015** [comment]
> Autofire rate is handed with config -> autofire, and is not core dependent

Yes, my bad. So happy you guys did this!

**Comment by EZGames69** [comment]
I sotra disagree with closing this ticket as it’s specifically talking about PCEHawk’s audio.  Just because we have a new core doesn’t mean the issue in PCEHawk is gone.

**Comment by vadosnaprimer** [comment]
The core is to be mercy killed soon.
