### ISSUE TITLE
BizHawk doesn't understand non-QWERTY keyboard layouts

### ISSUE THREAD

**Issue by fgimian** [TASVideos/BizHawk#1584]
Hey guys, absolutely love BizHawk! 😄 

I use a non-QWERTY keyboard layout (specifically DVORAK) and notice that BizHawk does something a little weird.

For example, let's take the "Open" keyboard shortcut which is usually mapped to Ctrl+O.  On my keyboard, the O key is actually the R key.  In order to invoke the Open dialog box with my keyboard, I must actually type Ctrl+R while in BizHawk.

Another example, if I open the Hotkeys dialog box and type A O E U (which are equivalent to A S D F on QWERTY), the dialog box shows A S D F, not A O E U.

My current workaround is simply ignoring the displayed letters and remapping keys to be functionally equivalent.

e.g. if I remap Ctrl+O to be Open with my keyboard layout, the Hotkeys dialog says Ctrl+S, but it actually functions as Ctrl+O.

Any help is greatly appreciated, is this something that can be improved?

Kindest Regards
Fotis

**Comment by YoshiRulz** [comment]
Reproducible with 2.3.1 on Win10 *Home* 1709. Also I gained a keyboard? I had en-US QWERTY, en-AU QWERTY, and en-AU Dvorak (which was active), it added and switched to en-US Dvorak. I had to add en-US as a language and add the layout to remove it.

Also I checked and it *does* use Dvorak when typing in textboxes. It seems to be just accelerators and the keybind thingos that aren't working.

I'm curious to know if your keyboard was manufactured as Dvorak or if you changed the keycaps on a QWERTY, HID keyboards might be able to specify what layout they are on Windows.

**Comment by fgimian** [comment]
Hey @YoshiRulz, thanks so much for your help! 😄 

Yeah, Windows tends to add the QWERTY layout for the respective country when you add DVORAK.  You'll find DVORAK layouts for each country, so if you add the country that matches your existing QWERTY layout, it'll be a bit neater.  I usually remove all except DVORAK when I'm done.  Here's a little snippet of my PowerShell setup script:

```powershell
# Settings / Time & Language / Language /
# Set language to English (Australia) with the United States-Dvorak keyboard
$currentLanguageList = Get-WinUserLanguageList
if ($currentLanguageList.Count -ne 1 -or
    $currentLanguageList[0].LanguageTag -ne 'en-AU' -or
    $currentLanguageList[0].InputMethodTips.Count -ne 1 -or
    $currentLanguageList[0].InputMethodTips[0] -ne '0C09:00010409') {

    Write-ItemProgress "Setting the language list to en-AU with a Dvorak keyboard layout"
    $languageList = New-WinUserLanguageList en-AU
    $languageList[0].InputMethodTips.Clear()
    $languageList[0].InputMethodTips.Add('0C09:00010409')
    Set-WinUserLanguageList -LanguageList $languageList -Force
}
```

My keyboard is just a regular boring QWERTY keyboard (specifically an Apple Keyboard which I use in Windows).  The way I learned DVORAK was sticking a print-out of the layout on my screen and memorising it.  I decided to do this after having very severe RSI many years ago and trying to minimise my movements.

I can't see myself ever using another layout now, it's so comfortable 😄

**Comment by jdpurcell** [comment]
I researched this and it seems that our KeyInput class - because it's based on DirectInput - gets the key's "scan code". That corresponds to a physical key on the keyboard but not necessarily which letter it represents based on the keyboard layout mapping (i.e. the "virtual-key code"). To do this translation we'd need to call MapVirtualKey with MAPVK_VSC_TO_VK. Since it's a potentially complex and/or risky change, I am not going to attempt it at this time, but I wanted to leave the information here in case someone else tries to take it on.

**Comment by jdpurcell** [comment]
@fgimian I added this as an experimental setting if you'd like to try it. It's in the latest 
[development build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts) and you have to enable it in Config -> Customize -> Handle alternate keyboard layouts.

**Comment by fgimian** [comment]
> @fgimian I added this as an experimental setting if you'd like to try it. It's in the latest
> [development build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts) and you have to enable it in Config -> Customize -> Handle alternate keyboard layouts.

Thank you so so much, I'll check it out shortly and let you know how it goes 😄 

Cheers
Fotis

**Comment by fgimian** [comment]
> [@fgimian](https://github.com/fgimian) I added this as an experimental setting if you'd like to try it. It's in the latest [development build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts) and you have to enable it in Config -> Customize -> Handle alternate keyboard layouts.

I honestly have no idea how I forgot this issue for so so so long (this has to be a record), but just wanted to tell you that the experimental feature appears to work perfectly here. Thank you so so much!! 😄 

Cheers
Fotis
