### ISSUE TITLE
N64 analog stick reverses at low magnitudes

### ISSUE THREAD

**Issue by noobkiller012345678** [TASVideos/BizHawk#1585]
on sm64 when i move slowly mario moves the oppisite way of what im holding, when i go full Power he goes the way im holding.... why??????????????????

**Comment by NarryG** [comment]
The default binds for N64 are a bit funky. Make sure you don't have the analog stick bound digitally and then flip the Y axis in the analog menu.

**Comment by noobkiller012345678** [comment]
> The default binds for N64 are a bit funky. Make sure you don't have the analog stick bound digitally and then flip the Y axis in the analog menu.

i have changed to what i want but it still backwards when lightly pushed but normal when hardly pushed

**Comment by noobkiller012345678** [comment]
> The default binds for N64 are a bit funky. Make sure you don't have the analog stick bound digitally and then flip the Y axis in the analog menu.
> edit: see also #1481 --yoshi

imma try what said there

**Comment by YoshiRulz** [comment]
@noobkiller012345678, were your binds messed up or is there an actual bug in your controller stack somewhere?
