### ISSUE TITLE
Performance loss after merger of pr #1462

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1587]
There is a substantial performance hit due to the new mem callbacks. NESHawk for example went from about 140 fps to about 90 fps for me unthrottled. Not sure what the best mitigation approach is, maybe some global variable to only activate callbacks when checked?

**Comment by nattthebear** [comment]
OOof.  We've built that sort of optimization on some cores before; where the core itself has a single bool check if any callbacks are enabled, and if not short circuits the whole thing

**Comment by adelikat** [comment]
That's a pretty unacceptable performance loss.  We could roll it back with enough git-fu and then reassess

**Comment by alyosha-tas** [comment]
It can be fixed if callbacks are initialized to empty functions and then only changed to their utility versions when actually needed. This seems to be the intent anyway, but the infrastructure isn't there for it right now.

**Comment by vadosnaprimer** [comment]
Please test the dev build.

**Comment by alyosha-tas** [comment]
cool, looks good.
