### ISSUE TITLE
Code/Data Logger not logging for SNES

### ISSUE THREAD

**Issue by Yoshimaster96** [TASVideos/BizHawk#1597]
For some reason, no matter how long I play, the logger stays at 0%. What's wrong?

![Capture12](https://user-images.githubusercontent.com/15160568/59810714-2c8e0780-92cc-11e9-9120-b73f5d36065d.PNG)

[EDIT]
Tried using the Snes9x core, but CDL is greyed out in the Tools menu, and I can't open it at all.

**Comment by zeromus** [comment]
needs special handling; can be easily done once waterbox is fixed. in the meantime there's _nothing you can do about it_

**Comment by Yoshimaster96** [comment]
Did it work in a previous version?

**Comment by zeromus** [comment]
doesn't look like it.

**Comment by vadosnaprimer** [comment]
An actual patch is needed now that we can build wbx.

**Comment by gocha** [comment]
More correctly, it does not seem to work as expected with cartridges with extra chips. Star Fox has a Super FX chip. (At least, it does not work good with Super FX and SA-1)

CARTROM is covered via [Cartridge::rom_read function in markup.cpp](https://github.com/TASVideos/BizHawk/blob/ce7d6cdcf5222152df72eb48a2790eec21fc283b/waterbox/libsnes/bsnes/snes/cartridge/markup.cpp#L67). However, [Super FX's bus_read reads ROM without calling Cartridge::rom_read or any CDL functions](https://github.com/TASVideos/BizHawk/blob/ce7d6cdcf5222152df72eb48a2790eec21fc283b/waterbox/libsnes/bsnes/snes/chip/superfx/memory/memory.cpp#L9). I guess that's the cause of the issue.

**Comment by zeromus** [comment]
I plan to do this any day now to prove that the waterboxdev environment works... but dont let that stop anyone else from doing it first....
