### ISSUE TITLE
Firmware issues - BizHawk 2.3.2 x64 stable

### ISSUE THREAD

**Issue by LodanZark** [TASVideos/BizHawk#1598]
![firmwares](https://user-images.githubusercontent.com/11250310/59857383-bbecf680-9370-11e9-95b6-db81d37099b4.png)

Missing the **A78 NTSC BIOS** details:
SHA-1:	D9D134BB6B36907C615A594CC7688F7BFCEF5B43
MD5:	0763F1FFB006DDBE32E52D497EE848AE
CRC32:	5D13730C

Missing the **Vextrex BIOS** details:
SHA-1:	65D07426B520DDD3115D40F255511E0FD2E20AE7
MD5:	AB082FA8C8E632DD68589A8C7741388F
CRC32:	BA13FB57

The **Mine Storm** has 2 entries with same hash (that matches with bios hashes), according to no-intro database there it's 3 versions of the game:

Name:	Mine Storm (World).vec
SHA-1:	5F00ED35F189357B4A16A190520166371CA57906
MD5:	EE19E350BE0AF2A509A202B057488DC8
CRC32:	6D509566

Name:	Mine Storm II (USA) (Rev 2).vec
SHA-1:	1FDCC6E54AE5177BC9CDC79CE616AE3401E5C229
MD5:	126FECBF4FB09FDB5A3C9AF92ABAED7C
CRC32:	F5B3B374

Name:	3D Mine Storm (USA).vec
SHA-1:	1731E892DA8945FE4945B43847D23960C581682A
MD5:	1A81FEA8AC1C1D46DE7B633814130857
CRC32:	B2313487

**Comment by alyosha-tas** [comment]
I fixed A7800 that’s my bad.

Don’t worry about vectored for now it’s WIP.

**Comment by Jhynjhiruu** [comment]
![image](https://user-images.githubusercontent.com/24824597/59924836-8b6b9200-942e-11e9-8922-1e74d77c4b70.png)
I think you might have managed to duplicate it... unless that's an issue my end?
