### ISSUE TITLE
[Feature request] Add Playstation 2 emulation with "PCSX2 1.6 stable release"

### ISSUE THREAD

**Issue by atomic83GitHub** [TASVideos/BizHawk#1601]
PS2 emulation on bizhawk is missing right now but is an important part of retrogaming history and is now finished enough that Tas recording is now possible with PCSX2. It would be an awsome improvement to Bizhawk which is part of a all in one and simple to use emulator goal.

- TAS feature in PCSX2: video recording, core patching/debuging, console logging, input recording.

However, due to it's design, it must be integrated as a standalone emulator (like in retropie):

![image](https://user-images.githubusercontent.com/26351275/59868350-067e6b00-9391-11e9-9259-ebaf5d12bcb2.png)

I can give you the build compilated with source code and update it when necessary.

Note: 1.6 stable will be comming very shortly.

**Comment by atomic83GitHub** [comment]
Users will also be eligible to PCSX2 forum help and I can took in charge the PCSX2 build itself.

**Comment by YoshiRulz** [comment]
They offer LGPLv3 licensing so it could happen, not anytime soon though. Once the first movie made with PCSX2 is accepted to TASVideos, I'll add it to [the readme](https://github.com/TASVideos/BizHawk#related-projects) with Dolphin and the others.

Closing this until someone in the future has the time and resources to decouple the emulator from the frontend and port it to a BizHawk or libretro core.

**Comment by Spikestuff** [comment]
...Can we not use/consider an emulator that requires plugins to be decently playable?

And an emulator that's own standalone can't even functionally TAS for a good amount of years even back when they didn't care.

Also I have stated other points on that [TASVideos forums](http://tasvideos.org/forum/viewtopic.php?p=470145#470145) as to why not which I won't be repeating.

**Comment by vadosnaprimer** [comment]
I've heard pcsx2 can't be built as 64-bit either.

**Comment by Wuups** [comment]
I've already detailed my experience testing these tools on the Tasvideos forum, in short: No. 
Plugins, hacks and inaccuracies everywhere.
>Desyncs.
Just.. No.

**Comment by NarryG** [comment]
> I've heard pcsx2 can't be built as 64-bit either.
You're right there. The JIT is 32-bit only.
If I'm not mistaken, you can get it to build under 64-bit but it's unplayable due to the lack of JIT.

**Comment by nattthebear** [comment]
amd64 is the only supported platform for BizHawk, and that's a hard requirement due to the Waterbox cores.  So this one isn't going to happen ever.  Wake me up if DobieStation ever gets good or if PCSX2 goes to amd64.

**Comment by YoshiRulz** [comment]
DobieStation is in `master` experimentally now, see #2250.
