### ISSUE TITLE
Improper Sega Mouse motion

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#1602]
It seems that the X and Y values set for the Sega Mouse is the absolute position of the mouse on the screen (with the center being (0,0)). However, the values that are supposed to be set is the distance that the mouse has traveled. The Y axis is flipped, too.

**Comment by YoshiRulz** [comment]
HMM
https://github.com/TASVideos/BizHawk/blob/b390c2829c688cfcd694d3d8ff0b452fb0778337/BizHawk.Client.EmuHawk/tools/VirtualPads/schema/GenSchema.cs#L282-L293

**Comment by nattthebear** [comment]
Is this a virtual pad problem or a core problem?

**Comment by getCursorsExe** [comment]
This is a emulator coding bug, since this does not occur in original Genesis Plus GX (libretro).

**Comment by YoshiRulz** [comment]
@getCursorsExe Can you confirm that the values (as seen in TAStudio) are relative movement i.e. (2, 5) doesn't snap the cursor to the centre, but makes it drift right and up?

**Comment by getCursorsExe** [comment]
This was tested using Sonic 1 Point and Click edition (By Nat the Porcupine).

**Comment by YoshiRulz** [comment]
Forgot to close this with a keyword when committing 771b5397f, but it's fixed.
