### ISSUE TITLE
Rerecording count skyrockets

### ISSUE THREAD

**Issue by Snodeca** [TASVideos/BizHawk#1605]
As shown in this video: https://youtu.be/ygEuekPXQWk
It skyrockets when you select a bunch of frames in TAStudio,
delete it by right clicking & deleting or using the hotkey CTRL+Del,
then by going to Edit at the top and pressing on Undo or using the hotkey CTRL+Z.

It went from a rerecording count of 3 to 161, and it can go from 13,000 to 31,000ish. This is consistent.

This issue is new as of Bizhawk v2.3.2, and it does not occur on v2.3.1.

**Comment by EZGames69** [comment]
After a bit of testing, it also occurred in 2.3.1, however it was on an incredibly small scale compared to this.  At most you would only jump up 5-6 extra rerecords, where here it’s a drastic difference.

**Comment by YoshiRulz** [comment]
Bisect points to 694ba93ec.

**Comment by vadosnaprimer** [comment]
When I do this on latest master, I only get 1 more rerecord after Undo.

**Comment by adelikat** [comment]
This has been fixed

**Comment by EZGames69** [comment]
I tested this personally yesterday and I can confirm it’s fixed.  (Inb4 someone else tests and it doesn’t work)
