### ISSUE TITLE
Existing firmware ROMs display as "Missing!"

### ISSUE THREAD

**Issue by Bedrock206** [TASVideos/BizHawk#1606]
Hello, I'm rather new to this in-depth level of emulation. I'm experiencing an issue with importing firmware ROMs. I have the correct ROMS in the correct location...
![image](https://user-images.githubusercontent.com/43396812/60474854-4f53e080-9c29-11e9-88c5-d715a5b307e8.png)
..but as you can see they still appear as missing. (Excluding CX4)
![image](https://user-images.githubusercontent.com/43396812/60474814-1a478e00-9c29-11e9-82c1-ef669cdb9130.png)
Can anyone help me out?
Thanks.

**Comment by YoshiRulz** [comment]
Is your global firmware path (`Config` > `Paths...` > `Global`) set to `.\Firmware`? If not you'll need to change it or set them individually.

**Comment by zeromus** [comment]
Those roms aren't supported. They're some new split-up formats someone invented while trying to be organized but succeeding only in creating redundant files and sowing confusion. The best thing you can do is acquire the supported combined files; you can open a new ticket if you wish to support bsnes new-format split-up snes firmware files, but it won't solve your problem now.
