### ISSUE TITLE
GBHawk: playing a movie from save state causes error.

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1608]
I get an error when trying to play a movie from a savestate.

[Track Meet (USA, Europe).zip](https://github.com/TASVideos/BizHawk/files/3364378/Track.Meet.USA.Europe.zip)

**Comment by alyosha-tas** [comment]
That movie is from 2.3.1. Are you trying to load it on 2.3.2? It won't if so because the states have changed.

**Comment by Reinc01** [comment]
I am. I did not notice a warning about save states not working.

**Comment by alyosha-tas** [comment]
savestates often become incompatible between versions, but you are right we don't have a warning about it, probably should at some point.

**Comment by Reinc01** [comment]
What I meant to say is that I did not notice a warning about incompatible save states in the new version's release notes on Tasvideos.
