### ISSUE TITLE
Inaccurate CX4 Chip Emulation on BSNES Core

### ISSUE THREAD

**Issue by schatty360** [TASVideos/BizHawk#1609]
Having done testing on both Mega Man X2 and X3 on the BSNES core, the instances where the CX4 chip is used by the game produce a few seconds worth less lag than the original cartridge on console. Is there any known way around this? For instance, the final climb in Mega Man X3 seems to be 2 seconds faster on Bizhawk using BSNES.

**Comment by zeromus** [comment]
Go find out what version of bsnes this was fixed in

**Comment by schatty360** [comment]
v111 has altered the slowdown to be more accurate.

**Comment by nattthebear** [comment]
https://github.com/byuu/bsnes/commit/6e5542aa20e1b483e3a8249018d183f7fc06a969

**Comment by nattthebear** [comment]
Investigated this.  The update in v111 was a change in timing of the CX4 cache feature.

But our version of bsnes doesn't even have the cache feature at all.  Targeting porting of this one fix is a non-starter.  Closing this issue and rolling into https://github.com/TASVideos/BizHawk/issues/1797.
