### ISSUE TITLE
Issues starting up PSX roms

### ISSUE THREAD

**Issue by GeneralDoomsday** [TASVideos/BizHawk#1610]
Used BizHawk a long time for PSX, but today i encountered this Error and i dont know what to do:

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.FreeRenderTarget(RenderTarget rt)
   bei BizHawk.Client.EmuHawk.RenderTargetFrugalizer.Dispose()
   bei BizHawk.Client.EmuHawk.DisplayManager.Dispose()
   bei BizHawk.Client.EmuHawk.MainForm.Dispose(Boolean disposing)
   bei System.ComponentModel.Component.Dispose()
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by YoshiRulz** [comment]
Try changing to OpenGL in `Config` > `Display...` > `Display Method`.

**Comment by GeneralDoomsday** [comment]
I get errors with GDI+ and OpenGL aswell:

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei BizHawk.Bizware.BizwareGL.Drivers.OpenTK.IGL_TK.FreeTexture(Texture2d tex)
   bei BizHawk.Bizware.BizwareGL.Texture2d.Dispose()
   bei BizHawk.Bizware.BizwareGL.Drivers.OpenTK.IGL_TK.FreeRenderTarget(RenderTarget rt)
   bei BizHawk.Client.EmuHawk.RenderTargetFrugalizer.Dispose()
   bei BizHawk.Client.EmuHawk.DisplayManager.Dispose()
   bei BizHawk.Client.EmuHawk.MainForm.Dispose(Boolean disposing)
   bei System.ComponentModel.Component.Dispose()
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

System.ArgumentException: Ungültiger Parameter.
   bei System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   bei BizHawk.Bizware.BizwareGL.Drivers.GdiPlus.IGL_GdiPlus.CreateRenderTarget(Int32 w, Int32 h)
   bei BizHawk.Client.EmuHawk.RenderTargetFrugalizer.Get(Int32 width, Int32 height)
   bei BizHawk.Client.EmuHawk.DisplayManager.UpdateSourceDrawingWork(JobInfo job)
   bei BizHawk.Client.EmuHawk.DisplayManager.UpdateSourceInternal(JobInfo job)
   bei BizHawk.Client.EmuHawk.DisplayManager.UpdateSource(IVideoProvider videoProvider)
   bei BizHawk.Client.EmuHawk.MainForm.Render()
   bei BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by YoshiRulz** [comment]
PSX works fine for me, can you try deleting/renaming `config.ini`? Also, did you run into this issue after updating, or did your existing copy which worked yesterday suddenly stop working?

**Comment by Spikestuff** [comment]
Dumb question. What are you attempting to load and what's the image file you're using into BizHawk?

**Comment by GeneralDoomsday** [comment]
> PSX works fine for me, can you try deleting/renaming `config.ini`? Also, did you run into this issue after updating, or did your existing copy which worked yesterday suddenly stop working?

it worked fine a week ago. havent played since then, today it didnt work anymore

> Dumb question. What are you attempting to load and what's the image file you're using into BizHawk?

i load up the marked cue file
![image](https://user-images.githubusercontent.com/52710003/60901624-9025a800-a26e-11e9-9540-69ae1026aa87.png)

**Comment by GeneralDoomsday** [comment]
I deleted the config, now it works again. Thanks for the tip.
