### ISSUE TITLE
Virtual Pad off by 1 Bug Using Analog Stick.

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1612]
When using an analog stick, for ranges -128 to 127, virtual pad incorrectly clamps the range to -127 to 127. This is easy to see by displaying input on the main BizHawk window.

**Comment by YoshiRulz** [comment]
I know, [not a regression](https://github.com/TASVideos/BizHawk/commit/1c0622d272866fa4ead4fc4b267ba94e9b663e6d#diff-6ee3413ae313695f025d44b3960a5039L184) btw
