### ISSUE TITLE
Basic Bot: Best Attempt Playback Does Not Give Expected Value

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#1613]
I have posted something on using the Basic Bot here, but I have been encountering issues.  The main issue is that after getting a great Best Attempt, the playback does not give the same result.  I have attached a picture showing the difference.  

![Basic Bot Issue - Playback Does Not Give Expected Value Sometimes](https://user-images.githubusercontent.com/34147391/61011630-655c5200-a349-11e9-997e-5ca79b4528ff.PNG)

Video on Basic Bot usage from what I could figure out.  If someone who is not the originalauthor wants to take a look.
http://tasvideos.org/forum/viewtopic.php?p=485873#485873

**Comment by ShinobiWannabe** [comment]
Ok noticed one thing to help reproduction.  When you click Stop, then press Play Best, it will sometimes play the CURRENT attempt. Then if you press Play AGAIN to play the best it will play the best.  Not sure if this is consistent to always get the best.

**Comment by ShinobiWannabe** [comment]
Well, I think I may have fixed the issue.  It was irritating me so I pulled down the project and started screwing with it and figured out what was going on.  Seems to be very consistent so far.  May have been an issue with TAS Studio only being up, but I don't know the flow of this program well enough.  I am not familiar with Git so tomorrow I will figure out how to commit this after doing some more testing.  But for now explain here what I have been doing.

	//Upon Load State, TASStudio uses GlobalWin.Tools.UpdateBefore(); as well as GlobalWin.Tools.UpdateAfter(); 
		//Both of which will Call UpdateValues() and Update() which both end up in the Update() function.  Calling Update() will cause the Log to add an additional log.  
		//By not handling both of those calls the _currentBotAttempt.Log.Count will be 2 more than expected.
		//However this also causes a problem with ramwatch not being up to date since that TOO gets called.
		//Need to find out if having RamWatch open while TasStudio is open causes issues.
		//there appears to be  "hack"(?) line in ToolManager.UpdateBefore() that seems to refresh the RamWatch.  Not sure that is causing any issue since it does look like the ramwatch is ahead too much..
	

To resolve this issue I created 
	public int LastFrameAdvanced { get; set; }
		#endregion

		public bool HasFrameAdvanced()
		{
			//If the emulator frame is different from the last time it tried calling
			//the function then we can continue, otherwise we need to stop.
			return LastFrameAdvanced != Emulator.Frame;
		}


and then called these in teh Update function near the start
	if (!HasFrameAdvanced())
			{
				return;
			}

and at the end of Update() put a check to prevent excessive inputs being generated.

				//Before this would have 2 additional hits before the frame even advanced, making the amount of inputs greater than the number of frames to test.
				if (_currentBotAttempt.Log.Count < FrameLength) //aka do not Add more inputs than there are Frames to test!
				{
					PressButtons();
					LastFrameAdvanced = Emulator.Frame;

				}

-

**Comment by vadosnaprimer** [comment]
So does it happen without tastudio too?

**Comment by ShinobiWannabe** [comment]
Not sure will take a look at it later today.

**Comment by ShinobiWannabe** [comment]
It looks like the original works properly when you don't have tas studio open.

**Comment by vadosnaprimer** [comment]
So was this fixed?

**Comment by ShinobiWannabe** [comment]
I could not fix this completely upon further testing it seems to not be getting the expected values from memory.  When I would be testing for 0 it would sometimes say say the result is 0 even when it is clearly not.  Not sure how to fix that.  Sorry.

**Comment by vadosnaprimer** [comment]
Is it a visible mismatch between values, like it tells one value for that frame and ram watch tells another? If so, they they must be getting values from different sources that don't align.

**Comment by alyosha-tas** [comment]
I made a commit attempting to resolve this, anyone interested in basic bot please test dev build.

There were numerous issues. Liberal use of 'new' left stale references, input was not synced at loadstate causing ghost inputs that appeared in the playback but not in the log, numerous off-by-one errors.

There is still an unresolved issue, basic bot can command U+D and L+R and those inputs go to the log, but if the option is not checked in the controller menu, the inputs do not go to the core, so a desync between reported value and playback can still result, I don't know what to do about that part.
