### ISSUE TITLE
Journey Escape (Atari 2600) graphical glitches

### ISSUE THREAD

**Issue by Arcorann** [TASVideos/BizHawk#1614]
During gameplay the background doesn't render properly, instead of a starfield vertical lines appear on the screen (see image):

<img width="80" alt="Journey - Escape (1982) (Data Age)  ! 2019-07-14 00 32 19" src="https://user-images.githubusercontent.com/13177041/61172909-e7a97800-a5ce-11e9-8176-0357809f0a55.png">

As seen in the below image, BizHawk version 2.3.0 renders the background correctly, making this a regression.

<img width="80" alt="Journey - Escape (1982) (Data Age)  ! 2019-07-14 00 33 36" src="https://user-images.githubusercontent.com/13177041/61172917-09a2fa80-a5cf-11e9-9396-59c35f7d198c.png">

**Comment by alyosha-tas** [comment]
I just made a commit. Please test the Dev Build. Also thanks for reporting this, everything in A2600 needs to be just right to work.

**Comment by Arcorann** [comment]
Dev build with the new commit tested, issue is still present.

**Comment by Glitcholog** [comment]
Can confirm Arcorann's statement, game was fine and broke in dev
