### ISSUE TITLE
Pixels are not square at any resolution other than 256x224

### ISSUE THREAD

**Issue by GigaOtomia** [TASVideos/BizHawk#1618]
![image](https://user-images.githubusercontent.com/32317465/61349113-f68f6500-a830-11e9-8e36-b68677d104cc.png)
This is how the gameplay window should look at all multiples of this resolution.

![image](https://user-images.githubusercontent.com/32317465/61349151-19217e00-a831-11e9-8101-a6a75ba646a2.png)
However, the window gets squashed vertically at any other.

![image](https://user-images.githubusercontent.com/32317465/61349199-41a97800-a831-11e9-90d3-48de4c268b4c.png)
As proof, here's 256x225, exactly one pixel taller than native. Though graphical accuracy isn't this emulator's aim, I would personally prefer to have it at resolutions other than 1x native, considering it's clearly possible.

**Comment by zeromus** [comment]
config > display > scaling and filtering > use 1:1 pixel size.
I know, 1x and 2x don't mean what they say they do.
