### ISSUE TITLE
firmware scan and organize broken

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1621]
atari 7800 ntsc rom not detected in 2.3.2

Organize function no longer renaming and moving? only renaming?

maybe more?

**Comment by YoshiRulz** [comment]
...Can you be more specific?

**Comment by jjfmz42015** [comment]
atari 7800 ntsc rom not detected 

in 2.3.2 

Organize function no longer renaming and moving? only renaming?

**Comment by YoshiRulz** [comment]
Reproducible on Win10 1709 (2.3.2 on left, 2.3.1 on right):
![firmware info dialog comparison](https://i.imgur.com/3cYWxQZ.png)

I couldn't tell you why it's hashing the file differently.

**Comment by alyosha-tas** [comment]
Known bug, fixed in the dev build . Not sure exactly what you are doing so I’ll wait to close this.

**Comment by jjfmz42015** [comment]
latest dev build also has a break now it double the 7800 ntsc entry

**Comment by alyosha-tas** [comment]
fixed
