### ISSUE TITLE
System.IndexOutOfRangeException: Trying to play a Snes Game and I get an Atari2600 error

### ISSUE THREAD

**Issue by Joshi234** [TASVideos/BizHawk#1625]
I got this error when I try to play snes games:
```
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei BizHawk.Emulation.Cores.Atari.Atari2600.mCV.ReadMemory(UInt16 addr)
   bei BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.ReadMemory(UInt16 addr)
   bei BizHawk.Emulation.Cores.Components.M6502.MOS6502X`1.FetchPCLVector()
   bei BizHawk.Emulation.Cores.Components.M6502.MOS6502X`1.ExecuteOneRetry()
   bei BizHawk.Emulation.Cores.Components.M6502.MOS6502X`1.ExecuteOne()
   bei BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.Cycle()
   bei BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.FrameAdvance(IController controller, Boolean render, Boolean rendersound)
   bei BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   bei BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Its really weird because it is a usual snes game(Super Mario World.smc)

edit: formatting --yoshi

**Comment by YoshiRulz** [comment]
Please download [this dev build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/26400094/artifacts) and try loading the game with it.

**Comment by adelikat** [comment]
Which game were you playing?

**Comment by YoshiRulz** [comment]
I can't think of why Atari2600Hawk would be chosen to load an `.smc` unless the start of the file was corrupted. The little info you've provided isn't enough to tell us what happened, so I'm closing this issue. @Joshi234 Feel free to comment with more info, or [join IRC](https://github.com/TASVideos/BizHawk#support-and-troubleshooting) to chat.
