### ISSUE TITLE
Choosing AVI writer crashes the emulator

### ISSUE THREAD

**Issue by samuraisnake86** [TASVideos/BizHawk#1629]
Everytime I try to record a segment of a game by clicking record and config, then choosing AVI writer, the emulator crashes.

**Comment by zeromus** [comment]
you have a buggy codec. uninstall them until you figure out which one is buggy

**Comment by Spikestuff** [comment]
Actually out of curiosity. What system are you attempting to dump?

**Comment by EZGames69** [comment]
Ive been having this problem for awhile and could never figure out what was causing it.

I believe it might be because my codec was 32 bit rather than 64 bit, so doing it on 2.0 bizhawk would always crash the emulator, but doing it on 1.0 would be fine.  

Have you tried dumping on 1.0 bizhawk?

**Comment by zeromus** [comment]
32bit codecs don't exist in the 64bit universe. That isn't the problem. Your problem was a codec whose 64bit version was buggy but whose 32bit version wasn't.

**Comment by samuraisnake86** [comment]
I had a buggy codec. Problem solved
