### ISSUE TITLE
Dump subframe length into movies properly

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#1631]
SubNESHawk requires vblank count to be dumped into movie header to allow accurate real-time length calculation (edit: [relevant code](https://github.com/TASVideos/BizHawk/blob/74d20ca45cd7d4c19c979e68e60d019b28637fb9/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs#L169-L173) --yoshi). GBHawk requires cycle count to be dumped (is gambatte also involved?).

It's trivial to dump those when one stops movie recording while being at its last frame. But for tastudio, you're not always on the last movie frame when you export bk2. So when we export bk2 from tastudio for these 2 (or 3) cores, there should be a check if we're on the last movie frame, suggesting to emulate to there if we're not. "If you don't emulate to the last movie frame, X count will be incorrect. Seek there?", and then if we hit Yes it does the thing and then exports the bk2.

Need feedback from @adelikat and @Masterjun3.

**Comment by vadosnaprimer** [comment]
Ugh.

**Comment by alyosha-tas** [comment]
GBHawk no longer requires cycle count to be dumped.
Gambatte does require it though.

**Comment by vadosnaprimer** [comment]
Why?

**Comment by vadosnaprimer** [comment]
> GBHawk no longer requires cycle count to be dumped.
Why?

**Comment by alyosha-tas** [comment]
Because GBHawk now runs at a constant rate, so normal frame timing is correct. You can see this in the pokemon crystal resync for example:
http://tasvideos.org/userfiles/info/58555860013787500

**Comment by vadosnaprimer** [comment]
Which commit made gbhawk frames equal length?

**Comment by Masterjun3** [comment]
> Which commit made gbhawk frames equal length?

https://github.com/TASVideos/BizHawk/commit/2c575dd91ac06872d8df6cd6ff9a6ba3d793cd00 or more specifically https://github.com/TASVideos/BizHawk/commit/2c575dd91ac06872d8df6cd6ff9a6ba3d793cd00#diff-5f118945855cd90893feb9f7abc421e7L81-R81 .
