### ISSUE TITLE
Kirby Tilt 'n' Tumble issues

### ISSUE THREAD

**Issue by Sun-in-jang** [TASVideos/BizHawk#1634]
1) "load error" message on Gambatte core, impossible to load game. On GBHawk working.

Kirby Tilt 'n' Tumble (USA)
SHA1:6AB8D666E2BEBBB3FEE7796C8968AAB2EA21B8F9
MD5:F2E24776D93082362C9B435ABC167D89

2) Implement option to map four directional keys to emulate the cartridge tilting (VBA) or using mouse for that (BGB). This is only suggestion, not sure if this possible implement

**Comment by alyosha-tas** [comment]
1. adding this mapper to gambatte is impractical, but maybe it can be made to auto load into gbhawk like with quicknes.

2. you can access mouse controls in GBHawk as follows:

- Load the game into GBHawk.
- in the menues go to GB -> settings -> sync settings ->Controller -> tilt
- Reboot the core
- bind analog controls to mouse by going to config -> controllers -> analog controls

**Comment by Sun-in-jang** [comment]
I was mean that in BGB you simple move mouse and kirby controls without problem, while in GBHawk something like delay, or mouse controlling is hard

**Comment by alyosha-tas** [comment]
You can try increasing the sensitivity and decreasing the deadzone to get more response from smaller movements, these options are in the same analog controls menu.

**Comment by Sun-in-jang** [comment]
Video with issue - https://youtu.be/b6CBSrDcTnA sensitivity was 190% and -190%, deadzone - 5%

**Comment by alyosha-tas** [comment]
video is unavailable.

Tilt X should be mouse X
Tilt Y should be mouse Y (might need to invert this one I can't remember.)

**Comment by Sun-in-jang** [comment]
Video is fixed, i will also try to change Tilx X and Y

**Comment by Sun-in-jang** [comment]
Just tested both Tilt X and Y, still the same problem, even if set sensitivity to 200% and deadzone 0%

**Comment by alyosha-tas** [comment]
can you make a video with input display on? (view -> display input)
Also make sure you are holding the mouse in the center of the window during the time the game tells you to hold the game flat.

**Comment by Sun-in-jang** [comment]
[2019-08-15-2059-58.zip](https://github.com/TASVideos/BizHawk/files/3506643/2019-08-15-2059-58.zip)

**Comment by alyosha-tas** [comment]
The second video looks correct to me.

It looks like maybe what you want is to turn down the sensitivity. maybe try deadzone = 0 and sensitivity = 75%

**Comment by Sun-in-jang** [comment]
Tested deadzone 0 and sensitivity on 75%, looks not enough smooth...

[2019-08-16-1744-55.zip](https://github.com/TASVideos/BizHawk/files/3510058/2019-08-16-1744-55.zip)

**Comment by alyosha-tas** [comment]
It looks like you want to flip y axis, you can do this in analog controls by clicking 'Flip Axis'

**Comment by Sun-in-jang** [comment]
Trying to make if you move mouse to left - kirby moves left, right - right. Same for up & down.

**Comment by alyosha-tas** [comment]
left and right is controlled by P1 tilt X, which should be bound to mouse X

up and down is controlled by P1 tilt Y, which should be tied to mouse Y.
If kirby is not moving correctly up and down, then click the 'Flip Axis' button under P1 tilt Y.

Otherwise just lower your sensitivity until you find settings that are comfortable for you, maybe 50%?

i can't test this myself at the moment so this is the best i can do, just experiment.

**Comment by Sun-in-jang** [comment]
On 50% for tilt Y and X there some troubles with making Kirby jump

**Comment by alyosha-tas** [comment]
Closing this as it will not be added to gambatte and seems to work fine in GBHawk
