### ISSUE TITLE
GBHawk: Litti's Summer Sports freezes/crashes

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1635]
Litti's Summer Sports keeps crashing/freezing at the beginning of the first weightlifting event.
[Litti's Summer Sports (Germany).GBHawk.QuickSave0.zip](https://github.com/TASVideos/BizHawk/files/3500623/Litti.s.Summer.Sports.Germany.GBHawk.QuickSave0.zip)

**Comment by Spikestuff** [comment]
Just as a question, did you attempt _Track Meet_ or the Japan Title _Track Meet: Mezase! Barcelona_ to see if they crashed as well?

**Comment by Reinc01** [comment]
They do not crash.

**Comment by alyosha-tas** [comment]
Clsoing and adding to #1227 
Also probably needs re-testing might already be fixed
