### ISSUE TITLE
[3 errors] BizHawk tries to save as every minute | BizHawk is slow 24/7

### ISSUE THREAD

**Issue by iiDk-the-actual** [TASVideos/BizHawk#1637]
Every single time I'm trying to create a TAS BizHawk decides to save as without my permission.
And whenever I create a tas or do anything, BizHawk is being a potato.
AAAND whenever I emulate N64, the frames switch from green to red every frame.

Screenshot:
![n64 bizhawk problem](https://user-images.githubusercontent.com/54154105/63121034-8c71f900-bf71-11e9-80b0-eba5d937714b.PNG)

**Comment by vadosnaprimer** [comment]
1. Config - Autosave - Set autosave interval - Set 0.
2. It's not a bug it's a feature.
3. It's how N64 works.

**Comment by iiDk-the-actual** [comment]
@vadosnaprimer How do I disable it from saving every 60 seconds?

**Comment by vadosnaprimer** [comment]
Try reading.

**Comment by iiDk-the-actual** [comment]
@vadosnaprimer I didn't ask for you to close this but you fixed my problem.
I just still need to figure out how to not let it be a potato, as I don't want it to lag when I'm putting it on tasvideos.
