### ISSUE TITLE
[BizHawk Error] Whenever I do anything on BizHawk, it slows down without my permission.

### ISSUE THREAD

**Issue by iiDk-the-actual** [TASVideos/BizHawk#1638]
(I don't want that one person saying that it's a feature again.)
Whenever I try to do anything on BizHawk, it lags on fricking frame 0.
The speed is set to 100% still, it just seems like it's set to 50%.
How do I fix this?
Video; https://youtu.be/dsseYppWMCE

DON'T CLOSE WITHOUT MY PERMISSION.

**Comment by zeromus** [comment]
tastudio slows down systems. it's working really hard to take savestates constantly and draw with windows cruddy drawing. you're not supposed to game with it, youre supposed to spend months slowly working on a tas

![mypermission](https://user-images.githubusercontent.com/102701/63122895-c8a75880-bf75-11e9-9629-0943ef385a12.png)

**Comment by iiDk-the-actual** [comment]
> tastudio slows down systems. it's working really hard to take savestates constantly and draw with windows cruddy drawing. you're not supposed to game with it, youre supposed to spend months slowly working on a tas
> 
> Per your request, I've attached your permission when closing this thread
> ![mypermission](https://user-images.githubusercontent.com/102701/63122895-c8a75880-bf75-11e9-9629-0943ef385a12.png)

oh my god i'm moving this subreddit again if i don't gen an answer. i want to record this to tasvideos

**Comment by YoshiRulz** [comment]
Duplicated as and resolved in #1639. Also we don't have a subreddit.
