### ISSUE TITLE
[BizHawk Error] Whenever I do anything on BizHawk, it slows down without my permission. (#1638 repost because an idiot closed it)

### ISSUE THREAD

**Issue by iiDk-the-actual** [TASVideos/BizHawk#1639]
(I don't want that one person saying that it's a feature again.)
Whenever I try to do anything on BizHawk, it lags on the fricking frame 0.
The speed is set to 100% still, it just seems like it's set to 50%.
How do I fix this?
Video; https://youtu.be/dsseYppWMCE

DON'T CLOSE WITHOUT iiDk-the-actual's PERMISSION.

I want to record this to TASVIDEOS without it being a potato

**Comment by Spikestuff** [comment]
You have follow cursor enabled. Disable that, Report back. Don't insult the devs.
(Not a dev here, but the person you did is.)

**Comment by iiDk-the-actual** [comment]
@Spikestuff I didn't know that, I'm sorry to who I insulted.

**Comment by iiDk-the-actual** [comment]
:(

**Comment by iiDk-the-actual** [comment]
also thanks
