### ISSUE TITLE
[Linux] no gba/gbc roms open

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#1640]
I did go under cores and selected the ones supposedly marked as working, but they still fail to load.

Error message: [https://photos.app.goo.gl/QuDSaHPNnVBdgjp69](url)

**Comment by InfamousKnight** [comment]
nevermind. Got it to work!

**Comment by YoshiRulz** [comment]
...How? They don't work in master.

**Comment by InfamousKnight** [comment]
I'm not sure... Somehow it just started working. Frame advance works from
what I tested.
