### ISSUE TITLE
Astal (JAP) graphics glitch cerulean final boss

### ISSUE THREAD

**Issue by ciccio576** [TASVideos/BizHawk#1654]
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 07 (1)](https://user-images.githubusercontent.com/54777500/64080623-bc9df380-ccf6-11e9-929b-c3acd6aeedde.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 08 (0)](https://user-images.githubusercontent.com/54777500/64080624-bc9df380-ccf6-11e9-8c7d-3b27424c292a.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 08 (1)](https://user-images.githubusercontent.com/54777500/64080625-bc9df380-ccf6-11e9-9c1c-e0ab1b548948.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 02](https://user-images.githubusercontent.com/54777500/64080626-bd368a00-ccf6-11e9-9664-d7c65d46d120.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 04](https://user-images.githubusercontent.com/54777500/64080627-bd368a00-ccf6-11e9-9939-69492919d039.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 05 (0)](https://user-images.githubusercontent.com/54777500/64080628-bd368a00-ccf6-11e9-848e-0c1bf39d36df.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 05 (1)](https://user-images.githubusercontent.com/54777500/64080629-bd368a00-ccf6-11e9-971e-f697e145dea0.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 06 (0)](https://user-images.githubusercontent.com/54777500/64080630-bdcf2080-ccf6-11e9-986d-0ef894835669.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 06 (1)](https://user-images.githubusercontent.com/54777500/64080633-be67b700-ccf6-11e9-9678-a8b28ef5febd.png)
![Astal - Kisuisyoudensetu Asutaru (JAP) (DW0446) 2019-09-01 20 22 07 (0)](https://user-images.githubusercontent.com/54777500/64080634-bf004d80-ccf6-11e9-8793-7667ef5fd1cb.png)

**Comment by Spikestuff** [comment]
Can you check upstream, this is most likely due to the fact that the core hasn't been updated in 2+ years (#1232).

**Comment by nattthebear** [comment]
Please retest on latest Bizhawk ( 2.5.x)

**Comment by nattthebear** [comment]
Reopen if this problem persists on BizHawk 2.5.3
