### ISSUE TITLE
tastudio.setplayback() function pauses mysteriously on N64 (possible race condition?)

### ISSUE THREAD

**Issue by nlburgin** [TASVideos/BizHawk#1656]
Theoretically I'd expect that `tastudio.setplayback()` would be faster than an emu.frameadvance() loop because it turbos through without displaying the frames onscreen. 

However, as of 2.3.2, on the Mupen64plus core (but apparently not necessarily on other cores, for example I tested with Gambatte and there was no such issue) it sometimes randomly enters a paused state when `tastudio.setplayback()` is called from within a loop.

This is best demonstrated with a simple test-case:

```lua
while true do
    tastudio.setplayback(2524); --substitute whatever frame you want for 2524
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
end
```

A simple infinite loop that should run forever. However, it randomly pauses after "a while". 

It doesn't seem to be deterministic at all, which is strange. The number of times it runs before stopping can vary a lot, and I can't pin down any specific thing that sets it off. Super weird.

For science, I also tried it without any frame-advances at all:

```lua
while true do
    tastudio.setplayback(2524);
    emu.yield();
end
```
And it behaved the same way: randomly pausing after a variable number of iterations.

however if I try doing something very stupid:

```lua
while true do
    tastudio.setplayback(2524);
end
```
_That_ does seem to hang the client indefinitely with no end in sight. So it seems our mysterious pause can only happen while the GUI is interactible, never when it's unresponsive?

Yet it's happened even when I left the mouse cursor sitting still and not overlapping any of Bizhawk's windows, so it doesn't seem to be an actual response to input.

After messing with it for a while I discovered something strange: **doing I/O can prevent the pause?** My nose isn't too well trained, but I think this smells like a weird race condition.

if you add a print statement to the emu.yield example, the bug vanishes:

```lua
while true do
    tastudio.setplayback(2524);
    print("why does this fix it?")
    emu.yield();
end
```

However, this fix doesn't seem to work reliably for `emu.frameadvance()` The only 100% reliable workaround in that case is to run a separate, simultaneous helper script that looks like this:

```lua
while true do
    client.unpause();
    emu.yield();
end
```
Which is clearly not ideal.

**Note:** To be very thorough, I even tested with both "NLua+KopiLua" and the alternate "LuaInterface" configuration, to see if that would make any difference. Best I can tell, it made no difference at all.

**Comment by nlburgin** [comment]
On further inspection, this behavior doesn't seem to be 100% consistent? 

It's not happening now, so now I have no idea what was going wrong earlier.

**Comment by nlburgin** [comment]
Now it seems like it's randomly pausing occasionally, but other times it continues??

**Comment by nlburgin** [comment]
It seems like it only happens if the TAStudio window is scrolled to where the destination frame is. 

If it's displaying a completely different area and the cursor isn't onscreen, then the bug doesn't manifest.

**Comment by nlburgin** [comment]
To get away from the more complex script I'd been testing, I prepared a very simple test case:

```lua
while true do
    tastudio.setplayback(2524); --substitute whatever frame you want for 2524
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
end
```

A simple infinite loop that should run forever. However, it randomly stops after "a while". 

It doesn't seem to be deterministic, which is strange.

Note that I've only tested on N64 and don't know if this happens on other cores.

**Comment by vadosnaprimer** [comment]
`emu.frameadvance();` doesn't force the emulator to advance a frame, it just tells the emulator "you can advance it now if you want", and then the client decides, based on user behavior. To force it to go to a new frame, unpause the emu, and if the framecount has changed, pause again.

**Comment by nlburgin** [comment]
>and then the client decides, based on user behavior. 

The problem is, this seems entirely uncorrelated to user behavior.

Like I mentioned in my previous comment, an infinite loop involving `tastudio.setplayback()`, regardless of if it uses `emu.frameadvance()` or `emu.yield()` to give control back to the client, will end up paused after a non-deterministic number of iterations, _with no user interaction_.

>To force it to go to a new frame, unpause the emu, and if the framecount has changed, pause again.

That doesn't help a lua script, because once it randomly decides to pause, the next statement( for example, `client.unpause()`) isn't going to be executed. As I mentioned, only a second script running at the same time, which uses an infinite `emu.yield()` loop to unpause at every possible opportunity, can work around the issue.

**Comment by nlburgin** [comment]
Okay, here's something interesting: **doing I/O can prevent the pause?** My nose isn't too well trained, but I think this smells like a weird race condition.

As I mentioned earlier both of these loops will randomly pause after a while.

```lua
while true do
    tastudio.setplayback(2524);
    emu.yield();
end

while true do
    tastudio.setplayback(2524); --substitute whatever frame you want for 2524
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
end
```

However, if you add a print statement to the emu.yield example, the bug vanishes

```lua
while true do
    tastudio.setplayback(2524); --substitute whatever frame you want for 2524
    print("why does this fix it?")
    emu.yield();
end
```

However, this fix doesn't seem to work reliably for `emu.frameadvance()`

I find it surprising to find an (apparent) timing issue in BizHawk since it seems to be very single-threaded by design. However I was poking around in the issues and I did see #690, which mentioned that sometimes multiple threads are needed to work around issues with "ported" cores, does mupen64plus have any weird multithreaded stuff like that going on?

Now I feel like I need to test if this issue also manifests in a "native" core like GBHawk.

**Comment by nlburgin** [comment]
The bug is completely absent on GBHawk.

**Comment by nlburgin** [comment]
Should I close this bug report and re-submit a cleaned up version that's easier to read? I admittedly seem to have made a huge mess here.

**Comment by YoshiRulz** [comment]
Just edit the first post and delete your comments.

**Comment by nlburgin** [comment]
Done. And if it somehow ends up being actually needed, my previous word vomit is preserved [here](https://web.archive.org/web/20190903025404/https://github.com/TASVideos/BizHawk/issues/1656) for posterity :stuck_out_tongue_closed_eyes:

**Comment by adelikat** [comment]
The basics of a lua script is to do emu.frameadvance() in a loop

while true do
    emu.frameadvance()
end

To do the expected behavior of navigating to a particular frame, simply add tastudio.setplayback(1234)

while true do
   tastudio.setplayback(1234)
    emu.frameadvance()
end

frameadvance isn't used to actually advance a frame, rather yield control to the emulator until the next frame.

emu.yield() is for special cases when you want to only yield control until the next "paint" event essentially, for finer interactivity from lua script (ones with a UI, or accept keyboard input)

**Comment by YoshiRulz** [comment]
But can anyone reproduce the pausing after `tastudio.setplayback` on a dev build? That's what this issue is actually about, the inconsistency between the Lua API and TAStudio.
