### ISSUE TITLE
GBHawk crash with TAStudio and lua

### ISSUE THREAD

**Issue by nlburgin** [TASVideos/BizHawk#1657]
While testing for #1656, I wanted to see if the problem I was having was exclusive to N64, so I decided to test with another core, and Game Boy happened to be the most convenient.

While Gambatte behaved normally (not exhibiting the behavior described in #1656, nor anything else out of the ordinary), with GBHawk the same test actually resulted in *crashing the emulator* with 

"Fatal error: IndexOutOfRangeException".

The game used was Tetris and the script used was

```lua
while true do
    tastudio.setplayback(2524);
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
    emu.frameadvance();
end
```

The test was performed by opening TAStudio, inserting 3000 empty frames, and then running the script. It successfully seeked to 2524 and then paused; unpausing at that point caused the crash.

EDIT: This was Bizhawk 2.3.2

**Comment by alyosha-tas** [comment]
It was trying to read 0 samples for some reason. not sure why exactly, but it's fixed now.
