### ISSUE TITLE
For N64, EEPROM and controller pak saves are exposed as memory domains, but not SRAM and FlashRAM saves.

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#1660]
Judging by this code here, all of them exist as simple buffers within the mupen core, so should be fairly simple to wire them up:
https://github.com/TASVideos/BizHawk/blob/7ff08fb63e4f96cb55ba4c481d59c2dc0a6fbde9/libmupen64plus/mupen64plus-core/src/memory/pif.c#L613-L627

**Comment by vadosnaprimer** [comment]
> [18:30:51] <MrCheeze__> I'd consider just making the contribution myself, but I know I'd spend 10 times as long on getting the build working to verify as on making the actual change..

Building m64p is easy, just use the right MSVC version and update the deps submodule. You don't even have to build the entire solution, only the core itself.

**Comment by MrCheeze** [comment]
^ hey, you were right.
