### ISSUE TITLE
GlideN64 rendering broken after latest DLL update on master (4.0)

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#1662]
@vadosnaprimer Shows up either entirely black or with extremely broken rendering such as below on all games. Copypasting an old gliden DLL from a stable build fixes the rendering.

![image](https://user-images.githubusercontent.com/6541413/64504202-6f90c300-d29c-11e9-8272-f3971d012d5e.png)

**Comment by MrCheeze** [comment]
Issue still present on 2.4 (and has been since 2.3.1). Does it not happen on all machines? Anything in particular about my setup I can give that would help narrow down the issue? Just using integrated graphics here.

**Comment by YoshiRulz** [comment]
Integrated graphics (Intel, I assume) is a good sign that it's a driver issue. The newer GlideN64 could be relying on some OpenGL trickery that isn't well supported by the proprietary ones—see #1820.

**Comment by vadosnaprimer** [comment]
I tried merging newer GlideN but it somehow resulted in some new problems we didn't have before. Either it's my GPU, or some incompatibility between our outdated-as-shit m64p and GlideN. I don't really expect it to be getting better anymore.

**Comment by vadosnaprimer** [comment]
Test latest master https://ci.appveyor.com/api/buildjobs/q2ljwvqdlagif065/artifacts/BizHawk_Developer-2020-02-04-072710-%238ff2ca2cd19d3280a45ab498c72f5d99785adc1d.zip

**Comment by MrCheeze** [comment]
Thanks for looking into it! Unfortunately, behaviour is identical to before.

**Comment by vadosnaprimer** [comment]
Core rot then.

**Comment by vadosnaprimer** [comment]
Main issue should be https://github.com/TASVideos/BizHawk/issues/1718
