### ISSUE TITLE
[NESHawk] Dendy-mode broken since 2.3.1 release (Vblank issue)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/BizHawk#1665]
Dendy-mode broken since 2.3.1 release in NESHawk core.
(NES -> Advanced settings -> Region override: Dendy)

Examples:
1. "Bucky O'Hare (U)" have graphical artifacts during intro movie, then hangs.
2. "Ninja Gaiden III Ancient Ship of Doom (U)" hangs similar to Bucky O'Hare.
3. "Alien 3 (U)" hangs during intro.
4. "Totally Rad (U)" skips first part of level 1 and gameplay start after second movie.
5. "Choujin Sentai Jetman (J)" issues. 
Start on any area and you'll see graphical artifacts and no-enemies on stage.
Sometimes game automatically reset, sometimes crashes.

Also Choujin Sentai Jetman's intro MUST HAVE this glitch on dendy-mode:
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Choujin%20Sentai%20Jetman.gif
caused by 50 extra scanlines in postrender. It confirmed on real hardware and other emulators.
This glitch was emulated perfectly in HESHawk 2.3.0, but hangs keeping black screen since 2.3.1

Mesen emulator had similar issues with these games a some years ago, and it was fixed.
Sour wrote:
> Hey,
> NMI was being triggered at scanline 291, but the vertical blank flag was being set at scanline 241 (like on NTSC/PAL machines), which was causing all of the issues you found.
> I've fixed the flag's timing and now everything seems to be working correctly (including the bug in Jetman's intro)
> Thanks a lot for testing!

Tech info:
https://wiki.nesdev.com/w/index.php/Cycle_reference_chart
http://wiki.nesdev.com/w/index.php/CPU#CPU_signals_and_frequencies
https://wiki.nesdev.com/w/index.php/Detect_TV_system
https://wiki.breaknes.com/_media/wiki:2652378.png

**Comment by alyosha-tas** [comment]
Oops, yeah I forgot about Dendy mode on the last update, please check now, should be fixed.

**Comment by eugene-s-nesdev** [comment]
Root of the problem was:
https://github.com/TASVideos/BizHawk/commit/69fe1bdf97207250fdc36c01475dd3cef46dc9a0

**Comment by eugene-s-nesdev** [comment]
Okay, i've compiled https://github.com/TASVideos/BizHawk/commit/0bd3553c27a2671358ca9b82cc6b0da6bd912343
At first look all those bugs are fixed, will test more
Thank You

**Comment by eugene-s-nesdev** [comment]
Strange but this game hangs on green screen at startup, noting related to lastest commit, it happens on 2.3.0 and earlier too. 
IIRC it works on Mesen/puNES/nintendulator and other emulators with dendy-mode support
[Aladdin_(Pirate).zip](https://github.com/TASVideos/BizHawk/files/3612974/Aladdin_.Pirate.zip)

**Comment by alyosha-tas** [comment]
I'll add it to the other open issue, thanks for the report.

**Comment by eugene-s-nesdev** [comment]
Some of recent bizhawk core-related commits fixes Aladdin, StarWars and BoatDuel, it works on 2.6.3-dev
I guess one of them:
https://github.com/TASVideos/BizHawk/commit/28ff96deb52c64bbda8e7d57acd36fcae324f6b4
https://github.com/TASVideos/BizHawk/commit/76c76a8775e12dbd2e6a6b595589c989927c93e7

https://forums.nesdev.com/viewtopic.php?f=2&p=275074#p274887
