### ISSUE TITLE
Incorrect symbol "&" on Bizhawk title bar

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/BizHawk#1667]
If romname contains `&` symbol and not recognized by internal database, like this:
"Battletoads & Double Dragon - The Ultimate Team (U) [t1].nes"
then `&` turns to `&amp;` on the title bar

![name_issue](https://user-images.githubusercontent.com/13199529/64845824-cd623980-d613-11e9-9e20-4a2d30c97596.png)

**Comment by YoshiRulz** [comment]
It's read as XML:
https://github.com/TASVideos/BizHawk/blob/7fb80514263a13266188bdeace2f608c20f40675/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.BoardSystem.cs#L645

**Comment by jdpurcell** [comment]
@eugene-s-nesdev Which version of BizHawk? I cannot reproduce this on 2.3.2 or the latest dev build.

**Comment by YoshiRulz** [comment]
It only affects the BootGod DB.

**Comment by sornerol** [comment]
I was able to reproduce the issue. I'm going to take a look at fixing it later this evening.
