### ISSUE TITLE
[Gambatte] Some addresses are displayed wrong on ram watch

### ISSUE THREAD

**Issue by gnaomo** [TASVideos/BizHawk#1672]
I was trying to read from addresses 0xFF18 and 0xFF19 with a lua script while playing a gb game (these are registers used to control square 2 sound channel http://gbdev.gg8.se/wiki/articles/Gameboy_sound_hardware) but their displayed values is not correct (e.g. FF or BF), these addresses should change instead, tried to RAM Watch the addresses to see if lua was the problem, but the result is the same. These addresses are displayed correctly using VBA instead
Here's a video, pay attention to the ram watch of Bizhawk and VBA: https://streamable.com/e4r2r

(The case is the same for addresses 0xFF13,0xFF14 and 0xFF1D)

**Comment by alyosha-tas** [comment]
This is not a bug. Certain audio registers cannot be read from. (Reference the 'Register Reading' section in your link.) VBA is returning values that are either just incorrect, or expecting that you want to know the actual register data and just returning that to you instead.

Your best option here is to track writes to those addresses instead using event.onmemorywrite
