### ISSUE TITLE
Bizhawk button press issue

### ISSUE THREAD

**Issue by joshe179** [TASVideos/BizHawk#1674]
On the NOGBA emulator when I hold in the "A" button, it only presses A one time, on bizhawk, if I hold it in, it continues pressing A rapidly. 

Can anyone PLEASE help me make my button presses single press only? I LOVE the emulator, I just cannot deal with it accidentally choosing moves I didn't want.

**Comment by nlburgin** [comment]
Check your button mappings, you're probably using the 'turbo A' button instead of just the 'A button'.

**Comment by joshe179** [comment]
> Check your button mappings; you've probably been using the 'turbo A' button instead of just the 'A' button.

Turns out I had autofire controls setup, as the normal controls were all controller buttons so I assumed I couldn't use those.

I FIXED IT FINALLY.
