### ISSUE TITLE
Desync issues with mgba for lego star wars ii

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#1679]
To reproduce the desync, make it the first level and try to kill the storm troopers without getting killed yourself.

Run into the first room on the left where the minikit is, replay the movie, and something will go wrong.

If that doesnt reproduce it, get the first mini kit and exit and then jump.

**Comment by Spikestuff** [comment]
https://github.com/TASVideos/BizHawk/pull/1307

**Comment by InfamousKnight** [comment]
Desync issue has been fixed in latest commit! Thanks guys!
