### ISSUE TITLE
Can not run Bizhawk: [FAIL] Visual C++ 2012 Runtime

### ISSUE THREAD

**Issue by Devilwasbad** [TASVideos/BizHawk#1681]
I can not get Bizhawk to run the error im getting is

[FAIL] Visual C++ 2012 Runtime

I have tried uninstalling Visual Studio 2012 and reinstalling it through Microsofts own program and the "bizhawk_prereqs" program and neither have worked and produced the same issue. Any help would be much appreciated.

Image of issue

https://i.imgur.com/YWzxlit.png

The output of the "bizhawk_prereqs" program

https://pastebin.com/25aSMXgC

**Comment by zirathashe** [comment]
im also having this issue.

**Comment by adelikat** [comment]
@zeromus @YoshiRulz we recently updated bizhawk to no longer depend on VC 2012, can this ticket be closed?

**Comment by zeromus** [comment]
let's do it

**Comment by RMMaxX** [comment]
> @zeromus @YoshiRulz we recently updated bizhawk to no longer depend on VC 2012, can this ticket be closed?
Is that version out yet ?

**Comment by YoshiRulz** [comment]
It was 60b7858fb so no, but 11.0/2012 was never a dependency in the first place. The error OP got is actually shown when MSVC 12.0/2013 is missing. If you're still seeing this error, try manually uninstalling all versions of the MSVC redistributable thingo, and then running [the installer](https://github.com/TASVideos/BizHawk-Prereqs/releases/tag/2.1) again.

**Comment by RMMaxX** [comment]
O thanks

**Comment by earthboundmisfits** [comment]
Ive tried the above and still getting same problem, yes i have the latest bizhawk 2.4 any other options ?

**Comment by earthboundmisfits** [comment]
all sorted now thanks :)

**Comment by zeromus** [comment]
@earthboundmisfits can you please write HOW you sorted it?

**Comment by earthboundmisfits** [comment]
Sorry all sorted by uninstalling everything and installing older version of bizhawk and older version of prerequisites.
