### ISSUE TITLE
Watch duplication does not refreshes the counter.

### ISSUE THREAD

**Issue by dart193** [TASVideos/BizHawk#1684]
If you duplicate a watch in RAM Watch window, the counter for how many watches are there is not actually updated. Example: you create one new watch. The counter shows 1 now. Then you duplicate this watch (with a new address, so that it is actually created), creating another watch. The counter still says 1 watch. You can keep duplicating watches, but the counter never refreshes. Creating new watches does refresh, but not duplicating.

**Comment by adelikat** [comment]
Fixed
