### ISSUE TITLE
Cannot fast forward.

### ISSUE THREAD

**Issue by FAKE1007** [TASVideos/BizHawk#1685]
Hello, I have encountered a problem. I am using RTCV5.0.2 and I cannot fast-forward/turbo. My hotkeys are set to default(except for pause). Pressing the FF/Turbo keys just seem to lower the volume of the game but nothing else. I am playing a GB game and this doesn't work on both cores, but that doesn't depend on the game itself, because on GBC it also doesn't work. Modifying speed in the context menu doesn't work either and I have no other settings that may affect fast forward, and I only can slow the game down. Rewinding still works.

**Comment by YoshiRulz** [comment]
Is [this](https://github.com/ircluzar/RTCV) the RTCV you're referring to? Please report the issue there unless you can reproduce it on the latest BizHawk release (2.3.2) from this repo.

**Comment by FAKE1007** [comment]
You were right, I'll just go back to rtc354 right now, it works there

**Comment by nlburgin** [comment]
@FAKE1007 In addition to just going back to the working version, you probably *should* still report this to the RTC devs. If they broke something accidentally, they'd probably like to know about it.

**Comment by omuncolo** [comment]
i have the same problem and i don't find any solutions around.

**Comment by YoshiRulz** [comment]
@omuncolo Were you using RTC Vanguard? If not, can you open a new Issue with details about your PC?
