### ISSUE TITLE
bSNES core accuracy mode selection support 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#169]
```
Some games have graphics issues - for example Cosmo Police Galivan II, see GIF.

Those issues are fixed by the accuracy profile - which is currently not 
supported in Bizhawk.

Grouchtart approved this message!
Mmmmm tart!
```

Original issue reported on code.google.com by `longpl...@longplays.org` on 3 May 2014 at 10:11

Attachments:
- [CPG.gif](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-169/comment-0/CPG.gif)

**Comment by hegyak** [comment]
This has been added, mostly.
