### ISSUE TITLE
Support adjusting the default configuration for unidentified ROM's

### ISSUE THREAD

**Issue by Nicholas-Steel** [TASVideos/BizHawk#1691]
It would be great if we could easily adjust the default game configuration that the program uses when loading up a ROM that isn't in any internal game database.

For example I might be using a bunch of ROM files that were modified and they all require the N64 Expansion Pak to work correctly. I would like to be able to change the default configuration to include the N64 Expansion Pak so that I don't need to make this change one-by-one to each and every ROM.

Request applies to all gaming platforms handled by Bizhawk.

**Comment by YoshiRulz** [comment]
Use `gamedb_user.txt`. See also #733.

**Comment by Nicholas-Steel** [comment]
Ah, in my case the ROM's are likely to be discarded once completed. For example: Zelda: Ocarina of Time Randomizer, Zelda: Majora's Mask Randomizer etc. produce ROM's that you're likely to discard after completing them, because you'll be generating a newly randomized copy for a new experience the next time.
