### ISSUE TITLE
[BSNES] allow region to be changed

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1692]
I know that it’s unlikely that TASVideos will allow PAL games to be played on NTSC frequencies, however there is one game where it was ment to be that way.

The homebrew rerelease “Nightmare Busters” has a special cartridge that allows players to play the game on both NTSC and PAL systems.  I am not sure if it’s as simple as just making the game run 10 frames faster or if the rom itself has a separate NTSC mode in it.  The website for the game: https://www.nightmarebusters.com claims to be both NTSC and PAL compatible.

The problem is if I load the game into bizhawk, it will only play the game in PAL mode.  The only other option I’d have to make it play at 60fps is to modify the rom itself, which staff is definitely not going to approve of.

Is there anything that can be done about this?  Or should this game just be TASed using PAL?

**Comment by zeromus** [comment]
we need more information on the special cartridge. you may interest a forum full of snes hackers.

**Comment by EZGames69** [comment]
The only thing I can point to is this article which says the cartridge fits in any region console: 

https://www.wired.com/2014/01/nightmare-busters/

And unfortunately the game has been sold out for awhile, so anyone wanting to buy it will have to wait.

**Comment by zeromus** [comment]
I think it's most likely it's just a built-in physical adapter and it doesnt affect the game in any way, which means it's going to result in a too-fast game on the NTSC snes. If the game runs differently in an NTSC snes, it's no big deal, it's the same as any other PAL game adapted to run in an NTSC snes. TASers dont do that, else we'd already have that option. You need to regard this as a PAL game, full stop.
