### ISSUE TITLE
Request: A Hotkey to Disable All Cheats

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#1694]
Hey guys.

Right now there's a hotkey to toggle cheats, but all that does is it _disables the cheats that are On, and it enables the cheats that were Off_.  It's a nice hotkey if you have all of your cheats On at the same time, but that's not always the case.

So, I would like to request an additional hotkey to Disable/Turn Off all the cheats that are ON and leaving the ones that are off alone. And then when the key is pressed again, it would turn back on those same cheats.

Thanks!

**Comment by alyosha-tas** [comment]
I added a disable all cheats hotkey (Ctrl + Backspace)

The other part of your request already exists in #553 , so I'll close this and leave that one open.
