### ISSUE TITLE
[Vboy] Change the Sync Setting to a Non-Sync Setting.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#1695]
Wow, we're getting an issue track for Virtual Boy.
No it's not a core update... _even though it does need that too probably_.

DisableParallax should not be a sync setting requirement.
![image](https://user-images.githubusercontent.com/12412764/66719167-db37f400-ee37-11e9-8717-2b55092298f7.png)
![image](https://user-images.githubusercontent.com/12412764/66719172-e5f28900-ee37-11e9-8add-f9a92d372522.png)

![image](https://user-images.githubusercontent.com/12412764/66719205-847eea00-ee38-11e9-8031-04533d62932c.png)
(Top is right, Bottom is wrong in regards to dumping.)

This doesn't affect sync at all whether disabled or enabled.
This is a setting which is created mainly for the TASer/runner to not deal with the 3D mode that is the Virtual Boy and have a single screen, it's fine and all but wrong for final dumping on an encoders end.
This should not be a thing forced, that we have to go into the SyncSettings file and adjust in, and then get replaced when it is actually used.

This should be a straightforward fix, but the core's waterbox, so have an issue tracker about it.

**Comment by Cyorter** [comment]
Why not also something like... force all http://tasvideos.org/EncodingGuide/VideoDumping.html settings when encoding, for example, for a PSX encoding, force the use of Hardcore Debug Mode, or enable Sprite Limit on PCE. In case its forgotten to change before encoding.

**Comment by nattthebear** [comment]
> This doesn't affect sync at all whether disabled or enabled.

Citation needed

**Comment by nattthebear** [comment]
Never mind that.  It's specifically called out by the mednafen authors as a sync affecting setting: [tha docs](https://mednafen.github.io/documentation/vb.html).  Closing ticket as moronic.

**Comment by Spikestuff** [comment]
> 
> 
> > This doesn't affect sync at all whether disabled or enabled.
> 
> Citation needed

http://tasvideos.org/4052M.html

Reopen it or remove the feature, this is your fault and don't call this moronic when you can't be bothered fixing something.

**Comment by Cyorter** [comment]
DisableParallax affects savestates only, not movies

**Comment by Spikestuff** [comment]
Thank you @Cyorter for putting that in.

Actually, while we're here what you're proclaiming would mean **doing the reverse would desync right**?
Well. If that's the case.

Here are 3 of the currently published VBoy TASes that have the feature disabled, switched to enabled.
These all pause on final frame, these are all correct.

[Nester's Funky Bowling](http://tasvideos.org/3615M.html)
![image](https://user-images.githubusercontent.com/12412764/68261794-54241780-0095-11ea-9319-ede6a7b16c19.png)

[Teleroboxer](http://tasvideos.org/3619M.html)
![image](https://user-images.githubusercontent.com/12412764/68261888-92b9d200-0095-11ea-9b2f-e88ab3b7c25f.png)
Because it's a black screen I'll show you the credits sequence which is a few frames later:
![Teleroboxer (Japan, USA) 2019-11-06 13 03 06](https://user-images.githubusercontent.com/12412764/68262046-2ab7bb80-0096-11ea-935b-fb02bf6e8c91.png)

[Waterworld](http://tasvideos.org/3699M.html) - Game loops at end of 16.
![image](https://user-images.githubusercontent.com/12412764/68261833-6ef68c00-0095-11ea-84fd-3b7fc1c9d4b8.png)

And before you even think about it, [here's the zipped file of it](https://github.com/TASVideos/BizHawk/files/3812167/DisableParallax.-.Enabled.zip) so you can test yourself.

That's a case of 4/4 TASes where there opposite is done to it.
Reopen this tracker.

**Comment by YoshiRulz** [comment]
If it only affects save *states* and not SaveRAM then it doesn't need to be sync'd. From a cursory look at the source code it seems the value is only read during rendering.

**Comment by nattthebear** [comment]
Again, the Mednafen authors, who are the ones that wrote this core and know how it works, specifically call out that setting as one that can affect sync.

> Caution: Any settings that change emulation behavior as seen from the emulated game are shown with the setting name bolded in the table. One should be conscious of these settings if one has changed them from the default values when using network play or movies, as they can cause desychronizations if not set the same among hosts(or between the recording emulator and the playing emulator). 

So no, we won't be moving sync settings that are actually sync settings to the non sync settings category.

**Comment by zeromus** [comment]
clarification from mednafen dev: games can read the framebuffer, and this setting affects what gets written in the framebuffer; so games can read this setting.
@Spikestuff your analytical process is poor. It pains me to have to explain this, when you could self-service by gaining life experience or studying logic, so I will just point out that based on the explanation from the dev, we could construct a trivial test program which would desync.

**Comment by Spikestuff** [comment]
Then I have a suggestion. Remove the feature or do something specific (like you've done to snes9x) cause this isn't something that shouldn't be available for a TAS.

@zeromus I'm fine with the analytical process being poor. What's more annoying is that he up and asked for "citation needed" we have four TASes that don't desync after switching the sync setting and as @Cyorter mentioned this apparently is only affected during TASing.
Do you have an extreme case from the mednafen dev where it should affect the framebuffer so we can actually test it with?

**Comment by nattthebear** [comment]
> What's more annoying is that he up and asked for "citation needed" we have four TASes that don't desync after switching the sync setting

It's not even that "4 games worked" isn't enough evidence, as alluded to by @zeromus, it's not even the right way to approach the problem.

> Remove the feature

Remove a feature entirely because it doesn't help your one use case?  I don't think so.  Bizhawk provides a lot of different things for a lot of different users.

**Comment by Spikestuff** [comment]
@nattthebear if you're going to do selective reading then do a better job at it.
> or do something specific (like you've done to snes9x)

Also keep in mind, I'm also using the factor of the consumer who wouldn't be using BizHawk for TASing as this is both a casual and a TASing emulator where it allowed snes9x and asked for a switch to BSNES.

As well as:
> Do you have an extreme case from the mednafen dev where it should affect the framebuffer so we can actually test it with?

**Comment by EZGames69** [comment]
If spike was able to dump the tas with the setting changed, and didn’t cause desyncs, I’m pretty sure that means it isn’t the sync settings.

Also so what if the mednafen devs say it is a sync setting, have you tested it yourself?

**Comment by vadosnaprimer** [comment]
When I made "savestate every frame" optional for the bsnes core, I tested how much faster it got and how much desync it introduced. It was reflected in the option description:

![RDywz7E](https://user-images.githubusercontent.com/7092625/68995634-f5367d80-08a0-11ea-89dd-180d7be66983.png)

Even if a sync setting only cases 1% of desyncs among all games, it's still a sync setting because it affects sync. If you test 99% of games and conclude it doesn't, and make it free to change on the fly, you may introduce unfixable desyncs that require the movie to be redone. Maybe you want unfixable desyncs in your TAS every time you lose in a lottery, but that's not what a TASing emulator is supposed to offer.
