### ISSUE TITLE
[Bug] Cheat Saving Issues (converts to hex, doesn't convert back correctly)

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#1696]
When you add a cheat (unsigned or signed), if you save it, it will automatically change the value to hex (you have to click on an empty spot after doing that to see the changed value).

And if you try to change it back to unsigned/signed, instead of converting the value from hex to the original value, it instead truncates the number. For example, if you had the unsigned value 224, and you saved it, it will change the value to "E0", but if you select unsigned again, it either sets the value to zero or it truncates it to "24" or something.

**Comment by alyosha-tas** [comment]
```
// Set to hex for saving 
							cheat.SetType(DisplayType.Hex);
```
line 387 of cheatlist.cs

So it's setting it to hex on purpose, Maybe it should just be changed back afterwards. I'll look into it.

**Comment by alyosha-tas** [comment]
Here is what I could do:

saving won't change the value displayed anymore.
Using the 'display as' button now works correctly.

Still wrong:
Cheats still save as hex so when you load them they will be hex (but at least you can change them)
Signed stuff is generally not correct (with what is displayed at least.) Probably the siged option should be removed from cheats unless a lot of effort is put into handling it better.

**Comment by ReyVGM** [comment]
Thanks. Personally, I never use Signed. Only Unsigned because it shows the value as it appears in the game, so it's easier for me to recognize what I'm looking for.
