### ISSUE TITLE
Cheat converter won't open in Dev Build

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1697]
I'm pretty sure line 766 in ToolManager.cs should be:

`var sysName = Global.Emulator.SystemId;`

instead of the current:

`var sysName = Global.Emulator.DisplayName();`

@YoshiRulz can you confirm the intent here?

**Comment by YoshiRulz** [comment]
That's a typo, it should be `attr.SupportedSystems.Contains(Global.Emulator.SystemId)` and `attr.UnsupportedCores.Contains(Global.Emulator.DisplayName())`.
