### ISSUE TITLE
bsnes startup RAM state

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#1701]
bsnes uses "randomized" startup RAM state in hawk, with the seed of 0, and this barely has any relation to how consoles work. When "randomizer" is disabled, the startup state gets closer to console and similar to lsnes's default.

http://tasvideos.org/forum/viewtopic.php?p=488318#488318

"Randomizer" should be made optional. Changing the seed moves it farther away from console behavior, so that option isn't required. Alternatively we could poke RAM upon startup and set whatever pattern we need.

**Comment by YoshiRulz** [comment]
see also #1285 re: sgb

**Comment by jjfmz42015** [comment]
Turning this off will break ai in super offroad

**Comment by vadosnaprimer** [comment]
Define "break".

**Comment by jjfmz42015** [comment]
Super Offroad when played on real hardware, Mesen-S or bsnes load ai defaults into random memory page.


when played on snes9x due to disable randimizxation ai doesnt load random therfore making the game too easy to play. this is well known enough that there is a rough patch that helps a little on rom hacks.

emulators with randomization ie bsnes & mesen-s allow ai to function as the programmer of super offroad intended.


disabling randomization will break this game 100%.


for a test play with bsnes core and snes9x core.


randomization off attract mode is no longer random
power ups during game play end up falling in static locations rather than random.
cpu driver patterns no longer random.

**Comment by vadosnaprimer** [comment]
0x55 fill is known to exist on some consoles. 00FF is another pattern that actually exists. Then some consoles mix those up in complicated ways, and some bits get hardly predictable states as shown on the pic I linked. Maybe that game's developers didn't try enough of different consoles and it looked proper to them, but that doesn't mean hawk's default state has anything to do with accuracy.

**Comment by jjfmz42015** [comment]
all i know is all fpga, clones, emulators without randomization break this. bsnes,mesen-s and real hardware get it right due to randomization.

my knowlage unfortunitly end here. im sure somone like qwertymodo or byuu or sourmesen can shed light on the topic.

**Comment by zeromus** [comment]
There is no right or wrong. Only different wrongs. If super offroad depends on undefined behavior then there's no right, only less wrong (more or less acceptably chaotic behavior). Look at the tasvideos thread for other concepts of what's more or less wrong.

Try to choose a minimal set of options, and give the user the option of which wrong to choose. Any choice that's less wrong for one case will be more wrong for others.

**Comment by jjfmz42015** [comment]
Well considering real hardware is this way, 100% compatible builds of bsnes are this way and the unbelievably compatible alpha of mesen-s is this way without breaking anything I don't see how it can be wrong at all. Remember the version of bsnes here which may have issues is a less compatible ancient build.

**Comment by zeromus** [comment]
Real hardware isn't this way. Compatibility doesn't determine reality. Every emulator is in a state of dynamic compromise between reality and practicality. Your gods are mortal men.

**Comment by jjfmz42015** [comment]
So on real hardware Ram is not randomly accessed on power up? A static address is called? 

I guess I'm misinformed. 

I don't know enough to say more unfortunately.

I was initially trying to be helpful.

**Comment by zeromus** [comment]
Did you read the link in the OP you're replying to? Does it look random to you?

**Comment by vadosnaprimer** [comment]
I forgot to link this too:
http://tasvideos.org/Nach/MemoryInit.html

**Comment by Arcorann** [comment]
A description of Super Off Road's usage of uninitialised RAM for its random number generator (which as mentioned affects the AI of CPU cars as well as placement of bonus items) can be found [here](https://www.romhacking.net/forum/index.php?topic=25789.msg352028#msg352028) - note the comment that 55 55 55 55 is considered to be a poor starting state for the RNG, and that the problem of poor starting states happens on real hardware, but only occasionally.

**Comment by nattthebear** [comment]
So, there aren't any broken games, and there isn't any console validated TAS that's failing.  Not really anything that requires action here.

**Comment by jjfmz42015** [comment]
No it just breaks ai in super off road and therfore makes it not playable as intended. I see clearly thats not the goal of this emulator. This fully breaks this game. Luckily i only use bizhawk for mega drive.

**Comment by nattthebear** [comment]
We didn't change anything, and you said it worked in your first post

**Comment by jjfmz42015** [comment]
In my first post i pointed out it kills the ai.

Mesen-s, bsnes plus, bsnes and higan current builds all emulate this game anyway

**Comment by nattthebear** [comment]
You said

>Turning this off will break ai in super offroad

We did not "turn this off", therefore we did not break the ai in super offroad.

**Comment by jjfmz42015** [comment]
Omg, my bad, its a long day, today ignore me please. Not a great day and clearly my brain is showing this sorry.

I should of went back to re read, forgot and was thinking backwards. 

Sorry

**Comment by vadosnaprimer** [comment]
I never said it was a bug. It's a feature request.

**Comment by nattthebear** [comment]
@vadosnaprimer fuck off
