### ISSUE TITLE
[Virtual Pad] Multi-Disk isn't supported for Saturn games

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#1703]
**_Update:_** Came to my attention that being able to switch disks is possible in TAStudio. I changed the title accordingly.

---

So, the Sega Saturn has games that require disk changing.
It doesn't exist when doing Multi-disk Bundler.

Tools > Multi-disk Bundler
System: SAT

![image](https://user-images.githubusercontent.com/12412764/67479411-b9493780-f6a9-11e9-9621-1417fa566cde.png)

PlayStation for reference:
![image](https://user-images.githubusercontent.com/12412764/67479427-c23a0900-f6a9-11e9-92e8-3dae2ee44253.png)

**Comment by Asnivor** [comment]
Huh, i've never seen that UI option before.

Saturnus has controller bindings wired up to change disks by the looks of it:

https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Emulation.Cores/Consoles/Sega/Saturn/Saturnus.cs#L149

**Comment by nattthebear** [comment]
The text of the issue is about the multi-disk bundler.  The screenshots are from the virtual pad???
???

**Comment by adelikat** [comment]
VirtualPad is not the defactor place but it is an important place.  If saturn can do multi-disk, we need to add support in virtualpad as well as the multi-disk bundler
