### ISSUE TITLE
Very lag movie loading in Windows 10

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1709]
Hi there a bug in Windows 10 that make movie loading box lag very slow and make the emu crash is you try do something also the memory usuage get crazy high
![IMG_20191030_003315](https://user-images.githubusercontent.com/42782548/67968730-49253f00-fbde-11e9-894e-7a692a21b94c.jpg)

**Comment by YoshiRulz** [comment]
What kind of movie are you loading? Also Windows comes with this cool thing called the Snipping Tool, you should try it.

**Comment by DarkLegend1987** [comment]
Example im complete a normal TAS in Windows 10 and click play movie and the box lag about 10 minutes and the memory show like the pic im have 8gb ddr4 dual channel hypernix  im have old bizhawk 1.13.12 in low end machine win 7 click play movie and the box show fast 10 seconds

**Comment by zeromus** [comment]
How big is your "normal tas" and please attach or link it. Since you wrote what version of bizhawk works, you seem to know what "version numbers" are, so you should be able to tell us the version number of bizhawk youre having problems with (and if possible the exact URL)

**Comment by YoshiRulz** [comment]
I meant what file extension the TAS movie is. And yes, please link to TASVideos if you got it from there.

**Comment by DarkLegend1987** [comment]
For my old win7 desktop im use the 1.13.2 because is a low end pc for the lastest versión im use Alienware 15r2 and Windows 10 but in the lastest there a massive lag for trading movies a difference of the old win7 pc that read movie quick the  role extention is any because im play TAS Challenge with Friends and summit to community and non summit vídeos im used to post in a streaming like YouTube and mixer

**Comment by zeromus** [comment]
You didn't answer any of our questions.

**Comment by DarkLegend1987** [comment]
Sorry im noticed this bug is only present in 2.3.2 im check the 2.3.1 and the movie load fine this must be the 2.3.2 have some memory leaks the next update check movie load pop up quickly

**Comment by YoshiRulz** [comment]
@DarkLegend1987 I'm closing this because none of us can get EmuHawk to slow down with movie playback. If this still happens to you on BizHawk 2.4, please comment with a link to the movie. You could also attach it with drag-and-drop.

For the record, your run-on sentences take a long time to read. You can always use Google Translate if you're not comfortable with English. It's quite good, especially with Spanish.
