### ISSUE TITLE
Zone of the Enders - The Fist of Mars (Europe) (En,Fr,De) graphics purple glitch on model(core: mGBA)

### ISSUE THREAD

**Issue by ciccio576** [TASVideos/BizHawk#1710]
![Zone of the Enders - The Fist of Mars (Europe) (En,Fr,De) 2019-11-01 21 27 56](https://user-images.githubusercontent.com/54777500/68054510-b922ea80-fcee-11e9-992d-ba7e54622dc9.png)
![Zone of the Enders - The Fist of Mars (Europe) (En,Fr,De) 2019-11-01 21 27 42](https://user-images.githubusercontent.com/54777500/68054513-b922ea80-fcee-11e9-8b58-58b26f376260.png)

**Comment by Spikestuff** [comment]
Is this fine on upstream 0.7.2?
If it isn't. Is this fixed on 0.7.3?

**Comment by ciccio576** [comment]
that problem manifests itself with the core 0.7.2 in 0.7.3 instead it is ok no glitch

**Comment by ciccio576** [comment]
that problem manifests itself with the core 0.7.2, externally trying on emulator mgba version 0.7.3 has no glitch

**Comment by endrift** [comment]
This has been fixed for a while and can be closed.
