### ISSUE TITLE
N64VideoPluginconfig - Disabled RSP dropdown causes NullReferenceException

### ISSUE THREAD

**Issue by Gorialis** [TASVideos/BizHawk#1711]
`N64VideoPluginconfig.SaveSettings()` checks the currently selected RSP type from the RSP dropdown to commit to settings:

https://github.com/TASVideos/BizHawk/blob/0405eb7c7301fe420dfe7dd7581cdcb4bf02fb42/BizHawk.Client.EmuHawk/config/N64/N64VideoPluginconfig.cs#L502-L504

However, in 46568bf1ecb5e8c63f27fa7e7f99630773aaedcb, the RSP dropdown was disabled as CXD4 was removed:

https://github.com/TASVideos/BizHawk/blob/46568bf1ecb5e8c63f27fa7e7f99630773aaedcb/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64.cs#L115-L124
https://github.com/TASVideos/BizHawk/blob/46568bf1ecb5e8c63f27fa7e7f99630773aaedcb/BizHawk.Client.EmuHawk/config/N64/N64VideoPluginconfig.Designer.cs#L492

`SaveSettings` still checks for this dropdown, and it has no default, so pressing Save on the N64 plugin config form causes a NullReferenceException that crashes the emulator (`RspTypeDropdown.SelectedItem` is null):

![image](https://user-images.githubusercontent.com/8049998/68071761-0f605e00-fdc1-11e9-8ca5-38dbf2fbbc4e.png)

**Comment by YoshiRulz** [comment]
This is only possible if it's loaded from config, in all other cases it's `0` (= `RspType.Rsp_Hle`). Did you copy `config.ini` from a previous version which had the other option?

**Comment by Gorialis** [comment]
Ah, this is probably from me moving my git HEAD around too much. I'll try clearing my config out.

**Comment by Gorialis** [comment]
Yep, this is the result of a stale config.
