### ISSUE TITLE
FFmpegWriter.CloseFileSegment throws NullReferenceException (cascading error)

### ISSUE THREAD

**Issue by Gorialis** [TASVideos/BizHawk#1714]
When using [File] > [AVI/WAV] > [Config and Record AVI/WAV], selecting the FFmpeg writer and any video format, upon pressing 'Save' when choosing a filename, an exception is thrown (`System.NullReferenceException: Object reference not set to an instance of an object`, `_muxer is null`):

![image](https://user-images.githubusercontent.com/8049998/68085229-08e5eb00-fe82-11e9-8547-fdc8d36620fc.png)
https://github.com/TASVideos/BizHawk/blob/64e8270cab2352a2f28aebacfc070502ee2b3173/BizHawk.Client.EmuHawk/AVOut/FFmpegWriter.cs#L136-L139

This exception occurs in the call stack from `aw.Dispose();` in `MainForm.RecordAvBase`:
https://github.com/TASVideos/BizHawk/blob/64e8270cab2352a2f28aebacfc070502ee2b3173/BizHawk.Client.EmuHawk/MainForm.cs#L3187-L3192

Breakpointing here shows the exception this block is catching is `System.InvalidOperationException: StandardIn has not been redirected`.

I traced this back to this reference of StandardInput in `FFmpegWriter.OpenFileSegment`:
https://github.com/TASVideos/BizHawk/blob/64e8270cab2352a2f28aebacfc070502ee2b3173/BizHawk.Client.EmuHawk/AVOut/FFmpegWriter.cs#L114

The declaration of `_ffmpeg` marks that it does not write to stdout, and does write to stderr, but does not pass anything about stdin:

https://github.com/TASVideos/BizHawk/blob/64e8270cab2352a2f28aebacfc070502ee2b3173/BizHawk.Client.EmuHawk/AVOut/FFmpegWriter.cs#L88-L95

And indeed, `OSTailoredCode.ConstructSubshell` does not actually even accept an argument for this:

https://github.com/TASVideos/BizHawk/blob/64e8270cab2352a2f28aebacfc070502ee2b3173/BizHawk.Common/OSTailoredCode.cs#L118-L133

Patching the StartInfo for this to explicitly redirect stdin fixes the bug for me, and AV capture works perfectly:
```csharp
StartInfo = new ProcessStartInfo {
    Arguments = args,
    CreateNoWindow = true,
    FileName = cmd,
    RedirectStandardError = checkStderr,
    RedirectStandardOutput = checkStdout,
    RedirectStandardInput = true,
    UseShellExecute = false
}
```

For the actual codebase though, the correct way of dealing with this is probably to add a `writeStdin` or such param to ConstructSubshell, and to mark it `true` when `_ffmpeg` is defined.

**Comment by YoshiRulz** [comment]
`UseShellExecute` is hardcoded to `false`, so we might as well hardcode `RedirectStandardInput` to `true` (they're mutually exclusive).
