### ISSUE TITLE
[Linux] cant open any rom

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#1717]
I tried setting core to neshawk and tried loading a rom, and it claimed it was missing its dll. I tried vbanext and tried loading a gba game like stuntman and that failed too saying its dll was missing too. 

I guess its not pointing to the right dll folder?

**Comment by YoshiRulz** [comment]
Could not reproduce either on 8c059aa43. Try deleting your `config.ini`.

(also please report issues in #1430 for the time being)

**Comment by InfamousKnight** [comment]
I tried deleting the config.ini, and still the same result.

Here's a photo of the error when I try loading gbc with gbhawk: [https://photos.app.goo.gl/1myo7Djstv4pQdDA7](url)

**Comment by YoshiRulz** [comment]
Oh I can fix that. Your link is backwards, here's a [Markdown cheatsheet](https://guides.github.com/features/mastering-markdown/).

**Comment by InfamousKnight** [comment]
I fixed the link. Thanks for the sheet.
