### ISSUE TITLE
Latest AppVeyor build filename odd?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1719]
So the latest appVeyor Build 0.0.3348 (master 7548abf6 is showing a weird name for the artifact

BizHawk_Developer-2019-10-26-184313-#7548abf66c9ada422486fc1b0f8f17dfa8c53c31

2019-10-26????

Just thought Ide mention in case its important.

This makes it seem older than previous builds.

**Comment by YoshiRulz** [comment]
That particular commit isn't on master, it's from a PR. The date is correct because I've since force-pushed the branch.

I don't think there's a way to filter out PRs from the AppVeyor page, but if there is, the readme needs to point there instead.

**Comment by jjfmz42015** [comment]
Thanks for taking the time to explain.
