### ISSUE TITLE
Sms hawk joypad bug

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1720]
Hi im found an issue in sms hawk the joypad combinación UP+Right Down+right
Up+left Down+Left dont work rastan game for máster system sms need up+right to jump but this dont work

**Comment by YoshiRulz** [comment]
Have you tried with the Virtual Pad? There might be something wrong with your keybinds.

**Comment by DarkLegend1987** [comment]
Yeah the bug is present in old 32bit versión 1.13.2 im check the 2.3.2 and its fixed
