### ISSUE TITLE
Update SNES9x Core to latest master? Lots of updates

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1722]
Update SNES9x Core to latest master? Lots of updates since what is in bizhawk.

Please? :)

**Comment by YoshiRulz** [comment]
Duplicate of #1374 (which you opened).

**Comment by jjfmz42015** [comment]
sorry forgot I opened that.

I just thought ide ask in case it was easy.


I can use BSNES.
