### ISSUE TITLE
problem with importing PSXjin movies (and PCSX movies)

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1723]
So I’m not sure if this is fixable but when I attempt to import a movie from PSXjin into bizhawk, the input file ends up like this:

https://cdn.discordapp.com/attachments/280808167993245707/590548205595394048/unknown.png

Why does this happen and is there a way around it?

as a side note, if you try to import a PCSX movie it will work, except the inputs dont press the correct buttons.

**Comment by vadosnaprimer** [comment]
Link the movie file you're trying so we're on the same page.

**Comment by EZGames69** [comment]
im very confused, now when I try to import movies they work just fine

**Comment by EZGames69** [comment]
ok so it's not the same but the importing is still incorrect, instead of showing inputs it's just this: 
(https://user-images.githubusercontent.com/44628443/68415793-23111900-0161-11ea-8142-3932cced1a42.png

the movie I imported was http://tasvideos.org/2541M.html

[what the fuck.zip](https://github.com/TASVideos/BizHawk/files/3821118/what.the.fuck.zip)

**Comment by Spikestuff** [comment]
For sake of sanity checking I did [Crash 1 just now](http://tasvideos.org/2391M.html).
[pirohiko-crashbandicoot.zip](https://github.com/TASVideos/BizHawk/files/3822241/pirohiko-crashbandicoot.zip)

Reason for the sanity check is that there are some SotN TASes that fumble around in the input opening.

**Comment by vadosnaprimer** [comment]
Test on dev.

**Comment by vadosnaprimer** [comment]
@EZGames69

**Comment by Spikestuff** [comment]
Using [Tekken 3](http://tasvideos.org/2869M.html) it results in the same result as that Crash 1 run listed above.

Using 2 PCSX-RR movies, [Crash 2](http://tasvideos.org/1506M.html) and [Tekken 3](http://tasvideos.org/2701M.html) they're both fine.

Crash 2 by pirohiko, entering the second level inputs:
![image](https://user-images.githubusercontent.com/12412764/69512438-1f222b00-0f98-11ea-850c-acd896df413d.png)

Since the Tekken 3 TAS uses a memory card it did prompt the error of it not being supported yet.
![image](https://user-images.githubusercontent.com/12412764/69512359-df5b4380-0f97-11ea-8327-5f905bd6b01b.png)

**Comment by EZGames69** [comment]
Sorry for not responding.

So yeah I did test them in the dev build but I still got the same result as the image I posted above.  I was testing this: http://tasvideos.org/2541M.html

interestingly, if I were to change controller set up and memory cards, the process crashes (but maybe I shouldnt be doing that anyway)

now when I test it with this: http://tasvideos.org/1246M.html, it works as intended now, instead of just pressing the wrong buttons.

**Comment by EZGames69** [comment]
here's the resulting movie for the PSXjin one, which failed: [forgonemoose-castlevaniasotn.pjm.zip](https://github.com/TASVideos/BizHawk/files/3887595/forgonemoose-castlevaniasotn.pjm.zip)


andhere is the resulting movie for the PCXS one, which worked: [castlevaniasotn-zggzdydp.pxm.bk2.zip](https://github.com/TASVideos/BizHawk/files/3887590/castlevaniasotn-zggzdydp.pxm.bk2.zip)
