### ISSUE TITLE
NES Palette

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#1724]
I made a palette, then add a string to that pal file's last, and it can be used in most NES emulators like VirtuaNES, FCEUX, Nestopia, etc... but can't be used in BizHawk, it throws an error when loading [this palette](http://www.mediafire.com/file/8kedaugaw9fmfl4/HeleReality.pal) .

**Comment by alyosha-tas** [comment]
BizHawk only recognizes specific size files for palettes. For your palette to work you have to delete the string at the end that says 'made by yave yu'
