### ISSUE TITLE
Compile Error on Linux (Filename casing)

### ISSUE THREAD

**Issue by pmprog** [TASVideos/BizHawk#1727]
Filenames are case-sensitive on most Linux filesystems. In:
https://github.com/TASVideos/BizHawk/tree/master/BizHawk.Client.Common/movie/import

Files PJMImport.cs and PXMImport.cs don't match what the compiler is looking for (PjmImport.cs and PxmImport.cs)

**Comment by YoshiRulz** [comment]
@adelikat Is there a way to make this a build warning?
