### ISSUE TITLE
Bizhawk closes right after chosing rom

### ISSUE THREAD

**Issue by Linkkun** [TASVideos/BizHawk#1728]
Hello everyone.

I downloaded the patched rom file for Ocarina of Time, I want to play with my friends the Ocarina of Time Randomizer Multiworld, I only changed some settings, the ones that don't require a rom loaded.
I am exactly here: https://wiki.ootrandomizer.com/index.php?title=Multiworld#Bizhawk_Settings 
When I try to complete the remaining settings, I need to load the rom, but when I load, the emulator closes.

Any answer?

**Comment by YoshiRulz** [comment]
Check that the unpatched rom loads, if so report in [TestRunnerSRL/OoT-Randomizer](https://github.com/TestRunnerSRL/OoT-Randomizer/issues).

**Comment by Linkkun** [comment]
I found a solution, I changed the video plugin, it works well for me, but for my friends is too laggy, this emulator is really bad :c
All of them can play other options like Project 64, so the issue is the emulator.
Anyway, if I can run the Ocarina Randomizer Multiworld, I suppose we can play it in here.
By the way, have you ever tried? I can't forward the ports, so we will try Hamachi, do you reccommend it?

**Comment by YoshiRulz** [comment]
I have a consumer router so IDK. If you fixed it can I close this issue? Any further problems should be directed at the above repo.

**Comment by Linkkun** [comment]
You can, but I still have some questions, should I post them in another thread?
Look, the Hamachi works very well, we could play, but the plugins are really bad, do you know some setting we can try so the emulator could run a little better?

**Comment by YoshiRulz** [comment]
Update your graphics card's drivers. Set `Config` > `Display...` > `Display Method` to OpenGL. Turn off each of `Config` > `Rewind & Saves...` > `Rewind Frequency`.
