### ISSUE TITLE
[FEATURE REQUEST] code data logger window refresh rate

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1729]
I noticed, after updates to some dialog boxes with lists like RAM search/watch code data logger statistics, etc, they updated the lists much more infrequent. at least for Code Data Logger I badly rely on immediate list update while logging and debugging a game. Hex Editor for example updated just fine for me. Previously only TURBO button had disable the updates at all but this is acceptable.

Now I'd like to request in any way an option to enable real time update for Code Data Logger window instead of current lazy update. and yes, I don't care about FPS here, they may drop I don't care since this is not important in my work.

**Comment by adelikat** [comment]
It isn't intended that they refresh any less often than they did before.  I'll look into it.
