### ISSUE TITLE
Specifying "System Bus" as the domain for memory.read... with N64 emulator returns wrong value

### ISSUE THREAD

**Issue by aliblong** [TASVideos/BizHawk#1734]
input: 
```lua
memory.read_u32_be(0x801CA1D8, "System Bus")
```

expected output, confirmed by RAM watch: `8`

actual output, versions 2.3.0 and 2.3.2: `1008369664`

**Comment by vadosnaprimer** [comment]
RAM watch won't catch mid-frame  values, only those on "frame boundaries" (think vblank, after the entire frame has been emulated).

**Comment by YoshiRulz** [comment]
The `memory` library (and `mainmemory`) cannot read from or write to addresses over `0x7FFFFFFF` because the address parameter is a 32-bit signed integer. Your call is interpreted as `memory.read_u32_be(-2145607208, "System Bus")`.

**Comment by zeromus** [comment]
it's a bug. we should be doing all those parameters as long. except where lua is directly involved and making things hard for having only doubles, any bug due to using int for address should be fixed. we could leave that one open as a reminder of it
