### ISSUE TITLE
SMSHAWK sega sg-1000 H.E.R.O (Japan) CRC32 4587DE6E garbage at bottom of screen

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1737]
SMSHAWK sega sg-1000 H.E.R.O (Japan) CRC32 4587DE6E garbage at bottom of screen

**Comment by jjfmz42015** [comment]
allow switching core to genesis plus gx would work

**Comment by jjfmz42015** [comment]
nevermind, tried switching to that core and black screen

**Comment by EZGames69** [comment]
Can you screenshot what the bottom looks like?  Also do we know how it looks on a SMS?

**Comment by jjfmz42015** [comment]
will do later. bottom quarter of screen should be black on real hardware, smsplus kega, on bizhawk orange garbage

**Comment by jjfmz42015** [comment]
proper on hardware or kega or sms plus or mednafen

![proper](https://user-images.githubusercontent.com/18354277/69053362-421c7000-09d7-11ea-8ed1-88e3893ea3b3.PNG)

**Comment by jjfmz42015** [comment]
Bizhawk

![bizhawk](https://user-images.githubusercontent.com/18354277/69053408-5b252100-09d7-11ea-9ac7-a69e9351369b.PNG)

**Comment by jjfmz42015** [comment]
hmm just noticed, enable display overscan fixes this but yeailds a smaller picture vs real hardware and other emulators with overscan not being display

**Comment by jjfmz42015** [comment]
OK so enabling display overscan and setting display to 4:3 made this look like real hardware.


Im going to consider it just settings and close this.



sorry guys.
