### ISSUE TITLE
Install from bizhawk_prereqs locking visuals to GZDoom (OpenGL)

### ISSUE THREAD

**Issue by MogWaltz** [TASVideos/BizHawk#1742]
Hello! A friend of mine decided he'd just go ahead and get DeSmuME (Nintendo DS emulator) running on my laptop without asking first by running bizhawk_prereqs.exe. Yes, the Emulator works now, but I play a lot more GZDoom (which uses OpenGL) and have been experiencing graphical freezes since the install. The game seems to run just fine, until it doesn't. Gameplay continues, but the screen is stuck on the last visual it processed (i.e. sounds from the game are running just fine), forcing me to save&quit (provided I'm not surrounded by demons at the time). The only thing that had been added/updated on the laptop is bizhawk_prereqs. I already checked for updates on drivers, Windows, & GZDoom, and they're all fine. Not really sure where to go from here, especially since I don't know what changes bizhawk_prereqs made to the system.
Windows 10, 8GB RAM, 2.4GHz Intel i3-7100U CPU (not sure what else you'd need)

**Comment by YoshiRulz** [comment]
The readme lists the prerequisites: .NET Framework 4.6.1; Visual C++ Redistributable 2015; Visual C++ redist 2012; Visual C++ redist 2010 SP1; and Direct3D 9. Look for those in `Settings` > `Apps` > `Apps and Features`.

**Comment by MogWaltz** [comment]
It has to be Direct3D 9, and not 12? Already have everything else.

**Comment by YoshiRulz** [comment]
EmuHawk needs version >= 9 to use it as a display method, other programs using OpenGL don't need it at all. You could try uninstalling it and everything else in that list (plus the Visual C++ redist 2013 which is installed but not needed) until your game works again. The only other suggestion I have is that you look elsewhere as this is the issue tracker for BizHawk.
