### ISSUE TITLE
[RAM Search] Can not open context menu for multiple selection

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1746]
EDIT: This bug affects the master branch. Version 2.3.2 is unaffected.

Right-clicking on a row to bring up the context menu also selects that row. This means that if you first select several rows with shift/ctrl + left click, then right click on the selected rows for a bulk operation, you end up selecting one row.

This behavior is unexpected due to the way Windows handles this situation, which is to not modify the selection with a right click if there is a multi-selection present. Current behavior could be intended however.

Gif of issue:
![right click issue](https://i.imgur.com/S4ICTXl.gif)

**Comment by adelikat** [comment]
Fixed this a few days ago.  Just be warned, using the latest build right now is pretty unstable.  Moving from the VirtualListVIew control to the InputRoll from TAStudio was a drastic change, there will be things like this for a bit.

But, if you want to bravely forge ahead in unstable land, that would be helpful to have bug reports.  As long as they are clearly labled as the latest master not last release :)

**Comment by Zinfidel** [comment]
Sorry about the version ambiguity, it slipped my mind that I was playing around in master when I discovered the issue. Is there a writing convention you follow for logging issues for master? I have another submitted issue that affects master specifically that I can update.

**Comment by YoshiRulz** [comment]
Comments are Markdown, so write the first 7+ chars of the commit's hash. `fcc0bc19a` becomes fcc0bc19a. If you're downloading from AppVeyor it's in the archive's filename.
