### ISSUE TITLE
Multi disk bundler review

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1747]
Hi friend im testing varios features of the emu hawk example multi disk bundler im think include GBC and GBA support Will be Nice to the emu you already simplemente old GB and this work fine there no bug or issue on the OLD GB multi disk bundler  think in these have Nice day

**Comment by alyosha-tas** [comment]
GBC is already supported (just use GB)
GBA will be supported when there is a multi GBA capability.
