### ISSUE TITLE
Genesis/MD TeamPlayer controller type issue - Columns 3: The Revenge of Columns

### ISSUE THREAD

**Issue by RoyTheDragon** [TASVideos/BizHawk#1750]
I was actually wanting to see what I could do with the TeamPlayer setting on Columns 3, trying to make a TAS using this emulator specifically.

It's apparent that the TeamPlayer needs to only be connected into player 2's controller slot for 3, 2v1, 4, 2v2 (Japanese only) and 5 player modes.
If there's anything I'm missing please let me know, because I'm a bit confused and still relatively new to the emulator as a whole.
Using: BizHawk 2.3.2.

**Comment by YoshiRulz** [comment]
Reproduced; none of the eight Start buttons will progress the splash screen. GPGX almost certainly supports 5-player so it should be possible to fix.

**Comment by nattthebear** [comment]
The following simple code change fixes this:

```
					case ControlType.Teamplayer:
						system_a = LibGPGX.INPUT_SYSTEM.SYSTEM_MD_GAMEPAD;
						system_b = LibGPGX.INPUT_SYSTEM.SYSTEM_TEAMPLAYER;
```
But I don't know if that's universally applicable.  Google suggests that all four combinations of teamplayer vs pad in each of the two controller ports are valid, but it's up to games to support whatever they support.  Do we need another config setting?
