### ISSUE TITLE
BizHawk SlimDX Problem

### ISSUE THREAD

**Issue by Adrix23** [TASVideos/BizHawk#1759]
I have a problem with SlimDX, I have a PC with Windows 7 Ultimate 32 Bits and I try to open bizhawk but I get this

System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version = 4.0.13.43, Culture = neutral, PublicKeyToken = null'. This assembly was compiled for a different processor.

I try to get in but I can't, does anyone know how to fix it?

**Comment by YoshiRulz** [comment]
Have you run the [prerequisite installer](https://github.com/TASVideos/BizHawk-Prereqs/releases/tag/2.1)?

**Comment by Sappharad** [comment]
You should clarify what version of BizHawk you're trying to run. BizHawk 2+ does not support 32-bit machines

**Comment by Spikestuff** [comment]
https://github.com/TASVideos/BizHawk/releases/tag/2.0
http://tasvideos.org/Bizhawk/PreviousReleaseHistory.html#Bizhawk20
