### ISSUE TITLE
Saturn Graphics Glitch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#176]
```
What steps will reproduce the problem?
1. Play Policenauts till office scene.
2.
3.

What is the expected output? What do you see instead?
The game displays properly... but it doesn't. It will however display properly 
if I activate a "Look" prompt. See screenshots. It will revert back to the old 
way if I go out of the look prompt.

What version of the product are you using? On what operating system?
Latest, Win 7.

Please provide any additional information below.


```

Original issue reported on code.google.com by `hrr...@gmail.com` on 20 May 2014 at 12:26

Attachments:
- [saturnissue.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-176/comment-0/saturnissue.png)
- [saturnfixed.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-176/comment-0/saturnfixed.png)

**Comment by nattthebear** [comment]
Closing as we have dropped yabause for mednasaturn
