### ISSUE TITLE
Clear Registered Functions doesn't work, can cause crash

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1763]
Affects master branch, commit: 5dd226d

The Clear Registered Functions menu item in the Lua Console does not work correctly. It clears the list of functions, but does not actually de-register them. After clearing the functions, the functions will continue to execute on callbacks. If the Lua Console is closed, and emulation resumed, an exception occurs when Ocotshock (any core?) tries to execute the callback and gets null.

This is due to accidentally calling the Clear() method on LuaFunctionList instead of the ClearAll() method.

```
private void ClearRegisteredFunctionsContextMenuItem_Click(object sender, EventArgs e) 
{ 
	GlobalWin.Tools.LuaConsole.LuaImp.RegisteredFunctions.Clear(); 
} 
```
should be
```
private void ClearRegisteredFunctionsContextMenuItem_Click(object sender, EventArgs e) 
{ 
	GlobalWin.Tools.LuaConsole.LuaImp.RegisteredFunctions.ClearAll(); 
} 
```

**Comment by vadosnaprimer** [comment]
I noticed that emulation slows down (as expected) when I hook to all instructions and after clearing registered functions it remains slow, even tho they indeed are meant to be unregistered.
