### ISSUE TITLE
ZXSpectrum has no music in Hardy

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#1767]
Spectaculator plays the music fine in 128 mode. Hawk only plays sound effects. @Asnivor @alyosha-tas?

[hardy.zip](https://github.com/TASVideos/BizHawk/files/3998786/hardy.zip)
https://rgb.yandex/storage/201/hardy.zip

**Comment by alyosha-tas** [comment]
The game expects port 0xFDFD to be recognized as AY-3-8912 port select. If this is done the sound works correctly.

Currently only 0xFFFD is recognized as port select.

According to worldofspectrum, port selection can be any of:

Peripheral: 128K AY Register.
Port: 11-- ---- ---- --0-

I'll leave it to Asnivor to implement it fully though as he is familiar with the inner workings of the architecture here, it might drive more changes.

**Comment by Asnivor** [comment]
Thanks @alyosha-tas, that is an interesting find. Should be sorted now.

When I have time I will have to go through all the other port decoding parts and see if I have missed anything.
