### ISSUE TITLE
Make Basic Bot Easier to Use/Understand

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#1769]
- When you open Basic Bot, it should pre-fill the ">=" operator on the primary value
- When one of the required fields is left blank, it should give an error that explains which field was blank. (Currently, it just gives a generic "can't run with those settings" which doesn't tell you what you did wrong).

- [optional] Turn off audio and visuals while running basic bot for a 2-3x speedup (Right now, it's easy to try using it, and not realize you can make it faster).

**Comment by adelikat** [comment]
Ok, added these 3 suggestions
