### ISSUE TITLE
Atari 2600 Pitfall II - line of video at far right

### ISSUE THREAD

**Issue by jaw9170** [TASVideos/BizHawk#1772]
Hi,

I just started using BizHawk, so if this is a known issue or user error, please forgive me and be nice to me.  ;)  

When using BizHawk to play Atari 2600 Pitfall II - Lost Caverns,, there is a vertical line of video to the far right that seems like it may not supposed to be there.

This is most visible on the second and third screens when an enemy is flying or crawling toward you.

![Pitfall II - Lost Caverns 2019-12-28 15 08 55](https://user-images.githubusercontent.com/34951611/71548972-05537980-2984-11ea-91a0-f3f56bd46995.png)

**Comment by alyosha-tas** [comment]
please test on the dev build, I have made many atari 2600 changes recently and some games were broken in 2.3.2.

Dev build available here:
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by jaw9170** [comment]
Hi.  Issue remains on dev build, sorry  Attached is a screenshot
![Pitfall II - Lost Caverns 2019-12-28 23 32 58](https://user-images.githubusercontent.com/34951611/71552392-7cabfc00-29ca-11ea-9ac6-a53d35283ab2.png)

**Comment by alyosha-tas** [comment]
alright i'll look into it, thanks for testing
