### ISSUE TITLE
SNES dragón view filter scanline bug

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1774]
Hi Friends in testing the bsnes core with lot of games im noticed some games have trouble with display filter example dragón view have a strange scanline that cannot be desactivated im post a pic of the bug 
![IMG_20191229_154607](https://user-images.githubusercontent.com/42782548/71561848-8416e800-2a52-11ea-8128-541263c5fa66.jpg)

**Comment by zeromus** [comment]
"a lot of games"? I don't think so. This is a famously troublesome, unique scene. This is the way the game is supposed to work. It looks better on a TV. If there's "a lot of games", then please list a lot of games.
