### ISSUE TITLE
SM64 is super buggy (epilepsy warning)

### ISSUE THREAD

**Issue by Derpspace** [TASVideos/BizHawk#1776]
No packs same rom works fine on Project 64

![2019-12-29_15-37-42_Trim_1](https://user-images.githubusercontent.com/59072461/71563281-503bc280-2a52-11ea-8f72-af087fbf1bab.gif)
No textures or anything

**Comment by NarryG** [comment]
Try swapping graphics plugins. I'm guessing it's a driver issue. Rice, while outdated, usually works fine on GPUs that GlideN64 doesn't

**Comment by Derpspace** [comment]
ok thanks that worked
