### ISSUE TITLE
Bring mGBAHawk to feature parity with VBANext

### ISSUE THREAD

**Issue by endrift** [TASVideos/BizHawk#1777]
I've been told that mGBAHawk is missing a few features that are keeping it from being in-line feature-wise with the VBA-Next core, namely:

- [ ] ROM pokes (which the mGBA core does support, using mCore's rawWrite interface)
- [x] Memory hooks
- [x] Trace logging

It would be nice to add these features to mGBAHawk to remove one remaining reason to use VBA-Next.

**Comment by NarryG** [comment]
If I'm not mistaken, ROM pokes are already wired up but just don't work because the domain is marked as read-only.

**Comment by RetroEdit** [comment]
Implementing `event.oninputpoll` for the mGBA core would be useful for me. I want to avoid a situation where an input is entered at the beginning of a frame and then somehow changes before the poll occurs, which could potentially desync the script I'm working on.

**Comment by vadosnaprimer** [comment]
Trace logging is implemented in dev.

**Comment by adelikat** [comment]
We have mem hooks, input callbacks, cpu setting.  We officially have the same features in mGBA as VBA-next :)
