### ISSUE TITLE
[Linux] Record AVI function does nothing.

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#1779]
And it seems the config was disabled too.  Which I would assume is done to prevent crashes, but the default should be ffmpeg.

**Comment by YoshiRulz** [comment]
typo https://github.com/TASVideos/BizHawk/commit/784c800ca2c5d3ef13760c48ec47f4fe6c9bf59c#diff-d14290069318f05b9231cd0d89ac18a0R287

**Comment by YoshiRulz** [comment]
Stupid amend didn't count - resolved by 854077343.

reminder to use #1430 so I don't have to label all these
