### ISSUE TITLE
PCEHawk: input desyncs in Akumajou Dracula X: Chi no Rondo

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1781]
I recorded a playthrough of Akumajou Dracula X: Chi no Rondo, only to find that it suffers from random desynchronizations. Random meaning that it does not always desync at the same spot.

Also, when I fast forward through cutscenes, the voices still sound at normal speed, even though the game goes faster. This does not affect the .avi recording, but still is kind of strange.

**Comment by Reinc01** [comment]
Upon closer inspection, it seems that desyncs were caused by a translation patch I was using. I recorded two playthroughs with patch applied and both playthroughs suffered from desyncs. Then I recorded a playthrough without the patch and there were no desyncs.

**Comment by zeromus** [comment]
Someone needs to find out why the hash wasnt different, or why the hash check wasn't running to warn you

**Comment by nattthebear** [comment]
Please retest on the mednafen pce core

**Comment by nattthebear** [comment]
Reopen if this persists on the new core.
