### ISSUE TITLE
NesHawk doesn't support S5B sound

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#1782]
Run Gimmick!
S5B sound doesn't play.

**Comment by alyosha-tas** [comment]
That's weird, everything looks like it's hooked up, did it ever work?

**Comment by nattthebear** [comment]
I seem to recall this working back in the day.  Can you confirm that the rom is identifying correctly?  It needs to pass a hash check to get the right stuff, and needs to be identified as Gimmick! (J) by the cart db.

**Comment by Yave-Yu** [comment]
OK, I tried original unmodified Gimmick ROM, the S5B sounds, is it too strict to play S5B sound?

**Comment by YoshiRulz** [comment]
Any modification changes the file's checksum, which is used by the gamedb to select which mapper to emulate. You can use `gamedb_user.txt` to do the same for roms that aren't in the gamedb.
