### ISSUE TITLE
Lua exec hooks don't work in Octoshock

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1783]
Affects latest master as of 69d8a473a1e8f504b8261a2f3842b2f2c4be3d2c

Read/write hooks work correctly, but exec hooks do not (confirmed by @vadosnaprimer ).
There does seem to be some sort of implementation for exec hooks in Octoshock at least:

**psx.cpp**
```cpp
extern void* g_ShockTraceCallbackOpaque;
extern ShockCallback_Trace g_ShockTraceCallback;
extern ShockCallback_Mem g_ShockMemCallback;
extern eShockMemCb g_ShockMemCbType;

//Sets the callback to be used for CPU tracing
EW_EXPORT s32 shock_SetTraceCallback(void* psx, void* opaque, ShockCallback_Trace callback)
{
	g_ShockTraceCallbackOpaque = opaque;
	g_ShockTraceCallback = callback;

	return SHOCK_OK;
}

//Sets the callback to be used for memory hook events
EW_EXPORT s32 shock_SetMemCb(void* psx, ShockCallback_Mem callback, eShockMemCb cbMask)
{
	g_ShockMemCallback = callback;
	g_ShockMemCbType = cbMask;
	return SHOCK_OK;
}
```

**cpu.cpp**
```cpp
   if (g_ShockTraceCallback)
   {
	//_asm int 3;
	shock_Util_DisassembleMIPS(PC, instr, disasm_buf, ARRAY_SIZE(disasm_buf));
    g_ShockTraceCallback(NULL, PC, instr, disasm_buf);
   }
```

**Comment by TwelveBaud** [comment]
The C++ side doesn't actually fire an execute callback in [`ReadInstruction`](https://github.com/TASVideos/BizHawk/blob/699fb1171caa63123ccd08c3d7a2b7fdd0b770c7/psx/octoshock/psx/cpu.cpp#L423) or in [`RunReal`](https://github.com/TASVideos/BizHawk/blob/699fb1171caa63123ccd08c3d7a2b7fdd0b770c7/psx/octoshock/psx/cpu.cpp#L550) -- it's missing the [trigger code](https://github.com/TASVideos/BizHawk/blob/699fb1171caa63123ccd08c3d7a2b7fdd0b770c7/psx/octoshock/psx/cpu.cpp#L256):
```cpp
 if (g_ShockMemCallback && (g_ShockMemCbType & eShockMemCb_Execute))
	 g_ShockMemCallback(address, eShockMemCb_Execute, 32, 0);
```

**Comment by vadosnaprimer** [comment]
Should be usable now.
