### ISSUE TITLE
Octoshock crashes when dumping a movie that's being replayed.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#1787]
Present on latest dev build as well.

How to crash BizHawk using Octoshock:
- Load any PlayStation game ([that has a BizHawk TAS](http://tasvideos.org/Movies-PSX-RatingU.html))
- Change PlayStation Options to Hardcore Debug Mode
- Pause BizHawk
- Load the movie to the chosen game
- Create an AVI Dump (Alt Sync Disabled if NTSC)
- Unpause BizHawk
- Crash.

Note: All the other screen modes also crash when doing the same steps.
2nd Note: fsvgm also has this exact same issue as me.

**Comment by Spikestuff** [comment]
Still Affects 2.4.

**Comment by Spikestuff** [comment]
@vadosnaprimer informed me about the fix attempting to correct that issue (at least on ffmpeg side).
Unfortunately that fix didn't fix anything and it still crashes for myself. :/

**Comment by Zinfidel** [comment]
@Spikestuff The ffmpeg fix hasn't been merged yet -- did you get a latest build from appveyor or a custom build with the fix when you tried it?

Also, apologies, I mistakenly thought this issue was about ffmpeg when it showed up in issue search.

**Comment by vadosnaprimer** [comment]
It was the PR build link.

**Comment by Zinfidel** [comment]
I tested a workaround for this issue with fsvgm. When attempting to dump a movie that crashes Octoshock, before loading the movie, make sure the psx input configuration matches the movie's input configuration exactly. Reboot the core, exit the program, then relaunch. Then try to play/dump the movie.

The emulator still crashes sometimes when doing this initially, but at least in the test case with fsvgm the second time worked. The input configuration tends to get reset/modified when doing this, so keep an eye on it.

**Comment by zeromus** [comment]
PROBABLY fixed, I said, but AI isn't that good yet (thank god)

**Comment by Spikestuff** [comment]
On my end using the appvoyer builds "[new octoshock dll](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/30683909)" corrected the issue for both FFmpeg and AVI Dumping.
Thanks guys.
