### ISSUE TITLE
Issues with Hamtaro GBA Game

### ISSUE THREAD

**Issue by zackattack056** [TASVideos/BizHawk#1789]
In the GBA game Hamtaro: Ham-Ham Heartbreak, both cores have huge issues. mGBA Plays properly as far as I can tell, but the top section of the screen doesn't display sprites properly, as they will dissapear and reappear at times, and just in general look off. It is first noticable when a character dissapears during part of the tutorial, and when you start to progress into Sunny Peak. In the VBA-Next core, the game simply wont run when you try to begin after the name select screen. This continues during transitions throughout the game, as this is copy protection that was bypassed in both the mGBA core and VBA-M. The issue in mGBA with the sprites isn't present if you load save data from later in the game to test it.

**Comment by NarryG** [comment]
Check this with mGBA upstream and see if it's an issue there. If it is, report it there. Otherwise, the core may just need an update

**Comment by zeromus** [comment]
I just played to sunny peak in the mgba core and didnt notice any problems. I am skeptical that the mgba core "bypasses a copy protection". I am skeptical that sprites missing from the top of the screen are "copy protection". I am skeptical that you have an unhacked rom. I am skeptical of any bug report concerning graphical corruption without a screenshot.

**Comment by zackattack056** [comment]
To clarify, here are pictures to confirm what I mean.

![Hamtaro - Ham-Ham Heartbreak (Europe) (En,Fr,De,Es,It) 2020-01-05 01 26 49](https://user-images.githubusercontent.com/36513712/72234274-30e87d80-359a-11ea-9f55-2d071c9bfd05.png)
![Hamtaro - Ham-Ham Heartbreak (Europe) (En,Fr,De,Es,It) 2020-01-05 01 27 12](https://user-images.githubusercontent.com/36513712/72234275-30e87d80-359a-11ea-84a7-41c5485961ad.png)
![Hamtaro - Ham-Ham Heartbreak (Europe) (En,Fr,De,Es,It) 2020-01-13 00 09 52](https://user-images.githubusercontent.com/36513712/72234277-30e87d80-359a-11ea-814d-70f00f8fbf9e.png)

I have confirmed the rom is unhacked. 

The copy protection thing refers to the VBA-Next core softlocking, something that had been reported in the past that in retrospect I am not sure if was copy protection, but regardless there are old cheat codes I found dedicated to passing the softlock from said "copy protection," or at least that is what I heard some places call it and I sort-of assumed those were correct. The "protection" only worked on some emulators from what I could find though in the first place. Partially an assumption it was protection specifically, but regardless an issue that has existed for others in the past.

That being said, I am likely just going to make sure my core is updated and then follow the first person's instructions.

**Comment by zeromus** [comment]
What's missing? I don't see anything missing.

**Comment by zackattack056** [comment]
In the first and third images it is just the graphical stretching at the top, but the second there is a floating seed when there is supposed to be an NPC holding it.

**Comment by zeromus** [comment]
OK, I believe it now. You must be using. Use a brand new version of bizhawk, the mgba core was updated less than 48 hours ago

**Comment by zackattack056** [comment]
That seemed to work, I didn't notice it updated so recently. Closing.
