### ISSUE TITLE
GBHawkLink4x is very broken

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1793]
I wanted to try GBHawkLink4x with the following games in the following order:
1) Pokémon Red,
2) Pokémon Blue,
3) Pokémon Gold,
4) Pokémon Silver.

This is what I got:
![Pokemon Gen 1-2 2020-01-13 16 33 23](https://user-images.githubusercontent.com/36802254/72268834-d9dabb00-3622-11ea-9b42-855f2efe29f6.png)

And this is where each player inputs go:
- Player 1 inputs go to Pokémon Blue.
- Player 2 inputs go to nowhere.
- Player 3 inputs go to both Pokémon Gold screens.
- Player 4 inputs go to Pokémon Silver.

Apart from all that, if you look into the Hex Editor and take a look into the different ROM domains, you'll see that:
- ROM A displays Pokémon Blue data.
- ROM B also displays Pokémon Blue data.
- ROM C displays Pokémon Gold data.
- ROM D displays Pokémon Silver data.

**Comment by alyosha-tas** [comment]
4x is not released, it is WIP

**Comment by alyosha-tas** [comment]
I fixed these bugs, but please use the dev. thread to post any further issues as this is still in development.

**Comment by hegyak** [comment]
For those who look at this later:
https://github.com/TASVideos/BizHawk/commit/8fed99456ad277f228c79b4955461ac23904b897

Is the Commit you want or anything past that commit for this issue.
