### ISSUE TITLE
SNES emu core updates (BSNES)

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1797]
The Bsnes and SNES 9x have lot of update to the core type emu that Boost performance need to review these core and update in bizhawk one of these update Fix some games can have scanline filter problem

**Comment by Spikestuff** [comment]
For snes9x follow the information at #1374 or #1722
snes9x is a low priority emulator which basically means "just use bsnes".

As for bsnes it's a waterbox core which you can follow the information at #1412 and [here](https://github.com/TASVideos/waterboxdev).

**Comment by zeromus** [comment]
renaming this to BSNES so it's not a waste of space

**Comment by nattthebear** [comment]
Among other things, CX4 behavior has changed in newer BSNES versions. https://github.com/TASVideos/BizHawk/issues/1609

**Comment by YoshiRulz** [comment]
With Faust for speed and an updated BSNES for handling edge cases, we can drop Snes9x (#1204; plus we'd close Snes9x issues #1374 and #1208).
