### ISSUE TITLE
Add support to blend Hi-Res image to SNES cores

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1798]
The SNES emu core missing an important function called blend Hi-Res imagen that are present in SNES 9x and other emu that increase the image Quality of SNES games its be Nice the bizhawk can use this function to  for a example check the snes 9x 1.60 emu and test with some games you look the diference

**Comment by Spikestuff** [comment]
For the sake of pointing it out there. Hi-Res is a hack.

https://youtu.be/6VrzJ6Y1kjQ

Also for the sake of showcasing, this is on mGBA as well.

https://youtu.be/j8hZAjeHYX8

**Comment by DarkLegend1987** [comment]
No im not meant that hack is you play dragón view rom in bsnes and Enter random battle you look a strange scanline that are disgusting play in SNES 9x conf. There an option called blend Hi-Res image when you click in the scanlines dissapear and be perfect image , yes im not like the HD mode hack because im used to be a snes console heavy player

**Comment by zeromus** [comment]
This should be tagged only as an upstream update for any core known to have it. that would be snes9x, not bsnes, unless we know bsnes has it.

**Comment by nattthebear** [comment]
Faust supports this
