### ISSUE TITLE
tastudio.submitinputchange() doesn't visually show the input change until playback starts

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1799]
When I run say `tastudio.submitinputchange(100, 'A', true)` (and subsequently `tastudio.applyinputchanges()`), if frame 100 has not been recorded (i.e. if frame 100 is greyed out and doesn't yet have a nearby savestate), then the input change is not immediately shown in the interface. Once playback starts, the button change magically appears in the interface. If the frame is within an area that *has* been played back, then it immediately shows the change, while obviously marking frames past the changed frame as not played back because of the input change.

This seems to me a usability issue and could be a bit confusing, because input changes through the API are thus entirely invisible until playback starts, which could lead to visual confusion if playback hasn't occured recently.

I'm using Bizhawk 2.3.3 by the way; I don't know if the issue was in 2.3.2, but I can test.

**Comment by adelikat** [comment]
Fixed in release branch
