### ISSUE TITLE
View inputs of loaded movie state

### ISSUE THREAD

**Issue by Tompala** [TASVideos/BizHawk#1802]
When loading a movie save state in all previous versions of BizHawk, you have been able to see what inputs presses that were made for that frame. This is not present anymore in 2.3.3 and 2.3.4. I do not know if there is a reason for its removal, but I would very much like to have it as an option to enable if so, as it's practically required for me to TAS properly.

**Comment by Sonia-7** [comment]
I echo this is a significant issue and gets on the way of proper movie making. Went back to 2.3.2 because of that, and will keep using that version until this is fixed.

**Comment by adelikat** [comment]
Fixed input display when in read-only mode too, which has been broken since 2014 (lol)

Closing this ticket.
