### ISSUE TITLE
[FEATURE REQUEST] SNES CDL (BSNES core) - logging JSL/JSR destinations

### ISSUE THREAD

**Issue by gocha** [TASVideos/BizHawk#1804]
If possible, I would like to collect subroutine addresses from emulation results. (I haven't used such a feature before, so I'm quite not sure how useful it really is for reverse engineering...)

Does BizHawk (BSNES) already have such a feature?

**Comment by zeromus** [comment]
Well, @g0me3 would be the guy to ask. I think without digging into it that it sounds feasible. Does it sound useful?

**Comment by g0me3** [comment]
maybe useful for some sort of disassembly automation, but currently I'm setting up my ida scripts for snes so I could find as well jsl/jsr destinations semi-automatically like I did it for gb. I haven't seen any examples when I coudn't find the jump destination during disasm at all without debugging.

for me most interesting and usable function would be to log destination offsets of short 16bit memory access instruction since IDA processor module by gocha does a lot of missing links (red offsets) even if there is a clearly wram locations for example...

**Comment by zeromus** [comment]
I need you guys to agree what to do next, and to explain in more detail what @g0me3 's new idea is. I don't quite understand it. (like give me example instruction and registers and tell me what should happen)

**Comment by g0me3** [comment]
actually I'm not too confident with snes internals as well, so maybe there a better way to fix offsets with ida only...
but there are two type of opcodes: 
8F 00 21 00                 STA     $00:$2100
and
8D 55 43                    STA     $4355
haven't investigating this but if opcode has full 24bit offset, it points to a particular place in memory.
im not sure where short opcode get its full offset but IDA do not know this as well and can't to set offset properly.
while in runtime, emulator obviously should know definitely the dst address and maybe there is a way to log it (maybe uint32 for every rom byte and fill those bytes which is memory offset operands for such opcodes don't know)...

**Comment by zeromus** [comment]
a narrow STA gets its full address from the data bank register. That STA instruction could reference SEVERAL different banks. This is more likely to be the case for a LDA though which would be reading different data files from the ROM. I'm not sure why you would doubt what a STA is doing.

**Comment by g0me3** [comment]
yeah, i see there are at least 3 segment registers for different purposes, the problem is sometime you couldn't see what register used for a given opcode at a given time only with disassembly. IDA processor module tries to analyze code to detect the correct banks, but I see it failed many times so it need something to guide it more precisely. im not even sure it always correctly distinguish hw registers from ram locations sometimes..

**Comment by zeromus** [comment]
What do you want IDA to tell you? Do you want to know if a LDA accessed the rom? We can possibly add a flag for instructions (1st opcode byte) that says whether it addressed the ROM.

At a certain point I think we're going to find that the CDL is insufficient and we really need to output a detailed trace (in a more compact form than trace log, but still with more information) which would then get analyzed by a tool with more flexibility.

**Comment by g0me3** [comment]
i want to know what exactly address the short opcode is refers to. not me personally want it but if you want to get a full disassembly which may be reassembled, you must know all offsets. that's all.

anyway, returning to the main object, this is not my request and me currently struggling with all this stuff myself lol when I know the right solution I will post my own request ;)

the snes cpu is an ass hell for disasm and re lol, second weirdest asm after ARM.

**Comment by gocha** [comment]
To zeromus and gome3: Thank you for your feedback.

Recently, I started trying to disassemble a certain game with [DiztinGUIsh](https://github.com/Dotsarecool/DiztinGUIsh/pull/10), and I changed my mind somewhat. Now I don't feel this feature is so necessary, so it may be better to close this issue?

As gome3 says, I can semi-automatically collect JSL/JSR destination addresses using a CDL result and a disassembler or a static analysis tool. (especially if we had a script to import the CDL to IDA)

Instead, now I have two issues/requests:

* Want to log direct page and data bank register values (and program bank register if useful?). As zeromus said, I also think the CDL is insufficient for this purpose. Compact detailed trace sounds nice, but I have no detailed ideas for it as of now
* Cannot determine if ROM data was read as 8-bit value or 16-bit value, from the CDL

I will comment again if I come up with something. Thank you for reading.

**Comment by zeromus** [comment]
Your second bullet point sounds easy. Can we add a flag for CPUData16 and if it's set, it was read as part of a 16bit read?

**Comment by gocha** [comment]
> Can we add a flag for CPUData16 and if it's set, it was read as part of a 16bit read?

Yes, I think so. Adding CPUData16 flag for 16bit read and write (for RAM usage) will help.

**Comment by gocha** [comment]
Cancel this request. As I wrote above, I was a little more interested in this request than at first. Also, I think it is better to work with this function in another function such as compact trace log instead of CDL.

Request for 16bit data is separated to #1835
