### ISSUE TITLE
Log Window is Broken

### ISSUE THREAD

**Issue by SuuperW** [TASVideos/BizHawk#1807]
1) Start BizHawk without the log window
2) Show the log window
3) Emulation -> Reboot Core
Result: Nothing is shown in the log window; actually, nothing will ever show there.

**Comment by zeromus** [comment]
Not gonna fix this. Probably not possible to fix this. It's due to the way the stupid windows console works. The workaround is obvious, close the app and reopen it and everything is peachy.
