### ISSUE TITLE
Octoshock corre rare error when play mega man X6 v.(1.0) /(1.1) redump

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1808]
Today im testing octoshock core and when im get redump mega man X6. v.1.0/1.1 the emu show a strange bug the gamedb psx have both hash and the core dont recognise the Redump iso 
![IMG_20200118_013523](https://user-images.githubusercontent.com/42782548/72917024-7d118b80-3d19-11ea-8b5d-9eff34771977.jpg)

**Comment by YoshiRulz** [comment]
Load the cue file, not the iso. We should replace that dialog with one saying "Don't load ISOs."

---

Push Shift+Win+S to take a screenshot, then save it somewhere, then drag-and-drop it into the textbox to attach it.

**Comment by zeromus** [comment]
I thought we had such a message but the rom loading code is always over-stressed and getting broken

**Comment by Spikestuff** [comment]
Load the cue.
![image](https://user-images.githubusercontent.com/12412764/72948632-dccf6b80-3dd9-11ea-8307-741f9a014235.png)
