### ISSUE TITLE
[BSNES core] crash when load state after restart

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1810]
I'm not sure if this is because of some specific settings combinations, or I have some problems here with my pc, but

when you play snes game with BSNES core (the same lawnmower again lol), the save states works just fine as soon as you does not close the emulator.

when you close it and then reopen the game again and try to reload the last save, emu crashes silently.

**Comment by zeromus** [comment]
Worked fine for me.
Are you sure youre not loading a savestate taken before the waterbox core was updated? That should trigger an error message, but maybe you're not getting exception error messages for some reason.
Can you try debugging emuhawk in VS and finding out what's going on?
@nattthebear did this ever happen to you? Sorry to nameflash you but if there's something wrong with my waterbox builds we had better find out ASAP

**Comment by g0me3** [comment]
savestates are created just now with newest build.

**Comment by g0me3** [comment]
sorry, I tried to build latest version of bizhawk but I failed lol build tool crashes, sln project does not load with my 2017. i give up.

**Comment by YoshiRulz** [comment]
You need VS 2019 now, changed about 3 months ago.

**Comment by g0me3** [comment]
ok, i did it after all. problem occurs at BSNES core somewhat.
as I checked carefully, if I use my own compiled version, all is fine actually, all states are load no matter when.
however, those states that were produced by one of previous appveyor builds does not load and cause crash even in my own build. so there are some save corruption were happens with a particular build but not in my current fresh build...

crash appears somewhere inside external compiled code (waterbox for BSNES i presume).

if you want to dig it for some reason, here are states. state2 is good one, state1 is a bad one.
[State.zip](https://github.com/TASVideos/BizHawk/files/4139146/State.zip)

**Comment by g0me3** [comment]
happens to me again, see more corrupted savestates.
First I was thought it is because using cheats, but European version of clay fighter crashes the same way without any cheats.
[State.zip](https://github.com/TASVideos/BizHawk/files/4142737/State.zip)

under debug crash occurs somewhat outside the main emu code, so it seems it is inside bsnes waterbox core as I said before...

can anybody confirm if my saves crashes on other pcs? also, note, i use goodsnes romset with gamedb disabled in emulator.

**Comment by g0me3** [comment]
something has changed. another time got this crash message

`System.InvalidOperationException: Memory consistency check failed.  Is this savestate from different SyncSettings?
   в BizHawk.Emulation.Cores.Waterbox.PeWrapper.LoadStateBinary(BinaryReader br) в D:\Dev\BizHawk\BizHawk.Emulation.Cores\Waterbox\PeWrapper.cs:строка 425
   в BizHawk.Emulation.Cores.Waterbox.PeRunner.LoadStateBinary(BinaryReader br) в D:\Dev\BizHawk\BizHawk.Emulation.Cores\Waterbox\PeRunner.cs:строка 1205
   в BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore.LoadStateBinary(BinaryReader reader) в D:\Dev\BizHawk\BizHawk.Emulation.Cores\Consoles\Nintendo\SNES\LibsnesCore.IStatable.cs:строка 35
   в BizHawk.Client.Common.BinaryStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback) в D:\Dev\BizHawk\BizHawk.Client.Common\BinarySaveStates.cs:строка 248
   в BizHawk.Client.Common.BinaryStateLoader.GetCoreState(Action`1 callbackBinary, Action`1 callbackText) в D:\Dev\BizHawk\BizHawk.Client.Common\BinarySaveStates.cs:строка 304
   в BizHawk.Client.Common.SavestateManager.LoadStateFile(String path, String name) в D:\Dev\BizHawk\BizHawk.Client.Common\SavestateManager.cs:строка 159
   в BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean fromLua, Boolean suppressOSD) в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:строка 4097
   в BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(String quickSlotName, Boolean fromLua, Boolean suppressOSD) в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:строка 4158
   в BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger) в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\MainForm.Hotkey.cs:строка 30
   в BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__109_1(Boolean current, String trigger) в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:строка 929
   в System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   в BizHawk.Client.EmuHawk.MainForm.ProcessInput() в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:строка 929
   в BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:строка 570
   в BizHawk.Client.EmuHawk.Program.SubMain(String[] args) в D:\Dev\BizHawk\BizHawk.Client.EmuHawk\Program.cs:строка 219`

**Comment by g0me3** [comment]
there is a potential fix https://github.com/TASVideos/BizHawk/commit/27e600c1ac83edad8d47c4b60ebfd09dd176da9c
but tried to compile latest repo and still have all issues i mentioned.

so, this fix does not change it for me, still can't restore savestate after emulator restarting, not even in BSNES core, but also in MD/GEN cores. 

need to mention, not sure I mentioned this earlier, but saves DO work when you use them without leaving the emulator - just in current instance. as soon as you close BizHawk, all previously made savestates are turns useless because when you start another instance of emularot, re-run the same rom and try to load save from previous instance, it failed silently.

**Comment by g0me3** [comment]
ok, MD seems work now, bsnes still not

**Comment by YoshiRulz** [comment]
Can you use a build from AppVeyor or GitLab, and record yourself reproducing the bug?

**Comment by nattthebear** [comment]
The error message you gave way back in February is from a build that's very outdated now.  Please provide error messages and/or reproducing steps for current dev builds.

**Comment by g0me3** [comment]
Ok, tried to reproduce on the camera. It seems, it workms mostly fine when using the menu options to save/load states. But me using the hotkeys F5/F7 accordingly, so as soon as I hit the F7 button near the end (does not displayed at the screen, crashes early than OCD displays), it crashes. See I did the same, hit F7 in the Studio and got Violation Error at the end. 

https://youtu.be/I99VWUEN4-U

Sometimes this may occur when switching the games, sometimes not. Sometimes all works fine, but after all degrade for sure. Even the menu options may cause the crash (with no error messages). For me it looks like at some point either the save file or save file path corruped somehow after some operation and does not load after that.

when I'm writing that text, tried to reload previously recorded saves from video above with menu options and it crashes too. So but seems semi-random.

**Comment by g0me3** [comment]
Also maybe starting from the ROM folder via command line association involved too.

**Comment by zeromus** [comment]
Please hit ctrl+alt+e and enable all the exception types and repeat the experiment. That way we can see where the exception is thrown from. It's not likely to help, but there's a real chance.

**Comment by g0me3** [comment]
There is no difference. The same "Access Violation" code even when running under debug build.

**Comment by g0me3** [comment]
Ok, my guess about savestagte corruption seems right, but it seems it occurs during save not further load. sometimes it saves a bad data.
Here two saves from my video, 2 does not load, 5 load eighter via menu option or hotkey. 
[State.zip](https://github.com/TASVideos/BizHawk/files/5644737/State.zip)

**Comment by g0me3** [comment]
on the second thought, I see not corruption in save data, all files inside are intact, same size and all fine. but states are just different a little. does both load well for you?

**Comment by zeromus** [comment]
state 2 crashes for me also, but I can't debug it right now due to some unhappiness between visual studio and libsnes/waterbox...

**Comment by zeromus** [comment]
I see state 2 crashing only deep inside bsnes indeed. Maybe there is something funny about libco. Can you test another waterbox core and see if you can ever make it happen? I would think this would disrupt pretty much all SNES tasing on bizhawk, so I don't understand fully what's going on...

**Comment by g0me3** [comment]
as I told before, MD were suffer from this as well, but at some point it works fine, maybe this is because semi-randomness of the bug as well. last time i tried to restore MS savestate it worked, but previously not.

**Comment by g0me3** [comment]
but i tried MD for some roms and does not have that bug anymore.

**Comment by g0me3** [comment]
as a side note, sometimes I see clearly a CDL data corruption. can't reproduce them all the time, and maybe here is nothing to do with snes save states stuff, but at least once I have this corruption after save state load attempt with silent crash of emulator. loaded CDL file after that and one fixed block at 400-FFF were ored with 0x31 bytes all the way.

as soon as sometimes this may happer because of internal game crash during emulation this is hard to determine what the actual code of this.

**Comment by zeromus** [comment]
That is not a great surprise. Based on the ORing pattern, I assume loading the savestate makes the emulator core go crazy "executing" nonsense code in a crazy way. Crazy emulator cores can easily crash a process.

**Comment by nattthebear** [comment]
Just spent some time slapping save/load state randomly in a few snes games, combined with core reboots and application restarts, and wasn't able to see anything unfortunately

**Comment by g0me3** [comment]
at some point me also thought the bug is fixed, but then me got the same crash again and again.

did you tried to load savestates me provided earlier?

**Comment by g0me3** [comment]
got the same corruption in another game (scooby doo). this time me doesn't do the saves at all. corrupted  area between 800-1a00. it is the first 1 or 2 kb of rom all the time. this time 06 or 07 flags set at once.

**Comment by zeromus** [comment]
Just to be clear, you did not use savestates but rather just played scooby doo for a few minutes and then noticed the CDL was corrupted? Did you notice corruption or crashes in any other manner?

**Comment by g0me3** [comment]
yes without savestates. just cant catch the actual moment when it happens. maybe when you use passwords ingame. no any side effects to the game itself. no crashes or wrong data reads. me get my sctips little bit of analyse and they show me corrupted areas. most of the time area of corruprion near the beginning of the rom (8500-A000 i.e. first 8kb). and usually this involves merging the whole area with the same bit 02 (opcode operand) or 04 (data) or both. havent seen other bits merged there with regular cdl data. even if there is possibility that game goes wrong at some point by itself no way it can fill that area with 02 flag without 01.

**Comment by g0me3** [comment]
ok, me played this game again a lot and never had the same corruption. maybe previously me hit the save state button reflectory. played the whole game, used all options and had no corruption this time... weird. still can't trust on savestates anyway ;)

**Comment by zeromus** [comment]
damn it, I hate to hear that
would it be too crazy to ask you to use some screen recording software whenever you are doing CDL work for a game so you have a video record of what you did and can be certain whether you instinctively used a state or rewind without even thinking about it?

**Comment by nattthebear** [comment]
@g0me3 Could I get some savestates to try this out against on the latest Bizhawk?  I promise I will look at them this time.

**Comment by g0me3** [comment]
nattthere

> @g0me3 Could I get some savestates to try this out against on the latest Bizhawk? I promise I will look at them this time.

here
[Uploading Scooby-Doo (U) [!].BSNES.Compatibility.QuickSave1.zip…]()

**Comment by g0me3** [comment]
nattthere

> @g0me3 Could I get some savestates to try this out against on the latest Bizhawk? I promise I will look at them this time.

here
[Scooby-Doo (U) [!].BSNES.Compatibility.QuickSave1.zip](https://github.com/TASVideos/BizHawk/files/6132178/Scooby-Doo.U.BSNES.Compatibility.QuickSave1.zip)

**Comment by g0me3** [comment]
nattthere

> @g0me3 Could I get some savestates to try this out against on the latest Bizhawk? I promise I will look at them this time.

here
[Scooby-Doo (U) [!].BSNES.Compatibility.QuickSave1.zip](https://github.com/TASVideos/BizHawk/files/6132178/Scooby-Doo.U.BSNES.Compatibility.QuickSave1.zip)

**Comment by g0me3** [comment]
damn this thing first it tells me i can't upload my file, then i can't delete my four duplicated files lol

**Comment by g0me3** [comment]
ok, me succesfully loaded with the previously saved savestate now...
will try to test if there are no more cdl corrupting

**Comment by g0me3** [comment]
already merged, rulz

**Comment by g0me3** [comment]
ok, me tested may OLD savestates with this fix and they are work now perfecly. closed. if there are any cdl corruption anymore, will opet the another issue ;)
