### ISSUE TITLE
Saving TAStudio movie breaks keyboard input

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1815]
This effects 2.4 as well as master.

Load a game, open TAStudio, save the movie, exit TAStudio.

Keyboard input no longer works. hotkeys no longer work.

**Comment by adelikat** [comment]
input and hotkeys work fine for me in that scenario...

**Comment by alyosha-tas** [comment]
Just tried with a fresh install of 2.4 and it's still happening. I don't know what's going on.

**Comment by alyosha-tas** [comment]
I did some more testing, and it looks like the problem (at least for me) is much more general then I firsst thought. Any open or save windows dialog will break input. I'm not really sure what's happening, must be something wrong with my computer, but not sure how to track down what.

**Comment by alyosha-tas** [comment]
I reset windows and the issue is now resolved. I'll try to see which program messed things up as I reinstall everything. For now, closed
