### ISSUE TITLE
ClientApi.SetSoundOn(false) causes sound looping from external tool

### ISSUE THREAD

**Issue by brian-armstrong** [TASVideos/BizHawk#1817]
Hello,

I have found a case where ClientApi.SetSoundOn(false) causes sound to loop the last ~10ms of audio forever when called from an external tool. I have only tested this on Octoshock so far. The looping occurs if my sound backend is set to DirectX but not if it's set to XAudio2. On the XAudio2 backend, the sound mutes as expected.

Upon calling ClientApi.SetSoundOn(true) with DirectX backend, sound playing continues as normal.

**Comment by Gikkman** [comment]
I remember there was an issue in the Lua implementation of SetSoundOff which caused the same problem. IIRC, the fix that was added was to "poke" the sound driver to make it realize that a change was made.

Found the commit: 41c57e5
