### ISSUE TITLE
[FAIL] Visual C++ 2010 SP1 Runtime

### ISSUE THREAD

**Issue by therion00** [TASVideos/BizHawk#1818]
So I installed Bizhawk but i'm getting an error on the verification of programs, below is the screenshot, I've reinstalled Visual C++ 2010 all the way to 2015 and still getting that error... help? Perhaps with TeamViewer for a quick fix?
Thanks!
 
![temp](https://user-images.githubusercontent.com/60335412/73150901-fa286200-4085-11ea-832b-a8f903a71b14.PNG)

**Comment by zeromus** [comment]
The box says to run the prerequisite installer, not visual c++

**Comment by therion00** [comment]
the prerequisite installer basically has all those files... but after installing I get the same error... this is the prereq installer, as you can see, it checks everything and everything gets checked and fine, but after I run bizhawk I get the same error. Below is the picture of what the prereq installer has: 
![temp 2](https://user-images.githubusercontent.com/60335412/73151330-fac1f800-4087-11ea-973f-745fc31a800a.PNG)

**Comment by zeromus** [comment]
I'll help you on teamviewer, but youll have to get on irc first

**Comment by therion00** [comment]
can you walk me through that? what's IRC

**Comment by zeromus** [comment]
No. It's in the Bizhawk.html link from the error box.

**Comment by therion00** [comment]
I'm sorry i'm not understanding

**Comment by zeromus** [comment]
You've tried for two minutes to understand. You can't succeed at everything you set out to do in two minutes. Give it two weeks.

**Comment by therion00** [comment]
well this is really helpful...

**Comment by zeromus** [comment]
User had to run prereq installer a 2nd or 3rd time, before it worked, supposedly....

**Comment by SkyLxcas** [comment]
i have the same fail and i can't fix it

**Comment by zeromus** [comment]
Did you run the prereq installer a 2nd or 3rd time? Are you actually using the latest version of that?

**Comment by SkyLxcas** [comment]
yes i did and it is version 2.4

**Comment by zeromus** [comment]
There is no prerequisite installer version 2.4
If you get on IRC and wait for me to show up, I will teamview to you and watch you run the prerequisite installer on your computer and find out what you're doing wrong

**Comment by SkyLxcas** [comment]
what is irc?

**Comment by zeromus** [comment]
I unhid all the comments so you can retrace the steps of the last guy asking the very same thing in this very same thread

**Comment by zeromus** [comment]
User had manually copied a 32bit msvcp100.dll into the 64bit dlls directory, acquired from <dll downloading website dot com>
the MS prereq installers do not remove such garbage dlls, so everything was broken.
Whenever anyone gets this bug, zap msvcp100.dll and msvcr100.dll from system32 directory and try the prereq installer again
