### ISSUE TITLE
Can not search for negative specific values in RAM search

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1819]
Affects most recent master at time of writing: 3287a0c465483d78d1a6b607a351729f5dd8e780

![2020-01-26 21_33_42-RAM Search](https://user-images.githubusercontent.com/1929934/73152318-538f9180-4084-11ea-8d5a-82690d35831e.png)

The RAM search tool does not accept negative input correctly when trying to find specific values. In the attached screenshot, notice that the value -128 in the left-hand pane is highlighted red, indicating that it would be removed by searching for the value -128. Clicking the search button confirms this.

I verified this bug using the Ocotoshock core, if that makes a difference.

Reproduction Steps:
1. Open a game to get a core loaded.
2. Open the RAM Search tool
3. Change comparison operator to "equals to"
4. Change display to "signed"
5. Change Compare To to Specific value
6. Enter a negative number in Specific value that exists in RAM at that time
7. Observe that it is not correctly preserved after searching for it

**Comment by zeromus** [comment]
You can work around this by entering the unsigned representation (128, in this case)
