### ISSUE TITLE
[TAStudio] Bind Markers to Input option does not persist across sessions

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1821]
Bug was found to exist from release version 2.3.2 to latest master commit ce79ec83d7951390dcf89cac453102c2ab161c74

The Bind Markers to Input option is reset when closing/reopening TAStudio. Other options in the same menu have their state persisted, so it seems like this one should too.

Reproduction steps:
1. Load ROM
2. Open TAStudio
3. Config > Bind Markers to Input
4. Close TAStudio
5. Open TAStudio
6. Observe Bind Markers to Input is unchecked again.

**Comment by YoshiRulz** [comment]
Fixed in 58ff3fa60.
