### ISSUE TITLE
Ocarina of Time Multiworld Bizhawk 2.3 crashes when loading N64 ROM

### ISSUE THREAD

**Issue by Shini1313** [TASVideos/BizHawk#1824]
As the title states, my emulator crashes once I try to load my oot multiworld ROM (or any N64 ROM for that matter). I have Bizhawk 2.3, installed with the [Powershell script for multiworld](https://raw.githubusercontent.com/TestRunnerSRL/bizhawk-co-op/master/bizhawk-co-op.ps1). Opening the Emulator works fine, but when I try to load the ROM it just closes after a few seconds without changing whatsoever before that. If I run it on my PC it works fine (I wanna use it on my laptop), if I run a non-modified Bizhawk it works and if I load a NES ROM it also works. Just with N64 ROMs it crashes. I have looked through other problems and found no answer to this. Hopefully Anyone can help me.

**Comment by zeromus** [comment]
as a test, try with a rom that's not hacked nor launched with some randomizer hacking scripts: do not install bizhawk through multiworld, do not run bizhawk through multiworld, do not use multiworld, do not use hacked roms.

**Comment by Shini1313** [comment]
Okay, so it appears to be a Bizhawk 2.3 related problem. with Bizhawk 2.4 everything works fine, but with Bizhawk 2.3 it doesn't even work with the unmodified version. Since there is no 2.4 Co-op version as far as I know I'd really like to fix the issue for my Laptop. Does anone know what could be the Problem?

**Comment by Shini1313** [comment]
I just tried out the versions 2.3.1, 2.3.2 and 2.3.3. In 2.3.1 and 2.3.2 the crash didn't occur but instead the Window froze and wouldn't take any inputs so I had to close it via taskmanager. in 2.3.3 however everytihng worked fine. Maybe that helps narrowing down the Problem

**Comment by zeromus** [comment]
we can't support old versions. this information may be helpful in case the problem reappears. in the meantime, you say there's no "coop version" for 2.4 yet 2.3.3 works, so why not use 2.3.3?

**Comment by Shini1313** [comment]
I would, but the script only exists for 2.3.0. and as i have understood from the releases page, one shouldn't mix the Bizhawk versions. I can understand that you can't support older versions, thank you for trying to help me anyway.

**Comment by zeromus** [comment]
so try mixing bizhawk versions, what's the worst that can happen?

**Comment by zeromus** [comment]
you should also try changing the n64 gpu plugin and config > display > display method. You can change the n64 gpu plugin probably before booting a rom, so you get a chance to do it before it crashes

**Comment by adelikat** [comment]
In this case, for what you are doing, it would be safe to use 2.4

**Comment by Wollikosi3D** [comment]
Its 2022 and i have the same problem. Have anyone a Idea.

**Comment by YoshiRulz** [comment]
Please open a new issue. Make sure to include: which version of BizHawk you're using, what kind of GPU you have, and whether it affects the vanilla OoT rom or only patched copies.
