### ISSUE TITLE
[Sega 32x]Kolibri Picodrive core movie record problem crashing

### ISSUE THREAD

**Issue by ciccio576** [TASVideos/BizHawk#1826]
when i try to make a 32x kolibri movie in this case bizhawk makes it run by picodrive after i do some rerecording again, bizhawk crashes and closes by itself.

**Comment by adelikat** [comment]
Are you using TAStudio?

**Comment by YoshiRulz** [comment]
Couldn't reproduce this on 2.4, with or without TAStudio.

**Comment by ciccio576** [comment]
I don't use TASstudio because my goal is to create a longplay and I only limit myself to making record movie + savestate rerecording is that when I am at 3 or 4 level when you reload the savestate with record movie activated bizhawk crashes

**Comment by YoshiRulz** [comment]
Okay, this has nothing to do with recording. I hit this intermittently during casual play without savestates. No idea what any of this means but maybe it'll save someone five minutes of gameplay:
![Annotation 2020-02-08 130525](https://user-images.githubusercontent.com/13409956/74085868-44b7ce80-4ac9-11ea-907b-8ac4e676157d.png)

**Comment by ciccio576** [comment]
then I went to see it and it practically happens between the seventh and the eighth minute and I was at level 3/4 and if I do it intermittently after a freehaw bizhawk and then it closes by itself and if then I restart it with the recorded video if I start from problematic quicksave it shows the desynchronized movements

**Comment by YoshiRulz** [comment]
I can't understand that run-on sentence, but you don't need to provide any more info as I've already reproduced the crash. The only thing left is to wait for the core maintainer to debug it, or a core update, whichever comes first.

**Comment by ciccio576** [comment]
I read that you have fixed the bug but nothing has changed keep crashing if you always record the video at the end of the level "infestation"

**Comment by nattthebear** [comment]
> Bizhawk version used: 2.4.2

As the tag " Repro: Fixed/Added in 2.5 dev" indicate, this fix has not yet made it to a release version and will be released in 2.5.

**Comment by ciccio576** [comment]
thank you so much for your quick reply
