### ISSUE TITLE
"New From Now" suggestion (TAStudio)

### ISSUE THREAD

**Issue by Snodeca** [TASVideos/BizHawk#1828]
I am using the option located at "File->New From->Now" in TAStudio for routing a lot (as can be seen in the image). The only problem with it, is that my folder is a bit all over the place due to how it currently creates files right now:
![unknown](https://user-images.githubusercontent.com/52331547/73594395-14d75c80-4506-11ea-98cd-9dabdfe999ac.png)

It does this because whenever I use the "New from now" option, it keeps creating the same files but adds a ".nfn" extension. This is incredibly annoying because it ends up all over the place and makes it super unorganized. In the image, I would only need one of each ID (0001, 0002, etc), but I have a lot of random unnecessary files thanks to this. 

What I would suggest is that it would instead, when you first create the .tasproj with New from now, that it asks what you want to name that new file instead of just using the current filename and add .nfn before .tasproj. This would make it much easier to organize everything.

**Comment by adelikat** [comment]
This has been fixed with the file extension redundancy fix awhile back
