### ISSUE TITLE
[Mgba core] Unable to save state to [file location] while recording movie

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#1833]
While testing for desync issues with mgba, I tried making a save state and it just said unable to save state. I have also verified its mgba by testing the n64 core and that one worked.

Game Im using is lego star wars ii the original trilogy gba. Im not sure if it matters, but I doubt it.
Using commit fd06504
To reproduce:

Load rom
Record movie
attempt to save state
failed message

**Comment by Spikestuff** [comment]
Followed the exact same steps to the exact same commit. Fresh Install.

- Using the same commit.
- Using the exact same game.
- Recorded a Movie.
- Dropped a Save.
- Loaded the Save 5 times.
[Here's the input file with the 5 rerecords](https://github.com/TASVideos/BizHawk/files/4147016/wtarsarsii.zip)

**Comment by InfamousKnight** [comment]
Well, I don't know what else to do other than make a video of it. I didnt touch any of the code(I used appveyor build), and it doesnt save state while recording a movie with mgba.

Is anyone else having this problem?

**Comment by zeromus** [comment]
delete your ini file, you probably have some wrecked paths. or instead of that you could use process monitor to watch where the messed up files are attempting to go

**Comment by InfamousKnight** [comment]
Now this is getting weird.. On commit 16045e3 input doesnt even work. It would display, but not register.

Lego star wars ii gba seems to be exclusive when it comes to save state issues. Maybe its the rom? Because spyro season of flame works(save state wise), but no input there either.

**Comment by Spikestuff** [comment]
So you're now talking about **a different issue**... this actually exists on that build and current build but that's besides the point that is different issue to this issue thread.

To repeat what zero asked for you which you didn't answer.
For the previous specific build to this issue ([fd06504](https://github.com/TASVideos/BizHawk/commit/fd06504882fa0317bf59ec447ea8a18b7957d1ac)) did you create a fresh install or was it overwriting previous files?

Cause I can tell you again for a fact that there is no error on my end with load/save states on that commit on **a fresh install**.

**Comment by InfamousKnight** [comment]
I didnt find any ini file, but a config file. I deleted that one. And what do you mean by fresh install? Fresh install of windows 10?

**Comment by YoshiRulz** [comment]
Clone the repo again instead of pulling or checking out. Windows Explorer hides file extensions by default, the option is in the ribbon under `View` > `Show/hide`.

**Comment by InfamousKnight** [comment]
Yeah, I found the file. Im using a European rom, so that might be the problem? Spyro season of flame works. So I guess I have the bios and rom messed up.

Well, I think this issue can be closed now.

**Comment by InfamousKnight** [comment]
In case anyone is interested in knowing, the cause was apparently file path being too long. Renaming the files to be shorter fixed the issue.

**Comment by YoshiRulz** [comment]
Both NesHawk and mGBA were fine with opening a rom at the longest path I could make at 246 chars.

**Comment by InfamousKnight** [comment]
I dont know then. I just renamed the file to something shorter and it
worked.  You could make it longer than 256 by making more folders. I didnt
do that, as mine were just in documents folder on windows 10. I could make
video proof on my end if anyones interested.
