### ISSUE TITLE
[TAStudio] "Show Player #" behavior is not intuitive.

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1837]
Affects latest master ba7fd37ce834b45d2ce9bc026cf313611fe73527 .

The "Show Player #" menu options in the Columns menu toggles all inputs for that player in the input roll. The menu items always start as checked a well, which can lead to this behavior:

![yB2agJWixZ](https://user-images.githubusercontent.com/1929934/73919572-a7665b80-4878-11ea-8d21-de3b0b80910e.gif)

Player 2 has no inputs enabled, but "Show Player 2" is checked. Unchecking it causes all of player 2 inputs to become _enabled_. What it seems like the options should do is act as a kind of master on/off switch for those inputs, so regardless of which inputs for player 2 are enabled, if the master switch is flipped off, they don't get shown. However, it will simply flip all of the input states for player 2 instead.

The above issue could be resolved by changing:

**TAStudio.MenuItems.cs**
```cs
SetUpToolStripColumns() {
// .....
    if (playerMenus[i].HasDropDownItems)
    {
	    var item = new ToolStripMenuItem($"Show Player {i}")
	    {
		    CheckOnClick = true,
		    Checked = true
	    };
// .....
}
```

to

```cs
SetUpToolStripColumns() {
// .....
    if (playerMenus[i].HasDropDownItems)
    {
	    var item = new ToolStripMenuItem($"Show Player {i}")
	    {
		    CheckOnClick = true,
		    Checked = playerMenus[i].DropDownItems.OfType<ToolStripMenuItem>().Any(mi => mi.Checked)
	    };
// .....
}
```

This will stop the situation where a .tasproj with no input for a pad enabled will show "Show Player 2" as checked, thus acting in reverse. If there are some inputs enabled and some not, however, the toggle behavior remains.

**Comment by Meerkov** [comment]
I'm using 2.4.2 and it still has this behavior, which I also find counter intuitive.
