### ISSUE TITLE
Firmware Renaming Schema Suggestions and Feedback

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#1840]
In reference to this:
https://github.com/TASVideos/BizHawk/issues/1736

I wanted to ask if a renaming scheme for BizHawk's Firmware Files could be suggested or implemented by myself.

Suggested Folder Organization:
All in One Folder
Separate Folder Per System.

I prefer the All in One Folder option myself as the users, generally don't need to go in here except to drop in Firmware manually if they are not using the Import Firmware Function.

The rename Schema I am suggesting as follows:
SNES_SGB.SFC
SNES_CX4.ROM
SNES_DSP1.ROM
GBA_BIOS.ROM
C64_Kernal.Bin

The main Schema I am after or suggesting is "System Name *SEPERATOR* Function of File.Extension of File"

So we could have
SNES_CX4.ROM
Or
SNES-CX4.ROM
Or
SNES - CX4.ROM

I personally like the System_Function.Extension naming schema myself.

It should be easy to implement this as well.  I did self-assign this issue.  I wanted to gather some feedback before I do this.

I would also like to suggest Merging the Saturn US and EU Firmware Entries as well.  As they share the same SHA1.

The GameBoy BootROM does use this naming Schema already:
GB_boot_ROM.gb

Though I would like feedback on if it should be written as:
GB_Boot_ROM.gb
Or
GB_BootROM.GB

I await suggestions and comments on this.
I do not want to implement something this drastic and standardizing things without some feedback first.

**Comment by hegyak** [comment]
I wanted to add that the 32X and TI83 BIOS Files do use this Naming Schema already.  Or something Similar to it.

**Comment by Spikestuff** [comment]
I agree to this for something like PlayStation as well.

Personally I dislike the naming for the bios as "ps-30a/ps-30e/ps-30j" especially when used for submissions as quick reference and you have to remember what you have. This is only if you're using the Organize function of the Firmware section of Hawk to rename everything.
Yes it stands for PlayStation v3 BIOS but that naming convention is less common than "scph550x" in this case following your example it would be "ps_scph550x".

I do prefer all in one folder with their system name at the start as you showed with the snes example with the underscore, having a choice for both would help those that want to be a bit more organized in separating systems by folder (I will admit when all the firmwares are accounted for it is a mess keeping it all segregated in a single place).

**Comment by hegyak** [comment]
That does raise an important question.  Would these renamed BIOS/Firmware Files affect/impact TAS Submissions?  I don't think it would, but I wanted to check on that issue.

**Comment by YoshiRulz** [comment]
The movie file contains the firmwares' hashes, not their filenames.

**Comment by hegyak** [comment]
Sorry it took me a while.  Got distracted and doing other things.  Figured I'd make a Pull Request.  So others can review and discuss and edit as necessary.

https://github.com/TASVideos/BizHawk/pull/2204
