### ISSUE TITLE
Gambatte movies made in TAStudio get the wrong cyclecount

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1845]
Happens in the latest devbuild. When exporting a movie file from a TAStudio project, the program asks to process all frames in order to get the total cyclecount, but it ends up with not counting the last 2 frames (sometimes 1 frame). So when you play back a .bk2 movie file, it will give the warning about the cyclecount in the movie file not matching the emulated cyclecount.
Note that the cyclecount got when playing back a .bk2 movie file is accurate, because it matches the same value got by launching the Lua function emu.totalexecutedcycles(), given that BizHawk is set to automatically pause the movie after finishing playback.

**Comment by vadosnaprimer** [comment]
There's no good way to do this from tastudio yet, so just resave the exported movie.
https://github.com/TASVideos/BizHawk/commit/a8472a77f396b9dc1bdd29f5c0c9e2c6fedc7e0f
