### ISSUE TITLE
[GBHawk] Harvest Moon 3 GBC (USA) wrong platform + TAStudio bug

### ISSUE THREAD

**Issue by ViGadeomes** [TASVideos/BizHawk#1854]
Hello, on both core, BizHawk 2.4 and the current version recognize Harvest Moon 3 GBC (USA) (SHA1: 5313C62C51B9B5417F764FE67B687F403F9765BB) as a GameBoy game but loads it with the GBC firmware when you create a movie or a *.tasproj. Even when you force the GBC mode, the header of the movie will be "Platform GB".
Also in TAStudio with GBHawk: sometimes in the case of a mix of loading frames (red frame) and playable frames (green frames) like red,green,red,green etc... You can have a shift from one frame so that the red frames are actually playable frames and green frames are load frames. It also happens to me all the time on "Asterix (UE) (M5) [!].gb" (SHA1: 7D4CA6925826C0FFCA3E3004479B5E9A5B6B311B). I don't know it it comes from the core or TAStudio itself.

**Comment by TiKevin83** [comment]
was this tested in gambatte interim before or after yesterday's overhaul

**Comment by ViGadeomes** [comment]
I just tested on Gambatte right before posting the issue

**Comment by TiKevin83** [comment]
Is it just the platform autodetect is broken and you can still force the game to run in GB/GBC/GBA-as-GBC as desired?

**Comment by ViGadeomes** [comment]
When I create a TAS the platform will be GB even if i forced to play it in GBC mode in GB -> Settings ->  Sync Settings -> Console Mode: GBC

**Comment by TiKevin83** [comment]
On my end when I select GB the game loads with a screen telling me that the game is only compatible with the GBC, and when I switch to Console Mode: GBC and reboot the core I get the game loading with appropriate colors, etc.  If you're referring to the emulator saying GB (interim), that shouldn't be a worry, all GB+GBC have that regardless of accuracy/colors/console sync.

**Comment by alyosha-tas** [comment]
I changed lag detection on GBHawk to be more representative of real input frames. It still won't be perfect due to different frame definitions, but you won't see red frames that are actually input frames now.

**Comment by ViGadeomes** [comment]
Ok thanks. And about the GBC recognization when creating a movie ?
