### ISSUE TITLE
Jetsons, The - Cogswell's Caper freezes

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#1856]
Stage - Rock Concert Hall. Game freezes after George fly a few enemies. Savestate attached. This is happening only on the QuickNES core. In Bizhawk 2.4 and Developer Build problem also remains.
[Jetsons, The - Cogswell's Caper.QuickNes.QuickSave1.zip](https://github.com/TASVideos/BizHawk/files/4227404/Jetsons.The.-.Cogswell.s.Caper.QuickNes.QuickSave1.zip)

**Comment by alyosha-tas** [comment]
added to the quicknes blacklist. The game will load with neshawk now, thanks for the report.
