### ISSUE TITLE
Different resolutions after rendering to AVI

### ISSUE THREAD

**Issue by Som3one1** [TASVideos/BizHawk#1860]
For example, I recorded game to AVI from beginning to the end and BizHawk split all movie into parts (that's okay, I can merge videos together, I thought, but some parts of movie recorded in different resolutions )

1st part in 320x224, 2nd part in 256x224...

I can't merge these files in VirtualDub because of different resolutions

What I have to do? Please, help!

**Comment by Spikestuff** [comment]
Quick and Dirty:
File > AVI > Config
Resize Video to whatever gameplay is.
Done.

**Comment by Som3one1** [comment]
Thanks! It works! If you know other methods, tell me, I'm interested)

**Comment by vadosnaprimer** [comment]
Enable capturing OSD in AVI menu, that will make it record video from the client area of bizhawk as opposed to internally emulated framebuffer. You can set exact size of it in config - display.

**Comment by Som3one1** [comment]
Thank you!

**Comment by zeromus** [comment]
avisynth scripts...

**Comment by Som3one1** [comment]
> avisynth scripts...

How?

**Comment by zeromus** [comment]
yes. read the manual, apply ingenuity.

**Comment by Spikestuff** [comment]
An AVISynth script would basically look like this (aiming for 1080p60fps):
("part1.avi").PointResize(320*6,224*6).LanczosResize(1440, 1080) + ("part2.avi").PointResize(256*6,224*6).LanczosResize(1440, 1080) --excetera, excetera.
