### ISSUE TITLE
Bizhawk failing to detect prerequisite "Visual C++ 2012 Runtime" despite it being installed

### ISSUE THREAD

**Issue by buffaloburrow** [TASVideos/BizHawk#1864]
Title sums it up. Not sure what to do, closed issues suggest I uninstall all redistributables but I don't know how to do that. Is there a newer version I'm unaware of? Troubleshooting emulator issues all day.

- BizHawk 2.4; Win10 Pro 1909; Intel

No screenshots because they're irrelevant.

**Comment by YoshiRulz** [comment]
Copied from TASVideos/BizHawk-Prereqs#4:
> EmuHawk does not depend on MSVC 2012 and never did. This is a typo in the dependency checker, the actual dependency is on MSVC 12.0 (2013).

You can check which versions are installed in the Win10 Settings app (I think it's labelled `Programs and Features`). The prereq installer linked in the readme should install the three versions required by BizHawk 2.4.

**Comment by buffaloburrow** [comment]
It worked. ...Why is this typo still there? lol

**Comment by YoshiRulz** [comment]
It's been removed, don't worry.

**Comment by Geemer** [comment]
It really hasn't...

**Comment by YoshiRulz** [comment]
I was the one who noticed and fixed the typo. The next version of BizHawk will have about half as many hard dependencies, and its prereq checker will have no such typos.

The version of the prereq installer linked in the readme, [`2.1`](https://github.com/TASVideos/BizHawk-Prereqs/releases/tag/2.1), is an older version which will still give you MSVC 12.0 as it always has. I can't possibly be any clearer about that.

**Comment by Geemer** [comment]
My bad, sorry. It's been a weird week.
