### ISSUE TITLE
[mGBA] Add sync setting to completely disable the RTC

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#1870]
> &lt;endrift> This is actually important because Ruby/Sapphire speedruns use a dead battery

**Comment by Real96** [comment]
Would be great if also hours:minutes:seconds are editable

**Comment by Real96** [comment]
The last commit doesn't read the RTC anyway :/ it read system clock, bot True and False

**Comment by YoshiRulz** [comment]
Does this require pulling from upstream?

**Comment by vadosnaprimer** [comment]
No it needs someone to test if setting `rtcEnabled=0` in the db file will do the required thing in-game. Then we can expose it as a syncsetting. Apparently it also involves [enabling overrides](https://github.com/TASVideos/BizHawk/issues/1112#issuecomment-460059738) for that game.

**Comment by Real96** [comment]
> No it needs someone to test if setting `rtcEnabled=0` in the db file will do the required thing in-game. Then we can expose it as a syncsetting. Apparently it also involves [enabling overrides](https://github.com/TASVideos/BizHawk/issues/1112#issuecomment-460059738) for that game.

I can test if you tell me which build i need to download!

**Comment by vadosnaprimer** [comment]
It should work in official releases.

**Comment by shenef** [comment]
did some quick testing on 2.5.0 using JP Boktai 1 and it didn't disable RTC using this entry:
`C51AD84E9403DB94CD18A14AC72F8367B52A0D7F	!	Bokura no Taiyou - Taiyou Action RPG (Japan)	GBA		rtcEnabled=0;mgbaNeedsOverrides=1`

**Comment by vadosnaprimer** [comment]
@shenef How do you test?

**Comment by Real96** [comment]
> @shenef How do you test in-game?

In pokemon ruby/shapphire version you just need to check the initial seed ram address. If itbis dofferent from 0x5A0 it means that battery isn't dead and it is not working

**Comment by shenef** [comment]
@vadosnaprimer When the battery is dead on the actual cartridge, before reaching the title screen the game will ask for the time and date every time the game is started. So that's what i looked for.
You will get it asking for the time and date on the first boot of the cartridge/rom because of the initial setup

**Comment by vadosnaprimer** [comment]
Does this work in actual mGBA?

**Comment by Real96** [comment]
> Does this work in actual mGBA? If yes, which options make it work?

I've just tested it in last mgba commit (4ecf64a) and it works. If you go to Tools > Game Overrides and disable Realtime Clock , battery will be dead.

![image](https://user-images.githubusercontent.com/20956021/102722640-bc1dd780-4302-11eb-9a11-03f96619442a.png)

**Comment by Real96** [comment]
Tested in last Bizhawk commit (3d84812), with Pokémon Ruby, it doesn't work.

**Comment by shenef** [comment]
Unfortunately i can't replicate the correct behavior on mGBA for Boktai. Instead of the game always asking for date and time, it seems to feed the game an empty value or something which makes it show 2003-07-17 00:00 (the release date of the game).

**Comment by vadosnaprimer** [comment]
Do any other mgba override settings work in bizhawk, through db file editing?

**Comment by shenef** [comment]
Just checked the code to see if there are other potential options i could test. I'm not very familiar with coding but if i understood correctly, then all options need the override setting to work, yet no game in the db file actually has the override setting?
https://github.com/TASVideos/BizHawk/blob/38838fa3c1396e8e1a037595517d4820ed44f93b/src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.cs#L191-L198

As far as i can tell there are no additional override settings in mGBA that aren't already used by several games in the db file.

**Comment by YoshiRulz** [comment]
I'll ask again: can this feature be implemented without pulling from upstream, or should we postpone it until then (which should be next month)?

**Comment by vadosnaprimer** [comment]
It shouldn't depend on upstream, I something on our side isn't wired up.

**Comment by nattthebear** [comment]
> all options need the override setting to work, yet no game in the db file actually has the override setting?

Yes, I believe that's correct.  The comment in the code you pasted explains it:  mGBA has its own builtin overrides, which already handle most regular cases fine.  But our gamedb is actually from old VBA garbage, which needs extra overrides to handle things that might not want or need overrides in mGBA.  So something like `rtcEnabled=0;mgbaNeedsOverrides=1` should do the trick.  Don't know why it's not working; presumably some issue in passing data to the core that isn't working out.

**Comment by Real96** [comment]
> Hopefully this is fixed in #2937
> 
> TESTERS NEEDED!
> 
> Just grab this artifact
> https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/40861997/artifacts

It seems to works perfectly!

**Comment by shenef** [comment]
Tested all Boktai games and it seems to work as expected in normal play and when using TAStudio.
