### ISSUE TITLE
Cut Off Audio in HH: GBC GB

### ISSUE THREAD

**Issue by Bloopiero** [TASVideos/BizHawk#1874]
In Hammerin' Harry: Ghost Building Company for gb, a lot of the sound effects are cut off too early and are much softer than usual, including the 'Let's Get Busy!' at the beginning of each level, the 'ouch' when you die, and whatever sound he makes when you press continue after a game over; it almost seems like they're missing an audio channel. This is only true for GBhawk, not Gambatte or, oddly, SubGBhawk.

**Comment by alyosha-tas** [comment]
Are you using the dev build? I updated sound recently. SubGBhawk uses GBHawk for sound,so they should sound the same.

**Comment by Bloopiero** [comment]
@alyosha-tas, I tried the dev build, and it fixes most of the cutting problems; however, they're still _incredibly_ soft compared to an actual gb, maybe even softer than they were before. gbhawk and subgbhawk are consistent, though.

Also worth noting is that everything I've said holds true for the game's direct sequel, Daiku no Gen-san - Robot Teikoku no Yabou; except in that game, these sound effects are now drenched in static (which also isn't present on an actual gb).

**Comment by alyosha-tas** [comment]
Alright that makes more sense, I'll take a look at it, thanks for the report.

**Comment by alyosha-tas** [comment]
I'm going to add this to the existing issue #1227
