### ISSUE TITLE
Hex Editor scrolling broken in Dev Build

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1887]
Scrolling through a domain in hex editor is broken. This is due to this line in `HexEditor`:
https://github.com/TASVideos/BizHawk/blob/33a14327b79afc489f77f3f3a1324e9455e658fe/BizHawk.Client.EmuHawk/tools/HexEditor/HexEditor.cs#L615

This expects references to vals to start at 0. However in `BulkPeekByte` we have:
https://github.com/TASVideos/BizHawk/blob/9dd9b4cc0d6576d48812edf6d8b7d2732a9186c4/BizHawk.Emulation.Common/Base%20Implementations/MemoryDomain.cs#L119-L122

This has references starting at the first address, not 0. So this breaks as soon as you start scrolling and the first address is not zero anymore.

I'm not familiar with the new inner workings of this stuff so I didn't try to fix it.

edit: formatting --yoshi

**Comment by YoshiRulz** [comment]
FYI you can link to source in Markdown by selecting the line numbers from the margin and choosing `Copy permalink` from the overflow menu that appears. Just make sure you're looking at a commit and not a branch, otherwise it's not a permalink and GitHub won't parse it.

**Comment by adelikat** [comment]
Fixed
