### ISSUE TITLE
[DSHawk] The Lid input in TAStudio crashes bizhawk

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1890]
With the Master, if you use the input of Lid (P), and let emulation play past it, the emulator just crashes.

I do not know if this is a firmware related issue, but I tried to see if it would happen with no firmware files inside the folder and it still happens.

the game I was testing was Drawn To Life Spongebob Edition.

**Comment by vadosnaprimer** [comment]
@SuuperW ping

**Comment by SuuperW** [comment]
fixed
