### ISSUE TITLE
[DSHawk] Touch Screen Calibration is off

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1891]
For Spongebob Drawn to Life, the touchscreen is not accurate in the drawing area, it seemed just fine in the title screen.

the mouse shows where I clicked, and the dot shows where input was drawn:

![unknown](https://user-images.githubusercontent.com/44628443/77238112-06bbc900-6ba4-11ea-9fc2-90e0ab803e18.png)

**Comment by vadosnaprimer** [comment]
@SuuperW ping

**Comment by SuuperW** [comment]
It works for me, I even tested on that game and everything is working as it should.
I did recently make some changes to how that code works, though. Try again and see if it's still messed up for you.

**Comment by zeromus** [comment]
FYI the contents of the firmware file can affect touch screen calibration. It seems pretty unlikely that it was perfect in the title screen and messed up here, but it is not impossible.

**Comment by EZGames69** [comment]
I do remember having some issues with incorrect firmware in my folder when I tested this, but I did remove those files from that folder and I still got that issue.

I'll see if I can fix the firmware issue and see if that fixes it.

**Comment by EZGames69** [comment]
Ok so yeah, it looks like it's fixed in the latest master now.

I am not sure if this would cause issues with firmware stuff in the future though.
