### ISSUE TITLE
BizHawk won't start on Windows 10.

### ISSUE THREAD

**Issue by antonw51** [TASVideos/BizHawk#1892]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheat sheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded ROM's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
So I like Old games but I rarely have the console or game for it. so I found this emulator called _BizHawk_ and so I used it for playing the games but today when I wanted to play I wasn't able too due to it not launching I have Windows 10 I don't have any problems

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.3.2; Win10 Pro 1903; Intel/AMD
- BizHawk dev build at 92847b1d1; Win10 Home 1809; AMD/NVIDIA
- BizHawk 2.3.2; Fedora 30; AMD/AMD
- BizHawk 2.3.2; macOS 10.15; Intel/AMD
- BizHawk 1.13.2; Win7 SP1; Intel/NVIDIA

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

### Event Viewer Info
in other issues, I saw the event viewer so I will give it here

Application: EmuHawk.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Reflection.RuntimeAssembly.nLoadFile(System.String, System.Security.Policy.Evidence)
   at System.Reflection.Assembly.LoadFile(System.String)
   at BizHawk.Client.EmuHawk.Program.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Exception Info: System.IO.FileLoadException
   at BizHawk.Client.EmuHawk.Program.SubMain(System.String[])
   at BizHawk.Client.EmuHawk.Program.Main(System.String[])

**Comment by zeromus** [comment]
You didn't say that you'd run the prerequisite installer, so I assume you haven't.

**Comment by YoshiRulz** [comment]
Security garbage with a `FileLoadException`? Could be 1. you haven't extracted the zip; 2. Windows security is being annoying, extract BizHawk somewhere else or use `Properties` > `Security` to give yourself perms; or 3. antivirus thinks we're shady.

Also, those host env. strings are examples. Other than that, a valiant attempt at filing a bug report!

**Comment by NarryG** [comment]
For a while, I was running the WhackMOTW code from Bizhawk in my project and I found that it was making certain antiviruses extra sensitive (it'd eat the assemblies at whack, causing LoadFile to throw various exceptions ranging from FileNotFound to NotSupported).
As of commit  https://github.com/TASVideos/BizHawk/commit/6ea20e9e9b74bcc767ba55f7aaef5bc4fdc83b36, I'm fairly sure the WhackMOTW code in Program.cs should no longer be needed.  Allowing remote sources should allow LoadFile() to load assemblies that still contain a MOTW.

**Comment by antonw51** [comment]
Thanks, @YoshiRulz I Tried Extracting Elsewhere And it Did Fix The Problem Now I'll go back to playing my games
