### ISSUE TITLE
[DSHawk] AVI writer dumps at 2x speed if Alternate Sync is checked

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#1893]
Title says all.
If you uncheck the Alternate Sync box, it dumps at normal speed.

**Comment by vadosnaprimer** [comment]
Sounds like it only outputs half the sample count that it's meant to output? Alt sync is tied to audio, and if audio *sounds* correct, then it's an issue with the samplerate or something. @SuuperW

**Comment by EZGames69** [comment]
The audio does not sound correct, it's twice as fast as well is higher pitched (and slightly quieter as well it seems)

**Comment by SuuperW** [comment]
I didn't get this problem, but I have fixed an issue with the audio. See if you still encounter this problem on the latest version.

**Comment by Sonia-7** [comment]
It's indeed fixed now, thanks.

**Comment by EZGames69** [comment]
I have tested with the new build and the problem looks fixed now.  I tested both with alt sync and no alt sync, and even with and without firmware enabled.
