### ISSUE TITLE
Unprotected Error when calling "joypad.set()" on MupenPlus

### ISSUE THREAD

**Issue by campbell000** [TASVideos/BizHawk#1897]
### Summary
My primary use case is running N64 games using the MupenPlus core. I upgraded from 2.2.1 to 2.4, and my previously-working scripts now result in the following error:

```
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_resume(lua_State* , Int32 )
   at BizHawk.Client.EmuHawk.EmuLuaLibrary.ResumeScript(LuaFile lf)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass57_1.<ResumeScripts>b__1()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)
```

I've narrowed down the cause to the joypad.set method. It seems like the following throws the exceptions:

```
        local input = {}
        input['Start'] = "True"
        joypad.set(input, 1) -- throws exception, but used to work in 2.2.1
       
        input['Start'] = 1
        joypad.set(input,1) -- throws exception, but is supposed to work according to documentation

        input['Start'] = true
        joypad.set(input,1) -- no exceptions, but does nothing
```

Any idea what I'm missing here? I think this is a regression or a bug, since my scripts USED to work in 2.2, but no longer work in 2.4. You can test this by using the n64 core and pasting the snippet above into a lua script. Hopefully you see the errors for yourselves. I'm on latest version of windows 10

**Comment by adelikat** [comment]
What has changed since 2.2 is config -> customize -> advanced -> Lua engine
Nlua is the default, if you switch back, does that work?

**Comment by campbell000** [comment]
> 
> 
> What has changed since 2.2 is config -> customize -> advanced -> Lua engine
> Lua+LuaInterface is now the default, if you switch back to Nlua+KopiLua, does that work?

I actually have always used the Lua+LuaInterfce option since that's the only one I could get to work with sockets. But changing it, I get:
```
NLua.Exceptions.LuaScriptException: table
```

Note that I've found that the following DOES work:
```
        local input = {}
        input['P1 Start'] = true -- Note the 'P1'
        joypad.set(input) -- Note the lack of controller 2nd argument
```
The docs DO mention this as an alternative, but I still think that something isn't right

**Comment by adelikat** [comment]
the other one "should" work, I don't know what would have changed to break it.

However, I do dislike supporting that one, feels like a hack, heh.

**Comment by campbell000** [comment]
Any ideas where in the code to look? I can take a crack at a fix. Never contributed but im a dev in other industries...so maybe i could help?

**Comment by adelikat** [comment]
The code that is in charge of the joypad lua methods can be found here: https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Client.Common/lua/EmuLuaLibrary.Joypad.cs

**Comment by YoshiRulz** [comment]
It'll probably be helpful to breakpoint here:
https://github.com/TASVideos/BizHawk/blob/6d5c4442524ed643a182854bb100da47366c932e/BizHawk.Client.Common/Api/Classes/JoypadApi.cs#L57

**Comment by campbell000** [comment]
I think I have a fix, seems to be working OK. My scripts now work, and I have a pull request here: https://github.com/TASVideos/BizHawk/pull/1898.

Let me know if there's something I need to do to this PR. I didn't see any unit tests or PR instructions, but maybe I didn't look hard enough :0

**Comment by adelikat** [comment]
PR merged, closing this ticket

**Comment by campbell000** [comment]
Wow, didn't realize my usage was the legacy way (actually assumed the "P1" syntax was legacy). Thanks for the clarification, regardless!
