### ISSUE TITLE
Allow customizable NDS screen gap

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1900]
Spikestuff mentioned MelonDS already has this, so hopefully it's just a matter of wiring up BizHawk to do it.

**Comment by zeromus** [comment]
this should be done inside the frontend, not inside melonds

**Comment by Spikestuff** [comment]
Just to point out, @adelikat has added the functionality of manual customization gaps compared to melon's set values (0, 1, 8, 64, 90 & 128).

However, I hope whilst it's still being worked on that it's something that's doesn't appear whilst dumping or taking a screenshot as it's currently set at the moment. If that's possible.

**Comment by zeromus** [comment]
FYI, @adelikat I had always planned for this to be done in displaymanager.  It has the ability to resize intermediate buffers and blit chunks all around it while filling with blackness. WITHOUT copying 256x192 int[] buffers all around. And the frontend already knows how to ignore displaymanager when dumping stuff.

**Comment by adelikat** [comment]
This is done in displaymanager now, closing this ticket

**Comment by Darxoon** [comment]
It says this is completed but i can't find anything about this. Is customizable DS screen gap actually a thing?

**Comment by YoshiRulz** [comment]
In current builds, it's `NDS` > `Settings...` > `Non-Sync Settings` > `Screen Gap`.

**Comment by Darxoon** [comment]
Oh, I see why i didn't find that, the NDS settings page is almost unusable on linux lol

Still thanks though :D
