### ISSUE TITLE
Can't increase speed

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1901]
Speed doesn't increase when I press the appropriate hotkey (equals). The Fast Forward and the Turbo hotkeys still work, so this can't be a performance issue on my part.

The issue started whith BizHawk 2.4. My OS is Windows 10 Pro.

**Comment by zeromus** [comment]
Delete your ini file to undo the settings changes you made which broke this for you. or disable vsync throttle.

**Comment by Reinc01** [comment]
Disabling VSync throttle did not help, but disabling VSync did help.

**Comment by zeromus** [comment]
Are you sure you disabled vsync throttle? If you clicked it once, you didn't do anything but choose it again.

**Comment by Inspirateur** [comment]
A friend of mine had the same issue and apparently it was caused by him streaming on discord. Probably also related to vsync but if this happens while streaming with discord you might want to try turning off the stream.

**Comment by Reinc01** [comment]
I wasn't streaming.
