### ISSUE TITLE
Screenshots issue when Scanlines filter is enabled

### ISSUE THREAD

**Issue by lucameat** [TASVideos/BizHawk#1902]
In the Display Configuration I enabled the Scanlines scaling filter because I love that old style effect, but I noticed an issue when taking screenshots on the following platforms: Atari 2600, ColecoVision, Mattel Intellivision, Nintendo NES, Nintendo SNES, Sega Master System, Sega Mega Drive.
When I take a screenshot on these platforms (by pressing the F12 key), the Scanlines effect seems to be taken into account in some way. As a result, I get screenshots like this
![img1](https://user-images.githubusercontent.com/43494463/77817491-6d247800-70cb-11ea-8eb5-e19408c62696.png)
instead of "clean" screenshots like this
![img2](https://user-images.githubusercontent.com/43494463/77817488-6c8be180-70cb-11ea-8baa-bc71e57e46c0.png)
(got after temporarily disabling the Scanlines effect).
On all the other platforms the issue doesn't occur.

**Comment by zeromus** [comment]
This doesn't really make sense to me. It should be the same as ctrl+C, which is a "raw" screenshot. That should take effect before the filters are applied. Yet I went all the way back to 1.11.7 and it was doing the same thing as you found.

**Comment by YoshiRulz** [comment]
It's also a little strange that it only affects some cores, but that can be explained away as "filters == jank".

**Comment by zeromus** [comment]
I don't really believe it doesn't happen on some cores. I tried one randomly OP didnt list (gameboy) and it happened there too. Same on PCE-cd. I don't see why it wouldnt apply to every console. It may just be a mirage to believe otherwise since certain resolutions look differently when the scanline filter gets munged down by whatever mysterious process is doing that

**Comment by lucameat** [comment]
I just tried with an Atari 2600 game.
This screenshot is taken with the Scanlines effect enabled
![Kangaroo 2020-03-28 08 39 48](https://user-images.githubusercontent.com/43494463/77818056-cd1d1d80-70cf-11ea-9e7f-69081d2af5cc.png)
and this without Scanlines effect
![Kangaroo 2020-03-28 08 39 59](https://user-images.githubusercontent.com/43494463/77818057-cdb5b400-70cf-11ea-9da1-4218955914a1.png)
Notice that the ratio is also different.
Ctrl+C and Ctrl+Shift+C give me the same result as F12.
The following is a Game Boy game screenshot taken with the Scanlines effect enabled
![Donkey Kong (World) 2020-03-28 08 49 42](https://user-images.githubusercontent.com/43494463/77818241-32254300-70d1-11ea-8d79-1fe63cd8a39f.png)
and this is a PCE game screenshot also with the Scanlines effect enabled
![Xevious - Fardraut Densetsu (J) 2020-03-28 08 52 34](https://user-images.githubusercontent.com/43494463/77818290-9516da00-70d1-11ea-846d-ee90d3be872a.png)
Both are clean.

**Comment by zeromus** [comment]
it's a mirage and moot because I just fixed it
