### ISSUE TITLE
Hex Editor causes IndexOutOfRangeException sometimes

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#1903]
Everytime i try to use or scroll down Hex Editor window the app crashes.
These are the two errors i'm getting:
https://pastebin.com/PGY3sZCF
https://pastebin.com/LuDX9y6T

I'm on Win10, using last BizHawk commit

**Comment by Real96** [comment]
The same thing happens with mGBA too. Do have it to open another issue?

**Comment by YoshiRulz** [comment]
No, but more details can't hurt.

see also #1887 @adelikat

**Comment by Real96** [comment]
> No, but more details can't hurt.
> 
> see also #1887 @adelikat

I saw this commit that should have fixed the proble. But i'm using last compiled commit, so it seems that the problem is still existing. It happens the same way as DS, just clicking/trying to use/scrolling down makes the app crash. I can add the two errors i get

**Comment by Real96** [comment]
GBA errors
1st error window: https://pastebin.com/PnTTb8sn
2nd error window: https://pastebin.com/FqRUK4dd

**Comment by Real96** [comment]
Commit #c3389f1 seems to have fixed the main crash error for both GBA and DS cores, Hex Editor is usable now.
There is still one problem:
[GBA/DS] Switching to 2byte (Option > Data Size > 2 Byte) app crashes (https://pastebin.com/zRBjvykM - https://pastebin.com/f1Y3vBqg). This doesn't appen with 1 byte and 8 byte
