### ISSUE TITLE
Ctrl+Shift+C doesn't work

### ISSUE THREAD

**Issue by lucameat** [TASVideos/BizHawk#1905]
I noticed that the key combination Ctrl+Shift+C (for client screenshots) do nothing, while if I select it from the menu it works. I tryed to change the combination to Shift+C (from the hotkeys configutaror) and it works. Then I tryed to revert the combination to Ctrl+Shift+C but what I get is
![client](https://user-images.githubusercontent.com/43494463/77843764-a11d9d00-71a0-11ea-9012-d8784a72ff9f.png)
The C key is not taken into account any more.

**Comment by zeromus** [comment]
try another keyboard. you probably have a sucky keyboard that can't hit those three keys at once. all that stuff works fine if you have a keyboard that doesnt suck.

**Comment by lucameat** [comment]
Ok. I've had problems like this in the past so I will stay with Shift+C that is working (or maybe I'll change keyboard in the future).
Thanks
