### ISSUE TITLE
Aspect Ratio not maintained in screenshots

### ISSUE THREAD

**Issue by lucameat** [TASVideos/BizHawk#1906]
What about the possibility to maintain the Aspect Ratio in screenshots?
For example, if I take a screenshot of an Atari 2600 game, I get this
![Kangaroo 2020-03-29 09 13 22](https://user-images.githubusercontent.com/43494463/77843907-e1314f80-71a1-11ea-8f61-e518181639cc.png)
while it could be like this
![Kangaroo](https://user-images.githubusercontent.com/43494463/77843919-002fe180-71a2-11ea-9e33-95b55544c247.png)
Maybe as an option?

**Comment by Spikestuff** [comment]
As long as it's a toggle to use I'll agree.
Since personally I don't want a repeat of #1244 where it got implemented (#1205) and then removed.

**Comment by YoshiRulz** [comment]
Ideally `Screenshot (raw)` would be deterministic and not based on Display settings, with things like pixel ratio and Lua graphics only being taken into account for `Screenshot (client)`.

**Comment by zeromus** [comment]
The concept is ill-defined. It is not clear how the raw data should be stretched to the intended aspect ratio. This can ONLY be done with the context of the user's display options and intended view size. You've chosen an example case where it is seemingly obvious how to do this, but it isn't obvious in every case. This toggle would do a crappy job, generally, so we shouldn't have it.

If the raw aspect ratio is so objectionable for atari (as it verily is) then I would suggest a "stretch by 3x in core" option is better, and then fight over whether it should be the default.

**Comment by vadosnaprimer** [comment]
Why not use `Screenshot (client) -> Clipboard`? It does it the way you want, with whatever display config you set.
