### ISSUE TITLE
NDS - LagCount and IsLagFrame setters

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#1910]
the lag frames need setters for this to be a releasable for.  InputCallbacks can throw a NotImplementedException and emuhawk can gracefully handle it, but not the lag setters.  Hopefully this is a super easy thing to set up

public int LagCount
{
	get => GetLagFrameCount();
	set => throw new NotImplementedException();
}
public bool IsLagFrame
{
	get => _IsLagFrame();
	set => throw new NotImplementedException();
}

**Comment by SuuperW** [comment]
These setters have been implemented in commit a57d09f.

**Comment by adelikat** [comment]
You rock!
