### ISSUE TITLE
TAStudio does not load saveram from .tasproj

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1913]
### Summary
I found this is mGBA core while trying to import a SaveRAM-anchored .bk2 movie of the game Shrek 2 (USA, Europe) (SHA1:D3C3201F4A401B337009E667F5B001D5E12ECE83, MD5:9EF8E30824DB751F3D42E048514A3624). I assume it occurs in other games and possibly other cores. It's not necessarily restricted to importing, but that is how I discovered the issue.

### Repro
Using this short example movie: [Shrek 2 (USA, Europe) 4-3.zip](https://github.com/TASVideos/BizHawk/files/4440763/Shrek.2.USA.Europe.4-3.zip)

1. Open and playback the entirety of the attached movie to see how it's supposed to play. The movie should successfully open a player save slot and enter Book 4, Chapter 3.
2. Select `Tools > TAStudio`
3. It will ask if you want to proceed in creating a new project form the current movie. Click 'Ok'.
4. Seek to the last frame of the movie in TAStudio. It should play back the whole movie identically as before.
5. Seek back to frame 0 and play forward from there. The movie will no longer start from SaveRAM and consequentially begin the process of creating a new save slot instead of entering into the save slot that previously existed when the movie started from SaveRAM.

`File > New > From current SaveRAM` within TAStudio has the same problem.

### Host env.
- BizHawk 2.4; Windows 8; Intel/Intel

**Comment by YoshiRulz** [comment]
see also #1593?

**Comment by RetroEdit** [comment]
This is very likely a different incarnation of the same issue. Perhaps I should have commented on the other issue instead of creating a new one (I did see the prior issue before I created this one). I did feel like my reproduction steps would allow more convenient testing, and this confirms something occurs on a newer version.

**Comment by adelikat** [comment]
Worked for me.
I verified that the attached movie has MovieSaveRam.bin.
 I took the .bk2 and I opened it in the traditional manner, verified it loaded the save ram
I opened tastudio and confirmed I wanted to covert it.
I opened the resulting .tasproj file it saved and confirmed it contains MovieSaveRam.bin

**Comment by RetroEdit** [comment]
I started with a clean install of BizHawk and reproduced. @adelikat You didn't explicitly mention: did you try to play it back in the manner I described in the original issue?

**Comment by RetroEdit** [comment]
After some discussion on IRC, this appears to be the same issue as #1593. I have closed this issue because it is a duplicate and I will add relevant details there.
