### ISSUE TITLE
BizHawk 2.x Genesis load lag issue

### ISSUE THREAD

**Issue by grifmoney** [TASVideos/BizHawk#1916]
### Summary
A significant amount of lag (~40 seconds) occurs before the intro cutscene of Crusader of Centy (U or J).  This does not occur in the E version or in BizHawk 1.13.2.

### Repro
1. Load BizHawk 2.x
2. Open Crusader of Centy (U) [!].bin or Ragnacenty (J) [!].bin
3. Wait until the SEGA logo disappears

### Host env.
Win10 Home; Intel i7
- BizHawk 2.4
- BizHawk 2.3.3
- BizHawk 2.3.2
- BizHawk 2.3.1
- BizHawk 2.3

Issue does not occur in BizHawk 1.13.2.  Issue does not occur in RetroArch.

![image](https://user-images.githubusercontent.com/45905923/78706149-99ff3900-78dc-11ea-8866-7a9e4ffeac9c.png)

**Comment by Sonikkustar** [comment]
If it helps, It looks like this starts to happen in 2.1.0 as 2.0.1 loads the game just fine.
![image](https://user-images.githubusercontent.com/22226938/80847900-4fbd5f00-8bdf-11ea-9ec3-9f65e3d212d6.png)

**Comment by adelikat** [comment]
Nice investigation work, @Sonikkustar !  Confirmed, it is broken between 2.01 and 2.1.0.  Fortunately there is only 2 weeks of changes between those two releases

**Comment by adelikat** [comment]
I tracked it down and confirmed that https://github.com/TASVideos/BizHawk/commit/d305c873bf5719f87a72425290a81f2749104da5 introduced this bug.

My guess is that upstream introduced this bug and then fixed it some time after this upstream update

**Comment by nattthebear** [comment]
This was https://github.com/ekeeke/Genesis-Plus-GX/commit/38ffc317cb3c75ef1002cdfb13a86503b11027d6 upstream

**Comment by nattthebear** [comment]
Branch is ready for testing a743984
