### ISSUE TITLE
cant run some roms

### ISSUE THREAD

**Issue by heckez-sys** [TASVideos/BizHawk#1921]
cant run games that emulators like fceux can why like super mario bros. 2 lost levels
(maybe add it to the cores?)

**Comment by YoshiRulz** [comment]
Are you sure your rom isn't corrupted?
![screencap of SMB2J working](https://i.imgur.com/RmtNDWq.png)

**Comment by Spikestuff** [comment]
Did you forget to put the FDS bios in the firmware folder?
(Confirming the same result as @YoshiRulz)

**Comment by heckez-sys** [comment]
oh i had a rom that looked like that but i lost it :( @YoshiRulz can i have the link

**Comment by YoshiRulz** [comment]
I can't send you the game because it's technically illegal. I also can't send you the BIOS, but I can run the game without it.

**Comment by heckez-sys** [comment]
my email is heckerz@mail.com if you want to message me(i use it to sign up to spam stuff as well(stuff like news sites)

**Comment by heckez-sys** [comment]
nice to find i aussie on here

**Comment by heckez-sys** [comment]
closed
