### ISSUE TITLE
[Feat.req] Native fps on gba

### ISSUE THREAD

**Issue by Liger0** [TASVideos/BizHawk#1929]
On mGBA you can set youw own fps, but while this is a personal decision that you may think of integrating or not and which you surely already discussed about, I was considering a thing.
On mgba the default fps are 60, which is the refresh rate of low-end consumer monitors.
However there is the option to set it to the native gba fps, which are, according to mGBA (I'm unsure how much rounded), 59.7275.
Would it be possible to implement a switch to toggle between the 60 and native one?
Thanks.

**Comment by nattthebear** [comment]
If you want exact frame for frame video output, turn on bizhawk's vsync output option.  If you want that to be perfectly timed, set your monitor's refresh rate to 59.shizzledizzle.  There may be occasional audio skipping.

If you want perfect audio output, turn on bizhawk's sync to audio option and you'll get 59.shizzledizzle frames per second with no audio skipping, but frames may have tearing and occasional studder.

If you want perfectly timed output with no video tearing and no audio studdering and exactly 59.shizzledizzle frames per second, tough beans bizhawk doesn't do that.  Try retroarch or something.

**Comment by Liger0** [comment]
I don't want to sync it on my screen or whatever (it isn't 60 hz anyway), I just wanted it to follow closely how the real gba works to emulate the console correctly timing-wise. 
It is in mgba so I thought it would be possible to implement it in this emulator since mgba is used as a core.

**Comment by YoshiRulz** [comment]
It's *already* accurate. EmuHawk speeds up or slows down to reach a target framerate, which you can pick as natt suggested. If you want it to be exact, you'll need to capture A/V and set the framerate and audio sample rate. I'm not familiar with that tool, but if you're not able to set it 59.7275 fps or whatever, you can [use FFmpeg](https://stackoverflow.com/a/45465730/7467292).

**Comment by Liger0** [comment]
I don't refear to recording or anything, just its usage.
I am not sure that I understood all, but I can't find an option to set the fps in the emulator, and I am not sure if it by default emulates at 59.7275 or at 60.

**Comment by YoshiRulz** [comment]
The concept of "framerate" is made up; it's calculated from frame length. The code in mGBA that emulates one video frame takes much less than 0.017 s (1/59.7275) to run, so EmuHawk just waits (based on the settings mentioned above). A real GBA would do something similar except there are no settings, it's always the same duration. Whatever you ask EmuHawk to do, the same code will be run, so there's no "more accurate" option. The default is `Clock Throttle` at `100%`, which I think means the virtual CPU is clocked 16.8 million times for each real-world second and has nothing to do with video (but in practice gives you about 60 fps).

**Comment by zeromus** [comment]
Stop trying to emulate the console correctly timing-wise. It's stupid and there is no point. If you want to emulate the console correctly timing-wise, you need to go further: use retroarch with a temporal blur filter, reduce the contrast and brightness to about 10%, then aim a flashlight at your monitor.
