### ISSUE TITLE
Ugly Dialog Boxes Due To Layout Panels (Customization Options)

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#1931]
I failed fixing this by adjusting margins and padding. If you can't do it, then layout panels are not a good plan
![image](https://user-images.githubusercontent.com/102701/79174905-2e303b00-7dca-11ea-92b3-a6bcc319505e.png)

**Comment by YoshiRulz** [comment]
Is that what you meant by "ugly" the whole time?

**Comment by zeromus** [comment]
Yes, but the display config had way more instances of this, far more egregious. In this dialog there was only the one minor instance.

**Comment by YoshiRulz** [comment]
I had noticed this on Mono, where everything is the wrong size, but not on Win10. If your revert commit doesn't fix DisplayConfig I'll fix the GroupBoxes in that form too. Could you take a screenshot of each tab for me?

**Comment by zeromus** [comment]
Let's see if you can fix this one first.

**Comment by zeromus** [comment]
![image](https://user-images.githubusercontent.com/102701/79207287-8721c280-7e0e-11ea-92fb-a18a4dd4dd60.png)
