### ISSUE TITLE
[melonDS] app crashes everytime i reboot the core or i open another .nds rom

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#1932]
In issue https://github.com/TASVideos/BizHawk/issues/1928 i was having the problem to not be able to open roms. It seems to be fixed, every rom can be opened without problems.
But the problem now is that app immedeately crashes when you try to reboot or, if you load another rom while emulation is in esecution, it crashes or stuck in black screen (it becomes single screen and then stuck) . I tested without BIOS and with BIOS, always the same problem, commit d2e19c9.

Also, after setting scale factor (default is 1) to 0 app still crashes and gives this error: https://pastebin.com/nDSYweCL

**Comment by heckez-sys** [comment]
wait you have melonDS core on bizhawk(i use 2.3 is it on 2.4 or...?)

**Comment by YoshiRulz** [comment]
@heckez-sys In [dev builds](https://github.com/TASVideos/BizHawk#testing) since about 25 days ago. We're not advertising it yet because there are bugs (like this one) and because our changes aren;t in sync with the melonDS developers' changes.

**Comment by heckez-sys** [comment]
@YoshiRulz cool i didn't know i have the rom for nsmb(new super mario bros) i use no$gba but the sound sucks

**Comment by SuuperW** [comment]
Crash on reboot should be fixed with commit ebc49db.
Scale factor issue is probably best fixed in libmelonDS in a future update. Setting it to 0 causing a crash is a bug there. I also just tested and found that setting it to over 11 causes savestates to not work, which I will also fix.

**Comment by Real96** [comment]
Problems seems to be fixed now. Great job! Tested bot reboot and rom changing, works great
