### ISSUE TITLE
[QuickNES] Spelunker (NES) unplayable

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#1934]
QuickNES

![Spelunker - QuickNES](https://user-images.githubusercontent.com/21311432/79262817-8d5d8080-7e9a-11ea-9531-20b84366df8a.png)

NesHawk

![Spelunker - NesHawk](https://user-images.githubusercontent.com/21311432/79262830-92223480-7e9a-11ea-83b0-cc8a403edfde.png)

Rom marked with green ✔. This happens on Bizhawk dev build with latest commit d2e19c9 and in Bizhawk 2.4 (QuickNES core)

**Comment by medigi** [comment]
Wrong label, game works great on NesHawk, while on QuickNES is buggy

**Comment by YoshiRulz** [comment]
Oh. In that case, nobody cares.
