### ISSUE TITLE
GBA Graphical Glitches Mega Man Zero

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#1936]
I have noticed some slight graphical issues when playing Mega Man Zero 1 (there are meant to be enemies where the red outlines are) and I am unsure how to fix them if there is a fix as they only happen during certain animations.
![screenshot 1](https://user-images.githubusercontent.com/12127502/79625488-69f83700-8121-11ea-8abc-315435ff9991.png)
![screenshot 2](https://user-images.githubusercontent.com/12127502/79625489-6a90cd80-8121-11ea-8122-a110af9c8fb5.png)

**Comment by endrift** [comment]
This has been fixed for a while and can be closed.
