### ISSUE TITLE
TAStudio: movie loading broken in current dev build

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1938]
repro: 
-Make a new movie in TAStudio (any system
-Advance 10 frames
-Save
-Load
Get an error:
Object reference now set to reference of an object,
...TAStudio.ListView.cs:line 265

NOTE: games that load with a bios or other instances where the movie starts with lag frames don't get this error right away. Apparently it's related to green frames. If you make a movie with only red (lag) frames it will load.

**Comment by alyosha-tas** [comment]
I did some debugging of this. This error will occur if 'use additional cpu thread' is checked in the 'rewind and savestates' menu.

I'm not sure I can get further then that, sounds bad.

**Comment by adelikat** [comment]
Does this happen on the 2.4 release?

**Comment by alyosha-tas** [comment]
It does not.

**Comment by adelikat** [comment]
I dont' feel great about this fix, but it works.  There is still the problem that while closing a rom, tastudio is exposed to NRE's by not having a tasmovie to draw from, there may be other things in the close rom process that could inspire it to redraw
