### ISSUE TITLE
No longer can see Orange inputs during Input Recording

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#1941]
If i remember correctly, before BizHawk 2.4, when i start to record the Inputs, when i press a Button while displaying the inputs, in the next frame, it apears as orange 1 frame before its gone, this used to help me before.

Now its disabled, i though if there was an option to enable it again but eother i couldnt find it or its just not there anymore.

Not to mention, as a Bonus, the Snowy Null Emulator option from Display it's gone, i liked it when it was still there but now its just gone.

**Comment by adelikat** [comment]
Input bug has been fixed since 2.4

Latest developer build will have it, will be in next release.
