### ISSUE TITLE
[Feature request] DS encode of only top or bottom screen

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#1945]
As in, only encode either the top or bottom. A lot of times 1 of those screens dont show much interest.

**Comment by zeromus** [comment]
Rejected: crop in postprocessing.

**Comment by Spikestuff** [comment]
As zeromus mentioned this can be done in post without hassle.
DS is one of the simpler systems (until you go into that other territory) so it's not worth implementing.
Here's the [DS Myst encode](https://youtu.be/6dVVY7lhzL0) that crops off the top screen in post since it's straightforward.
