### ISSUE TITLE
[MelonDS] Horizontal Screen layout is off center.

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#1947]
I've been playing Ace Attorney Investigations 2 on bizhawk dev build (since I dont want to play the game on DeSmuME).  however I wanted to play with vertical view and full screen, but the vertical part is off position.

Vertical: https://media.discordapp.net/attachments/205849868562989056/703035330345042010/unknown.png?width=1235&height=671

Horizontal: https://media.discordapp.net/attachments/205849868562989056/703035488763641977/unknown.png?width=1254&height=671

the horizontal view is up way too high to the point where it gets cut off.  this should be fixed.

**Comment by zeromus** [comment]
Use newer dev build.
