### ISSUE TITLE
Making new movies in TAStudio broken in current dev build

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1948]
Repro:

load a game, 
play some frames (until something appears on screen.)
open TAStudio.

It does not reboot the core. The current frame remains on screen.

Even starting a new movie with file -> new does not reboot the core or create a new movie.
Attempting to write any inputs in the piano roll results in a crash.

**Comment by adelikat** [comment]
Closing this, and reopening 1937
also, I give up, and will leave 1937 unaddressed.  If it's a regression it's a regression, I can't fix it without rewriting it, loading movies is too tangled :(
