### ISSUE TITLE
how to run game PSP?

### ISSUE THREAD

**Issue by candrapersada** [TASVideos/BizHawk#1949]
how to run game PSP?

**Comment by adelikat** [comment]
PSP is not currently a supported platform in BizHawk

**Comment by Spikestuff** [comment]
Oh assuming if you're still active @candrapersada the current Dev Builds of BizHawk now has PPSSPP in it's primary phase.
There's a few issues that need to be ironed out, but you can take a look at those issues, or contribute if you spot anything here: #4642
