### ISSUE TITLE
TASTudio: Save bug with recording mode on

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1950]
Repro:

load a nes game and start TAStudio.

Check the recording mode checkbox to turn on recording mode and advance some frames.

Go to file -> new.

Hit no on the dialog.

Even though you hit no it will save and make a file anyway.

NOTE: If you did this without renaming anything it will save a default.tasproj and trigger #1937

**Comment by adelikat** [comment]
This is fixed from 8ace823682afc93be842dde1fc0bcb914a0da5d7
