### ISSUE TITLE
cant play games with a need for a different controller

### ISSUE THREAD

**Issue by heckez-sys** [TASVideos/BizHawk#1951]
i cant play mario paint i think its the snes mouse i want it to be in the emulator
and i know its hard to code but try to add all the official controllers plz

**Comment by YoshiRulz** [comment]
The SNES Mouse is emulated correctly in BSNES, with the exception of being flipped vertically. This is fixed in dev builds from 34b84e709. It is not implemented in the Snes9x core (#1056).
