### ISSUE TITLE
Gambatte doesn't work in latest devbuild

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1955]
c8ae659b1

Exception box: **GB load error:**
```
A core accepted the rom, but threw an exception while loading it:
System.DllNotFoundException: Unable to load DLL 'libgambatte.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  at BizHawk.Emulation.Cores.Nintendo.Gameboy.LibGambatte.gambatte_create()
  at BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy..ctor(CoreComm comm, GameInfo game, Byte[] file, Object settings, Object syncSettings, Boolean deterministic)
```

edit: used Markdown for commit and transcribed [screenshot](https://user-images.githubusercontent.com/36802254/80477258-ebcf3800-894b-11ea-9388-6c9bd0eba749.png) to text --yoshi

**Comment by nattthebear** [comment]
@TiKevin83 Did anything change in the dll dependency chain for libgambatte.dll with #1954

**Comment by vadosnaprimer** [comment]
Works for me btw. Not sure what's different.

**Comment by ThunderAxe31** [comment]
I just needed the latest prereqs installer (2.4.8_1), sorry.
