### ISSUE TITLE
bizhawk is slow and uses tons of data

### ISSUE THREAD

**Issue by heckez-sys** [TASVideos/BizHawk#1960]
i can run super mario bros 100% on other emulators but on bizhawk is super slow
and other stuff like it takes like 80% task manager said

**Comment by YoshiRulz** [comment]
100% of what? What would you like EmuHawk to use less of?

When comparing emulator performance, keep in mind that the BizHawk project is about accuracy (usually) and debugging. Single-system emulators are always going to be faster than multi-system emulators. A dedicated NES emulator like Mesen can outperform NesHawk mostly for technical reasons; Hawk cores are single-threaded and don't/can't offload to the GPU.

**Comment by alyosha-tas** [comment]
One of the simple things you can do to reduce memory usage is to go to config -> rewind and states and uncheck everything there. Obviously you then won't be able to rewind, but it might help for casual play.

Also NESHawk is poorly optimized for speed, it's not just a matter of technical stuff. It could go twice as fast if I started from scratch, but the mapper overhead is too high. Try QuickNES if you just want to play Mario or other common games. Conifg -> Cores -> NES -> QuickNES.

**Comment by heckez-sys** [comment]
@YoshiRulz i mean cpu oops

**Comment by zeromus** [comment]
Don't bother posting "X is slow" bugs without posting your system specs

**Comment by heckez-sys** [comment]
@zeromus ok closing it now

**Comment by YoshiRulz** [comment]
Post the specs! Worst case, your PC is old and bad and we make fun of you.
