### ISSUE TITLE
Recording GIFs is broken

### ISSUE THREAD

**Issue by lunjesse** [TASVideos/BizHawk#1962]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Making GIFs using the GIF writer for gameboy (color) games, using either Gamebetta or GBHawk cores, creates gifs showing only a solid black screen instead of what was on screen. Example:
https://cdn.discordapp.com/attachments/280813077853765632/704906804701822976/hptest.gif

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk
2. Open some gameboy rom
3. Go to File > AVI/WAV > Config and Record AVI/WAV
4. Select the "Gif writer" option. Name the file whatever you want.
5. Press OK on the dialogue boxes.
6. Let the emulator run for a bit
7. Go to File > AVI/WAV > Stop AVI/WAV

Check the resultant gif. It would appear as a black screen instead of gameplay footage.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
What I get:
![Broken](https://cdn.discordapp.com/attachments/280813077853765632/704906804701822976/hptest.gif)
What 2.4 gives instead:
![Works](https://cdn.discordapp.com/attachments/280813077853765632/704904971845500958/gif_test.gif)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- Latest interim: BizHawk_Developer-2020-04-28-225624-#9dc32fcafe815068ffabdfb6e98910ee73273dd6.zip

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by ThunderAxe31** [comment]
I also had a black screen when recording GIFs for a PSX game, in the latest devbuild.

**Comment by nattthebear** [comment]
The first gif is (or appears to have been) recorded with OSD capture off, but the second has OSD capture on.  Of course both modes should work, but can you confirm which mode you're using?

**Comment by lunjesse** [comment]
> The first gif is (or appears to have been) recorded with OSD capture off, but the second has OSD capture on. Of course both modes should work, but can you confirm which mode you're using?

I just tried both modes; they both fail to make a non blank gif.

**Comment by YoshiRulz** [comment]
I'd say it's malformed or corrupted rather than empty as it looks like [this](https://youtu.be/L3JqDQ-_0Ks) on my machine.

**Comment by adelikat** [comment]
Confirmed the behavior for NesHawk as well.  Edited title since it is not GBC specific
