### ISSUE TITLE
Custom Resolution is bugged

### ISSUE THREAD

**Issue by ggcld** [TASVideos/BizHawk#1975]
I would like to put the window in 960x720 and it shrinks down to a small window if I input any custom value in resolution.

I'll have to go back to old bizhawk for now.

**Comment by YoshiRulz** [comment]
Is this on 2.4.1? Was it working properly in 2.4?

**Comment by ggcld** [comment]
Yes this is on 2.4.1 and it works fine in 2.4

**Comment by TiKevin83** [comment]
Sounds similar to #1958 , can someone check if the noted commits also change custom resolution?
