### ISSUE TITLE
Lua client lib is missing in the Lua Console when NullHawk is loaded

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#1977]
> &lt;YoshiRulz> No idea. client.getavailabletools() doesn't autocomplete, and when you try and call it you get an exception that looks like calling a nonexistent function.
> &lt;YoshiRulz> Ergo, it is missing.

**Comment by RetroEdit** [comment]
I think the scale of this issue may be over extrapolated, I just tested a script that utilizes `client.bufferheight()` and `client.SetGameExtraPadding()` and it works perfectly as expected.

However, I did notice the docs (http://tasvideos.org/Bizhawk/LuaFunctions.html) were missing the client module, and that's probably related to this issue.

**Comment by YoshiRulz** [comment]
git bisect start
\# bad: [b60bbba126cb5c49c0aa708800435f9dd865878f] Flatten BizHawk.Bizware.*
git bisect bad b60bbba126cb5c49c0aa708800435f9dd865878f
\# bad: [b8accdfd75d320a07a52d552ae226d0d035b0f2f] work harder to update mednafen PSX.cpp from 1.24.0-UNSTABLE more exactly
git bisect bad b8accdfd75d320a07a52d552ae226d0d035b0f2f
\# good: [7c32305cb4ebeb7cb3cf6c335698a50c2e3bdf7f] GBHawk: fix videoplayer2 audio
git bisect good 7c32305cb4ebeb7cb3cf6c335698a50c2e3bdf7f
\# good: [90a03f3f6a4ab09ec2c932c70bcc350fd5e54bb9] ButtonSchema - lock down Location setting
git bisect good 90a03f3f6a4ab09ec2c932c70bcc350fd5e54bb9
\# good: [0437de604b1df3590b1ee45ba402e82a4e617c2e] Revert transformPoint* changes, add transformPoint, delegate all three
git bisect good 0437de604b1df3590b1ee45ba402e82a4e617c2e
\# good: [165f3db2d85e01f0ec318d4b8d1690575d7d2d06] WIP 0.9.44.1
git bisect good 165f3db2d85e01f0ec318d4b8d1690575d7d2d06
\# good: [e62c2e3646cf6817f3ddfd54c8063b4cbe9afed4] PlayMovie dialog - simplify a bit
git bisect good e62c2e3646cf6817f3ddfd54c8063b4cbe9afed4
\# bad: [489084242fb3090b1e3792ea44039daa9c7ece85] Move [AssemblyVersion]/[AssemblyFileVersion] to VersionInfo.cs
git bisect bad 489084242fb3090b1e3792ea44039daa9c7ece85
\# good: [786fd9d5a1d827755f32b781b3005386f8909845] Database.SaveDatabaseEntry() - account for NotInDatabase rom status, and simplify
git bisect good 786fd9d5a1d827755f32b781b3005386f8909845
\# bad: [813a2ee935c3bcf76296733acddadc7c7e56e647] delete empty code file
git bisect bad 813a2ee935c3bcf76296733acddadc7c7e56e647
\# bad: [a83c125ac4cb6db4ddf4d7eb8c9885a57efe226e] Simplify nullemulator - emuHawk already handles cores with no video provider by using NullVideo, so no reason for NullEmulator to provide NullVideo
git bisect bad a83c125ac4cb6db4ddf4d7eb8c9885a57efe226e
\# good: [cb2d365284a42e009d9e7c9b626555c62e0dd354] O2Hawk: better fix for blockout
git bisect good cb2d365284a42e009d9e7c9b626555c62e0dd354
\# first bad commit: [a83c125ac4cb6db4ddf4d7eb8c9885a57efe226e] Simplify nullemulator - emuHawk already handles cores with no video provider by using NullVideo, so no reason for NullEmulator to provide NullVideo

**Comment by YoshiRulz** [comment]
Fixed by 63ef4125d.
