### ISSUE TITLE
2.4.1 Windows version Display Configuration Scaling & filtering broken.

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1978]
2.4.1 Windows version Display Configuration Scaling & filtering broken.

in 2.4 and previous is ok.

Example try opening config and set custom aspect ratio. go back in custom ratio gone and not retained.

**Comment by jjfmz42015** [comment]
custom aspect ratio broken on this windows build.

**Comment by YoshiRulz** [comment]
Duplicate of #1975?

**Comment by zeromus** [comment]
yes
