### ISSUE TITLE
MSX Firmware confusion?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1981]
I was trying to complete the firmware for my Bizhawk. Then Came MSX

Are these entries correct? (like what bizhawk is actually looking for as far as MSX?

**Comment by alyosha-tas** [comment]
No, those are only temporary for testing. Once the core is released it will have official hashes.

**Comment by jjfmz42015** [comment]
> No, those are only temporary for testing. Once the core is released it will have official hashes.

Thank you, so ill just leave blank for now
