### ISSUE TITLE
Lua: function registration/unregistration causes NullReferenceException

### ISSUE THREAD

**Issue by Trivial-Man** [TASVideos/BizHawk#1983]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Running a Lua script that registers and unregisters functions seems to cause NullReferenceExceptions in at least the 2 cases outlined below, though I suspect there are more. For context, I found the first case when running a rather complex script and trying to remove it, and the second I only discovered when I tried to create the sample script shown below. It's likely related to #1957 since the error is the same and it's using Lua too.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Put this script into a file and then run it while any game is playing:
```lua
local function1ID = ""
local function2ID = ""

local function function2()
  console.writeline("Function 2 (load state) called")
  
  event.unregisterbyid(function2ID)
end

local function function1()
  console.writeline("Function 1 (mem execute) called")
  
  event.unregisterbyid(function1ID)
  
  function2ID = event.onloadstate(function2, "function 2")
end

local function InitializeExecutionFunctions()
  function1ID = event.onmemoryexecuteany(function1, "function 1")
end

local function main()
  InitializeExecutionFunctions()
end
main()
```
2. As soon as the game executes anything (should be near instantaneous if the emulator isn't paused) function1 will run and print to console, unregistering itself and registering function2. Now you have 2 different bugs you can trigger here depending on what you do:

3A. Try to reload or remove the script using the buttons or script menu in the Lua Console window. You'll get a pop-up error with the output below and the script will not actually removed or refreshed. If you manually remove the registered functions then you can remove or refresh the script as normal. Similarly, closing the Lua Console window does seem to unregister everything and stop all scripts.

3B. Instead of all that, try and load a savestate to trigger function2. It will not be triggered and instead a short error message will be printed to the Lua Console output this time. Very similar to the other but with much less detail.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
Pop-up error log:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.LuaFunctionListExtensions.<>c__DisplayClass0_0.<ForFile>b__0(NamedLuaFunction l)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BizHawk.Client.Common.LuaFunctionList.RemoveForFile(LuaFile file, IEmulator emulator)
   at BizHawk.Client.EmuHawk.LuaConsole.RemoveScriptMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Lua Console error log:
```
error running function attached by lua function event.onloadstate
Error message: Object reference not set to an instance of an object.
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.1; Win10 Pro 1903; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Both errors still happen on 2.4.2 @adelikat.

**Comment by Trivial-Man** [comment]
Thank you. This resolves my issues in the real script I was using as well as the demonstration script posted here.
