### ISSUE TITLE
Gambatte: emulate un-mapped memory in GBA mode

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1987]
@TiKevin83 
The region 0xFEA0 - 0xFEFF behaves differently on GBA then on GBC, so this might be relevant for console verification.

see: https://github.com/AntonioND/gbc-hw-tests
memory -> oam_echo_ram_lcd_on.gbc

I just went through this with GBHawk, it should return (addr & 0xF0) | ((addr & 0xF0) >> 4) and writes should have no effect, not too hard. Could throw off a run though since Gambatte currently doesn't do anything with GBA mode in this case.

**Comment by TiKevin83** [comment]
This should be easy to fix as an exercise of theory, but it should also be low priority as it doesn't seem to affect any TASes that Pokemon Speedrunners are aware of, and the gbdev scene also believes it would not affect any commercial games that would be TASed.
