### ISSUE TITLE
Lua joypad.set doesn't appear to do anything

### ISSUE THREAD

**Issue by dfaulken** [TASVideos/BizHawk#1990]
### Summary
Lua functions for setting or getting joypad input don't appear to do anything for PSX.

### Repro
I have the following Lua script which I am running throughout the loading phase of a game where pressing Start should skip the intro cutscene.

```lua
function enactInput(t)
  joypad.set(t)
  if t.start then
    gui.drawText(0, 0, 'start')
  end
  emu.frameadvance()
end

while true do
  local t = {}
  for i = 1, 30 do
    t['start'] = true
    enactInput(t)
  end
  for i = 1, 30 do
    t['start'] = false
    enactInput(t)
  end
end
```

The word 'start' flashes every 30 frames on screen, but the joypad input set has no effect. Actually pressing my mapped key to the joypad 'Start' button, though, works fine.

I should note that I am using the lowercase `'start'` key according to [this guide](http://tasvideos.org/LuaScripting/TableKeys.html).

### Output
Nothing happens.

### Host env.
Latest stable, Windows 10, emulating PSX

**Comment by adelikat** [comment]
That guide is not for Bizhawk.

You should do this in the lua console window: joypad.get(), or in your script via console.log(joypad.get()) to get the proper names of the controller buttons.

They are case sensitive, and likely to be 'P1 Start' for PSX, but you should get in the habit of looking them up as described, there's too many platforms and peripheral options to keep documentation like that up to date.
