### ISSUE TITLE
NES: RAM Search needs improvement

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#1994]
Current 2.4.1 could only show $0000-07FF, unlike FCEUX could show $6000-7FFF.
Though I can select "System Bus" to show all RAM addresses, however I can't edit $6000-7FFF values with HEX Editor unlike FCEUX.

**Comment by zeromus** [comment]
ram search: settings, memory domain, system bus.
totally separate question not described by the topic about hex editor: check this
