### ISSUE TITLE
NES: Most ROM cheats don't work on most games

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#1995]
### Summary
Most Game Genie cheats, and other cheats that modify ROM, don't work on NES at all.

### Repro
One particular example:

ROM:
```
Hash for BootGod: A611B90B4833B20A364BF06EE3BE3B9093EA4DF9
BootGod entry found: Super Mario Bros. 3
```

Cheat:
```
nxkxglie (game genie format)
```

Merio should start every level in leafy form with the tail.  He does not.  This works in FCEUX and most likely most other emulators

### Host env.
This has been broken as long as I remember.  It was never implemented.  But if you need a specific version, BizHawk 2.4.1 exhibits it.

### Technical
On any ROM with bankswitching, ROM codes must be applied to whatever bank is switched in at all times.  BizHawk applies ROM cheats only at a particular time in vblank, hitting whatever bank is active at that moment.  Not only is this not likely to hit the right blank, for many games it absolutely will not ever hit the right bank, since many games (including SMB3) only have certain banks swapped in when vblank hits due to their game design.

**Comment by alyosha-tas** [comment]
I can fix this pretty easily if I knew how to send the 'compare' value to the core (which is what is currently missing to make this work.)

Currently cheats are sent to the core through a system bus poke, which doesn't include the needed 'compare' value.

After that, they are applied continuously though, not just on vblank, so I would only need to add another 2 lines of code to check that correct bank is there.

So, it's really just the first step I don't know how to do.

**Comment by alyosha-tas** [comment]
I think with a bit of tinkering I can get this working. I'll give it a try. Probably won't be relevant to other cores but oh well.

**Comment by zeromus** [comment]
This was never done precisely because nobody ever finished designing a cheats interface. IMO, cheats need to get sent to cores as a list of strings for the core to interpret in its own way. In the case of NES, of course, it needs to be implemented by filtering EVERY rom read.

**Comment by nattthebear** [comment]
> they are applied continuously though, not just on vblank

I see.  I was thinking about a much older version of BizHawk where they were applied only on vblank, and that's why it was broken.  I assumed the implementation was still the same, since they still don't work.

**Comment by nattthebear** [comment]
c53bda923536ee046fa794cf4e18095899b46
