### ISSUE TITLE
OBS Studio BizHawk Detection

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/BizHawk#1996]
### Summary
OBS Studio Can pick up on the TAStudio window, but you have to choose the window again each time you open TAStudio.
Somewhat related to #1529 but specific to TAStudio

### Repro
Open TAStudio to a specific TAS.  In OBS Studio create a new window capture, choose TAStudio, capture method automatic, any Window Match Priority method.  Close EmuHawk and reopen to the same tastudio project, the tastudio window will switch to the emulator.  EmuHawk will stick fine if window match priority is set to "find window of same executable" which covers #1529 but TAStudio has the same executable name as emuhawk.exe so OBS can't consistently find it.

### Host env.
- BizHawk 2.4.1; Win10 Pro 1909; AMD

**Comment by YoshiRulz** [comment]
Static window titles would be easy if we had a `DialogFormBase : Form`, but all attempts at that have failed...

**Comment by zeromus** [comment]
My response is the same as the other ticket. It is not our problem if OBS isn't engineered to do what its paying customers want it to do. Our job is create windows. OBS's job is to capture windows. If OBS has any suggestions other than "Make the window caption special" then I'll be glad to listen. If the only way you guys can solve this is by making the window caption special, then it should certainly be doable (I don't know what problem there is with DialogFormBase but we already have "tool windows" widely deployed). 

Why can't you capture your whole desktop and crop the area to match the location of the tastudio window?

**Comment by YoshiRulz** [comment]
I still want a base class for doing this properly (maybe `ToolFormBase` is good enough?), but I'm going to add a "static window title" setting for 2.5 and get *at least* MainForm and TAStudio to follow it.

Can someone confirm that `Config` > `Display...` > `Window` > `Windowed` > `Frame` has no effect on OBS' ability to detect the window?

**Comment by nattthebear** [comment]
> My response is the same as the other ticket.

I agree.  We must not do anything about this.
