### ISSUE TITLE
Screenshot get blurry when use Bilinear the Final Filter

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#1997]
![Zanac 2020-05-12 21 46 25](https://user-images.githubusercontent.com/54294476/81699826-7199ca00-949a-11ea-8696-a0b30de09e88.png)

**Comment by zeromus** [comment]
screenshot using WHICH hotkey or menu option in WHICH version of the emulator

**Comment by Yave-Yu** [comment]
F12
2.4.1

**Comment by zeromus** [comment]
try an autobuild, and delete your config.ini file (make a backup first)
you must have a weird setting, because it works fine for me

**Comment by Yave-Yu** [comment]
OK, I know the reason.
If I won't increase Prescale value, this bug won't happen; but if I increase it, screenshot will crop 1 vertical line pixel and leave the right-most a black line. So about the latter, if I use Bilinear filter, the center of screenshot will blurry; if I use None, the center will lack 1 vertical line pixel.
I think it's a bug.
![20200513101134](https://user-images.githubusercontent.com/54294476/81763606-3632e600-9502-11ea-9584-782561fd259a.png)

**Comment by zeromus** [comment]
Yes, this is a bug. the F12 key should be a "raw" screen shot, as you expected, which should not have the effects of the prescale (and somehow the subsequent filtering) applied. The same problem happens with ctrl+c which is where it's described as a raw screen shot.

**Comment by YoshiRulz** [comment]
Was this fixed in the dev build with #1975/#1978?

**Comment by zeromus** [comment]
no.
