### ISSUE TITLE
OTK input + Print screen key CRASHES the program

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#1998]
This is due to the key map dictionary being un-exhaustive.
Please make it exhaustive, else it's a regression relative to the old dinput-only code.
Do not check HasValue, do not catch exceptions. Expand the key map.

**Comment by YoshiRulz** [comment]
CNR on Linux, booting Windows machine

**Comment by zeromus** [comment]
One day, someone else will find a key that crashes on a foreign keyboard. I will send them here to haunt this thread. This key map is fundamentally frail.
