### ISSUE TITLE
Add Mednafen's PCE Core to Bizhawk

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2000]
Our PCE core has accuracy issues and is not really updated anymore.  Mednafen's PCE core is known for high accuracy and is most likely well written and organized, as Mednafen cores generally are.

See https://github.com/TASVideos/BizHawk/issues/960

**Comment by Sonia-7** [comment]
This is exciting! Thank you so much for this, I've been waiting years for it to happen.

**Comment by YoshiRulz** [comment]
...this isn't a PR.

**Comment by Sonia-7** [comment]
> 
> 
> ...this isn't a PR.

Never thought it was one. Just seeing the "Future Core" label was enough to make me happy. ;)

**Comment by nattthebear** [comment]
Basic work is done.  Blockers:

For the next release

settings UI
arcade card rewind hack --- this is actually an exposed setting in mednafen, so only needs settings UI
bg viewer
sprite viewer
sound debugger

memory domains:

"ROM"
?"Battery RAM"
?"ADPCM RAM"
?"Arcade Card RAM"


lag flag


Code data logger?  not likely


#2043 
#2051

**Comment by nattthebear** [comment]
Also need some basic savestate size optimizations -- nothing major, but stuff like the owl resampler need placement new

**Comment by nattthebear** [comment]
Most all of the regular functionality that PCEHawk supported is hooked up.  We'll handle other things as they come.
