### ISSUE TITLE
[Feature Request] Add debug window

### ISSUE THREAD

**Issue by martmists** [TASVideos/BizHawk#2005]
### Summary
While debugging a new game or porting to bizhawk from a different emulator, being able to draw and output is a great feature to have. The issue, however, is that there's very limited space, and debug output easily obscures vision of the game.

### Proposal
For this reason, I suggest adding a new "debug" window which Lua scripts can access, which allows for drawing elements every tick similar to the main window, but without covering the game. This would also mean that this debug window is not limited by the size of the game screens, but could theoretically stretch indefinitely, allowing for an easier overview of a lot of data.

### Lua Implementation
There are many ways to implement this, but I have two possible proposals in mind:

#### setDebug
One option is to add `gui.setDebug(boolean)`, which tells the gui module to draw to the debug window or main window, depending on the last value it was called with.

#### debuggui
An alternative is to "copy-paste" the `gui` module to a `debuggui` module, which does the same things on the previously mentioned debug window.

**Comment by YoshiRulz** [comment]
You can add padding to the main EmuHawk window in `Config` > `Display...`, or create a new window with Lua `forms.newform`.

**Comment by adelikat** [comment]
You can also expand the main window canvas side via lua, and draw on that space

**Comment by martmists** [comment]
The issue with forms is that they can't be immediately drawn to, instead they need to get a pictureBox first. Additionally, stopping a script does not remove the box, causing a lot of issues for managing multiple scripts whereas these could draw to separate regions in the same window instead when using a global debug window.

**Comment by martmists** [comment]
For those curious as to how to get an object that behaves similar to `gui`, here's my solution (does not solve the multiple windows issue):
```lua
local ___handle = forms.pictureBox(forms.newform())  -- This may sometimes crash, I don't know why or how
local debug = {}  -- The object that will act as the `gui` replacement
setmetatable(debug, {  -- metatable mess to add the pictureBox handle to all methods called on debug and redirect it to the `forms` module
  __index = function(self, f)
    return setmetatable({}, {
      __call = function(t, ...)
        -- Bizhawk has no table.unpack for some reason, so this uses the one from the wiki: 
        -- https://www.lua.org/pil/5.1.html
        return forms[f](___handle, unpack(arg, 2))
      end
    })
  end
})
```
