### ISSUE TITLE
[GBHawk] Audio playback is screwed up with Pokemon Crystal

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#2006]
Noticed with this TAS submission: http://tasvideos.org/6746S.html

Audio has this weird static noise with some tracks.  Most noticably with the intro theme with Professor Oak.  And other tracks have some weird background echo to them (like the hometown theme).

Note that Alt Sync does not fix this issue.  This is the case for both GBHawk and SubGBHawk.

also tested myself to confirm it: https://www.youtube.com/watch?v=EWUnVrEKD_U

**Comment by YoshiRulz** [comment]
2.4.1?

**Comment by CasualPokePlayer** [comment]
> 
> 
> 2.4.1?

My submission used 2.4.1, yes.

**Comment by alyosha-tas** [comment]
I'm calling this fixed, it sounds much better now. Audio emulation in general needs more filtering, but when I added a high pass filter experimentally it didn't help anything here.
