### ISSUE TITLE
Pasting converted dsm input to TAStudios crashes game

### ISSUE THREAD

**Issue by lunjesse** [TASVideos/BizHawk#2009]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
When a .dsm file is converted to a .bk2 file by drag-dropping it to BizHawk, attempting to copy paste the input (by opening the input log.txt inside the newly converted .bk2 file, and copying a line) to TAStudios causes the game to crash. Game in question was "Paint by DS"

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open up DeSmuME
2. Open up Paint by DS on DeSmuME
3. Go to File > Record Movie. Record input with stylus.
4. Immediately end the movie.  You should get a file like the following:
``` version 1
emuVersion 91000
rerecordCount 0
romFilename 2035 - Paint By DS (E)(Xenophobia).nds
romChecksum 00000000
romSerial NTR-AONP-EUR
guid 84BE2329-6CE1-AED6-9052-49F1F1BBE9EB
useExtBios 0
advancedTiming 1
useExtFirmware 0
firmNickname yopyop
firmMessage DeSmuME makes you happy!
firmFavColour 10
firmBirthMonth 7
firmBirthDay 15
firmLanguage 1
rtcStartNew 2009-JAN-01 00:00:00:000
comment author Hi
|0|.............000 000 0|
|0|.............019 000 1|
```
(Or save the above as test.dsm)
4. Open up BizHawk with the Paint by DS rom.
5. Drag and drop it to BizHawk. It should give a file named "test.dsm.bk2"
6. Open "test.dsm.bk2" with 7z or similar
7. Click on "Input Log.txt" It should look like the following:
```
[Input]
LogKey:#TouchX|TouchY|Left|Right|Up|Down|A|B|X|Y|L|R|Start|Select|LidOpen|LidClose|Power|Touch|
|    0,    0,...............|
|   19,    0,..............T|
[/Input]
```
8. Copy the last line, including the new line character at end.
9. Stop "test.dsm.bk2" from playing in BizHawk.
10. Go to Tools > TAStudios
11. Go to the 1st frame, and paste in the line from above. In other words, paste in (include the new line!):
```
|   19,    0,..............T|

```
The game will now crash, and you just ruined your TAS project. To confirm that it's indeed a crash, let the game run normally until developer name shows up. Then go back to frame 1 and paste it in. The game now won't show anything, even after removing the input.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
Nothing. Game just turns to black screen and lag counter increments forever.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.1, interim (https://github.com/TASVideos/BizHawk/commit/00aebc110c57e71099a14564bcca4548c72cb96c) this build

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
If you copy-paste from somewhere else, this page for example, does it still crash? It sounds like you're over-complicating the repro.

**Comment by lunjesse** [comment]
> If you copy-paste from somewhere else, this page for example, does it still crash? It sounds like you're over-complicating the repro.

You can skip most of the steps and last 2 steps. Ie. 
1. Open up BizHawk with Paint by DS
2. Go to Tools > TAStudios
3. Paste in 
```
|   19,    0,..............T|

```
Now it would also crash. I included the initial steps so people would know "where did you get the idea to paste input from" and show that it was initially from a valid input file, and not because I messed up myself.

**Comment by vadosnaprimer** [comment]
Who ever promised that you could copypaste from non-tastudio?

**Comment by lunjesse** [comment]
> Who ever promised that you could copypaste from non-tastudio?

In every other core I used, you could copy paste the input from the input log inside the BK2 file into TAStudios.  Why should DS be the exception? I'm NOT saying I copied from DESMUME's input file; I copied from a BK2 file generated by drag-drop .DSM into BizHawk.

**Comment by vadosnaprimer** [comment]
Who ever promised that you could copypaste from non-tastudio?

**Comment by adelikat** [comment]
it should work though.  The input log for tastudio is the same as bk2

**Comment by vadosnaprimer** [comment]
The "imported" log doesn't work in hawk at all.

**Comment by lunjesse** [comment]
I closed the report since after talking a while, it appears it's due to the import not working. I made a report on that instead. Sorry about that.
