### ISSUE TITLE
Hex Editor reads stuff many times

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2012]
### Summary
Hex editor makes far too many calls to memory domain reads

### Repro
Open the hex editor.  Set to one byte wide.  Frame advance once.  Observe the sequence of calls.  You'll see one call to bulk read byte, followed by a large number of calls to read byte.

### Host env.
BizHawk 2.4.1, Windows 10

**Comment by vadosnaprimer** [comment]
It's for chars on the right?

**Comment by adelikat** [comment]
Yes, the chars code was never converted to use a bulk read
