### ISSUE TITLE
How can I don't create state bak file like SaveRAM?

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2014]
I didn't see an option to disable state bak creation like SaveRAM...

**Comment by adelikat** [comment]
Config -> Customize -> Advanced -> Backup SaveRam

**Comment by zeromus** [comment]
Config > Rewind & states > Backup Savestates

**Comment by Yave-Yu** [comment]
> Config > Rewind & states > Backup Savestates

Thanks lol
