### ISSUE TITLE
Changing domain doesn't take effect immediately or prompt

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2020]
Version 2.4.2
Every time change Memory Domain, it requires refresh (click New) to take effect, not immediately.

**Comment by RetroEdit** [comment]
Changing the memory domain on the RAM search tool? If it changed instantly, it could potentially overwrite a user's previous search without warning (though I suppose it could prompt the user about it, seems a bit overkill?)

That being said, I do find memory domain selection on the RAM search screen to be annoying, but I'm not sure what the best way to improve that would be.

**Comment by Yave-Yu** [comment]
> If it changed instantly, it could potentially overwrite a user's previous search without warning

OK, if this is a problem, don't change it is better way.
