### ISSUE TITLE
SNES: Update Snes9X core to latest.

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2021]

**Comment by YoshiRulz** [comment]
..? Did you figure out why the sound wasn't smooth?

Edited issue is a duplicate of #1374.

**Comment by Yave-Yu** [comment]
> ..? Did you figure out why the sound wasn't smooth?
> 
> Edited issue is a duplicate of #1374.

Sorry for that, because I discovered it's my PC problem, after reboot PC, that issue gone.

**Comment by nattthebear** [comment]
Closing in favor of existing issue
