### ISSUE TITLE
Legend of Zelda Oracle of Ages Mermaid dungeon impossible with Gambatte core

### ISSUE THREAD

**Issue by BopItFreak** [TASVideos/BizHawk#2026]
I'm having trouble finishing the mermaid dungeon in the oracle of ages game. I looked up some tutorials online and it seems the room I'm stuck in is missing about half of what it should look like. I've attatched screenshots of what the Gambatte core looks like, and what it should like it. I can't finish the game with this glitch, so I hope it gets fixed :(

### Repro
I made a savestate of the room with the issue [here](https://cdn.discordapp.com/attachments/651555700354449410/712444432506552380/Legend_of_Zelda_The_-_Oracle_of_Ages_USA.Gambatte.QuickSave1.State).

### Host env.
- Latest release,  Windows 10; Intel/AMD

Screenshots:

Here is what it looks like on the Gambatte core: 
![image](https://user-images.githubusercontent.com/41522720/82387973-5da81800-9a06-11ea-9e97-840fbc40dab4.png)

Here is what the room should look like normally:
![image](https://user-images.githubusercontent.com/41522720/82387908-3e10ef80-9a06-11ea-95f0-a9716aaf3fe1.png)

The arrow in the second screenshot seems to be where the room was cut off in the Gambatte core.

**Comment by nattthebear** [comment]
I don't know much about these zelder games; do we know this isn't just some game hidden wall thing that you have to go talk to a guy about first?

**Comment by BopItFreak** [comment]
I'm dumb
