### ISSUE TITLE
Gambatte: Wario Land 2 Desync (compared to real console)

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/BizHawk#2033]
Logging an issue for the Wario Land 2 console desync investigation

I'll be sending a PR which adds a corner case to VRAM reads, where the first time VRAM is accessed below 0x9000 on the exact cycle of the switch to mode0, the read should return 0x00 instead of the block 0xFF or the expected VRAM read.  This behavior has been verified in a testROM with mattcurrie and fixing the testROM also fixes the console desync.

GBP result
![image](https://user-images.githubusercontent.com/38826675/82575617-b71f5c80-9b56-11ea-9b59-f26778f2ee30.png)

Before EMU
![image](https://user-images.githubusercontent.com/38826675/82575556-a4a52300-9b56-11ea-9984-f452f0f3c50a.png)
After EMU
![image](https://user-images.githubusercontent.com/38826675/82575461-80e1dd00-9b56-11ea-8bed-fa617abcb1a0.png)

Console Behavior compared to before in EMU
[WL2ConsoleLeftEmuRight.zip](https://github.com/TASVideos/BizHawk/files/4663285/WL2ConsoleLeftEmuRight.zip)

EMU behavior after fixing the testROM
![image](https://user-images.githubusercontent.com/38826675/82576069-547a9080-9b57-11ea-9407-fd79badb4b4c.png)

**Comment by nattthebear** [comment]
Edited the title.  Not sure what perfect verbage is, but I always get a heart attack whenever I see desync because I assume savestate nondeterminism.  This is more just a plain old inaccuracy

**Comment by TiKevin83** [comment]
ah sorry for the scare natt, yes this is an inaccuracy, savestates are deterministic still :)
