### ISSUE TITLE
Sega CD - load error

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2035]
![Sega CD loading error in bizhawk](https://user-images.githubusercontent.com/21311432/82602921-735e3e80-9bba-11ea-8a8d-581e0033f920.PNG)

Using latest dev build - commit db91189

**Comment by EZGames69** [comment]
Did you load the .bin file or .cue file?

**Comment by medigi** [comment]
cue file. Tested with: Sonic The Hedgehog CD, Keio Flying Squadron

**Comment by zeromus** [comment]
that's not the problem. ElfSharp is legitimately missing.

**Comment by nattthebear** [comment]
@YoshiRulz @zeromus do we need to do anything special to get ElfSharp to show up in builds?  It's referenced as a nuget package, and works locally.

**Comment by zeromus** [comment]
fixed by 4f10b97
