### ISSUE TITLE
Log Window is garbage

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2038]
All output from waterbox cores is missing.  All output from when the emulator first started up is missing.  If this isn't fixed by the next time I return to master, I will completely rip out the tool garbage and set the app to always show a console window.

@adelikat being able to log plain text output is one of those basic features that has to work.  `Console.Out` needs to go to a working place in the right way all the time.  Don't rip out existing functional code please.

**Comment by nattthebear** [comment]
If you need test vectors, for waterbox:  Loading an uzebox will print `-- Loading UzeROM Image --` to the console, and there are a few screenfuls of duplicate gamedb hashes that should show up there as well.  (Why duplicate game hashes?  Well, different bug I guess.)

**Comment by zeromus** [comment]
better revert bdd0d56a70067863b8d3cb142f939234bd341d2f before someone gets hurt. should be possible to do by hand, since it's not likely to be automatically revertable post-all-source-code-moved.

**Comment by nattthebear** [comment]
I'm not blocked since for local dev I've just slapped `<OutputType>Exe</OutputType>` into the csproj

**Comment by alyosha-tas** [comment]
This reminded me of something. Sometimes when I hit 'clear' it clears it but then stops outputting new data.

**Comment by vadosnaprimer** [comment]
It took me a while to realize this is the reason I'm not seeing my debug info from mame core. It's kinda impossible to develop without console output.

**Comment by nattthebear** [comment]
Another interesting thing I noticed:  Depending on what debugger is attached, certain corrupted state exceptions can print useful information to a real windows console before they destroy the application, but no winforms code would ever catch that.
