### ISSUE TITLE
Axes don't seem to respect mid

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2048]
Not sure what's going on here, but if you look on latest master you'll see that floatranges on the new PCE core that were initalized with min = 0, mid = 0, max = 1 are getting fed values of 1 by the frontend.

**Comment by YoshiRulz** [comment]
Are you referring to [this](https://github.com/TASVideos/BizHawk/blob/162a15145172770a326827f820b17fcb2f46ff24/src/BizHawk.Emulation.Cores/Waterbox/NymaCore.Controller.cs#L111-L112)? I tried your new core but both the Virtual Pad and TAStudio refuse to show controllers. There's some failing cast to `PCEngine` (the other core) somewhere.

**Comment by nattthebear** [comment]
Yes.  I've been testing it without virtual pad or tasstudio.

**Comment by nattthebear** [comment]
They're no longer floats, but the problem still persists.

Under the hood, mednafen has the idea of "switches" that can be changed at arbitrary times while running, but are expected to be 'sticky' and hold their position without needing continuous input.  Some have only 2 positions, like the ones in mednapce, but some have more.

Both mouse binding and gamepad analog bindings are a poor fit for them.  Virtual pads work fine, but that would be a poor experience for non-tasers.

For this ticket, I just want the `mid` value to be respected if nothing is bound, but we need a better solution overall for them.

**Comment by YoshiRulz** [comment]
Am I right in thinking such switches in nyma cores are currently implemented like radio buttons (using 8 buttons instead of an axis)? We might be able to add "is sticky" semantics to `AxisSpec`, or maybe `Controller` needs to change.

Can I have a minimal repro case where `AxisSpec.Mid` doesn't work as expected?

**Comment by nattthebear** [comment]
Yes, radios is how they work now.  It should be noted that the mednafen cores have very few of these, so it's not high priority.

The original controls that made me write this ticket no longer exist, but I don't think there was anything special about them.  It was just an axis with min = 0, mid = 0, max = 1.

**Comment by alyosha-tas** [comment]
Here is what I see is going on. First, if you have a new config file, mid is correctly being respected as the default for analog controls. However if you save a control config (even if not binding anything to analog controls) an analog control binding still gets saved in the config file. the binding is blank ("") but this is still read from somewhere in the controller reading here: 

https://github.com/TASVideos/BizHawk/blob/9600bc2ce0add5fa8041a57b9fa8f53158403313/src/BizHawk.Client.Common/Controller.cs#L121-L129

This returns 0 (at least for me, might be system dependent I don't know where it's reading from exactly.)
Then, in NormalizeAxes the code for scaling and bounding the control expects a zero centered range (i.e. control stick) so it produces an incorrect result for ranges like 0-1 or 0-70224 in the case SubGBHawk:

https://github.com/TASVideos/BizHawk/blob/9600bc2ce0add5fa8041a57b9fa8f53158403313/src/BizHawk.Client.Common/Controller.cs#L82-L89

For an input of zero, this returns 1 for range 0-1 in the original issue, or 35112 in the SubGBHawk issue.

How to fix it? Ignore blank bindings? I think this code will always see a zero centered range when reading from an actual control stick as intended, so maybe just ignoring a blank config is good enough.

**Comment by nattthebear** [comment]
The problem with blank bindings vs non bindings sounds like it's related to https://github.com/TASVideos/BizHawk/issues/2264 as well

**Comment by adelikat** [comment]
This affects SubGBHawk as documented in this ticket: https://github.com/TASVideos/BizHawk/issues/2272

**Comment by adelikat** [comment]
various commits, including and up to https://github.com/TASVideos/BizHawk/commit/dc7f5ef7a2bf98fd8e8ae8cd15ff4254dfe68c87 seem to have resolved this issue.

I tested with various analog controls and hardcoding a mid value that is not actually mid-way between min and max, and the client side was able to adapt.

**Comment by YoshiRulz** [comment]
As of that commit (dc7f5ef7a), analog<=>analog bindings seem to work correctly on all combinations of { N64, PSX, Saturn } with { DirectInput, OpenTK }.
