### ISSUE TITLE
Suggestion for adding new cores. (PHOENIX emulator)

### ISSUE THREAD

**Issue by AlanRibas** [TASVideos/BizHawk#2055]
It is not a problem that you will report, but a suggestion:

I saw that the suggestion for the ATARI JAGUAR video game is the "Virtual Jaguar" emulator.

I currently use PHOENIX to emulate the atari jaguar and 3DO.

I believe to be the best emualdor for theses systems. You should use the core of this emulator.

**Comment by YoshiRulz** [comment]
Duplicate of #1907. Phoenix is on the list, but since I couldn't find its source code it's not the first choice.
