### ISSUE TITLE
TAStudio Leaks Memory, even after closing

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2059]
Repro: Load a game. Open TAStudio. Close TAStudio. Unpause and Let the game run normally.

Watch in task manager as memory usage increases be tens of MB per second.

**Comment by YoshiRulz** [comment]
Is this something? master at d13a1b54a
![Annotation 2020-05-29 022036](https://user-images.githubusercontent.com/13409956/83167205-4c23e600-a153-11ea-8fc0-c33c5e89b951.png)

**Comment by nattthebear** [comment]
Did you link the right commit?  Doesn't seem related, and OmniSharp told me the things I deleted had not been in use.

**Comment by alyosha-tas** [comment]
This problem comes from here:

15f69cf
