### ISSUE TITLE
Sound config  RW & FF manual increase and decrease not working

### ISSUE THREAD

**Issue by Liger0** [TASVideos/BizHawk#2061]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
In the Sound configuration, in Volume, the RW & FF manual singular increase and decrease of the value doesn't affect the slide bar and the value in general. 
Manually writing the value doesn't work either.
Only sliding the bar stores the changed value. 
But, even so... what is that setting for even? It doesn't exist in the documentation for what I've seen.

### Host env.
- BizHawk 2.4.2; Win10; AMD

**Comment by YoshiRulz** [comment]
The value of that RW/FFW volume slider should take effect when rewinding or turboing.

$10 says I'd fixed this problem as part of a refactor which was reverted in e8e0a94d3.
