### ISSUE TITLE
NDS Path only visible when a DS rom is open

### ISSUE THREAD

**Issue by Liger0** [TASVideos/BizHawk#2062]
### Summary
NDS only appears in the list in the path options only when a DS rom is open, it doesn't appear otherwise.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.2; Win10 Pro 1903; Intel/AMD

**Comment by vadosnaprimer** [comment]
What NDS Path?

**Comment by Liger0** [comment]
Config -> Paths 
There is no NDS tab unless you select an NDS game.
