### ISSUE TITLE
TAStudio: Loading a movie starts at frame 0 instead of where you saved at.

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2063]
Repro: (NOTE: use 2.4.1 or 2.4.2, it's broken in master in a different way.)
Load a game and TAStudio. let it run for a bit and save it. Load it again, you are back at frame 0.

This is a regression from 2.4.0, where loading returns you to the frame where you saved.

**Comment by nattthebear** [comment]
> it's broken in master in a different way.

Does that need a separate ticket?

**Comment by alyosha-tas** [comment]
That's #2057. time wise this one happened first though. Not sure if / how they might be related.
