### ISSUE TITLE
allow switching between gens plus gx and picodrive core for genesis emulation feature request

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2068]
allow switching between gens plus gx and picodrive core for genesis emulation feature request

ive done it by editing files to test

**Comment by nattthebear** [comment]
Yeah, the picodrive core supports regular megadrive and megacd stuff, and it's mostly working.  I forget why we never enabled it @adelikat

**Comment by jjfmz42015** [comment]
32x games use it.

**Comment by nattthebear** [comment]
Talked to adelikat offline.  In general, picodrive is not very accurate.  We use it for 32x because it's the only game in town.  We use it for certain specific genesis games because they're more accurate on it (but there aren't many of those).

What exact use case do you have that's not supported by the current setup?

**Comment by jjfmz42015** [comment]
I see. Best to leave alone then.

**Comment by getCursorsExe** [comment]
Well, I have encountered another problem with Sonic 3 Delta romhack. The game freezes if we enter any level while we are in Genesis Plus GX core. I don't know why this happens, but this definetly does not happen in PicoDrive core.

**Comment by getCursorsExe** [comment]
Also, because it is possible to play a Sega Genesis ROM in PicoDrive (32X), this almost doesn't make any sense at all.

**Comment by getCursorsExe** [comment]
While PicoDrive is less accurate than Genesis Plus GX, it may sometimes display something that is not emulated on Genesis Plus GX.

**Comment by getCursorsExe** [comment]
TiTAN Overdrive appears to be emulated a lot better than Genesis Plus GX, meaning that Genesis Plus GX emulates it differently.

**Comment by getCursorsExe** [comment]
It will still not be used for TASing Genesis games, but it is still a good idea to add it here, since there are some features that Genesis Plus GX doesn't emulate, while PicoDrive does.

**Comment by YoshiRulz** [comment]
This feature request was denied. If you can elaborate on
> there are some features that Genesis Plus GX doesn't emulate, while PicoDrive does

then we may reconsider (OP was unable to do so). Otherwise, please stop commenting.

**Comment by getCursorsExe** [comment]
Still a good idea, but okay.

**Comment by getCursorsExe** [comment]
Lower accuracy actually means more games playable!

**Comment by getCursorsExe** [comment]
PicoDrive in BizHawk is completely different from upstream. I mean, BizHawk's PicoDrive has the same accuracy as DGen!

**Comment by YoshiRulz** [comment]
Added in https://github.com/TASEmulators/BizHawk/commit/9dcb84336e011af5cd00cead60542b8db17c549e, removed in https://github.com/TASEmulators/BizHawk/commit/fa15e35603f391ae4bdc7670dee8e72d19600ae9.
