### ISSUE TITLE
Desync on 2.4.1

### ISSUE THREAD

**Issue by The8bitbeast** [TASVideos/BizHawk#2070]
This has been happening to me since the TAStudio speed improvements. The desync seems to be a separate issue than the one that was fixed back then.

It happened to me very quickly when TASing James Pond 2 on the Master System (bk2 attached). 

Video (skip to 6:30): https://www.twitch.tv/videos/636227047

[James Pond 2 - Codename RoboCod (E).zip](https://github.com/TASVideos/BizHawk/files/4705397/James.Pond.2.-.Codename.RoboCod.E.zip)

Edit: This has also happened to me on N64 (Banjo-Kazooie) and many other SMS games. I haven't been able to cause it on NES.

**Comment by vadosnaprimer** [comment]
Same as https://github.com/TASVideos/BizHawk/issues/2186 ?

**Comment by alyosha-tas** [comment]
At 6:45 in this video you can see the greenzone gap on click and drag of mouse to paint inputs. 

So, I'm closing this one, it's the same as the one feos mentioned.
