### ISSUE TITLE
Disabling "GB in SGB" throws up an exception

### ISSUE THREAD

**Issue by kamekku14** [TASVideos/BizHawk#2071]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
This happens when I was using the latest version of BizHawk (v2.4.2). I mean, this is ABSOLUTELY wrong.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Launch BizHawk
2. Go to **Config \> Cores** and select **GB in SGB**
3. Load a Game Boy ROM
4. Go to **Config \> Cores** again and deselect **GB in SGB**
5. Reboot the core

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.DllNotFoundException: Unable to load DLL 'Iibgambatte.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  at BizHawk.Emulation.Cores.Nintendo.Gameboy.LibGambatte.gambatte_create()
  at BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy..ctor(CoreComm comm, Gamelnfo game, file, Object settings, Object syncSettings, Boolean deterministic)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.2; Windows 10 Pro 1909; Intel(R) Core(TM) i3-4170 CPU \@ 3.70 GHz

[//]: # "(screenshots, if applicable)"
![image](https://user-images.githubusercontent.com/66167734/83330451-89a68180-a2c1-11ea-83a9-18c67075045b.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by nattthebear** [comment]
Run prereq installer

**Comment by nattthebear** [comment]
@zeromus I will reassert my complaint that it was utter bullshit to change dll deps in a minor version bump

**Comment by zeromus** [comment]
The algorithm which determines whether a user runs the prereq installer does not incorporate the prior or current version number.

**Comment by nattthebear** [comment]
> algorithm 

🤣 We both know that the deps updated due to brownian motion, see https://github.com/TASVideos/BizHawk/issues/2073
