### ISSUE TITLE
Boktai Trilogy Solar emulation 

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#2075]
Hi Dev team here in boktai Trilogy from gba solar emulation dont work as the original Mgba emu have working solar emu that make the game unplayable for TASing is you use a patch for solar emu to rom the emu say warning Unknown ROM

**Comment by YoshiRulz** [comment]
Are you using 2.4.2?

**Comment by DarkLegend1987** [comment]
Yeah friend im test in 2.4.1 and 2.4.2 and the game not detect the sunlight is im use a  game patch for this the emu recognise as warning unknow rom

**Comment by YoshiRulz** [comment]
Patches aren't in the database. Use an unpatched version, or copy its entry into `gamedb_user.txt` and swap out the hash.

**Comment by zeromus** [comment]
we can put patches in our database, FWIW. we don't have anybody in charge of that, but I certainly consider popular patches ID's as legit for inclusion in bizhawk

**Comment by DarkLegend1987** [comment]
Thanks friends they work my friend develop a patch to Fix and swap the hash in game DB the game recognise as good rom
