### ISSUE TITLE
Window size not changing (Saturn, NDS)

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2080]
For the test i'm loaded "Sonic 3D Blast" on Sega Saturn, then clicked "View > Window Size". Tested from 1x to Max. No change.

Same for NDS. Used "Mega Man Star Force 2 - Zerker x Saurian" for test. It works, but not completely

**Comment by Spikestuff** [comment]
For the sake of asking. What's your desktop res?

**Comment by zeromus** [comment]
1x and max are the same :occams_razor: the max is 1x.
