### ISSUE TITLE
PCE Waterbox vs PCE Faust Waterbox, how to switch?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2084]
PCE Waterbox vs PCE Faust Waterbox, how to switch?

**Comment by nattthebear** [comment]
faust is a snes core, maybe you meant pce fast?  there's no picker yet

**Comment by jjfmz42015** [comment]
Pce fast, to be honest i just preffer it off so was asking.

**Comment by jjfmz42015** [comment]
Is there any indication if using PCE accuracy vs fast? On modern PCs fast isnt really required

**Comment by YoshiRulz** [comment]
They're separate cores, so you can look in the status bar for the core name. Not that it matters because there's no way to choose the pce_fast core yet.

**Comment by jjfmz42015** [comment]
> They're separate cores, so you can look in the status bar for the core name. Not that it matters because there's no way to choose the pce_fast core yet.

Ok perfect thanks.

**Comment by jjfmz42015** [comment]
figured out and tested Turbo TurboNyma can be enabled by editing config.ini right now.

**Comment by YoshiRulz** [comment]
Both new PCE cores were added to the core picker menu in ede8877cc.
