### ISSUE TITLE
cannot compile HelloWorld_BizHawkTool example

### ISSUE THREAD

**Issue by AbitFishy** [TASVideos/BizHawk#2085]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
When I try to compile the HelloWorld_BizHawkTool external program example I get this error: 
`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "BizHawk.Client.ApiHawk". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.`

Indeed when I went to include "BizHawk.Client.ApiHawk", I could not find it in the BizHawk dll folder or anywhere in the program files.  I heard something about apihawk changes, but details are not findable. 

### Repro
1.Download and extract BizHawk-2.4.2
2. go to and extract the HelloWorld_BizHawkTool example
3. open solution
4. change framework to 4.8 and add Bizhawk.client.common and Bizhawk.emulation.common dlls as references

BizHawk.Client.ApiHawk.dll is missing and can't be added.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"

- BizHawk 2.4.2, Window 8.1, Visual Studios 2019

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
The `HelloWorld_BizHawkTool.zip` archive in the release is an old version. An up-to-date version is in the repo at [`/ExternalToolProjects/HelloWorld`](https://github.com/TASVideos/BizHawk/tree/f95bcf0e1466156ea51ba12d4d334684d9effdf3/ExternalToolProjects/HelloWorld) (link is old commit before 2.4.1). You can copy its code if you'd like, but be careful with the project file as it includes files from elsewhere in this repo.

ApiHawk changes should be in the release changelog, and I've also put them in my WIP [ext. tool guide](https://github.com/TASVideos/BizHawk-ExternalTools/wiki/Development-quickstart#bizhawk-241242) so they're easier to find.

---

@zeromus I don't want to break anything, could you remove these safely?
https://github.com/TASVideos/BizHawk/blob/79dcfc583d00bf1d2ce6067971708504e76da5f8/Dist/BuildAndPackage.bat#L48-L52
https://github.com/TASVideos/BizHawk/blob/79dcfc583d00bf1d2ce6067971708504e76da5f8/Dist/BuildAndPackage.bat#L82-L83
And this after cf7aabba3:
https://github.com/TASVideos/BizHawk/blob/79dcfc583d00bf1d2ce6067971708504e76da5f8/Dist/BuildAndPackage.bat#L72-L76

**Comment by AbitFishy** [comment]
Thank you, after going through what you posted I was successful.  I just want to leave a note for anyone else a bit confused, "BizHawk.Client.EmuHawk" namespace is in "Emuhawk.exe" and that's what needs to be added as a reference assembly.
