### ISSUE TITLE
N64: Analog Stick Inputs with Physical Controller Binding Inverted and Broken

### ISSUE THREAD

**Issue by nathanisbored** [TASVideos/BizHawk#2086]
### Summary
N64 on v2.3.3 or later is unplayable with a USB controller. The analog inputs don't go full range, sometimes read inputs backwards, and the character flips around.

- Control stick direction never seems to match input display nor character movement if its Y position is in the range [-72, 72]

- Character movement for Y-axis only matches control stick direction (UP makes character move north, DOWN moves south) if the Y position is between [-128, -73] or between [73, 127]

- Character movement for Y-axis only matches input display (positive makes character move north, negative moves south) if the Y position is between [-72,72].

- This phenomenon only seems to happen with a Gamecube controller (others?) and not with eg. an Xbox controller

- This phenomenon only seems to happen on v2.3.3 of Bizhawk or later. It does not happen on v2.3.2 or earlier which suggests a bug in the software and not my controller (exact same settings, calibration, etc).

- Additionally (maybe separately?), a full UP input on the control stick reports a Y position of -82, and a full down input reports 116. I can't seem to get anywhere close to -128 or 127 unless I increase sensitivity to 200%. Unlike the other bug, this happens on both the X and Y axis.

### Repro
1. Plug in controller via USB (apparently not an Xbox controller?)
2. Map direction controls and bind stick
3. Try moving slowly up or down (less than 72 units)
4. I tested this on Ocarina of Time and Tonic Trouble, game doesn't matter

### Host env.
CONTAINS BUG:
- BizHawk 2.3.3; Win10 Pro Intel/AMD
- BizHawk 2.4; Win10 Pro Intel/AMD
- BizHawk 2.4.1; Win10 Pro Intel/AMD
- BizHawk 2.4.2; Win10 Pro Intel/AMD

DOESN'T CONTAIN BUG:
- BizHawk 2.3.2; Win10 Pro Intel/AMD
- prior versions

**Comment by zeromus** [comment]
change config > customize > input method
We need to leave this open though because if this fixes it then there is a serious problem with the opentk stuff. Is it possible opentk has a device database and is inappropriately applying its own calibration?

**Comment by nathanisbored** [comment]
Thanks for the reply, I tried switching from OpenTK to DirectInput, no luck sadly!

I've also been sitting on this report since 2.4 was released. I switched from 2.3.2 when 2.4 first came out, realized controls were messed up, and switched back hoping it was just a fluke or some setting I never noticed. More recently I realized 2.4 had major performance boosts so I tried to switch back and kept having this problem. Gave up today and submitted a report, since it's been keeping me from updating for far too long.

**Comment by nathanisbored** [comment]
NOPE! I was right the first time. Changing the input method _did not_ fix the problem, it just changed the interval from [-72, 72] to [-41, 42]. And it's still only happening on the Y axis! DirectInput method _did_ however fix the full analog range bug I mentioned at the end of the post.

**Comment by zeromus** [comment]
Then don't use your stick to bind "P1 A Up" etc. in the controller configuration.

**Comment by YoshiRulz** [comment]
To be clear, you're certain the input method setting has no effect and you've definitely restarted EmuHawk (not the core) when changing it?

see also #787, #1481, #1585

**Comment by nathanisbored** [comment]
Yes, i closed the program completely and reopened each time. zeromus is right that i had the up,down,left,right directions mapped to the stick, but as long as they are aligned that shouldn't cause any weird behaviors right? it certainly didnt on older versions. but even without those 4 directions mapped, the Y axis is still inverted. -100% sensitivity fixes it, but I have a feeling that is why the 4 directions arent aligned with the analog axis. And nothing weird happens with xbox controler, no matter what input method i use. so theres definitely weirdness going on.

**Comment by zeromus** [comment]
Yes, it will cause weird behaviors. You will notice once you invert the axis. As for why you have to do that, I don't care. if it was possible to make everything work without some people having to flip axes, we wouldnt have to program the provisions for flipping axes. It's a fact of life. Flip it and move on.

**Comment by YoshiRulz** [comment]
GameCube controller doesn't work out-of-the-box on Windows (#1879), so we can blame your drivers for flipping the axis. I set up the orientations in e12b5d813 using the Virtual Pad, and then matched it with an official xbone controller.

**Comment by nathanisbored** [comment]
switch pro does work out of the box tho, if im not mistaken.

thanks for your help btw. perhaps a suggestion would be some kind of simple wizard to help the user debug this kind of thing so this question doesnt come up again. bizhawk sold me on its user-friendliness back in 2013 but as newer features have been added it confuses the average user more i think (ive had great difficulty getting others to switch to bizhawk over the years).

**Comment by zeromus** [comment]
don't care. Half of controllers will work out of the box, and half of them won't. We don't have a controller database. We won't add a wizard. Controls don't work? Rebind your controls. Teach a man to fish, and all that. Wizard adds technical debt and takes time. Educating user adds no technical debt and takes less time.
