### ISSUE TITLE
Shantae (GBC) - few issues

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2088]
Affects devbuild and 2.4.2 version:

GBHawk - after saving in-game and closing or rebooting (Reboot Core), emulator doesn't see in-game saves
SubGBHawk - same result, as in GBHawk
![Shantae (USA) 2020-06-02 19 51 51](https://user-images.githubusercontent.com/21311432/83547819-725ad480-a50b-11ea-8978-94387a986179.png)

Affects only devbuild: 

Gambatte - doesn't loading, white screen

**Comment by nattthebear** [comment]
> Gambatte - doesn't loading, white screen

Confirm that this is happening on both 2.4.2 and dev?

**Comment by medigi** [comment]
Bizhawk stable 2.4.2 - loading fine (Gambatte), while on dev build in same core is white screen

**Comment by nattthebear** [comment]
Gambatte issue is tracked already by #2067 

GbHawk sounds like a path config thing?  @alyosha-tas @YoshiRulz

**Comment by alyosha-tas** [comment]
I can't check this particular game at the moment, but for GBHawk you need to go to:
GB -> settings -> sync settings -> Use Existing SaveRAM (set it to true and reboot core.)

**Comment by adelikat** [comment]
It's not okay for this to be false by default.  That's a terrible user experience.  I'll trust you that it is a helpful thing for developing or debugging cores, but default settings MUST cater to the casual user first and foremost.

**Comment by nattthebear** [comment]
Gambatte issue is fixed ad16294

**Comment by nattthebear** [comment]
GBHawk issue was fixed in some commit
