### ISSUE TITLE
feature request please reconsider

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2097]
Pull request #2096 - remove CoreForcingViaGameDb user option.
remove COreForcingViaGameDb user option. We should not give the user the ability to turn this off. If they are power users and want to overright our db, they can mod the db entries

If somone wants every game to run in a specific core its alot of editing versus the one checkbox that has been there forever and now being removed.

**Comment by nattthebear** [comment]
We generally only gamedb a game to one core if it is not capable of running correctly in other cores.  What instances are you running into where this is a problem?

**Comment by jjfmz42015** [comment]
i havnt run into issues. but for example for SNES I run all the games in BSNES core. For PCE once TurboNyma and Turbo TurboNyma exist I would like to run all in TurboNyma.

Does it really hurt to have this feature? I mean I know Im nobody and who cares what I think. Im just politely asking that its kept there or somewhere if at all possible.

**Comment by YoshiRulz** [comment]
That's not the feature that's being removed.

**Comment by jjfmz42015** [comment]
> That's not the feature that's being removed. Also, in future, discussion of a PR should be kept under that PR and not in a separate issue.

The artifact i downloaded did have that feature removed. Sorry i guess by now i should know how to post on here.

**Comment by YoshiRulz** [comment]
If you want *every rom* to load with core X, select X under `Config` > `Cores`. This will behave as before, with all roms *except those with overrides* using core X.

Previously, you could tell EmuHawk to use core X, even if the rom has a gamedb override for core Y, by disabling `Config` > `Cores` > `Follow GameDB Core Overrides`. Starting with the next release, you will need to add a duplicate gamedb entry for that rom with core X, and it will override the entry with core Y. (This was also possible before, but is now the *only* way to do this.)

This isn't something the average user will be doing, as the core overrides are in place to stop crashes, graphical/audio problems, and desyncs.
