### ISSUE TITLE
ffmpeg add option for 4:3 video?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2102]
ffmpeg add option for 4:3 video?

isd that possible?

even though I have my display set to 4:3 when playing ffmpeg seems to capture 8:7.

Which looks very narrow and tall compared to what I believe it should.

As a temp fix I came up with my own resolution for now. 512x400

**Comment by nattthebear** [comment]
![image](https://user-images.githubusercontent.com/1824709/83893617-2a5fcb80-a71e-11ea-901e-c65fd7b28e80.png)
