### ISSUE TITLE
latest build crashes immediate if you try to record a "movie"

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2103]
latest build crashes immediate if you try to record a "movie"

**Comment by jjfmz42015** [comment]
happens only in latest master bf5aca72

**Comment by adelikat** [comment]
Works for me, need more info

**Comment by jjfmz42015** [comment]
on my system it just closes no warning no error message.


on 2 of my systems.

the previous 5 builds do not.

**Comment by jjfmz42015** [comment]
if i just hit ok to record instant crash, if i go to change file path before clicking ok i get the following unhandled exception(just discovered this)

also just tried appveyor 0.0.0.4775 and 4774 to make sure im right, they work.


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.RecordMovie.BrowseBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
EmuHawk
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/EmuHawk.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
BizHawk.Bizware.BizwareGL
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/BizHawk.Bizware.BizwareGL.dll
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/OpenTK.dll
----------------------------------------
BizHawk.Common
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/BizHawk.Common.dll
----------------------------------------
BizHawk.Client.Common
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/BizHawk.Client.Common.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.0.1
    Win32 Version: 4.6.26919.02
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/System.Drawing.Common.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
BizHawk.Emulation.Common
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/BizHawk.Emulation.Common.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/Newtonsoft.Json.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BizHawk.Emulation.Cores
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/BizHawk.Emulation.Cores.dll
----------------------------------------
SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/SlimDX.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/OpenTK.GLControl.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.1.0.145
    Win32 Version: 1.1.0.145
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/ICSharpCode.SharpZipLib.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
BizHawk.Emulation.DiscSystem
    Assembly Version: 2.4.0.17009
    Win32 Version: 2.4.0.17009
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/BizHawk.Emulation.DiscSystem.dll
----------------------------------------
FlatBuffers.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/FlatBuffers.Core.dll
----------------------------------------
Virtu
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/Virtu.dll
----------------------------------------
SharpCompress
    Assembly Version: 0.24.0.0
    Win32 Version: 0.24.0
    CodeBase: file:///C:/Users/James.UNIROPE/Desktop/PERS%20TEST/BizHawk_Developer-2020-06-05-AppVeyor%200.0.0.4776%20Win%2064%20bit%20007/dll/SharpCompress.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jjfmz42015** [comment]
nevermind now all of a sudden its working, must be something specific to my setups. ill close this. if i re encounter it with better info ill reopen.
