### ISSUE TITLE
GBA - Missing graphics/text

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2105]
This affects some games with same core (mGBA)

Tested games: Boktai - The Sun Is in Your Hand (USA); Cinnamoroll - Koko ni Iru yo. This probably affects many games on gba.

Bizhawk dev build - e69cedf

![Boktai - The Sun Is in Your Hand (USA) 2020-06-06 18 41 46](https://user-images.githubusercontent.com/21311432/83948383-a0028f00-a825-11ea-8d2e-98840c9746bd.png)

Bizhawk stable 2.4.2

![Boktai - The Sun Is in Your Hand (USA) 2020-06-06 18 42 08](https://user-images.githubusercontent.com/21311432/83948409-c1637b00-a825-11ea-830d-45e4e97af01c.png)

Bizhawk dev build - e69cedf

![Cinnamoroll - Koko ni Iru yo (Japan) 2020-06-06 18 39 40](https://user-images.githubusercontent.com/21311432/83948417-cde7d380-a825-11ea-8e80-39e4fed80bb1.png)

![Cinnamoroll - Koko ni Iru yo (Japan) 2020-06-06 18 39 34](https://user-images.githubusercontent.com/21311432/83948416-ccb6a680-a825-11ea-823e-a1360bf641c8.png)

Bizhawk stable 2.4.2

![Cinnamoroll - Koko ni Iru yo (Japan) 2020-06-06 18 40 47](https://user-images.githubusercontent.com/21311432/83948447-ebb53880-a825-11ea-93f9-3ef676797649.png)

![Cinnamoroll - Koko ni Iru yo (Japan) 2020-06-06 18 40 40](https://user-images.githubusercontent.com/21311432/83948446-eb1ca200-a825-11ea-8573-2b63d27a56e0.png)

Latest build mGBA is fine

![mGBA_axI2ASNnkV](https://user-images.githubusercontent.com/21311432/83948601-fae8b600-a826-11ea-80c9-8e5d44548c75.png)

**Comment by RetroEdit** [comment]
A likely cause for this problem has been determined, and the bug's reporter hasn't commented for over a month. If it can't be reproduced and no further info can be given, if makes sense for the issue to be closed.

@medigi If you have any further info to add, please feel free to make another comment on this issue.
