### ISSUE TITLE
Sometimes Clicking an analog cell will jump to different frame#

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2107]
I have been having this annoying problem in tasstudio.  Sometimes when I click an analog cell to input a value, it will instead jump to some entirely different frame#. Is there a setting I am missing to stop that? Scrolling does not make it go away.  If i close out tasstudio/bizhawk and reopen it goes away. This might have something to do with switching branches.

Example
https://www.youtube.com/watch?v=0gFPO52kiw8&feature=emb_logo

**Comment by alyosha-tas** [comment]
#2189 was a duplicate of this one, and is fixed.
