### ISSUE TITLE
Config -- Paths -- Global /Temp not setting correctly?

### ISSUE THREAD

**Issue by bramcn0745** [TASVideos/BizHawk#2118]
### Summary
Attempting to set "Temp" path on the Config - Paths - Global tab, seems to ignore the Base property. If this is intended then please close.

I apologize if this isn't enough information, this is my first bug report.

### Reproduction of error
In Config menu Select Paths, 
On global tab:

1. -    Set BASE to the value ..\\..\
2. -    Set Temp to .\Emulators\BizHawk\BizHawk-2.4.2\Temp

### Output
In the file system the folder structure is built from the executable's location regardless of Base's value.

### Host env.
- BizHawk 2.4.2; Win10 Pro 1903 OS Build: 18362.836; AMD

**Comment by zeromus** [comment]
`..\` (and `....\` for that matter) make no sense for BASE. It's the _base_. Your specification is relative to---what?

**Comment by bramcn0745** [comment]
Base before any path modifications is the current location of the executable, 
Since on the computer in question the absolute path is Y:\emulators\BizHawk\BizHawk-2.4.2\
and as an example, my global roms directory is at  Y:\ROMS
I assumed based on the instructions that ..\..\ set on base would reflect on Y:\ and then all further paths can be set relative to that folder.

**Comment by zeromus** [comment]
No, "base" is not relative to "roms". "roms" is relative to "base". Everything is relative to base, which is relative to nothing. Although I checked now and the UI says it's supposed to be relative to executable... that may have got broken at some point... are you also using lua?

**Comment by bramcn0745** [comment]
No I am not using Lua. this was a fresh install of 2.4.2 and I was copying configurations over from 2.3.2 by hand. 
the issue is the temp property wasn't reflecting correctly to the location. ROMS was set to .\ROMS after base was set to ..\\..\  and does work correctly when I open to select a ROM. The only issue identified was the temp property.

**Comment by zeromus** [comment]
How are you testing how the temp folder works? I just tested it with a state and everything was working fine

**Comment by bramcn0745** [comment]
I only observed the issue when hitting SAVE on the Path configuration dialog box and noticing a new Emulators folder with the folder structure in place.
.\Emulators\BizHawk\BizHawk-2.4.2\Temp was the value entered in the temp property.

**Comment by bramcn0745** [comment]
![image](https://user-images.githubusercontent.com/66711803/84226481-dbb08980-aaaf-11ea-83f9-a4a4086eefdc.png)
Hopefully this will clear up my confusing explanation.

**Comment by zeromus** [comment]
there's a todo for this in `RefreshTempPath` in `PathEntryCollectionExtensions.cs` that dates back to 2018 from ba4b32f619505fbea85992b6fcb5ce874ebb8880
I don't see why I thought it was so hard at the time.
Guess we gotta leave this open now that someone found out

**Comment by bramcn0745** [comment]
Just was reporting an inconsistent behavior on the panel. Sorry.
