### ISSUE TITLE
feature suggestion, make default out of the box PCE core to one of the Nyma cores for newcomers

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#2122]
No disrespect to PCEHawk but now that TurboNyma and HyperNyma work well (Have completed a few games just for the sake of testing nyma) 

For newcomers to get a more compatible experience maybe make the default out of the box experience of Bizhawk to default to Nyma over PCEHawk.

Not a huge deal but a suggestion.

Ideally Ide say TurboNyma but maybe HyperNyma since its cpu and memory usage are only slightly higher than PCEHawk.

Just a thought.

Nyma core has me happy, grateful and excited :)

**Comment by nattthebear** [comment]
I support this.  PCEHawk is mostly for a few extra features that the new cores don't support, now.
