### ISSUE TITLE
[Saturn core] games crash after boot screen

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#2124]
I tested a few games, sonic R and sonic Z-treme(homebrew) and they first come with an error message saying 'program stopped working close window' dialog box. After clicking close program, it runs the boot screen after, and once the boot is complete, it crashes immediately. 

Build: BizHawk_Developer-2020-06-11-201432-#52cc0050b8ca33f23c1c48a14e4c3a0141abbfa0

**Comment by nattthebear** [comment]
Reproed pretty easily on sonic-r; crashes after frame 690
