### ISSUE TITLE
[Saturnus] Reduce the amount of controller ports being used back to 2.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#2128]
Title. If this is already being dealt with then this is probably the most useless bug report I've written up.

Hawk 2.4.2 as a comparison next to latest DevBuild:
![Comparison](https://user-images.githubusercontent.com/12412764/84570365-6eaf3380-add0-11ea-97e5-af963741f712.png)

**Comment by nattthebear** [comment]
Noticed.  Probably can do something clever and useful in the backend, let me think it over.

**Comment by nattthebear** [comment]
Removing HyperNyma as it actually doesn't have a way to turn off multitap, adding PCFX because it has multitap.

**Comment by nattthebear** [comment]
Fixed; these cores will now not show controller config or accept inputs for players that aren't valid by multitap settings.
