### ISSUE TITLE
[Saturnus] Some Controllers Crash in DevBuild and Some Inputs are Displaying !

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#2129]
Well the ones that already existed on 2.4.2 are fine. So this is due to the update.

I'll just do the shorthand version of what inputs:
Digital Gamepad - Up, Down, Left, Right, Start, Left & Right Shoulder.
Mouse - Left, Middle & Right Click.
Steering Wheel - Everything
Mission Stick - B, A, C, Start... and basically everything after R.
Dual Mission - Everything except L & R.
Light Gun - Start & Offscreen

And the ones that crash BizHawk current DevBuild:
3D Control Pad
Keyboard (US)
Keyboard (JP)

**Comment by YoshiRulz** [comment]
see also #2078; controller defs aren't finalised yet

**Comment by nattthebear** [comment]
I will look at the crashing ones when I have a chance.  I can help with the `!` as well, but @adelikat I'll need some guidance on what we're doing with names.  We can just use the old names, or the new names, or whatever...

**Comment by nattthebear** [comment]
The commit was related to the issue, but didn't fix it.  Naughty github!

**Comment by nattthebear** [comment]
Guns, keyboards, and 3d pads should now work.

**Comment by nattthebear** [comment]
I believe this is done, poke me if anything still breaks.
