### ISSUE TITLE
[Virtual Pad] Saturnus controller inputs are no longer appearing.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#2130]
This is probably also already known about.
I'm just putting in an issue report for the sake of putting an issue report.

2.4.2 for reference:
![image](https://user-images.githubusercontent.com/12412764/84570842-3ceb9c00-add3-11ea-8360-6ce7a73810c5.png)

Latest DevBuild:
![error message](https://user-images.githubusercontent.com/12412764/84570807-0f9eee00-add3-11ea-8418-b2e0c2160aba.png)
![virtual pad](https://user-images.githubusercontent.com/12412764/84570811-13327500-add3-11ea-91f9-8535c4a19e42.png)

**Comment by nattthebear** [comment]
@adelikat Anything left to do here now that I removed the extra buttons from mission stick?

**Comment by adelikat** [comment]
fixed
