### ISSUE TITLE
Evaluate suitability of "Zwinder" rewinder replacer

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2131]
It's on a separate branch.  It has exactly three knobs:
1. Amount of ram to use on states, in bytes
2. Target history size in frames
3. Enabled or not (this is handled outside of the class by not even instantiating if not enabled).

The settings are not wired up at the moment.

Does it work well?  The information that it logs to the console:  Is there somewhere we could or should show that?

@adelikat Please look at this as a possible solution to #2104

**Comment by nattthebear** [comment]
There's now a 4th parameter to enable deflate compression

**Comment by adelikat** [comment]
Well, this implementation in master and the old one is deleted so I guess that qualifies as "suitable"  :)
