### ISSUE TITLE
[Saturnus] Restore Resolution Mode

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/BizHawk#2133]
Short explanation: TASVideos Publishers/Encoders don't use PixelPro mode for dumping instead we use [Hardcore Debug](http://tasvideos.org/EncodingGuide/VideoDumping.html#SaturnSaturnPreferences) and making sure what mode we're using is a must.

2.4.2 as Reference on how it's handled:
![image](https://user-images.githubusercontent.com/12412764/84583565-0185b780-ae3d-11ea-8b7e-04caa44b0641.png)

**Comment by nattthebear** [comment]
I believe the current Saturn core should meet all of your needs.  Please reopen ticket if you have specific examples where it does not.

**Comment by Spikestuff** [comment]
I want this ticket to be reopened as this applies to the course of TASing as well.

TASing would be great to be in Mednafen mode for instance to force the game to 4:3 if it has whacky as hell resolutions such Dead or Alive has which has these resolutions in the game; 352x480, 352x240 and 704x480.

This screen is 352x480 normally, mednafen mode forces it to 4;3 and window size x2 as I want it.
![image](https://user-images.githubusercontent.com/12412764/84591881-2ef65380-ae85-11ea-8368-de85ef6c463d.png)

This is what hardcore debug sets it as. Now imagine window size x2 being enabled in this situation.
![hdebug0](https://user-images.githubusercontent.com/12412764/84592055-0cb10580-ae86-11ea-8390-5fb5819c8bb3.png)

Now I can't be certain since DoA crashes on DevBuild Hawk.
But another game that also crashes on the DevBuild of Hawk popped a different resolution directly after bios and answered my question of what default mode was set to before closing out.

DecAthlete has a resolution of 704x240 on boot before settling on 704x480.

Now these are two games I know that has multi resolutions on Saturn, I'm not well versed on this system but if there are more games where actual ingame events are multiple resolution changes due to either menus or fmvs this is extremely important to have on the normal TASing front as well.

This helps the workspace. I don't know why Octoshock can have this but Saturnus which has the same Resolution Modes isn't able to.

The answer to the Encoder preference is met thanks to DecAthlete being able to show it.
However the title is asking for it to be restored and I've shown and stated why here.

**Comment by nattthebear** [comment]
> Now I can't be certain since DoA crashes on DevBuild Hawk.

Which makes me wonder how this ticket was made when you couldn't even verify your problem? 🤔 

Anyway, I've fixed crashing in Dead or Alive (E) and on casual examination it appears to behave exactly as you'd want it to:  The default setting just gives 1:1 framebuffer copies, and the non-sync setting "Constant Framebuffer Size" prestretches everything to make certain casual use easier.  You'd keep that setting off for encoding.

**Comment by Spikestuff** [comment]
> Which makes me wonder how this ticket was made when you couldn't even verify your problem? 🤔

Seriously? I stated why. I asked why. And I was able to prove why.
Do you have reading comprehension issues @nattthebear or are you just into selective reading?

-  But another game that also crashes on the DevBuild of Hawk **popped a different resolution directly after bios and answered my question** of what default mode was set to before closing out.
- DecAthlete has a resolution of 704x240 **on boot**.

You want to see what it looks like?
![image](https://user-images.githubusercontent.com/12412764/84596165-77226f80-ae9f-11ea-8fcb-6b307bf9fd9c.png)
I was able to verify it thanks to this other game that apparently you chose to not read.

**Comment by vadosnaprimer** [comment]
The intended solution seems to be turning on and off Constant Framebuffer Size. When it's off, the result is like with the Hardocre Debug option: window matches the internal res. When it's on, the result is like with the Mednafen option: everything is 480 pixels high.

The problem is with Correct Aspect Ratio option when it's used with Constant Framebuffer Size. If Correct Aspect Ratio is set to true, turning on Constant Framebuffer Size crashes the emu. It somehow makes width of the window way too big and dies in SlimDX:

```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в BizHawk.Client.EmuHawk.IGL_SlimDX9.FreeTexture(Texture2d tex)
   в BizHawk.Client.EmuHawk.TextureFrugalizer.Dispose()
   в BizHawk.Client.EmuHawk.DisplayManager.Dispose()
   в BizHawk.Client.EmuHawk.MainForm.Dispose(Boolean disposing)
   в System.ComponentModel.Component.Dispose()
   в BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Also maybe I'm dumb but it looks like for Saturn games Correct Aspect Ratio is reversed.
