### ISSUE TITLE
nyma cores - reconsider sync settings

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2134]
Nyma cores put a lot of setting into sync settings automatically, due to their design.  Some of them may be moveable out of sync settings but we need to examine code to see if they are actually safe to move out of sync settings, and questions like whether they need reboot.

One such example is the 12 saturn gun crosshairs, although we might reconsider whether that setting is needed at all (could it just be forced to off all the time, and would anyone care?)

**Comment by vadosnaprimer** [comment]
The main principle is ability to dump video authentic to the original console, without emulator hacks and without movie desyncs. In cases when that may conflict with TASer needs, I think we should prefer authenticity and determinism, and whenever those are guaranteed, make those conflicting settings non-sync. If TASer needs compromise authenticity and sync, I feel we should just remove ability to change such settings (compensating via frontend features if possible). Otherwise it may be impossible to have an authentic video dump.

Actual reports in progress...

**Comment by vadosnaprimer** [comment]
**Saturn**

For crosshair colors, the most appropriate feature would be having this support in the frontend for all such cores where analog control is meant to map onto the game screen. If that's not feasible, some indication is helpful to have, but we don't want crosshair to go to official encodes. So it should either be a non-sync setting, or disabled for all movies.

Aspect ratio is handled by the frontend in all variations one may dream of. If having it on for the core applies internal changes to the framebuffer, we also want it off for video dumps. I don't see why it may be needed as either sync or non-sync setting.

Horizontal blur should be non-sync. It seems to be something smarter than whatever our frontend has, so for some users it may be helpful. But if fiddling with it compromises sync, it should be off for movies.

Overscan and scanlines should be non-sync, unless they cause movie desyncs. If they do, they should either be removed, or forced to defaults for movies.

**Comment by YoshiRulz** [comment]
re: crosshair: mice != light guns

**Comment by vadosnaprimer** [comment]
**PCE**

Overscan, sound quality, and aspect ratio are in the same situation as in Saturn.

Some options make emulation inaccurate, but they still look like important sync settings. We may ban some of them in tasvideos rules. May also be helpful to warn about any such settings in their description. For TASes we want those settings to represent accuracy, but I'm not sure about other users who may be making movies.

**Comment by nattthebear** [comment]
@vadosnaprimer ecdfc66 should be a reasonably complete solution to this

**Comment by vadosnaprimer** [comment]
Tested, looks good.
