### ISSUE TITLE
Link local for Pokemon games in GBA

### ISSUE THREAD

**Issue by hawkiq** [TASVideos/BizHawk#2135]
in Pokemon games there is Trade option so we can evolve some Pokemons, I've notices many GBA emulators has option called **Link local** so I can open two emulators windows as separated devices and can trade Pokemons between them. but i didn't find any in BizHawk emulator, is there any script for **link local** or not ?

**Comment by YoshiRulz** [comment]
This isn't currently available for GBA.

If someone was dedicated enough, they might be able to use a Lua script or external tool to link two EmuHawk instances together. Sockets would be the go-to for this, and networking is also theoretically possible (prime example: SM64 online).
