### ISSUE TITLE
Saturn resolutions

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#2141]
If `Correct Aspect Ratio` is set to true, turning on `Constant Framebuffer Size` crashes the emu. It somehow makes width of the window way too big and dies in SlimDX:

```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в BizHawk.Client.EmuHawk.IGL_SlimDX9.FreeTexture(Texture2d tex)
   в BizHawk.Client.EmuHawk.TextureFrugalizer.Dispose()
   в BizHawk.Client.EmuHawk.DisplayManager.Dispose()
   в BizHawk.Client.EmuHawk.MainForm.Dispose(Boolean disposing)
   в System.ComponentModel.Component.Dispose()
   в BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Also maybe I'm dumb but it looks like for Saturn games `Correct Aspect Ratio` is reversed. Clockwork Knight has a visible resolution change when Correct AR is on, but it's seamless when the option is off.

**Comment by nattthebear** [comment]
I wasn't able to reproduce the crash, but I assume some GPUs nope out at the 10k wide texture.

Correct aspect ratio on means that 320 wide is 320 wide, and 352 is 352 wide, and to switch between the two either the frontend changes its geometry (with constant framebuffer off) or you have a giant wide texture (with constant framebuffer on).

Incorrect aspect ratio means that we pretend 320 wide is actually 352 wide in the first place, so there's no resizing with constant framebuffer off and we just double to 704 (remember the high res modes!) with constant framebuffer on.

So the best way to describe correct aspect ratio is that it gives you the data that you could then stretch to the appropriate size to get the right aspect ratio.  But if you don't do your post processing (either video dump or frontend) correctly, you're not guaranteed correct aspect ratio.

I think the best way around the 10k issue is to default to correct aspect ratio off, or fix the underlying frontend problem that necessitated constant framebuffer size.

**Comment by nattthebear** [comment]
I'm seeing a lot of frontend presentation issues in Dead or Alive.  None of these affect video dumping because there, it's just raw pixels to video files that you can then post process to your heart's content.

But the Bizhawk frontend seems to make a giant mess of things.  I have my size default set to 2x, correct aspect on, constant framebuffer off.

The tecmo logo and main title screen do this:
```
For emulator framebuffer {Width=352, Height=512}:
For virtual size {Width=365, Height=256}:
Selecting display size {Width=352, Height=512}
```
This is way off:  With a specified DAR of 1.43, the frontend has chosen a presentation DAR of 0.69 (???).  Using integer scaling, we could easily achieve a DAR of 1.38 with 2x width, 1x height, but somehow that never gets considered.

Other non Saturn cores show similar issues.

**Comment by nattthebear** [comment]
Ewww.

![image](https://user-images.githubusercontent.com/1824709/84828518-2cfed280-aff4-11ea-9a09-5534021020b6.png)

**Comment by vadosnaprimer** [comment]
> I think the best way around the 10k issue is to default to correct aspect ratio off

I agree with this. I don't necessarily agree with how mednafen handles this, but we will not have to suffer from it if correct aspect ratio defaults to off: then switching constant framebuffer on and off will behave like those requested resolution modes that the currently released saturn core has.

**Comment by nattthebear** [comment]
c32ca26790498aba8ab5d19eff10eb0d57ec7c03 defaults correct aspect to off

**Comment by nattthebear** [comment]
> But the Bizhawk frontend seems to make a giant mess of things

All of these issues were caused by me getting the settings wrong.  The fact that Bizhawk's video settings are dense enough to discourage a developer and occasional user... ehh, I'm not too worried.

**Comment by vadosnaprimer** [comment]
To document the proper logic:

If `Correct Aspect Ratio` is disabled, then `Constant Framebuffer Size` starts working as a debug/mednafen mode switch: CFB set to true is mednafen mode, when the screen stays at the same resolution even in the dump; CFB set to false is hardcore debug mode that shows at internal resolution, that goes to dump too. Maybe not exactly identical how mednafen mode worked but that should suffice.

**Comment by zeromus** [comment]
So I still have to find out why there's a >10,000 texture getting created?

**Comment by vadosnaprimer** [comment]
I think it's created because mednafen works that way with Saturn games, `Correct Aspect Ratio`, and `Constant Framebuffer Size` set both to true.

**Comment by zeromus** [comment]
Sorry, I don't know what's going on here. I can't repro with both those options set to true and I don't see anything weird like your screenshot. If mednafen is sending us a 10,000 wide picture then it's a bug in mednafen or a bug in our modifications to mednafen.

**Comment by vadosnaprimer** [comment]
Doesn't seem to crash anymore...
