### ISSUE TITLE
TAStudio bottom UI text can overlap, making it hard to read

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2142]
![TAStudio text overlap](https://user-images.githubusercontent.com/30182911/84831627-351e3880-b01b-11ea-897e-c89fa886922e.png)

It can be worse than this example, but it gets the basic point across

> Name your TAStudio TAS projects something shorter.

Yeah, maybe that's what I should be doing. The default name is the ROM name, which can sometimes be difficult to read unless you have the TAStudio window really wide. I kind of wonder if there's another place to present the selected frames/current frame info, either somewhere else in the interface, or in a row under the saving message component.

**Comment by adelikat** [comment]
Super simple idea, what if it just said "file saved."
The name of the file is already in the title

**Comment by RetroEdit** [comment]
Yeah, that'd work great, since it's redundant to the file in the title.
