### ISSUE TITLE
Burai Fighter - Softlock

### ISSUE THREAD

**Issue by mart0258** [TASVideos/BizHawk#2145]
### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Burai Fighter (USA) (SHA-1: EECC4BCC7697BFFA04C6425D2399E7F451175AD6) will softlock on BizHawk 2.4.2 (x64) (GIT release#546ccda). 

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Launch BizHawk, with the NES Rom.
2. Press start, until you see Stage 1. 
3. Press start, game locks. 

It is not reproduced with Burai Fighter (Japan), nor with Burai Fighter (Europe).  In case of the latter, something called quicknes doesn't work, thus it goes to some fallback, maybe the USA version is missing hash from the blacklist that covers the Europe version.

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by nattthebear** [comment]
Works fine on Ne Shawk

**Comment by alyosha-tas** [comment]
Looks like the PAL version falls back to NESHawk because PAL isn't supported in QuickNES (it's not actually in the black list.)

I'll explicitly add the JP and USA version to the blacklist.

**Comment by nattthebear** [comment]
There must be some other fastish more accurate NES core we can replace quicknes with...  For another ticket

**Comment by jjfmz42015** [comment]
> There must be some other fastish more accurate NES core we can replace quicknes with... For another ticket

Mesen? But you want faster probably? puNES? Netopia UE? How about waterboxing Mednafen??? NES-Nyma? Mednafen nes is FCE Ultra based.

**Comment by nattthebear** [comment]
Yeah, faster than Mesen.  puNES seems interesting.  I've heard that Nestopia is a bit of a mess to work with.  NymaNES would be easiest

**Comment by nattthebear** [comment]
Filed https://github.com/TASVideos/BizHawk/issues/2146
