### ISSUE TITLE
Replace QuickNES with a still quick but more accurate core

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2146]
> Mesen? But you want faster probably? puNES? Netopia UE? How about waterboxing Mednafen??? NES-Nyma? Mednafen nes is FCE Ultra based.

> Yeah, faster than Mesen. puNES seems interesting. I've heard that Nestopia is a bit of a mess to work with. NymaNES would be easiest

**Comment by jjfmz42015** [comment]
> > Mesen? But you want faster probably? puNES? Netopia UE? How about waterboxing Mednafen??? NES-Nyma? Mednafen nes is FCE Ultra based.
> 
> > Yeah, faster than Mesen. puNES seems interesting. I've heard that Nestopia is a bit of a mess to work with. NymaNES would be easiest

Yeah I figured Mesen would be too heavy, on a user experience puNES seems lighter and accurate enough. Nestopia UE is a mess that I know but fast and high compatibility.

I think NymaNES would be the right option seeing as you are currently working with Nyma already.

Nyma is the reason your comment caught my attention :)

**Comment by alyosha-tas** [comment]
How fast does it need to be? QuickNES goes about 2300 fps on my laptop. By comparison NESHawk is way down at 180 and stand alone Mesen is around 600.

If Mesen could be made to do sub frame stuff, it could potentially replace everything by itself.

**Comment by zeromus** [comment]
max-performing quicknes is a cool option for people doing automation and AI stuff. I think it may be worth leaving for that reason. 
as far as I'm concerned, mesen is the reference nes emulator nowadays. I would vote for doing that one next, if only for supporting the reference nes emulator. I don't think nymaNES is a great idea, as the mednafen nes core is really elderly.  I don't know the first thing about puNES but in a world with mesen I'm not sure anything else is needed. Mesen has the HD packs, too. And it's possible mesen integration will earn mesen-s for little added cost.

**Comment by jjfmz42015** [comment]
> max-performing quicknes is a cool option for people doing automation and AI stuff. I think it may be worth leaving for that reason.
> as far as I'm concerned, mesen is the reference nes emulator nowadays. I would vote for doing that one next, if only for supporting the reference nes emulator. I don't think nymaNES is a great idea, as the mednafen nes core is really elderly. I don't know the first thing about puNES but in a world with mesen I'm not sure anything else is needed. Mesen has the HD packs, too. And it's possible mesen integration will earn mesen-s for little added cost.

Mesen would always be my first choice for NES (and Mesen-S is becoming my go to snes) I just thought that since its to replace quicknes with something fast it may be a bit heavy?


For me to be honest for a long time now if Im booting NES its Mesen.

**Comment by Sonia-7** [comment]
I'd vote for Mesen as well. It's superior in accuracy even than neshawk, and the only reason I don't use it is due to the lack of TAS tools.

For the record, there are some games that still don't work correctly in neshawk, as shown in issue #1757. They work correctly in Mesen. Don't know about PuNES, NymaNES or whichever other cores though.

**Comment by jjfmz42015** [comment]
> I'd vote for Mesen as well. It's superior in accuracy even than neshawk, and the only reason I don't use it is due to the lack of TAS tools.
> 
> For the record, there are some games that still don't work correctly in neshawk, as shown in issue #1757. They work correctly in Mesen. Don't know about PuNES, NymaNES or whichever other cores though.

puNES runs those correctly, puNES is still under active development and nice. its my very close 2nd to Mesen.

**Comment by vadosnaprimer** [comment]
Nestopia is the fastest, and the most lightweight, but its code is a c++ nightmare. Mesen is the slowest and the most demanding. puNES is in the middle.

**Comment by adelikat** [comment]
We want MESEN instead of NesHawk.  

The only reasonable alternative to quicknes would be fceux, we need something comparably fast and "accurate enough".  quicknes is more accurate than fceux but much poorer game support.

I don't think there is an emulator that can be "1 emulator to rule them all" here.  If there were it would be mesen in that it's pretty fast for the accuracy level it is, it would just be unfortunate if it were the only choice for heavy botting.

**Comment by jjfmz42015** [comment]
> We want MESEN instead of NesHawk.
> 
> The only reasonable alternative to quicknes would be fceux, we need something comparably fast and "accurate enough". quicknes is more accurate than fceux but much poorer game support.
> 
> I don't think there is an emulator that can be "1 emulator to rule them all" here. If there were it would be mesen in that it's pretty fast for the accuracy level it is, it would just be unfortunate if it were the only choice for heavy botting.

And then Mesen-s for snes? Lol it renders the shadow in ASP and is light enough for an accurate core. That sour mesen is a genius

**Comment by Yave-Yu** [comment]
puNES might be a good choice for alt NES core, fast speed and accurate enough... but it's VRC7 emulation sucks, I don't know is it fixed in newer version... I think NesHawk still needs keep, because some old TASes needs that.

**Comment by adelikat** [comment]
A suggestion of a core without inclusion of some kind of fps calculations isn't helpful.  Until we know that poones is fast enough to consider as a candidate, we can't make a decision to use it.

And I would be surprised if it were fast enough.  It's very hard to be as accurate as it is, and still be fast

**Comment by Yave-Yu** [comment]
How about **Nintendulator**?

**Comment by nattthebear** [comment]
Thanks for all of the feedback.  I've heard a lot from users of QuickNES and now believe that it is our best interests to keep it around.  There doesn't seem to be any other core which approaches its combination of accuracy and speed, being good enough for a lot of games while fast enough for advanced botting.
