### ISSUE TITLE
Exception when opening emuhawk

### ISSUE THREAD

**Issue by Liger0** [TASVideos/BizHawk#2148]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Exception when opening emuhawk or after a bit of playing.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Maybe use my config that were initially made in stable 2.4.2

[config.zip](https://github.com/TASVideos/BizHawk/files/4798564/config.zip)

2. Start up emuhawk. It doesn't always happen so multiple tries are required

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.Exception: Initialization of Direct3d 9 Display Method failed; falling back to GDI+ ---> SlimDX.Direct3D9.Direct3D9Exception: D3DERR_DEVICELOST: Device lost (-2005530520)
   in SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   in SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   in SlimDX.Direct3D9.Device..ctor(Direct3D direct3D, Int32 adapter, DeviceType deviceType, IntPtr controlHandle, CreateFlags createFlags, PresentParameters[] presentParameters)
   in BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateDevice()
   in BizHawk.Client.EmuHawk.IGL_SlimDX9..ctor()
   in BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   --- Fine della traccia dello stack dell'eccezione interna ---
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk dev build pre-2.5 (commit 01e3a6c); Win10; AMD; Win10 ; AMD

[//]: # 

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by zeromus** [comment]
This is due to a bug in your GPU or an instability in your system, or some other junkware or security software being installed. Try cleaning your system and updating your drivers.

**Comment by Liger0** [comment]
It doesn't happen in 2.4.2

**Comment by zeromus** [comment]
This is due to a bug in your GPU or an instability in your system, or some other junkware or security software being installed. Try cleaning your system and updating your drivers.

**Comment by Liger0** [comment]
It seems 2.4.2 is indeed also affected. 
So bad I can't use bizhawk on this system, as this persists even after reinstalling windows and latest amd drivers.

**Comment by nattthebear** [comment]
OpenGL might be less broken, could try that
