### ISSUE TITLE
Get Win7 freezed when open BizHawk 2.4.2 with DS4Windows.

### ISSUE THREAD

**Issue by catscarlet** [TASVideos/BizHawk#2150]
I just updated BizHawk from 2.3.2 to 2.4.2, and got Windows freezed when open BizHawk 2.4.2 with DS4Windows.

Step:
1. Open my computer with booting up Windows 7 x64
2. Open DS4Windows 2.1.3 with Sony DS4 connected
3. Open BizHawk 2.4.2

And then System freezed about 12 seconds with absolutely no mouse or keyboard responding.

I know this may related to DS4Windows's Exclusive Mode issues, but BizHawk 2.3.2 has no problem with DS4Windows. At least I think I should leave a message to let others know it.

**Comment by YoshiRulz** [comment]
So you can still use EmuHawk with your PS4 controller, it just freezes for a bit on startup?

**Comment by zeromus** [comment]
if you had said bizhawk froze, then this would be interesting to us. but since your whole OS froze, it is definitely due to a bug in DS4Windows.

**Comment by Spikestuff** [comment]
> DS4Windows

Windows 7 is able to detect it as a gamepad (well "wirless controller" and is able to use both analog sticks and the face buttons.
You do not require that program to be able to run BizHawk with your PS4 controller.

**Comment by zeromus** [comment]
If it's so easy, why is there a program to do it? Nothing about bluetooth is easy on windows. For the record, I'm not going to tell anyone they won't use whatever desperate measures they feel they had to use to get a gamepad not meant to work on windows, to work on windows.

**Comment by catscarlet** [comment]
Sorry I didn't mention I use DS4 wired with USB cable, not wireless.
I use DS4Windows because I use a input monitor which can only recognize XInput but DS4 works as DirectInput on win7. Not only that, but also a lot windows game can only work fine with XInput instead of DirectInput too.
I don't use Win10, and will not. (My new computer use Linux so pls don't recommend me Win10)

**Comment by Spikestuff** [comment]
That's not an issue to BizHawk.
Like already mentioned. BizHawk already accepts the PS4 controller without the use of external programs such as DS4Windows.
