### ISSUE TITLE
shortcuts not always work

### ISSUE THREAD

**Issue by Liger0** [TASVideos/BizHawk#2151]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Shortcuts, like the default Shift+number or Fn for save states don't always work.
Like, 1/5 of the times nothing happens

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.2, latest nightly; Win10 Pro 1909; AMD Ryzen/AMD RX Vega

**Comment by zeromus** [comment]
We already know your system is unstable. 
Most likely the emulator is running at 1 frames per second while your system is glitching and it is missing the keystrokes. Check your keys for crumbs, too.

**Comment by YoshiRulz** [comment]
I assume by "latest nightly" you mean dev builds. Try changing `Config` > `Customize...` > `Input Method` to DirectInput and restarting EmuHawk.

**Comment by Liger0** [comment]
> 
> 
> We already know your system is unstable.
> Most likely the emulator is running at 1 frames per second while your system is glitching and it is missing the keystrokes. Check your keys for crumbs, too.

It's very stable at the max fast forward speed allowed which is 400%.
Keys are pretty fine. Also never had this issue with desmume and I use it daily still.
Funny enough, Dolphin presents the same issue but worsened exponentially. 
Hotkey inputs basically work one time out of 10+.

> 
> 
> I assume by "latest nightly" you mean dev builds. Try changing `Config` > `Customize...` > `Input Method` to DirectInput and restarting EmuHawk.

Yes, that's what I mean.
And yes, the Direct Input absolutely worked!
This issue is just for hotkeys and not for gaming buttons.
