### ISSUE TITLE
`emuVersion` in movie headers should be handled better

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2152]
My original concerns detailed below have been fixed by 0b07e38. The suggestion of storing each emulator version that edited a file may be a good one, but it's a bit outside of the scope of my initial problem. If there's a compelling reason to store a list of emulator versions, feel free to open a new issue and/or pull request discussing it.

----

Here's some sort of minor, but also important thing that bothers me about the `emuVersion` field in movie headers: it's set once and then never touched again.

So if I start a movie in BizHawk 2.2, then edit that same movie to resync in 2.3, and then again in 2.4, the movie header will still contain `emuVersion Version 2.2`.

In my opinion, this field should be updated any time a movie is edited by BizHawk and saved. That way, the header is always up-to-date on the BizHawk version used to edit the movie. This isn't always a perfect solution, namely for incomplete resyncs, but I'd argue that's more a user issue than an issue the emulator problem, since a syncing movie is an arbitrary concept to the emulator (unless the user can provide objective parameters for what final game state counts as a synced movie, technically possible, but probably best accomplished through Lua scripts at the moment). Having `emuVersion` update with each edit would be better handling than the current model where `emuVersion` is static and can easily become out-of-date.

If desired, there could also be an `originalEmuVersion` that denotes the original version used to create the movie, basically serving the same purpose that `emuVersion` currently serves.

**Comment by vadosnaprimer** [comment]
Or just append tot he same line, with some delimiter.

**Comment by RetroEdit** [comment]
Yeah, that's certainly a possible resolution. The only hesitation for me in thinking about that is if someone edits in a later version and then subsequently goes back to an earlier version, but I would prefer having a complete list even if it's verbose.

**Comment by RetroEdit** [comment]
@vadosnaprimer Are you happy with 0b07e38b as a resolution? Or do you think there's value in storing every single emulator version that has ever edited a movie file?

One benefit of what I did is that it's completely backwards-compatible; `emuVersion` still contains only one movie version. I suppose we could alter the meaning of it or add another field that stores a list of emulator versions, but that adds extra code for parsing, storing, and maintaining a list of movie versions that may have negligible benefit.

**Comment by vadosnaprimer** [comment]
OK
