### ISSUE TITLE
EmuHawk: Add 100% speed hotkey.

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2154]
Press this hotkey can make speed change to 100% directly.

**Comment by zeromus** [comment]
It will take several keystrokes to get to your non-100% target speed, why not several more keystrokes to get back to 100%?

**Comment by dart193** [comment]
Because FCEUX has change to 100% directly key, which is immediately missing from Biz for people who used this key. but moved to Biz from FCEUX, me included.

**Comment by zeromus** [comment]
Ohhhh you really knew the magic words
