### ISSUE TITLE
Crash on loading Sega Mega Drive games.

### ISSUE THREAD

**Issue by dart193** [TASVideos/BizHawk#2156]
System.IndexOutOfRangeException: Индекс находился вне границ массива. //Translates as "Array index out of bounds." exception.
   in Bizhawk.BizInvokeProxyLibGPGX.gpgx_put_sram(Byte[] , Int32 )
   in BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.StoreSaveRam(Byte[] data)
   in BizHawk.Client.EmuHawk.MainForm.LoadSaveRam()
   in BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args)
   in BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args)
   in BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   in BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

The error is given when almost any given SMD game is loaded for the second time. Examples include Skitching, Road Rash 3 and basically any.

Note that all games that use SRAM work fine. Includes Phantasy Star games, Shining force games.

It looks like 0 byte SRAM file is created which is then loaded. It works fine with other cores/worked fine in at least 2.3.2, but SMD core crashes if 0 byte SRAM file exists for a game that does not uses SRAM.

**Comment by nattthebear** [comment]
If I manually create a 0 byte saveram, I see the error message you're describing, but I can't figure out any way to actually get the core to create a 0 byte saveram.

**Comment by nattthebear** [comment]
I've added extra hardening for your situation; even if there is a 0 byte file, things won't crash now, but I still don't understand how they're being created.

**Comment by dart193** [comment]
I have noticed that unlike many emulators, when you close the emulator with Alt+F4, SRAM is not flushed. As such, I bound "Flush SRAM" on the same key as "Save state" so that I can be sure that SRAM is saved. Unfortunately, it creates a 0 byte file if there is no SRAM, and this bug triggers on 2.4.2 SMD core but did not triggered before.

Note that it was a long time this problem happened, and maybe Biz now always saves SRAM on exit, but I still ahve this key.

**Comment by YoshiRulz** [comment]
`Alt+F4` isn't a hotkey (at least, not one that we control) so it's hard to change its behaviour. However, SaveRAM is flushed automatically when you close a rom. `Ctrl+W, Alt+F4` should do what you want without having to mess w/ savestates.

**Comment by RetroEdit** [comment]
Note that automatic saving is not intended to be the main way of saving; you're supposed to manually save and backup your save files. (See disclaimer of [In-game saves](https://github.com/TASVideos/BizHawk#in-game-saves).

**Comment by zeromus** [comment]
we can control what alt+f4 does. it should be flushing the sram. if it isn't in some case, that's a bug and please tell me specific examples.

**Comment by dart193** [comment]
If what RetroEdit says is true, then I am indeed supposed to press "Flush SRam" before closing the game. Problem is, it creates empty file if there is no SRAM instead of not creating any file at all and I consider this as a bug too.

As of examples, I think I have lost some progress in PSX Diablo when I closed the emulator. I used "X" button instead of Alt+F4. I have indeed noticed that Close ROM ALWAYS creates SRAM, if it exists. So another thing to check might be to make sure than when BizHawk exits, it first executes Close ROM function and only then actually exits.

**Comment by zeromus** [comment]
as far as I can tell, the core flushes save ram on alt+f4. possible explanations are
1. You have found one of the examples I just found where this may not work
2. The emulator is crashing when exiting before it gets a chance to save

in case it's #1, please confirm exact repro steps for me

**Comment by dart193** [comment]
Since I save like mad, I would have to go out of my way now for that. But should I ever get this issue again, I will try to reproduce it and will file a new ticket then. For now, I just want for Biz not to create 0 byte files on forced flush.

**Comment by zeromus** [comment]
ok
1. it doesnt anymore
2. it wouldnt crash now, if it did
