### ISSUE TITLE
HQ2X BROKE  last few appveyor builds

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#2160]
HQ2X BROKE  last few appveyor builds

makes a mess.

**Comment by jjfmz42015** [comment]
i believe it broke with this

**Comment by zeromus** [comment]
omfg do you actually use all these filters

**Comment by jjfmz42015** [comment]
> omfg do you actually use all these filters

To be honest no.

Testing :)

I use bilinear only. Force aspect 4:3

I only report this stuff cause Im assuming I help when I do this?

**Comment by zeromus** [comment]
Thanks for making these helpful bug reports
