### ISSUE TITLE
[Saturn core] Indepence day softlocks at beginning.

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#2162]
After you see fox interactive logo play, the game softlocks and doesn't go any further.

commit: b9f59337

Im using the linux build, but that shouldn make any difference.

**Comment by YoshiRulz** [comment]
Saturnus behaves very differently on Linux.

@natt wbox shenanigans

**Comment by nattthebear** [comment]
This better have Will Smith in it

**Comment by nattthebear** [comment]
@InfamousKnight Does this issue happen in upstream Mednafen?

**Comment by nattthebear** [comment]
I'm seeing the same issue in Windows, so it's probably just a vanilla core bug.

**Comment by InfamousKnight** [comment]
I haven't tried upstream yet, where's the build for linux?

**Comment by nattthebear** [comment]
https://mednafen.github.io/

**Comment by InfamousKnight** [comment]
Softlocks in upstream as well.

**Comment by YoshiRulz** [comment]
Changelog for 1.26.0-UNSTABLE claims this was fixed.

see also #2464

**Comment by InfamousKnight** [comment]
Cool, thanks for bringing that to my attention. I'll test it once the cores are updated
