### ISSUE TITLE
good dump report as ?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2163]
The following no-intro verified dump shows as ? not as good in bizhawk

Haven't noticed others yet

Shadow Dancer - The Secret of Shinobi (USA, Europe) (Steam Version)
SHA1:A3A1C2CB8BD202C5E1B9745B35B2FFB12B2B90F5
MD5:4BBE8B456F87A22062A98A0D50E41CD5

**Comment by zeromus** [comment]
we don't have an exhaustive database. especially not games that were released last week as hacked versions on steam. (and in particular, we dont have anything seeded from no-intro database). if you are going to start hunting for games that need to be whitelisted, please accumulate them in one ticket.

**Comment by jjfmz42015** [comment]
> we don't have an exhaustive database. especially not games that were released last week as hacked versions on steam. (and in particular, we dont have anything seeded from no-intro database). if you are going to start hunting for games that need to be whitelisted, please accumulate them in one ticket.

ok, not complaining, first time I saw a verified no intro with a ?

Just trying to be helpful. Maybe Im annoying. Ill go away.
