### ISSUE TITLE
Mid-frame execution callbacks can cause lag to be applied to the wrong frame

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2165]
The title says it all, but quick summary:

I opened Final Fantasy I & II: Dawn of Souls, loaded a script ([weird_lag.zip](https://github.com/TASVideos/BizHawk/files/4815591/weird_lag.zip)), and found that TAStudio was blatantly retroactively mismarking frames as lag.

This video is more expressive than my text explanation can be: https://www.youtube.com/watch?v=A-Tczsxuv1A

I've also explained *why* the problem occurs in my most recent comment.

**Comment by nattthebear** [comment]
I love Dawn of Souls.  Dunno why.

To clarify:  If you try to do the same exact inputs in the same exact core with no LUA involvement and no Tassssssssstudio involvement, does the lag flag work correctly?

**Comment by RetroEdit** [comment]
Uh, doing the *exact* same inputs isn't technically possible because of the callback (though it does fire on a consistent frame), but otherwise I'll try that out.

**Comment by nattthebear** [comment]
I mean the exact same inputs to the emulated game.  I'm just trying to see if this is a core issue or a movie issue or a tassssssssssstudio issue.

**Comment by RetroEdit** [comment]
For better and more concise expressiveness of the problem, I made a video: https://www.youtube.com/watch?v=A-Tczsxuv1A

This problem can be explained in three easy steps:

1. A frame is running as normal

https://github.com/TASVideos/BizHawk/blob/e4e078a1c97ed706f5e60475953548c0ba6dda7e/src/BizHawk.Client.EmuHawk/MainForm.cs#L2896-L2898

2. And suddenly gets interrupted by a callback mid-frame.

3. But it just barrels along with continuing to `MovieSession.HandleFrameAfter()` after the callback is resolved, and within there it takes the lag value that was calculated during the frame in which the callback hit. The problem is, it's no longer *at* the frame that comes right after the frame the lag value was calculated for; it's now at an earlier frame because the greenzone was modified.

So essentially, at the very least mGBA's callbacks can have messy interactions with TAStudio, but I could imagine other cores having this problem as well.

**Comment by nattthebear** [comment]
Unless tasstudio code is about 4000 times more robust than I think it is, the appropriate action here is to throw an error or deadlock or crash the application entirely when a midframe call like this is attempted

**Comment by vadosnaprimer** [comment]
Yeah this is just wrong approach with the current state of things. Frame granularity is what everything depends on, you can't randomly throw away parts of it and magically fix everything related to it. Let the frame end properly, then lag info will obviously be there.

**Comment by adelikat** [comment]
This zip file is corrupt, can somebody paste the script contents?

**Comment by RetroEdit** [comment]
```lua
local SHIP_END = 874
local game_delay = 0
local MAX_WAIT = 5

local function fifteen_puzzle_seed()
	tastudio.submitinsertframes(SHIP_END + game_delay, 1)
	tastudio.applyinputchanges()
	tastudio.submitinputchange(SHIP_END + game_delay, 'A', true)
	tastudio.applyinputchanges()
	game_delay = game_delay + 1
	if game_delay == MAX_WAIT then
		console.log("Script paused.")
		client.pause()
	end
end

event.onmemoryexecute(fifteen_puzzle_seed, 0x0803C23C, "15_puzzle_seed")
```

**Comment by RetroEdit** [comment]
```lua
local SHIP_END = 874
local game_delay = 0
local MAX_WAIT = 5

local function fifteen_puzzle_seed()
	tastudio.submitinsertframes(SHIP_END + game_delay, 1)
	tastudio.applyinputchanges()
	tastudio.submitinputchange(SHIP_END + game_delay, 'A', true)
	tastudio.applyinputchanges()
	game_delay = game_delay + 1
	if game_delay == MAX_WAIT then
		console.log("Script paused.")
		client.pause()
	end
end

event.onmemoryexecute(fifteen_puzzle_seed, 0x0803C23C, "15_puzzle_seed")
```

**Comment by adelikat** [comment]
Seeing the script I think I agree with natt, we are no where near being ready to deal with a script like this.  Tastudio can't deal with applying input at any point in a frame like this.

There is an alternative here too I think.  Rather than applying input changes mid-frame, I think you could use joypad.set() instead, and then allow tastudio to pick up those inputs and provide lag info on the frame boundaries when it expects

**Comment by RetroEdit** [comment]
For sure, there are ways of restructuring this script to ensure the frame-changing operations occur at the end of frames. `joypad.set` isn't quite powerful enough alone because it can only affect the next frame, not rewrite prior frames.

I also don't think this is a TAStudio-specific problem. I'll be if you just loaded a savestate within the callback, you'd have the same problem.

**Comment by adelikat** [comment]
Well, it isn't one problem, more like 2342398234 little problems, there's no end to the bugs you could find once you start doing things during a callback

**Comment by YoshiRulz** [comment]
Is there anything actionable here?
