### ISSUE TITLE
TAStudio: Inconsistency between rerecords and greenzone behavior when pasting inputs

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2168]
When you paste inputs, there's some logic in TAStudio that checks whether the greenzone should be invalidated when a paste section start precedes the playback cursor. In the case that the greenzone *isn't* invalidated, it shouldn't add a rerecord, because nothing is being rerecorded. In practice, pasting in this manner can be a way to record inputs for the first time, merely at consistent intervals.

**Comment by adelikat** [comment]
" In the case that the greenzone isn't invalidated, it shouldn't add a rerecord"
Agreed...that's why it doesn't add a rerecord.  I tested and I could find no example of an inconsistency here.  If greenzone is invalidated, rerecord is added, else it isn't

**Comment by RetroEdit** [comment]
I'll do some tests and post a video tomorrow. I've noticed this for a while.

**Comment by adelikat** [comment]
I put in a fix with 4a6b3e407a8a4ef61896bdf1393c4e30eaf8637d but it was confirmed to not help the situation.  The commit was still a better handling of the situation where the LagLog and StateManager might be out of sync, so I think it was a positive so I merged it.

**Comment by adelikat** [comment]
Please provide repro steps

**Comment by RetroEdit** [comment]
I really don't remember this issue and can't discern what I originally meant. I'm pretty sure something is a bit off, but I'll point it out if I notice it again with better repro steps.
