### ISSUE TITLE
Exception when trying to choose a ROM when a game is loaded via Libretro core

### ISSUE THREAD

**Issue by alb3530** [TASVideos/BizHawk#2176]
(This happens only when option **Always use recent path for ROMs** in Config -> Paths... is disabled)

Start any game using a Libretro core.

A exception will appear if you try at least one the actions below (that cause a file picker to appear):

-Open a ROM (File -> Open ROM, or by using Ctrl + O)
-Click any of the "Launch Game" buttons in the "Open Advanced" dialog
-Try to import a movie using File -> Movies -> Import Movies

Exception:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.PathEntryExtensions.RomAbsolutePath(PathEntryCollection collection, String systemId) in C:\BizHawk\src\BizHawk.Client.Common\config\PathEntryCollectionExtensions.cs:line 212
   at BizHawk.Client.EmuHawk.MainForm.OpenAdvancedMenuItem_Click(Object sender, EventArgs e) in C:\BizHawk\src\BizHawk.Client.EmuHawk\MainForm.Events.cs:line 361
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by alb3530** [comment]
It seems like the problem is when the emulator tries to get the absolute ROM path, it looks for it on a PathEntry collection, searching for a path for "Libretro" system and "ROM" type.
Once the path collection doesn't have a match for this, it remains null, which causes the exception.

It happens in **\src\BizHawk.Client.Common\config\PathEntryCollectionExtensions.cs , line 210**:

`var path = collection[systemId, "ROM"];`

The default values for this collection can be found at **\src\BizHawk.Client.Common\config\PathEntryCollection.cs, line 292**

`
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Base", Path = Path.Combine(".", "Libretro"), Ordinal = 0 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Cores", Path = Path.Combine(".", "Cores"), Ordinal = 1 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "System", Path = Path.Combine(".", "System"), Ordinal = 2 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Savestates", Path = Path.Combine(".", "State"), Ordinal = 3 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Save RAM", Path = Path.Combine(".", "SaveRAM"), Ordinal = 4 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Screenshots", Path = Path.Combine(".", "Screenshots"), Ordinal = 5 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Cheats", Path = Path.Combine(".", "Cheats"), Ordinal = 6 },
`

All other systems have a default value for "ROM" type, *except* Libretro.

Then what I did was adding a additional PathEntry for system "Libretro" and type "ROM" inside this collection, and the problem seems to be fixed.
It's now like this:

`
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Base", Path = Path.Combine(".", "Libretro"), Ordinal = 0 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "ROM", Path = ".", Ordinal = 1 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Cores", Path = Path.Combine(".", "Cores"), Ordinal = 2 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "System", Path = Path.Combine(".", "System"), Ordinal = 3 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Savestates", Path = Path.Combine(".", "State"), Ordinal = 4 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Save RAM", Path = Path.Combine(".", "SaveRAM"), Ordinal = 5 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Screenshots", Path = Path.Combine(".", "Screenshots"), Ordinal = 6 },
			new PathEntry { System = "Libretro", SystemDisplayName = "Libretro", Type = "Cheats", Path = Path.Combine(".", "Cheats"), Ordinal = 7 },
`

I don't know if it could cause some side effects, and even if it couldn't, maybe it's not a correct fix from the code's design philosophy standpoint.

Maybe due to its nature, it doesn't make sense for Libretro to have a ROM path, so it could be tested if system is "Libretro", and if true, do some other thing in order to avoid the null exception.

**Comment by getCursorsExe** [comment]
Well, something similar happens in BizHawk 2.6.2. We also get an exception when trying to load a ROM with Libretro, but this time we only get this with cores that makes WinForms windows pop up (like Genesis Plus GX Debugger), and also under specific circumstances within the ROM, like TiTAN Overdrive 2.
