### ISSUE TITLE
[Regression] TAStudio doesn't restore cursor to the frame it was saved

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2181]
A user commented on Discord that the latest version of BizHawk doesn't properly restore the cursor to the frame it was saved. Instead, the cursor always starts on frame 0.

From my own testing, TAStudio started loading at frame 0 in 2.4.1. In 2.4, it loads at the frame the cursor was at when saving.

**Comment by adelikat** [comment]
Duplicate of #2063

**Comment by RetroEdit** [comment]
Whoops, my bad. Forgot to search before filing for that one.
