### ISSUE TITLE
[TAStudio] Clicking on analog box jumps back up to last input changed

### ISSUE THREAD

**Issue by Blazephlozard** [TASVideos/BizHawk#2189]
Clicking on an analog box in TAStudio moves the cursor back up to the last input changed. I have a video here showing it a bit.

https://youtu.be/YLbU2nBgrEg

I have tested this occurring in Kirby Tilt n Tumble, and Banjo-Kazooie (wanted to make sure it wasn't a niche case, as Tilt n Tumble is the definition of a niche case).

It occurs for me in anything 2.4 or later, but not in 2.3.

Having "Follow cursor" unchecked prevents it from happening, but it still seems like a regression, and analog in tastudio is annoying enough as it is.

**Comment by vadosnaprimer** [comment]
Worth a bisect for someone who has time on it.

PS: Thanks for voice comments, they make it so much easier to understand quickly.

**Comment by alyosha-tas** [comment]
Happened between 2.3.1 and 2.3.2, I'll try to narrow it down a bit more, there was a batch of TAStudio commits in there.

**Comment by alyosha-tas** [comment]
https://github.com/TASVideos/BizHawk/blob/be2ba08c10c1a608e35bdc3a57ffadb7d42fd828/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs#L685

I'm pretty sure this jumptogreenzone call shouldn't be there. A single click on an analog cell does not edit it. I tested without it and it seems to work fine. Single and double clicks to not trigger an edit to greenzone and a jump, but edits to the value do. I don't know all the ways to edit analog values though, so should be tested more before committing.

**Comment by Blazephlozard** [comment]
The big cursor jumps upward to the last edited input (instead of to where the greenzone is invalidated) still happen, but only on modifying an analog value as opposed to just clicking on the entry box. This isn't too troublesome when typing values in but can really cause problems when click-and-dragging analog input, as it'll drag the entire way up, ruining the greenzone and everything.

Quick gif here: https://i.gyazo.com/8d95445364e206e0c9d68a4c0b031e0c.mp4

**Comment by alyosha-tas** [comment]
I made some additional fixes, please test.

**Comment by Blazephlozard** [comment]
Yep, analog cursor jumping seems to be fixed now, thank you so much!
