### ISSUE TITLE
Jump List Causes NRE in TAStudio

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2191]
I found this obscure error while trying to track down other issues in TAStudio. I don't know why it is happening, but it is consistently reproducible:

1. download and extract the dev build
2. open a game (i used NES and a2600) and record a bk2 of some frames (exact amount doesn't matter.)
3. stop the movie
4. open TAStudio and using the open menu option, load your newly made bk2
5. hit ok to accept the import window
6. you should get this error:

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.TasMovie.get_Item(Int32 index)
   at BizHawk.Client.EmuHawk.TAStudio.TasView_QueryRowBkColor(Int32 index, Color& color)
   at BizHawk.Client.EmuHawk.InputRoll.DoBackGroundCallback(List`1 visibleColumns, Rectangle rect, Int32 firstVisibleRow, Int32 lastVisibleRow)
   at BizHawk.Client.EmuHawk.InputRoll.DrawBg(List`1 visibleColumns, Rectangle rect, Int32 firstVisibleRow, Int32 lastVisibleRow)
   at BizHawk.Client.EmuHawk.InputRoll.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 
```

(I should note that on my local build I get the error under slightly different circumstance, by importning one bk2 then closing that and importing another bk2 from a different system (ie first one from NES second from A2600.)

Somehow, this exception is caused by:
https://github.com/TASVideos/BizHawk/blob/eede99a5052ae92c4f23223c2dc372207a8ff569/src/BizHawk.Client.EmuHawk/JumpLists.cs#L53

How? Why? I have no idea. I comment out the call in MainForm:

https://github.com/TASVideos/BizHawk/blob/eede99a5052ae92c4f23223c2dc372207a8ff569/src/BizHawk.Client.EmuHawk/MainForm.cs#L3672

and then the error no longer happens. Also, I'm not sure what this even does.

**Comment by adelikat** [comment]
I suspect the JumpList is a red herring.
But what it does it put the rom in the EmuHawk jump list (the list that shows up when you right-click emuhawk from the windows task bar)

**Comment by nattthebear** [comment]
What made you suspect JumpList?  They don't seem related.

**Comment by alyosha-tas** [comment]
I just console.WriteLine in between different instructions. The last one to print was the one before the JumpList call. The one after it doesn't print until I acknowledge the exception. Doesn't make sense to me either.

**Comment by adelikat** [comment]
I no longer get this error based on these repro steps.  I've done a number of things since this this report that potentially fix it.  @alyosha-tas : can you try again and see if you can still reproduce?

**Comment by alyosha-tas** [comment]
I no longer get the error as above, however I do still get it if I open the bk2 twice. (i.e. repeat steps 4 and 5 above.)

Even if I close emuhawk and reopen it, then try opening the bk2 again it will throw the error, even though it still correctly creates a new tasproj each time.

**Comment by adelikat** [comment]
I'm getting no error when opening the same .bk2 multiple times.  I even tried to use the recent menu and everything seemed to work

**Comment by adelikat** [comment]
I put in some defensive null checks that might be your issue. I saw it once but couldn't consistently reproduce, and you didn't mention what the error was, but maybe this fixes it?

**Comment by alyosha-tas** [comment]
The error still occurred, but I checked the path in the first post and narrowed it down to another instance of Emulator being null.

Adding in a null check fixed the problem.

I think this has something to do with the mouse being over the piano roll when the 'ok' button is clicked, causing an immediate redraw? not certain but maybe that's why it's not very consistent.
