### ISSUE TITLE
Nintendo 64 games Textures all messed up with GLideN64 2.4.2 (tested with "Conker Bad Fur Day")

### ISSUE THREAD

**Issue by riccardofrosini** [TASVideos/BizHawk#2192]
I recently downloaded version 2.4.2 of BizHawk and the game "Conker Bad Fur Day" had all the textures messed up when running it with out of the box settings (i.e. using GLideN64 with its default settings). The games used to work fine with version 2.3 with the GLideN64 plugin (again all the default settings where used). The game works properly when using GLide64mk2 with with both versions of the software.

I did a comparison of GLideN64 settings for 2.4.2 and 2.3 but they were exactly the same.
I also tried to update the bizhawk prereqs to version v2.4.8_1 from 2.1 but the issue is still there.

![Immagine](https://user-images.githubusercontent.com/62237321/86467764-e6b4ad80-bd2d-11ea-8353-4de30e570ff9.png)
![Immagine1](https://user-images.githubusercontent.com/62237321/86467772-e9af9e00-bd2d-11ea-99ff-6c92680ff3a0.png)

**Comment by Spikestuff** [comment]
Also using GlideN64 (2.4.2):
![image](https://user-images.githubusercontent.com/12412764/86468649-353c6900-bd7b-11ea-8615-aef0557d16e4.png)

It'd be nice to know what your specs are and if it's a laptop or not as a note.

**Comment by YoshiRulz** [comment]
This looks like what's happened to some other users with an Intel CPU and no dedicated graphics card. (Not sure what being a laptop has to do with it, that factor hasn't come up before.) GLideN64 is known to not work on Intel iGPUs: #1820. If an older version works for you, that corroborates some other reports: #1662, https://github.com/TASVideos/BizHawk/issues/1820#issuecomment-636275469, #2167.

---

Off-topic: I noticed you're on Win10 with an Italian keyboard layout, does #1923 affect you?

**Comment by riccardofrosini** [comment]
I have a windows 10 machine I have a dedicated graphic card NVIDIA GeForce 820M. Intel i7-4710HQ CUP, 8GB of RAM
I just noticed that @YoshiRulz is right my computer was using by default the Intel(R) HD Graphics 4600 which I now disabled and by using the dedicated graphic card the game is now working properly. Although, I still wonder why version 2.3 was working fine.

**Comment by Spikestuff** [comment]
@YoshiRulz there used to be issues with Glide64 and GlideN64 and laptops (with nvidia). The solution was basically...
- Open NVIDIA control panel
- Manage 3D Settings
- Program Settings
- Add > BizHawk
[And if I recall correctly]
- Change preferred graphics to: High-Performance NVIDIA

**Comment by YoshiRulz** [comment]
It's weird that the dedicated card isn't used by default, probably because it's a laptop, but I'm convinced it's the iGPU at fault and not the NVIDIA GPU. Forcing EmuHawk to run using the dedicated card is technically just a workaround. It sounds effective though, so I've added it to the epic.

@riccardofrosini I'm closing this issue as it works correctly with your GPU. If the same thing happens again, please let us know.

**Comment by riccardofrosini** [comment]
> @YoshiRulz there used to be issues with Glide64 and GlideN64 and laptops (with nvidia). The solution was basically...
> 
> * Open NVIDIA control panel
> * Manage 3D Settings
> * Program Settings
> * Add > EmuHawk
>   [And if I recall correctly]
> * Change preferred graphics to: High-Performance NVIDIA

Yep this works perfectly as well! Thanks! It is pretty painful to disable and re-enable the CPU graphics every time.
