### ISSUE TITLE
Lua's comm.socketServerSend replaces non-ascii with '?'s

### ISSUE THREAD

**Issue by whiteted-strats** [TASVideos/BizHawk#2194]
### Summary
comm.socketServerSend(string.char(x)) will send a '?' for 256 > x >= 128

I want to use it for sending raw bytes, which are effectively supported by lua's strings but not by this method.

### Host env.
BizHawk 2.4.1 & 2.2.2; Windows 10 Home 10.0.18362

**Comment by whiteted-strats** [comment]
The cause is in Communication.SocketServer :
```c#
public int SendString(string sendString)

{

int sentBytes = SendBytes(Encoding.ASCII.GetBytes(sendString));

_success = sentBytes > 0;

return sentBytes;
}
```

Using Encoding.GetEncoding("ISO-8859-1") should be a happy easy fix?

**Comment by YoshiRulz** [comment]
This affects the .NET API too, so it should probably be Unicode to match `System.String`. I'd imagine that wouldn't cause issues for Lua as strings are bridged correctly?

I should really cleanup the comms API and impl while I'm at it.

see also: #190 (strings bridged correctly but rendered as tofu)

**Comment by whiteted-strats** [comment]
Supporting unicode there makes sense. In that case in `CommLuaLibrary` could we do

```c#
		public int SocketServerSend(string SendString)
		{
			if (!CheckSocketServer())
			{
				return -1;
			}
			return GlobalWin.socketServer.SendBytes(Encoding.GetEncoding("ISO-8859-1").GetBytes(SendString));
		}
```

If I'm not mistaken lua string characters must be in 0-255, so there's no need for unicode support from lua's POV. 

My server is in c++ and I send TLV data, so when I send a u32 I want it to be 4 bytes not something variable :)

**Comment by fusoyeahhh** [comment]
Just ran into this, myself, and it's a big blocker for socket communication with Lua --- half of the representable byte values are corrupted. Is it agreed that the only fix needed to change the encoders from ASCII to unicode? If so, I can try to put together a patch for that.

**Comment by YoshiRulz** [comment]
See 45488f266 and fafa29a2b.
