### ISSUE TITLE
sync settings are not applied in latest devbuild

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2195]
Just as title. Version used: https://github.com/TASVideos/BizHawk/commit/53b61d9cfa834981da8d84d9d290bd1bd55061c5

**Comment by nattthebear** [comment]
@ThunderAxe31 Please retest on 054efa4 or later

**Comment by ThunderAxe31** [comment]
Sorry for the late reply, I was very busy these days and didn't notice the fix.

I tried the latest devbuild and now it works correctly, just as before, thank you.
