### ISSUE TITLE
bug in latest builds opengl + hq2x flash (caused by fix from #2160)

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2196]
OK so 
Sega Genesis Altered Beast.

load game and fast forward to third attract mode. (level 2 with dragons)

in version 2.4.2 no problem. OGL and DX work perfect here

Latest AppVeyor build in Direct X mode no problem.

Latest appveyor Build in OpenGL problem, Every time dragon fires screen flashes.

This will happen if you reach level 2 or if you allow the game to demo level 2 which is every 3rd demo and you can fast forward to get there.

Was able to replicate on 3 systems with 3 different video cards, Nvidia, Intel and AMD

Something has either changed with OGL or with Genesis Plus GX in latest dev builds. I can make this occur 100% of the time on dev and 0 times on 2.4.2

**Comment by jjfmz42015** [comment]
ok so last commit that is ok master 499b59a0

first commit where it breaks master 62537118 which i believe came from master a566dc75 ← mainform-interface 2722b34a

**Comment by jjfmz42015** [comment]
not just altered beast, happens 100% of time during game play if in OGL mode on Twin Cobra.


Note 2.4.2 also plays this proper. Dev builds only, OpenGL only

**Comment by jjfmz42015** [comment]
happens with many more games

**Comment by nattthebear** [comment]
I can't reproduce this.

**Comment by YoshiRulz** [comment]
@jjfmz42015 You'd linked the first broken commit, why did you remove it? Did you bisect properly?

**Comment by jjfmz42015** [comment]
> @jjfmz42015 You'd linked the first broken commit, why did you remove it? Did you bisect properly?

Because the last commit i thought was good does this intermittently. Still have not reproduced under 2.4.2 but still producing with dev builds. I will test more and try to find the exact build it starts from, then I will record videos of proper vs what Im noticing.

**Comment by jjfmz42015** [comment]
> I can't reproduce this.

Try loading the a second genesis game. Seems sometimes it happens and sometimes it doesn’t until you load a second game.

I will see if I can somehow narrow down better. Already tried on multiple video cards on multiple systems so I know its not a video driver issue and that it will happen on other machines. 

Will update this topic soon. Will test more

**Comment by jjfmz42015** [comment]
ok guys.

with this rom
Twin Cobra (U) [!]
SHA1:C386C617703A3F5278D24B310C6BC15E3E180BDF
MD5:0006C0C0DB9B334B79F1ED20EEB8B9BF

 
under opengl and hq2x  I am able to replicate 100% of the time during gameplay


With version 2.4.2 under ogen gl and hq2x it works perfect.

@nattthebear @YoshiRulz

**Comment by jjfmz42015** [comment]
hmmm actually happens on all cores not just sega.

so if opengl and hq2x many games either flash or seem to cycle through colors.

a few builds back hq2x was broken and i guess its fix is partial

**Comment by jjfmz42015** [comment]
the problem stars since this fix https://github.com/TASVideos/BizHawk/issues/2160

**Comment by zeromus** [comment]
Find a game to test that doesn't require having to play to level 2

**Comment by jjfmz42015** [comment]
> Find a game to test that doesn't require having to play to level 2

Try twin cobra sega genesis

**Comment by jjfmz42015** [comment]
This game should show the problem the second you start level 1
