### ISSUE TITLE
Download ffmpeg from A/V dialogs and remove it from the BizHawk package

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#2199]
Currently most of the size of BizHawk is for ffmpeg, which many (most?) users don't even use.  We should have an appropriate dialog do a check for its existence and give an option to download it (with a progress bar).  This would reduce the bizhawk download by more than 90%

**Comment by vadosnaprimer** [comment]
Not all ffmpeg commands we have embedded work on all ffmpeg versions, so it will need to keep track of version we've tested against. Otherwise, very yes.

**Comment by nattthebear** [comment]
We can probably just hardcode a single URL to download and then change that as needed after testing a new one

**Comment by YoshiRulz** [comment]
On Windows:
* Version check
	* For the dialog's first run, see if `ffmpeg` exists in `%PATH%`, and compare its version to our known-good {range/whitelist} (not sure if version ranges are applicable to FFmpeg).
	* Subsequent runs, still perform the version check, but on the cached path (maybe skip if the path is `/dll/ffmpeg.exe`). If it's been replaced with an unsupported version, restart from first-run.
* If a known-good version can't be found, download the latest known-good version to `/dll` in the background.
* Cache the executable path of whichever is chosen for when the dialog is next opened. We can use the existing paths system for this, or save it to config and make a "forget" button.

On Linux (and macOS?):
* Every run, see if `ffmpeg` exists in `$PATH`, and compare its version to our known-good {range/whitelist} (ditto).
* If a known-good version can't be found, disable the list item(s) and display a "install/upgrade/downgrade ffmpeg with your package manager" dialog.
* Don't cache the executable path. If it's installed via package manager, it's updated in-place (and it will always be `ffmpeg` in the shell anyway). If someone adds a custom version to `$PATH`, *that* copy will always be `ffmpeg` in the shell.

**Comment by vadosnaprimer** [comment]
> If the download fails, give up and disable the list item(s).

Nope. Tell the user what version is needed and ask to get it somewhere and to put where we want it.

**Comment by adelikat** [comment]
This was implemented
