### ISSUE TITLE
new 7800 bios is a hack. old was official.

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2207]
new 7800 bios is a hack. old was official, isnt this a step backwards?

source of new hack job bios https://atariage.com/forums/topic/237208-atari-7800-only-speed-bios/

**Comment by YoshiRulz** [comment]
(referring to [this change](https://github.com/TASVideos/BizHawk/commit/fa7ac3d4c1b0bf1e93233dbd6fd81b6e7ddd0d4e#diff-7b074d2e4471bfff26eded5b6ac29edfL33-R34) @alyosha-tas)

**Comment by alyosha-tas** [comment]
Oops forgot to revert after fixing serpentine. I'll update after the open firmware rename pr is dealt with

**Comment by hegyak** [comment]
@alyosha-tas I merged the Firmware Rename.  All I ask is that the Filenames, maintain the same Format/Style.  Because I  don't think I touched the Commented File names
