### ISSUE TITLE
NesHawk Question: Why APU2 volume is not same on different games?

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2208]
Example on Triangle:
**Wario's Woods** would hear stronger triangle sound.
**Dragon Fighter**, **Shatterhand** would hear weaker triangle sound.

**Comment by nattthebear** [comment]
Why would you expect them to be the same volume?  Do you have recordings from real hardware or something?

**Comment by Yave-Yu** [comment]
Other emulator like FCEUX, Mesen (or NSFPlay) have same (or near) APU2 volume.

**Comment by zeromus** [comment]
So why did you close it? Did you figure out what was wrong?
