### ISSUE TITLE
MSX BIOS Using Bad SHA-1?

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#2211]
I am attempting to find the MSX BIOS for Testing in BizHawk but after looking through the TOSEC DAT files for MSX, MSX2 and MSX+ the SHA-1:
"B398CFCB94C9F7E808E0FECE54813CFDFB96F8D0"

Is not found in any of those DAT Files.  Which, makes me ask is BizHawk using an invalid Dump for the MSX BIOS.

**Comment by alyosha-tas** [comment]
MSX is WIP and that is for development only. That will be fixed when I get back to work on it (after O2 stuff.) I use that one for ease of troubleshooting.
