### ISSUE TITLE
TAStudio: allow selecting and deleting multiple branches or markers.

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2215]
In my opinion, you should be able to select markers and branches in the same way you can select frames, and it should switch focus away from frames. Then you should be able to press `Delete` to delete them (this functionality should also be in the right-click context menu).

This was requested by g0goTBC, but I incidentally found this to be annoying just now when I accidentally cleared some frames when I was trying to delete a marker.

**Comment by vadosnaprimer** [comment]
People seem to want this, so if someone implements that, I'm fine. As a PR of course.

**Comment by RetroEdit** [comment]
With b101df8235ed1ab4a95faeca4c9c85c3a7a31c1f, we're partially here. Just needs branches to be complete.

**Comment by adelikat** [comment]
DUN

**Comment by RetroEdit** [comment]
This may have been partially implemented, but I can't see a way to select multiple branches in the latest 2.5.1 dev (714fd0f) at time of writing. I also see the same problem in 2.5.
