### ISSUE TITLE
Cant complete firmware?

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2216]
I keep backups of all software I like. When I do this I make complete packages.

I cant seem to fulfill the current bios list. 

See attached screenshot.

Maybe its not possible for me to fill these?
![Capture](https://user-images.githubusercontent.com/67816530/87041680-98396000-c1c0-11ea-8eb6-f1ff43ab490d.JPG)

**Comment by nattthebear** [comment]
This is an issue tracker, not a place to help you find crap to pirate.

**Comment by jjfmz42015** [comment]
pirate?????? That is not my intent.

I am doing this for myself and didnt think having my bizhawk backup preconfigured with obsolete bios is piracy.

So you are saying this tool fully equipped is piracy?


Thats not good.


BTW if you really think there is a hot pirate market for MSX you are insane sorry.

I just wanted to have a clean backup of bizhawk on my back up drive. Im not running a pirate site hosting super bizhawk packages. I dont think anybody is.

What a stupid statement.

**Comment by YoshiRulz** [comment]
NDS is a known issue with the Firmware Manager. You can set it manually and it will work, regardless of what settings are saved to it already.

MSX is wontfix: see #2211.

**Comment by jjfmz42015** [comment]
and this is an issue. bioses that seem to be incorrect and i was simply asking.

**Comment by jjfmz42015** [comment]
> NDS is a known issue with the Firmware Manager. You can set it manually and it will work, regardless of what settings are saved to it already.
> 
> MSX is wontfix: see #2211.

thank you. proper reply.
