### ISSUE TITLE
Question about game Hashes Database

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#2217]
Hi Friends im like to support the hash database with rom upgrades and Mod projects but i dont know how the rom hash system of bizhawk work

**Comment by YoshiRulz** [comment]
If you click on the orange ?-block in the status bar, it'll show you the hash, even for homebrew.

**Comment by DarkLegend1987** [comment]
No i meant add the hash to the Database or maybe i do a list of especial hash and you add into the network

**Comment by zeromus** [comment]
there are literally 1000s of examples, what's not to understand?

**Comment by hegyak** [comment]
In the Folder GameDB there are TXT Files.
I recommend creating the file:
gamedb_user.txt
For ROM Hacks/Mods.

If you don't know the formatting, there are Files for Each System.  The Formatting is mostly self explanatory.

If you give more details, I may or may not offer better information.
