### ISSUE TITLE
Remove uses of System.Windows.Forms.ContextMenu

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2222]
This class does not exist in .NET Core WinForms and uses will have to be removed before moving to .NET Core.  System.Windows.Forms.ContextMenuStrip is supposed to be a good replacement?

There aren't many of these; see some of the diffs in https://github.com/TASVideos/BizHawk/commit/de1215b3fb904579d343f7b9ff5426c92d30e874 for reference

**Comment by adelikat** [comment]
Yeah, we generlaly use ContextMenuStrip in tools, I blame the designer for having inconsistencies.  I'll knock this one out

**Comment by YoshiRulz** [comment]
Missed one.
https://github.com/TASVideos/BizHawk/blob/36b7d9df28ffad3166c141c03162fccb141ee600/src/BizHawk.Client.EmuHawk/CustomControls/InputWidget.cs#L42
