### ISSUE TITLE
TasStudio Feature Request "Clone Selection X Times"

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2241]
This is something I have wanted actually.

Ex: User wants to clone this section of complex rapid attack sequence 14 times to kill a boss. Select the sections, clone X times selection, then enter and it will insert that section that many times.

1. Highlight frames
2. Right Click -> "Clone Selection X Times"
3. In popup enter Number of times to clone.
4. Enter or click Ok button.

**Comment by adelikat** [comment]
That's a nice idea

**Comment by RetroEdit** [comment]
Related: #2239

**Comment by davidackroyd99** [comment]
Can I have a go at implementing this? or is someone already doing it?

**Comment by YoshiRulz** [comment]
go for it

**Comment by adelikat** [comment]
a PR for this was developed and merged
