### ISSUE TITLE
FEATURE REQUEST An good GUI to load games

### ISSUE THREAD

**Issue by Augusto7743** [TASVideos/BizHawk#2243]
BizHawk is amazing to emulate several systems, but the mode that load games is difficult to select an system.
When loading an game BizHawk use an Windows default GUI and not has an option to select first what system will be loaded before of selecting an game.
I has several folders for each system with several config.ini in each BizHawk folder thus avoinding problem when selecting an game, but need to replace files in all files when need to update Bizhawk being an temporary solution to avoid that problem.
Not is possible add an GUI where has an option to first select an system and after an game cd list ?
Thanks for read my post.

**Comment by YoshiRulz** [comment]
...what. Just drag and drop the game you want to load onto EmuHawk. I'm not sure why you'd need to keep multiple configs around, that's not generally required for casual play.
