### ISSUE TITLE
Request: "Replace Port 2 Start With Microphone" feature from FCEUX 

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#2247]
There are some Famicom and FDS games that use the microphone. Examples: Zelda 1, Hikari Shinwa, Bungeling Bay, Star Soldier, Takeshi no Chousenjou, etc. FCEUX has the feature mentioned in the title under "Config > Input Configuration", but this isn't available in NesHawk at all.

If said feature could be added to the Hawk, it'd be much appreciated.

**Comment by adelikat** [comment]
We already have it, for NesHawk.  You need to go to NES -> Controller Settings, and check the "Famicom" checkbox, and set port 2 as a NES Controller.  THen you should see P2 Microphone as a "button" in the player 2 settings.

**Comment by Sonia-7** [comment]
Oh, I totally missed it. Thank you for the answer!
