### ISSUE TITLE
RFC:  Viability of DobieStation

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2250]
I have an experimental branch of BizHawk which runs DobieStation.  It's still a very early WIP, but from what I can tell the finished product, if it's finished, will have some limitations:

- Speed:  15-20FPS on a top tier machine
- Savestate Size:  100MB+
- Compatibility:  Limited to whatever DobieStation supports.

Everything not core-specific of course would be the same as the rest of BizHawk:  Good TASing tools, full AV dumping, etc.

Is this good enough that I should pursue it?  Would people actually make TASes in this situation?

**Comment by InfamousKnight** [comment]
Given how we have to play it in slow motion anyways for tasing, I definitely would. Dobbiestation has a good chunk of games that work too nowadays. Its gonna be awhile before a speedboost comes.

**Comment by nattthebear** [comment]
This would work for linux.

**Comment by InfamousKnight** [comment]
Sweet! In case nobody found the branch, its wbx fake threads

Its gonna be waterboxed too!

**Comment by Zinfidel** [comment]
I've worked on some PS2 tases already on PCSX2 and ultimately gave up because I'm spoiled on BizHawk's tools and it was just too painful going without them. I would definitely explore doing a PS2 TAS in BizHawk. My laptop's specs are not even close to top-tier though, and there's a limit to my sanity if I'm having to replay the game at 5 fps or something.

**Comment by InfamousKnight** [comment]
Yeah, I have an i7 core laptop with 1.8 ghz and it runs at like 5fps too during gameplay. In the menus its pretty good. I wish it was at 15-20 fps all the time.

Would overclocking my intel i7 laptop help with that? Go from 1.8ghz to 3.0? The more I overclock, the more I damage my machine.

**Comment by InfamousKnight** [comment]
In case anyone is interested in what I'm planning on using this for, midnight club 2 glitchless run. Although the frame rate is slow, at least there won't be any desync issues or having to play it back up to the point where you left off at a low frame rate like with libtas. That game and maybe dirge of cerberus.

**Comment by nattthebear** [comment]
`master` now contains a build of DobieStation.  Do not file any issue against it unless you've already tested that game in upstream as well, and the issue does not happen there.  Expect it to be 1/2 or slower of the speed of regular DobieStation.

**Comment by InfamousKnight** [comment]
Well, thanks to the build problem, I haven't been able to test it. But damn, its bad enough that dobiestation runs so slow on its own, imagine playing it even slower. If anyone has the patience to deal with it, have fun.

**Comment by NarryG** [comment]
Could the submodule be replaced with an https:// submodule rather than a git: submodule? Requiring ssh keys set up could throw some people off.

**Comment by nattthebear** [comment]
> Could the submodule be replaced with an https:// submodule rather than a git: submodule? Requiring ssh keys set up could throw some people off.

I'm completely puzzled by this response.  First of all, this issue is about people making TASes, not developing the core.  When making TASes, you just download the CI build and go with that.  But even for developers, this is super strange.  Most developers generally aren't building Waterbox cores; indeed, I'm only aware of two other devs besides me who have ever done it.  And if you're getting into hacking on and building Waterbox cores, surely you've figured out how to change a git remote by now?

**Comment by nattthebear** [comment]
Closing because I got the information I needed to make my decision:  I proceeded with the project and added DobieStation to Bizhawk.
