### ISSUE TITLE
SubGBHawk Movies won't load into SubGBHawk unless the core is selected Config -> Cores

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2259]
Config.PreferredCores gets correctly set to SubGBHawk when the movie is loaded. However this does not get sent to _config.PreferredCores in the actual ROM loader. As a result, the ROM loader tries the cores available  for GB, and since GBHawk and SubGBHawk share the same settings and sync settings, it recognizes this as a valid core and loads it because that's the first one it tries.

This is a regression from 2.4.2

**Comment by nattthebear** [comment]
Cannot reproduce.  I created a subgbhawk movie, then closed everything, and set my GB core preference to Gambatte.  I reopened the rom, and it opens with Gambatte; then I reopened the movie, and it went right back to subgbhawk.  The movie's header contains the following:

```
Core SubGBHawk
```

**Comment by ThunderAxe31** [comment]
Related: https://github.com/TASVideos/BizHawk/issues/2246

**Comment by alyosha-tas** [comment]
Looks like I was using a movie from an older version that doesn't work correctly now that cycle count is in the header instead of vblank count. Movies made in the current version work correctly.

**Comment by alyosha-tas** [comment]
Actually even with a movie made on current build I get this error with a fresh dev build, re-opening.

**Comment by alyosha-tas** [comment]
Here are some exact repro steps:

1. download and unzip the dev build
2. add the necessary firmware files for GB / GBC
3. download this movie file (which was also made in dev build): http://tasvideos.org/userfiles/info/65117679898782606
4. load pokemon crystal (rev A)
5. run this movie,

It will run in GBHawk even though it is a SubGBHawk movie

**Comment by nattthebear** [comment]
`Game.System` is GBC so the RomLoader uses the GBC core preferences to decide what core to load, but `Movie.System` is GB, so the movie spaghetti code mutates the GB core prefs and not the GBC core prefs.  The bug seems to be in the movie code, I guess?  The game database is the one that returned a system of GBC.
