### ISSUE TITLE
Controller configurations doesn't save cleared controllers

### ISSUE THREAD

**Issue by Cyorter** [TASVideos/BizHawk#2264]
Happens in 2.5 dev. As the name says, I can configure all controllers "Normal buttons" and "Autofire buttons".
But when I click "Save", the ones I wanted to clear doesn't actually clear.

Example:
Let's suppose second controller Autofire buttons has this config
![image](https://user-images.githubusercontent.com/42274825/89138817-d1889580-d50a-11ea-9e48-41e17c9020a6.png)
I clear it
![image](https://user-images.githubusercontent.com/42274825/89138852-e9f8b000-d50a-11ea-94f2-0aef966a09f4.png)
After clicking save (doesn't clear)
![image](https://user-images.githubusercontent.com/42274825/89138892-14e30400-d50b-11ea-9b00-62a9bcb38505.png)

**Comment by nattthebear** [comment]
@adelikat Seems like you did this intentionally in c13430896f49c25ae59f5e52b23bb0e168c9414e.  Thoughts?
