### ISSUE TITLE
Emuhawk can't recognize ps2 isos

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#2265]
If you load a ps2 iso, it tries to open it with octoshock. Dobiestation should also work with ps1 games too, so maybe a setting on ps core would help address it. I wonder how much faster ps1 games would be using it.

**Comment by nattthebear** [comment]
It worked for me (although I didn't try much); what game are you having issues with?

**Comment by InfamousKnight** [comment]
Kingdom hearts re chain of memories. I'm using Linux and that shouldn't make a difference though. It just falls back on octoshock.

**Comment by nattthebear** [comment]
Reproduced, working on a PR

**Comment by nattthebear** [comment]
Should be fixed now
