### ISSUE TITLE
PSX Pixel Pro Mode has lower frame rate on full screen

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2271]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
If you use Pixel Pro Mode and full-screen a game, you can instantly notice degradation of performance.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
This works on nearly any game, though in this case I'm using Front Mission 3. Note that the exact performance may depend on your system and game choice.

1. Load a PSX game with Pixel Pro Mode visual options. Keep window small, and play the game.
2. Notice 60 FPS. Game has no issues. Bizhawk CPU use at 9%. RAM at 162 MB.
3. Full Screen the game
4. Notice 55 FPS, and random stuttering/skipping. Bizhawk CPU at 14.8%. RAM jumps up and down between 162 and 172 MB.
5. The sound make a "pop" sound about once a second (i.e. stuttering).

### Expected Result
Larger windows would not degrade performance this much. Switching to mednafen Mode fixes the issue

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.1 Windows 10

Example renders between fullscreen and non-full screen.

![fast](https://user-images.githubusercontent.com/8139496/89250269-3e626500-d5c9-11ea-99d9-5d4c0ca38637.png)
![slow](https://user-images.githubusercontent.com/8139496/89250276-41f5ec00-d5c9-11ea-8309-f7b00c443d91.png)

**Comment by Meerkov** [comment]
Please notice that maximizing the window (but not full screen) does not degrade performance. See attached

![stillfast](https://user-images.githubusercontent.com/8139496/89250747-4242b700-d5ca-11ea-8153-8d61187d55cd.png)

**Comment by zeromus** [comment]
Has nothing to do with octoshock, has nothing to do with the game, has nothing to do with pixel pro mode.
change config > display > display method
pick something other than gdi+

**Comment by Meerkov** [comment]
Thanks, I changed out of GDI+ and it seems to work as you said. So GDI+ mode doesn't like fullscreen I guess?

**Comment by zeromus** [comment]
The first word used describing gdi+ is "slow"
