### ISSUE TITLE
SubGBHawk emulates at half speed after setting controller keys

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2272]
Version: dev build https://github.com/TASVideos/BizHawk/commit/c8b8efedac6858ee47e3a8cac1a7e0e181d890fb

Repro:
1. Select SubGBHawk as GB core
2. Open a GBC ROM
3. Go to Config > Controllers...
4. Close the controller configuration window
5. Set View > Display FPS

You'll see that the game is being emulated at 30 FPS, even if you toggle Turbo Throttle. However, Fast Forward and the regular Turbo will speed up emulation to the limit allowed by your PC. It seems that the target speed of emulation gets effectively changed to 30 FPS. In fact, you will also hear that the game audio sounds with a lower pitch.

**Comment by alyosha-tas** [comment]
This is actually another instance of #2048 
SubGBHawk uses a float control to input cycle count for its input window. As long as you don't go to the controller config window it defaults to a full frame of cycles (the mid value is the upper limit of 70224.) This is respected as long as you don't go to the controller config window. If you save there, it reset the value to the physical mid point of 35112 so you get 1/2 speed.

As a quick fix, you can go to Config -> Speed/Skip -> Audio Throttle and it will give full speed for casual play.

But I'll try to fix the underlying issue for at least this specific case.

**Comment by adelikat** [comment]
This has been fixed as of 1671cd32c4ac0a798507bf4659455baf53bd4a69
