### ISSUE TITLE
Retro-Bit Saturn USB Model 2 - Can't set left or right on dpad. 

### ISSUE THREAD

**Issue by GambitOG** [TASVideos/BizHawk#2273]
Controller: Retro-Bit Saturn USB Model 2
When attempting to configure this controller, all buttons can be configured except "Left" and "Right" on the dpad. When pressing these during setup, it does not pick it up and acts as if no button press occurred. It was tested using the Genesis Plus GX core loading both Sega CD and Genesis ROMS.

This controller has been tested in both Retro Arch and Windows controller setup, and the left and right fully respond. I can play any game without issue in Retroarch.

**Comment by zeromus** [comment]
config > customize > input method
