### ISSUE TITLE
[TAStudio] Emulation automatically plays when you move your mouse out of TAStudio window.

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#2275]
While testing the new PCE core and checking if anything was buggy in the dev, I found that emulation kept playing at random for some strange reason, I found out it happens when you move your mouse button outside of the window.

I tested this in 2.4.2 and the issue isnt there.

here's a video of me doing it: 

https://www.youtube.com/watch?v=XITwHK4DPX8

this is also the case for the bottom part of the window too, but at the time of recording this video, I had only found it did it on the side.

tested in Dev Build #9600bc2ce0add5fa8041a57b9fa8f53158403313

To re-create this:

1. Open TAStudio with a game running

2. While emulation is unpaused, Click and Drag inputs upwards, so BizHawk pauses once you let go of the mouse button.

3. Simply move your mouse from inside the TAStudio window, to the outside of the window, from either the left side or bottom side.

here is another video me talking about how to reproduce the glitch: https://www.youtube.com/watch?v=U2PhmQLaD-U

**Comment by RetroEdit** [comment]
Huh, I wonder if #2258 is related.
