### ISSUE TITLE
Crash when starting v2.4.1 and v2.4.2

### ISSUE THREAD

**Issue by dacicus-occidens** [TASVideos/BizHawk#2276]
When I try to start EmuHawk.exe, it immediately crashes.  Same behavior from the command line or from double-clicking the file in Windows Explorer.  I'm running Windows 8 64-bit and have no problems with version 2.4.0.  I've installed the latest prerequisites and restarted the computer.

The error dialog says:
```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EmuHawk.exe
  Problem Signature 02:	2.4.2.1
  Problem Signature 03:	5ec1733d
  Problem Signature 04:	EmuHawk
  Problem Signature 05:	2.4.2.1
  Problem Signature 06:	5ec1733d
  Problem Signature 07:	be0
  Problem Signature 08:	0
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.2.9200.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	f536
  Additional Information 2:	f536a6bcb56ab99a9a84961f6978269a
  Additional Information 3:	f686
  Additional Information 4:	f686c4f05879f33af03cc448a8d10867
```
This is similar to #1886, so I used Process Monitor as described there and got this list of missing files: [missing.txt](https://github.com/TASVideos/BizHawk/files/5036873/missing.txt)

**Comment by YoshiRulz** [comment]
Install all available updates (to [KB4565541](https://support.microsoft.com/en-us/help/4565541)), then restart. If it still doesn't work, install the [.NET Runtime](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer) manually.

**Comment by zeromus** [comment]
Also try installing these individually and look for any failures: https://github.com/TASVideos/BizHawk-Prereqs/tree/master/dist

**Comment by dacicus-occidens** [comment]
Thanks for the suggestions.  I installed all of the Windows Updates labeled "Important" and tried to install all of the files that zeromus linked, but they were all installed already.  The .Net Runtime manual install fails with the message 

> The .NET Framework 4.8 is not supported on this operating system.

Following the link from that window led me to https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements, which says that the 4.8 framework is not compatible with my OS at all.  Too bad for me, but thanks again for your help.

**Comment by nattthebear** [comment]
.NET 4.8 is fully supported in Windows 7 SP1, Windows 8.1, and Windows 10.  Windows 8.1 is available as a free update for Windows 8 users.
