### ISSUE TITLE
`memorysavestate.load` retains trailing frames

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2283]
This is inconsistent with standard savestates. It is annoying for precisely controlling when a movie should end when using Lua-assisted traditional re-recording.

To demonstrate this, I will list a methodology for testing standard savestate workflow:

1. Open a game, pause the game, and begin recording a movie.
2. Save a state
3. Advance 10 frames
4. Load the state
5. Advance one frame
6. Save the movie

After doing these steps, you will be left with a one-frame movie.

However, if you do the equivalent by opening a movie and then running the following script (instead of doing steps 2-5), you will end up with a 10-frame movie.

```lua
local state_id = memorysavestate.savecorestate()
for i = 1, 10 do
	emu.frameadvance()
end
memorysavestate.loadcorestate(state_id)
memorysavestate.clearstatesfrommemory()
client.pause()
```

(Tested: BizHawk 2.4.2 and 07d0688f45e0ba46b322d5c22447bf9188fd7fca)

**Comment by YoshiRulz** [comment]
Assuming you've omitted `state_id = memorysavestate.savecorestate()` from your script, I think this is intentional behaviour. They are not savestates, they're raw blobs straight from an `IStatable`.

**Comment by RetroEdit** [comment]
https://github.com/TASVideos/BizHawk/blob/1bded467b3a77400de973b5d5562f45f64e85cd9/src/BizHawk.Client.Common/lua/CommonLibs/MemorySavestateLuaLibrary.cs#L19

Yep, I guess I should have read the documentation more carefully before using it. That makes sense.
