### ISSUE TITLE
Toggling ReadOnly doesn't change the framecount display

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2296]
In traditional `.bk2` rerecording, toggling ReadOnly has the potential to change the movie's mode (i.e. Recording vs. Playback). The FrameCounter's display should be immediately updated upon toggling ReadOnly, instead of waiting for the next frame advance.

Specifically, if I had a two-frame movie and I was at frame one, this is the difference between what Recording and Playback looks like:

```
Playback:  1/2
Recording: 1
```

This was a problem in 2.3 and 2.5 dev. I assume this was never a feature, but perhaps it's a really old regression. I suspect it was just never implemented, so I'm not planning to test any further builds.

**Comment by adelikat** [comment]
No, it is working as intended.

The framecounter indicated 1/1000 when you are in playback mode.  Toggling read-only does not put in you in playback mode.  That mode is initiated when you load a state.

This behavior is intended and consistent with every rerecording emulator I'm aware of

**Comment by RetroEdit** [comment]
Ah, I see, never mind then. I thought it did change modes when you frame advanced, I guess I misunderstood.

> This behavior is intended and consistent with every rerecording emulator I'm aware of

Hmm... I'm curious why, it seems a bit strange to me, and I can't think of a reason off the top of my head for this. But I'm not doubting it.
