### ISSUE TITLE
Controller buttons are mapped to fast-forward and rewind by default

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2297]
Joypad buttons are mapped to fast-forward and rewind by default.

https://github.com/TASVideos/BizHawk/blob/ad07eb85742c6ef89c74642f1363369758d611fa/src/BizHawk.Client.Common/config/Binding.cs#L108-L110

I might be the only one who feels this way, but this annoys me incessantly, and deleting them from the config is quite annoying every time. I understand the idea (probably shoulder buttons for navigating forward and backwards), but there's a few problems here:

1. Not all controllers map these buttons the same. On my controller, buttons `J1 B7` and `J1 B8` are Start and Select.
2. These buttons could conflict with actual console's controller mappings.

In my opinion, joypad buttons should not be bound to non-controller functionalities by default. The user can easily add these if they're wanted. A controller's primary purpose should be restricted to actual in-game controls.

For the Left Trigger and Right Trigger, I care slightly less because it doesn't personally affect me at the moment, but I think the same philosophy applies, if a bit less so because they aren't arbitrary numbered buttons at least.

This annoys me so much I went to the trouble of digging up the commit that added these in, way back in `1.5.1-approximate`: ac25f3f3e62abff9c22e2213f70611eda9aee92e

@adelikat J'Accuse!

(Just kidding.)

**Comment by nattthebear** [comment]
IMO any default bindings for dinput are a bad idea, as there's too much variance between what different trollers do.

**Comment by RetroEdit** [comment]
Even for console controls? The default for those don't work for me either, but it's not as annoying because I can just change them.

For general hotkeys, it's really annoying because it's so easy to forget to change them and then accidentally activate them. There was a while where I didn't even realize I was pressing Fast-forward when I was first using BizHawk many months ago.

**Comment by YoshiRulz** [comment]
Not sure why GitHub didn't close this issue. I'd have re-opened it anyway because, as natt said, the DirectInput gamepad binds aren't used by default and don't need to be in `defctrl.json`. Self-assigning that job.

**Comment by RetroEdit** [comment]
@YoshiRulz I'm not familiar with the details of how `defctrl.json` is related, so it's unlikely I'll be adding that to that PR. Feel free to do whatever you want to the PR. I would at least prefer to see the fast-forward/rewind bindings addressed before 2.5, since it seemed simple to fix.
