### ISSUE TITLE
Loading a movie doesn't update input display or rewind symbol

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2298]
For .bk2 loading, it still shows the previous set of buttons that were pressed and the rewind symbol/fast-forward symbol (`<<` or `>>`). I believe loading states has similar issues. Ideally, the buttons would be cleared and then reloaded from the movie if relevant, not out-of-date until frame-advance is pressed.

This is a similar type of situation to #2296.

**Comment by alyosha-tas** [comment]
I didn't see any problems with input display not being updated on movie load, was probably fixed somewhere along the way with all the controller updates.
