### ISSUE TITLE
Rewind is now limited / missing many features

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#2300]
In recent builds, the rewind window became overly simplistic, with many features missing. You can no longer set the rewind frequency every x frames, no "Use disk for buffer instead of RAM", etc, and the biggest issue is that now the Max buffer size is only 1024MB. Even with "use compression" checked, this is hardly enough to rewind even a few minutes in stuff like SNES games. Meanwhile in previous versions I could rewind up to over 1 hour.

Here's a screenshot comparison between the old and new window:
https://i.imgur.com/fhg2baP.png
https://i.imgur.com/EETDAYw.png

What explains such a massive downgrade?

**Comment by RetroEdit** [comment]
The rewind implementation was redone in the newest dev build, with something that's been called 'zwinder'. The intention there was to increase the efficiency of savestates for waterboxed cores.

@nattthebear is probably the best equipped to answer your questions.

**Comment by Sonia-7** [comment]
Can't at least the max buffer size get increased? Maybe up to 8192MB or so would already make a difference. 1024MB is too little.

**Comment by nattthebear** [comment]
Frequency is set by determining the desired frame length together with the buffer size and the core's state size.  Max buffer size larger than 1GB is something I've been thinking about; is there much interest in it?

**Comment by Sonia-7** [comment]
I don't know where to change the state size anymore. Could you tell where it is?

And well, higher max buffer size is certainly something I'd be interested in. I mean, most machines nowadays can have 32GB+ of RAM (mine has 16GB), so personally I don't see why having such a small limit.

**Comment by nattthebear** [comment]
By state size I mean the core's actual savestate size, which cannot be changed (except by turning on compression, sort of.)  So for instance, if your buffer is 512MB large, and states are 300KB large, then the buffer can hold about 1747 states.  If you ask for a frame length of 10000, that means the frequency will be about one state every 5-6 frames.

This behavior was needed to better support cores with variable savestate sizes.

**Comment by nattthebear** [comment]
I did a bit of rearchitecting in the rewinder to support larger buffers.  The UI now caps you at 32GiB buffers (although if you manually edited your config, I suppose you could go larger.)

Tell me how it works out for you, and please reopen this issue or create another one if there are any further gaps in functionality.
