### ISSUE TITLE
Rewinder - change buffer size control functionality

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2302]
The new rewinder supports buffer sizes in powers of two only, so the current updown numeric is kind of jank to use for it.  Maybe we could use something that freezes to just powers of two?

**Comment by Sonia-7** [comment]
I agree with this. Not really a point in having non-powers of 2 if they're not supported.

Speaking of that, "Desired frame length" caps at 16383. Shouldn't it be 16384?

**Comment by nattthebear** [comment]
I bumped up the UI limit for desired frame length.  Because it's just a calculation input, it doesn't really have a hard limit

**Comment by YoshiRulz** [comment]
In the description of commit 5ea32b875 you said it *doesn't* need to be powers of 2. Can we close this?

**Comment by nattthebear** [comment]
> In the description of commit [5ea32b8](https://github.com/TASVideos/BizHawk/commit/5ea32b875b90dcaeb9886478efa0b9081bbd23a7) you said it _doesn't_ need to be powers of 2. Can we close this?

No, that doesn't change anything at all.

* Target frame length:  no restrictions on value in code, no restrictions on value in UI.
* **Buffer Size:  Limited to powers of two in code, but that's not well exposed in the UI.  << What this ticket is about.**
* Maximum state count:  Hardcoded to 16383 in the code.  Not exposed in the UI.
