### ISSUE TITLE
libgambatte won't build due to msvc crash -- please help me test

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#2309]
I decided not to strip down the project. But that makes it extra important for someone else to confirm that it crashes.
Can someone please try building this in msvc? I have compiler version `Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64` (`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe`)

If you are gonna test this for me and you DONT have this version, then cool! Please check it. Then update visual studio 2019 and try again. That way we'll know if the updated compiler broke it (please record the version number of your old version)

But I really only need one person on cl r29111 to confirm that it fails.

If someone can confirm it, I'll post the bug myself to MSFT. I have a history of compiler bugs with them, maybe that will count for something

**Comment by zeromus** [comment]
@vadosnaprimer please help, dont you build windows msvc slns?

**Comment by vadosnaprimer** [comment]
Builds and runs with 19.26.28805. I should update to VS 16.7.2 and try again?

**Comment by adelikat** [comment]
Tested with VS 16.7.2 and the cgb-gba-fix branch, It compiled with no errors. I was also able to load the resulting dll and played some random GB and GBC games

**Comment by zeromus** [comment]
I still can't build it. Please wait until we finally have a finished bizhawk release (and don't need to build gambatte anymore) and then update and test again?

**Comment by zeromus** [comment]
I repro'd it in a VM on latest VS, so I posted the bug to MSFT

**Comment by TiKevin83** [comment]
I reproduced it, turned a bunch of compiler optimizations off and it built fine, but then when I turned them back on it still built fine!  Thanks microsoft.

**Comment by zeromus** [comment]
You.... must not have done it right. If you do a clean rebuild, it should break again. I don't think it's nondeterministic.

**Comment by TiKevin83** [comment]
was doing a clean and rebuild between each test, checked it again and I'm still succeeding build.  Wondered if something wasn't working with clean:

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(477,5): warning MSB8004: Output Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Output Directory.

Added the trailing slash, clean worked either way, rebuild still succeeding.

**Comment by zeromus** [comment]
OK, I found the problem is due to an old .iobj file (or some of the other associated files, possibly .ipdb). And then due to the slash, it wasn't getting cleaned. THANK YOU!!!!
