### ISSUE TITLE
BizHawk's FCEUX font is a little different than real

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2313]
gui.defaultPixelFont(0) uses FCEUX font, but the **1** look crappy.
![20200817091140](https://user-images.githubusercontent.com/54294476/90348836-f41dc100-e069-11ea-98e5-db4e4f063c9d.png)
the real FCEUX's **1** is this.
![20200817091132](https://user-images.githubusercontent.com/54294476/90348857-0435a080-e06a-11ea-99f9-d7ede70de21d.png)

**Comment by RetroEdit** [comment]
The source for what? FCEUX? The font?

I'm willing to take care of this @vadosnaprimer I've been looking into this and I have a pretty good idea of how to solve it.

**Comment by vadosnaprimer** [comment]
It was created as a bitmap font in an online editor, and I don't have the link of the bitmap font file.

**Comment by RetroEdit** [comment]
They're embedded in the font itself:

https://fontstruct.com/fontstructors/1279495/feos
https://fontstruct.com/fontstructions/show/1217225/fceux
https://fontstruct.com/fontstructions/show/1217065/gens-1

**Comment by vadosnaprimer** [comment]
LOL you found it!
