### ISSUE TITLE
loading master system and saturn roms

### ISSUE THREAD

**Issue by supermario1995** [TASVideos/BizHawk#2318]
Ok so 1 when I open this one master system game it works perfectly fine but when I open any other game all it does is boot up the sega master system title screen and the game won't load beyond that. How can one game work fine but the rest of them don't? And if this helps any, it initially said I do not have the bios needed to run the game so I went to configure it and then it worked but again did not load past master system title screen. But that one game that works fine did not initially say I did not have the bios file, I was just able to open it without any issue from the start. how can all this possibly be? what's the fix? and 2 there are a couple saturn games that when I try to open, do not load at all. one of them loads the title screen of the game itself and then when I click play it is stuck frozen on the loading screen, and then one other game I try to open it says no core could boot rom. They are isos btw because that's the only format roms it supports for the sega saturn. But so then what's going on here and what's the fix?

**Comment by RetroEdit** [comment]
It would help if you listed the games you tried and which ones did and didn't work, so we actually have specific details to be able to reproduce the issue.

**Comment by supermario1995** [comment]
I didn’t think it mattered and that you may not even know the games but alright. They are bug and bug too for Saturn that don’t work. All other games work fine. and rainbow islands, New Zealand story, Alex Kidd in miracle world, and Alex Kidd the lost stars for master system that don’t work. Wonder boy works fine.

**Comment by YoshiRulz** [comment]
@supermario1995 If you're still having trouble on the latest version, comment with the info we've asked for, or [join IRC/Discord](https://github.com/TASVideos/BizHawk#support-and-troubleshooting).
