### ISSUE TITLE
Tastudio - changing the StateHistory settings mid-movie does not work

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#2322]
This has been broken as part of the rewrite of using ZwinderStateManager.

We have a few options here
1) Muck with the zwinder to allow changing the buffer after it has been instantiated and in use
2) Require mid-movie changes to clear savestate history, maybe add a warning that it will do this, and just new up a new zwinder as a result
3) block mid-movie settings changes.  Ideally we don't do this, it is important to be able to tweak your settings.   As your movie gets longer, the ideal settings will evolve, or maybe you just made a bad choice to start, and need to correct it

**Comment by SuuperW** [comment]
Done, with commits 4b6ff63, 6b63db8, and 956b710.
