### ISSUE TITLE
CycleCount of a .bk2 is overwritten when you open TAStudio

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2325]
Versions: 2.4.2 and #44d7603

Repro:
1. Download a movie file made with a core that stores the CycleCount in the Header.txt. For example, this: http://tasvideos.org/submissions/6844.zip
2. Open BizHawk
3. Open a ROM for playing back the movie
4. Open the .bk2 movie
5. Launch TAStudio
6. A confirmation window will appear, click on OK

At this point, you can see that the .bk2 file has been modified, by looking at the file proprieties. If you open it with as a .zip file and look at the Header.txt, you'll see that the CycleCount value has been replaced with the value relative of the frame that was being emulated when you opened TAStudio.

BizHawk should never modify a .bk2 file in any way when you open TAStudio.

**Comment by RetroEdit** [comment]
This is a broader problem: TAStudio requires saving the bk2 file before importing (and it informs you about in a nice little dialog). Ideally, it should provide an option to just import without saving the bk2.

Alternatively, it could check changes and only save if there are changes.

**Comment by RetroEdit** [comment]
That PR will fix the unwanted saving issue. CycleCount sometimes being invalid is a separate issue that I filed a while ago (#2203) and I'll try to address it soon.
