### ISSUE TITLE
.bk2 from older versions do not work in latest dev

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#2326]
Tested in Dev Build: #44d76036224549c37b761775cc59be05d4f79201

loading a .bk2 (loaded a Genesis movie "Pulseman" made on 2.4.2) into the latest dev build causes this error: 

When loaded into TAStudio:

https://cdn.discordapp.com/attachments/320041228009996289/747509732255989790/unknown.png

(note, this error will not go away no matter how many times I try to click it away, it also prevents me from closing bizhawk, the only way I can get rid of it is from restarting my computer)

When loaded into BizHawk itself: 

https://media.discordapp.net/attachments/320041228009996289/747516344521588796/unknown.png

here is the bk2 I tried to load:

http://tasvideos.org/userfiles/info/65610137879066220

I can still record movies in the dev build, but I just cant load old ones into it.

**Comment by EZGames69** [comment]
I have figured out the cause of the issue, somewhere down the line the sync settings for the controller setup changed.

this is how it looks (dev on the left, and 2.4.2 on the right): 

![image](https://user-images.githubusercontent.com/44628443/91082326-8992f500-e616-11ea-8f16-3d2d2c8e9621.png)

The changes was each controller type for each port now can be set individually, where as in previous versions of bizhawk, it was under one setting, where you set the player type to "One Player, Two Players, etc".

**Comment by nattthebear** [comment]
Loading movies from older versions is always an "at your own risk" thing.  If a setting changed and you need to manually modify the movie's sync settings, then a setting changed and _you_ need to manually modify the movie's sync settings.

**Comment by RetroEdit** [comment]
Crashing and leaving the user stuck seems to me not an ideal behavior, even if we aren't intending to support the old movie format.

**Comment by nattthebear** [comment]
For reference, this was the genesis change https://github.com/TASVideos/BizHawk/issues/1750

**Comment by YoshiRulz** [comment]
It looks like this was found after changing the sync settings schema, but the crash could be caused by any malformed movie. The new schema just causes the controller setup to be interpreted wrong.

The linked movie's `Input Log.txt` starts like this:
```
[Input]
LogKey:#Power|Reset|#P1 Up|P1 Down|P1 Left|P1 Right|P1 A|P1 B|P1 C|P1 Start|P1 X|P1 Y|P1 Z|P1 Mode|#P2 Up|P2 Down|P2 Left|P2 Right|P2 A|P2 B|P2 C|P2 Start|P2 X|P2 Y|P2 Z|P2 Mode|
|..|............|
```
Is that even valid?
