### ISSUE TITLE
GBHawk is forced when using GBC BIOS with GBCinGBA mode

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2327]
Version: #44d7603

Repro:
1. Open a GBC ROM
2. Go on GB > Settings... 
3. Set "Enable official Nintendo BIOS" to True
4. Set "CGB in GBA" to True
5. Click on OK
6. Reboot core.

You'll see that the active core has been changed to GBHawk. Trying to set back to Gambatte doesn't work. The only way to use Gambatte again is to delete the config.ini file.

**Comment by nattthebear** [comment]
Cannot reproduce.  Are you sure you just aren't missing the bios file?  Check your firmware configs.

**Comment by ThunderAxe31** [comment]
I'm sure. Have you tried deleting the config.ini before following the repro steps?

**Comment by alyosha-tas** [comment]
There is a new BIOS file (just recently dumped apparently) that is the real GBA mode BIOS. Gambatte uses this file with BIOS on. If you don't have it, it will default to GBHawk (which still defaults to the old GBC + patch method.
