### ISSUE TITLE
Unhandled exception: "VirtualAlloc() returned NULL" when launching TAStudio

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2338]
Version: #44d7603

Repro:
1. Open any ROM
2. Launch TAStudio
3. If you don't get any error message, close TAStudio and open it again until you eventually get it.

Full error report: https://pastebin.com/Unk7JN4d
System specs: https://pastebin.com/NmjkJywn

**Comment by nattthebear** [comment]
@adelikat With "If you don't get any error message, close TAStudio and open it again until you eventually get it", are we disposing consistently every time, or possibly waiting for the finalizer?

**Comment by ThunderAxe31** [comment]
I just noticed that the chances of incurring in this error are much higher if I have much more RAM used by other programs.

**Comment by nattthebear** [comment]
faa3d52500c69476519bef45f7a06aa28593d8df fixed this well enough
