### ISSUE TITLE
Disconnect SNES Controllers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#234]
```
What steps will reproduce the problem?
1. Play Tiny Toon Adventures Wacky Sports Challenge
2. Select Start Game
3. You will need to push the A button on Player 2 to start playing

What is the expected output? What do you see instead?
I would like a way to turn off SNES Controllers that I don't want/need.

What version of the product are you using? On what operating system?
SVN Build r7446

Please provide any additional information below.
This applies to all SNES Cores only.
```

Original issue reported on code.google.com by `hegyak` on 29 Jul 2014 at 1:10

**Comment by adelikat** [comment]
I'm going to take a stab at this (finally).

This task will be specifically about setting up a controller config dialog similar to other cores.  These will be sync settings that will require a core reboot.

Being able to do this on the fly wont' be apart of this task.  Also, peripherals and multitap are out of scope of this task (but this paves the way for those being more feasible)

**Comment by hegyak** [comment]
@adelikat What, if anything was done towards this?  Or is this going to be a future bug fix thing?

**Comment by adelikat** [comment]
We have a full controller configuration with peripherals and multitap, and ability to disconnect
