### ISSUE TITLE
Tastudio - instantiates 2 TasStateManager instances on load

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#2343]
This is an expensive thing to new up, since it allocates a lot of memory.

We have to instantiate one in the constructor of TasMovie, and then we do it again when loading a movie.

We could easily move the constructor instantiation to Attach() and check for null (if not null, we have already loaded it from a .tasproj file).  However, then it cashes because it saves before it loads.  Why does it do this? because when generating a default tasproj on Tastudio load, we save and load it.  Why do we save and load it? Because we must reboot the core, and this mask systemic problems in how we queue a movie, reboot a core, and load a movie.

This isn't easy to detangle but it needs to be done, and would have a nice performance boost on Tastudio load (the double benefit of not instantiating the manager twice, and not saving/loading to disk)

**Comment by nattthebear** [comment]
I doubt this is expensive.  VirtualAlloc() calls and VirtualFree() calls are very lightweight and don't incur any of the overhead of a traditional allocator.  Has this been profiled as a real issue?

**Comment by adelikat** [comment]
I guess I ASSumed they were expensive.  The detangling still needs to occur however.

**Comment by YoshiRulz** [comment]
I put a print statement in the `ZwinderStateManager` ctor and it only printed once when I opened TAStudio (was on `master` at 60da77053). Has this been fixed?
