### ISSUE TITLE
Controller Axis.Mid needs to be renamed

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#2345]
Axis.Mid implies that it is a value that is mid-way between min and max.  However, it's usage is in determining what the "resting" state is for a control.  This is often the midway point but not always.

We need to rename this to Default, or RestingState, or something more precise as to it's intended behavior

**Comment by RetroEdit** [comment]
I vote `RestingValue` (at least, that's what my PR that attempted to address the light sensor problems renamed it to, but then YoshiRulz re-implemented it a separate way and didn't retain that change).

**Comment by YoshiRulz** [comment]
My idea was `Neutral` or `NeutralValue`.

FWIW "resting" doesn't work for switches that stay in whatever state you choose ("gear shifters"), though as came up when discussing the TG-16(?) controllers, we'll probably need to come up with a new abstraction for those.

**Comment by adelikat** [comment]
I am happy with Neutral:   Min, Neutral, Max, pretty intuitive what those values mean
