### ISSUE TITLE
Update mGBA before 2.5?

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2348]
I'll just put this here so it's somewhere public and not just in some IRC logs.

mGBA in BizHawk is somewhat out-of-date and endrift has told us what the last safeish commit of mGBA was (https://github.com/mgba-emu/mgba/commit/0a52f44fa822539200f5ae6aad1fe5f5a6a3ab0e).

feos built this successfully, but said there were some problems running BizHawk, which was `System.AccessViolationException inside the BizAdvance() call`. [bizhawk-0.9-update](https://github.com/TASVideos/mgba/tree/bizhawk-0.9-update) stored the build.

However, when endrift tried to test it she wasn't able to reproduce the problem. [Note: I rebased the branch to add my savedata memory domain fix, but it is unlikely to affect any problem that feos may have had.]

Hopefully @feos can give us some more information about the problem so we don't merge in a broken mGBA.

**Comment by vadosnaprimer** [comment]
It's fixed now, though there might be other commits worth cherry-picking?

**Comment by RetroEdit** [comment]
(fixed except for the Linux dll, which I assume @YoshiRulz will take care of.)

**Comment by YoshiRulz** [comment]
eed111bd8 and d5c24b367
