### ISSUE TITLE
Hide GBHawk's "Use Existing SaveRAM" sync setting in release versions

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2354]
Version: 2.5.0. In the Sync Settings tab, there is one setting called "Use Existing SaveRAM". This affects casual play, but it's actually ignored when making a movie, as that is actually decided by the movie creation dialog. This setting should be removed from the Sync Settings tab, as that's already handled by the movie creation dialog window.

**Comment by RetroEdit** [comment]
I think @alyosha-tas was involved in implementing that? I am also curious about this setting, since it seems odd for a setting like this to be specific to Game Boy emulators.

**Comment by alyosha-tas** [comment]
It's use is to explore how the game deals with SaveRAM without having to worry about any existing SRAM files, it's a valuable development tool (at least for me, I use it pretty regularly.) I prefer to leave it in sync settings as that's where other settings that require a core reboot are.

**Comment by adelikat** [comment]
@alyosha-tas: then can I ask you to add a description attribute to them suggesting they are for development? also, to make sure all of them default to true?

**Comment by alyosha-tas** [comment]
It already defaults to true in 2.5.

I'll add something to the description.

**Comment by adelikat** [comment]
Yeah, some were true, I just wanted to be sure we didn't miss one.  Thanks for adding the descriptions 👍

**Comment by ThunderAxe31** [comment]
@alyosha-tas This feature does still override the SRAM value in the SyncSettings.json of movies created, which is bad, as it may cause a SRAM-anchored movies created to not use use SRAM when false, or to incorrectly report a non-SRAM-anchored movie when true. The SRAM value inside a .bk2 should be decided by the movie creation window, by setting "Record from SaveRAM", and NOT via the Sync Settings window.

Also, since you need this for development purposes, why don't you make it visible for dev builds only?

**Comment by YoshiRulz** [comment]
GBHawk's sync settings dialog is autogenerated. Adding a new attribute to the generator just for this one prop seems a bit much, #wontfix.
