### ISSUE TITLE
mGBA - important savestate deserialization fix

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2355]
~~This commit is important:~~

~~https://github.com/mgba-emu/mgba/commit/27b31024cee96991735069a72d5d709dcb9ebb9e~~

Currently, this means savestate loading in mGBA will imperfectly restore the exact state that was saved, which could cause desyncs. We'll want to cherry-pick or otherwise include this commit before the next release.

EDIT: The linked commit doesn't specifically change any code, but there's probably an issue in upstream mGBA that endrift is looking into.

**Comment by InfamousKnight** [comment]
Um, that commit is 7 days old, and we already rebuilt mgba twice in the past 2 days.

So this isn't really an issue. If it ain't broke dont fix it

**Comment by RetroEdit** [comment]
You're entirely mistaken @InfamousKnight . Updating mGBA has been an ongoing discussion we've been talking about in `#bizhawk` IRC and some tickets (#2348 , #1620).

Yes, it is true we updated 2 times. But we didn't update all the way to this commit, because it was past the commit endrift said was safe. However, what we should have done was cherry-picked this commit into 2.5, because it's a literal savestate bug that endrift fixed and told us we should include.

Please do your research before dismissing an update ticket as "we've updated too many times already".

**Comment by vadosnaprimer** [comment]
> **we** already rebuilt mgba twice in the past 2 days.

I don't remember you participating.

**Comment by InfamousKnight** [comment]
I'm sorry. Its unfortunate that as a part of human nature we make
assumptions.

**Comment by RetroEdit** [comment]
Okay, so that particular commit I linked does not specifically affect BizHawk, because it only changes a Game Boy specific.

However, @endrift thinks this indicates there is probably a similar issue in the deserialization code for GBA savestates that needs to be resolved, so it seems reasonable to keep this ticket open until that is resolved.

**Comment by endrift** [comment]
This can be closed, I'm pretty sure. I believe I verified that there was no action necessary on the GBA side.
