### ISSUE TITLE
Bizhawk 2.50 virus!

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2356]
Bizhawk 2.50 virus!

see image
![Capture](https://user-images.githubusercontent.com/67816530/91673686-4b5c7080-eb03-11ea-9927-c7967784980d.PNG)

**Comment by YoshiRulz** [comment]
That's new. Did you download BizHawk from [this page](https://github.com/TASVideos/BizHawk/releases)?

**Comment by jjfmz42015** [comment]
> That's new. Did you download BizHawk from [this page](https://github.com/TASVideos/BizHawk/releases)?

yes.

First time ever seeing this with bizhawk.

Maybe false positive?

**Comment by zeromus** [comment]
Virus reports only matter if theyre from virustotal, where this package is 0/78 hits.

**Comment by YoshiRulz** [comment]
Check the file's hash to make sure there really isn't a trojan (could have been injected by a browser extension or dearchival program):
PowerShell: `Get-FileHash C:\Users\HTPC\Downloads\BizHawk-2.5.0.zip -Algorithm SHA512 | Select-Object Hash`
Command Prompt: `certUtil -hashfile C:\Users\HTPC\Downloads\BizHawk-2.5.0.zip SHA512`
Output should be: `cb35924402932f13f3ed7159bd5991c58790287c856db6958f41b631a36c345c5ddea5249d75560ae608c2900c939579fb395989939f99bf11b4b3b9e2e671ae`

**Comment by jjfmz42015** [comment]
the file at this link https://github.com/TASVideos/BizHawk/releases/download/2.5/BizHawk-2.5.0.zip

most def is a trojan.

**Comment by zeromus** [comment]
https://www.virustotal.com/gui/url/377c2f7e5c3d0c08d8306da96145b6b7779b504d5934aa554797e4aca0d3b570/detection

**Comment by YoshiRulz** [comment]
Nobody else has had it flagged by antivirus, and as zeromus has shown, it got a pass from VirusTotal (I'm in infosec and can vouch for that site's reliability). Which is more likely: that your one machine has malware, or that the release has malware and it's gone undetected? Check the hash, if it doesn't match then you're infected.

**Comment by RetroEdit** [comment]
Discussion continued at #2357 because the discussion here was locked.

**Comment by YoshiRulz** [comment]
My Win10 machine is giving me the same anti-virus warning now (it wasn't when I originally downloaded the file, maybe because I put it on `F:\`).

The good news is that it's only a false positive. The bad news is that it's annoying for users and makes us look bad.

**Comment by RetroEdit** [comment]
Yep, it got quarantined for me on Windows 8.1 with the same error message.

**Comment by Bio37** [comment]
> https://www.virustotal.com/gui/url/377c2f7e5c3d0c08d8306da96145b6b7779b504d5934aa554797e4aca0d3b570/detection

https://www.virustotal.com/gui/file/b16aaa38d66cb93a188aa4a1fe6702df9678431c0c5d2ca365989bd021ca5681/detection

**Comment by Bio37** [comment]
This was actually from an uploaded emuhawk.exe

**Comment by Bio37** [comment]
Nevermind i get it. Thanks for clearing that out

**Comment by YoshiRulz** [comment]
I've run 2.5.1 through the same check and it appears unaffected: [`BizHawk-2.5.1.zip`](https://www.virustotal.com/gui/file/de02f02b989c80b6bf30197ddef70aa55eaebcdc0ba2e2459ae4315326bc097e/detection), [`EmuHawk.exe`](https://www.virustotal.com/gui/file/f83bcfbb224ad3db6a39421603a9016b031a9ce352fc11f1294ef45a8d0858c1/detection). This time around, the archive has a false positive from some Chinese AV I've never heard of that doesn't seem to be available (outside China? anymore?).
