### ISSUE TITLE
mGBA: Glitched stripes in the background graphics (Kirby and the Amazing Mirror)

### ISSUE THREAD

**Issue by gocha** [TASVideos/BizHawk#2361]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Glitched stripes are displayed on the background graphic in Kirby and the Amazing Mirror.

### Repro
1. Start the game and view the title screen

### Output
![mgbahawk](https://user-images.githubusercontent.com/332500/91728804-94352780-ebde-11ea-8034-2b8a8081c658.png)

Below is the expected output from mGBA 0.8.3 official:

![mgba](https://user-images.githubusercontent.com/332500/91728876-b0d15f80-ebde-11ea-91f5-65e6f3f8158c.PNG)

### Host env.
- BizHawk 2.5.0; Win10 Pro 1909
- BizHawk 2.4.2; Win10 Pro 1909

**Comment by RetroEdit** [comment]
![KAM_Title_BizHawk2 5](https://user-images.githubusercontent.com/30182911/91739209-1dc60480-eba1-11ea-9a3f-15ca0e24b749.png)

I tried this in BizHawk 2.5.0 and couldn't reproduce. I'm on Windows 8.1.

BizHawk is actually using a newer version of mGBA than 0.8.3. BizHawk is currently at the equivalent of  https://github.com/mgba-emu/mgba/commit/0a52f44fa822539200f5ae6aad1fe5f5a6a3ab0e but upstream doesn't appear to have this issue.

Thanks for including the screenshots.

**Comment by gocha** [comment]
Thank you for your feedback. I will re-check the problem with a fresh install when I have a time. Thanks.

**Comment by gocha** [comment]
I am sorry. This issue is invalid.

A broken GBA BIOS file caused this behavior. Once I used the correct GBA BIOS file (which is exactly 16384 bytes long, and has the SHA256 hash `fd2547724b505f487e6dcb29ec2ecff3af35a841a77ab2e85fd87350abd36570`) the problem is gone.
