### ISSUE TITLE
DS4 gamepad not working in BizHawk v2.5

### ISSUE THREAD

**Issue by podstanar** [TASVideos/BizHawk#2362]
Hey, since updating from 2.4.2 to 2.5, DS4 gamepad (xinput over DS4Windows) is not recognised. On v2.4.2 it works.
No, it's not old settings file, i deleted that.

**Comment by podstanar** [comment]
Fixed.

**Comment by nattthebear** [comment]
Care to leave a bit of insight on how you fixed it, in case someone else hits the same problem?

**Comment by InfamousKnight** [comment]
I actually had the same problem. It worked once and then after reboot it
stopped. Probably has nothing to do with bizhawk though

**Comment by zeromus** [comment]
2.5 doesnt work with my gamepad out of the box. It's because opentk can't read an xpad. I need @YoshiRulz to give a rationale for changing the default to opentk (and we need a plan to find out why opentk can't handle my xpad) or else I'm changing it back to the old code by default

**Comment by YoshiRulz** [comment]
> &lt;zeromuisan> opentk (DEFAULT) is not working with my xpad....
> &lt;zeromuisan> any rationale for changing the default?
> &lt;Yoshi> No SlimDX on .NET Core... Was the gamepad plugged in when you started EmuHawk?

**Comment by zeromus** [comment]
Yes.
That's not a rationale for changing the default, except to discover that it's broken and it's a blocker for using .net core.
Please change the default back. Detect which runtime youre on, if you have to.
