### ISSUE TITLE
Turbonyma - No sound unless frame 0 is emulated

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#2365]
On the turbonyma core:
1)  Advance to some point in the game
2) Make a savestate
3) Pause
4) Reboot core
5) load state
6) unpause
There will be no sounds.

If you have a movie, you can do this with a savestate on frame 0, and note that if you load the state on 0, the sound will be restored

**Comment by nattthebear** [comment]
I have a good idea what's causing this, and it shouldn't be too hard to fix, will just need some untangling.

This probably affects some of the other mednacores.

**Comment by nattthebear** [comment]
Same thing happens in PCFX, and with PCFX, a lot of the video is broken as well (some of the layers are missing color, some are full on black.)

**Comment by nattthebear** [comment]
Another effect of the same issue:  Do the following in PCFX or PCE:

1. Load core
2. Save state at frame 0
3. Advance one frame
4. Load state from step 2.
5. Goto 3.

You'll leak memory within the waterbox, eventually crashing when it runs out of memory in its preallocated pool.
