### ISSUE TITLE
TAStudio context menu spawns a bit too close to the cursor

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2369]
Several times, I have accidentally double-clicked right click and accidentally deleted a marker from a frame. If it was a bit farther away, this wouldn't happen.

I'm not sure how configurable this is, but it would be a nice little enhancement.

**Comment by adelikat** [comment]
The context menu spawns at the same pixel position as any winforms, right on the cursor point.  I also tried random things like visual studio and context menus spawn in the same place.  I don't think we should deviate from standard behavior

**Comment by YoshiRulz** [comment]
https://github.com/TASEmulators/BizHawk/commit/128c8e6218ef50b7d298b6ee2db319173607bad6 doesn't change the context menu's behaviour. It restores the default location of child dialogs.

You can right-click-and-hold by the way.
