### ISSUE TITLE
CycleCount saved to file may not be correctly handled through power-cycling

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2374]
I just realized this is an issue for GBHawk at least, so my code is still somewhat flawed:

https://github.com/TASVideos/BizHawk/blob/cdf20ff1bed4f9d200b9040396af7d778e71c20d/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs#L75-L90

I would assume it's an issue for Gambatte as well, which means there's more work to be done.

~~This actually introduces some complexity: it means intermediate states have to be taken into account, and invalidated properly, instead of simply having a good number at the end in all cases.~~ Nah, this is technically accurate, but zeromus pointed out I'm framing this wrong. We can just store something like a `CumulativeCycleCount` in savestates.

Further context: for Game Boy movies, accurate cycle count calculation is required for accurate timing, because video frames are variable length.

EDIT: This is not a problem for Gambatte. The CycleCount is properly accumulated on the BizHawk side already.

**Comment by alyosha-tas** [comment]
GBhawk uses equal length frames, it does not need to save cycle count

**Comment by nattthebear** [comment]
> GBhawk uses equal length frames

Any chance we could fix that?  Kind of silly that the first party core is both slower and less featureful than the 3rd party port job :/

**Comment by alyosha-tas** [comment]
I have equal length frames on purpose for simplicity of audio implementation (for cases like where audio is playing while the screen is off.) I don't really think it needs to be changed / fixed.

**Comment by RetroEdit** [comment]
@alyosha-tas What about SubGBHawk? I see code above saving the cycle count, does SubGBHawk keep a running total of the cycle count that GBHawk doesn't?

**Comment by alyosha-tas** [comment]
SubGBHawk accurately keeps track of cycle count through resets.
