### ISSUE TITLE
Tasproj version identifier can have a different decimal mark

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2377]
A user reported on Discord that the movie version was being saved with a comma instead of a period with certain language settings:

```MovieVersion BizHawk v2.0 Tasproj v1,1```

instead of 

```MovieVersion BizHawk v2.0 Tasproj v1.1```

This is a problem: the decimal separator written the movie file should not be operating-system dependent.

**Comment by zeromus** [comment]
Can we use `DefaultThreadCurrentCulture` and set it to Invariant so this scourge is eradicated?

**Comment by YoshiRulz** [comment]
I assume that overrides the system language/culture for the lifetime of the program? That would prevent us adding translations in the future.

**Comment by zeromus** [comment]
Translations arent in the plan for bizhawk EVER. I do not accept this rationale.
