### ISSUE TITLE
Add support for .m3u bundled PSX games again

### ISSUE THREAD

**Issue by KillshotELO** [TASVideos/BizHawk#2378]
Hello I am running Bizhawk 2.5 , I tried opening Grandia.m3u for the PS1, it's a combination of Grandia disc 1 & 2 , Bizhawk 2.5 says it doesn't support m3u, can someone please add m3u support back to Bizhawk, thanks. I was able to run m3u discs on past versions of Bizhawk, I would really appreciate it if someone could help get m3u support back on Bizhawk, thanks.

**Comment by YoshiRulz** [comment]
`.m3u` support was dropped in 86ac6eadc. It was initially added because Mednafen supports/supported it, and we didn't have a good multi-disk system at the time.

Our current multi-disk system is using `.xml` files created with the Multi-disk Bundler, found under `Tools` in EmuHawk.

**Comment by nattthebear** [comment]
Willing to leave this open as a legit feature / regression ticket.  Unfortunately, the old m3u support was never complete and hacked in to PSX only, and the developer who made it absolutely refused to clean it up, and no one else saw much of a need for it as we have the xml bundler.

**Comment by KillshotELO** [comment]
Ah I see, I didn't know .xml replaced .m3u. I am not too familiar on implementing disc code onto .xml ; on my m3u file for Grandia I have my Grandia Discs set as
Grandia (Disc 1).cue
Grandia (Disc 2).cue
I will make some .xml files and see what works.
    On Monday, September 7, 2020, 4:29:20 AM CDT, James Groom <notifications@github.com> wrote:  
 
 


.m3u support was dropped in 86ac6ea. It was initially added because Mednafen supports/supported it, and we didn't have a good multi-disk system at the time.

Our current multi-disk system is using .xml files created with the Multi-disk Bundler, found under Tools in EmuHawk.

**Comment by KillshotELO** [comment]
Okay, I didn't know .xml was a better alternative, I will look into updating my .m3u files to .xml . Thanks.

     On Monday, September 7, 2020, 10:07:26 AM CDT, nattthebear <notifications@github.com> wrote:  
 
 


Willing to leave this open as a legit feature / regression ticket. Unfortunately, the old m3u support was never complete and hacked in to PSX only, and the developer who made it absolutely refused to clean it up, and no one else saw much of a need for it as we have the xml bundler.

**Comment by KillshotELO** [comment]
Hi James, I believe I got the XML to work on Bizhawk 2.5 ; I attached a copy of the source code, do you have any suggestions on how to transfer over save states from Bizhawk 2.4 to 2.5.0 ; from what I noticed I always get error codes when I attempt to manually load the save states after an update, I am not sure if anyone ever found a way around this, or if this can be fixed through an update in the future.
    On Friday, September 11, 2020, 4:39:11 PM CDT, Emilio Ortiz <emilioortiz4@yahoo.com> wrote:  
 
  Ah I see, I didn't know .xml replaced .m3u. I am not too familiar on implementing disc code onto .xml ; on my m3u file for Grandia I have my Grandia Discs set as
Grandia (Disc 1).cue
Grandia (Disc 2).cue
I will make some .xml files and see what works.
    On Monday, September 7, 2020, 4:29:20 AM CDT, James Groom <notifications@github.com> wrote:  
 
 


.m3u support was dropped in 86ac6ea. It was initially added because Mednafen supports/supported it, and we didn't have a good multi-disk system at the time.

Our current multi-disk system is using .xml files created with the Multi-disk Bundler, found under Tools in EmuHawk.

**Comment by adelikat** [comment]
Unfortunately, due to core improvements, PSX Savestates from pre2.5 are not compatible with 2.5

**Comment by YoshiRulz** [comment]
Added in 6ee62023a (PR #2390).
