### ISSUE TITLE
Turbo Fastforward with "Display Watches on Screen" causes massive slowdown

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#2379]
### Summary
Whenever you use the Turbo option to fast-forward the game while ram watches are displayed on screen, they watches will get drawn anew each frame, but the ones from previous frames never get erased. This ironically causes the game to run much slower than if you weren't fastforwarding at all.

### Repro
1. Open Ram Watch
2. Add any watches
3. Hold down your assigned Turbo hotkey to fast forward

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.2 (x64); Windows 10

**Comment by zeromus** [comment]
Note, you do have to use the hotkey (shift+tab by default); picking 'unthrottled' from the speed options doesn't manifest this bug.
