### ISSUE TITLE
Subtitles DataGrid No Way to Remove a Subtitle

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2381]
While it is possible to just make the message empty this does seem like something of a minor oversight.

**Comment by YoshiRulz** [comment]
Click the row header (where the arrow is) and press ⌫ Delete.

**Comment by ShinobiWannabe** [comment]
![image](https://user-images.githubusercontent.com/34147391/92431688-1fc23180-f166-11ea-833e-f83782e904cf.png)
Sorry I do not see the button here? Am I missing something?

**Comment by YoshiRulz** [comment]
You need to use the ⌦ Delete key on your keyboard. The on-screen keyboard in Windows should have one if your physical keyboard doesn't.

**Comment by ShinobiWannabe** [comment]
Ok I was thinking delete as a button in some popup or in the grid.  Thank you.
