### ISSUE TITLE
As of 2.4.1, Bizhawk assumes a controller is J2 instead of J1

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#2382]
If you go to "Config > Controllers" to assign a controller's buttons to their respective commands, Bizhawk 2.4.1 and above assumes the connected controller is a J2 instead of the normal J1. The only way to fix that is unplugging and plugging the controller back again. But you have to do that every time you run the emulator. 2.4 and below don't have this issue.

I made a short video showing this in detail. What I do is go through 2.3~2.5 showing what happens in each version. And in 2.5, I demonstrated the temporary "fix" by disconnecting and reconnecting the controller:
[Bizhawk Tests.zip](https://github.com/TASVideos/BizHawk/files/5192213/Bizhawk.Tests.zip)

Perhaps this should be fixed before releasing 2.5.1.

**Comment by zeromus** [comment]
1. config > customize > directinput
2. so what if it's J2? does it not work? what if it was JCOOL, would that be a problem? does it matter, as long as it works? we can not, will not, and will never guarantee that we will always display J1 for your controllers. J1 has no universal definition, nor does J2. Joysticks may be listed by your OS in any random order at any time and munged differently by controller input libraries.

**Comment by Sonia-7** [comment]
>     1. config > customize > directinput

Thanks. Merely changing from 'OpenTK' to 'DirectInput+XInput' fixed the issue.
