### ISSUE TITLE
Setting watches to autoload can result in a blank list

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2383]
Collected on some rando forum somewhere:

> Oh, and "Autoload Watches" does not seem to function when I open BizHawk by dragging a ROM onto the executable when "Autoload with Bizhawk" is selected. It works fine when I open Bizhawk first, open a ROM, then open the RAM Watch window manually. Only mentioning this because it seemed to work on past versions.

**Comment by YoshiRulz** [comment]
What does this have to do with drag+drop? After setting up a watch file, if you set the rom *and* RAM Watch *and* the watch file to autoload, then restart EmuHawk, the watch file fails to load. The watch file does of course load when closing and re-opening RAM Watch.

I repro'd on c0b6bf61b (I haven't done regression tests so I removed the label).

**Comment by adelikat** [comment]
Fixed in 82f26ee4ecb38ddd298a7fc95ab8381ebe8ed734
