### ISSUE TITLE
neopop -- english not working

### ISSUE THREAD

**Issue by threenator** [TASVideos/BizHawk#2385]
[//]: # Every time I try to play a multiple region NeoGeo Pocket ROM, the only language supported is Japanese. There are three "English" options in the Core settings, but none of them work. 

I'm using BizHawk 2.5.0, this error doesn't appear in the old versions.

**Comment by nattthebear** [comment]
> this error

Are you getting an error message then?

And can you give the name of a game this works on?

**Comment by threenator** [comment]
No, I'm not getting an error message, but I think there's something wrong with those three "English" options, none of them working: https://i.imgur.com/FESZ2LS.png

I tried with SNK vs. Capcom: Match of the Millennium, Metal Slug - 2nd Mission and Dark Arms: Beast Busters, all of them are (JUE) roms.
