### ISSUE TITLE
Drag-and-drop tasproj while TAStudio is open spawns errors

### ISSUE THREAD

**Issue by arukAdo-tas** [TASVideos/BizHawk#2386]
-start bizhawk
-recent rom>castlevania saturn iso
-emulation>pause
-drag'n'drop saturn-fast1.tasproj
-Tools>Tastudio
-emulation>pause
-emulation>pause
-drag'n'drop saturn-fast.tasproj
-error
-ok
-wait until autosave interval happen > .net error > continue
-then randomly do stuff outside bizhawk > more of the same .net error

**Comment by RetroEdit** [comment]
Okay, so dragging and dropping a tasproj in 2.4.2 did not produce an explicit error, but it also seemed to not ask before saving and just completely override the previous tasproj without properly reloading TAStudio. Ideally, EmuHawk would pass it along to TAStudio to prompt for closing the previous `.tasproj` before opening a new one, so TAStudio can properly initialize the new one.
