### ISSUE TITLE
Open a tasproj from TAStudio's recent menu automatically unpauses emulation

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2387]
It should stay paused if the emulator was paused before, not automatically unpause whenever files are loaded from the recent menu.

Edit: Okay, this probably isn't specific to the recent menu, it's probably related to the tasproj wanting to automatically restore to the previous position. It should initiate this seek, but it should still keep the emulation paused.

**Comment by adelikat** [comment]
Are you saying it doesn't stop once it is has finished seeking?  Our unofficial term for this is "run away seek".  Is this only happening on load?

**Comment by RetroEdit** [comment]
So my problem isn't specifically about runaway seek, but about the emulator automatically initiating the seek and unpausing emulation even though I previously had emulation paused.

It's kind of a minor thing, but I would prefer if the prior pause state was preserved. Of course, if the seek finishes properly, it's still paused after the seek finishes, so probably that's still a fair way of "preserving the pause state".

This is kinda a minor gripe anyway, so I'll just close it, since there are bigger fish to fry and I don't really care that much or necessarily even see this as being "wrong".
