### ISSUE TITLE
sram file not detected/used and desync

### ISSUE THREAD

**Issue by arukAdo-tas** [TASVideos/BizHawk#2388]
update for sram issue; the issue will show up regardless of what movie you are using.
It may or may not be linked to the game (castlevania nocturne in the moonlight).
what you just need to do, is start a (tastudio) project from sram, it will be easier if you have already a game file in sram
the new project will use the sram, you will have now to input sufficient frames for the greenzone to be far ahead of the actual use of sram (just load your save file inside the game, input blank for few thousands of frames)
at this point, if you try to replay from start, the movie will desync because your sram will be blank.
if you delete greenzone from your tasproj, he will regenerate it and the sram will be ok/loaded/present.

a few files to generate sram data
http://tasvideos.org/userfiles/info/66347598891274248
http://tasvideos.org/userfiles/info/66370270424611994

-----
old post below

https://workupload.com/file/kFUffDqaPLr
when you load the proj, it has a state inside that desyncs

-----SRAM issue
-drag'n'drop saturn-fast1.tasproj
-Tools>Tastudio
-load branch 5
-play from frame 0
sram is empty (advance to frame 1500)
now
-export
-close studio (dont save proj)
-drag'n'drop saturn-fast1.bk2
sram is present (advance to frame 1500)

-----

-------Desync Issue
-drag'n'drop saturn-fast1.tasproj
-Tools>Tastudio
-load branch 0
-select marker frame 0
-advance to frame 11000 and it will desync
-export to bk2
-close studio (dont save)
-drag'n'drop saturn-fast1.bk2
-advance to frame 11000 and it will sync (sram present)
-movie stop
-open bk2 and delete sram
-drag'n'drop saturn-fast1.bk2
-advance to frame 11000 and it will desync

**Comment by alyosha-tas** [comment]
The SRAM issue is a general TAStudio issue, I also encountered it using both gameboy cores.

It looks like TAStudio creates the frame 0 state before applying SRAM.

**Comment by alyosha-tas** [comment]
pretty sure I fixed the SRAM part of this,

@arukAdo-tas  please retest in master
