### ISSUE TITLE
Oem102 key stopped working

### ISSUE THREAD

**Issue by Tompala** [TASVideos/BizHawk#2389]
Since BizHawk 2.4.1, the Oem102 keyboard key stopped working when trying to assign it as a hotkey or controller input. This key is not present on all keyboard, it can be found on a Swedish keyboard between Z and Left Shift.

Nothing more to add.

**Comment by YoshiRulz** [comment]
You mentioned on Discord that trying to bind something to that key will crash with DirectInput as opposed to doing nothing. I think I know why that is.

**Comment by YoshiRulz** [comment]
Oops, forgot this was left open. This bug will not be present in the next release (2.5.3), and until then you can use a [dev build]().

Duplicate issues: #2458, #2459
