### ISSUE TITLE
v2.5 hang on opening tasproj

### ISSUE THREAD

**Issue by arukAdo-tas** [TASVideos/BizHawk#2392]
drag'n'drop saturn-fast-replay.tasproj
https://workupload.com/file/ZqsFRmEWCzS

**Comment by adelikat** [comment]
What game is this tasproj for?

**Comment by nattthebear** [comment]
The tarseproj file here is badly broken, the greenzone lump is way too small.  With 302b12c this will now give an error instead of hanging.

Whatever bug there may be here happened when the tarseproj was originally saved.  How did you make it and can you reproduce this?

**Comment by adelikat** [comment]
I confirmed that if you delete the greenzone file, that the .tasproj will load fine, so the work can be salvaged if needed.

**Comment by arukAdo-tas** [comment]
I dont need to salvage stuff and sry for slow answer.
To produce such a file, my best guess would be to use sram.
I can try to reproduce steps but they will all be depending on a tasproj that will be broken too, so im not too sure how to avoid the redundancy in this.
The game is castlevania symphony of the night btw.

**Comment by nattthebear** [comment]
The brokenness here matches 757ac4e27ef5654453eda392a2d reasonably well, so I think we fixed it.
