### ISSUE TITLE
event.onexit() not working since 2.5

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#2393]
Lua function `event.onexit()` stopped working since the version 2.5.
This can be checked with the simple lua script:
```lua
event.onexit(function()
  print("'event.onexit' is working!")
end)

while true do
  emu.frameadvance()
end
```
When closing/reloading the script, it should output "`'event.onexit' is working!`", as it does with previous versions such as 2.4.2, 2.4.1, etc.

**Comment by zeromus** [comment]
caused by ed9b7b3eb1633fb921b1763e1f87533d96dfeb5c `DetachedRegisteredFunctions()` call added to line 635 of LuaConsole.cs 
That didn't make any sense to me. Looks like a brain fart.
maybe this commit helps

**Comment by brunovalads** [comment]
@zeromus your 82c4fa48810b7c0fbea882f23ae126ff58ff784b commit solved this issue!

**Comment by zeromus** [comment]
The real question was whether it reversed whatever adelikat was trying to do

**Comment by adelikat** [comment]
I think this change is solid and captured the intent of what I was trying to do there.  I'm not sure what all edge cases I had specifically fixed, but the original tickethttps://github.com/TASVideos/BizHawk/issues/1920 is still fixed after this commit, so I think we can consider this closed.
