### ISSUE TITLE
PSX Movie Desyncs in 2.5.1

### ISSUE THREAD

**Issue by Samtastic1** [TASVideos/BizHawk#2396]
### Summary
[//]: # "When recording a PSX movie and copying/pating frames from a previous movie made in a previous version, the movie will often desync at random places whilst recording a movie. It keeps sync in Bizhawk 2.3.3. 

### Repro
1. Start recording a movie. 
2. Copy and paste frames from a previous movie 
3. Most of the time the movie will sync like in 2.3 but sometimes after loading a save state the movie will desytnc and I have to re-record input again. 

`

### Host env.
- Bizhawk 2.5.1 - Windows 10 x64 Intel 

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by zeromus** [comment]
https://github.com/TASVideos/BizHawk/issues/2214
