### ISSUE TITLE
CGP shaders aren't working correctly

### ISSUE THREAD

**Issue by Colact** [TASVideos/BizHawk#2397]
I've tried to use one of the libretro common shaders available and it didn't work with the new BizHawk 2.5.1 . The same shaders worked perfectly with older versions (2.4 and previously).
https://github.com/libretro/common-shaders

On BizHawk previous versions:
![bizhawkissueshader](https://user-images.githubusercontent.com/71272832/93113554-b6737e80-f68f-11ea-8402-62809253cb75.png)

Shader location and function ".\xsal\4xsal-level3-xbr-soft.cgp"  remove spurious scale_type source entries

BizHawk 2.5.1 

Exception

 ===================
> Pass 0:
> Vertex Shader:
>  System.InvalidOperationException: Error compiling shader: E:\BizHawk-2.5.1\memory(2,9): warning X3568: 'parameter' : unknown pragma ignored
> E:\BizHawk-2.5.1\memory(3,9): warning X3568: 'parameter' : unknown pragma ignored
> E:\BizHawk-2.5.1\memory(4,9): warning X3568: 'parameter' : unknown pragma ignored
> E:\BizHawk-2.5.1\memory(138,14): error X3000: syntax error: unexpected token 'texture'
>  --- SlimDX.CompilationException: E:\BizHawk-2.5.1\memory(2,9): warning X3568: 'parameter' : unknown pragma ignored
> E:\BizHawk-2.5.1\memory(3,9): warning X3568: 'parameter' : unknown pragma ignored
> E:\BizHawk-2.5.1\memory(4,9): warning X3568: 'parameter' : unknown pragma ignored
> E:\BizHawk-2.5.1\memory(138,14): error X3000: syntax error: unexpected token 'texture'
>  --- SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)
>    at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
>    at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
>    at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
>    at SlimDX.CompilationException.Check[T](Int32 hr, String errors)
>    --- End of inner exception stack trace ---
>    at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
>    at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateVertexShader(String source, String entry, Boolean required)
>    --- End of inner exception stack trace ---
>    at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateVertexShader(String source, String entry, Boolean required) 
> -------
>Fragment Shader:
>System.InvalidOperationException: Error compiling shader: (138): error X3082: Object types are not allowed in structs
>--- SlimDX.CompilationException: (138): error X3082: Object types are not allowed in structs
>--- SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)
>    at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
>    at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
>    at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
>    at SlimDX.CompilationException.Check[T](Int32 hr, String errors)
>    --- End of inner exception stack trace ---
>    at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
>    at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)
>    --- End of inner exception stack trace ---
>    at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)

**Comment by zeromus** [comment]
retroarch shaders no longer work verbatim, and this won't change. Retroarch shaders aren't really designed to work without a huge amount of support from retroarch apparatus. This became too difficult to maintain reliably in bizhawk. You will have to revise the shaders to work in bizhawk. Feel free to post the fixed shaders and we'll put them in the bizhawk repository
