### ISSUE TITLE
TAStudio InputRoll ObjectDisposedException after importing .bk2

### ISSUE THREAD

**Issue by scrimpeh** [TASVideos/BizHawk#2398]
Tested in BizHawk 2.5 and latest master as of writing this issue.

How to reproduce:

1.Import .bk2 with TAStudio
2.Close TAStudio
3.The exception will be thrown immediately on reopening TAStudio.

Seems to be independent of system. It also seems to only happen after importing a .bk2, for whatever reason.

Edit: On further examination, it appears that `_initialized` in TAStudio.cs is not being set when loading a .bk2, which causes the form to not close properly. The culprit appears to be line 128 in TAStudio.MenuItems.cs where `_initialized` is being set to false again. Looks like it should be `_initializing`
I added a pull request with something that should fix it.

**Comment by nattthebear** [comment]
The title of the ticket says "InputRoll" but no further mention of that is made in the body of the ticket.  Did you forget to include some information?

**Comment by scrimpeh** [comment]
@nattthebear 
InputRoll is the class in which the exception is being thrown.
