### ISSUE TITLE
Lua Console - Sessions Cannot Be Saved in 2.5.1

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2400]
The Lua Console sessions don't seem to save.

**Comment by zeromus** [comment]
the contents of the .luases file are nonsense

**Comment by adelikat** [comment]
@zeromus : how is this a helpful comment? Ridiculous.

**Comment by adelikat** [comment]
@ShinobiWannabe : seems to save fine for me, can you provide any more details?

**Comment by zeromus** [comment]
I mean, the session actually saves, or rather that a .luases is created. But the contents are messed up (the paths are simply not correct, the filenames are getting messed up long before they get saved so that at the point when theyre saved the values are messed up)

**Comment by ShinobiWannabe** [comment]
Actually looking at the path of the script now it literally looks like the Lua Console is trying to load the Session file AS the Lua script file if you look at it.  

Repro steps.

1. Open up a game in Bizhawk
2. Open Lua Console
3. Open a script(s) and load it up on LUA console
4. File -> Save Session As
5. File ->Open Session

Now while it might appear that it worked it does not actually work. If you attempt to open those scripts you will see that they are non files or are corrupt.


Ex: screenshots
Before saving session
![Right before saving session](https://user-images.githubusercontent.com/34147391/93693350-ca264700-facc-11ea-8423-8ac1667886f6.PNG)

After loading session (notice how it just loses the script names?
![After Loading Saved Session](https://user-images.githubusercontent.com/34147391/93693349-b975d100-facc-11ea-8386-30e2278c2ca4.PNG)

Trying to run a script the saves session opens
![image](https://user-images.githubusercontent.com/34147391/93693365-f6da5e80-facc-11ea-97b0-3481b7221a12.png)

Trying to Edit a "script" that the session loads up just has windows ask for what program should be used to open it and it opens the session file.
![image](https://user-images.githubusercontent.com/34147391/93693398-520c5100-facd-11ea-9e76-5ad9ae30bbfb.png)

**Comment by adelikat** [comment]
I'll take a look, thanks for the extra details
