### ISSUE TITLE
Lua Console Menu : Script -> "Select All" Does Not Select All in 2.5.1

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2401]
The menu option and the shortcut do not work to select all the scripts loaded in the Lua Console.

**Comment by zeromus** [comment]
While checking this, keep in mind the input roll rendering is majorly glitched (will take a few hours to fix) which will make even diagnosing this problem difficult due to repaints not happening

**Comment by ShinobiWannabe** [comment]
This is just for the Lua Console grid.  If you have multiple scripts, and then try the CTRL + A shortcut, or the menu option then it fails to select all the scripts.  The input roll is tasstudio as far as I understand it.  Attached a screenshot of where it is occuring.
![Lua Console grid](https://user-images.githubusercontent.com/34147391/93165098-2bbf6d80-f6e9-11ea-991e-f3c973722e0b.PNG)

**Comment by zeromus** [comment]
I don't think whoever replaced this with the inputroll fully thought through how the semantics ought to be a LISTVIEW and not an INPUTROLL. Thus automatically breaking many, many, many expected behaviours. Recreating a listview is not easy, and that's not even inputroll's job.

**Comment by ShinobiWannabe** [comment]
Oh that is weird.  Thanks for the explanation.

**Comment by adelikat** [comment]
1) whoever = me, and you know that.
2) I did INTEND it to be a drop in replacement of a listview, and it DOES
3) There may be a few oversights, but that's not an indictment of the whole process
