### ISSUE TITLE
Lua Console Menu : Help -> "Documentation Online..." Does Not Open TasVideos LuaFunctionsWebPage in 2.5.1

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2402]
In 2.4.2 this button opens up http://tasvideos.org/BizHawk/LuaFunctions.html in chrome.  However in 2.5.1 I get the chrome error "chrome.exe - Application Error"  "The application was unable to start correctly (0xc000007b).  Click OK to close the application."  So the fact that it worked in an earlier version of Bizhawk is making me think this is a bug.

**Comment by zeromus** [comment]
Reboot your computer and turn off your security software. This code hasn't changed. Something larger in bizhawk may have changed, but it's only tripping a flaw in your OS install or security software

**Comment by ShinobiWannabe** [comment]
OK maybe it is related to a security software thinking this version of 2.5.1 Bizhawk is sort of virus/trojan/malware/whatever.  I did have an issue the first time I had started up Bizhawk, but after that it stopped complaining.  I tried what you suggested but it did not fix that link for this 2.5.1.  Oh well.

**Comment by zeromus** [comment]
could also be a change to our .net version (if we updated that between those versions). That would be an example of "something larger in bizhawk tripping a flaw in your OS install or security software"

**Comment by YoshiRulz** [comment]
Reproduced on 2.5.1 with the same error code (but mine says "waterfox.exe"). Could not repro on `master` at afbce436c.

**Comment by zeromus** [comment]
oh yeah, repro'd on 2.5.1 myself. I had only checked it on master previously

**Comment by zeromus** [comment]
dup #2101. fix by deleting version.dll
