### ISSUE TITLE
(FFmpeg AVI writer does not work -- Bizhawk 2.5.1)

### ISSUE THREAD

**Issue by foggystyleut** [TASVideos/BizHawk#2403]
### Summary
FFMpeg AVI writer has stopped working in Bizhawk 2.5.1 as it can no longer detect the required or correct version of the ffmpeg.exe. It last worked on Bizhawk 2.5.0.

### Repro
You open any rom file in bizhawk to select the game you want to play in Bizhawk. 
1. Then go to File > AVI/WAV> Config and Record AVI/WAV
2. Select FFmpeg writer
3. A message saying correct or required version of ffmpeg.exe not found and cannot be detected. 
https://user-images.githubusercontent.com/71349647/93258232-f9a31f80-f76b-11ea-8ce0-d96d10f66919.png

The message also says ffmpeg relies on a specific version of ffmpeg from this  link https://github.com/TASVideos/ffmpeg-binaries/blob/master/ffmpeg-20181118-529debc-win64-static_ffmpeg.7z

### Output
[//]: # 
We've downloaded the correct and required version of ffmpeg from the link above and Bizhawk 2.5.1 is still not recognizing it and still says it could not be found.

```

### Host env.
[//]: # bizhawk 2.5.1

[//]: # 
![image](https://user-images.githubusercontent.com/71349647/93258232-f9a31f80-f76b-11ea-8ce0-d96d10f66919.png)

**Comment by zeromus** [comment]
almost positively the same issue as #2402

**Comment by zeromus** [comment]
dup #2101. fix by deleting version.dll
