### ISSUE TITLE
TasStudio Branches Grid : Can Delete or Update Two Branches At Once on Bizhawk 2.5.1

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2405]
The root issue I think is that creating a new branch does not deselect the older branch. This is an issue since as I just had, you can accidentally update or delete two branches.   This can lead to accidentally updating/deleting the older branch since it leaves the previous one selected as well.

Repro steps
1. Open TasStudio
2. Make some input
3. Click the New Branch button
4. Make a change to input
5. Click the New Branch button
6. Click Update / Right Click Delete

Now both branches should have the exact same inputs if you clicked update, or both be deleted.  I would hope that making a new branch then updating it, would not affect the previous one.
![image](https://user-images.githubusercontent.com/34147391/93280339-641d8500-f797-11ea-9cc9-997677b711b4.png)

**Comment by RetroEdit** [comment]
To be clear, selecting and deleting multiple branches is an intended new feature, requested in #2215. However, it sounds like this is erroneously selecting multiple branches when it is undesirable?

**Comment by ShinobiWannabe** [comment]
If you add a new branch it really should deselect the older one to prevent this kind of issue.  Also how are you supposed to select multiple branches?

**Comment by RetroEdit** [comment]
Yeah, I think branch selection when you create a new branch is broken in 2.5 and 2.5.1. I actually had this issue recently with 2.5 that I chocked up to my own error, but you pointing this out makes me think the code has started forgetting to change the selected branch when a new branch is created.

You select just by clicking them. It switches focus from the input log to the branches.

**Comment by ShinobiWannabe** [comment]
Maybe that multi select is still in dev.  I tried holding shift / ctrl and clicking another branch, but only one would remain selected.
