### ISSUE TITLE
SNES Faust core: Trials of Mana crash

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2408]
I can't get the Faust core to open my Trials of Mana ROM. When I try, Bizhawk closes. This did not happen with Bizhawk 2.4.2 where I used the BSNES core.

**Comment by zeromus** [comment]
so use the bsnes core in whatever version of bizhawk you're using now.

**Comment by nattthebear** [comment]
Duplicate of https://github.com/TASVideos/BizHawk/issues/2394
