### ISSUE TITLE
Problem loading a LUA script (works fine in Mesen)

### ISSUE THREAD

**Issue by Nix20** [TASVideos/BizHawk#2412]
Here's the script:
[testSpriteOverflow.zip](https://github.com/TASVideos/BizHawk/files/5248620/testSpriteOverflow.zip)

Contents:
```
PPU_STATUS = 0x2002
currentStatus = 0
spriteOverflowSet = 0
prevSpriteOverflowSet = 0
hitLine = 0
hitCount = 0

function testSpriteOverflow()

  -- Read PPU Status
  currentStatus = emu.read(PPU_STATUS, 256)
  
  -- Test sprite Overflow (AND #%00100000)
  spriteOverflowSet = currentStatus&0x20

  -- Handle Hit, print once per frame, and draw a nice line.
  if(spriteOverflowSet) then 
    if(spriteOverflowSet > prevSpriteOverflowSet) then
      hitLine = emu.getState().ppu.scanline
      emu.log("HIT AT SCANLINE " .. hitLine .. "      HIT COUNT " .. hitCount)
      emu.drawLine(0, hitLine, 255, hitLine, 0x0000FF00)
      hitCount = hitCount + 1
    end
  end
  
  prevSpriteOverflowSet = spriteOverflowSet
end

-- Call testSpriteOverflow at every instruction. A little brute forcey...
emu.addMemoryCallback(testSpriteOverflow, emu.memCallbackType.cpuExec, 0x8000, 0xFFFF)
```
Works in Mesen, but in BizHawk it gives this error:
`NLua.Exceptions.LuaScriptException: [string "main"]:14: unexpected symbol near '&'`

Anyone knows the reason and how to fix it so it'd load?

**Comment by nattthebear** [comment]
`unexpected symbol near '&'`

Yes, that's exactly the problem.  Our lua system doesn't support 5.3 additions.  Try the bitwise library that we ship and is in the documentation.

**Comment by zeromus** [comment]
Besides that, bizhawk does not support mesen lua scripts and mesen does not support bizhawk lua scripts and that's how it will always be. You must port scripts from one emulator to the other.
