### ISSUE TITLE
Ram Search - "Specific Value"and "Difference Of" Column cannot search Negative Values

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2418]
If you select the "Difference of" Compare to option, and have the "Diff" Column on you can see how it is not possible to find a difference value that is negative.  Ex: if you damage an enemy and their decreases by 1, the difference is then "-1".  There is no way to search for that "Difference of".  You could use the "different by" comparison option to do 1, but then you get the range of +-1.  It seems like that Difference Box needs to allow a negative sign "-" or something.

Could be missing something but this looks like an oversight.

[image](https://user-images.githubusercontent.com/34147391/93727554-9e1ccb80-fb89-11ea-869d-306a47f984a9.png)

**Comment by adelikat** [comment]
Difference is an absolute value. If you set a diff of 1, and a value is 100, it will look for values that are 99 or 101.  Diff doesn't make sense to be negative.

As for specific value, it does allow negative but you must set the display type to signed, then you will be allowed to use negative numbers.
