### ISSUE TITLE
TAStudio slows down noticably after the project becomes larger

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2428]
Something I've noticed and several other users have reported is that TAStudio will become very sluggish once you get far enough into the project. Dragging inputs can take a few seconds once you get to 60k frames.

This is a result of the new state manager. If you configure the Savestate History Settings to allocate less space for the Current buffer and Recent buffer, ~~it will no longer be an issue~~ *EDIT*: it can still happen even at the smallest settings. However, it is still troubling that a project will slow down noticeably and likely indicates some underlying inefficiency.

~~If this is not fixable by reworking logic, I would recommend the defaults be set to be smaller, but this shouldn't be necessary.~~ This needs to be fixed by reworking the logic.

**Comment by RetroEdit** [comment]
Okay, this is unfortunately not straightforward to reproduce. I'll need to see if I can come up with a better set of reproduction steps at some point.

**Comment by RetroEdit** [comment]
I have a straightforward way of reproducing this now, thanks to Samsara.

1. Open Super Mario Bros. in NESHawk and open TAStudio
1a. Click and drag the mouse over the input roll to get a sense of the baseline speed for drawing the inputs.
2. Just unpause emulation and let around 40000 frames be emulated in TAStudio (41000 is a good target)
3. Click and drag the mouse around the 40000 frame mark. It will be noticeably slower than before, and probably take a few seconds to draw the letters corresponding to the inputs.

**Comment by nattthebear** [comment]
I probably can't do anything about this as is, but feel free to assign to me if you can't straighten it out and can explain to me exactly what calls are slow  @adelikat @RetroEdit

**Comment by RetroEdit** [comment]
@nattthebear One major issue seems to be that painting calls `ZwinderStateManager.InvalidateAfter()` several times in quick succession, once for each frame that is changed. The `StateCache.RemoveWhere(s => s > frame);` call seems to be somewhat expensive. If the state manager internally kept track of the last valid frame in a separate variable, then it could skip doing invalidation in many cases when it would be redundant.

**Comment by nattthebear** [comment]
Seems like it would also help to turn those into a single `InvalidateAfter` call

**Comment by RetroEdit** [comment]
Yeah, turning those into a single `InvalidateAfter` call might be better, but it also might be a bit complicated, due to the many convuluted layers of architecture involved in painting. The choice to call `InvalidateAfter` for each frame that was changed was made 5 years ago, so it's a bit more set-in.

**Comment by adelikat** [comment]
Fixed
