### ISSUE TITLE
[Linux] Xbox one controller stops working

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#2429]
Commit a932cce63691aa3fc6a1ef97b728fb70c11e0c61
To be more specific, it slowly breaks:

At first, I had to reload bizhawk in the terminal to get it to work, then I tried bsnes with dirt racer and made a movie with it, it would crash at random with either segmentation fault or abort with the controller plugged in. Without it plugged in I dont know. It's like it has a mind of its own. I ran lsusb to see if my controller was detected and it was.

I didn't test windows 10 and I would think its not an issue there. But I dont know.

Is anyone else having this problem?

**Comment by InfamousKnight** [comment]
Solution has been found:
Follow these steps, have controller unplugged until you open bizhawk.
Once bizhawk is open, plug controller in. Go to hotkey and try to change something like frame advance. It should fail(this is a necessary step because otherwise it just doesn't work for some reason).
Next close bizhawk and reload it. Test out the hotkey setting and now it works!

When you close bizhawk again, go back to step one(you don't have to restart the computer).

**Comment by InfamousKnight** [comment]
Reopening as the workaround above is annoying to work with and we shouldn't have to do that. Although its good I found a consistent way to reproduce.

**Comment by InfamousKnight** [comment]
Testing again on commit: cf297da
First testrun: it worked like a charm without the annoying solution! ... but after reopening the program, it stopped working for some reason.. I tried the workaround again, and that didn't work either. I tried rebooting my laptop, tried the same steps I did that got it to work in the first run(just plug the controller in and open the program and change a hotkey), I tried deleting the bizhawk folder and reextracting the files and no luck...

I wonder if a ps4 controller might have better luck. Hmm.

**Comment by YoshiRulz** [comment]
Repro'd with XBone on 2.5.3 dev at 8bbd6b2d8. Workaround didn't do anything.

**Comment by InfamousKnight** [comment]
Testing commit: 928ea05 and it worked on first load, but when I closed bizhawk and reopened to make sure, it stopped working...

**Comment by InfamousKnight** [comment]
Would OpenTK be to blame for this? I believe after updating that, it became even more dysfunctional.

**Comment by InfamousKnight** [comment]
Okay, I tested this commit: be536c6 which updates openTK to latest, it was completely broke. I tested the commit right before that, and the workaround worked. So yes, it must be OpenTK to blame here... not really sure what to report to them though to fix this?

**Comment by InfamousKnight** [comment]
New workaround: use antimicro to map gamepad buttons. Its an outside program, but it works.

**Comment by InfamousKnight** [comment]
Sorry for flooding this thread, but updating opentk might fix this.

**Comment by YoshiRulz** [comment]
@InfamousKnight It should be a lot less fragile now, and you should be able to plug in a gamepad at any time. Let me know if it still drops out. It may be machine- or distro- specific.

**Comment by InfamousKnight** [comment]
Running ubuntu 20.04 on latest commit and it works like a charm! Restarting it doesnt break anything, I can unplug the controller whenever and its pretty stable now.

This one was really bothering me. Thanks!
