### ISSUE TITLE
Separate Global tab in PathConfig and/or replace tabs with another control

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#2435]
This has gotten out of hand. Two lines or six, it's a nightmare either way.
![Screenshot_20201001_075608](https://user-images.githubusercontent.com/13409956/94744043-b7a8e900-03bb-11eb-8489-3356e66739f5.png)
![Screenshot_20201001_075730](https://user-images.githubusercontent.com/13409956/94744094-c7c0c880-03bb-11eb-8e1b-b2570efcdf0a.png)

**Comment by nattthebear** [comment]
MORE TABS
