### ISSUE TITLE
Incorrect Mapping with 8BitDo M30 Controller

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2439]
The left and the right inputs on the d-pad are not mapping properly in the Config_> Controllers menu .  When pressing the left and right they do not map to anything.  Changing the input method in the Config->Customize from OpenTK to DirectInput+XInput did not work either.  One thing I did notice is that Bizhawk is treating the Left Bumper on the controller very strangely.   When I tried to map the L bumper it mapped the DOWN press of the L bumper as the X+, then the release of the L bumper as X- for the next option on the controller mapping.

Instead of using some kind of workaround like JoyToKey I would like to be able to map this properly please.

Product Link
https://www.8bitdo.com/m30/

**Comment by zeromus** [comment]
We don't have special logic for individual controllers. If your controller is reporting unusable nonsense, there's nothing we can do about it. It's not BIZHAWK treating the bumper strangely, it's the controller reporting the bumper strangely. Set it to xinput mode.

**Comment by ShinobiWannabe** [comment]
As I stated in the text the XInput option had not worked fyi.

**Comment by zeromus** [comment]
Change your CONTROLLER to xinput mode.

**Comment by ShinobiWannabe** [comment]
Ok looked at this a little more carefully.  Turns out I had just needed to restart bizhawk. I had missed that note to restart. Then it maps properly.
