### ISSUE TITLE
Problems with N64hawk and registered functions in Lua

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#244]
```
There are some problems using registered functions with n64hawk. Here is a 
sample broken script which will cause bizhawk to deadlock:


function print_input()
  console.log(joypad.get())
end

event.oninputpoll(print_input)


This similar script works as expected:


while true do
  console.log(joypad.get())

  emu.frameadvance()
end


If there is an error in a registered function it can crash bizhawk instead of 
just being displayed in the lua console. Here is a sample script where "handle" 
is not defined causing a lua error and resulting in bizhawk crashing:


function print_input()
  handle:write(0)
end

event.onframeend(print_input)


Here is a similar script with the same problem, but this time the error message 
is displayed on the console:


while true do
  handle:write(0)

  emu.frameadvance()
end
```

Original issue reported on code.google.com by `pjga...@gmail.com` on 11 Aug 2014 at 10:53

**Comment by YoshiRulz** [comment]
Reproducible on BizHawk 2.3, OS: Win10 Home 1709. The following script still causes the program to freeze when loaded:
```lua
function a_func() console.log("hi wrld") end
event.oninputpoll(a_func)
```
However, when this script with a syntax error is loaded, it prints errors to the console as expected and **does not** crash:
```lua
function a_func() syntax:error() end
event.onframeend(a_func)
```
The other scripts still work as expected, and error upon load, respectively.

**Comment by zeromus** [comment]
I should look into this.

**Comment by zeromus** [comment]
Can't repro. Probably only causes program to "freeze" because the game polls 100000000000000 times and your script is duly appending 100000000000000  messages to the console log. I just ran your script in megaman with no problems.
