### ISSUE TITLE
PS bk2 from 2.4 doesn't sync on 2.5.2

### ISSUE THREAD

**Issue by Samtastic1** [TASVideos/BizHawk#2442]
### Summary
I'm still getting frequent desyncs on recording PSX inputs on version 2.5.2. 

### Repro

1. Open Abe's Exoddus PSX Rom. 
2. Record inputs. 
3. When going back in a movie file, the game will desync. Here's a movie file that I been working on: https://1drv.ms/u/s!AjWXiOXUkSgPwcQazNlePszexlXJZg?e=keOo4K - it desyncs around frame 1127 after re-syncing it previously.

**Comment by InfamousKnight** [comment]
Does it work in bizhawk 2.3.0? I'm seeing a submission of this on tasvideos using that version. Must be a regression somewhere.

**Comment by zeromus** [comment]
syncs fine for me out to frame 10,000

**Comment by Samtastic1** [comment]
Yes and 2.4

**Comment by Samtastic1** [comment]
What happens in 2.5 is I record input and it looks like it synced, but when
I go back to an earlier frame it desyncs and doesn't save my inputs where
in 2.4 it does.

**Comment by zeromus** [comment]
desyncing and not saving inputs sounds like entirely different things. if input isn't "saved" then of course it will desync because the input is not the same.

**Comment by Samtastic1** [comment]
Yeah I don't know why it does it in 2.5 but it doesn't do that in 2.4.

**Comment by YoshiRulz** [comment]
It might help if you were to record your screen and upload it to YouTube for us.

**Comment by Samtastic1** [comment]
I think I know why it might be causing a major desync - I'm using inputs
from a movie file that was created in an older version of PSXHawk but then
the inputs are exactly the same. I'll make a video when I get chance later
today. It would be nice to finish a new run on 2.5 but 2.4 seems more
reliable for me.

**Comment by Samtastic1** [comment]
I have made a video showing the problem.

It seems even if I save the movie from a save state later on in the movie
that shows the right input, I replay the movie and it desyncs right in
Tunnel 1.

https://www.youtube.com/watch?v=SEyX46Ub2Ug&feature=youtu.be&ab_channel=SamLocke

**Comment by zeromus** [comment]
Please rename this bug to "psx bk2 from 2.4 doesn't sync on 2.5.2" if that statement is true, so that I can close the bug as "working as designed".

**Comment by zeromus** [comment]
Old movies do not generally sync. In this case, in particular, the psx core was updated by more than a year's worth of backlogged upstream updates between 2.4 and 2.5.2. You will need to edit inputs by hand or use tastudio to repair your movie, but probably you should just stick to 2.4
