### ISSUE TITLE
[GBC] Bomberman Selection (Korea) is not playeble 

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2443]
Game can be open and can choose game from title screen. After that game gives error massage. Its in Korean so I don't know what it exactly says. In comparison I can play this game in mGBA.

**Comment by alyosha-tas** [comment]
Are you playing in GBC mode? This game is GBC only so my initial guess would be that the error says it's not compatible with GB.

**Comment by ozderya** [comment]
Yes, I tried to change Auto to GBC but still haven't worked. Though I believe it gives same error when I use GB mode. Emulator also gives unknown rom warning at left down side.

**Comment by CasualPokePlayer** [comment]
GB -> Multicart Compatibility -> True

If that setting isn't ticked the game will not work.

**Comment by nattthebear** [comment]
@CasualPokePlayer Thanks for providing a fix!

**Comment by alyosha-tas** [comment]
Oh I forgot about those multi carts, added hash check for GBHawk too.
