### ISSUE TITLE
Syncless recording only gets the last frame

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#2444]
Not sure if its linux exclusive, but when I tried Syncless recording which would put all the frames and audio in 1 folder which would be exported later, it only captures the last frame.

Tested on mgba and saturnus.

I'm only using that because I can't figure out how to use ffmpeg on linux..

**Comment by Color-Printer** [comment]
Getting this issue on windows 2.5.2 and 2.4.0 as well, with Gambette and QuickNES. It's producing a blank "0.png" and a not-blank "0.wav", which I assume is the actual sound output.

**Comment by zeromus** [comment]
syncless recording isn't really useful. the folks I made it for didn't even end up using it. it needs to be improved considerably. you should ignore it.

**Comment by alyosha-tas** [comment]
@InfamousKnight I fixed this so that it works, in a basic form, for me on Windows, please try dev build in linux

**Comment by InfamousKnight** [comment]
Tested linux build and it works!
