### ISSUE TITLE
SEHException from SlimDX.XInput on 2.5.2

### ISSUE THREAD

**Issue by klkk5469** [TASVideos/BizHawk#2447]
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at XInputGetState(UInt32 , _XINPUT_STATE* )
   at SlimDX.XInput.Controller.get_IsConnected()
   at BizHawk.Client.EmuHawk.GamePad360.Initialize()
   at BizHawk.Client.EmuHawk.DirectInputAdapter.FirstInitAll(IntPtr mainFormHandle)
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by YoshiRulz** [comment]
Did you unplug a gamepad while EmuHawk was loading? What kind of gamepad(s) would you have been using when the crash happened?

**Comment by klkk5469** [comment]
i use keyboard play.

**Comment by klkk5469** [comment]
i use windows 10 play

**Comment by klkk5469** [comment]
no, run the program, got installer an show me. Thank..

**Comment by YoshiRulz** [comment]
https://github.com/TASVideos/BizHawk-Prereqs/releases/tag/2.4.8_1

**Comment by klkk5469** [comment]
can use now

**Comment by klkk5469** [comment]
do u have new firmware for ver 2.5.2?

**Comment by YoshiRulz** [comment]
The [changelog](http://tasvideos.org/Bizhawk/ReleaseHistory.html) says:
> Minor GB/C and PCFX firmware detection revisions (#2430)

You shouldn't have any problem if you just copy the `/Firmware` folder from an older version.

Did running the prereq. installer stop the crashing?

**Comment by klkk5469** [comment]
same of the game cannot play

**Comment by klkk5469** [comment]
![image](https://user-images.githubusercontent.com/72747322/96072698-6dedf180-0ed7-11eb-8963-2cb38d3ada64.png)

how to set in 2.5.2

**Comment by klkk5469** [comment]
![image](https://user-images.githubusercontent.com/72747322/96072757-8eb64700-0ed7-11eb-8ebd-fb38331b3dec.png)

**Comment by zeromus** [comment]
whatever you're yammering about is a different issue. look online for other firmwares or use the bizhawk firmware manager to see what firmware managers are installed. only you know what version you used to use and what firmware files you have

**Comment by Sappharad** [comment]
The game in question requires the 4MB Saturn RAM cart expansion to run. That's not a firmware issue, user needs to enable that add-on if BizHawk supports it.

**Comment by klkk5469** [comment]
how to enable that add-on?

**Comment by zeromus** [comment]
want to change a saturn setting? try saturn > settings.
