### ISSUE TITLE
GBHawk: Soreyuke! Speedy Gonzales desynchronization

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2452]
Recording an input movie of Soreyuke! Speedy Gonzales (Japanese version of Speedy Gonzales) results in a desynch.
[Soreyuke! Speedy Gonzales (Japan).zip](https://github.com/TASVideos/BizHawk/files/5377691/Soreyuke.Speedy.Gonzales.Japan.zip)

**Comment by alyosha-tas** [comment]
Another one? Man I looked over savestates multiple times but didn't see anything wrong, very strange. I'll try to prioritize this once the current round of hardware testing is complete. Hopefully in the next couple of weeks. Thanks for the report.

**Comment by alyosha-tas** [comment]
As autofire was used around frame 5675 in the .bk2, I'm going to close this one.

@Reinc01 please retest in 2.6.2
