### ISSUE TITLE
Option to carry inputs from one ROM to another (BizHawk)

### ISSUE THREAD

**Issue by brossentia** [TASVideos/BizHawk#2453]
Hello! I'm working on a Lua script that will load a different ROM at random times, giving players an additional challenge. However, input gets lost between loads. Is there any way to have input carry over in the same emulator? Or when loading a new emulator? If not, I'd love to see that happen (especially with up/down/left/right; others aren't as important).

If there's currently a way to do that, please let me know; I'm fairly new to scripting. Thanks!

**Comment by YoshiRulz** [comment]
By "input gets lost between loads" do you mean (host) inputs that are *held* become unheld when loading a rom?

**Comment by brossentia** [comment]
YoshiRulz, yes, that's correct. Held inputs from one joypad do not carry over when a ROM is loaded. I haven't been able to find a good work around, either.
