### ISSUE TITLE
Pressing slash or backslash crashes the emulator

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#2458]
Title says everything. Pressing / or \ causes the emulator to close abruptly. It's only those two keys specifically.
Demonstration video: https://i.imgur.com/6oWfOta.mp4

Note that there's no shortcut key associated with "Exit Program".

**Comment by nattthebear** [comment]
@YoshiRulz Is there some way we can permanently eliminate this entire class of errors?  We shouldn't be needing to play whack-a-mole with various keyboard layouts.  The low level APIs presumably give us a number or a string or something, and we should just accept and allow all values.  Then, in the worst case scenario an unfamiliar layout would simply not match our default settings; but the user could still map and use the keys.

**Comment by YoshiRulz** [comment]
I'm pretty sure I've fixed this. @Sonia-7 please try a recent dev build.

**Comment by Sonia-7** [comment]
@YoshiRulz Just tested the latest one (0.0.0.5580). Backslash no longer crashes, but slash still does.

**Comment by zeromus** [comment]
Can you please either make it fail-safe by ignoring unknown keys or map them all? Obviously all the keyboards in the world have more keys than your keyboard has so if youre gonna map them all, youre going to need to do ones you can't test, so you may as well do them all if youre not going to ignore unknown ones. The key constants wouldnt exist if there werent keyboards that used them.

**Comment by YoshiRulz** [comment]
@Sonia-7 Could you please try 370996875, making sure the input settings (`Config` > `Customize...` > `General`) look like this?
![screencap](https://user-images.githubusercontent.com/13409956/96653719-0de6c780-137d-11eb-8b80-61743bbd00f3.png)

**Comment by Sonia-7** [comment]
@YoshiRulz Everything seems fine now, so I'll go ahead and close this.

**Comment by YoshiRulz** [comment]
Do you mean with that build, or with 2.5.2?

**Comment by Sonia-7** [comment]
With that build.

By the way, it's not crashing anymore even without checking that "Handle alternate keyboard layouts" checkbox.
