### ISSUE TITLE
ExternalTool GuiApi.DrawImage() Error

### ISSUE THREAD

**Issue by BigTheDave** [TASVideos/BizHawk#2461]
I've been having trouble making an External Tool that uses GuiApi.DrawImage and I've tracked the problem down to BizHawk.Client.Common being .Net 2.0, rather than .Net Core and should be fixed once it's properly moved over to .Net Core. But I figured I'd report it anyway since I can't seem to find anyone else with this specific issue.

Using the HelloWorld template as a base, and attempting to call GuiApi.DrawImage (either the Image or String version) causes the following error: 

`The type 'Image' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

![image](https://user-images.githubusercontent.com/1863289/96793915-2a264b00-13f5-11eb-917e-b5247afa8e9b.png)

Including the .Net 2.0 version of System.Drawing.Common that BizHawk.Client.Common references changes the error. Instead complaining that System.Drawing.Image is defined in two places (which makes sense, naturally).

Like I said before, the fix is moving BizHawk.Client.Common over to .Net Core like the rest of the project.

Or, as an intermediate fix, splitting the overloaded function calls into two separate calls (like DrawImage and DrawImageFromFile) should prevent it complaining about System.Drawing.Image.

So far the rest of GuiApi works fine, it's just DrawImage that doesn't.

**Comment by YoshiRulz** [comment]
Nothing in EmuHawk is .NET Core yet, only .NET Standard 2.0 or .NET Framework 4.8. Add this to your project file:
https://github.com/TASVideos/BizHawk/blob/3709968757ee6beaec1e3b44e52250fed2183478/src/BizHawk.Bizware.BizwareGL/BizHawk.Bizware.BizwareGL.csproj#L11

**Comment by BigTheDave** [comment]
Okay, maybe I got confused about .net core, since 
`<!-- some NuGet packages aren't for Standard, and are only loaded at runtime because EmuHawk is still Framework. More work will be required to move to Core. -->` 
is in the BizHawk.client.core csproj file, but adding System.Drawing.Common causes the second half of the issue, where it complains that System.Drawing.Image is defined in two places (System.Drawing, and System.Drawing.Common)

This is definitely due to the discrepency between  .NET Standard 2.0 and .NET Framework 4.8 (the HelloWorld csproj is in .NET Framework 4.8)

**Comment by YoshiRulz** [comment]
I can use `DrawImage(Image,...)` with minimal changes to the repo:
```diff
diff --git a/ExternalToolProjects/HelloWorld/CustomMainForm.cs b/ExternalToolProjects/HelloWorld/CustomMainForm.cs
index 84839ff5b..b6fbbeb5c 100644
--- a/ExternalToolProjects/HelloWorld/CustomMainForm.cs
+++ b/ExternalToolProjects/HelloWorld/CustomMainForm.cs
@@ -1,4 +1,5 @@
 using System;
+using System.Drawing;
 using System.Windows.Forms;
 using System.IO;
 
@@ -23,6 +24,11 @@ namespace HelloWorld
                [RequiredService]
                private IMemoryDomains? _memoryDomains { get; set; }
 
+               [RequiredApi]
+               private IGuiApi? _maybeGuiAPI { get; set; }
+
+               private IGuiApi _guiAPI => _maybeGuiAPI ?? throw new NullReferenceException();
+
                private WatchList? _watches;
 
                private WatchList Watches
@@ -96,6 +102,11 @@ namespace HelloWorld
                        {
                                return;
                        }
+                       static Image PNGFromBase64(string base64Str) => Image.FromStream(new MemoryStream(Convert.FromBase64String(base64Str)), true); // MemoryStream.Dispose() is a no-op
+                       var img = PNGFromBase64("iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAC3ElEQVRYhb3W3UtTYRwH8P0fx+TYi2OmNlOYDpuWm2eeeVE3Ed11caAMckUvGCSEFF0kHFu1jIao4AsuC2koydS5zc2iq6QIuulCEhTrqHPv+3blcp3t7DnurAPP1Xme5/vheX7Pc45KJfPBx3ZINbnzKRJaVMxBwwtG7J9k22PGN2czPo8asDJqwKrLiMSypXiQvUERPwv7zePgGErUbp2n8XW8SXnE/gGxAIvxHi0CDj3WZkwILbZBWDDjx9QZuHrr8EUmgAhR6J4XBJAaGF1isTJmwMZsa9b38aAFQYcew93VeNKpQd81DRxdlfC+qMemm8mPyCe3WTXgGAqdZ0ux6RYjVl1GcAyFOxfKwDEUHneo8fJ2JTosh8AxFL5PnpZGSIVvzLZmFKCvvyHnKvVeVYNjKFyxlGD9vQkRP4tPg40Q5vOsghTg1xyTAQg49ERQj72erBZIime4uxocQ6HrYhm2PeasfX7PZ0KDOaAiBAkguWzBqqsFYV+bZD/ngxpwDIX7l44i5JXuW7Sjtz7biugSS34klQaQNmJA0p99z/8LIO5ugcDT2HFUIhXMv6yKAxILJgg8DYGnEXbqsOlmMN6jxdPrFbBZNRi4WwVvf0PWy0mZLfjQngZs2cvxc9oIm1WDoXvVeP2wBs9vVOByWwk4hsKbRycRD5J/ponuglSATQMEns7aJ+JnEXilh/VcKdamjfLDpQDRqca/ANvh3IXqMyM204zwhA5hpw7I88NCBIhNN0HoK8uogXRteEyIvjuF3ZFabNnVGask8DQSc9IrIQL8i4jNNIkmDU/oEBrSYst2RPQuXSfPjmF3rA4piRXIGr4fkPSZJUMyAu3l2B2pRdRlQHKR7CTkBOwhIpMNROECT2PbrkYqQH4/SIbvPTsDVcQAgaeR9DLKhatUKpWc8NCwVtnwgyBSS4Sf3WIAdgZPKBssFxB5K/7rKShYLkKxMLkQpeb+AwvJdcwGKjUvAAAAAElFTkSuQmCC");
+                       _guiAPI.DrawNew("emu");
+                       _guiAPI.DrawImage(img, 0, 0);
+                       _guiAPI.DrawFinish();
                        Watches.UpdateValues(GlobalWin.Config.RamWatchDefinePrevious);
                        label_Watch1.Text = $"First watch ({Watches[0].AddressString}) current value: {Watches[0].ValueString}";
                        label_Watch2.Text = $"Second watch ({Watches[1].AddressString}) current value: {Watches[1].ValueString}";
diff --git a/ExternalToolProjects/HelloWorld/HelloWorld.csproj b/ExternalToolProjects/HelloWorld/HelloWorld.csproj
index 0a31dd445..9983f47c8 100644
--- a/ExternalToolProjects/HelloWorld/HelloWorld.csproj
+++ b/ExternalToolProjects/HelloWorld/HelloWorld.csproj
@@ -2,6 +2,7 @@
        <Import Project="$(ProjectDir)../ExtToolCommon.props" />
        <Import Project="$(ProjectDir)../NET48ExternalToolForm.targets" />
        <ItemGroup>
+               <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
                <EmbeddedResource Include="icon_Hello.ico" />
        </ItemGroup>
 </Project>
```

**Comment by BigTheDave** [comment]
Thanks for the help, I must have been copying it into the wrong part of the project or something cause that started working and I have no idea why. Great success.
