### ISSUE TITLE
[FDS] Kiki KaiKai: Dotou Hen doesn't work

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2462]
It did not continue after start screen. I believe it gives some kind of warning but don't know what it says.

**Comment by Spikestuff** [comment]
False error. User doesn't know how to flip sides.
![Insert Side B](https://user-images.githubusercontent.com/12412764/97006059-009f2800-158b-11eb-862a-462e6e2d309a.png)

NES > FDS Controls > Eject Disk
NES > FDS Controls > Insert Disk 1
![Game Running](https://user-images.githubusercontent.com/12412764/97006061-0137be80-158b-11eb-862d-7ff2c1e1171f.png)

**Comment by nattthebear** [comment]
Thanks @Spikestuff
