### ISSUE TITLE
Add config option for rewinds every fixed number of frames.

### ISSUE THREAD

**Issue by dacin21** [TASVideos/BizHawk#2463]
The new rewind system doesn't allow you to have rewinds every fixed number of frames, say every 2 frames. Instead, you have to set a "Desired frame length" and the rewind length is dynamically calculated based on the current average state size. As the average state size changes over time, there is no way of avoiding the occasional 1-frame rewind or 3-frame rewind.

It would be nice to have an additional config option that allows you to have rewinds every x frames (as in the pre 2.5 rewind system) instead of setting a "Desired frame length". Having rewinds every x frames is very useful for tasing without TASudio, as it allows you to predict exactly how many frames you go back. For example, after pressing rewind once, pressing rewind 3 more times always moves you back 6 frames. (With the current system, you might go back 5 or 7 frames, which is very awkward.)

**Comment by Sonia-7** [comment]
Agreed with this. That's one feature I miss from the old rewind system. Setting a fixed number like 2 frames instead of 1 for example would also allow rewinding for a longer Est. time.

**Comment by zeromus** [comment]
I agree, rewind should be defined by intervals and it should be estimating how long that is for the current game; if you think it's too short, you can increase the buffer size or decrease the intervals. With a big enough default memory size, there's not even a reason for anyone to change these options other than to change the rewind SPEED which is critical for gameplay in some cases.

**Comment by dacin21** [comment]
I do see that setting a "Target Frame Length" makes sense in a TASudio setting, but my point is that outside of TASudio, setting a rewind length is preferable in most if not all cases. I'm specifically talking about adding a config option to `Config > Rewind & States > RewindSettings` and those settings are AFAIK ignored by TASudio. My bad for not specifying this; at the time I didn't know about TASudio's "Savestate History" settings. I'm not talking about changing those.

I've already explained why setting a fixed rewind length is desirable when TASing without TASudio. For other cases, such as glitch hunting, analysing glitches or even casual play, setting a rewind length translates to a certain rewind speed, which really is the quantity you care about. Setting the rewind length to 5 frames is way more intuitive than setting the "Desired Frame Length" to 40000 and having to change that if you decide to increase the buffer size. You typically won't run into issues with exhausting the rewind buffer, and if you do, you can always increase the buffer size.

TASudio supporting arbitrary rewind lengths sounds great. Unfortunately, it seems to only support going back a single frame at a time (I would love to be proven wrong on this). This makes it cumbersome to use, as it requires me to mash the rewind button a lot. Compared to 2-frame rewinds, you have to press rewind twice as many times and this gets even worse when comparing with 3-frame or 5-frame rewinds.

**Comment by YoshiRulz** [comment]
You can rewind as far back as you want with single-frame precision in TAStudio, that's kind of the point. Click in the cell to the left of a frame index (where the current frame marker is) to jump to that frame.
