### ISSUE TITLE
GBHawk: Teenage Mutant Hero Turtles: Fall of the Foot Clan

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2466]
I recorded a playthrough of Teenage Mutant Hero Turtles: Fall of the Foot Clan (European version of Teenage Mutant Ninja Turtles: Fall of the Foot Clan), but it desynchs when I try to play the input movie.
[Teenage Mutant Hero Turtles - Fall of the Foot Clan (Europe).zip](https://github.com/TASVideos/BizHawk/files/5475158/Teenage.Mutant.Hero.Turtles.-.Fall.of.the.Foot.Clan.Europe.zip)

**Comment by alyosha-tas** [comment]
Thanks for the continued reporting, this is the next thing I am going to work on.

**Comment by alyosha-tas** [comment]
I tried to reproduce desyncs here with no success. 

I have looked over GBHawk's savestates several times and nothing looks wrong.

@Reinc01 I suggest that whenever you make a movie you use a unique name, so as to avoid the possibility of state errors. If you still get a desync I can look into this again.

For now closing as CNR.

**Comment by Reinc01** [comment]
Doesn't every game have a unique name already, meaning the movie name will be unique? When I record multiple movies of the same game, I do give each movie a unique name.

**Comment by alyosha-tas** [comment]
Well, the presumption is that something about your movie making process is hitting a bug in BizHawk, and the only thing we can do now is narrow down possibilities of what it might be.
