### ISSUE TITLE
X-position analog stick inputs for N64 broken.

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#2467]
I learned about the Stick having issues inputting X position while trying to TAS a 3D game for once.  Virtual Pad was being really strange with recording X inputs into TAStudio, and I figured out it's because it's completely broken in 2.5.2, and it may have started back during the 2.5 version, because it isnt an issue in 2.4.2

You can still manually put in X-position in TAStudio, but the actual controller config and Virtual Pad inputs do not work.

**Comment by alyosha-tas** [comment]
Everything seems to be working for me now, this was a general bug in virtual pad not limited to N64. 

But I didn't test everything too extensively, so feel free to reopen if there is something more specific to look at.
