### ISSUE TITLE
Input movie desynchronizations

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2470]
I recently recorded playthroughs of the following games:

Captain America and the Avengers (SNES)
Contra Force (NES)
Yie Ar Kung Fu (NES)
Disney's Darkwing Duck (NES)
Urban Champion (NES)
S.C.A.T.: Special Cybernetic Attack Team (NES)
Mighty Final Fight (NES)
Bad Dudes (NES)

All these input movies suffer from desynchronization.
[desynch.zip](https://github.com/TASVideos/BizHawk/files/5499203/desynch.zip)

**Comment by YoshiRulz** [comment]
see also #2469

**Comment by zeromus** [comment]
can you record a screencap video of yourself desyncing a small NES game so we can see what you're doing to make bizhawk mess up? make sure youve turned on all the hud messages (the state loading ones, frame counter, input display) so that we can trace what you're doing.

**Comment by nattthebear** [comment]
Possibly related to https://github.com/TASVideos/BizHawk/issues/2452, https://github.com/TASVideos/BizHawk/issues/2388

**Comment by Reinc01** [comment]
Update. These games desynch in NesHawk, too:

Urban Champion (NES)
S.C.A.T.: Special Cybernetic Attack Team (NES)
Mighty Final Fight (NES)
Bad Dudes (NES)

The first message of this issue was updated accordingly.

**Comment by Reinc01** [comment]
Life Force (NESHawk), too.
[Life Force.zip](https://github.com/TASVideos/BizHawk/files/5504476/Life.Force.zip)

**Comment by zeromus** [comment]
Type fewer words about your continued failed tases and more words about how you're acknowledging the instructions I provided and planning to follow them.

**Comment by Reinc01** [comment]
Did anyone test any of the games that I reported to see that desynchronizations are not regularily occuring? If they **are** regular, then my further input is not required. I didn't record these games in a manner that's different from how I usually record.

 It's not like my movies desynch only on a full moon when Bizhawk is launched on a bootleg Macbook made in a specific Chinese town, or something like that.

**Comment by zeromus** [comment]
A lot of people make a lot of tases on bizhawk. We would have heard more chatter if there was something so thoroughly wrecked on MULTIPLE cores.  I just made a tas of 1.25 levels of life force using rewind and states both and had no problem.

**Comment by Reinc01** [comment]
For me, Life Force in particular desynched on the second half of level 2. Others desynched in the very first level.

**Comment by zeromus** [comment]
disable rewind and try again, maybe something happens when the buffer gets full

**Comment by Reinc01** [comment]
Will do. But I have to point out that not every game desynchs. In recent days, I recorded 18 games in total, and 8 of them did not desynch. Same with my earlier Game Boy input movies. Some worked, and some did not.

**Comment by Reinc01** [comment]
Tried recording Life Force (NES) with rewind disabled. Desynchronizes at the beginning of the first level.

**Comment by alyosha-tas** [comment]
@Reinc01 are you using a fresh dev build of BizHawk? If not, maybe it's possible you have some RAM or other addresses frozen or something and forgot about them?

**Comment by Reinc01** [comment]
I'm using BizHawk-2.5.2 release version. I avoid using dev builds in order to see fewer bugs.



> t's possible you have some RAM or other addresses frozen or something and forgot about them?

I don't even know what that is, so probably not?

**Comment by Reinc01** [comment]
The hard drive where I keep Bizhawk have died about three weeks ago. Could all these desynchronizations have happened because of damaged sectors in the hard drive, or some other issue related to hard drive failure? Although I did not have any issues with copying these movies later (no "could not read from disk" error messages).

**Comment by nattthebear** [comment]
Well, can you reproduce (IE, make a desynchronizing movie) now?

**Comment by zeromus** [comment]
It's impossible for the hard drive to destroy the tas's. The zips would show as corrupted, and if they didn't, bizhawk would crash loading the corrupted tas. The odds of having multiple desyncing bizhawk tas's from hard disk corruption are lower than the odds of the hard disk corruption creating a directory with an entire U2 mp3 album.

**Comment by Reinc01** [comment]
Another desynchronization, this time in Octoshock core. It seems to only desynchronize at certain sections of the movie, but playing the movie in read-only mode does not always show the movie desynchronizing, so you might need to look at the movie multiple times.

Here is a short movie and two save-states. In one case, the desynchronization is starting noticable starting from the moment where player character does not pick up loot from enemies, and in the other case, player character talks to an NPC which he is not supposed to talk to.

[Movie and saves.zip](https://github.com/TASVideos/BizHawk/files/5826197/Movie.and.saves.zip)

**Comment by alyosha-tas** [comment]
The movies in the op use autofire, so once again I am closing this unless it is repro'd in 2.6.2or later.
