### ISSUE TITLE
[GBC] Konami GB Collection Vol. 4 - Antarctic Adventure can't playeble

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2472]
Game can be open and even race map can be seen but it could not able to start race.
All other volumes and games seem good tho.

**Comment by YoshiRulz** [comment]
Which core were you using? Could you click the rom status indicator and copy the hash for us?

**Comment by ozderya** [comment]
I cheeked all core and I can only play it in Gambatte. Other cores freeze just before race. 

If I'm not mistaken this is rom status values:
Konami GB Collection Vol.4 (Europe)
SHA1:4C0C9E9CBA36BFE5588E2A2DC799D207AFD1321E
MD5:F3414D53473E2CC43347774CC5F40495

**Comment by alyosha-tas** [comment]
Thanks for the report, I'll close this and add it to the existing GBHawk issue.
