### ISSUE TITLE
Bizhawk 2.5.2 can't accept PSX rom converted from Discohawk

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2478]
1) Obtain the **Thousand Arms Undub** iso
2) Convert it using DiscoHawk on version 2.5.2
3) Try to run the resulting ".ccd" file

Result:
```
A core accepted the rom, but threw an exception while loading it:
System.InvalidOperationException: No core was found to try on the game
[...etc]
```
See attached image for full exception
![romfail](https://user-images.githubusercontent.com/8139496/99041560-01026180-2540-11eb-8447-a1530645c7f2.png)

**Comment by zeromus** [comment]
Because the rom input to discohawk was garbage. As per normal from romhackers. It's delivered as a ".iso" but it isn't, it is a mode 2 .bin without it's associated .cue.
