### ISSUE TITLE
BSNES debug disassembler scroll bar broken

### ISSUE THREAD

**Issue by darkgob** [TASVideos/BizHawk#2480]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
When scrolling up in the Debugger Disassembler on BSNES core (whether with the scroll wheel or clicking up on the scroll bar), the list actually scrolls down to the next address.  Clicking on the scroll track itself above the scroll bar and Page Up both still work as expected, although dragging the scroll bar up does not.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open Debugger with BSNES Core.
2. Scroll down in the Disassembly view a little bit.
3. Attempt to scroll up with the mouse wheel, or by clicking up on the scrollbar, or by dragging the scroll bar.

### Code trace
DisassemblerView_Scroll in GenericDebugger.Disassembler.cs (line 145) seems to be the culprit.  The following trace was tested using the mouse wheel to scroll.
1. When you scroll down for the first time, InputRoll.IncrementScrollBar increments the value of the scroll bar from 0 to 13 (SmallChange=13).
2. DisassemblerView_Scroll ends up being called after this, sees that scrollBar.Value is > 0, and sets scrollBar.Value to the hardcoded value of 14 for some reason.
3. When you then scroll up, InputRoll.IncrementScrollBar decrements the value of the scroll bar from 14 to 1 (SmallChange=13).
4.  DisassemblerView_Scroll ends up being called after this, sees that scrollBar.Value is > 0, and once again sets scrollBar.Value to the hardcoded value of 14.

Looks like DisassemblerView_Scroll was changed to do this on [10/19/19](https://github.com/TASVideos/BizHawk/commit/9100526a0ca5cad4167d8d62be3046103487c759#diff-a182ab3eaf3c9abe819bd9f3b75a167883e240b68cd52347d481f302b15174aeR162).

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.2; Win10 Pro 1909; AMD/AMD

Bug confirmed to not exist:
- BizHawk 2.3.0; Win10 Pro 1909; AMD/AMD

**Comment by YoshiRulz** [comment]
Based on where the offending code is, this isn't BSNES-specific. In fact I noticed something similar with mGBA around the time of #2417.

---

You've done a lot of the work for us here, so thanks for that, and congrats on an amazing first issue!

**Comment by alyosha-tas** [comment]
This was pretty badly broken.

I fixed it to work in a reasonable way, I don't think it ever worked as that code intended.

Now you can use [ and ]  to scroll the start address of the disassembly. Use shift to go 3x as fast.
(I also made a note in the window that this is how it works.)

The scroll bar now just scrolls through the different addresses already disassembled, it won't change what's being disassembled.

@darkgob please test in master

**Comment by darkgob** [comment]
@alyosha-tas Seems to work as expected again.

**Comment by nattthebear** [comment]
For reference, this was fc92d3c63e49ab99a0fc9c7999377b83888a9055
