### ISSUE TITLE
TAStudio: Error when navigating to frame 0 when movie starts from SRAM

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2481]
When you navigate to frame 0 on an SRAM anchored movie in TAStudio, the movie will play forward from then on with clear / default SRAM. If you don't alter the greenzone, and then select  a different frame, it will load a state with the correct SRAM.

It looks like the state for frame 0 is being created before the SRAM is applied.

**Comment by nattthebear** [comment]
Possibly related to or duplicate of https://github.com/TASVideos/BizHawk/issues/2388

**Comment by alyosha-tas** [comment]
Oh, seems it is the same issue, I was using both gambatte and GBHawk for testing, so I'll close this and post some comments there.
