### ISSUE TITLE
Seeking assistance with mupen integration into non-Bizhawk frontend

### ISSUE THREAD

**Issue by SpiceyWolf** [TASVideos/BizHawk#2483]
Hi, sorry to bug you here, I dont exactly know what other way to reach out. I'm writing my own 'frontend' in C# for mupen64plus (n64) and have gotten pretty far -> Though I'm encountering an issue ONLY with attaching plugins and I know you guys have obviously gotten that working. I've attempted to reference you're guys' work to get this to work but had no luck thus I'm not sure if its the method I'm using to load the library or something else.

Thus my issue ends up being (while mimic'ing the cli frontend) when I go to connect plugins, If i try to hook them in any order that has video not first, itll fail and report none of the plugins are loaded etc trying to boot and fail, or if I put the video first, it hangs for about 30 seconds then returns with no error. Do you guys have any familiarity with this problem and what steps I may specificly be missing or doing wrong?

Again, sorry to reach out here for a selfish question, I just don't know who else to turn to to find any success with this problem.

**Comment by zeromus** [comment]
if the plugin is malfunctioning, then debug the plugin. I hope you're building it from sources.

**Comment by SpiceyWolf** [comment]
I did build all the mupen binaries from source, also ran the standard frontend-cli that the mupen repo makes WITH the binaries i made .. they load fine so its just something im doing wrong in particular or with .net cores library loader x.x im working off of arch linux so i cant rule out it may be a bug with .net but i didnt have any other ideas cause i cant seem to find any steps im missing. Im willing to drop a repo if anyone would like to see the code i have.

**Comment by zeromus** [comment]
doesnt change my advice. debug the plugin. it hangs for 30 seconds when you call an exported dll symbol from c#? then step into the exported dll symbol from c# and find out why.
I can tell you bizhawk runs mupen in another thread for some reason I can't quite remember. 
```
		private void StartThreadLoop()
		{
			var thread = new Thread(ThreadLoop) { IsBackground = true };
			thread.Start(); // will this solve the hanging process problem?
		}
```

**Comment by SpiceyWolf** [comment]
Ill try what i can when i get home, but to clarify its not necessarily calling exported symbol causing the problem, its passing a not null int ptr (generated from trying to load the plugin dll) to mupens attachplugin func... If i pass a null to it it just says plugin fail and doesnt break/hang

**Comment by zeromus** [comment]
If you're not calling an exported function then youre not using mupen and mupen isn't hanging

**Comment by SpiceyWolf** [comment]
Im confused... I am calling a function in mupen... Calling that function isnt broken i can invoke it and get a response... Its only passing what SHOULD be valid data thats a problem, if i pass null instead it functions just fine -> but passing null doesnt make mupen actually use a plugin

**Comment by SpiceyWolf** [comment]
Thats why i made the assumption im not doing something right to actually load the plugins or something about c# in .net isnt loading the actual video plugin or otherwise properly (not returning a valid intptr that mupen can interface with)

**Comment by zeromus** [comment]
right, you pass a value that makes it do something and it malfunctions while doing it. debug it doing it.

**Comment by SpiceyWolf** [comment]
Aside putting print statements like a madman is there a better way to DO debugging between a c and c# app?

**Comment by zeromus** [comment]
"enable native code debugging"

**Comment by SpiceyWolf** [comment]
Oof ill look into how thats done when im home

**Comment by SpiceyWolf** [comment]
Couldnt figure out a way to do the enable native code on linux... im using rider >.> Anyway, went printf happy in mupen... it SEEMS to pass connecting the plugin, its on calling plugin start that it poops the bed. Trying to explore further why that is.

**Comment by SpiceyWolf** [comment]
I was able to figure it out :P stuff works now. Thanks for the time you spent, found i missed an extra step of calling pluginstartup when i loaded plugins xD
