### ISSUE TITLE
Hang when loading Saturn .cue without firmware

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#2487]
Does not affect `.ccd`.

Initially reported by @arukAdo-tas as a regression from 2.5.2, but I was able to repro on 2.5, 2.5.2, and 2.5.3 dev at 0093c16d7. On 2.4.2 the missing firmware prompt came up immediately, as expected. On 2.3.2, EmuHawk froze for a bit but eventually showed the prompt.

**Comment by nattthebear** [comment]
Got a stacktrace?

**Comment by YoshiRulz** [comment]
VS breaks at the exception thrown here:
https://github.com/TASVideos/BizHawk/blob/0093c16d799030edbfaaf1a51bc6c512626ab26f/src/BizHawk.Client.Common/CoreFileProvider.cs#L44
If I hit continue, it does give me this:
```
Managed Debugging Assistant 'FatalExecutionEngineError' 
  Message=Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0xed7e4246, on thread 0x168c. The error code is 0x80131506. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'
```

**Comment by nattthebear** [comment]
Investigating this one right now.

> Does not affect .ccd.

Are you certain of this?  What happens when you try to load a ccd with no firmwares?

**Comment by YoshiRulz** [comment]
IIRC the missing firmware prompt is shown as expected. I failed to repro just now, whether that's because the crash only happens on Windows or because it was fixed with the recent update I'm not sure.

**Comment by nattthebear** [comment]
The crash I'm seeing is by its nature Windows only, so that fits.
