### ISSUE TITLE
GB layers not toggling

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#2491]
GameBoy layers are not being toggled properly.
This is a feature in Gambatte core that used to work up to version 2.4, but since BizHawk 2.4.1 it's not working: both hotkeys and options under GB > Settings > BG|OBJ|WIN do nothing (hotkeys only display the layer toggle message, but layer rendering doesn't update).
Maybe it's due the big overhaul on this update ("Many updates ported from upstream Gambatte through Gambatte-Speedrun [...]").

**Comment by CasualPokePlayer** [comment]
This probably should be turned into a Sync Setting if fixed; this setting is not deterministic and can't be changed on the fly without sync issues.

**Comment by YoshiRulz** [comment]
Can someone bisect for this? (Or just check whichever the Gambatte commit was, and the one before that.) 2.4.1 should be far enough back that you only have to change `/global.json` once.

**Comment by CasualPokePlayer** [comment]
https://github.com/TASVideos/BizHawk/blob/d4f42d9f32026bd70a47ff40805f5fb9425af579/libgambatte/src/video/ppu.cpp
https://github.com/TASVideos/BizHawk/blob/23c1c74030e320af86e3ff8e65b2a3d85de4c778/libgambatte/src/video/ppu.cpp

Changes between these commits caused the issue, notice all mentions of layersMask is gone.
