### ISSUE TITLE
Controller inputs not being detected

### ISSUE THREAD

**Issue by BlackLotus9029** [TASVideos/BizHawk#2499]
I started to use EmuHawk when it was in 2.3. Everything was working fine, I was using my Xbox One controller to substitute for the N64 controller which worked great. I stopped playing till now, but now it doesn't detect my inputs but it detects if there's a controller there.
I’ve even updated to 2.5.2.

What can I do to fix this?

**Comment by InfamousKnight** [comment]
Is this happening on windows or Linux?

I'm having the same problem on Linux and found a workaround that no longer works on interim but might work on 2 5.2 still.

**Comment by BlackLotus9029** [comment]
It’s on Windows. I forgot to specify

**Comment by InfamousKnight** [comment]
The workaround is this:
Open bizhawk
Plug controller in
Open the hotkeys window and attempt to change a key(it should fail, and this is a necessary step)
Close out of the window
Close bizhawk
Reopen bizhawk and now it should work.

Those are the steps needed for "stable" release. In the interim its completely broke.

**Comment by YoshiRulz** [comment]
> I stopped playing till now, but now it doesn't detect my inputs but it detects if there's a controller there.

Was this just on 2.5.2 or did you try 2.3 again first? And what do you mean by "detects if there's a controller there"? That's not something EmuHawk exposes to the user.

---

Linux-specific issue is #2429.

**Comment by BlackLotus9029** [comment]
I tried 2.3 first. And EmuHawk didn't say, the game said upon getting to the main screen ’No controller detected’ when I changed to a different controller using controller settings. Which now that I think about it didn't do anything nor would’ve helped.
My input method is set to: `DirectInput+XInput`

**Comment by YoshiRulz** [comment]
I'm not sure what I was expecting, but I couldn't repro. Try the other input method I guess?

**Comment by BlackLotus9029** [comment]
Tried it, sadly It doesn't work. Could it be perhaps of an existing Xbox application interfering with the Xbox one controls?

**Comment by YoshiRulz** [comment]
Probably fixed with e71506ac6.
