### ISSUE TITLE
emu.getdisplaytype() not returning PAL in BSNES

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#2503]
The lua function `emu.getdisplaytype()` is not returning the correct region on BSNES core (didn't test on other consoles).
By using the GameInfo.lua script that comes with BizHawk, you get the following log for a clearly PAL version of Super Mario World (the Europe one):
```
Game Info library test
Rom Name: Super Mario World (Europe)
Rom Hash: 56265120A74B55260FF7CACC00DA1F21CBCB64F4
Display Type: NTSC
In Database?: true
Rom Status: GoodDump
Is Status Bad?: false
Board Type: 
Game Options: 
```
This was tested in several releases, it's wrong since version 2.0 (versions from BizHawk 32bit like 1.13.2 are correct). 

#### Other info
The emu displays 50fps correctly when "Display fps" is toggled.
The Snes9x core gets the correct region on every version tested.

**Comment by YoshiRulz** [comment]
C# side didn't change from 1.12.1:
https://github.com/TASVideos/BizHawk/blob/fbd7601b773f6b2c4ed1ab67b42aafbe0da86766/BizHawk.Client.Common/lua/EmuLuaLibrary.Emu.cs#L393-L401
https://github.com/TASVideos/BizHawk/blob/fbd7601b773f6b2c4ed1ab67b42aafbe0da86766/BizHawk.Emulation.Cores/Consoles/Nintendo/SNES/LibsnesCore.cs#L710-L719
to 2.3.2 (I had Lua libraries delegate their behaviour to ApiHawk in 2.3.3):
https://github.com/TASVideos/BizHawk/blob/e39e083c13029b3f16c75bd69d04dda7554af713/BizHawk.Client.Common/lua/EmuLuaLibrary.Emu.cs#L342-L347
https://github.com/TASVideos/BizHawk/blob/e39e083c13029b3f16c75bd69d04dda7554af713/BizHawk.Emulation.Cores/Consoles/Nintendo/SNES/LibsnesCore.IRegionable.cs#L7-L18
If it broke sometime between those then it must have been on the unmanaged side.

**Comment by brunovalads** [comment]
Weird...
Worth pointing out commit f83261c116ae5ba24a573ad2332434abe8e61ddf that changed LibsnesCore.IRegionable.cs.

**Comment by brunovalads** [comment]
This fix also fixed the issue where the "PAL 1" flag in movie headers was not being set, marking all bsnes movies as NTSC by default, which later was detected by TASVideos submission system giving the wrong movie length.
