### ISSUE TITLE
[GB] Xenon 2 some enemy bullet sprites doesn’t appear in gambatte under console mode GBC and GBA

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2506]
Very begging at the game there is a plant like enemy on left side of the wall and it is shooting bullet. This bullet does not appear in gambatte core but still damage you.

Edit: version 2.5.2

![InkedXenon 2 - Megablast (USA, Europe) 2020-12-05 10 41 31_LI](https://user-images.githubusercontent.com/38931422/101237280-70571580-36e8-11eb-846a-0e0f04596298.jpg)
![InkedXenon 2 - Megablast (USA, Europe) 2020-12-05 10 42 11_LI](https://user-images.githubusercontent.com/38931422/101237281-73520600-36e8-11eb-9f43-dba6e071acc7.jpg)

**Comment by TiKevin83** [comment]
possibly related to issue 72 in upstream GSR, I'll test the current fix and see if there's any improvement. What version was this happening on? Can you test it on the current dev build and see if it's still occurring? There have been some Gambatte updates already this cycle.

**Comment by ozderya** [comment]
Yep. It was fixed on current dev build.
