### ISSUE TITLE
Windows 10 - Game crashes at startup.

### ISSUE THREAD

**Issue by JustinMDP** [TASVideos/BizHawk#2507]
Before I state what the error I'm getting is, I figured I'd touch on a few key things from seeing other posts when trying to troubleshoot it on my end: Windows is 64 bit (with a x64 based processor) and Windows 10 Pro. NVIDIA card drivers are up to date. I've installed the prereqs, and have attempted to reinstall them a few times in case something corrupted or got blocked. I've even attempted to do so with Windows Defender set to off. Hell, I've even contacted some friends of mine who actively use Bizhawk and none of them can figure out the issue. Lastly, I am using Bizhawk version 2.5.2, with prereq version 2.4.8_1

Anyway, when attempting to load EmuHawk, I get the following issue:

System.Exception: Initialization of Direct3d 9 Display Method failed; falling back to GDI+ ---> System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=null' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1) ---> System.BadImageFormatException: Could not load file or assembly 'SlimDX.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at BizHawk.Client.EmuHawk.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at BizHawk.Client.EmuHawk.IGL_SlimDX9..ctor()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   --- End of inner exception stack trace ---

After clicking ok on this, a second error message pops up but then the program closes before I can even hit the copy button to copy and paste it. However, I've made a screen capture of it. ( https://imgur.com/JGnq5cT )

**Comment by zeromus** [comment]
search your system for slimdx.dll and delete it. it's probably in c:\windows somewhere. you can also use process monitor to see where it's loading from by leaving it running with that filename filtered while booting bizhawk

**Comment by YoshiRulz** [comment]
I'm guessing there's a copy of `SlimDX.dll` installed somewhere (`System32`?) which is being loaded instead of the one shipped with BizHawk. Aaaand I got sniped by zeromus saying the same thing.

The obvious cause of a `BadImageFormatException` would be a corrupted file, which you can check by re-downloading [just that file](https://github.com/TASVideos/BizHawk/raw/master/References/x64/SlimDX.dll) or the whole release, but I'd go with the other explanation.

**Comment by zeromus** [comment]
This is also caused by the wrong bitness. Most likely a sloppy 32bit game has "installed" a 32bit dll to system32 instead of syswow64.

**Comment by JustinMDP** [comment]
Ok, so using Windows Explorer with "This PC" selected and the search string "SlimDX.dll" (mainly saying this in the event there is actually a better option for doing this) the only results I'm getting is in the Bizhawk dll folder itself.

https://imgur.com/gDBV5em

I'll try replacing it with the file Yoshi linked to and see if that helps.

**Comment by nattthebear** [comment]
These error messages are transitive so it could be any dependency of slimdx causing the issue.  Could use https://www.dependencywalker.com/ to see if anything weird shows up.

**Comment by YoshiRulz** [comment]
> Could use https://www.dependencywalker.com/ to see if anything weird shows up.

Or its spiritual successor, [lucasg/Dependencies](https://github.com/lucasg/Dependencies).

> using Windows Explorer with "This PC" selected and the search string "SlimDX.dll" (mainly saying this in the event there is actually a better option for doing this)

Honestly just spend a few minutes manually looking in `C:\Windows`. Windows' search is and always has been terrible for anything but finding documents in the My Documents folder.

**Comment by JustinMDP** [comment]
I downloaded that dependency walker thing, but if I'm being honest I'm not fully grasping what I'm looking at. I know enough about computers to get around, but when it comes to the deep inner workings it becomes gibbrish unfortunately.

I'm looking though the Windows folders and thus far I'm not really seeing anything SlimDX related. Already looked though the main Windows folder, and System32. I'm glimpsing inside all of the folders inside System32, but I'm not really seeing anything related. If it is there it's very well hidden I'd suspect.

**Comment by zeromus** [comment]
Youre supposed to open bizhawk's slimdx.dll and see if the dependency walker is unable to open it

**Comment by YoshiRulz** [comment]
You can find files with PowerShell:
```pwsh
Get-ChildItem -Recurse -Path "C:\" -Filter "SlimDX.dll" -File -ErrorAction SilentlyContinue
```

**Comment by JustinMDP** [comment]
Ok, opening bizhawk's slimdx.dll got me these error messages:

"Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module."

**Comment by YoshiRulz** [comment]
These are the files you're looking for then:
![Screenshot](https://user-images.githubusercontent.com/13409956/101295244-1d0bd100-3868-11eb-9e2c-26250b691c57.png)

**Comment by zeromus** [comment]
You're gonna have to do a better job scrutinizing or pasting the results from dependency walker. The different cpu types one is the problem.

**Comment by JustinMDP** [comment]
In the system 32 folder, of those files in your screen cap there I see all of them. So it doesn't seem like anything is outright missing.

As far as the scrutinizing goes... is there a way of easily copy and pasting all of this? I tried to save it and upload the dwi file but github says no.

**Comment by nattthebear** [comment]
> Error: Modules with different CPU types were found.

Make sure you're using the 64 bit version dependency walker, otherwise it will hit the wrong resolutions for Windows system dlls and bring up bad results like that.

**Comment by JustinMDP** [comment]
Yeah, I grabbed the x64 version.

**Comment by zeromus** [comment]
1. zip files github wont take
2. file > save as > change the type

**Comment by JustinMDP** [comment]
[slimdx.txt](https://github.com/TASVideos/BizHawk/files/5649902/slimdx.txt)

**Comment by zeromus** [comment]
delete c:\windows\system32\msvcp100.dll (make a backup just in case) and install these
https://download.microsoft.com/download/3/2/2/3224B87F-CFA0-4E70-BDA3-3DE650EFEBA5/vcredist_x64.exe
https://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe

**Comment by JustinMDP** [comment]
Alright. I've deleted that file.

I attempted to install both of those links but both of them gave me a "you got a newer version already mate" message and wouldn't let me.

**Comment by zeromus** [comment]
ah, yeah, that's believable. It's not worth messing up your system trying to get that to install, but if something seems to be missing that file, you might get those installers to work by deleting all msvcr100.dll also (from both system32 and syswow64) and deleting any remaining msvcp100.dll since I think those are the two those installers provide,.

**Comment by JustinMDP** [comment]
I got rid of them, but it's still telling me I have a newer version unfortunately.

**Comment by zeromus** [comment]
OOPS! I updated the post with the correct links.
Uninstall anything like visual c++ 2010 distributable/runtime you can see in windows add/remove programs.
But don't bother doing it right now, because deleting that file fixed your bizhawk

**Comment by JustinMDP** [comment]
Progress! It doesn't give me that error message anymore. Now it just says

"EmuHawk needs Microsoft Visual C++ 2010 SP1 Runtime (x64) in order to run! See the readme for more info. (EmuHawk will now close.)"

Which I should already have that runtime, weirdly.
