### ISSUE TITLE
BizHawk crashes almost every time I open the emulator

### ISSUE THREAD

**Issue by EvanLei1** [TASVideos/BizHawk#2509]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Once I open this emulator, it works as fine. It was version 2.5.2. Then when I open a file explorer on Windows, the file explorer and the emulator **stops** and **"suspends**" the program. I don't know how to solve it, so it is a heisenbug, and it still happened to me after running the emulator for 3 minutes. It mainly happened with supported BizHawk 2.5.2 crashing and it stops working after it doesn't respond.

"I was using BizHawk 2.5.2 for two weeks now. I have noticed that when I play games from this emulator, bugs happened extremely often, almost whenever I startup. I opened BizHawk and then I opened a SNES ROM, which takes 10 seconds to load. Once I didn't do anything, the emulator stopped at 1300 frames and was placed at "Suspended" according to the application status in Task Manager.

Windows stopped BizHawk because it stopped working. With BizHawk 2.2.x to 2.4.x works without crashes, bugs, and freezes, the 2.5.x version doesn't. This version series makes the BizHawk emulator stop working after 3 minutes of using it, with the same reason why it crashes when I run BizHawk v. 2.5.2 on any game.

I said two weeks ago about the same problem, "This happened when I play Ecco the Dolphin on my computer. Without pressing anything, there is a bug detected. The game stopped, it doesn't respond, and the app crashes because it stopped working. My computer has 2 core 2.7 GHz CPU and 4GB memory, as I was having concerns recording movies on NES and Genesis games. Also, it happened almost every time while recording Genesis games." Note that these bugs, crashes, and freezes weren't fixed as of December 6, 2020."

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5-2.5.2; Win10 Enterprise 2004; AMD A6

[//]: # "(screenshots, if applicable)"
![image](https://user-images.githubusercontent.com/75634096/101384424-4845ee80-386f-11eb-9cb5-d06e7918831a.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Did you run the new prerequisite installer when switching from 2.4.x to 2.5.x?

**Comment by EvanLei1** [comment]
No.

**Comment by EvanLei1** [comment]
I installed the prereqs recently. Nothing had changed, but it crashes when I open the game.

**Comment by YoshiRulz** [comment]
1. Try changing `Config` > `Display...` > `Display Method` to "OpenTK" and restarting
2. Try [this dev build](https://gitlab.com/TASVideos/BizHawk/-/jobs/895499640/artifacts/download) which has debugging enabled (the download link will expire in 30 minutes I think)

**Comment by EvanLei1** [comment]
> 1. Try changing `Config` > `Display...` > `Display Method` to "OpenTK" and restarting
> 2. Try [this dev build](https://gitlab.com/TASVideos/BizHawk/-/jobs/895499640/artifacts/download) which has debugging enabled (the download link will expire in 30 minutes I think)

What is a dev build?

**Comment by EvanLei1** [comment]
I didn't see OpenTK. I see OpenGL.

**Comment by YoshiRulz** [comment]
That's what I meant, sorry.

The dev build is just like a BizHawk release, but with some changes that might not work properly. In this case it may also give a more helpful message than "BizHawk.Client.EmuHawk has stopped working".

**Comment by zeromus** [comment]
Are you opening a file from within bizhawk? Try drag and drop for a while and see what happens.

**Comment by EvanLei1** [comment]
How to put the dev build into BizHawk 2.5.2?

**Comment by zeromus** [comment]
the provided file contains everything. Don't put it anywhere but a new folder on your desktop.

**Comment by EvanLei1** [comment]
It was not solved. The emulator version 2.5.2 is very **defective**, and when I open the emulator in OpenGL, it crashes within 2 minutes of using it, and it crashes even WITHOUT pressing any buttons or on idle.

**Comment by zeromus** [comment]
if you didn't use it, then you didn't load a rom. if bizhawk crashes without a rom being loaded, then the problem is in your graphics card. since you know how to specially choose opengl display method, why not try choosing direct3d instead and see what happens?

**Comment by YoshiRulz** [comment]
@EvanLei1 Are you still having this issue? Were you able to get any debugging information out of EmuHawk? I've triggered another automated build if you'd like to try again: [download](https://gitlab.com/TASVideos/BizHawk/-/jobs/933852664/artifacts/download) ([pipeline](https://gitlab.com/TASVideos/BizHawk/-/pipelines/234977980)).

**Comment by EvanLei1** [comment]
It works when using OpenTK sound.
