### ISSUE TITLE
Bizhawk crashes every time I try to change the volume (with Fn)

### ISSUE THREAD

**Issue by rain1598** [TASVideos/BizHawk#2512]
### Summary
I use Fn-(up) and Fn-(down) on my laptop to change the volume. However, Bizhawk crashes every time I do.

### Reproduce
Press Fn-(up) or Fn-(down) on a laptop which supports Fn volume changing. 

### Output
Bizhawk, even without a rom, music stops, freezes for 3 seconds, and crashes.

My computer is a Windows 10 x64 running Bizhawk 2.5.2 with i5-8250U, 8 gb of memory, and Intel UHD graphics 620.

![bug](https://user-images.githubusercontent.com/70437021/101653301-2c784f00-3a0d-11eb-959e-556129135d99.gif)

**Comment by YoshiRulz** [comment]
Can you try a [dev build](https://github.com/TASVideos/BizHawk#development-builds)? This should be fixed already (#2459).
