### ISSUE TITLE
saturn -- expansion carts doesn't work 

### ISSUE THREAD

**Issue by threenator** [TASVideos/BizHawk#2513]
I'm trying to run Street Fighter Zero 3 and Marvel Super Heroes vs. Street Fighter on BizHawk 2.5.2, and even selecting the correct configuration on Saturn -> Settings, the games doesn't run at all. It even displays a warning asking to put the 4MB cart on. It wasn't an issue on older versions such as 2.4.2.

Thank you.

**Comment by nattthebear** [comment]
So it did work in 2.4.2?  Probably some nyma related regression then; I just need to find and hook up the right thing again.

**Comment by Reinc01** [comment]
Still doesn't work in 2.8. Or rather, the 512KB option works, but all other options are ignored as if there is no memory card at all.
