### ISSUE TITLE
"[GBC] 1942" is stuck at password screen before stage 28 with GBHawk

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2514]
I first tried GBHawk and it stuck at password screen before  stage 28 and played with gammbatte to see if this core also have same issue. gammbatte was okay but realized GBHawk have also missing sprite at this screen which I circled in photo below.

Edit: ver 2.5.2

![Inked1942 (USA) 2020-12-10 22 29 53_LI](https://user-images.githubusercontent.com/38931422/101820420-a6a4f280-3b37-11eb-8ac1-97225b079311.jpg)

**Comment by alyosha-tas** [comment]
Interesting, can you try this in the dev build? A lot of changes have occurred in GBHawk since 2.5.2.

link: https://ci.appveyor.com/api/buildjobs/h9y57pvses2n1u8m/artifacts/BizHawk_Developer-2020-12-10-035412-%234447d5ddc7da235958c7943844898d8b82497f6d.zip

**Comment by ozderya** [comment]
Sure. I will test it with dev build soon.

**Comment by ozderya** [comment]
I was fixed in the current dev build.
