### ISSUE TITLE
Lua Console: Remove Lua Events on Disabling or Removing Script

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASVideos/BizHawk#2515]
Please remove events if the user disables or removes the script from the Lua Console. Otherwise when refreshing or restarting a script the the same events will start to accumulate and run multiple times per frame.  While you can right click and then remove the events by right clicking on the Lua console output and selecting "Clear Registered Events", it is unintuitive and is annoying to do every time you make a slight change.

**Comment by YoshiRulz** [comment]
I'm going to close this, not because it's not a good idea, but because I'm in the middle of obsoleting the current Lua scripting system. While you're waiting, here's a workaround:
```lua
-- insert one event.unregisterbyname call at the top of your script for each event handler you register; the string can be anything but must match what you pass to event.on* (i.e. when registering)
event.unregisterbyname("a");
event.unregisterbyname("b");
event.unregisterbyname("c");
event.onmemoryexecute(exec_handler, 0x1234, "a"); -- note the position of the name parameter depends on which event.* function you're calling
event.onmemorywrite(write_handler, 0x5678, "b");
event.onloadstate(loadstate_handler, "c");
```
