### ISSUE TITLE
GBA

### ISSUE THREAD

**Issue by Tas-player** [TASVideos/BizHawk#2517]
GBA doesn't respond no matter how you press it. The game doesn't start and the buttons don't respond

**Comment by TiKevin83** [comment]
Hi TAS-Player,
We need a lot more information about the computer you're trying to run on, including full system specs (cpu/gpu/ram). Something is off about that given the info from your other issue.

**Comment by YoshiRulz** [comment]
What version are you using? What rom(s) are you using? (This is why we have a template...)

I suspect the keybinds are just not what you're expecting. Change them in `Config` > `Controllers...`, and check that they're working with `View` > `Display Input`.

**Comment by Tas-player** [comment]
CPU i7-8700 GTX 1060 5G

**Comment by Tas-player** [comment]
Bizhawk 2.5.2

**Comment by Tas-player** [comment]
16g running memory

**Comment by Tas-player** [comment]
After debugging in the controller, there is still no control over the game.

**Comment by zeromus** [comment]
0. Don't expect it to work without manually configuring the controllers
1. Test another GBA game
2. Test a game from another system.

**Comment by Tas-player** [comment]
GBC&GB can be used normally, that is, GBA can't, and it can't be tested after changing many games

**Comment by zeromus** [comment]
1. disable your security software
2. rewrite "it can't be tested after changing many games" in a way that makes sense. try using more words.
3. write which games you're testing and tell us what buttons you are trying to press.

**Comment by Tas-player** [comment]
ROCKMAN ZERO & START KEY

**Comment by zeromus** [comment]
What do you see on your screen? Do you hear anything? Did you try importing a save file for that game? Click the green checkmark and copy out the rom hashes.

**Comment by Tas-player** [comment]
Can load the game and see, hear, but when it comes to the start screen, no matter how you press it, it doesn't respond

**Comment by Tas-player** [comment]
![image](https://user-images.githubusercontent.com/75160793/102077445-474f2700-3e44-11eb-90fe-687aa3db02ec.png)
Just stop here and the button doesn't work

**Comment by Tas-player** [comment]
![Uploading 1.jpg…]()

**Comment by Tas-player** [comment]
Just stop here and the button doesn't work

**Comment by zeromus** [comment]
Make a screenshot of config>controllers while this game is open, and then tell us what keyboard key you are trying to use to start the game

**Comment by Tas-player** [comment]
![Uploading 1.jpg…]()

**Comment by YoshiRulz** [comment]
Don't click "Comment" until the image has finished uploading

**Comment by Tas-player** [comment]
The key problem has been solved, but a new problem has appeared again. When GBA and GBC do TAs, the recording and playing are not synchronized

**Comment by Tas-player** [comment]
The key problem is that I use the wrong version, there is a problem

**Comment by Tas-player** [comment]
The key problem is that I use the wrong version

**Comment by zeromus** [comment]
So you're saying you have an all-new problem? Then open an all-new ticket without all this noise.

**Comment by YoshiRulz** [comment]
moved to #2523
