### ISSUE TITLE
How can I use Zapper and other peripherals in BizHawk?

### ISSUE THREAD

**Issue by anonymous7002** [TASVideos/BizHawk#2518]
Config/Controllers menu seems to only setup normal controllers.

**Comment by Spikestuff** [comment]
Have an NES game loaded up.
Config > Cores > NES > NESHawk
Reboot Core.

NES > Controller Settings...
![image](https://user-images.githubusercontent.com/12412764/102015971-a95f4c00-3db2-11eb-9aff-5df0794cad2a.png)
