### ISSUE TITLE
[Feature Request] Option to show fractional framerate

### ISSUE THREAD

**Issue by shenef** [TASVideos/BizHawk#2521]
Currently when enabling the "Show FPS" option, the framerate is only displayed as a whole number. 
It would be nice to be able to see fractional values (e.g. 59.727 instead of 60) so you can properly tell how close to accurate the game is currently running and how stable it's holding that framerate.
Alternative (or additionally) a "Show frametime" option could be added.

**Comment by nattthebear** [comment]
Bizhawk's realtime A/V presentation has nowhere near the accuracy you're expecting and that this value will be completely worthless.
