### ISSUE TITLE
crashes alot of the time 

### ISSUE THREAD

**Issue by DangerSR** [TASVideos/BizHawk#2524]
was doing attempts for a game to speedrun, but while attempting runs, bizhawk crashes 1 minute in. help?
vid : https://streamable.com/5elzdw

**Comment by nattthebear** [comment]
For anyone who prefers reading more than videos:

- Some powerpuff girls game
- mgba core
- Bizhawk itself crashes and terminate.  No error messages are shown.

**Comment by YoshiRulz** [comment]
I hadn't considered it, but yes, this could be another symptom of the unrecognised key bug (#2389). Do you use a non-QWERTY keyboard? Maybe you hit a volume control key or similar while playing? If you can repro the crash by pushing a certain key, please try a [dev build](https://github.com/TASVideos/BizHawk#development-builds) as it should be fixed.
