### ISSUE TITLE
Genesis core doesn't reset everything properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#253]
```
What steps will reproduce the problem?
1. Open ROM provided in attachment
2. Select Sonic Only (No Save)
3. It should pull up a corrupted level select screen.  Select Carnival Night 
Zone act one and wait for it to crash.
4.  Attempt a hard reset.

What is the expected output? What do you see instead?
Should reset and run the ROM.

What version of the product are you using? On what operating system?
SVN r7603

(Yes, this is a corrupted ROM, but the behavior is still incorrect)


```

Original issue reported on code.google.com by `Reaper.m...@gmail.com` on 17 Aug 2014 at 3:27

Attachments:
- [s3andk (10 knuckles, get into lava reef and others).bin](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-253/comment-0/s3andk %2810 knuckles, get into lava reef and others%29.bin)

**Comment by alyosha-tas** [comment]
Somehow this ROM is attempting (and succeeding) to write to ROM space. Addresses starting at 00061A are changed after the level is selected. They are not changed back as part of loading the state (obviously not expecting this region of memory to be swappable.)

The trace logger crashes on me when I attempt to use it to figure out exactly what's happening, but this is the basic explanation of the problem.
