### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Maenad44** [TASVideos/BizHawk#2534]
I was told to write here with my crash problem:
I think this software is not intuitive since it crashes on boot right after installing 4.6.1 framework.
Win7 32bit
AMD Phenom 2 x2 Processor 3,1 GHZ
8 GB Ram
I dont know what else can i say to help you fix it since i said my PC parameters and uploaded screenshot.
![rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr](https://user-images.githubusercontent.com/76597178/103140862-21e7d600-46ec-11eb-97db-1c4066200796.png)

**Comment by YoshiRulz** [comment]
I'm not sure which version you're trying to run, but given `EmuHawkMono.sh` is in there it must be 2.x. If you're not able to update your operating system then you'll have to use 1.x. Download it [here](https://github.com/TASVideos/BizHawk/releases/tag/1.13.2).

**Comment by Maenad44** [comment]
It was newest version that i assumed to be compatible with Win7 that majority of the population uses.
