### ISSUE TITLE
Please support open PBP file format on PSX emulator

### ISSUE THREAD

**Issue by Mark-Joy** [TASVideos/BizHawk#2539]
It would be wonderful if BizHawk can open PBP file format on PSX emulator. PBP has better compressed file size, and only single file is needed.

**Comment by zeromus** [comment]
this is up to mednafen to support.

**Comment by Spikestuff** [comment]
But the PBP format is technically **not** a PlayStation format.
It's technically exclusive for the PlayStation Portable that emulator devs just hacked into.
So technically in this very hypothetical scenario what you're requesting is something that's for a PlayStation Portable emulator.

[The longer more important information](http://tasvideos.org/forum/viewtopic.php?t=20563) about [this has been discussed before](http://tasvideos.org/forum/viewtopic.php?t=22267).
They have extra information.
