### ISSUE TITLE
All- t he sou-nd beco-mes lag-gy

### ISSUE THREAD

**Issue by TKTDTGT** [TASVideos/BizHawk#2543]
when running Sega Saturn the sound is laggy, while increasing the sound buffer solve the problem somehow is this a probability to increase the maximum value to 1000 or higher? 

- BizHawk 2.5.2; Win10 Pro 2003 NVIDIA

**Comment by TKTDTGT** [comment]
After a long fuck with files, I found several docs in the other folders. Removing them solves the problem

**Comment by YoshiRulz** [comment]
Is the framerate fluctuating or is it only the audio?

**Comment by nattthebear** [comment]
Saturn core is slow.  If your system isn't fast enough (should be getting at least 70-80fps when unthrottled), then there's nothing we can do.

**Comment by TKTDTGT** [comment]
i7 9750 60Gb RAM

nattthebear <notifications@github.com> 于 2021年1月3日周日 07:21写道：

**Comment by TKTDTGT** [comment]
![image](https://user-images.githubusercontent.com/54839301/103484207-c4b1eb80-4da1-11eb-9906-43200ad2cffd.png)
Is there someway I can share the log to you?

**Comment by TKTDTGT** [comment]
> Is the framerate fluctuating or is it only the audio?

The framerate is fluctuating and switching to several settings or default is not working.

**Comment by TKTDTGT** [comment]
ROM used is these two and they can be recognized by the simulator
[saturn-1.00.zip](https://github.com/TASVideos/BizHawk/files/5761935/saturn-1.00.zip)

**Comment by YoshiRulz** [comment]
Do you have a dedicated graphics card? The Intel iGPU might be slowing you down. In any case you should use another emulator, our priority is with accuracy and not speed.

Also I've hidden your comment as this is not a place for sharing roms.

**Comment by TKTDTGT** [comment]
I deleted the rom, sorry about that. I will run with graphic card to see if that is the case. The problem just happened suddenly after a reboot or something, (and at the same time my GOG, Steam and Android studio are down)

https://user-images.githubusercontent.com/54839301/103484317-b4e6d700-4da2-11eb-90ce-bce9e7cf25ca.mp4

**Comment by TKTDTGT** [comment]
![image](https://user-images.githubusercontent.com/54839301/103484599-d47eff00-4da4-11eb-99a0-cbde20a9d9b7.png)
The problem remains

**Comment by TKTDTGT** [comment]
![image](https://user-images.githubusercontent.com/54839301/103488551-621d1780-4dc2-11eb-9a63-82016727ab39.png)
Sometimes, and only sometimes removing this file slightly increase the performance. 
[EMUHAWK.EXE-BF79E9A9.zip](https://github.com/TASVideos/BizHawk/files/5762259/EMUHAWK.EXE-BF79E9A9.zip)
Disable integrated graphic processor also slightly increase performance but not too much.

**Comment by TKTDTGT** [comment]
> Do you have a dedicated graphics card? The Intel iGPU might be slowing you down. In any case you should use another emulator, our priority is with accuracy and not speed.
> 
> Also I've hidden your comment as this is not a place for sharing roms.

The problem is it used to perform well, but recently just not working for unknown reason.

**Comment by zeromus** [comment]
the pf files mean nothing.
I do not see a fluctuating framerate. Your images and videos do not SHOW a framerate. I hear a buggy sound card. Change bizhawk's sound output driver

**Comment by TKTDTGT** [comment]
So how can I change the sound output device? Working in windows device manger and adjusting anything in the simulator does not work.

**Comment by zeromus** [comment]
change it IN emuhawk.exe. You didn't have time to adjust everything in the "simulator", so I have doubts that you did.

**Comment by TKTDTGT** [comment]
In this panel ? but it still not working
![image](https://user-images.githubusercontent.com/54839301/103488891-4e26e500-4dc5-11eb-8802-17dde7846613.png)

**Comment by zeromus** [comment]
So what did you change in there? 
Turn on the FPS display in bizhawk and record another video.

**Comment by TKTDTGT** [comment]
Uploading bandicam 2021-01-03 13-27-05-544.mp4…

**Comment by TKTDTGT** [comment]
Uploading bandicam 2021-01-03 13-17-48-816.mp4…

**Comment by TKTDTGT** [comment]
Uploading bandicam 2021-01-03 13-27-05-544.mp4…

https://server29.freeconvert.com/converted/5d237a1107b7/bandicam%202021-01-03%2013-17-48-816.mp4

**Comment by TKTDTGT** [comment]
https://user-images.githubusercontent.com/54839301/103489286-52a0cd00-4dc8-11eb-996c-8959d3048a5b.mp4

**Comment by zeromus** [comment]
OK, that was a good video.
Have you turned off any streaming or overlay or reshading software? 
Have you tried changing config > display > display method?
Try changing config > speed/skip and choose unthrottled.
Then try running a gameboy game or some other low power 8bit system and see how many fps you get

**Comment by TKTDTGT** [comment]
Streaming software off, but problem remains. 
Display method checked, but not working
https://user-images.githubusercontent.com/54839301/103489516-e626cd80-4dc9-11eb-8b58-a3f0863976ac.mp4

unthrottled tried but still not working

https://user-images.githubusercontent.com/54839301/103489560-44ec4700-4dca-11eb-9bc0-61405e49fc95.mp4

tried mario but speed is a little weird 

https://user-images.githubusercontent.com/54839301/103489620-b3c9a000-4dca-11eb-9420-08ba5f447f94.mp4

**Comment by zeromus** [comment]
Why did you use the GBA mario? That is a 32bit system, not a low power 8bit system. That was a weird choice.
Anyway ok we can roll with that.
Use this
config > display > window > Misc > absolute zero
And the FPS will display in the window caption. Run that weird SMB on GBA rom and tell me what FPS range you get in the window caption. I get 515-620. I think there is a problem with your CPU. It is low power, or unable to turbo due to background processes. "speed 1.63ghz" in your performance monitor screenshot is not encouraging.

**Comment by TKTDTGT** [comment]
Sorry but I don't know too much about that.  it is around 200

**Comment by zeromus** [comment]
Your single core speed should be roughly the same as mine (ryzen 3800x). Your cpu should be turboing to 4.5 but it's running at 1.6ghz. That is 1/3 of its potential. 
Your fps is around 200; mine is around 550. That is around 1/3 of its potential.
Your laptop is put on power-saving mode or there is dust in your cpu fans or you have other processes running stealing CPU so that bizhawk can't make the CPU go to its turbo speed.

**Comment by TKTDTGT** [comment]
OK, I will see if I can change a power adapter or something else.
