### ISSUE TITLE
Instant crash when Windows 10 volume OSD is displayed

### ISSUE THREAD

**Issue by xy2iii** [TASVideos/BizHawk#2546]
### Summary
Seems to be the same as #2524. Whenever BizHawk is open, it will then crash seemingly randomly. It is possible to trigger the crash with certain actions, like triggering the pop-up volume slider.

Of note is that my laptop has HiDPI, though I'm not sure if that's significant. I'm willing to give more details as needed.

### Repro
Reproduction video: https://streamable.com/u75s56
The most reliable way I have found to trigger the crash is:
1. Open Bizhawk.
2. Invoke the Windows 10 volume on screen display (with volume up, for example).
3. BizHawk will then either instantly crash or crash after a bit, without any error messages.

### Output
No output, BizHawk will crash silently.

### Host env
- BizHawk 2.5.2; Win10 Family 1909; Intel/Intel

**Comment by YoshiRulz** [comment]
Duplicate of #2459?

**Comment by xy2iii** [comment]
Thanks! The fix described at [#2458 (comment)](https://github.com/TASVideos/BizHawk/issues/2458#issuecomment-713259505) works: I had to switch Input Method to OpenTK for it to work on my end. Closing this.

**Comment by xy2iii** [comment]
The crash is averted on the latest dev build.
