### ISSUE TITLE
Gambatte GB core: CDL missing OPCODE START flag (01)

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#2551]
latest repo, starts to be bad at leas two weeks ago

when Code/Data is logged, only bits > 1 are written (02, 04, etc). no code 01 which is OPCODE START (02 is OPCODE operand). all 02 are logged for code only. 

does this now a feature or bug? my scripts previously are depended on 01 bit and I noticed they don't work anymore because of that. 

this is not a problem, if this is a new behaviour. i will fix scripts then, but what if this is a BUG????

**Comment by YoshiRulz** [comment]
Gambatte was updated on Nov 24 (fe25b41c1), but other than that it's been basically the same since 2.5.

**Comment by nattthebear** [comment]
> previously 

Any idea when this was?

**Comment by g0me3** [comment]
always had been
[quote]
GB (gambatte)
CartRAM may or may not be present. Of course CartRAM may vary in size (and WRAM will depend on gb/gbc type)
Blocknames: ROM, CartRAM, WRAM, HRAM

Flags:

  ExecFirst = 0x01
  ExecOperand = 0x02
  Data = 0x04
[/quote]

http://tasvideos.org/Bizhawk/CodeDataLogger.html

**Comment by YoshiRulz** [comment]
Can you try the commit I linked, and the one before it?

**Comment by g0me3** [comment]
i'm not sure maybe i doing bissect wrong. but this issue remains at the start of the year 2019. maybe me not updating the emu for too long. or something else...

**Comment by g0me3** [comment]
as I remember correctly, there were an issue with gambatte core all the time, looking on my old CDL files. the 02 flag is always set even for OPCODE START byte. so there are many 03 bytes in CDL as soon as it set 02 and 01 at the same OPCODE START. so now this is works mostly the same, 02 set always for any opcode byte, but no more 01 flags are set.

tested now with fixed GBHawk Core, it does exactly as expecting: 01 for OPCODE START and 02 for OPERANDS of opcodes. no 03 flags at all.. it is fine, but most of other debug (i see debugger is hooked somehow, but very briefly and does not work) functionality in GBHawk is missing and also leads to crashes ;)

**Comment by CasualPokePlayer** [comment]
This is a regression from 2.4. This behavior appears on 2.4.1, and I believe this commit (https://github.com/TASVideos/BizHawk/commit/fd793322f9e5fdbfae2b14858587d82b86b51f50) is the cause. Not sure where in here this screwed up other than this was a very major update to Gambatte.
