### ISSUE TITLE
GENPLUS-GX CORE: TASStudio crashes

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#2553]
in MD with at start
************** Текст исключения **************
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.AccessViolationException: Попытка чтения или записи в защищенную память. Это часто свидетельствует о том, что другая память повреждена.
   в Bizhawk.BizInvokeProxyWaterboxHostNative.wbx_activate_host(IntPtr , ReturnData )
   в BizHawk.Emulation.Cores.Waterbox.WaterboxHost.Enter() в D:\Dev\BizHawk\src\BizHawk.Emulation.Cores\Waterbox\WaterboxHost.cs:строка 312
   в Bizhawk.BizInvokeProxyLibGPGX.gpgx_set_cd_callback(CDCallback )
   в BizHawk.Client.EmuHawk.CDL.set_CodeDataLogger(ICodeDataLogger value)
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в BizHawk.Emulation.Common.ServiceInjector.UpdateServices(IEmulatorServiceProvider source, Object target) в D:\Dev\BizHawk\src\BizHawk.Emulation.Common\ServiceInjector.cs:строка 38
   в BizHawk.Client.EmuHawk.ToolManager.Restart(Config config, IEmulator emulator, IGameInfo game)
   в BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   в BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   в BizHawk.Client.EmuHawk.MainForm.RebootCore()
   в BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
   в BizHawk.Client.EmuHawk.TAStudio.StartNewMovieWrapper(ITasMovie movie)
   в BizHawk.Client.EmuHawk.TAStudio.HandleMovieLoadStuff(ITasMovie movie)
   в BizHawk.Client.EmuHawk.TAStudio.StartNewTasMovie()
   в BizHawk.Client.EmuHawk.TAStudio.Engage()
   в BizHawk.Client.EmuHawk.TAStudio.Tastudio_Load(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в BizHawk.Client.EmuHawk.FormBase.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by g0me3** [comment]
in GBHawk core works normally
not tested any other cores

**Comment by nattthebear** [comment]
The posted error is most likely a gpgx core issue, so let's stick with that.  If there's a problem with the gambatte core and tarsestudio, open a separate issue.

**Comment by nattthebear** [comment]
Trivially reproduces on ecafbde:

1. Open up a Genesis ROM
2. Open the Code Data Logger
3. Open TasStudio

**Comment by YoshiRulz** [comment]
Has nothing to do with TAStudio, any core restart is sufficient as long as the CDL had been loaded (it can even be closed). 234642ed0 is the first broken commit (though its description implies there was a more prevalent crash which it fixed).

**Comment by g0me3** [comment]
im not usre why cdl here is involved. before i tested it me disabled the cdl and it crashes without any cdl involving

**Comment by g0me3** [comment]
i'm awave that using CDL crashes almost any portion of the emulation lol 
but apart from this issue, wether this is right as well?
