### ISSUE TITLE
Gambatte GB core: TASStudio silently closes the emulator

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#2554]
just run it

**Comment by nattthebear** [comment]
Trivially reproduces on ecafbde:

1. Open up a GB ROM, ensuring that the Gambatte core is used.
2. Open the Code Data Logger
3. Open TasStudio

Interestingly, the repro steps and the failure mode (unmanaged code access violation) are both identical to https://github.com/TASVideos/BizHawk/issues/2553.  Accordingly, my first instinct to separate the issues may have been wrong, but we'll see what we find.

@YoshiRulz I suspect a lifecycle issue of some sort with the tool stack; if we're trying to disengage a CDL that's already dead, or something, that might blow everything up.

**Comment by g0me3** [comment]
ok, can confirm, CDLogger causes this, usually I have it autoloaded, then close then open TAStudio and it eventually crashes even if there CDL window already closed. if no CDL had started, Studio runs just fine

**Comment by YoshiRulz** [comment]
Haven't tested this core but I'm assuming this was the same bug as #2553 after all, and so should be fixed with 9ed56cdc6.
