### ISSUE TITLE
On whether the game of Playstation can be run on bizhawk

### ISSUE THREAD

**Issue by Tas-player** [TASVideos/BizHawk#2556]
I wonder if I can run Playstation games on bizhawk, such as Rockman 8.

**Comment by zeromus** [comment]
hey, that's my job

**Comment by Tas-player** [comment]
After loading the game, the option to select the emulator platform will pop up. After selecting Playstation, the screen will not respond and the game will not run

**Comment by zeromus** [comment]
open cue files, not bin or iso files.

**Comment by Tas-player** [comment]
I didn't think the previous one was published. No, I republished this one

**Comment by Tas-player** [comment]
I republished this one. I thought it was not published before. Now you can delete the old one

**Comment by Tas-player** [comment]
Yes, it does use the bin file

**Comment by Tas-player** [comment]
And I also loaded all the BIOS files needed by PlayStation

**Comment by Tas-player** [comment]
So how to open the cue file

**Comment by zeromus** [comment]
how to open any file?

**Comment by Tas-player** [comment]
&nbsp;I am understand&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zeromus"<notifications@github.com&gt;; 
发送时间: 2021年1月9日(星期六) 上午9:15
收件人: "TASVideos/BizHawk"<BizHawk@noreply.github.com&gt;; 
抄送: "Minion Kevin"<762647511@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [TASVideos/BizHawk] On whether the game of Playstation can be run on bizhawk (#2556)






打开提示文件，而不是bin或iso文件。

—
因为修改了打开/关闭状态，所以您收到了此消息。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by Tas-player** [comment]
I've solved this problem, but it's the same as GBA when doing TAS of PS




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zeromus"<notifications@github.com&gt;; 
发送时间: 2021年1月9日(星期六) 上午9:22
收件人: "TASVideos/BizHawk"<BizHawk@noreply.github.com&gt;; 
抄送: "Minion Kevin"<762647511@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [TASVideos/BizHawk] On whether the game of Playstation can be run on bizhawk (#2556)





 
how to open any file?

**Comment by zeromus** [comment]
Then the issue will be solved when the GBA issue is solved. Add extra steps including PSX test cases to the GBA thread if you want, but the most useful would be a complete screen recording of every step you make on the shortest possible tas that fails on playback. PSX games are long and slow, so GBA would be a better test case.
