### ISSUE TITLE
Does Bizhawk Support Rumble?

### ISSUE THREAD

**Issue by appollo147** [TASVideos/BizHawk#2558]
I am new to Bizhawk and I play using an XBox One wired controller. I have tried several options trying to enable rumble on PSX and N64 games but I couldn't get it to work. So my question is this, does Bizhawk support rumble, and if so how do I enable it?

**Comment by YoshiRulz** [comment]
Both cores (Mupen64Plus and Octoshock) support rumble but it's not wired up.

Duplicate of #1756.
