### ISSUE TITLE
Sega Saturn Expansion RAM Upgrade games won't work since Ver. 2.5.0 and above

### ISSUE THREAD

**Issue by TheProdigiousRMZ** [TASVideos/BizHawk#2559]
I've been trying to find research on the Sega Saturn games that needed a RAM Upgrade (4MB minimum) in the latest Bizhawk emulator versions (in this case, Ver. 2.5.2), but for unexpected circumstances it doesn't want to load properly.

In a generic example, when loading KOF 95 (3MB Variant), i get an RAM Error, i tried enabling it with either 1MB, 4MB and 16MB in the Expansion RAM Sync Settings and rebooting the core, but nothing works.

The last version that loaded Saturn games with Expansion RAM properly was on Ver. 2.4.2 of the emulator.

**Comment by nattthebear** [comment]
https://github.com/TASVideos/BizHawk/issues/2513
