### ISSUE TITLE
Improve the IGameboyCommon.GetGPU API

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2564]
It started as a Gambatte only API, then was minimally worked over to support waterbox.  It doesn't really feel nice implementing on a managed core at all.  Here's what I'm thinking of.

```cs
interface IGameboyCommon
{
  // ... other methods omitted

  // Acquire GPU memory for inspection.  The returned object must be disposed as soon as the frontend
  // tool is done inspecting it, and the pointers become invalid once it is disposed.
  IGPUMemoryAreas LockGpu();
}

interface IGPUMemoryAreas : IDisposable
{
  IntPtr Vram { get; }
  IntPtr Oam { get; }
  IntPtr Sppal { get; }
  IntPtr Bgpal { get; }
}
```

* The waterbox (Sameboy) implementation could acquire the waterbox lock in `LockGpu` return the pointers directly to guest memory, and release the lock in `Dispose`.
* The Gambatte implementation could just return the pointers to unmanaged memory, no problem.
* The GBHawk implementation could pin the managed arrays in `LockGpu`, return those pointers, and then unpin in dispose, removing the need for the copy that we have now.

So all three cores would be able to do this with 0 copy and in a reasonably ergonomic way.

I'm willing to do this work myself, but I want to see if it will fit our needs.  @alyosha-tas let me know what you think.

**Comment by adelikat** [comment]
I really like this design

**Comment by alyosha-tas** [comment]
Yeah go for it, I haven't looked at any of that stuff in a while but I remember it being a headache trying to make it work.

I loaded up the GPU viewer just now and I'm getting some random crashes in both GBHawk and Gambatte. I don't remember it crashing before, maybe that new sprite position viewer? No error message and not sure how to reproduce, I'll try to narrow it down.

Also maybe unrelated but the update on scanline option doesn't work in Gambatte.
