### ISSUE TITLE
Taito Grand Prix: Eikou e no License doesn't have SaveRAM

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2570]
Reproduce steps:

1. On title select "Normal"
2. Create profile with player name
3. Go to the first town and save game
4. Press "Ctrl + R" to reset game and on title screen select "Normal". You can see that game recognizes profile with player name . But if you close rom from menu "File - Close ROM" and launch it from "Recent ROM", profile with player name, that you created earlier is disappear somewhere.
[Taito Grand Prix Eikou e no License .zip](https://github.com/TASVideos/BizHawk/files/5823421/Taito.Grand.Prix.Eikou.e.no.License.zip)

Expected behavior that Bizhawk is (will) create something, so you can continue play game without using save states, using only in-game saves (battery), there's no SaveRAM file (-s) in "Bizhawk - NES" folder

Tested on Bizhawk 2.5 and 2.5.2

**Comment by Yave-Yu** [comment]
_Kaijuu Monogatari_ too.

**Comment by nattthebear** [comment]
Taito Grand Prix is most likely fixed (I gave it my best effort to test, but I don't know any Japanese so the menus were a pain.)

Kaijuu Monogatari is most likely fixed.  I looked at the code and it should be the same codepath.  I did not test it.
