### ISSUE TITLE
Loading multidisc PSX throws an exception

### ISSUE THREAD

**Issue by jackjasonb** [TASVideos/BizHawk#2573]
### Summary
Loading PSX Multidisk XML file throws an exception. Exceptiopn Message is below.

XML is here.
```xml
<BizHawk-XMLGame System="PSX" Name="DRAGONQUEST7_1">
  <LoadAssets>
    <Asset FileName=".\DRAGONQUEST7_1.CUE" />
    <Asset FileName=".\DRAGONQUEST7_2.CUE" />
  </LoadAssets>
</BizHawk-XMLGame>
```
This ROM can be read PSX(J) BIOS firmware.
When I open only disk 1 .cue file, I can load ROM.  
I got this exception when I try update Bizhawk 2.4.2 to 2.5.2.
It's similar to this issue.　#2557

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open CD1 of a PSX game with multiple discs
2. Open the multidisc bundler and create a bundle
3. Save and run the bundle
4. Throw Exception

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."

<img width="452" alt="スクリーンショット 2021-01-16 21 08 33" src="https://user-images.githubusercontent.com/54601897/104811711-c5865b00-5840-11eb-9cde-77ec3ebe6a63.png">

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.2; Win10 Home(latest); Intel core i7
- PSX BIOS(J)

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
The related issue you linked has been fixed in [dev builds](https://github.com/TASVideos/BizHawk#development-builds), could you please try one of those?

**Comment by jackjasonb** [comment]
Thank you for your reply.
I tried [dev build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts)(BizHawk_Developer-2021-01-15-234757-#26fb9b9694b4360f9aa6d7ec361d17a52b342bde), but I got same Exception below.
<img width="461" alt="スクリーンショット 2021-01-16 21 51 52" src="https://user-images.githubusercontent.com/54601897/104812457-932b2c80-5845-11eb-9849-e2587219a0bf.png">

Furthermore, I've tried loading Disc1 .cue file, it loaded without any problems.

**Comment by Spikestuff** [comment]
> This ROM can be read PSX(J) BIOS firmware.

You grabbed the American version of Dragon Quest.
> BizHawk Emulation Couldn't find required firmware "PSX:U".

This is not a multidisk issue. This is a user issue.
Was only able to replicate this by removing my bios files.

**Comment by jackjasonb** [comment]
Spikestuff:
The ROM was definitely the Japanese version. I read to your xml file and tried a few things about the file name.
I've tried three type of file names.
First,
```
DRAGONQUEST7_1.BIN
DRAGONQUEST7_1.CUE
DRAGONQUEST7_2.BIN
DRAGONQUEST7_2.CUE
```
and xml file is here. This file name is "DRAGONQUEST7_1.xml"
```xml
<BizHawk-XMLGame System="PSX" Name="DRAGONQUEST7_1">
  <LoadAssets>
    <Asset FileName=".\DRAGONQUEST7_1.CUE" />
    <Asset FileName=".\DRAGONQUEST7_2.CUE" />
  </LoadAssets>
</BizHawk-XMLGame>
```
First case throws Exception. Second, changed the filename to your xml.
```
Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1).bin
Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1).cue
Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 2).bin
Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 2).cue
```
and xml file is here. This file name is "Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1).xml"
```xml
<BizHawk-XMLGame System="PSX" Name="Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1)">
  <LoadAssets>
    <Asset FileName=".\Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1).cue" />
    <Asset FileName=".\Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 2).cue" />
  </LoadAssets>
</BizHawk-XMLGame>
```
I chenged .cue file below.
```
- FILE "DRAGONQUEST7_1.BIN" BINARY
+ FILE "Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```
Second case doesn't throw Exception! I can load ROM! 
Third, I modified extension to lowercase.
```
DRAGONQUEST7_1.bin 
DRAGONQUEST7_1.cue
DRAGONQUEST7_2.bin 
DRAGONQUEST7_2.cue
```
and xml file is here. This file name is "DRAGONQUEST7_1.xml"
```xml
<BizHawk-XMLGame System="PSX" Name="DRAGONQUEST7_1">
  <LoadAssets>
    <Asset FileName=".\DRAGONQUEST7_1.cue" />
    <Asset FileName=".\DRAGONQUEST7_2.cue" />
  </LoadAssets>
</BizHawk-XMLGame>
```
The contents of cue file have been modified in the same way.
Third case doesn't throw Exception, too.

<img width="777" alt="スクリーンショット 2021-01-17 2 39 03" src="https://user-images.githubusercontent.com/54601897/104819305-edd97e00-586f-11eb-856a-8a637d25897b.png">

I was able to solve the problem successfully!
Thank you, YoshiRulz ! :)
Thank you, Spikestuff ! :)
