### ISSUE TITLE
Movie system Id () does not match the currently loaded platform (GEN)

### ISSUE THREAD

**Issue by ItsPietroFelix** [TASVideos/BizHawk#2574]
I was making a TAS, and when i clicked to save it, bizhawk crashed and now the .tasproj file doesn't open.
What do I do?

**Comment by ItsPietroFelix** [comment]
Version 2.5.2

**Comment by YoshiRulz** [comment]
Duplicate of #2479? Using 7zip or similar, remove the file `GreenZone` from the `.tasproj`.

**Comment by ItsPietroFelix** [comment]
I tried using WinRAR, but it said that the file was corrupted.

**Comment by vadosnaprimer** [comment]
> Using 7zip

Try using 7zip.

**Comment by ItsPietroFelix** [comment]
Still nothing.
Guess i'll have to tas it all over again.

**Comment by vadosnaprimer** [comment]
Upload it somewhere.

**Comment by ItsPietroFelix** [comment]
https://drive.google.com/file/d/1n3ihrH1B6Et15a22dw_Qx1MFJsX-05i8/view?usp=sharing

**Comment by vadosnaprimer** [comment]
Try this one https://yadi.sk/d/wMcPXPpBaEfhlA

**Comment by ItsPietroFelix** [comment]
Thanks, the file now works!
I think it's case closed now

**Comment by vadosnaprimer** [comment]
What version of 7zip do you have?

**Comment by ItsPietroFelix** [comment]
9.20

**Comment by vadosnaprimer** [comment]
Update I guess. I used newer and it worked. Opened, removed `GreenZone`, packages to .zip, renamed to .tasproj.

**Comment by ItsPietroFelix** [comment]
Thank you for the help, this TAS was already on the end of the game, and losing 1+ week of work would be awful.
I'll update 7zip.

**Comment by vadosnaprimer** [comment]
Don't you have autobackups enabled?

**Comment by ItsPietroFelix** [comment]
Yes, they are enabled. But somehow new versions of the file don't show up.
Guess they are set-up to save in the original file, i dunno

**Comment by vadosnaprimer** [comment]
Check in `[YourHawkDir]\Movies\backup`

**Comment by ItsPietroFelix** [comment]
Nope. Just the "default.tasproj" file there.
Nothing on the file.
