### ISSUE TITLE
"Plus" as a hotkey was renamed to "Equals", but the default hotkey for "increase speed" is still set to "Plus".

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#2576]
Plus as a hotkey was renamed to Equals but default Speed Increase hotkey was not updated to reflect this.  In order to speed up emulation you have to set the hotkey for "Increase speed" to be "Equals", as "Plus" doesn't go to anything.

**Comment by McW4v3-X** [comment]
Plus and Equals are the same key. Pressing it types in =. Pressing it while holding down Shift types in +.
Pressing += does nothing. Holding down Shift and pressing += doesn't do anything either

**Comment by YoshiRulz** [comment]
I'm able to bind hotkeys to `Equals` and `Shift+Equals` on a759e2626. Where are you trying to type, what version are you using, and what input method are you using (in `Config` > `Customize...`)? It would be best if you open a new issue with those details, this one is only tangentially related to keybinding.
