### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by NotReaper122** [TASVideos/BizHawk#2578]
Whenever i try to open EmuHawk.exe it says there was an error compiling the shaders.

**Comment by YoshiRulz** [comment]
Did you install the [prereqs](https://github.com/TASVideos/BizHawk-Prereqs/releases/tag/2.4.8_1)? (I assume you're using 2.6 from today.) What GPU do you have?

**Comment by NotReaper122** [comment]
I was using 2.5.2 but i will update. And my GPU is intel (R) UHD Graphics 630

**Comment by NotReaper122** [comment]
And how do you install prereqs?

**Comment by YoshiRulz** [comment]
Download, extract, and run the thing I linked above.

**Comment by NotReaper122** [comment]
Ok.
