### ISSUE TITLE
Clock Throttle assumes 60FPS for all systems

### ISSUE THREAD

**Issue by energynede** [TASVideos/BizHawk#2580]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
The Clock Throttle sound setting now seems to assume that every system is running at 60FPS, leading to incorrect sound output when that setting is used on a core that does not run at 60FPS. This has been observed with Vectrex, Wonderswan, VirtualBoy, and PAL games on multiple systems. This behavior was observed on a fresh install of BizHawk 2.6, and does not occur in BizHawk 2.5.2.

**Comment by alyosha-tas** [comment]
This was broken in 636a9a4

When Sound and SoundOutputProvider perform the callback _getCoreVsyncRateCallback they have a null IEmulator instance. 

core.VsyncNumerator() returns 60 in this case. I don't know why it's null. @YoshiRulz

**Comment by nattthebear** [comment]
Well yeah, that's always going to use the emulator that existed at the moment the thing was instantiated.

**Comment by YoshiRulz** [comment]
Yeah that's my bad. I really need to stop my obsession with method groups.
