### ISSUE TITLE
DiscoHawk won't extract the audio tracks to MP3

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#2581]
I don't know what's the problem with DiscoHawk for me.
Before i have lost my original hard drive because of Windows 10 corruption files, it was working like normal.
Now when i want to extract the audio tracks from a multiple bin/cue game, it doesn't do anything, it doesnt even throw an error, its suposted to extract the audio tracks to the same directory where that game is.
Sure i can still do the CCD conversion but now i cant with the audio tracks and not even doing the CCD conversion then tried to extrack the audio tracks worked.

**Comment by nattthebear** [comment]
If this is a brand new bizhawk install, you'll have to open bizhawk and use the download ffmpeg button (somewhere in the audio video dumping options/setup) to have ffmpeg for discohawk to use.

**Comment by nattthebear** [comment]
@zeromus Thoughts on adding the ffmpeg downloader nag to discohawk?

**Comment by danylopez123** [comment]
I downloaded it and placed in the dll folder but sadly, is still not working for me.

**Comment by adelikat** [comment]
"placed in the dll folder", did you download it through the BizHawk UI? This suggests you did not.  You would not have to have placed it anywhere yourself.

**Comment by danylopez123** [comment]
I did downloaded it through the BizHawk UI but i did the manual option because it gave an error when it tried to download from the Download button, i had to do the link option.
Also, i didint typed it correctly but yes, i did placed the FFMpeg.exe file in the dll folder.

**Comment by danylopez123** [comment]
I am not trying to do a bump but i've tried something else with DiscoHawk + i did this on 2.6.1
I tried to run DiscoHawk as Admin and that causes to prevent dragging the .cue files for both CCD dumping and MP3 Extraction, it just blocks them.

**Comment by zeromus** [comment]
So you've learned not to run discohawk as admin, right? You may need to disable UAC in order to have a functional windows system.

**Comment by YoshiRulz** [comment]
On the contrary, you need UAC on the highest setting to protect against privilege escalation attacks. (And obviously stop running things as admin when they don't need it.) There are [working POCs](https://github.com/hfiref0x/UACME) for circumventing the lower UAC settings—which sounds like a security blunder from Microsoft, and it is in effect, but the lower settings were [only added to appease customers](https://devblogs.microsoft.com/oldnewthing/20160816-00/?p=94105) who were complaining the loudest.

**Comment by zeromus** [comment]
What part of "needed for secure computer" is contrary to "needed for functional computer". These are orthogonal; the most secure system is one you never even turn on. Stop wasting my time, I was tired of arguing about this already when you were still arguing with your parents about your bedtime.

**Comment by danylopez123** [comment]
Please, do not start an argument with this "UAC" stuff.
I just wanted to say that i've fixed this now.

The UAC option from Windows didin't worked but then i did a command from the CMD program and i restarted my PC and it did the trick.
Im closing this now.
