### ISSUE TITLE
IndexOutOfRangeException when trying to open a bk2 file

### ISSUE THREAD

**Issue by anonymous7002** [TASVideos/BizHawk#2582]
http://tasvideos.org/userfiles/info/31829455564006099
When I try to open this, it throws "IndexOutOfRangeException".

**Comment by vadosnaprimer** [comment]
It's for hawk version 1.11.6.

**Comment by nattthebear** [comment]
Opening movie files from old hawks isn't generally supported.  If you want to resync an old movie forward, you'll need to put in some effort.  In most cases, you can start by lifting out the input roll and putting it into a new movie file, but there can be other obstacles as well.
