### ISSUE TITLE
Wagyan Land 2 - Graphical bugs

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2584]
Bizhawk 2.6 (Core - NesHawk)

![Wagyan Land 2 (Japan) (Virtual Console) 2021-01-19 21 58 06](https://user-images.githubusercontent.com/21311432/105086441-0cc35480-5aaa-11eb-915e-0f2b0e54ce63.png)

Fceux 2.3.0
![Wagyan Land 2 (Japan) (Virtual Console)-0](https://user-images.githubusercontent.com/21311432/105086505-24024200-5aaa-11eb-9a67-d39db1e85f25.png)

This is stage isn't possible to pass due to the graphical bug, tested in Fceux, Mesen, Nintendulator and _Bizhawk_:

![Wagyan Land 2 2021-01-21 03 41 05](https://user-images.githubusercontent.com/21311432/105268369-25636580-5ba3-11eb-9d87-87218bc57dc5.png)

In the Nestopia UE (version 1.50) this stage also unplayable:

![Wagyan Land 2 (Japan)_001](https://user-images.githubusercontent.com/21311432/105276381-4f705400-5bb2-11eb-9ec5-52a201db8d58.png)

Can be this is fixed, or i should switch to the fceux to record a longplay for this game? 

Note: Rom used is _Wagyan Land 2 (Japan)_ from _no intro_

Dump Status Report (rom marked green √):

Identified from BootGod's database

------
BEGIN NES rom analysis:
Found iNES header:
pr=256,ch=128,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER210,sys=
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: sha1:97E7E61EECB73CB1EA0C15AE51E65EA56301A685
headerless rom hash:  md5:4238F0A8612EA6B4BCBD39C416A64321
Could not locate game in bizhawk gamedb
Chose board from nescartdb:
pr=256,ch=128,wr=0,vr=0,ba=0,pa=0|0,brd=NAMCOT-340,sys=Famicom
Final game detection results:
pr=256,ch=128,wr=0,vr=0,ba=0,pa=0|0,brd=NAMCOT-340,sys=Famicom
"Wagyan Land 2"
Implemented by: class Namcot175_340
END NES rom analysis
------

This game is using iNES Mapper 210, and Namco 340 (Submapper 2) - https://wiki.nesdev.com/w/index.php/INES_Mapper_210 , vertical mirroring (as shows fceux 2.3.0 from the "Debug - iNES Header Editor"

[Wagyan Land 2.NesHawk.QuickSave.zip](https://github.com/TASVideos/BizHawk/files/5846700/Wagyan.Land.2.NesHawk.QuickSave.zip)

**Comment by medigi** [comment]
https://youtu.be/YaloJo1rlpY?t=1695 - Time code for this stage, someone recorded gameplay/walkthrough from famicom

**Comment by nattthebear** [comment]
I took a look and this isn't anything simple/obvious with the mapper data being wrong.  It may require actual effort to fix.

**Comment by Bangerra** [comment]
I think this is can be related to the mirroring issue. If someone can make temporary workaround or pull request, topic starter can than test if everything works fine.

**Comment by nattthebear** [comment]
What mirroring issue?

**Comment by medigi** [comment]
Just tested this game in Nestopia Plus! emulator and it is works fine both levels

Mirroring register maybe (there was similar problem like here, in the Wagyan Land 3 - this was fixed in fceux by implementing namco 340 NT mirroring register)
[Nestopia Plus!.zip](https://github.com/TASVideos/BizHawk/files/5953576/Nestopia.Plus.zip)
[Uploading Wagyan Land 2 in Nestopia Plus!.zip…]()

**Comment by YoshiRulz** [comment]
That dump is in our copy of `NesCarts.xml` (bootgod's DB) as mapper 210, not mapper 19 as Nestopia gives.

**Comment by zeromus** [comment]
nesdev wiki has details to the level of defining submappers, which is almost certainly newer than neshawk's handling of this

https://wiki.nesdev.com/w/index.php/INES_Mapper_210

the mapper may just need to be fully refreshed
