### ISSUE TITLE
Tottoko Ham Tarou 3 never shows the next screen from name entry

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#259]
```
What steps will reproduce the problem?
1. Load Tottoko Ham Tarou 3 GBA ROM
2. Start new game and enter hamster names

What is the expected output? What do you see instead?
It never shows the next screen (ham2.png). It shows name entry screen eternally.

What version of the product are you using? On what operating system?
BizHawk 1.8.0 on Windows 7 x64

```

Original issue reported on code.google.com by `gochaism` on 29 Aug 2014 at 1:41

Attachments:
* [ham1.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-259/comment-0/ham1.png)
* [ham2.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-259/comment-0/ham2.png)

**Comment by nattthebear** [comment]
We now use mgba, which this works in.
