### ISSUE TITLE
Unable to emulate a PSX game

### ISSUE THREAD

**Issue by EvanLei1** [TASVideos/BizHawk#2592]
I tried to load a 409MB **7z** file with Densha De Go! ROM for PSX. Then it takes a long time to respond and I realize that it is a PSX game and the firmware is missing. I had **scph1001.bin** file put in the firmware folder and it was a PSX BIOS file, but the game still didn't load because of the missing firmware.

I was running BizHawk 2.6. When I put a cue file in DiscoHawk, it doesn't recognize it and an error message was shown. When I tried to open a bin file (this game has 4 tracks, so the first one is >500MB), it doesn't load because there were unsupported characters. This game was Japanese version **only** and I don't have a way how to load Densha de Go in PSX, N64, or GBC.

**Comment by zeromus** [comment]
My trigger finger is itching to close this "an error message was shown" post which lacks the text of the error message.

**Comment by Spikestuff** [comment]
- Japanese Game Mentioned
- American Bios Mentioned

[This is what the upstream emulator requests, hunt these 3 down](https://mednafen.github.io/documentation/psx.html#Section_firmware_bios) (heck even Hawk tells you to get these three).

I'll check the game later but this is 100% leaning to just a user error.

**Comment by nattthebear** [comment]
The emulator does its best to tell you what's going on here:  When it fails to load a game, it gives you a message that tells you exactly what BIOS file you're missing, and offers to send you off to our firmware screen where you can see exactly what BIOS files you have and what ones you don't.

**Comment by EvanLei1** [comment]
@nattthebear I tried this game using another bios **scph1000.bin**, but it still doesn't work. I don't think all scph variants work as BIOS for PSX. Also, I don't know how to open and load the game called **Densha de Go 2 (PSX)**.

**Comment by zeromus** [comment]
"doesn't recognize it" "an error message was shown" "still doesn't work" "don't know how"
Open a new bug WITH AN ERROR MESSAGE. This one needs to be purged from the universe.

**Comment by YoshiRulz** [comment]
This is what your firmware config should look like (the checkmark specifically, you're going for the J BIOS not U):
![Screenshot_20210225_162608](https://user-images.githubusercontent.com/13409956/109112378-46147180-7786-11eb-8ed4-bb855be46850.png)

Please include the actual error message you're seeing if you want our help. Better yet, join IRC/Discord and ask for help because this is (supposed to be) an issue tracker.

**Comment by nattthebear** [comment]
> I don't think all scph variants work as BIOS for PSX.

You are correct; they don't.  That is not a feature of this emulator.  It emulates a particular revision of PSX hardware and supports BIOSes that were shipped with that hardware.
