### ISSUE TITLE
Frequent PSX Desyncs Issues (CTR NTSC-U / -J / PAL)

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#2598]
I've had this issue since 2.4, then 2.4.2, 2.5.2 and now 2.6, on the game Crash Team Racing for PSX. (NTSC-U / J / PAL)
I will include some tasproj i started collecting recently to hopefully provide more material towards fixing this issue.

These kinds of desyncs cant possibly be fixed by messing around with the inputs afterwards, usually lag frames mess up everything, once a desync happens, no matter what i try, its hopeless. Even without lag frames, it seems re-syncronization is still impossible.

DESYNCS tasproj folder: https://mega.nz/folder/i1U1RC7a#5WfxDsNAqhRFMescyxYmXw

I've had 3 different desktops, and ive had the same issues on all of them. Today another taser from this game tried to switch from 2.3.0 to 2.4 but he faced the same issues. This happens in all versions of this game. I actually have no idea if it depends on the game or bizhawk specific psx core, but i suppose so since in 2.3.0 noone of this happens. 
Im also guessing that these desyncs tend to happen more in this game, as it doesnt seem plausible that not so much people get PSX desyncs so often.

It happens in random time frames. Can happen in the menu, while playing, loading. It doesnt seem to present any similarities with the exception of being unfixable. I've tried in the past 6 months to analyze even more in depth if some ways of tasing triggered this mechanism, but there was nothing i could find that proved this theory. Also this other taser doesnt even drag inputs like i once did, and he still gets this very annoying issue.

Is the only answer still using 2.3.0? (My only problem with not sticking to 2.3.0 is that its incredibly slow, despite having a decent desktop)

Usually there are no error outputs, at least on the newer versions of bizhawk, but if i manage to replicate on an older version, and getting an error when switching between the sync/desync sections, ill make sure to update it here.

![1](https://user-images.githubusercontent.com/47687575/106293580-77b12000-624e-11eb-897d-b254a242047d.png)
![2](https://user-images.githubusercontent.com/47687575/106293587-78e24d00-624e-11eb-83e0-6d5fd930f11d.png)

**Comment by zeromus** [comment]
Call me crazy, but it doesn't look like the psx core was updated between 2.3 and 2.4 other than one tiny tiny thing: e3736bdaa7783475c27e0c633a11d9aacdccb002

**Comment by AleMastroianni** [comment]
That is exactly the reason i opened this thread. I personally suggested this other taser to switch from 2.3 to at least 2.4 cause it was impossible for us to keep collaborating on 2.3. I specifically picked 2.4.0 instead of .2 due to the psx core major update, but today he got this. Might have been different from the other kinds of desyncs that kept happening from 2.4.2 to 2.6. I cant really tell to be honest. Thats why i also included the tasproj

**Comment by nattthebear** [comment]
> Call me crazy

Ok, crazy.  Crazy crazy crazy.

Is this possibly a frontend issue then?  (Something something https://github.com/TASVideos/BizHawk/issues/2522 something something)

**Comment by AleMastroianni** [comment]
Got a desync on 2.6.1 without using TAStudio at all. Just playing with savestates on a .bk2 while recording it. 

Firmware: scph5501.bin
1 Memory card, 1 multitap, all 4 players on DualAnalog

![Immagine](https://user-images.githubusercontent.com/47687575/116232256-2b488400-a75a-11eb-8305-6fc7287c223a.png)

9A742438 CTR-NTSC-U.cue
Game: Crash Team Racing NTSC-U (PSX)

BK2: https://mega.nz/file/r4s1kYxb#HAtN-iYEAG7ACKiGzL8O9e1QVsTHBKE5gUlK0KAmg3Y

**Comment by zeromus** [comment]
That error message "the savestate input..." seems more like a problem in the movie infrastructure than a bug in the psx core

**Comment by InfamousKnight** [comment]
I am also facing a desync problem with this game:
http://tasvideos.org/userfiles/info/71073407737314605

BizHawk_devbuild_9ff4b904

Opengl backend.

using rewind.

It might be the opengl backend. I'll do another test with a game I had no
desync issues with gdi

**Comment by zeromus** [comment]
It's not the opengl backend. Don't waste your time testing that.  Better use of time would be finding some way to repro desync in first few seconds of bios or game (especially by messing around while the game is just beginning to boot)

**Comment by InfamousKnight** [comment]
Um, the desync occurs at the beginning of the first mission. Everything
before that syncs fine

**Comment by zeromus** [comment]
Can you create an exact script to reproduce this?
Like:
1. Delete save data
2. Boot game
3. At frame 10312, save the state
4. At frame 10400, load the state
5. At frame 10350 the game is visibly desynced

**Comment by InfamousKnight** [comment]
Ok, to consistently reproduce, delete saveram data if you have any for said
game.  In driver 2, go up to first mission in undercover, make a save state
once the in-game cutscene is finished, move around, load save state, move
around again. On playback, those inputs are dropped.

**Comment by zeromus** [comment]
define "inputs are dropped". Do you mean the inputs are MISSING ENTIRELY from playback, or they are just nonsensical inputs that yield no visual effect due to being desynced?

**Comment by InfamousKnight** [comment]
*bump* tried to reproduce with the steps above and it syncs fine now?

**Comment by InfamousKnight** [comment]
I'm talking the inputs were dropped after the save state was loaded. But
now I can't reproduce.. maybe its a save state before some message popup or
during in-game cutscene? Because i used rewind in the first movie and that
makes a save state almost every frame

**Comment by zeromus** [comment]
if inputs are dropped, then this isn't a desync, this is a bug in the tasing framework

**Comment by TizianoMattei** [comment]
This issue seem to be fixed. I've recently restarted TASing this game for extended periods of times and i have NOT encountered a single desync in 40000 frames from boot and 30k rerecords on TAStudio using 2.6.3 dev. It was probably a sequence of multiple desync issues (the dragging inputs one, then the autofire one, then the turbo throttle one) which now are all fixed.
