### ISSUE TITLE
Autofire main settings not working

### ISSUE THREAD

**Issue by AleMastroianni** [TASVideos/BizHawk#2599]
This issue is present from 2.4 to 2.6 as far as im aware. 

![1](https://user-images.githubusercontent.com/47687575/106295465-c5c72300-6250-11eb-9a8f-7df8f523e01b.png)
![2](https://user-images.githubusercontent.com/47687575/106295476-c8c21380-6250-11eb-886e-84a662f2f185.png)
![3](https://user-images.githubusercontent.com/47687575/106295794-2bb3aa80-6251-11eb-8f04-667dc97864c4.png)

Doesnt matter if one clicks on either "Ok" or "Cancel", or even changing the values, the setting just wont go in. 
Unfortunately, it is also buggy in TAStudio, as it skips 1 frame of inputs or adds 1, from time to time

In 2.3.0 both these features work; it also works in TAStudio when saving, by keeping the custom autofire configs: newer version doesnt seem to care about saving custom settings for autofire in the .tasproj itself.

I should mention about the 3rd issue, the skipping/adding 1 more input, that it might be present on 2.3.0 too, i didnt test that enough. The other 2 do work 100% on 2.3.0

**Comment by YoshiRulz** [comment]
`Config` > `Autofire...` *does* save if you click "OK", the OSD message is incorrectly shown.

**Comment by AleMastroianni** [comment]
> `Config` > `Autofire...` _does save_ if you click "OK", the OSD message is incorrectly shown.

It doesnt look like it, when i set from: "config --> autofire" (2 on and 2 off) and then in tastudio: "apply pattern to painted input" it still draws 1 on and 1 off in newer versions: am i missing something? Im sorry if thats the case 
The workaround for this of just using custom patterns from the settings inside tastudio doesnt save anymore either

**Comment by adelikat** [comment]
I believe TAStudio uses it's own patterns, in the tastudio menu.  Config -> Autofire isn't supposed to affect TAStudio, it is a casual gamer feature.
