### ISSUE TITLE
Graphical glitch in Atari 2600 Crystal Castles

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#260]
```
What steps will reproduce the problem?
1. Start the game
2.
3.

What is the expected output? What do you see instead?

Expected: game draws the first castle.  See second attachment for Stella 
emulation.
Seen: game draws first castle, there is also garbage lines in upper-left.  See 
first attachment for BizHawk emulation.

What version of the product are you using? On what operating system?
1.8.1, Windows 7 64-bit

Please provide any additional information below.
I do not believe this graphical glitch affects gameplay.

```

Original issue reported on code.google.com by `djk...@gmail.com` on 31 Aug 2014 at 4:29

Attachments:
* [Crystal Castles (1984) (Atari).2014-08-30 21.23.20.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-260/comment-0/Crystal Castles (1984) (Atari).2014-08-30 21.23.20.png)
* [Crystal Castles (1984) (Atari).png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-260/comment-0/Crystal Castles (1984) (Atari).png)

**Comment by hegyak** [comment]
Closed by the above Pull Request.
