### ISSUE TITLE
Setting brush colors with Lua isn't working correctly

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2602]
BizHawk version used: 2.6.0

I've tried anything that could possibly set a color. Any function of the `forms` library didn't work at all. `forms.drawBox` draws a box with the default colors, effectively ignoring any color argument I put in the function call. I've even gone as far as using `forms.getproperty` with the correct arguments provided by .NET documentation, yet nothing happened, not even errors.

I need to set custom colors, I don't care what kind of form controls, anything is good as long as I can display a custom color in my form.

**Comment by YoshiRulz** [comment]
Here's one way to use `Color`s:
```lua
local form_handle = forms.newform(200, 200, "My Amazing Form");
forms.setproperty(form_handle, "BackColor", "#FF007F7F");
```
Note that `forms.setproperty` *only* accepts strings formatted `#AARRGGBB` (I will be changing it to accept `Color`s made with `forms.createcolor` too).
https://github.com/TASVideos/BizHawk/blob/f76f3d7eed2045927131d1fed5dba54c7245e854/src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs#L1228-L1243

**Comment by ThunderAxe31** [comment]
Thank you for the response, however I found more issues that need to be fixed.

Despite the fact that your approach works for changing the form color, it didn't help for `pictureBox` controls. I've tried by using both `forms.createcolor` and `#AARRGGBB`, and I've tried all functions available:
`forms.setproperty` (with `"ForeColor"`, `"BackColor"`, `"Color"`, etc.)
`forms.setDefaultForegroundColor`
`forms.setDefaultBackgroundColor`
`forms.clear`

Also, using `forms.drawBox` ignores any color argument I give, regardless of using  `forms.createcolor` or `#AARRGGBB`.

> Note that `forms.setproperty` _only_ accepts strings formatted `#AARRGGBB` (I will be changing it to accept `Color`s made with `forms.createcolor` too).

This is not true. In the end I was able to a background color to a `label` control by using:
`forms.setproperty(my_label, "BackColor", forms.createcolor(255, 128, 0, 255))`

While instead using `#AARRGGBB` gave me the following error in the Lua console:
```
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_resume(lua_State* , Int32 )
   at BizHawk.Client.EmuHawk.Win32LuaLibraries.ResumeScript(LuaFile lf)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass61_1.<ResumeScripts>b__1()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)
```

Also, interestingly, setting a color to a label with the `forms.createcolor` allows to set any desired alpha value that gets correctly blended with the form background color, however if I set a `#AARRGGBB` background color to a form with any alpha value different than `FF`, I get the same error as above.

**Comment by YoshiRulz** [comment]
There is definitely some weirdness here, and I think it ties into #2098. If I pass an integer (as [documented](https://github.com/TASVideos/BizHawk/blob/fb03771bb7c92f35aa3bcd9af2551be1cc66bf8a/src/BizHawk.Client.Common/lua/LuaDocumentation.cs#L34) in the TASVideos wiki article) where we expect `Color?`, it's parsed correctly. But if I use a `Color` made with `forms.createcolor` it doesn't work, as you saw (same with hex strings, though contrary to the docs, those are only parsed by `forms.setproperty`). Here's my code:
```lua
--local cyan = forms.createcolor(0, 127, 127, 255); -- these DON'T work currently
--local red = forms.createcolor(255, 0, 0, 255);

--local cyan = "#FF007F7F"; -- nor do these, as expected
--local red = "#FFFF0000";

local cyan = 0xFF007F7F;
local red = 0xFFFF0000;

local form_handle = forms.newform(200, 200, "My Amazing Form");
local pb_handle = forms.pictureBox(form_handle, 20, 20, 100, 100);
forms.drawEllipse(pb_handle, 0, 0, 99, 99, red, cyan);
forms.refresh(pb_handle);
```
