### ISSUE TITLE
(SNES Hack Mother 2 Deluxe -- Version 2.00 ROM crashes emulator)

### ISSUE THREAD

**Issue by breaktube** [TASVideos/BizHawk#2609]
Hello there, I hope you all are well. 
I love the BizHawk emulator and it has been my go-to for a long while. 
Today I tried to run a hack of Earthbound (USA) 
Called "Mother 2 Deluxe" version 2.00  
Seems to crash the BizHawk emulator when you try to open and run the hacked ROM. 
The same way as 6MB SNES games (like Star Ocean for example). 
Did a checksum check and seems that everything was patched correctly 
Even runs just fine on other emulators. 
Asking the development team to take a look at this hack 
To see if it is possible to make it a compatible SNES game.  
Continue to stay safe out there and thanks in advance !

**Comment by YoshiRulz** [comment]
Which core were you using? If you switch cores with the `Config` > `Cores` > `SNES` menu, it might run correctly.

**Comment by breaktube** [comment]
@YoshiRulz  
Hello there, did not know about the "Cores" with this emulator ! 
Looks like mine is set to "Snes9x" 
When changing cores to either "Faust" or "BSNES" 
The hack loads just fine...guess the Snes9x-Core is not compatible with this SNES game.  
Big thanks with this !
Will try to play the game past the intro, with both cores, to see if there are any problems.

**Comment by Oggom** [comment]
>  The hack loads just fine...guess the Snes9x-Core is not compatible with this SNES game.

Fixed in the latest nightly builds https://github.com/snes9xgit/snes9x/commit/a146093e4e3750e934f9fb54fe306eed1a1258e8

**Comment by breaktube** [comment]
Thanks, sounds like the core was update to the lastest Snes9x nightly build ? 
Will check it out when I return home this evening. 

     On Tuesday, February 9, 2021, 08:29:27 PM CST, Oggom <notifications@github.com> wrote:  
 
 



The hack loads just fine...guess the Snes9x-Core is not compatible with this SNES game.


Fixed in the latest nightly builds snes9xgit/snes9x@a146093

**Comment by nattthebear** [comment]
No, that's an upstream fix only.  Bizhawk hasn't taken this change.

**Comment by breaktube** [comment]
Wait, so I would need to grab the "latest dev build" to apply these changes ?

**Comment by nattthebear** [comment]
_Bizhawk hasn't taken this change._  No build of BizHawk will have it.

**Comment by breaktube** [comment]
Ah, my mistake. 
So I will need to wait for the Bizhawk "Snes9x" core to be officially updated 
Before I can use it to play the game ?

**Comment by YoshiRulz** [comment]
You can go to #1374 and click "Subscribe" on the right to get notified when Snes9x is updated, assuming we ever get around to updating it. Though I'm not sure why you care given you were able to use Faust?

**Comment by breaktube** [comment]
@YoshiRulz   
Thanks, I have subscribed to the core-update discussion. 
BizHawk is my emulator of choice...might be a bit greedy of me to want it to stay as the best emulator around.
With that said, I have not contributed to the development of the updated "Snes9x-Core" 
But I do care that all of the BizHawk cores are updated to the latest versions 
So that the emulator can run the library of available games with the best compatibility possible. 
The team that has and continues to work on the BizHawk project are amazing ! 
It might be a selfish request, but it is encouraging to see the team keep this emulator at such a high level.
