### ISSUE TITLE
About PS2 How to open the game 

### ISSUE THREAD

**Issue by Tas-player** [TASVideos/BizHawk#2610]
I want to know if bizhawk supports PS2, whether or how to open the ISO game file of PS2, and whether or not to load the cue file like PS1

**Comment by Tas-player** [comment]
Drag and drop the game file directly into bizhawk. Although it is recognized, it is black screen

**Comment by YoshiRulz** [comment]
DobieStation is very much *experimental*. Getting games to run properly will be a challenge. You should use another emulator instead, such as PCSX2.
