### ISSUE TITLE
Couldn't increase speed of this game

### ISSUE THREAD

**Issue by EvanLei1** [TASVideos/BizHawk#2615]
### Summary
When I press the + or = button in my keyboard, it doesn't increase the speed. It was running at BizHawk 2.6.

### Repro
1. Press the + button to increase the speed.
2. Nothing happens.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6 Win 10 20H2

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Rebind the hotkey in `Config` > `Hotkeys...` > `General` (3rd column).

**Comment by zeromus** [comment]
user must expect the old default hotkey to work, but it was broken in 2.6
bind as @YoshiRulz says or download a new buildbot build

**Comment by EvanLei1** [comment]
I think **plus** is causing it to be mistaken with **equals**. Equals key works while plus don't, since it was in an exact key position.

**Comment by zeromus** [comment]
less thinking. more rebinding or downloading of buildbot builds.
