### ISSUE TITLE
Pokemon crystal

### ISSUE THREAD

**Issue by garterser** [TASVideos/BizHawk#2617]
when i open pokemon crystal i get this error message, i think it's reading it as a archive?

![10 02 2021_13 44 57_REC](https://user-images.githubusercontent.com/78876942/107563394-a3b19700-6ba6-11eb-9902-add52d616d62.png)

**Comment by TiKevin83** [comment]
duplicate of #2587

**Comment by zeromus** [comment]
use recent buildbot build
