### ISSUE TITLE
TAS view doesn't always refresh upon pausing

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#2621]
If you disable "Follow cursor", unpause, and emulate past the view, if you then pause with the muddle mouse button, the view won't fully refresh until you advance/rewind/edit input, even if you try scrolling down. You will not see where the playback cursor is, it will be beyond refreshed area. Pausing with mainform hotkey or with tastudio || button does refresh the view properly.

**Comment by YoshiRulz** [comment]
Fixed in d4dc260fc.
