### ISSUE TITLE
TAStudio state corruption

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2624]
repro steps:

1. load up an odyssey 2 game
2. open TAStudio and advance ~100 frames.
3. scroll back up and click on a frame ~10 (no inputs, just moving emulation back to that frame)
4. observe a lag frame appear before the frame you selected.

I have only noticed this with Odyssey 2, not other cores. It is obvious that the first variable in the state (in this case a bool variable for cpu IRQ enable) is corrupted on the state load but I have no idea why. The corruption goes away if I change the order things are saved in, for example if I save the frame count first (an int sized variable) the corruption does not occur. Normal savestates outside of TAStudio do not experience any corruption.

I narrowed down where this started to this commit : f4e98fd

The corruption did not happen before that. That's all I know.

**Comment by nattthebear** [comment]
> I narrowed down where this started to this commit : [f4e98fd](https://github.com/TASVideos/BizHawk/commit/f4e98fd9bd419dc71dc8bb25a74eac635ddd9afb)
> 

Ooof.  Yep, that's a nice commit.  I will look at this this weekend if no one beats me to the punch.

**Comment by nattthebear** [comment]
@alyosha-tas Please test again on 577987e3b4976fd.  (Do not merge this commit into master, as it's not a real fix but more a hack.)

**Comment by alyosha-tas** [comment]
Tested and cannot reproduce the original issue. Also tried some random inputs and brief TAStudio tests and everything seems to work.

**Comment by nattthebear** [comment]
13b7b43db65916f4287ebeffe6bd868f6206bc9e
