### ISSUE TITLE
Genesis Plus GX M68K BUS memory domain bug

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2625]
The M68K BUS memory domain is intended as a full memory. However, addresses from 0x400000 to 0xDFFFFF are unspecified while they actually do exist. This causes this space to be filled with 0xFF, which does not make any sense.
Offsets: https://wiki.megadrive.org/index.php?title=Main_68k_memory_map
![](https://user-images.githubusercontent.com/39802077/108346699-f5c66e00-71df-11eb-802b-916957272a3c.png)
![](https://user-images.githubusercontent.com/39802077/108346759-0676e400-71e0-11eb-8716-7078a0a6900c.png)

**Comment by nattthebear** [comment]
The bus here is a "peeker" not a "reader", so it won't do things with possible side effects.  What's our usual policy on this for memory domains with potential side effects on reads?

**Comment by getCursorsExe** [comment]
Yeah, but why it is a "peeker" instead of "reader"? This space is actually used by Expension Port, Z80 RAM, IO Registers, Z80 Control, and VDP Ports. Because the Z80 RAM comes from 0xA00000 to 0xA0FFFF, and Cartridge ROM and 68k RAM are visible here, then what is the purpose of using as a "peeker" instead of "reader"? There must be more memory domains otherwise!

**Comment by nattthebear** [comment]
I don't disagree, but possibly desyncing someone's TAS because they had the hex editor open at all is a bad user experience.  Let's see what the rest of the team says.

**Comment by getCursorsExe** [comment]
Well, restarting the entire TAS may fix this.

**Comment by zeromus** [comment]
"The M68K BUS memory domain is intended as a full memory of the ROM and RAM"
False. The M68K bus memory domain is intended as a full memory map, or at least as much of it as is addressible on the system.
Give some reason why you care what's there where the 0xFF are?
The problem of whether reading memory addresses can change them is a troublesome one, but does it apply here?

**Comment by getCursorsExe** [comment]
This space is actually used by Expension Port, Z80 RAM, IO Registers, Z80 Control, and VDP Ports.

**Comment by YoshiRulz** [comment]
Please don't delete comments, you can edit them to add ~~strikethough~~ for retractions. Please don't remove all relevant information from the issue title and description.

**Comment by getCursorsExe** [comment]
I don't know who did this.

**Comment by getCursorsExe** [comment]
This space is used by Expension Port, Z80 RAM, IO Registers, Z80 Control and VDP Registers, I would say this is a bug since there is no way it should be like this. That's over 9FFFFF empty space! So, Z80 RAM comes out of nowhere then?

**Comment by zeromus** [comment]
already supposed to be _where_?

**Comment by getCursorsExe** [comment]
https://wiki.megadrive.org/index.php?title=Main_68k_memory_map

**Comment by nattthebear** [comment]
> already suppossed to be _where_?

Please stop, this is entirely unproductive.  The question was clearly asked and it's clear what's going on in Bizhawk.  Some things aren't on the bus view because it would be more effort to put them there, and/or it might lead to nondeterministic reads.  We know what those things are, it can be seen in the source code.  We can change them if we want to.

**Comment by getCursorsExe** [comment]
This also happens in RAM Search too.

**Comment by zeromus** [comment]
This thread is garbage. Feel free to add a comment if and only if it actually addresses my questions
