### ISSUE TITLE
Suggestion: On first open of Bizhawk - remind about pre-req installer

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2628]
Just an idea, since it seems like a common pain point:

Bizhawk could have a simple flag in its config that causes it to remind the user to install the pre-reqs first. Then flip the flag after the message appears one time, so it only happens on first launch.

I don't think it would annoy users too much, and could potentially save some silly people trouble when they forget (like me).

**Comment by zeromus** [comment]
it already checks for the prereqs every time. I am disinclined to add noise for the rare case where someone's system is scrambled in such a state that our prereqs check passes and yet the prereqs arent actually satisfied, as in the majority of those cases the prereq installers don't repair it anyway. If you found such a case, please open a bug about that. if you have evidence it's a common pain point, please provide it so we can improve the prereqs checker.

**Comment by Meerkov** [comment]
https://github.com/TASVideos/BizHawk/search?q=is%3Aissue+is%3Aclosed+prereq&type=issues

For example : https://github.com/TASVideos/BizHawk/issues/2537

This was on a fresh system image. The pre-req checker didn't show up.

**Comment by zeromus** [comment]
46 closed issues. This is supposed to be compelling?
OK, that one should not have been closed

**Comment by Meerkov** [comment]
If it's not compelling that's OK. I just wanted to highlight that the pre-req installer seems to be a common pain point, as shown by the number of bugs people file (like me) who are confused and likely could avoid by a reminder.

Naturally, error catching would be better, but as mentioned in #2537, it doesn't seem like catching directX errors is within reach right now.

**Comment by zeromus** [comment]
6b6637f
Next move is yours.
