### ISSUE TITLE
TASStudio "Start from Savestate" Feature

### ISSUE THREAD

**Issue by Aurumaker72** [TASVideos/BizHawk#2629]
### Summary
Make TASStudio support starting from a savestate. As of 2.6.0 TASStudio afaik can only start from bootup and also clears eprom.

**Comment by Aurumaker72** [comment]
(This is a feature suggestion not a bug report)

**Comment by Spikestuff** [comment]
You're better off doing Start from Now/Savestate from the bk2 then loading up TAStudio.

**Comment by Aurumaker72** [comment]
> from the bk2 then loading up TAStudio.

TASStudio instantly resets core when launched and clears eprom

**Comment by YoshiRulz** [comment]
Try `File` > `Open` in TAStudio and load a `.bk2` which starts from a savestate.

**Comment by Spikestuff** [comment]
Please don't focus on half of what I wrote when I provided full context on what you should do.

Image version to what I meant:
1. I personally drop a save, just in case I somehow mess up the next bit.
![1](https://user-images.githubusercontent.com/12412764/108631110-850fa200-74bc-11eb-8687-b033a0add931.png)

2. File > Movie > Record Movie...
![2](https://user-images.githubusercontent.com/12412764/108631112-86d96580-74bc-11eb-8c57-347adeab8e6f.png)

3. Tools > TAStudio
![4](https://user-images.githubusercontent.com/12412764/108631115-880a9280-74bc-11eb-8249-b220d1026376.png)

4. Done.
![5](https://user-images.githubusercontent.com/12412764/108631116-88a32900-74bc-11eb-9091-4cad707c0e93.png)

**Comment by Aurumaker72** [comment]
It works but tbh when you just want to start from savestate why do you have to make movie for it. Seems hacky. Anyways,
