### ISSUE TITLE
GBA Emulator Errors - Robopon 2

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2635]
### Summary
GBA- Robopon 2 crashes or has other glitches.

Robopon has two versions (Ring and Cross) in multiple languages. All versions seem to have these glitches relating to menu use.

### Repro
https://youtu.be/I3j-8-11_YU?t=572
https://youtu.be/_WO5LBkfkWE?t=1091
Success Rate: 2 out of 2

1. Play Robopon 2
2. Get Sun and Ion batteries (though any combination might work)
3. Get a folder
4. Combine your Robopon (Notice that the menu icon is glitched)
5. Enter the Robopon menu
6. Select the robopon you just made
7. Game crashes

### Repro 2
https://youtu.be/Z2yZy-47kuU?t=445
Success Rate: 2 out of 2
1. Repeat steps 1-4 of the above repro steps.
2. Exit the menu instead of viewing your Robopon.
3. Find yourself stuck in a wall

(Note, the video fiddles with the menus a lot more, but this repro is consistent. It might be possible to trigger without creating a robopon, but I'm not sure).

### Host env.
- BizHawk 2.5.2; Win10
- Bizhawk 2.6.1; Win10

**Comment by YoshiRulz** [comment]
Does the same happen on upstream?

**Comment by Meerkov** [comment]
It reproduces on 2.6.2

Also I confirmed that the "get stuck in wall" is the same glitch. If you unpause instead of viewing the Robopon, then you get stuck in a wall instead of the game freezing. Updated the instructions above.

**Comment by YoshiRulz** [comment]
Wait, there is no 2.6.2, which build were you using? Please try mGBA upstream too.

**Comment by Meerkov** [comment]
Typo. 2.6.1

**Comment by Meerkov** [comment]
Tried on mGMA 0.8.4
Only partially reproduces.
1. When the Robopon is created, no image appears (it should)
2. When you view the Robopon from the stat screen, no image appears (it should)
3. You still have control (the game doesn't freeze as above)
4. The cursor icon is still busted (appears as a quarter circle)

![image](https://user-images.githubusercontent.com/8139496/108903891-aebaed00-75d2-11eb-95fb-447a99f171a3.png)

**Comment by Meerkov** [comment]
When I close the menu, I teleport into the wall. So I guess it's a full repro actually.

**Comment by CasualPokePlayer** [comment]
> ![image](https://user-images.githubusercontent.com/8139496/108903891-aebaed00-75d2-11eb-95fb-447a99f171a3.png)

The display bar is showing the title from the header rather than the no intro name, indicating this is a bad dump.

**Comment by Meerkov** [comment]
After reviewing the video playback, I was able to reproduce the Japanese issue. It looks like both issues are related to loating a sprite. Either the Robopon sprite, or the player's sprite within the menu.

I'm going to hypothesize that these roms are bad, even though one of them is labeled [!].

**Comment by Meerkov** [comment]
It looks like No Intro confirms that 8MB is the expected size. Thanks for the troubleshooting :)
