### ISSUE TITLE
The xbrz filter is very powerful, when can we use it? Preferably, you can bring it with you when installing the software.

### ISSUE THREAD

**Issue by kongmao45678** [TASVideos/BizHawk#2637]
The xbrz filter is very powerful, when can we use it? Preferably, you can bring it with you when installing the software. I hope I can support, thank you

**Comment by zeromus** [comment]
there are 1000s of shaders. we don't need feature requests for them. anyone interested in doing the work can create the shaders and put them in a PR. retroarch shaders work with very minor modifications.

**Comment by vadosnaprimer** [comment]
A potential solution has been posted on the forum (I haven't tried).
http://tasvideos.org/forum/viewtopic.php?p=507920#507920

@zeromus what do you think of shipping those includes if that fixes shaders without further hassle?

**Comment by zeromus** [comment]
I would love it if someone would prepare a suite of shaders that actually work and ship it with bizhawk. the only problem is that retroarch shaders do not work out of the box (they are some kind of junked up litter that utterly depends on accomodations made inside retroarch and details of how their shaders are processed by cgc or whatever) and so they all need repairing
