### ISSUE TITLE
2.6.1 Crash on startup 

### ISSUE THREAD

**Issue by Aurumaker72** [TASVideos/BizHawk#2638]
### Summary
2.6.1 crashes on startup with exception message
```System.MissingMethodException: Method not found: 'Void BizHawk.Client.Common.ApiContainer.Dispose()' at BizHawk.Client.EmuHawk.ApiManager.Restart(IEmulatorServiceProvider serviceProvider, IMainFormForApi mainForm, ```

### Repro
I replaced the exe in my Bizhawk folder and this happened. Do i need to completely nuke the config...?

**Comment by Aurumaker72** [comment]
Yep, this fixed it

**Comment by adelikat** [comment]
In general, you always need to nuke your config, there's no way we can keep it backwards compatible, and most releases have a breaking change.
