### ISSUE TITLE
TAStudios not saving branches on projects

### ISSUE THREAD

**Issue by lunjesse** [TASVideos/BizHawk#2640]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Making a branch in TAStudios does not get saved to the tasproj file, so it disappears on reload.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open up a ROM (I used GBA)
2. Open TAStudios
3. Add a new branch by clicking on the green + button
4. Save the project.
5. Reopen the project
Now the branch you made in step 3 is gone.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.1; Win10 Home; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by vadosnaprimer** [comment]
If you open your .tasproj in 7zip, do you see the Branches folder?

**Comment by Zimond47** [comment]
> If you open your .tasproj in 7zip, do you see the Branches folder?

Yes, all branches are saved in the branches folder.

**Comment by YoshiRulz** [comment]
@Zimond47 The question was directed at OP specifically. Unless that's your alt account?

**Comment by Zimond47** [comment]
> @Zimond47 The question was directed at OP specifically. Unless that's your alt account?

Uhm, no. sorry. I just thought I can answer this to help.

**Comment by YoshiRulz** [comment]
@ThunderAxe31 reproduced this. Does anyone know if 2.6 is affected or if it was only broken in the interim and 2.6.1?

**Comment by vadosnaprimer** [comment]
Bisected! It's caused by adca19c30a816c1627a7c436cc8776a918ba5f36

**Comment by Morilli** [comment]
@vadosnaprimer I am currently working on fixing this (wasn't expecting someone to pick up right now lol). I should have a fix ready in a couple minutes
