### ISSUE TITLE
BizHawk has memory leak issues from the moment it's launched

### ISSUE THREAD

**Issue by g0goTAS** [TASVideos/BizHawk#2646]
Watch video for evidence of this happening. From the moment that you launch BizHawk, it will be consuming more and more RAM as it remains open.
https://youtu.be/GIMo-3R2Mz4

Bug present on BizHawk 2.6.0. OS used is Windows 10.

**Comment by YoshiRulz** [comment]
We know. Last I checked, a lot of that gets freed when you switch roms.

**Comment by zeromus** [comment]
keep recording and watch it stop after having "leaked" 512MB, then check your rewinder settings
