### ISSUE TITLE
BizHawk 2.6.1 Audio Out-Of-Sync

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2647]
The entire audio output from BizHawk 2.6.1 is now probably out of sync. This actually did not happen to older ones. This is probably because BizHawk 2.6.1 completely changes audio output method.

**Comment by YoshiRulz** [comment]
..?

**Comment by zeromus** [comment]
user rebooted his computer

**Comment by getCursorsExe** [comment]
I don't know why I wrote this?
