### ISSUE TITLE
Find Save State History

### ISSUE THREAD

**Issue by Sir-Quack-III** [TASVideos/BizHawk#2648]
Is there any way to find the history of the save states you set? I accidentally overwritten one of mine.

**Comment by zeromus** [comment]
search your disk for your states (try searching for state, or for the name of the game). If there's a backup state (there will be by default) then it's RIGHT THERE. If you don't like that backup, then consider making backups yourself of important documents (or find out whether your operating system is set to do that by default or whether dropbox may have old versions in case you were running from there, or something like that).

**Comment by Sir-Quack-III** [comment]
@zeromus I found the state, but how do I load it?

**Comment by zeromus** [comment]
How long did you try before asking?
