### ISSUE TITLE
Dolphin core is planned to be in BizHawk!

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2653]
![image](https://user-images.githubusercontent.com/39802077/109773659-c102df80-7bff-11eb-8040-53346434aa53.png)

Does this error mean that Dolphin core is planned?

**Comment by zeromus** [comment]
no

**Comment by getCursorsExe** [comment]
I have no idea if this core is inaccurate, if yes, than what is the point of accepting TAS of Wii and GameCube games?

**Comment by YoshiRulz** [comment]
Dolphin is not coming to EmuHawk anytime soon, but it already has a rerecording-capable frontend, one that's tailored to the Wii and GameCube. One which is under active development.

Please go to [the Dolphin subforum](https://tasvideos.org/Forum/Subforum/34) on TASVideos if you want to discuss TASing with Dolphin.

**Comment by InfamousKnight** [comment]
Why do you want to use dolphin in bizhawk so bad?

**Comment by buruto** [comment]
So BizHawk cannot play neither GameCube nor Wii roms.
Am I correct?

**Comment by YoshiRulz** [comment]
The main branch including 2.9 RC2 cannot, but @CasualPokePlayer has forked BizHawk and added an experimental Dolphin port. You can read more about that [here](https://tasvideos.org/Forum/Topics/23347).

Also please don't do this for every system. The readme is up-to-date with the exception of MAME and TIC-80, which are new, and Satellaview, which is unfinished.

**Comment by buruto** [comment]
> 

I understand. Thank you.
