### ISSUE TITLE
[Gambatte] Upstream testrunner fails 13 tests for Bizhawk-Gambatte

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/BizHawk#2657]
I've done some [work](https://github.com/CasualPokePlayer/gambatte-speedrun/tree/bizhawk_tests) to get Gambatte's testrunner to be compatible with Bizhawk's Gambatte, and in doing so have uncovered 13 failures from the test suite. All tests pass upstream, so something is wrong within Bizhawk's fork.

![failures](https://user-images.githubusercontent.com/50538166/110275745-86de6880-7f86-11eb-88ec-069f57a4bd63.png)

**Comment by YoshiRulz** [comment]
Do the test cases differ between gambatte and gambatte-speedrun? If so, which are you comparing our fork to?

**Comment by CasualPokePlayer** [comment]
As in do the tests differ? No. The tests are identical.

If you mean the test results differ? Probably not. Gambatte-Speedrun (which should be considered upstream) passes all tests. Gambatte probably passes all the tests (the commit that made all the tests pass on Gambatte-Speedrun was just merging all changes Gambatte made in 2019), but I haven't verified that myself.
