### ISSUE TITLE
Loading a Mega-Tech Arcade ROM File causes "LoadLibrary" pointer to be "null"

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2661]
### Summary
The pointer in LoadLibrary is set to "null" if we attempt to load a Mega-Tech Arcade ROM file, which causes an exception in the ROMLoader. MAME is supposed to run Mega-Tech ROM files.
### Repro
1. Load a Mega-Tech Arcade ROM
2. You get this:

### Output
![image](https://user-images.githubusercontent.com/39802077/110633298-e1efa580-81a8-11eb-9f5c-e587892796b3.png)

### Host env.
BizHawk 2.6.1 x64 WIN

**Comment by Spikestuff** [comment]
> Host env.
> BizHawk 2.6.1 x64 WIN

You do realize that stable-Hawk (and build versions for that matter) doesn't actually support MAME right?
Only a [special specific version that actually supports](http://tasvideos.org/forum/viewtopic.php?t=21778) it.

Anyways, it runs on that special specific version:
![image](https://user-images.githubusercontent.com/12412764/110634396-03c74780-81fe-11eb-9121-a80aa29e18e0.png)

**Comment by Spikestuff** [comment]
Yes and it was also ported across early much like everything else that usually gets ported across early from DevBuilds to Hawk since this placeholder, cause that's what it is a placeholder has been in Hawk since 2.4.

Anyways "issue" is practically resolved this can be closed.

**Comment by getCursorsExe** [comment]
Probably that looks stupid, but the MAMEHawk is a dev build of BizHawk 2.4.0, then why a non-functionable feature is there? If it is here, then it is threated as an issue.

**Comment by Spikestuff** [comment]
It was never functional to begin with. I said it already, and I'll say it again. THIS IS A PLACHOLDER, IT HAS BEEN A PLACEHOLDER SINCE 2.4.

It was never part of BizHawk, and it was never part of DevBuild. It's on a specific version like I mentioned and the placeholder text was grabbed.

**Comment by getCursorsExe** [comment]
Yeah, It is a placeholder, but why is it even there? Who would ever implement a non-functionable feature at all!
