### ISSUE TITLE
(SNES) Disable H-DMA emulation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#267]
```
Just a simple thing, a option to disable the (SNES) H-DMA (HDMA) Layer, like 
the background layers.

Reason for that is, if TASing a game, H-DMA can make your viewfield smaller, in 
wich it can be annoying.

```

Original issue reported on code.google.com by `N3ui....@gmail.com` on 19 Sep 2014 at 12:34

**Comment by adelikat** [comment]
Can we just close this ticket since there's nothing we can do that specifically addresses this issue?

**Comment by vgturtle127** [comment]
@adelikat Also, and I could be wrong about this, but wouldn't disabling background layers in your emulator be kind of cheap anyway? Or is that a common thing in TAS?

I'm OK with closing this, it's ancient anyway.

**Comment by Asnivor** [comment]
so.... can we actually close this then?

@zeromus @adelikat
