### ISSUE TITLE
Emulation is on the UI Thread

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2673]
### Summary
Emulation is on the UI Thread. This means that if the emulator needs to hit disk for any reason, the program becomes unresponsive until the disk read is complete, which can take seconds.

### Repro
1. Load a large game, such as a PSX game, from an external harddrive
2. Play the game for some period of time, until the disk spins down (may take a few minutes)
3. When the emulator needs to read from disk to load a sound, image, level, video, etc... then, EmuHawk becomes unresponsive
4. Sounds repeat, and no menus can be used
5. The disk spins up
6. The read finally happens

### Result
The emulator is unresponsive for 10+ seconds, every couple of minutes.

### Expected Result
The user could still use the UI menus while the emulator is waiting on a disk read.

### Work Around
Copy the game to a SSD before starting the game.

### Host env.
- BizHawk 2.5.2; Win10
- External USB HDD

**Comment by zeromus** [comment]
By design. If it were otherwise, bizhawk would be an unstable hunk of junk.
