### ISSUE TITLE
BizHawk doesn't load PSX game into RAM

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2674]
### Summary
When you load a PSX game from an external HDD, bizhawk becomes unresponsive when loading new content, as it must hit disk.

### Repro
1. Load a PSX game from external hard drive
2. play for a while until the disk spins down
3. enter a new area, or load an fmv, sound, etc
4. Bizhawk becomes unresponsive
5. Sound repeats for 10+ seconds
6. Disk spins up
7. Bizhawk continues

### Expected Result
There is no reason to hit disk. The game can fit in RAM.

### Host env.
- BizHawk 2.5.2; Win10 ; 16 GB Ram
- External USB HDD
- PSX game size of ~500MB

### Additional Comments
If it's Working As Intended for emulation to be on the UI thread, then the bug is that the game isn't kept in RAM when it should be.

**Comment by zeromus** [comment]
This will not be "fixed". 
Reopen this as a feature request to add an OPTION to load CDs fully into memory

**Comment by Meerkov** [comment]
Can't you change it from a bug report to a feature request? I'm not sure I see the benefit of opening a third issue, but I'll do as you suggest.
