### ISSUE TITLE
Feature Request: Hotkey for recording mode in TAStudio

### ISSUE THREAD

**Issue by WarHippy** [TASVideos/BizHawk#2677]
There's currently no option to toggle Recording Mode in TAStudio as a global hotkey. I would like to be able to set this.
![Capture](https://user-images.githubusercontent.com/81324628/112413188-27a68500-8cf6-11eb-83e1-026acb3e67f9.PNG)

**Comment by vadosnaprimer** [comment]
![Безымянный](https://user-images.githubusercontent.com/7092625/112423782-55b2b600-8d44-11eb-9dad-1fcad130d96d.png)
