### ISSUE TITLE
Windows Build Instructions missing git requirement

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2679]
### Summary
The windows build instructions are missing steps.

### Repro
1. The user needs to install git. Even though the first step allows the user to download via .zip, the second step (QuickTestBuildAndPackage_Release.bat) requires git to be installed.
This is because fart runs `git --version  1>NUL`

A windows user that runs the bat by double-clicking will not see any errors, but nothing will happen.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk dev build at 370996875; Win10

**Comment by zeromus** [comment]
The instructions should be revised to separate "build the sln" builds which dont require git, from "build packages" builds which require git.
