### ISSUE TITLE
GBHawkLink not saving data

### ISSUE THREAD

**Issue by McW4v3-X** [TASVideos/BizHawk#2681]
### Summary
I loaded my 3P/4P xml of Pokémon Yellow, played for a while, and saved the game. When I loaded it, the data is gone. This is a problem for those who don't use the autosave feature. The only workaround right now is using the autosave feature and have it save every 5 seconds and when it's time to save the game, wait for 5 seconds after saving, then close, rename, reopen, reload, and voila!

### Repro
1. load a Gameboy game (i.e. Pokémon or F-1 Race)
2. open disk bundler
3. select GB3x or GB4x
4. choose individual games or click on current for each
5. name the xml file
6. click save and run
7. play the games
8. save each game
9. reload the game
10. try to load each saved game.

### Host env.
- BizHawk 2.6.1; Win10 Home 1903; Intel/NVIDIA

**Comment by McW4v3-X** [comment]
If you're unsure on renaming the file, find it in the SaveRAM folder in the appropriate system path, rename the file by deleting ".AutoSaveRAM" from the name.

**Comment by McW4v3-X** [comment]
Now GBHawkLink in general won't save since I updated my Windows 10. Can anyone comment on this issue?

**Comment by alyosha-tas** [comment]
Seems to work fine for me, I just tested pokemon in 4x.

Are you using File -> save RAM -> Flush Save RAM ?

**Comment by alyosha-tas** [comment]
Closing since I can't repro. and no response.
