### ISSUE TITLE
SNES core getting forced to "faust"

### ISSUE THREAD

**Issue by Morilli** [TASVideos/BizHawk#2690]
Happens after 6f47492d95c8f355a86da9000e451c43d828c329. Just open any rom and check the used snes core. Trying to change it doesn't do anything, and causes exceptions when opening a .tasproj file in TAStudio.

I was tempted to just revert this commit and make a pull request but I thought I'd rather ask about it.

I have no idea why this happens, but reverting this commit fixes all issues, so...

**Comment by adelikat** [comment]
@YoshiRulz : please fix, we can't release with a regression like this, and we really want a release for the .tasproj problem

**Comment by nattthebear** [comment]
This is heavily fucked, and seems to affect some other cores as well.
```
		public ControllerDefinition() => HapticsChannels.Add("Debug");
```

NO.  If the core does not want to present Haptics data, do not ask it to present Haptics data.

```
				foreach (var s in def.HapticsChannels)
				{
					string r = Allocate(s, ref plr, ref playerNext);
					ret.HapticsChannels.Add(r);
					feedbackRemaps[s] = r;
				}
```
NO.  `ControllerDefinitionMerger` is a special tool used internally in certain cores to handle player number remappings.  It has no general public API; it expects its data to come in in particular ways and go out in particular ways.  It does not know haptics.


Specifically, definitions sent to CDM are expected to start with a single digit followed by a string: "0Up", "0Down", etc, and that digit is used internally as a part of player number to port number reconciliation. There's a "Debug" in there now and nothing knows what the fuck to do with it.
