### ISSUE TITLE
Log Window is not thread safe

### ISSUE THREAD

**Issue by dgp1130** [TASVideos/BizHawk#2694]
### Summary

Using `Console.WriteLine("...");` from a backend thread and viewing it in Log Window causes the thread to crash. For example:

### Repro

1. Make a new external tool with at least this implementation:

```cs
public sealed class MyTool : Form, IExternalToolForm {
    // ...
    public void Restart() {
        Task.Run(() => {
            Console.WriteLine("Hello");
            Console.WriteLine("World");
        });
    }
}
```

2. Open BizHawk and click `View > Open Log Window...`.
3. Click `Tools > MyTool`.
4. Observe log window reads simply: "Hello"

You can also put a breakpoint on the two `Console.WriteLine("...")` statements. The first will trigger, but the second will not. If you view the thread in the Visual Studio threads window, it is listed as `<not available>`.

If you do the same thing with the Log Window **closed**, both statements will execute just fine.

### Host env.

- BizHawk 2.5.2; Win10

### Additional Info

I believe the root cause here is that Log Window [does not use a thread safe implementation for `Console.SetOut()`](https://github.com/TASVideos/BizHawk/blob/2.5.2/src/BizHawk.Client.EmuHawk/LogWindow.cs#L49). According the C# docs, the [`Console` class is thread-safe](https://docs.microsoft.com/en-us/dotnet/api/system.console?redirectedfrom=MSDN&view=net-5.0#thread-safety), so I think it's reasonable for devs to expect this to work. Unfortunately I'm not well-versed enough in C# threads to know the best fix, but I think we just need to marshal the input buffer to the main thread.

Aside from just breaking the code, it also is difficult and unintuitive to debug. I was expecting an exception of some kind but just never got one. The thread silently died without explanation.

**Comment by nattthebear** [comment]
I chewed someone out about this a while back, but there was no interest in fixing it.  The new console was so utterly worthless for other reasons that I certainly had no interest in fixing it.

When I'm working I usually build Bizhawk in debug mode, which has a different console that actually functions.  If I need to use release mode, I make a quick code mod to turn on the same console that debug mode uses.  Is that awful?  Of course.  Oh well.

**Comment by vadosnaprimer** [comment]
The title of this issue is what I concluded based on my experience with this new "debug console" and output my mamehawk core is sending to hawk, from threads via callbacks. It dies with IOException saying "invalid handle" and zero explanation what actually went wrong. Back when we were printing to VS output tab, everything was working perfectly. I forgot all the reasons why we ever had to switch to something else. Maybe @adelikat remembers?

**Comment by adelikat** [comment]
Do whatever you guys want to do

**Comment by YoshiRulz** [comment]
see also #2225

**Comment by vadosnaprimer** [comment]
I was sure logging to VS output tab was explicitly removed, but bisecting makes me think it was just lost in a mess of non-working commits?

![Безымянный](https://user-images.githubusercontent.com/7092625/117567202-b5320e80-b0c3-11eb-9112-26392b7730a8.png)

**Comment by YoshiRulz** [comment]
[`EmuHawk.csproj` in old format](https://github.com/TASVideos/BizHawk/blob/5a8349b5a59f607e0b2beee64733306ea7942d06/src/BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj) <-- go nuts with that, I see a `<UseVSHostingProcess/>` that might be relevant

**Comment by vadosnaprimer** [comment]
@dgp1130 can you try using `System.Diagnostics.Debug.WriteLine("...");` instead?

**Comment by vadosnaprimer** [comment]
> 
> 
> [`EmuHawk.csproj` in old format](https://github.com/TASVideos/BizHawk/blob/5a8349b5a59f607e0b2beee64733306ea7942d06/src/BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj) <-- go nuts with that, I see a `<UseVSHostingProcess/>` that might be relevant

That makes it print to Output tab, but the lines that were crashing the console now don't print anything, unless I change them to `Debug.WriteLine()`.

**Comment by nattthebear** [comment]
Let's not derail too much here; the original bug report is a very real, very broken behavior and it has absolutely nothing to do with some Visual Studio garbage.

**Comment by vadosnaprimer** [comment]
Fixed in https://github.com/TASVideos/BizHawk/commit/6f992e92e7b60957b02b7a0d3c6b61b06ea871a3 according to zeromus.
