### ISSUE TITLE
Consider re-adding accurate AssemblyVersion or AssemblyFileVersion information to generated binaries

### ISSUE THREAD

**Issue by Morilli** [TASVideos/BizHawk#2696]
Currently, the `EmuHawk.exe` and `Discohawk.exe` display their version like this when viewing detail in windows explorer, which isn't exactly descriptive of their actual version.
![image](https://user-images.githubusercontent.com/35152647/113459946-59ff6300-9417-11eb-91d8-a91720a34331.png)
Previously, this would (more or less lol) show their actual version, like here for `2.4.0`:
![image](https://user-images.githubusercontent.com/35152647/113459988-84512080-9417-11eb-952c-c405fd058510.png)

This affects all versions from 2.5+ (after ebd9645c1e7dbb55dc725014415b783115e4e7e8). I would consider finding a way to re-add this information here to make it easier to view Bizhawk's actual version without having to open it and look in the `About`  section to find the required info.

I tried to experiment with the code logic a bit and haven't found a good way that didn't break anything yet, so I'm just throwing this out here in form of an issue.

**Comment by YoshiRulz** [comment]
[relevant blog post](https://cezarypiatek.github.io/post/setting-assembly-and-package-metadata/)
