### ISSUE TITLE
[GBHawk] OAM DMA Bus Conflicts Incorrectly Emulated

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/BizHawk#2709]
When working on https://github.com/TASVideos/BizHawk/pull/2706 I was using a test rom to test the tracelogger. This happens to be [hell1.zip](https://github.com/TASVideos/BizHawk/files/6283662/hell1.zip) by Optix, which GBHawk fails due to always reading $FF during an OAM DMA bus conflict. The test shouldn't be executing any rst $38s due to this bus conflict. Gambatte passes this test fine to note.

**Comment by alyosha-tas** [comment]
Interesting, somehow I have never encountered this before. Will be a few weeks before I ca look into it, but thanks for posting.
