### ISSUE TITLE
Gameboy link does not work sometimes.

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#2711]
game example: panel action bingo.
reproduce:  start multihawk as dual gb eighter with gambattelink or gbhawklink cores.
what expected: menu option 2players should appear after restart.
what we get: no 2players option

probably games need to be powered up at the same time with link enabled to handshake properly. but in dual mode you cannot reset or power up emulation for some reason. you can only reboot the core which isnt work for link.

bgb link works just fine with this game but it has no cdl lol. 

btw. dualhawk link core crashes when cdl enabled   inside read function. something isnt initialized properly for that core.

**Comment by CasualPokePlayer** [comment]
You are actually able to restart emulation (non-reboot core)... it just requires TAStudio to do so... (which doing that fixes the issue).

Another workaround would be to boot one game in GBC mode and another in GB mode (assuming you are using an official BIOS here), which will boot up the games at different times.

**Comment by g0me3** [comment]
why i cant just have reset or power up buttons just like non linked core does? is it against some rules or maybe religiin i dont understand?

how can i use different cores in multihawk btw? where is the setting for each core? it seems i does not know how run it properly?

**Comment by CasualPokePlayer** [comment]
I don't know why Hard Reset is greyed out, somebody didn't bother implementing it? It works "fine" in TAStudio if you really need it (well, TAStudio has some weird issues with GambatteDual, unrelated to this really).


I'm pretty sure you can't use different cores, it's either two Gambatte instances or two/three/four GBHawk instances.

**Comment by g0me3** [comment]
there is a better workaround for now without using tasstudio.
there is a dedicated controller button "POWER" which function like hard reset/power on.
as soon as link itself work just fine and this is the game problem not to syncing exactly the same time then issue may be closed.
unless someone wanted to re-enable hotkeys for reset in dual mode ;)

**Comment by YoshiRulz** [comment]
MultiHawk doesn't exist anymore, workarounds are all you're going to get.

I did attempt to add the left- and right-hand console's Reset and Power buttons to the `Emulation` menu (automated for all cores ofc), but I couldn't get the weird WinForms collection type to behave.
