### ISSUE TITLE
Can't use bit.tobit function in lua

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#2714]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Can't use bit.tobit function in lua scripting.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
Just add this line in any lua script:
```
bit.tobit(number)
```

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
NLua.Exceptions.LuaScriptException: [string "main"]:134: attempt to call field 'tobit' (a nil value)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk dev build at e6c33e6; Win10 Home 1809; Intel/NVIDIA

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by vadosnaprimer** [comment]
Bizhawk already has `bit` library.

**Comment by Real96** [comment]
> Bizhawk already has `bit` library.

I checked it, but it seems that you can't use "bit.tobit" function. Am i wrong?

**Comment by vadosnaprimer** [comment]
Not available http://tasvideos.org/Bizhawk/LuaFunctions.html

**Comment by Real96** [comment]
> Not available http://tasvideos.org/Bizhawk/LuaFunctions.html

Maybe is better if i change the issue title

**Comment by YoshiRulz** [comment]
Our `bit` library is not the [Lua BitOp library](https://bitop.luajit.org/) or any of the other third-party options on [this page](http://lua-users.org/wiki/BitwiseOperators). It's our own, and you can't expect any random code you find to work for it.

In this case, a function like `bit.tobit` is unnecessary, as Lua's numbers are coerced to the correct .NET type (barring precision error) when calling back into our libraries. Just omit the call, or define a shim `bit.tobit = function(n) n end;`.

**Comment by Real96** [comment]
> Our `bit` library is not the [Lua BitOp library](https://bitop.luajit.org/) or any of the other third-party options on [this page](http://lua-users.org/wiki/BitwiseOperators). It's our own, and you can't expect any random code you find to work for it.
> 
> In this case, a function like `bit.tobit` is unnecessary, as Lua's numbers are coerced to the correct .NET type (barring precision error) when calling back into our libraries. Just omit the call, or define a shim `bit.tobit = function(n) n end;`.

Thanks!
