### ISSUE TITLE
[GBHawk] MBC3's RAM Gate register is incorrectly emulated

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/BizHawk#2715]
See https://github.com/CasualPokePlayer/test-roms/tree/ramg-mbc3-test (has real hardware result)

GBHawk result:
![ramg-mbc3-test 2021-04-13 17 56 29](https://user-images.githubusercontent.com/50538166/114639003-afdad300-9c81-11eb-9b53-f44ae1d4ce73.png)

The offending code is here: https://github.com/TASVideos/BizHawk/blob/84e195659c47fdf8b617777a1504efe5cffb169e/src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/Mappers/Mapper_MBC3.cs#L175

value & 0xA should be value & 0xF here.

Unrelated, but it seems like there is some open bus code going rouge here. I specifically wrote the test to do the potentially disabled SRAM reads from HRAM, to guarantee 0xFF is read instead of an open bus value. These open bus values don't even make sense, it seems to be putting writes onto the bus? (which I have an unpublished test using call which proves writes do not affect the bus that gets read, although I suppose this test also somewhat proves such too).

**Comment by alyosha-tas** [comment]
@CasualPokePlayer do you have a compiled version of this test?

**Comment by CasualPokePlayer** [comment]
[ramg-mbc3-test.zip](https://github.com/TASVideos/BizHawk/files/6496455/ramg-mbc3-test.zip)

**Comment by alyosha-tas** [comment]
Cool thanks, I'll fix this and leave the open bus stuff to the other issue.
