### ISSUE TITLE
FormatException at startup

### ISSUE THREAD

**Issue by SnkaeSael** [TASVideos/BizHawk#2716]
### Summary
When I try to run *EmuHawk.exe*, the application opens an exception window and doesn't allow the main window to open. Since I haven't found another person with the same bug, I cannot provide a reproduction guide.

### Output
```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Cyotek.Drawing.BitmapFont.BitmapFont.LoadXml(TextReader reader)
   at Cyotek.Drawing.BitmapFont.BitmapFont.LoadXml(Stream stream)
   at BizHawk.Bizware.BizwareGL.StringRenderer..ctor(IGL owner, Stream xml, Stream[] textures)
   at BizHawk.Client.EmuHawk.DisplayManager..ctor(Config config, IEmulator emulator, InputManager inputManager, IMovieSession movieSession, IGL gl, PresentationPanel presentationPanel, Func`1 getIsSecondaryThrottlingDisabled)
   at BizHawk.Client.EmuHawk.MainForm..ctor(Config config, IGL gl, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
Every version of BizHawk I've tried (nearly every version above 2.0); Windows 10 Home version 10.0.19042; Intel/NVIDIA

### Extra Info
I have all versions of Microsoft Visual C++ Redistributable installed and have rerun the prereq installer multiple times.

**Comment by zeromus** [comment]
This is caused by your using a non-english locale in your OS and cyotek being retarded and not using the invariant locale when parsing strings, but HOW IN THE WORLD DOESN'T THIS STRIKE 1000S OF USERS FOR HALF A DOZEN YEARS?

**Comment by SnkaeSael** [comment]
Is there a fix for this issue? I checked my system locale and it is set to English (Canada).

**Comment by zeromus** [comment]
well, you can change your number format in the globalization options to use this style: $1,234.56

**Comment by SnkaeSael** [comment]
Resetting the number formats to default fixed the issue. If any other people have this exact issue, go to Control Panel > Change date, time, or number formats > Additional Settings and press Reset. Since I have found the cause, I have also found a way to reproduce it: Go to Control Panel > Change date, time, or number formats > Additional Settings, then in the field next to *Negative sign symbol:* replace the hyphen with anything else (any letter, symbol that's not a hyphen), and attempt to launch *EmuHawk.exe. If no additional comments are necessary from contributors, this issue may be closed.

**Comment by nattthebear** [comment]
Weren't we going to fix the culture to US at all times on the C# side?  I feel like that was a thing.

**Comment by YoshiRulz** [comment]
Is it ours to fix? zeromus said the problem is in the `Cyotek.Drawing.BitmapFont` library. We could try updating that I guess.

**Comment by nattthebear** [comment]
It's always ours to fix.  This hasn't been the first nor the last time; .NET is notorious for this crap.  We don't support any real localization, so why not always use US culture?

**Comment by zeromus** [comment]
.net made a mistake by not defaulting to invariant culture. I will brook no debate on that subject. Unfortunately they can't fix it without breaking a lot of stuff, and might not have been convinced out of their idiocy by any contrariwise arguments. It falls on us to fix it by setting it globally for emuhawk. I do not fault a library for assuming invariant culture any more than I would fault the library for assuming nondeterministic behavior from a STRING PARSING FUNCTION, FOR CHRIST'S SAKE.

**Comment by zeromus** [comment]
Oops, I didn't mean to close that. I guess my emphatic conclusion convinced my brain to move the mouse cursor a few pixels to the left.

**Comment by YoshiRulz** [comment]
Pushed b7b10e263. @SnkaeSael Please try a [dev build](https://github.com/TASVideos/BizHawk#development-builds) with the system locale as it was initially.

**Comment by SnkaeSael** [comment]
Tried the latest dev build, same error.

**Comment by YoshiRulz** [comment]
Still affects latest version of upstream (2.0.1), so I opened cyotek/Cyotek.Drawing.BitmapFont#25. I changed BizwareGL to use 2.x for testing and was able to build with some warnings, I think mainly related to cyotek/Cyotek.Drawing.BitmapFont#22.

**Comment by zeromus** [comment]
just set the default locale on the process
