### ISSUE TITLE
Default input config for pce aka turbografx button 2 and 1 reversed 

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#2720]
Default input config for pce aka turbografx button 2 and 1 reversed 

i know i can remap it just pointing out that out of the box its backwards in case anyone cares

**Comment by nattthebear** [comment]
They look fine to me.

**Comment by jjfmz42015** [comment]
Xbox butoon a is mapped to 1 and b to 2.

to be like a read 2 button layout should be a to 2 and b to 1

**Comment by nattthebear** [comment]
Oh, xbox shit.  Yeah, seems like it's inconsistent, hopefully someone that uses that stuff can fix it.

**Comment by jjfmz42015** [comment]
Not a big deal. Custom mapping is there anyway. Was just showing.
