### ISSUE TITLE
[bug] A2600 Kaboom! Joypad isn't working

### ISSUE THREAD

**Issue by ViGadeomes** [TASVideos/BizHawk#2723]
Hello, I've tried to play to Kaboom! on the Atari 2600 ( SHA1 40D4DF4F8E4A69A299AE7678C17E72BEDEB70105 ) and everything work unless the joypad which do nothing. Referring to the game manual, you start the game pressing the B button, but there you start it pressing Right (then no matter if you press Right or Left, you won't move). I tested on 2.6, 2.6.1 and the dev version from today.
I didn't find this problem on another Atari 2600 game for the moment, all of them seem to work.

**Comment by adelikat** [comment]
Isn't that a paddle game?

**Comment by ViGadeomes** [comment]
hum yes sorry...
