### ISSUE TITLE
C64 memory callbacks

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#2726]
Doesn't look like they're implemented.

@alyosha-tas may I ask you to add them?

**Comment by alyosha-tas** [comment]
Yup I'll look at it

**Comment by alyosha-tas** [comment]
I implemented this.

Probably someone who actually uses these things should test before closing, I don't really know what the typical use case is.

**Comment by vadosnaprimer** [comment]
It works! Thanks!

The usecase is breakpoint simulation to figure out the PC I need to look at in the tracelog.

```lua
event.onmemorywrite(function() print(emu.getregisters()) end, 0xBABE
```
