### ISSUE TITLE
COMMON SHADERS .CGP DO NOT WORK

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2727]
.CGP common shaders all crash.

Or am I using the wrong shaders?

**Comment by jjfmz42015** [comment]
the included hq2x doesnt work properly easy to notice when used and compare to the emulator cores being used running hq2x outside of bizhawk

**Comment by zeromus** [comment]
cant compare without screenshots but I guess I don't care, either

**Comment by YoshiRulz** [comment]
CNR. Please use the issue template when reporting crashes, you haven't given us anything to go off of.

**Comment by jjfmz42015** [comment]
okj so bizhawk documents it can use the common shaders. 

it is able to load the bundled cgp file for hq2x. however if you go on github and download the latest common shaders pack bizhawk fails to load them. I can not find a version of bizhawk that wont fail.


if you try it instant error.


no looking for the lost city of atlantis here. the feature does not work period.

**Comment by YoshiRulz** [comment]
Repro'd with [this shader](https://github.com/libretro/common-shaders/blob/55e401834b732e62c34411321c4ffd82524345d4/hqx/hq2x.cgp) at 6dbe73d30. No promises that it'll get fixed.

**Comment by vadosnaprimer** [comment]
Making libretro shaders work would be insanely huge!

**Comment by jjfmz42015** [comment]
It just looked like a broken feature so i reported it.

**Comment by zeromus** [comment]
Which "documents" say it can use the common shaders? It should say it can use the common shaders, roughly, but that each shader will require adapting. Bizhawk cannot use retroarch shaders verbatim because they are generally a broken mess. This issue can be closed once the docs are fixed. We ALREADY have an hq2x shader PORTED FROM LIBRETRO so I have no idea why OP would be trying this, he seems generally very confused to me.

**Comment by jjfmz42015** [comment]
> Which "documents" say it can use the common shaders? It should say it can use the common shaders, roughly, but that each shader will require adapting. Bizhawk cannot use retroarch shaders verbatim because they are generally a broken mess. This issue can be closed once the docs are fixed. We ALREADY have an hq2x shader PORTED FROM LIBRETRO so I have no idea why OP would be trying this, he seems generally very confused to me.

You are an asshole. Close it and keep your shit mess of a front end
