### ISSUE TITLE
Bizhawk desync issue (Playback of a tas project is totally random)

### ISSUE THREAD

**Issue by SIREN87** [TASVideos/BizHawk#2738]
I am trying to do a tas of nes games.

i am using the latest bizhawk emulator (dev build) because the previous one had the same issue

Some games like punchout eg or batman run well. But the majority i have tried dont. Eg batman returns, batman return of joker, nightmare on elm street, battle of olympus etc

I have no clue why this is happening, since i changed zero stuff in options or anywhere else. Does bizhawk tas work with select games? If yes is there a list?

If this is indeed a bug what other info is needed? i even downloaded a firmware folder and put it in the appropriate folder in bizhawk thinking it might fix things

**Comment by YoshiRulz** [comment]
Are you making your own movies or importing them from TASVideos? There's no guarantee that imported FCEUX movies will sync.

**Comment by SIREN87** [comment]
No it is my own movies, also yes at some point i got asked something one was a) is faster b) is more accurate, i chose the more accurate option. If this was an error how can i rechoose it? It was asked only once. 

on another note i just tried battleship and no problems so i have no clue what might be going on. In theory all games on nes should be tasable correct?

**Comment by YoshiRulz** [comment]
If a game is playable then it shouldn't desync, but there are bigger, systematic problems in EmuHawk (#2522). It'd really help if you recorded your screen while TASing so we could see the last thing you did before a desync. If you're not able to, try recreating one of the desync'd movies without using TAStudio.

**Comment by SIREN87** [comment]
Ok here is a mega link until 4:45 is the recording of stage 1 battletoads. It is what i normaly do when i record, form 4:45 onwards i playback to see what is going on.if the file host is not good i can upload to another

https://mega.nz/file/OZpUSAYT#rKJYe5Osp4bVvjJA_GNgx1iXz5kHDp6_EBGsFZs1NX4

**Comment by SIREN87** [comment]
Adding a few more lines that might help or might be totally irrelevant (am not tech wiz like you guys)

1942 works fine. 1943 which is the sequel doesn't. 

Also tried burai fighter and the same thing happens. I then thought maybe the roms are faulty so i tried burai fighter on fceux another emulator with tas. There it works okay.  Let me know if i should also try that toads game. Have a good day all

**Comment by alyosha-tas** [comment]
What controls are you using to to do rewinding?

**Comment by SIREN87** [comment]
Hey Alyosha, sadly i deleted that run because even if i "fix" commands it still breaks the rest of the commands for some reason. But i have another run of 1943 that went haywire. 

https://mega.nz/file/nIhQzZxa#5dfAbUN5XpOgpcP8_i8BM-eZuWJRwDTWLajBuiaVLk0

If needed i can redo that battletoads game and post another link for checking. Basically its like this, some games work well, some others dont.

**Comment by alyosha-tas** [comment]
Thanks I'll look at that file.

So just to be clear you only used the mouse to control TAStudio? When making inputs do you use keyboard or a controller?

If you can record the screen like you did last time and make a new Battletoads file that would be a big help. It would be even better if you did it on the dev build: https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/39204720/artifacts

Make sure you don't change any settings besides changing the core to NEShawk, it's important to start with as clean a slate as possible.

**Comment by SIREN87** [comment]
Thats easy i already used the dev build because i had the same issues on previous stable? build. As for the core there was a question 1 is faster 2 is more accurate. I chose the more accurate but i dont remember if it was neshawk.

Yes inputs are only from mouse, and my controller is from the new xbox, either x or s? I think s not 100% sure. I will try to upload later one more battletoads project

**Comment by SIREN87** [comment]
Here is link with another run on the emulator from the link above. This time it didnt get past the first golden robot on the recording. 

https://mega.nz/file/7JQD3YYa#3tCizRtCPZ0KJ4dtoFkpOxxUMye1BJDP_9ikAd-twHo

**Comment by alyosha-tas** [comment]
can you add the movie file too?

**Comment by SIREN87** [comment]
https://mega.nz/file/iVZlEAQQ#DzLgSqANglZH9miX28aovnX8qgtNq7tjG6nZZeyuLGo

movie project of video above

**Comment by alyosha-tas** [comment]
Cool, finally a lead.

Integrity checker says something goes wrong when you start using autofire controls.

I personally never use auto fire controls so it makes sense I would never encounter desyncs assuming this is the cause.

Time to dig into auto fire and see what's going on.

**Comment by SIREN87** [comment]
Funny you mention that, i noticed that in rpevious build the autofire went like this
1b
2
3b
4
5b etc 

while in this interim it went 

1b
2b
3b
4b

I did use autofire in 1942 though and no problem with that game, tas worked fine. while in 1943 it didnt. Thats all the info that might help that i can think of right now. If i remember-notice anything else i will post

**Comment by Sonia-7** [comment]
Yes, it's definitely autofire. In fact, I was about to report this as well. I don't use the feature either but enabled it in a test movie just to check something, and a desync happened. Then I tested several other games and autofire desyncs them universally.

This bug started on 2.6 btw, 2.5.2 and below all work fine.

**Comment by alyosha-tas** [comment]
@Sonia-7 were you using a keyboard or controller for input when using autofire?

**Comment by Sonia-7** [comment]
@alyosha-tas Controller. I should also mention that this isn't TAStudio exclusive. Desyncs also happen just by recording a movie normally.

**Comment by alyosha-tas** [comment]
The flow of input through the movie code is pretty tough to follow, but I think I have a theory about what is causing this. Fortunately it's easy to check. Please try the following steps:

-Open a game and open TAStudio.
-Advance a few frames manually.
-Turn on Recording mode.
-Open the controller menu and hit save.

Then TAS as normal and check if any desyncs happen.

What seems to be happening is InputManager.ControllerOutput.Source is not being set properly. The convoluted steps above will set it properly since advancing frames manually latches movie input to the log and saving the controller menu latches ControllerOutput to movie output.

Fun fact: in SIREN87's movie, recording mode was turned on before any frames were advanced, so even though the controller menu was opened and saved, that was insufficient actually change anything relevent. Very conveniently (un)lucky!

**Comment by alyosha-tas** [comment]
Attempting to bisect, so far at e3f7519 autofire is already broken.

**Comment by alyosha-tas** [comment]
Ok, so the immediate cause of this is an order of operations error.

Autofire controllers rely on Frame counter from core to determine the autofire state. The problem with this is that some cores (e.x. NESHawk, GBHawk, Octoshock) increment Frame before execution. When the controller is polled, it polls the autofire controller which now sees an incremented frame and toggles the state (assuming one-on-one-off.) Unfortunately, input is latched to the movie file before frame advance, so it is latched with the pre-incremented value, hence a desync.

Controllers probably shouldn't be relying on core state, but I don't know what else to use. Moving Frame increment to the end of NESHawk does fix the problem.

Any thoughts here?

**Comment by YoshiRulz** [comment]
Can the `AutofireController` have a property for "current frame number" instead of reading from the `IEmulator`? Something like:
```csharp
public void LatchFromPhysical(IController controller, int frame)
{
	_frame = frame;
```
in [here](https://github.com/TASVideos/BizHawk/blob/bf9c6d784d5bcae718d6461e2d59ff04a73d843b/src/BizHawk.Client.Common/controllers/AutofireController.cs#L55-L57)

**Comment by nattthebear** [comment]
I support standardizing when cores increment Frame.  After emulation seems more natural to me.  Ideally nothing would rely on this, but that's life.

**Comment by alyosha-tas** [comment]
> 
> 
> Can the `AutofireController` have a property for "current frame number" instead of reading from the `IEmulator`? Something like:
> 
> ```cs
> public void LatchFromPhysical(IController controller, int frame)
> {
> 	_frame = frame;
> ```
> 
> in [here](https://github.com/TASVideos/BizHawk/blob/bf9c6d784d5bcae718d6461e2d59ff04a73d843b/src/BizHawk.Client.Common/controllers/AutofireController.cs#L55-L57)

Yeah seems like that would work, as long as LatchFromPhysical never becomes accessible to any external tools that can be called during a callback mid frame.

Probably still safer to just standardize Frame increment.

**Comment by alyosha-tas** [comment]
Alright fixed. @SIREN87 @Sonia-7 please re-test, re-open if needed.

**Comment by AleMastroianni** [comment]
@alyosha-tas I tested rn with the latest dev release, the desyncs still happen consistently with autofire

Recorded process: https://youtu.be/RG9IhpRMEBI

**Comment by Sonia-7** [comment]
@alyosha-tas Tested and it's indeed fixed now.

**Comment by YoshiRulz** [comment]
Possibly related issues:
- #2406
- #2452
- #2469
- #2485
