### ISSUE TITLE
Replicable desyncs on Bugs Bunny Lost in Time NTSC-U / PAL

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#2743]
I've recorded a clip of how to consistently replicate desyncs on this PSX game. It happened when manually tasing inputs without drawing, and playing with just the controller while recording a movie, not even opening tastudio. Also replicated without any turbo throttle and autofire setting. The movie never syncs. Same happens with a tas that starts from boot.

Video: 
https://www.youtube.com/watch?v=mW7lJuFTwO8

Desync TASproj i saved at the end of the video: https://mega.nz/file/zklnnQBb#nPLtnG2PPF8ctynRT3HflT72O9AT_k_tVBChKRQvxfk

Bizhawk version: 2.6.1

If any other kind of test or information to provide is needed, just tell me, i'll be happy to help

**Comment by AleMastroianni** [comment]
Upon further testing, i am not able anymore to replicate with autofire OFF. Still testing on 2.6.1. Using autofire almost guarantees an immediate desync in the movie

**Comment by nattthebear** [comment]
Thanks for investigating.  I'll call this a copy of https://github.com/TASVideos/BizHawk/issues/2738 then.

**Comment by AleMastroianni** [comment]
@nattthebear well i'll be damned, but upon further-further-further testing the issue doesnt seem to be connected to autofire. 

Recorded process#1(w/Autofire): https://youtu.be/RG9IhpRMEBI
Desync movie(bk2): https://mega.nz/file/3xk1VCYZ#JUSsjNo5RbZxuisLHtFNTm9a1kzXk4nNcyQ0dYDsV4E

Recorded process #2 (w/o Autofire): https://youtu.be/MmlESz50lgA
Desync movie#2(bk2): https://mega.nz/file/S1ly2SDK#C_qCXEjZxrjJNwHqxW-BsfHw_ys7amyA3sHujrRj0S0
Tasproj: https://mega.nz/file/341QGYTb#4KcRpks008LnZ5_IDs8FXeGkLcCOPVKikEBLMGtYW3U

These other 2 movies were on the latest dev build after the autofire issue got fixed. I also ran a savestate integrity check once more after i quit recording, after i had cleared savestates in the tasproj. The movie was desync/random in yet another way from the first desync. On this savestate integrity check after i cleared savestates, bad data was already from frame 0 to 1.


Desktop Specs: OS Win10, CPU Ryzen5 3600, GPU Nvidia 1660 Super, 16GB Ram, SSD Samsung Evo 860 1TB, Motherboard is MSI B450 Tomhawk MAX

Game is "Bugs Bunny Lost in Time" - PAL (PSX)

**Comment by TizianoMattei** [comment]
After the recent fix on turbo throttle, i cant get any more desyncs in this game using the same workflow

**Comment by alyosha-tas** [comment]
Good enough for me, thanks for testing.
