### ISSUE TITLE
BIZHAWK WIN 2.6.2 ABOUT LISTS BSNES 87 BUT NOT BSES 115 WHICH IS PRESET

### ISSUE THREAD

**Issue by Eggo-dotcom** [TASVideos/BizHawk#2755]
BIZHAWK WIN 2.6.2 ABOUT LISTS BSNES 87 BUT NOT BSES 115 WHICH IS PRESET AND ACCESSABLE.

**Comment by zeromus** [comment]
![redalert](https://user-images.githubusercontent.com/102701/119878862-a12a4180-bef8-11eb-9a67-f8a4be69cb3f.gif)

**Comment by Eggo-dotcom** [comment]
lol i know it is not a big deal, or super important, i assume it was a slight oversight, mentioned it only because I can see it being over looked for long that is all.

**Comment by YoshiRulz** [comment]
New BSNES is *experimental* after all.
