### ISSUE TITLE
Hex Editor window becomes unaccessible when reduced to icon

### ISSUE THREAD

**Issue by AleMastroianni** [TASVideos/BizHawk#2759]
### Summary
Opening hex editor with the option "stay on top"already enabled from a previous use, and then reducing it to icon, makes it disappear/unaccessibile. There is actually no way of re-opening hex editor with the exception of actually closing and re-opening the emulator.

### Repro

1. Enable "stay on top" on hex editor if unchecked, then close and reopen bizhawk.
2. Open any rom, then hex editor
3. Reduce it to icon
4. Hex editor disappears and cant be re-accessed even in other ways like trying to open it via ram search, using the "view adress on hex editor" feature

Happens on bizhawk 2.6.1 and 2.6.2 as far as i know, dunno about previous versions

**Comment by YoshiRulz** [comment]
CNR. Alt+Tab, Win+Tab, and hovering over the icon in the taskbar all work normally.

**Comment by AleMastroianni** [comment]
Interesting, this is quite odd.
I tried deleting the config.ini file aswell and replicating, and it indeed shows up from win+tab, and it will also appear on the taskbar AFTER doing that.

Not doing win+tab or alt+tab doesnt make it appear on taskbar or open it via ram search. 
Although i recall not being able to open it also via alt+tab, its not happening rn, but it seemed to happen when i had a lot of other tabs open with "stay on top".
Anyway, it doesnt show up to me on the bottom taskbar before win+tab, any idea why im getting this behaviour only with "stay on top"? Perhaps bizhawk is trying to reopen the tools specifically on the second monitor (which is a tablet, and isnt always connected to the pc, maybe "stay on top" gets oob?

Repro: https://www.youtube.com/watch?v=nn6KoxubzgA
This way as you can see it doesnt show up on the bottom taskbar.


I'll keep recording when i happen to re-use the tools in case i replicate the issue where hex editor isnt accessible from win+tab aswell.

**Comment by alyosha-tas** [comment]
Can reproduce as described. Also happens with trace logger and probably other tools using that setting.

The tools still show up normally when hitting 'task view' on the task bar next to the cortana icon, but otherwise are not visible.

**Comment by alyosha-tas** [comment]
This was broken in aa1de1c  (building everything with most recent SDK version)

Not sure exactly how or why yet.

**Comment by YoshiRulz** [comment]
Ugh I bet it's doing something stupid like caching the value of `Form.Text` immediately after the ctor.

I'm checking repro with static window titles.

**Comment by alyosha-tas** [comment]
Yeah, if I let the value of Text be settable in FormBase and give the tool a value for text in the designer, then the problem no longer occurs.
