### ISSUE TITLE
(Genesis) Editing System Stack crashes BizHawk

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2764]
![image](https://user-images.githubusercontent.com/39802077/120107408-362f7380-c161-11eb-9dd9-b46ecb3401c6.png)
BizHawk doesn't even know how to properly handle this in Sonic 1 Prototype. This is caused by incrementing by 1 in address FDFA. After a few frames at some point after triggering this, BizHawk crashes "again" in the same way as #1760, because we see a loading icon over my cursor even though nothing is even loading. Is there an explaination for this crash?

Occurs in 2.6.2 or less.

**Comment by YoshiRulz** [comment]
What happens when you do this on Genplus-gx standalone?

**Comment by getCursorsExe** [comment]
I can't do this, original Genesis Plus GX is exclusive to Nintendo Gamecube/Wii, and I don't know how to do the same thing in Libretro core.

**Comment by getCursorsExe** [comment]
It is unknown if it affects upstream.

**Comment by vadosnaprimer** [comment]
Try this (retroarch core) https://github.com/lab313ru/gpgx_debugger tho I couldn't find intructions in english.

**Comment by getCursorsExe** [comment]
These features such as VDP Register Debugger should be on BizHawk too.

**Comment by nattthebear** [comment]
If I'm reading this right you poked arbitrary memory and the game crashed?  Possibly the core because that's something no real game would ever do?

I don't see any real issue here.

**Comment by getCursorsExe** [comment]
Well, no. It doesn't happen on upstream

**Comment by getCursorsExe** [comment]
If you go to Special Stage in Sonic 1 Prototype and increment address FDFA, then at some point, we see some craziness and BizHawk crashes.

**Comment by getCursorsExe** [comment]
This is clearly an issue, because BizHawk crashes after messing with Sega Mega Drive's system stack.

**Comment by YoshiRulz** [comment]
Assuming this is a fatal error in GPGX' internals like #1760 was, recovering from it (i.e. showing an error dialog and returning to NullHawk) is not a good idea for technical reasons: see https://github.com/TASVideos/BizHawk/issues/1760#issuecomment-636516204. If upstream is unaffected then we probably just need to pull updates.

**Comment by getCursorsExe** [comment]
Similar crash also occurs in upstream, but we don't end up getting the same location as BizHawk that caused the crash, meaning that crash caused by messing with system stack only happens in BizHawk.

**Comment by zeromus** [comment]
doesn't matter. pushing emulators beyond the limits they were programmed for can cause any kind of wacky malfunction

**Comment by getCursorsExe** [comment]
Well, I managed to open EmuHawk in Microsoft Visual Studio 2019, I got this message after triggering the bug (sorry for Polish language):
`Program „[9296] EmuHawk262.exe” zakończył działanie z kodem -1073741819 (0xc0000005) 'Access violation'.`

**Comment by getCursorsExe** [comment]
Wait, what? What BizHawk was trying to access!?

**Comment by zeromus** [comment]
Memory outside the allocated range. Which is _exactly what you did_. If an emulator crashes when you hack or debug a rom, then stop debugging or hacking the rom. We're not interested in bug reports or discussions about this. Stop posting about it or I'll lock the thread to force you to stop.

**Comment by getCursorsExe** [comment]
Okay, I will shut my mouth.
