### ISSUE TITLE
Changing cores while Debugger window is open causes BizHawk Corruption and also corrupts .NET Framework as well (2.6.2)

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2766]
### Summary
The "Debugger" window is completely broken. Changing cores completely corrupts BizHawk while "Debugger" window is active. BizHawk doesn't even know what to do and even affects .NET Framework as well. In this case I managed to switch cores from Mupen64Plus to Genplus-gx while Debugger is open, and BizHawk is in a glitched state. In this state, frame counter and lag counter is frozen, the sound is gone, and the core is invaild. BizHawk is also very vulnerable to crashes as well. Through error message checking, I see that the version of .NET Framework is 64-bit v4.0.30319.
![image](https://user-images.githubusercontent.com/39802077/120209050-80325b00-c22e-11eb-9943-9522502e94ef.png)
You see what is wrong? It says that I'm using the wrong core.
### Repro

1. Open any ROM (I used Paper Mario 64 and Sonic 1 Prototype to trigger this bug)
2. Open Debugger, and then open different ROM while previous was open, make sure you switch from Mupen64Plus to Genplus-gx.
3. BizHawk will become completely corrupted.

### Output
```
System.ArgumentOutOfRangeException: Określony argument jest spoza zakresu prawidłowych wartości.
   w BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.<SetMemoryDomains>b__103_0(Int64 addr)
   w BizHawk.Emulation.Common.MemoryDomain.PeekUshort(Int64 addr, Boolean bigEndian)
   w BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.<>c__DisplayClass61_0.<Disassemble>b__0(Int32 a)
   w BizHawk.Emulation.Cores.Components.M68000.MC68000.Disassemble(Int32 pc)
   w BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.Disassemble(MemoryDomain m, UInt32 addr, Int32& length)
   w BizHawk.Client.EmuHawk.GenericDebugger.Disassemble()
   w BizHawk.Client.EmuHawk.GenericDebugger.UpdateDisassembler()
   w BizHawk.Client.EmuHawk.GenericDebugger.EngageDebugger()
   w BizHawk.Client.EmuHawk.ToolManager.Restart(Config config, IEmulator emulator, IGameInfo game)
   w BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   w BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   w BizHawk.Client.EmuHawk.MainForm.LoadRomFromRecent(String rom)
   w System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   w System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   w System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ToolStrip.WndProc(Message& m)
   w System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Another error occured when I minimized it:
```
System.ArgumentOutOfRangeException: range end < start
Nazwa parametru: endInclusive
Rzeczywista wartość to -1.
   w BizHawk.Common.MutableRange`1.Overwrite(T start, T endInclusive)
   w BizHawk.Client.EmuHawk.InputRoll.IsVisible(Int32 index)
   w BizHawk.Client.EmuHawk.InputRoll.set_RowCount(Int32 value)
   w BizHawk.Client.EmuHawk.GenericDebugger.DisassemblerView_SizeChanged(Object sender, EventArgs e)
   w System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   w System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   w System.Windows.Forms.Control.UpdateBounds()
   w System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
### Host env.
BizHawk 2.6.2, Windows 10 64-bit
.NET Framework 64-bit v4.0.30319

**Comment by YoshiRulz** [comment]
Possibly fixed by 28fe92198, try a dev build.

**Comment by getCursorsExe** [comment]
No, it is still there.

**Comment by alyosha-tas** [comment]
Looks like the disassembly view isn't updated properly when changing cores, I'll take a look at it.

**Comment by AleMastroianni** [comment]
I tried switching from GBA to PSX with debugger open on dev the newest dev release, it did crash but without error dialogs

**Comment by alyosha-tas** [comment]
I'm not getting any crashes, even with GPGX, but I'm definitely getting some invalid looking disassemblies. Could be dependent on what addresses are present when the core is switched? Not sure yet.

**Comment by getCursorsExe** [comment]
Do you need to use in-game cheats and then do it? Or install the same version of .NET Framework?

**Comment by getCursorsExe** [comment]
It is unknown what caused this corruption to happen, but I think that this has to do with the way how Visual Studio works on my system.

**Comment by getCursorsExe** [comment]
Meaning this only happens on some PCs, like mine.

**Comment by getCursorsExe** [comment]
And the results might be different.

**Comment by alyosha-tas** [comment]
Ok, changing from GBA to any other core with debugger open definitely crashes for me.

**Comment by alyosha-tas** [comment]
So the problem here is with breakpoints. Changing ROMs in any core if you have an active breakpoint in debugger causes a crash.

Some cores (like mGBA) start with a default breakpoint for some reason that I don't understand. It is made in GenerateUI(). So in this case you don't even need to add any breakpoints yourself to get a crash.

It looks like breakpoints are cleared after the core is disposed, so the associated memory can't be accessed anymore.

I can just restart the debugger if it's loaded easy enough, but what are those weird breakpoints that pop up? @nattthebear do you know? Why does it only appear for certain cores?

**Comment by nattthebear** [comment]
No idea, I'm not much involved with the debuggers.  This does sound like the classic reuse of resources after disposal.  Anything on an unmanaged core that touches the unmanaged resources will flat out fail after the core is disposed.

**Comment by alyosha-tas** [comment]
Ok then, at any rate this should be fixed now. @getCursorsExe please test dev build.

**Comment by getCursorsExe** [comment]
It is fixed in the dev build. Finally!

**Comment by getCursorsExe** [comment]
Here are the results when I opened it with Microsoft Visual Studio 2019:
![image](https://user-images.githubusercontent.com/39802077/121958280-cbd32180-cd63-11eb-8bf1-ae26713b940f.png)

**Comment by YoshiRulz** [comment]
Is that from building c5e6aadb0? It looks like you've got the source for 2.6.2, but the fix for this crash was made after that.
