### ISSUE TITLE
Gen plus gc default settings issue

### ISSUE THREAD

**Issue by Eggo-dotcom** [TASVideos/BizHawk#2775]
Default settings with 6 button pad.

result some game unplayable need to switch to 3 button.

if you want a example try playing me pac man in default 6 button mode.

this problem also exists on real hardware.

Put default to 3 button test again perfect control.

Why have a default that breaks games?

**Comment by Spikestuff** [comment]
Then you run into the issue of 6 button games not being playable.
What's wrong with just changing it yourself?
Spoilers: There isn't any.

This is a non-issue.

**Comment by Eggo-dotcom** [comment]
Lol no.

100% of the commercial library supports the 3 button controller. Approx 5% break with the 6 button. It is only logical to want the most compatible as default and optional enhancement when enhanced can break things.

clearly you dont know much about the megadrive or genesis with that stupid comment

**Comment by nattthebear** [comment]
> Why have a default that breaks games?

I foresaw that you would have supreme knowledge of all things Genesis related and would be smart enough to change the setting as needed for yourself.

**Comment by Eggo-dotcom** [comment]
> > Why have a default that breaks games?
> 
> I foresaw that you would have supreme knowledge of all things Genesis related and would be smart enough to change the setting as needed for yourself.

My comment was at someone calling an issue a non issue. Doesnt matter, i can change myself
