### ISSUE TITLE
Turbo while Botting doesnt work - Basic Bot

### ISSUE THREAD

**Issue by AleMastroianni** [TASVideos/BizHawk#2776]
### Summary
The check enable on default "turbo while botting" on basic bot doesnt work.
There also seem to be issues when using basic bot in a movie outside tastudio, but given the bugs with "record from now" that currently exist, i havent recorded a repro of the issues outside tastudio for this instance.

### Repro
1. Open a tastudio project that starts from boot
2. Open basic bot
3. Create branch 0
4. Set basic bot input conditions and such
5. Enable Turbo while botting (under Options, its checked by default iirc)
6. Click run
7. Basic bot wont register inputs both with and without recording mode being checked

To be able to run basic bot in a tastudio project that starts from boot, "recording mode" has to be checked, in a "record from now" bk2 to .tasproj, recording mode does not need to be checked, and will run the bot for 1 time only. Following attempts to give inputs from the bot will have no effect, despite seeing the inputs being actually given from bizhawk feature View-->Display input

Video repro: https://www.youtube.com/watch?v=OWmQDwQT5tI

**Comment by alyosha-tas** [comment]
Has there ever been a release build where basic bot actually works as intended? I've never used it and don't really know what I should be expecting.

**Comment by AleMastroianni** [comment]
I remember trying it out on 2.4.2 but i didnt really "use" it cause in that instance i needed analog inputs which arent supported in Basic bot.

I just checked right now to be sure, basic bot DOES work properly in 2.4.2 having turbo while botting enabled on default, whereas in 2.6.1 it just seems to write inputs and delete them immediately as if the bot is running 1 frame earlier than its supposed to (since it requires recording mode to write inputs by itself), so tastudio just deletes them as the tasproj goes on

**Comment by alyosha-tas** [comment]
I tried to reproduce this in dev build, but everything seems to be working fine. Turbo works as expected (sometimes it might not be noticable though, if BizHawk is already going as fast as it can, having TAStudio and basic bot running slows things down a lot.)

I also didn't see inputs being overridden as in that video.

@AleMastroianni please test in dev build, preferably with a simple NES game of some sort if you can.

**Comment by alyosha-tas** [comment]
closing as I can't repro. and no response.

**Comment by AleMastroianni** [comment]
Uh, apologies, somehow i had completely forgotten about this, i stopped tasing at this point so i didnt get the chance to look for a NES game (never played NES so i didnt own any copy personally) 
I checked rn with a couple of games and everything looked fine and stable as far as i could tell, even tho thats not the case for psx games obviusly
