### ISSUE TITLE
TAStudio: Column->Show Player # doesnt work properly

### ISSUE THREAD

**Issue by AleMastroianni** [TASVideos/BizHawk#2779]
### Summary
Apparently tastudio doesnt enable/disable inputs from players properly on his own timeline when there are 4 players enabled (didnt test with 3). I recall it working with 2 players in the past though.
Putting the check on X or Y doesnt seem to work, and it gets re-enabled by also messing around with other player #. (So changing show player 3 and changing the check on inputs, affects and switches the checks on player 4, for example)

### Repro
1. Open bizhawk
2. Open tastudio having 4 players enabled
3. Just use the show player # tab and enable/disable inputs, they mix up with other player # aswell that shouldnt affected
4. Notice that it has no affect on tastudio timeline or if it does, its inconsistent for some reason, meaning it works only on some inputs to display or not on the timeline tab.

Short video repro, as there are multiple things that shouldnt happen with this issue, it makes it a bit easier to understand: https://www.youtube.com/watch?v=tNNQexZ96yk

Edit: tested on 2.6.2 and 2.6.1, forgot to mention that as i generally just use the latest public released version

**Comment by alyosha-tas** [comment]
so the 'show #' button is just toggling the visibility state of all the buttons, instead of acting as a master visibility indicator, should be easy enough to fix.

I can't recreate any issue with the wrong player buttons being effected.

Also, videos are helpful but please slow down your actions in them.

**Comment by AleMastroianni** [comment]
Oh, my bad, you're absolutely right. Will keep that in mind if i happen to record other issues!

**Comment by alyosha-tas** [comment]
I think ideally here the "Show Player #' button would act as the master control for showing a player controller, and the drop down menu should represent which buttons on that control you want to see when it is active. Kind of like 'button visible = 'master visible' & 'button checked'

At the moment though, there is no underlying state to preserve that would allow this to happen, the  master control just toggles the check status of each button. 

I can at least make the operation more intuitive by making it a simple on/off,

**Comment by YoshiRulz** [comment]
see also #2449
