### ISSUE TITLE
Something is wrong with Genesis ROMs...

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2789]
### Summary
Genesis Plus GX is a pretty accurate- wait, excuse me.

![image](https://user-images.githubusercontent.com/39802077/121339170-80151800-c91e-11eb-9b64-07cda3c15d62.png)

No idea why, but it doesn't make any sense.
### Repro
1. Just open TiTAN MD-NICCC ROM, and you see this message.

### Host env.
BizHawk 2.6.2 Win10

**Comment by Eggo-dotcom** [comment]
try Blastem.

Using 0.63 via retroarch here no crashing save states work. CRT shader is an added treat. (Genesis needs this due to using dithering for fake transparencies ie: shinobi 3 stage 2)

**Comment by getCursorsExe** [comment]
It does say that it has Z80 accuracy issues, even though I don't see any. Is this because Genesis Plus GX has a different emulation than BlastEm?

**Comment by getCursorsExe** [comment]
I messed with File Extensions options to force load it with PicoDrive Core (normally for 32X), and it clearly bypasses it and audio freezes after 333 frames.

**Comment by Eggo-dotcom** [comment]
Blastem and Genesis plus share no code.

Genesis plus GX is a great emulator but its old code with many tricks with that has seen many hands patching with more tricks and methods and has horrible timing.


This being said its a great emulator but when it comes to timing and accuracy these things are non existent there.


That also being said its the most popular genesis emulator.

Blastem by 0.63pre has come a long way. be hard pressed to find a game pad based game or demo that wont run accurately on it.

Blastem only looks bad on very weak hardware now, by todays standards very very weak hardware.


This is why I initially thought BizHawk could use the core as a fall back option,

**Comment by getCursorsExe** [comment]
Dude, BlastEm can be waterboxed, and we need to check it first in dev build.

**Comment by Eggo-dotcom** [comment]
thats another thing they should add, core over ride to picodrive, just cause its possible and its a core that can do it.


HOWEVER Genesis Plus GX for regular Genesis/MD games is the best way to go.

I also still thing default needs to be fixed on bizhawk genesis to 3 button. 100% of the commercial library works with 3 button pads <2% fail with 6 button even on real hardware. Default settings should always aim at compatible out of the box let user mess it up after if they want, this is backwards

**Comment by Eggo-dotcom** [comment]
> Dude, BlastEm can be waterboxed, and we need to check it first in dev build.

That was my suggestion I know

**Comment by nattthebear** [comment]
There's already an open issue for blastem integration.

Closing this as there's nothing actionable here:  As has been established many times, gpgx's homebrew compat is not great, and its accuracy is not great.  We won't be rewriting gpgx.
