### ISSUE TITLE
NDS Ultimate Mortal Kombat, swapped screen when on character select and during a fight

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#2793]
### Summary
When you get to the character select screen or in a fight, the screen are swapped. On every other screen, the screen display the right thing. The Puzzle Kombat mode do not have this problem

### Host env.
- BizHawk 2.6; Win10 Pro 19042; Intel/Nvidia

[//]: # "(screenshots, if applicable)"

![YUTEv00 2021-06-10 20 26 18](https://user-images.githubusercontent.com/24578279/121613399-5cd78f00-ca2a-11eb-8345-db01cb02704f.png)

![20210610_202555](https://user-images.githubusercontent.com/24578279/121613403-606b1600-ca2a-11eb-8f7d-d7ff37bab2b0.jpg)

**Comment by YoshiRulz** [comment]
Does this affect upstream?

**Comment by Glitcholog** [comment]
Im not sure what you mean, how can I check that?

**Comment by YoshiRulz** [comment]
What happens when you play this game on melonDS standalone?

**Comment by Glitcholog** [comment]
Thanks for the clarification!

Using Melon DS, the problem is the same, so im guessing that Melon DS itself need to fix the bug

Ive also noticed that corner infinite combo ( which is as simple as spamming the low punch or high punch in a corner) does not work on Melon DS, but work on a real Nintendo DS and Nintendo New 3DS

**Comment by Glitcholog** [comment]
I've also asked on the github of Melon DS about the issue, just to give a quick update.

**Comment by Glitcholog** [comment]
turns out that it was an option ive changed when I bought the game... almost 15 years ago.

While still minor, Im still trying to figure out why you can't do infinite on emulation (not that it is a so important feature, its just for accuracy)

**Comment by YoshiRulz** [comment]
Ah! We're all good then. Remember to close the other issue too :)

**Comment by Glitcholog** [comment]
thanks you! will do for the next issues!
