### ISSUE TITLE
[GB] Terminator 2: Judgment Day Bizhawk Illegal Path error

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#2802]
### Summary
Opening my personnal dump of Terminator 2: Judgment Day cause an illegal path error, despite all my other games working, which are in the same folder (some of them have many spaces in it). Even renaming the game simply as "Terminator" won't do it. Regular rom doesn't work either.

Both rom work perfectly on VBA, including when i rename it with a name with spaces
### Host env.
- BizHawk 2.6.0; Win10 Pro Lastest update;

Screenshot

![illegal](https://user-images.githubusercontent.com/24578279/122317947-50e94280-ceec-11eb-89f3-ee9e2f2766c0.PNG)

**Comment by YoshiRulz** [comment]
Duplicate of #2587. Update to 2.6.2.

**Comment by Glitcholog** [comment]
thanks you, I thought it was an isolated case and not something related to that big one. All good now!
