### ISSUE TITLE
Issue with file writing using lua + lua interface

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2810]
Repro steps:

1. Record a NES movie for ~50 frrames or so (to garauntee some inputs are polled) while holding up + left.
2. pause the emulator, load the movie, then load this lua script: http://tasvideos.org/userfiles/info/72245967815748003
3. replay the movie, then close the emulator when movie is finished and open the resulting timestamps.r08 file.
4. For some inexplicable reason, up + left, which should be converted to 0A in the file, is converted to 0D 0A

This doesn't happen with nlua + kopilua, and it also doesn't happen when not using an event callback, and it only seems to be an issue for up + left (which is equivalent to 10 when sent to string.char() in the lua script.)

Very strange. Maybe lua + lua interface should not be the default.

**Comment by nattthebear** [comment]
> 0A in the file, is converted to 0D 0A

```
LINE ENDINGS
I
N
E

E
N
D
I
N
G
S
```

Doesn't lua have some way to open that shit in binary mode?

**Comment by Morilli** [comment]
`local timestamps = io.open("timestamps.r08", "w")`
No idea about lua but this should probably be a `wb`

**Comment by vadosnaprimer** [comment]
Correct https://github.com/TASVideos/fceux/issues/337

**Comment by alyosha-tas** [comment]
oh, ok , kind of strange it works with kopi lua then
