### ISSUE TITLE
SMSHawk does not preserve aspect ratio when "Expand pixels by integers only" is enabled

### ISSUE THREAD

**Issue by emu-hopeless** [TASVideos/BizHawk#2815]
I don't believe this is by design, not only because the aspect ratio that results after enabling the setting is incorrect (and inconsistent between windowed and fullscreen modes), but also because Genplus-gx seems to have no issues retaining the proper aspect ratio with the same setting checked.

The two attached screenshots show what the output looks like with and without "Expand pixels by integers only" checked, respectively. In both cases, the aspect ratio is set to "Use system's recommendation".

![no_integer_scaling](https://user-images.githubusercontent.com/86317528/122975420-ef482e80-d358-11eb-9216-5601dd844798.png)
![integer_scaling](https://user-images.githubusercontent.com/86317528/122975419-ef482e80-d358-11eb-894b-5cb15800a343.png)

**Comment by EZGames69** [comment]
What happens if you enable overscan?

**Comment by emu-hopeless** [comment]
With overscan enabled, I get the same aspect ratio whether or not I have "Expand pixels by integers only" on, but it's the narrower aspect ratio instead of the one that I understand is "right". 

![overscan](https://user-images.githubusercontent.com/86317528/122979077-c164e900-d35c-11eb-9159-8ca292429bb5.png)

**Comment by emu-hopeless** [comment]
Setting the aspect ratio to "Use custom AR: 4:3" with overscan enabled yields an image that is reasonably close, though not quite identical, to the original borderless image:

![4x3_borders](https://user-images.githubusercontent.com/86317528/123018576-6d75f680-d394-11eb-8a92-ea7f5f05c4d7.png)

But "Expand pixels by integers" still ignores this aspect ratio completely.

![4x3_borders_int](https://user-images.githubusercontent.com/86317528/123018624-841c4d80-d394-11eb-8837-eb3a6a2aaefe.png)

**Comment by zeromus** [comment]
This is just how the numbers work out. The mandate to maintain the integer pixels is higher priority than displaying a correct aspect ratio. Apparently there arent any solutions that appear to satisfy both constraints until the jump from 4x window to 5x window (this allows it to create 5x4 pixels in order to get some more horizontal stretch). You're forgiven for being baffled, because it's baffling. There's no way to change this because this is just how complicated it is when people want these complicated options.

**Comment by emu-hopeless** [comment]
Do you suppose it would be worth including an option to apply integer scaling to the vertical axis only? Surely there's at least one other system with a PAR that would cause a similar issue. Uneven pixels on one axis is better than uneven pixels on both.

**Comment by zeromus** [comment]
No. Fiddle around with the user-selected size or aspect ratio to get the size you want to pop out. I might also consider adding a separate X and Y "user prescale" which you could use to stretch the pixels the exact amount you want, although that isn't going to create pixels on average 2.5 wide (alternating 3-wide and 2-wide)
