### ISSUE TITLE
BizHawk attempts to load an absolute path for .CUE files

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2819]
We are in fact able to load a CUE file in a ROM to make us play custom music like in Sonic Winter Adventures, but BizHawk attempts to load an absolute path for them, basically causing an exception in ROM loader.
![image](https://user-images.githubusercontent.com/39802077/123229113-49bac980-d4d6-11eb-96a2-4bca9c6d3bc6.png)

**Comment by adelikat** [comment]
It attempts to load the file specified in the .cue
If the cue has an absolute path, should that not be the path it attempts to load?

**Comment by getCursorsExe** [comment]
It literally tries to do this even though it does exist.

**Comment by zeromus** [comment]
This error is misleading: it's the contained binary/wave file it can't find, not the cue.
I just reproduced by scrambling my cue
There is a typo in your cue

**Comment by getCursorsExe** [comment]
It's because I have no words to describe this.

**Comment by nattthebear** [comment]
It'd be nice if the error wasn't misleading, and gave the name of the missing file.
