### ISSUE TITLE
Pitch Shift Change Effect

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2821]
Some cores will change the pitch shift, but what if it was a feature?

**Comment by YoshiRulz** [comment]
I'm still not sure what you mean by this, but it's probably best done in post-processing after making an A/V recording.

**Comment by zeromus** [comment]
Which core changes the pitch shift?

**Comment by getCursorsExe** [comment]
blastem_libretro core. After we unpause the core, the pitch goes down, and after we load a savestate, it goes up. This does not happen if Audio Throttle is enabled.

**Comment by getCursorsExe** [comment]
By loading a savestate in EmuHawk being run in Visual Studio 2019 while Audio Throttle is enabled with version 2.6.2 or higher, craziness will happen. EmuHawk is tempomary frozen while Audio Output is not, and it also makes the real sound when Z80 is frozen.

**Comment by zeromus** [comment]
Works fine for me. By "z80 is frozen" I assume youre still using glitched roms that break the emulator and youre using blastem in bizhawk since youve run out of bugs to find in bizhawk's GPGX with your glitched roms. We're not going to waste time supporting this.

**Comment by getCursorsExe** [comment]
Well, no. This seems to depend on your PC.

**Comment by getCursorsExe** [comment]
I was using Sonic 2 when this happened.

**Comment by zeromus** [comment]
test a different libretro core

**Comment by getCursorsExe** [comment]
For some reason our Gambatte core will slightly lower the pitch if a transition occurs for example in Pokemon Blue. I don't know why, but GBHawk has no issues with this.

**Comment by EZGames69** [comment]
This is because Gambatte runs with equal length frames turned off, which is how an actual Gameboy runs.  If you check “Audio Throttle” under Config->Speed, it will play normally.

GBHawk has Equal Length Frames on by default which is why it doesn’t do this.
