### ISSUE TITLE
"System.InvaildOperationException: No core was found to try on the game" after trying to load hawked .CCDs

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2822]
If you try to load hawked CCD like Sonic Winter Adventures, BizHawk is too lazy to find a core to run, so you get this:

![image](https://user-images.githubusercontent.com/39802077/123554373-f10e5980-d77f-11eb-9f7c-da6ac24e09f8.png)

I don't even know.

**Comment by zeromus** [comment]
Sonic winter adventures is a romhack of a cartridge game. As usual, what the hell are you actually even doing with a disc?

**Comment by getCursorsExe** [comment]
This is one of the features that almost no other game has.

**Comment by zeromus** [comment]
what feature?

**Comment by getCursorsExe** [comment]
It is a Sega Mega Drive game that can use Sega CD to play custom tracks in-game.

**Comment by zeromus** [comment]
Bizhawk has no way to load roms like this, and is not likely to any time soon. We're certainly not going to do it for you so you can use it to report more bugs in GPGX.

**Comment by getCursorsExe** [comment]
However, it says that "no core was found to try on the game". Instead of this error, there can be a core selection window that happens when ROM is not found in database.

**Comment by zeromus** [comment]
there is no core for an audio cd
