### ISSUE TITLE
Rewinding after you loaded a savestate to a point before you loaded it during movie playback causes IndexOutOfRangeException Crash

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2826]
### Summary
When you load a savestate and rewind to a point before you loaded it during movie playback, BizHawk will throw an IndexOutOfRangeException Crash.

### Repro
1. Record a movie and stop at some point.
2. During movie playback, save and load a savestate and then rewind to a point before you loaded it.
3. IndexOutOfRangeException Crash.
### Output
![image](https://user-images.githubusercontent.com/39802077/123979778-4d13f080-d9c1-11eb-9a9d-cb95563fba37.png)

### Host env.
BizHawk 2.6.2 Win10

**Comment by nattthebear** [comment]
Can anyone get a stack trace for this?

**Comment by alyosha-tas** [comment]
I cannot reproduce it, It won't let me rewind to a point before the savestate was loaded. @getCursorsExe can you give more detailed steps or a demonstration of what you do?

**Comment by getCursorsExe** [comment]
I don't know what caused it, this seems to happen probably due to how savestates work or something I don't know.
How about this rewind and savestate config?
![image](https://user-images.githubusercontent.com/39802077/124168210-1e6f4600-daa5-11eb-99c3-af3297e6a14c.png)

**Comment by alyosha-tas** [comment]
Ok, so 'Use delta compression' is definitely causing this issue. Not sure how or why, but when it's off everything works fine, and when it's on things go bad pretty quick.
