### ISSUE TITLE
BizHawk Crashes Upon Loading N64 ROMs

### ISSUE THREAD

**Issue by SheikYerboutea** [TASVideos/BizHawk#2827]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

I've been using BizHawk 2.3 to run Ocarina of Time Multiworld for several months now, and as recently as last week without any issues that hadn't been previously reported. Yesterday I ran a ROM in the same version and it won't load the ROM at all. None of the settings had been changed since my previous session with the program, and none of my N64 ROMs that will work with other programs will work. SNES ROMs work right away.

I've deleted and reinstalled the same version several times through different methods and haven't had any success.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.3, Windows 10 Home 19041, NVidia 1080ti, Intel i9 9900k

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Are you seeing an error dialog, or does nothing happen when loading the rom? What happens when you use 2.6.2 to load the rom?

**Comment by SheikYerboutea** [comment]
I'm seeing no errors or pop ups at all. The application hangs for about 4 seconds and closes. 2.6.2 works fine.

**Comment by getCursorsExe** [comment]
This is an outdated version of BizHawk.

**Comment by SheikYerboutea** [comment]
It is, but unfortunately it's the only version currently supported by OoT Multiworld.

Considering it's still used consistently by a decently sized community I was curious if this was something that has happened but I couldn't find the post, and it happened suddenly with no explanation when it had been working fine for so long. I can't think of anything that I updated that would have caused any issues, and I didn't touch any of the program files between then and now.

**Comment by zeromus** [comment]
Reboot your computer, upgrade/downgrade your gpu drivers, uninstall any recently installed software including windows 10 malware/scumware/bloatware/updates

**Comment by arlber** [comment]
Did you find a solution for this? I just ran into the same issue where it was working a couple days ago and then suddenly stopped working. I have tried rolling back my display drivers and doing a fresh install but no luck.

**Comment by YoshiRulz** [comment]
Were you also using 2.3?

**Comment by arlber** [comment]
Yes, I found information in the Zelda Multiworld discord. It seems like there was a recent Windows update that they believe broke BizHawk 2.3. I ended up moving to Bizhawk 2.6.1 which seems to working fine.

**Comment by YoshiRulz** [comment]
Hmm gonna call this fixed then.
