### ISSUE TITLE
Arrow Keys Don't Respond During TAStudio Recording Mode

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/BizHawk#2828]
2.6.2 seemed to have done something where my arrow keys don't do any input during TAStudio recording mode. Worked fine in 2.6.1, broken in latest dev too. Other arrow key interactions work fine.

**Comment by alyosha-tas** [comment]
Works for me in 2.6.2 (fresh install) and dev, build, can you give anymore detailed info or repro steps (or video of the problem?)

**Comment by CasualPokePlayer** [comment]
Odd, I can't reproduce if I just grab a fresh install of 2.6.2. Along with fresh dev. I can reproduce once I copy paste my config file. Seems like the cause is something in my config file.

Don't know if this is still issue worthy, although I am curious what setting could have been ticked that caused this extremely specific behavior.

**Comment by vadosnaprimer** [comment]
Configs should always be fresh. We used to have this warning in the readme because people like to "update" their hawk by unpacking it into some old release folder and it always breaks things in ridiculous unreproducible ways. Can't find it anymore.

**Comment by CasualPokePlayer** [comment]
Ah, it was the "Hotkeys override controller buttons" which TAStudio recording mode did not like apparently. Apologies about the issue.

**Comment by vadosnaprimer** [comment]
> 
> 
> Configs should always be fresh. We used to have this warning in the readme because people like to "update" their hawk by unpacking it into some old release folder and it always breaks things in ridiculous unreproducible ways. Can't find it anymore.

Actually it has been there all along:
https://github.com/TASVideos/BizHawk#windows
