### ISSUE TITLE
Controller Config copies one section when scrolling

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2834]
When we are scrolling the controller config like crazy, you will see copies of the same section, creating an illusion of a glitched screen. This occurs for a split second, after a few miliseconds, it goes back to normal.
This probably depends on the graphics card itself (well, I am using GeForce GTX 1050 Ti). This is well seen in LibRetro controller config. Something like this never happens on almost any other software at all.

![image](https://user-images.githubusercontent.com/39802077/124623973-bf327c80-de7c-11eb-9a5d-8d3bf9431d23.png)

![image](https://user-images.githubusercontent.com/39802077/124624001-c8234e00-de7c-11eb-8509-cf633cbd4da1.png)

![image](https://user-images.githubusercontent.com/39802077/124624402-218b7d00-de7d-11eb-9cda-71dbd15d551f.png)

**Comment by YoshiRulz** [comment]
> scrolling [...] like crazy

> after a few miliseconds, it goes back to normal

This is just how WinForms works, there's not much we can do about it.
