### ISSUE TITLE
Genesis Overscan is in upstream release, but not in BizHawk

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2836]
Genesis Plus GX upstream has Overscan borders, but BizHawk is missing them. Without this, it will not look like an accurate core.
If no overscan borders is supposed to be intended, then this would be a very weird core.

**Comment by YoshiRulz** [comment]
Is this different from #2824?

**Comment by getCursorsExe** [comment]
Yes.

**Comment by nattthebear** [comment]
> Without this, it will not look like an accurate core.

Good, because it's not an accurate core.

I'm tempted to close this because as far as I know, we don't have a single core in hawk that supports rendering outside the active pixels of any PPU, and given that I doubt anyone would start with the genesis.
