### ISSUE TITLE
How to use game genie for NES in BizHawk?

### ISSUE THREAD

**Issue by MrTASerPranav** [TASVideos/BizHawk#2839]
How to use cheat codes in BizHawk for NES?
BizHawk is so complicated to use, that sometime I can't TAS using it...
I want to use a game genie code while TASing, but it is again and again crashing...
How to us it
Please help!

**Comment by YoshiRulz** [comment]
You can't use cheats while recording a movie. Though it shouldn't be crashing in any case. If you include the exact error message and what you were doing just before the crash, we can put in a more helpful message.

You *can* record a movie *after* using a cheat code which modifies the virtual memory, for example a "give 99 lives" code. That's done with the "Record From" dropdown when starting a movie recording, or in TAStudio, `File` > `New From`. "Now" will take a savestate of the whole virtual system, "SaveRam" will only include the save data on the virtual cartridge. Of course, movies starting from a savestate with cheats are going to be rejected on TASVideos.

For more complex codes, or a code that needs to be enabled at a specific time, you'd need to program the whole run in a Lua script, outside of TAStudio.
