### ISSUE TITLE
Atari 7800 Light Gun coordinates (X and Y) do not registers with mouse

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2846]
Without Virtual Pad, I could not find anyway to aim target. Unlike NES Light gun games, I cant fire to my aim with mouse. I believe mouse coordinate on Bizhawk does not register so cannot move your aim on screen and fire fixed point. 
I tried 2.4.2, 2.5.2, and 2.6.2 and none of them worked. Also if you open TAStudio, the column of coordinate never gets any value without Virtual Pad.

**Comment by alyosha-tas** [comment]
NES just has default configuration for player 2 light gun.

For anything else, you have to configure the controls for this in Config -> Controllers -> Analog Controls

Hit 'Bind' under the 'X' direction then move your mouse left / right, WMouse X should show up in the window. Then do similar for the 'Y' direction but move the mouse up / down.
