### ISSUE TITLE
Dragon Spirit - Aratanaru Densetsu is broken in BizHawk (works fine in FCEUX)

### ISSUE THREAD

**Issue by Sonia-7** [TASVideos/BizHawk#2847]
NesHawk core, not QuickNES. Game shows garbled graphics everywhere. Below are some comparison screenshots:

**BizHawk | FCEUX**
![b1](https://user-images.githubusercontent.com/24638400/125210552-d73c3e80-e276-11eb-8be7-718871a21cfc.png) ![f1](https://user-images.githubusercontent.com/24638400/125210561-ec18d200-e276-11eb-86a1-75d1dc4fdbc7.png)
![b2](https://user-images.githubusercontent.com/24638400/125210566-f8049400-e276-11eb-97b9-cb8c68eae51a.png) ![f2](https://user-images.githubusercontent.com/24638400/125210569-faff8480-e276-11eb-8214-a085a73440b4.png)
![b3](https://user-images.githubusercontent.com/24638400/125210570-fcc94800-e276-11eb-99ce-0b70cca2f5fb.png) ![f3](https://user-images.githubusercontent.com/24638400/125210571-fdfa7500-e276-11eb-86c1-ddd0bb707f06.png)

**Comment by Spikestuff** [comment]
Unable to replicate. Bad Dump?
![Dragon Spirit - Aratanaru Densetsu](https://user-images.githubusercontent.com/12412764/125237269-c3511500-e328-11eb-9952-79d7345c886c.png)

**Comment by getCursorsExe** [comment]
Really!? Does this mean that it is [IMPOSSIBLE](https://github.com/TASVideos/BizHawk/issues/2805) to TAS another game too!?

**Comment by getCursorsExe** [comment]
If this cannot be fixed in any way, then you have to add FCEUX core, it does exist in libretro as FCEUmm.

**Comment by YoshiRulz** [comment]
@getCursorsExe Please stop leaving unhelpful comments on every issue you see. We'll be forced to block you otherwise. An example of a *helpful* comment would be "I'm seeing the same bug when using the X core" or "This bug was fixed in upstream version X".

**Comment by getCursorsExe** [comment]
Well, some people think that this is helpful while is not, thank you for telling me this.

**Comment by Yave-Yu** [comment]
I remember when I play this game to see and record final boss footage on NESHawk core, it emulates JP version with graphic issue but still playable, until final boss appears... IT GARBAGED TOO! Forunately, US version works fine.
