### ISSUE TITLE
MovieSaveRam ignored after rewinding the TAS

### ISSUE THREAD

**Issue by Zimond47** [TASVideos/BizHawk#2849]
Using dev build 946b0e2c0

When converting a Moviefile with a Saveram in it into a TASproj the moviesaveram.bin gets ignored again when you rewind the TAS file to the beginning. This happened in an earlier version of Bizhawk once (I think 2.52) and was fixed in 2.6. I used a PSX game.

- Create a BK2 file with "from Saveram" option.
- Load it into TAStudio and convert it.
- You can normally play now starting with your previous saveram.
- When you rewind the TAS to the beginning saveram is "empty".
- The file moviesaveram.bin is still in the TASproj file though, so it seems it's not loaded on rewind.

**Comment by alyosha-tas** [comment]
Unable to repro. @Zimond47 please try another system besides PSX if you can.

**Comment by Zimond47** [comment]
ok, i repeated it myself and now it worked. Sorry, No idea what was different.

**Comment by alyosha-tas** [comment]
Well, if you run into this issue again, preferably if you know EXACTLY what steps you did leading up to it, please update. Until then, closing.
