### ISSUE TITLE
Can't load CD files from archive

### ISSUE THREAD

**Issue by PegHorse** [TASVideos/BizHawk#2855]
![image](https://user-images.githubusercontent.com/7678316/125630629-db1ba617-ad92-46d4-9db9-8c5e06a6fb11.png)

I notice when i want to Load ROM from CD Archives, like for example Mega-CD files, it cannot.
The program ask which file to run, i select and run it, and it fails.

If i extract the archive and load manually the first file, it works

Thanks

**Comment by YoshiRulz** [comment]
This is intentional. I can't find the comment from zeromus, but it was something about the random-access nature of discs being at odds with the sequential-access nature of .zip archives.
