### ISSUE TITLE
N64 PAL roms in `.n64` format are treated as NTSC

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#2864]
I have tried this with some N64 games and as far i got, any of my European/PAL N64 games will still run in NTSC at 60 FPS with a Higher Pitch.

### Repro
1. Run a N64 PAL game in .n64 format.
2. Set Speed/Skip either in "Clock Throttle" or "VSync Throttle"
3. Run any European/PAL N64 Game.
4. Problem mentioned.

Recorded video: https://youtu.be/ypZho37GS44

### Afected Examples
- SHA1 2BD376C3DB3080D0A2328EF4052E59C3DF71797E  Bust-A-Move 3 DX (Europe)
- SHA1 197556F41756C82EDB6BA7767F0D181290C1B2C2  Chameleon Twist (Europe)
- SHA1 F02C1AFD18C1CBE309472CBE5B3B3F04B22DB7EE  Earthworm Jim 3D (Europe) (En,Fr,De,Es,It)
- SHA1 63BD69C382ECA5E569EDDF7456F6435A7DCE484F  F-1 World Grand Prix (Europe) (Beta)
- SHA1 53ED343A757B8A14814732393D02B3D780BCCAB5  F-1 World Grand Prix II (Europe) (En,Fr,De,Es)
- SHA1 6E9C4B097628F0147E9E79393DBA6D7B4E59986F  LEGO Racers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi)
- SHA1 FA5D1426488B298A1C5C383360A78F1A3DE18DC7  Mario Party 2 (Europe) (En,Fr,De,Es,It)
- SHA1 9E1DDFE872C6D43AE51010A9E8A6FE2D2E634B50  Mario Party 3 (Europe) (En,Fr,De,Es)
- SHA1 2111D39265A317414D359E35A7D971C4DFA5F9E1  Paper Mario (Europe) (En,Fr,De,Es)
- SHA1 A2846CB316DC980DD0040CA95C20ABFC8CCCE212  Rakuga Kids (Europe)
- SHA1 619AB27EA1645399439AD324566361D3E7FF020E  Rayman 2 - The Great Escape (Europe) (En,Fr,De,Es,It)
- SHA1 899A8245DA017289C88E97327FDCD6694B770A25  Star Wars Episode I - Racer (Europe) (En,Fr,De)
- SHA1 92015E5254CBBAD1BC668ECB13A4B568E5F55052  Toy Story 2 - Buzz Lightyear to the Rescue! (Europe)

**Comment by Spikestuff** [comment]
Unable to replicate...
![image](https://user-images.githubusercontent.com/12412764/126059264-2148705c-c6c4-402d-9aa8-b6b5848e721c.png)
![image](https://user-images.githubusercontent.com/12412764/126059299-15e4b872-7ce3-49e2-9421-deacab569975.png)
![image](https://user-images.githubusercontent.com/12412764/126059314-e1bfe6b8-227a-45e9-96ee-1459ea9c4450.png)

----
How have you set your core and are you accidentally turbo'd without knowing it and it somehow doing a vsync?
Config > Speed Skip > 100%

**Comment by danylopez123** [comment]
I double checked and it seems that if i have the Speed/Skip either in "Clock Throttle" or "VSync Throttle" it does happen.
Having it with "Audio Throttle" will do the correct FPS at 50.
However, if "Audio Throttle" is selected, you won't be able to speed up and slow down the emulator because you must be in "Clock Throttle"

**Comment by Spikestuff** [comment]
I wasn't using Audio Throttle myself as a note.

**Comment by danylopez123** [comment]
I dont think i've been changing stuff from the core's settings, all i know it's that i've been overwritting older BizHawk versions with the recent ones.
I did also copied the Speed/Skip you showed and still the same thing.

When you said "have you tried just doing it all from a fresh BizHawk and just seeing with no modifications if it was something that was done in the settings which caused it?"
Well.. i did 2 things:

1. I deleted the config file from my current BizHawk but first i've made a backup of it, my problem it's still present.
2. Re-downloaded BizHawk 2.6.2 and put it in a completly new folder like a fresh install, my problem it's still present, even by doing the picture you showed me, still the same.

Either it's something from the settings by default without changing anything or must be something else.

**Comment by YoshiRulz** [comment]
Was able to repro Clock Throttle bug with `SHA1:61373D4758ECA3FA831BEAC27B4D4C250845F80C` *San Francisco Rush 2049* (E) on 2.6.2 with a clean config.
I did not see the same behaviour on:
* `SHA1:2171FE2C0A9253CBA56828F24A5E6153726C1516` *Air Boarder 64* (E)
* `SHA1:53ED343A757B8A14814732393D02B3D780BCCAB5` *F-1 World Grand Prix II* (E)
* `SHA1:F6B5F519DD57EA59E9F013CC64816E9D273B2329` *Mario Kart 64* (E)
* `SHA1:619AB27EA1645399439AD324566361D3E7FF020E` *Rayman 2* (E)
* `SHA1:BC8D37E3A3B9EDB4C8465ED7E477C6434C31B47D` *San Francisco Rush - Extreme Racing* (E) which I "dumped" thinking it was the same game

Note that VSync Throttle causes all these PAL titles to speed up to 60 fps, but the audio pitch does not increase because samples are being dropped.

**Comment by danylopez123** [comment]
Here, i made a list with the SHA1 with the games that affected me:

- SHA1 2BD376C3DB3080D0A2328EF4052E59C3DF71797E  Bust-A-Move 3 DX (Europe)
- SHA1 197556F41756C82EDB6BA7767F0D181290C1B2C2  Chameleon Twist (Europe)
- SHA1 F02C1AFD18C1CBE309472CBE5B3B3F04B22DB7EE  Earthworm Jim 3D (Europe) (En,Fr,De,Es,It)
- SHA1 63BD69C382ECA5E569EDDF7456F6435A7DCE484F  F-1 World Grand Prix (Europe) (Beta)
- SHA1 53ED343A757B8A14814732393D02B3D780BCCAB5  F-1 World Grand Prix II (Europe) (En,Fr,De,Es)
- SHA1 6E9C4B097628F0147E9E79393DBA6D7B4E59986F  LEGO Racers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi)
- SHA1 FA5D1426488B298A1C5C383360A78F1A3DE18DC7  Mario Party 2 (Europe) (En,Fr,De,Es,It)
- SHA1 9E1DDFE872C6D43AE51010A9E8A6FE2D2E634B50  Mario Party 3 (Europe) (En,Fr,De,Es)
- SHA1 2111D39265A317414D359E35A7D971C4DFA5F9E1  Paper Mario (Europe) (En,Fr,De,Es)
- SHA1 A2846CB316DC980DD0040CA95C20ABFC8CCCE212  Rakuga Kids (Europe)
- SHA1 619AB27EA1645399439AD324566361D3E7FF020E  Rayman 2 - The Great Escape (Europe) (En,Fr,De,Es,It)
- SHA1 899A8245DA017289C88E97327FDCD6694B770A25  Star Wars Episode I - Racer (Europe) (En,Fr,De)
- SHA1 92015E5254CBBAD1BC668ECB13A4B568E5F55052  Toy Story 2 - Buzz Lightyear to the Rescue! (Europe)

I had to make that list after seeing that YoshiRulz changed the topic name.

**Comment by YoshiRulz** [comment]
Your list includes *F-1 World Grand Prix II* and *Rayman 2*, which were on my unaffected list—did you have to progress past the title/demo to make them speed up?

**Comment by Spikestuff** [comment]
I believe I figured out how to consistently reproduce this issue I think.
The .z64 format does not produce this issue whilst the .v64 format does for Europe titles.

![image](https://user-images.githubusercontent.com/12412764/126268270-87358c5d-ef4e-4fc4-a4ba-3a09edf382a2.png)

Both dumps of Super Mario 64 are identical in SHA1, the only difference is the method they were dumped.
`SHA1:4AC5721683D0E0B6BBB561B58A71740845DCEEA9`

**Comment by Asnivor** [comment]
I haven't got time to test, but perhaps since .v64 is byte-swapped, and we are looking at a single byte position in the rom file to determine country code, that the switch is falling through to NTSC?

https://github.com/TASVideos/BizHawk/blob/master/src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64.cs#L47

**Comment by YoshiRulz** [comment]
It's exactly that. `.n64` -> `country_code = 0x00` -> `DisplayType.NTSC` -> 60 fps; `.z64` -> `country_code = 0x50` -> `DisplayType.PAL` -> 50 fps. What I don't understand is how the rom byte array arriving in the core constructor isn't byteswapped already.

(For anyone unaware: EmuHawk [will byteswap](https://github.com/TASVideos/BizHawk/blob/56594840ada308e2e024ce563f1786c7b04df228/src/BizHawk.Client.Common/RomGame.cs#L87-L96) `.n64` and `.v64` dumps after reading from disk, and the hash shown in the "Dump Status Report" window is for *the byteswapped rom*. The real, on-disk hash of the SM64 `.n64` dump that Spike was using would have been `SHA1:D80EE9EEB6454D53A96CEB6ED0ACA3FFDE045091`.)

**Comment by Asnivor** [comment]
> What I don't understand is how the rom byte array arriving in the core constructor isn't byteswapped already.

Presumably mupen has its own byteswapping stuff.

**Comment by danylopez123** [comment]
Huh.. you guys were right, these roms i reported from the list they were in the.n64 format.
I tried to find a N64 EUR rom but in z64 format and that seems to solve the problem.

Well, that said, i've made a last edit to my main post.
Case closed, you can close this issue when possible.
