### ISSUE TITLE
Rewinder with delta compression crashes when rewinding a full buffer all the way.

### ISSUE THREAD

**Issue by dacin21** [TASVideos/BizHawk#2870]
### Summary
If delta compression is enabled and the rewind buffer is full, then rewinding all the way until the buffer is empty crashes with the following exception:

```
   System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Client.Common.ZwinderBuffer.GetState(Int32 index)
   at BizHawk.Client.Common.ZeldaWinder.Rewind(Int32 frameToAvoid)
   at BizHawk.Client.EmuHawk.MainForm.Rewind(Boolean& runFrame, Int64 currentTimestamp, Boolean& returnToRecording)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Repro
1. Open Bizhawk
2. Emulation > Pause (pauses the emulator)
3. File > Open Rom > open a Super Mario World rom. (Also happens with Paper Mario for the N64.)
4. Config > Rewind & States. 
    - Enable rewinds
    - Set max buffer size to 2^6 = 64 MB (smallest value so filling the buffer doesn't take too long.)
    - Set "Desired frame length" to 1 (to avoid triggering #2866. You can skip this step if you use this build: https://github.com/TASVideos/BizHawk/commit/1c3eb451b295a20405edcb706a5e0b438a26d241)
    - Enable "Use delta compression (...)"
    - Click "OK" to close the configuration window.
5. Emulation > Pause (unpauses the emulator)
6. Let the game run until the rewind buffer is full (10000 frames were enough for me).
7.  Config > Rewind & States. Double check that the buffer is 99.99% full (or 100%).
    - If you close the configuration window, let the game run for a few more frames and then reopen the configuration window, you see that "Est. storage" and "Frames Stored" just increased, despite the buffer being full. (I'm not sure if this is just a visual glitch.)
    - Click "Cancel" to close the configuration window.
8. Press and hold the rewind key (shift+R by default) until you get the crash (happened at frame 596 for me.)

Note: This only happens if delta compression is enabled.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.2-win-x64; Win10 Pro 19041; Intel
- BizHawk dev build at 56594840ada308e2e024ce563f1786c7b04df228; Win10 Pro 19041; Intel
- BizHawk dev build at https://github.com/TASVideos/BizHawk/commit/1c3eb451b295a20405edcb706a5e0b438a26d241; Win10 Pro 19041; Intel

**Comment by getCursorsExe** [comment]
I got the same crash, but this time this is a lot weirder. I started rewinding on frame 545407 while the est. storage is over 57239045 frames, and the crash occured at frame 529033. Wait, excuse me. Does this REALLY mean that BizHawk behaves as if Delta compression was disabled!?

**Comment by nattthebear** [comment]
> Does this REALLY mean that BizHawk behaves as if Delta compression was disabled!?

No

**Comment by dacin21** [comment]
> I got the same crash, but this time this is a lot weirder. I started rewinding on frame 545407 while the est. storage is over 57239045 frames, and the crash occured at frame 529033. Crazy.

I guess this issue could also happen if you hit the 16k state limit (#2306) instead hitting a full rewind buffer.
I did a quick test and rewinding the full 16k states works on a recent dev build, so I'd expect that 8cd67529a3d08f0e66e8e4b45a8f773dc7456c7c also fixed your crash.
