### ISSUE TITLE
[Libretro] PPSSPP crash log

### ISSUE THREAD

**Issue by InfamousKnight** [TASVideos/BizHawk#2874]
Using bizhawk linux under wine:
[SYSTEM] Using Software backend
[BOOT] PPSSPP v1.11-183-g9640636 Windows 64 bit
[MEMMAP] Memory system initialized. Base at 00007FF6EAFF0000 (RAM at @ 000000001
88C1E48, uncached @ 00000000188C1E60)
[LOADER] ULUS10235 : Driver 76
[LOADER] Failed to read /ULUS10235_ppsspp.ini. No game-specific settings found, 
using global defaults.
[LOADER] Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
[SYSTEM] Exception handler not implemented on this platform, can't install

=================================================================
        Native Crash Reporting
=================================================================
[SCEKERNEL] Initializing kernel...
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
[SCEKERNEL] Kernel and user memory pools initialized
=================================================================
=================================================================
0024:err:seh:call_stack_handlers invalid frame 0000000016B5FF40 (0000000000122000-0000000000220000)
0024:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.

I guess it wants NtRaiseException raised. That same message comes on a lot of cores that "modern"

**Comment by YoshiRulz** [comment]
Don't use WINE.
