### ISSUE TITLE
PSX Game doesn't save inputs in Bizhawk 2.6.2 

### ISSUE THREAD

**Issue by Samtastic1** [TASVideos/BizHawk#2879]
### Summary
Whn TASing the PSX version of Abe's Exoddus, I can't get it to recognize my inputs after creating a savesate and saving the movie file. It syncs but then I replay the movie file and desyncs. This does not happen in any of my movies in 2.4.
http://tasvideos.org/userfiles/info/73040317691794869

### Repro
1. Record a few frames
2. Save the movie.
3. Replay the movie then it will desync.

**Comment by Spikestuff** [comment]
> BizHawk 2.6.2
> Any of my movies in 2.4

User error. There was a core update between 2.4 and 2.6.2

**Comment by YoshiRulz** [comment]
You *should not expect* movies from version X to sync in version Y when there was a core update.
