### ISSUE TITLE
N64 Hercules: The Legendary Journeys fails to load the title screen (seems to work fine on upstream)

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2887]
Hercules: The Legendary Journeys, fails to load the title screen. It just gets stuck at black screen instead.
This doesn't happen in RetroArch version of Mupen64Plus (called Mupen64Plus-Next).

**Comment by Spikestuff** [comment]
That's nice, RetroArch isn't upstream.
Did you even bother to check upstream like the other times you're told to check upstream?
Yes, that's a rhetorical of course you didn't.

Now if I'm not mistaken this is upstream:
![image](https://user-images.githubusercontent.com/12412764/127746162-89a8747e-7207-44ad-b82a-35ac5db339fe.png)
Using default settings cause I honestly have no idea what I'm doing with M64+ so it's using Rice and not GlideN64 but using Rice on Hawk also brings the issue.

So core needs an update.

**Comment by getCursorsExe** [comment]
I couldn't check the upstream because of the way how to open it...

**Comment by YoshiRulz** [comment]
Duplicate of #1391.
