### ISSUE TITLE
Bizhawk crashes when i change Deep Fear disk

### ISSUE THREAD

**Issue by Erchitu** [TASVideos/BizHawk#2894]
Hi. I have this problem. I just finished the Deep Fear`s first disk. When I  swap to the second disk Bizhawk just crashes. Using Saturnus core. Any idea on how to solve?
Using Bizhawk 2.6.2 x64 on Windows 10 Pro. Platform is GPD Win Max.
Thanks

**Comment by Mad-Matty** [comment]
I'm using a current dev build of Bizhawk (2.6.3) and the disc swapped fine using Darkwater cd images. Game continues on as expected.

**Comment by nattthebear** [comment]
@Mad-Matty Thanks for looking at this, I haven't yet got to reproing myself.  @Erchitu Could you verify that you have good disk images and try current dev builds?

**Comment by Erchitu** [comment]
Hi, sorry for the long delay. I confirm I solved the problem, but I'm not sure how. I just opened the iso and it worked at a certein point. Thanks!
