### ISSUE TITLE
Associate .bs (Satellaview ROMs) with SNES

### ISSUE THREAD

**Issue by anewuser** [TASVideos/BizHawk#2915]
Trying to open `.7z`-compressed  `.bs` (Satellaview) ROMs makes BizHawk show the `Choose file from archive` / `Choose a platform` window, even when there's just one file in them. Shouldn't this format be associated with SNES by default? Or is this extension used for something else too?

Even after manually setting it to always open this extension with SNES cores, BizHawk still shows `Choose file from archive` for these ROMs.

![Screenshot 2021-08-23 165005](https://user-images.githubusercontent.com/6733770/130510544-b7bd109f-5bc0-41e9-9b4c-023afccdcdd1.png)

BizHawk 2.6.3
Windows 10

**Comment by YoshiRulz** [comment]
But does it work when extracted? The first `.bs` rom I found won't load in any core.

**Comment by anewuser** [comment]
Yes, after setting this extension to SNES in the `Choose a platform` dialog, extracted ROMs supported by bsnes/Snes9x (like the Zelda games) load right away, but not if the are compressed.

**Comment by YoshiRulz** [comment]
I didn't actually add `.bs` to the list, but if you set it to SNES manually (e.g. by loading a dearchived copy) then that preference will be respected when loading archives.
