### ISSUE TITLE
RetroArch "common" Cg shaders not working

### ISSUE THREAD

**Issue by I-Megaman-I** [TASVideos/BizHawk#2916]
CGP shaders not working in 2.6.2 x64
![(PNG Image, 786 × 793 pixels)](https://user-images.githubusercontent.com/13409956/131273714-32c93ee9-ee98-462d-9e9a-a6384fb14b93.png)

but working perfectly in 2.1.1 x64

**Comment by YoshiRulz** [comment]
*Which* shaders? The ones shipped with RetroArch won't work out-of-the-box.

see also #2397, #2727, #2730

**Comment by I-Megaman-I** [comment]
but they do work in 2.1.1) 
im using 2xbrz-linear, its much better than the default hq2x.

**Comment by zeromus** [comment]
Open an issue with a specific request if you want a specific shader and maybe someone will port it.
