### ISSUE TITLE
Minimizing Debugger harms BizHawk

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2918]
Just minimize debugger window and you get this:
```
System.ArgumentOutOfRangeException: range end < start
Nazwa parametru: endInclusive
Rzeczywista wartość to -1.
   w BizHawk.Common.MutableRange`1.Overwrite(T start, T endInclusive)
   w BizHawk.Client.EmuHawk.InputRoll.IsVisible(Int32 index)
   w BizHawk.Client.EmuHawk.InputRoll.set_RowCount(Int32 value)
   w BizHawk.Client.EmuHawk.GenericDebugger.DisassemblerView_SizeChanged(Object sender, EventArgs e)
   w System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   w System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   w System.Windows.Forms.Control.UpdateBounds()
   w System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
![image](https://user-images.githubusercontent.com/39802077/131696250-b2e83809-ee73-4634-b9fe-ae0c33e0450c.png)

**Comment by TizianoMattei** [comment]
#2760

**Comment by getCursorsExe** [comment]
Unlike #2760, this one does not crash the emulator, and occurs in all cores. This has happened to me in Genplus-gx debugger and Gambatte debugger.

**Comment by TizianoMattei** [comment]
@getCursorsExe Thats interesting, i had linked the closed issue cause since that fix i havent encountered that problem with the debugger tho. Did you get this error on 2.6.3 dev?

**Comment by getCursorsExe** [comment]
Already fixed, just to mention that this bug happens with all cores, not PSX only.

**Comment by TizianoMattei** [comment]
Yea i should have been more clear, i wasnt talking about psx in the first place, just that the minimizing issue was fixed in the dev version. Glad thats fine then
