### ISSUE TITLE
Unintentional behaviour with Gambatte core 

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2919]
Some unintentional behaviour will occur with Gambatte core when you mess with VBlank address (0041-0042) at some point. In newer versions it can prevent BizHawk from loading next frame, this did not happen in older versions.
This can break most homebrew, and it may affect normal games too.

**Comment by CasualPokePlayer** [comment]
> Some unintentional behaviour will occur with Gambatte core when you mess with VBlank address (0041-0042) at some point. In newer versions it can prevent BizHawk from loading next frame, this did not happen in older versions.
> This can break most homebrew, and it may affect normal games too.

You mean the VBlank *interrupt* address, which also is actually at 0040. And you cannot modify it without outright modifying the ROM (so no, this does not affect "normal games"). And for all we know you just ended up getting an invalid instruction/halt/stop executed and has the system lock up.

**Comment by getCursorsExe** [comment]
After the game executing rst $38, it managed to completely prevent BizHawk from loading next frame instead of showing crash logs, which I don't think this should be intentional, But if you think this is intentional, then okay.

**Comment by YoshiRulz** [comment]
If it's in a game, can you record a movie which plays the game to just before the crash?

**Comment by CasualPokePlayer** [comment]
> 
> 
> After the game executing rst $38, it managed to completely prevent BizHawk from loading next frame instead of showing crash logs, which I don't think this should be intentional, But if you think this is intentional, then okay.

You mean tracelogs didn't show up? Are you saying you aren't at least getting the `Z80: PC, opcode, registers (A, B, C, D, E, F, H, L, LY, SP, CY)` in tracelog files?

If you are, then this is likely intentional behavior when Gambatte enters a state where the CPU cannot execute anymore instructions.

**Comment by getCursorsExe** [comment]
Well, yes. This crash does not occur in GBHawk.

**Comment by CasualPokePlayer** [comment]
> Well, yes. This crash does not occur in GBHawk.
Again, the result of this bus conflict would depend on whatever is in sprite data, i.e. instance specific. If you are not willing to provide a movie file and whatever modifications you did to whatever rom you used, there isn't a way to repro this (and again, your descriptions seem to indicate intended behavior).

**Comment by getCursorsExe** [comment]
I still don't know, but I did not encounter these emulator crashes in 2.6.2.

**Comment by CasualPokePlayer** [comment]
> The ROM I used is Pokemon Yellow Debug Hack by TheZZAZZGlitch.
> I still don't exactly know about it, but when this happens to bus conflict, BizHawk might hang completely. I did not encounter these emulator crashes in 2.6.2.

Are you saying you were using interim builds? 2.6.2 is the latest stable release.

**Comment by getCursorsExe** [comment]
Depending on the ROM you are playing, when the game attempts to execute rst $38, then after a few frames, BizHawk completely hangs. Not even advancing one frame! Can someone where BizHawk hangs after rst $38 depending on the ROM?

**Comment by CasualPokePlayer** [comment]
I don't know what you're talking about, some tests on my end and everything seems to work fine on rst $38. BizHawk does not hang for me. Either provide clear repo steps or any sort of video of this occurring, or we cannot help you.

**Comment by getCursorsExe** [comment]
Is this actually Visual Studio fault or something? I don't know.

**Comment by YoshiRulz** [comment]
You need to start listening to developers. We asked you some simple questions for clarification and you keep ignoring them. Why report a bug, only to delay and block us from fixing it?

For this issue, we need you to do *any one of these*:
1. Provide a movie which plays through the game until *just before* the crash/hang, and explain how to trigger it from there.
2. Same as 1., but don't bother with a movie, just record your screen the whole time.
3. Answer these questions:
	1. Which version of EmuHawk are you using?
	2. What rom are you using? Include the hash please.
	3. What do you need to do in-game to cause the crash/hang?

**Comment by getCursorsExe** [comment]
I only got this in interim builds of BizHawk, the ROM hash is:
```
DebugYellow
SHA1:ECE578EE1642A7AA9A3C9DE9F647E7599ABF0231
MD5:E7B6D8EC4BB227B1E9E2E3A0C6219D41
```
Set the PC register to 0x0000 so the rst $38 is executed.

**Comment by CasualPokePlayer** [comment]
I have repro'd the crash and have [committed a fix.](https://github.com/pokemon-speedrunning/gambatte-core/commit/c0eab0b01f7b670c0646ab7a5b684957f880ac0c#diff-470960ef2daecd0aea2cf41cd4f93c3ce1d6b9815c4dd1c7e86a3063e46cf40e)
