### ISSUE TITLE
"UserDefinedFrames" option completely changes Game Boy controllers (Gambatte)

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2921]
For some reason if we set Equal Length Frames to "UserDefinedFrames, you will find that Game Boy Controller is completely changed (you can see this when you notice that all inputs are now blank).

**Comment by YoshiRulz** [comment]
I think this will be fixed by #2917? Enabling/disabling ELF should require a core reboot, but currently it can affect the `ControllerDefinition` of the running core instance.

**Comment by getCursorsExe** [comment]
This is still not fixed.
