### ISSUE TITLE
Changing palette in Gambatte with SGB glitches out the SGB border, and also the game

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2931]
Whenever you change palette to GBA, then after the boot screen, SGB border will glitch out, and can affect the whole gameplay. If the palette is VBA accurate (old), the whole game is rendered unplayable at some points. Just look at this:

![image](https://user-images.githubusercontent.com/39802077/134031822-0e5bd75d-ad1d-4b0a-8896-64b737208c7f.png)

Everything is rendered correctly if the palette is Gambatte:

![image](https://user-images.githubusercontent.com/39802077/134032101-9f2ecc00-5b36-48c3-9587-42bb343f666e.png)

**Comment by CasualPokePlayer** [comment]
Will be fixed in upstream PR https://github.com/pokemon-speedrunning/gambatte-core/pull/8
