### ISSUE TITLE
"Can't have lua running in two host threads at a time!" when loading a state in lua console

### ISSUE THREAD

**Issue by tonylukasavage** [TASVideos/BizHawk#2940]
### Summary

Environment: BizHawk 2.6.2-win-x64, WIndows 10 Home Intel i7-8700
Cores: QuickNes (throws exception), NesHawk (crashes)

Using the trivial lua script in the following section on version 2.6.2, I get this exception thrown when starting it with QuickNES. On NesHawk it just crashes and hangs.

![exception](https://i.imgur.com/tia1ENR.png)

When I executed the same code on version 2.5.2, everything works as expected. I know that there was an issue addressing this same error with respect to TASStudio resolved in 2.52.2 mentioned in the release notes. There wasn't a a ticket number mentioned for this particular issue in the release notes, but this was the closest thing I could find in the way of existing similar ticket: [https://github.com/TASVideos/BizHawk/issues/1119](https://github.com/TASVideos/BizHawk/issues/1119)

### Repro

1. Load any NES ROM in EmuHawk.exe
2. Save state to a file and remember where you saved it
3. Close EmuHawk.exe
4. In the script that follows these steps, change `ROM_PATH` to the absolute file path to the ROM you just loaded
5. In the script that follows these steps, change `SAVE_PATH` to the absolute file path to the savestate you saved in step number 2
6. Save the edited script somewhere on your PC
7. Start EmuHawk.exe
8. Open the Lua Console
9. Open your edited script in the Lua Console
10. Run the script

```lua
ROM_PATH = "C:\\path\\to\\rom";
SAVE_PATH = "C:\\path\\to\\savestate";
client.openrom(ROM_PATH);
savestate.load(SAVE_PATH) -- loadslot() has the same issue
```

In 2.6.2 this will result in an exception/crash. In 2.5.2 it works as expected.

**Comment by YoshiRulz** [comment]
Haven't repro'd this yet, but `client.openrom` is supposed to halt Lua execution, effectively restarting all scripts. So if it worked before it's probably because of poor encapsulation which has since been tightened up.

**Comment by tonylukasavage** [comment]
If that's the case, does that mean literally no code should ever come after
openrom() in any bizhawk Lua script?

**Comment by YoshiRulz** [comment]
I made `client.openrom` behave like `client.reboot_core` i.e. once the rom has loaded, execution will continue immediately after the `openrom` call. No promises it won't still crash.
