### ISSUE TITLE
What happened to BSNES's graphics debugger?

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2950]
In interim builds graphics debugger was there, but on stable 2.6.3 it is completely missing, why?

**Comment by nattthebear** [comment]
You installed a different copy of bizhawk with different settings and used a different core which doesn't have that support

**Comment by getCursorsExe** [comment]
I have downloaded the windows binary, I don't think so.

**Comment by zeromus** [comment]
Show us which core you're using for SNES and when you're in the middle of doing that you'll realize what you've done wrong

**Comment by getCursorsExe** [comment]
I was using BSNES, but things are now back to normal. I've just downloaded BizHawk and this happened.

**Comment by getCursorsExe** [comment]
Turns out this issue happens when you switch SNES core from BSNESv155+ to original BSNES.

**Comment by CasualPokePlayer** [comment]
This is a legitimate bug. The Graphics Debugger is option is not present in the old BSNES core if the BSNESv115+ core is ever used in that BizHawk instance until the BizHawk instance is completely closed.
