### ISSUE TITLE
DiscoHawk Freeze

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2952]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
DiscoHawk freezes when extracting music from Gunship (USA)

I don't know why it freezes, as it works fine for other games.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. First open DiscoHawk
2. Drag "Gunship (USA).cue" to the HAWK area
3. Drag "Gunship (USA)_hawked.ccd" to the MP3 extraction area.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
4. DiscoHawk hangs for a long time (forever).
5. Force quit DiscoHawk
6. Check the output folder, and you will see Track 02 successfully extracted.
7. No other files extracted successfully.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
BizHawk 2.6.2 - win64

**Comment by Meerkov** [comment]
When debugging, it seems like it gets through about 8 tracks before hitting an exception here:
```c++
int trackLength = track.NextTrack.LBA - track.LBA;
```
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DiscoHawk
  StackTrace:
   at BizHawk.Client.DiscoHawk.AudioExtractor.Extract(Disc disc, String path, String fileBase) in C:\Users\admin\Documents\GitHub\BizHawk2\src\BizHawk.Client.DiscoHawk\AudioExtractor.cs:line 24

```

**Comment by zeromus** [comment]
I found this problem too... but it's not what made it hang for me... it's like, a separate problem. I just added a random check to avoid it. but uhhhh ... I'm not sure how this code ever worked. Well, it got all the tracks in this case, and the only dysfunction I can imagine from the change I made is that a final track might fail to get dumped, so since _that_ isnt happening.... we'll just leave it at that for now

**Comment by Meerkov** [comment]
In the game "5 Star Racing" I noticed the final 2 tracks are silent. The second to last one is 8 minutes, and the last one is 3.

Is that the issue you're talking about, with failing to export the final track(s)? I've seen a number of games seemingly not export the final track. I just assumed a lot of games include a data track as the last track, but maybe it's export failures. I'll start keeping my eyes out for more examples.

**Comment by zeromus** [comment]
That one is a bad example. The last 2 tracks are actually silence.
Yes, the problem would be problems exporting final track(s), or more precisely, only the final track.
But I checked it just now and I'm less concerned that it's a problem. In the scheme DiscSystem is using, the final track is the leadout track, which isn't audio to be dumped. preceding tracks should all be fine, so I now believe this should be working at 100% success

**Comment by Meerkov** [comment]
Ok, thanks for checking zeromus. If I notice other strange behavior I'll take a note of it.

**Comment by Meerkov** [comment]
You know, I find it a little suspicious that so many games have a blank track at the end. Are we sure this isn't a bug?

**Comment by zeromus** [comment]
So many which games?
