### ISSUE TITLE
Two bugs in Bizhawk (Psycho Chaser desync and inability to dump SNES AVI files)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#308]
```
Psycho Chaser desyncs at stage 6 (Not the first time seen, others that desync 
included Gun-Nac on the NES and Cruise 'n USA on the Nintendo 64). In addition, 
BizHawk can't dump AVI files made from SNES playthroughs

Tested on Bizhawk 1.8.4 on Windows 10 Technical Preview
```

Original issue reported on code.google.com by `Warblefl...@gmail.com` on 14 Nov 2014 at 1:50

**Comment by adelikat** [comment]
Closing this ticket.

The desync reports have not enough information.  It ALWAYS desyncs in a level? Are you talking about a movie you made desyncs? When are you savestating? 

Then 2nd has been fixed or was user error.  Video dumping in snes in general works fine and people do it every day.

Please create new tickets if you are experiencing these issues but make SEPARATE tickets, do not lump everything into one, and please provide as much information as you can in order for a developer to recreate and fix them
