### ISSUE TITLE
Crash on rewind

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#322]
```
What steps will reproduce the problem?
1.Running SNES and Sega ports
2.Rewinding
3.Rewinding multiple times

What is the expected output? What do you see instead? The rewind runs fast and 
also on every other instance will crash the emulator. (Side note: It happens on 
certain systems i.e. Sega Genesis, SNES.)


What version of the product are you using? On what operating system?
1.8.4 / Windows 8.1

Please provide any additional information below.
It could be possible that some settings are incorrect but this release fixed 
the buffer issue.

```

Original issue reported on code.google.com by `Gerard.C...@gmail.com` on 21 Nov 2014 at 9:03

**Comment by zeromus** [comment]
Just in case this user followed us to github, can you please post a screenshot of the crash dialog / stacktrace /etc? You could have managed more informative than "it crashed"

**Comment by adelikat** [comment]
Closing due to lack of a response for over a year.  Feel free to reopen if this is still an issue and we can get stacktrace information
