### ISSUE TITLE
Add Game Genie/PAR function

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#324]
```
What steps will reproduce the problem?
1.None
2.None
3.None

What is the expected output? What do you see instead?
Ability to use Game Genie or Pro Action Relay codes.

What version of the product are you using? On what operating system?
1.8.4 / Windows 8.1 (x64)

Please provide any additional information below.
Might require the incorporation of code conversion.

```

Original issue reported on code.google.com by `Gerard.C...@gmail.com` on 21 Nov 2014 at 9:20

**Comment by adelikat** [comment]
Closing this ticket as we have game genie support.

Please open a ticket for the specific platform you want, that is not currently supported.  Open up several tickets if necessary.  A single ticket for generic support doesn't make sense, as it can never be closed.
