### ISSUE TITLE
RAM Watch Icon becomes EmuHawk's TaskBar Icon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#334]
```
What steps will reproduce the problem?
1. Have a ROM and RAM Watch on AutoLoad and have them be valid.
2. Open EmuHawk
3. The Ram Watch Icon is the "Icon" for EmuHawk

What is the expected output? What do you see instead?
EmuHawk's Taskbar Icon to be the first one/on top.


```

Original issue reported on code.google.com by `hegyak` on 1 Dec 2014 at 5:55

**Comment by YoshiRulz** [comment]
Reproducible w/ BizHawk 2.2 on Win10 x86_64, though not if BizHawk was pinned before setting autoload or even when pinned after RAM Search autoloaded. (Is RAM Watch's autoload supposed to be upon opening BizHawk? Because it didn't.)
