### ISSUE TITLE
Sega Game Gear: Shining Force Gaiden - Final Conflict doesn't launch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#335]
```
What steps will reproduce the problem?
1. Try to open a ROM of Shining Force Gaiden - Final Conflict
2.
3.

What is the expected output? What do you see instead?
The game is supposed to start, it doesn't. I just see black screen and hear 
nothing.

What version of the product are you using? On what operating system?
Bizhawk 1.8.2, Bizhawk 1.9.1; Windows 7

Please provide any additional information below.
I used a ROM in .gg format.

```

Original issue reported on code.google.com by `Reinc...@gmail.com` on 4 Dec 2014 at 3:22

Attachments:
- [Shining Force Gaiden - Final Conflict (J).gg](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-335/comment-0/Shining Force Gaiden - Final Conflict %28J%29.gg)

**Comment by Reinc01** [comment]
The game starts now but colors become inverted on the secret sound test screen. It happens on both the release version of Bizhawk and the most recent dev build as of this writing.
[Shining Force Gaiden - Final Conflict (J).QuickSave8.zip](https://github.com/TASVideos/BizHawk/files/769144/Shining.Force.Gaiden.-.Final.Conflict.J.QuickSave8.zip)

**Comment by Reinc01** [comment]
The issue still persists in 1.12.1 release. The game now also resets by itself after loading the above save state.

**Comment by alyosha-tas** [comment]
The game does not reset itself for me on either 1.12.1 or the most recent dev build using the above savestate. Is there any other information you can give? Can you try a clean dev build and see if it still happens?

**Comment by Reinc01** [comment]
I have tried the dev build just now. It does not reset when I enter the code, but it does reset when I load that save state.

I don't know whether colors become inverted on real hardware or not, but the two other Shining Force Gaiden games have the same sound test code and they don't have this issue.

**Comment by alyosha-tas** [comment]
Can you try making a similar savestate with the Dev Build and see if that one resets for you as well?  

I can't do anything with the colors until it's confirmed that it does not happen on hardware.

**Comment by Reinc01** [comment]
How do I make it similar?

**Comment by Reinc01** [comment]
"Colors" state shows that colors still become inverted in the most recent build. No auto-reset though.

"Corruption" state shows a starting stage of text corruption, which always starts with the "C" letters becoming glitched, and can later progress to the point of all text becoming unreadable. It appears and progresses depending on how much the game went without resetting, but may not appear depending on controls input,

"Blink" state shows screen blinking, which starts happening after the game haven't been reset in a while. Just like with corruption, it may change depending on input, so don't press anything on the controls and you will be able to see the blinking as soon as the character starts speaking.

[save states.zip](https://github.com/TASVideos/BizHawk/files/975230/save.states.zip)

**Comment by alyosha-tas** [comment]
Corruption: Can you make a savestate one or two frames before the corruption happens? I can't really analyze what's going on when it is already there.

Blink: I don't see any blinking. Did you change any other emulator settings?

**Comment by Reinc01** [comment]
I did not change any other settings. I cannot pinpoint the exact frame when corruption happens, because I do not know when or why it happens.

This input movie shows a turn in progress with no corruption, then another characer's turn comes (a blink happens when their turn starts), then I show that corruption happpened in the previous character's name.

I also included a screenshot showing the exact moment where a blink happens in the previously sent save state.

[blink and corruption.zip](https://github.com/TASVideos/BizHawk/files/977945/blink.and.corruption.zip)

**Comment by alyosha-tas** [comment]
Ooooooohhhhhhhh you are using an english translation. 
I downloaded an IPS patch and then loaded the state and yes I do indeed see the blinking.
The unpatched game does not blink, so I'm guessing the blinking is the result of the patch.

I probably won't be looking deeply into this but I'll leave this issue open until a resolution to the color issue is found.

**Comment by YoshiRulz** [comment]
@Reinc01 Can you reproduce this on 2.x with an unmodified rom?
