### ISSUE TITLE
Video Dumping Died: Possible incorrect parameters for output stream

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#336]
```
What steps will reproduce the problem?
1. Play GBA game
2. Try to record using ffmpeg (mp4 or whatever)
3. Crash

What is the expected output? What do you see instead?

Video Encoding just like previous versions

What version of the product are you using? On what operating system?

BizHawk 1.9.1, Windows 7 x64

See attached pictures
```

Original issue reported on code.google.com by `xmikecam...@gmail.com` on 4 Dec 2014 at 7:13

Attachments:
- [Capture.JPG](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-336/comment-0/Capture.JPG)
- [Capture1.JPG](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-336/comment-0/Capture1.JPG)

**Comment by zeromus** [comment]
hey vgturtle, check this with his exact game and we can close it, this is so old i bet it's been solved

**Comment by vgturtle127** [comment]
@zeromus Yeah, this has been fixed. I tried the exact game and multiple recording setups, as well as the PAL version of the game. I tried with and without GBA BIOS as well, everything works fine.

Sorry about not getting to this sooner.
