### ISSUE TITLE
Grab screenshot of frame via command line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#366]
```
I humbly request your consideration to add the ability to grab one (or many) 
screenshots of specific frames using Bizhawk's command line, ideally 
independent of other options (so it can occur during A/V capture).

Thanks!
```

Original issue reported on code.google.com by `farr...@bluetoaster.net` on 13 Jan 2015 at 1:15

**Comment by zeromus** [comment]
fixed by 04b625ab6867408d7aa6be57d2687ac0273f1d38
fixed by 8491be66baa720bb9e8e4a2bb9ef145fe81d15a5
--dump-frames=100,200,300
--dump-type, --dump-name, --dump-length, --dump-close

**Comment by vadosnaprimer** [comment]
Usually command line is used for some (relatively) smart automation, but only a few functions are exposed to command line, so efficiency is very limited. Lua function client.screenshot([string path = null]) should be used instead, with all conditions one may come up with. But yeah, he didn't tell us what he's doing, so we can only guess.

As for potentially new, I added hashing for user buffers to fceux, so when used for screenshots, it's very useful for romhackers.

**Comment by zeromus** [comment]
Since we have the functionality to run lua strings not contained in files, it would be neat if we put that on the commandline (and then figured out a way to let lua do some stuff the commandline already does succinctly), although kind of cumbersome on the whole.

**Comment by zeromus** [comment]
i'm going to open a new ticket for lua on commandline
