### ISSUE TITLE
Mapper 90 Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#390]
```
What steps will reproduce the problem?
1. Try to start Mortal Kombat II Special or Mortal Kombat III Special, or 
Mortal Kombat 3 - Special 56 Peoples on Bizhawk.
2.
3.

What is the expected output? What do you see instead?
The games are supposed to start. They don't, there's just green screen.

What version of the product are you using? On what operating system?
1.9.1, Windows 7

Please provide any additional information below.
They work on Nestopia.

```

Original issue reported on code.google.com by `Reinc...@gmail.com` on 7 Feb 2015 at 3:14

Attachments:
* [Mortal Kombat II Special (Unl) [!].nes](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-390/comment-0/Mortal Kombat II Special (Unl) [!].nes)
* [Mortal Kombat III Special (Unl) [!].nes](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-390/comment-0/Mortal Kombat III Special (Unl) [!].nes)
* [Mortal Kombat 3 - Special 56 Peoples (Unl) [!].nes](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-390/comment-0/Mortal Kombat 3 - Special 56 Peoples (Unl) [!].nes)

**Comment by adelikat** [comment]
Mapper 90 has been implemented
