### ISSUE TITLE
Relative path changes in lua during forms.button clickEvent

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#405]
```
What steps will reproduce the problem?
1. Load a rom, load the attached sample script in the lua console
2. Watch the lua console output
3. Click the button in the lua form

What is the expected output? What do you see instead?
At the start of the script "lua_test.txt" is created next to the .lua file and 
filled with "Waiting...". The contents of the file are displayed on the console 
every frame as part of the frame loop. Clicking the button in the form should 
write "Success!" to the same file, but the relative path during the click event 
is different than during the frame loop causing a second "lua_test.txt" file to 
be created next to the bizhawk exe. 

If the path was the same, "Waiting..." would be replaced with "Success!", and 
this would be displayed on the lua console. 
```

Original issue reported on code.google.com by `pjga...@gmail.com` on 7 Mar 2015 at 5:12

Attachments:
* [lua_failure_test.lua](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-405/comment-0/lua_failure_test.lua)

**Comment by tomzx** [comment]
I'll see what I can do about this one. It appears that the thread context is different when lua is initialized (main loop) than when it is running from an event (button click).

**Comment by tomzx** [comment]
After taking a quick look, it appears my assumptions are correct.

In LuaConsole.ResumeScripts, `Environment.CurrentDirectory` is set to the script's directory before it is executed and then reverted to the current path of the executable.

However, when the callbacks are executed, the `Environment.CurrentDirectory` is the executable path. Furthermore, the information to figure out what current directory should be set is not available.

An "easy" fix would be for lua not to use `Environment.CurrentDirectory` at any point, but that is likely to not be backward compatible.
