### ISSUE TITLE
Change All Instances of "Gameboy" to "Game Boy"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#411]
```
Game Boy is two words: 
http://transparent-aluminium.net/Gallery/game-boy/Game-Boy-Original-Box-2.jpg

This also applies for Game Boy Color and Game Boy Advance.

I recommend using the tool FAR - Find And Replace to do a mass find and replace.
```

Original issue reported on code.google.com by `Buddyb...@gmail.com` on 20 Mar 2015 at 4:05

**Comment by hegyak** [comment]
The issue with this, is that there's the Displayed Strings.  Like the Title Bar and there are the internal functions and methods that use GameBoy.

**Comment by adelikat** [comment]
Closing this ticket.
I changed all the places that are visible to the user I could find. 
If there are any I missed make a new ticket about the specific place(s), instead of a generic "fix all the places" ticket that's hard to complete and close.
