### ISSUE TITLE
Cannot call emu.frameadvance() in Lua Console

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#414]
```
What steps will reproduce the problem?
1. Open Lua Console.
2. Type emu.frameadvance().
3. Alternatively, call any user-defined Lua function that internally calls 
emu.frameadvance().

What happens:
LuaInterface.LuaScriptException: attempt to yield across metamethod/C-call 
boundary

What should happen:
It should just work. :)


BizHawk 1.9.3, tested this with bsnes core.
```

Original issue reported on code.google.com by `denilsonsa` on 23 Mar 2015 at 4:17

**Comment by vadosnaprimer** [comment]
Might be invisible to the OP from here, but emu.frameadvance doesn't advance the frame like the hotkey does. It simple gives control back to emulator until the next frame occurs.

Such functions must have a "fail gracefully" logic for lua console.
