### ISSUE TITLE
Corvette ZR-1 Challenge (Race America) has glitches in Bizhawk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#415]
```
What steps will reproduce the problem?
1. Play a race in Corvette ZR-1 Challenge (European Race America).
2.
3.

What is the expected output? What do you see instead?
The road on the top screen is not supposed to have glitches - it does.

What version of the product are you using? On what operating system?
Bizhawk 1.9.3, Windows 7

Please provide any additional information below.
Only the European version has glitches.

```

Original issue reported on code.google.com by `Reinc...@gmail.com` on 6 Apr 2015 at 11:51

Attachments:
* [Corvette ZR-1 Challenge (E) [!].nes](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-415/comment-0/Corvette ZR-1 Challenge (E) [!].nes)

**Comment by zeromus** [comment]
FYI this rom isnt supported in quicknes, so it's a neshawk-only bug

**Comment by alyosha-tas** [comment]
in line 304 of NES.Core.cs, change 

cpu_step &= 31;

to

if(cpu_step == 5) cpu_step=0;


The original code did not properly cycle through the CPU sequence. This fixes the problem.

**Comment by zeromus** [comment]
Dang it, how embarassing. I dont know what I was thinking when I did that, apart from it being an idiotic optimization. Feel free to commit fix

**Comment by alyosha-tas** [comment]
I can't commit stuff but I added the fix to my existing pull request. (I couldn't figure out how to make a seperate one.)

**Comment by zeromus** [comment]
Why are there files deleted in that PR?

**Comment by alyosha-tas** [comment]
Sometimes I mistakenly upload files to the main page and not as updates to the existing files.

Look at BizHawk's main page and you will see a stray TIA.cs sitting at the bottom of the page from my last PR. Oops!

So yeah just me making a mess, sorry about that!

**Comment by zeromus** [comment]
I dont understand. I'm asking if your current PR is ready to go.

**Comment by alyosha-tas** [comment]
Oh, yes it is ready to go.

**Comment by hegyak** [comment]
Closed by the above Pull Request.
