### ISSUE TITLE
Wario ware inc(e) Gba last phase graphics issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#416]
```
While register the movie during the last phase of wario ware inc tends begins 
to cause problems in terms of graphics(glitch and black screen).

```

Original issue reported on code.google.com by `leobrixi...@live.it` on 6 Apr 2015 at 1:18

Attachments:
* [1012 - Wario Ware Inc (E)(Cezar).2015-04-06 15.15.56.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-416/comment-0/1012 - Wario Ware Inc (E)(Cezar).2015-04-06 15.15.56.png)
* [1012 - Wario Ware Inc (E)(Cezar).2015-04-06 15.16.11.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-416/comment-0/1012 - Wario Ware Inc (E)(Cezar).2015-04-06 15.16.11.png)
* [1012 - Wario Ware Inc (E)(Cezar).2015-04-06 15.16.20.png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-416/comment-0/1012 - Wario Ware Inc (E)(Cezar).2015-04-06 15.16.20.png)

**Comment by nattthebear** [comment]
I tried this and couldn't get it to happen on mgba
