### ISSUE TITLE
breakpoints not working with N64 emu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#428]
```
What steps will reproduce the problem?
1. start N64 emulation with the default settings and set a write breakpoint
2. wait until the breakpoint should be triggered

What is the expected output? What do you see instead?
I expect the emulation to be paused and the debugger window to show the 
instruction triggering the breakpoint, but nothing happens instead.

What version of the product are you using? On what operating system?
v1.9.4 on Windows7 64-bit



```

Original issue reported on code.google.com by `mantox...@gmail.com` on 27 May 2015 at 3:33

**Comment by Meerkov** [comment]
I had a similar issue in TurboGrafix16 games. The issue was that you can't set breakpoints on the Main Memory section. There is no error or warning if you do try to set one there. 

This is potentially the same issue. Try a higher address space (in TurboGrafix, e.g. add 0x2000 to the address to find the real address).

**Comment by zeromus** [comment]
The memory mapping is more complex on the n64, the same memory can be mapped to several places. 
Additionally, at the present, the debugger just hangs if it does get a breakpoint.

**Comment by adelikat** [comment]
There was a real bug here, that has been fixed (memory breakpoints in N64 weren't firing)

**Comment by vadosnaprimer** [comment]
The author is expecting the debugger to pause the core and show the instruction, I think this is exactly what Wyster added in his recent patch (which hopefully turns into a PR).

TurboGrafix is (or was) probably lacking the System Bus memory domain? Doesn't sound relevant here.
