### ISSUE TITLE
Save files not cleared when using savestates on bios

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#441]
```

What steps will reproduce the problem?
1. Load Game & Watch Gallery 4
2. Select the core as mGBA OR go to settings and select Skip Bios to FALSE.
3. During the bios boot, make a savestate
4. Wait until the game loads and shows a red backdrop.
5. Load the savestate.

What is the expected output? What do you see instead?
http://i.imgur.com/KfB0cXz.png
I should be seeing the red background with 102 lag frames consistently.


What version of the product are you using? On what operating system?
BizHawk-1.10.0 Windows 8.1

Please provide any additional information below.
Technically works in any game with a save, but since Game & Watch gallery 4 
autosaves, and its appearances is red at blank file but blue when you save, 
that was used as an example.

```

Original issue reported on code.google.com by `lunjess...@gmail.com` on 18 Jun 2015 at 1:56

**Comment by nattthebear** [comment]
I'm able to easily reproduce this on mGBA; savedata is not being stored in savestates.  I'm not able to reproduce this at all on VBANext.

**Comment by zeromus** [comment]
Whether savedata should go in savestates is some kind of controversial topic I'm not sure I've ever heard resolved clearly, it's possible for different programmers to have selected different approaches without ever knowing it.  Major pain in the butt. Anyway, the needs of TASing should resolve it firmly in favor of keeping savedata in savestates, but many casual gamers hate it.

**Comment by nattthebear** [comment]
a1f3b3d
