### ISSUE TITLE
TAStudio breaks states if input is edited during emulation

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#446]
1. Create/ take a random project.
2. Emulate some fresh greenzone from beginning, run integrity check over it. It passes.
3. Unpause emulation and try editing input while new greenzone is being created. New integrity check shows broken states on where playback was when you edited it.
4. Same happens if you have autorestore on, edit input, and then edit it again before it comes to the green cursor to pause.

Looks like input changes interrupt state saving.

**Comment by adelikat** [comment]
Fixed
