### ISSUE TITLE
SVN or Commit number/ID not updating correctly

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#451]
I manually ran the subwcrev.sh to see what was going wrong as every new build since we moved to Git, has been broken for me.  The Output is below from the command line.

BizHawk\Trunk\bizhawk>subwcrev.sh
Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Unable to determine upstream SVN information from working tree history

D:\Emu\BizHawk\Trunk\bizhawk\subwcrev.sh: line 11: /Properties/svnrev.cs.tmp: No
 such file or directory
cp: cannot stat `/Properties/svnrev.cs.tmp': No such file or directory

**Comment by marzojr** [comment]
This happens because BizHawk is no longer in SVN, but in Git. The same issue happened with Gens rerecording after the move, and I fixed it in this commit: https://github.com/TASVideos/gens-rerecording/commit/d08a6a8d2bd342800f5e81e4fb0ce93088b7170d

Something like this may serve as a base for BizHawk.

**Comment by Sappharad** [comment]
As far as I know, you don't need to run the scripts anymore to update the version number. The version project runs a tool that does it for you. I believe that zeromus or someone updated the tool to support git.

**Comment by zeromus** [comment]
You shouldnt use the .sh unless youre building outside of visualstudio. Visual studio does indeed use a tool I made which finds a git executable on your system and uses that.

If that tool isn't working for you, then we need to debug it.

The .sh was made to only work for git checkouts of an svn repository. There's no way it can work anymore without revising.

**Comment by hegyak** [comment]
Newer Builds for me, haven't given me anything that resembles a GIT or SVN number or Commit Hash or anything else.  Just SVN 0

**Comment by hegyak** [comment]
This issue was caused by a VERY bad Clone method.  Somehow I mixed GIT and SVN, at the same time.
