### ISSUE TITLE
Play Movie Dialog Ignores Subfolders

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#452]
I made a quick TASProj file for Super Mario 64.  Then I copied it, a BUNCH.  I took the Copied TASProj files and put them into, Movies\Mario.  The Play Movie Dialog Box ignores the subfolder named Mario.  Or any other folder.

If this is necessary to prevent the bug related to the folder TAStudio states, So be it.  I am fine with this.

**Comment by solarplex** [comment]
Within Play Movie Dialog Box, it's selected to only show .bk2 files, you can set it to show TASProj. Is that what you're looking at? I can't seem to reproduce a subfolder not showing up, all my folders show up.

**Comment by adelikat** [comment]
There's a checkbox to show subfolders, it is off by default
