### ISSUE TITLE
N64 - Jabo not applying options most of the time

### ISSUE THREAD

**Issue by Yadokingu** [TASVideos/BizHawk#456]
Jabo will not apply some selected options ~90% of the time. I can say this for certain for the "Copy Framebuffer" option, as it fixes the pause delay in Ocarina of Time Master Quest, but I think "Force Z Compare" and maybe others might be effected as well.

**Comment by pjgat09** [comment]
This might be a problem with accessing the registry (which is required to change Jabo settings). b2b70fb will display more information in the event accessing the registry fails. Try those changes with the log window active and let us know if you see any relevant errors.

**Comment by pjgat09** [comment]
I haven't heard back about this, so I am going to close this issue. Please reopen it if you are still having trouble and can give us new information to work with.
