### ISSUE TITLE
N64 - Fix pause delay in Ocarina of Time - Master Quest (U) and (J)

### ISSUE THREAD

**Issue by Yadokingu** [TASVideos/BizHawk#457]
All Ocarina of time games have a bug where when you press pause, the pause menu only comes up after multiple seconds of delay.
Emulators like PJ64 and Mupen64+ fix this bug by patching one byte in RDRAM. Sadly the mupen+ devs seem to have forgotten the Master Quest versions of the game. It would be great if you could patch this.

The bytes are in RDRAM and as follows:

Zelda no Densetsu - Toki no Ocarina GC URA (J) (GC) [!].z64 : 1DB78B
Legend of Zelda, The - Ocarina of Time - Master Quest (U) (GC) [!].z64 : 1DB748

Both have to be patched to 2 (unsigned).

**Comment by pjgat09** [comment]
It looks like you meant 1DB74B for the USA version. This is fixed in 0bb994b.

**Comment by jerajera** [comment]
> All Ocarina of time games have a bug where when you press pause, the pause menu only comes up after multiple seconds of delay. Emulators like PJ64 and Mupen64+ fix this bug by patching one byte in RDRAM. Sadly the mupen+ devs seem to have forgotten the Master Quest versions of the game. It would be great if you could patch this.
> 
> The bytes are in RDRAM and as follows:
> 
> Zelda no Densetsu - Toki no Ocarina GC URA (J) (GC) [!].z64 : 1DB78B Legend of Zelda, The - Ocarina of Time - Master Quest (U) (GC) [!].z64 : 1DB748
> 
> Both have to be patched to 2 (unsigned).

Noob here - wtf does any of this mean, does this mean that I change "1DB74B" to "2"? Is "unsigned" a part of the 2?
