### ISSUE TITLE
Add luasocket support

### ISSUE THREAD

**Issue by Sn0wCrack** [TASVideos/BizHawk#458]
If it would be possible to add luasocket support directly into the BizHawk lua interpreter.

**Comment by Dicatoro** [comment]
@Sn0wCrack It's possible to use the 0MQ lua binding with Bizhawk. It's not TCP but better than nothing.

**Comment by zeromus** [comment]
if bizhawk's lua can load the luasocket dll then we won't be integrating it. i don't know what the status is of bizhawk's lua loading dlls.

**Comment by vadosnaprimer** [comment]
Using this example, I couldn't access any socket functions:
http://www.lua.org/pil/8.2.html

I put luasocket.dll (and what it comes with) in the EmuHawk.exe folder, and this code
```
socket = assert(package.loadlib("luasocket.dll", "luaopen_socket"))
socket()
```
crashes the emu. Without `socket()` it works, but what's the point then.

**Comment by zeromus** [comment]
check stackoverflow, theres a post about it. it isnt easy.

**Comment by vadosnaprimer** [comment]
If you mean yours, it refers to lua version of sockets (as do all stackoverflow questioins), not dll (that comes with beta releases). There were some general advices how to load dlls, but they refer to very unclear docs that provide zero samples. So the only example code I found didn't work. Right now I'm getting `LuaInterface.LuaScriptException: userdata` with the above code. And as I said, non-beta releases provide lua version sockets, and it works by simply using `socket = require("socket")`.

**Comment by zeromus** [comment]
I dont understand "lua version of sockets" vs "dll that comes with beta releases". I just followed my instructions again, and it worked perfectly. I added `socket = require("socket"); print(socket);` and it worked perfectly. Then, believe it or not, I repeated these steps on the latest git code and it worked perfectly. Why butt your head against it? Do it the way I worked out.

**Comment by vadosnaprimer** [comment]
I know this one works. But you mentioned loading luasocket.dll, and that's what I also tried.
"socket.lua": http://files.luaforge.net/releases/luasocket/luasocket/luasocket-2.0.2
"luasocket.dll": http://files.luaforge.net/releases/luasocket/luasocket/luasocket-2.0-beta2-win32

Yes, the first one still has core.dll, but it also has sockets.lua, and it's exactly what allows plugging it in via `socket = require("socket")`. The second one only has luasockets.dll, so it requires precisely loading the dll itself, and it's what's not working. I honestly don't care as long as there's a way to use sockets with no problem. But the issue addresses embedding luasockets.dll, and you said we might be embedding it if it doesn't load already. So it's funny: it doesn't quite load, but you can use sockets the other way, which is probably what people don't want, but I don't know for sure.

**Comment by zeromus** [comment]
I don't care why one works or doesn't either, as long as one of them works, somehow. Our lua is garbage. All lua is garbage. It's a miracle if a module EVER works, ANYWHERE. This bug is old and predates my discovery there's another way besides loading the dll to get luasockets running. Who cares about the damn dll.

**Comment by YoshiRulz** [comment]
see #1080
