### ISSUE TITLE
PSX OSD Overlap issue

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#460]
When I use View Input on the PSX Core, I get this image:
http://s530.photobucket.com/user/hegyak/media/Spyro%20the%20Dragon%20USA.2015-07-19%2021.20.55.png.html

What's wrong with it is that the 0 becomes a 1 and is Overlapped by my button press.  In this instance, I was using Virtual Pad and Pressing and Holding the Start button.

**Comment by zeromus** [comment]
Some code in the input display, which is amazingly complex, was hardcoded to replace a two-dimensional "    0,    0," with an empty string, so the pink and the white wouldnt conflict. It needed to be "    0," instead to work with the PSX disc select control, which is what youre seeing here.
