### ISSUE TITLE
Ram watch, memory domains, and breakpoints

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#462]
Ram watch lets you rightclick an address (how about hex edit, and others?) and add a breakpoint to it. This should be forbidden for non-systembus domains*
Todo:
1. Introduce strong-concept awareness of what the sysbus memorydomain is, and only allow adding breakpoints to sysbus domain. Maybe gray them out, maybe be more informative.
2. Make it more clear what memdomain youre in (it's printed, but not labeled)
3. Check other tools for similar problems

Other ideas I dont think are good:
- Have the core translate one physical address into several (or none) logical sysbus addresses. 
  Other ideas I think are good:
- Documentation urls about memory mapping
- In the distant future, cores should be able to mount non-sysbus domains for breakpoints. For example: break on ppu read of vram

**Comment by adelikat** [comment]
This was fixed some time ago, menu item is only visible if all selected watches are system bus
