### ISSUE TITLE
readbyterange off-by-one

### ISSUE THREAD

**Issue by notwa** [TASVideos/BizHawk#463]
readbyterange returns one more value than requested. writebyterange probably has a similar issue.

eg.
```
> mainmemory.readbyterange(0,4)
"0": "60"
"1": "26"
"2": "128"
"3": "9"
"4": "39"
```
specifically, this goes against the documentation:

luatable mainmemory.readbyterange(int addr, int length) 
Reads the address range that starts from address, *and is length long.*

**Comment by zeromus** [comment]
Besides fixing this, I changed it functionally: the array indices had been previously set equal to the address, which is weird, and at least not the same as FCEUX, and I presume so for every other emulator. Besides this, the code, including the bug you wrote about, gives every indication of the previous behaviour being a bug. So whatever, it acts normally now.
