### ISSUE TITLE
Prescale (2x-16x) and GDI+ (bug)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/BizHawk#465]
BizHawk 1.11.0

DISPLAY CONFIGURATION:
display method -> GDI+
scaling and filtering -> final filter -> bilinear
Set prescale from 2x to 16x, and press "OK" - emulator will crash

**Comment by zeromus** [comment]
fixed in f8b840ea41646a083f2037da1e213cf4f8db3721
