### ISSUE TITLE
Crash after opening options (Castlevania Chronicles V1.0 - PSX)

### ISSUE THREAD

**Issue by JlNX** [TASVideos/BizHawk#467]
![2015-07-26 17_55_14-](https://cloud.githubusercontent.com/assets/13512575/8896376/78623ba6-33bf-11e5-9d10-1a320ccf6761.png)
Was going to the options on Castlevania Chronicles for the PSX when I got this crash.

**Comment by zeromus** [comment]
Same crash as other. Same cause. Unrelated to PSX or castlevania.

**Comment by YoshiRulz** [comment]
other is #466
