### ISSUE TITLE
Lua: Feature request: forms library enhancement: oncloseevent

### ISSUE THREAD

**Issue by Warepire** [TASVideos/BizHawk#469]
Being able to receive a "closed" event for the forms created with the forms library in the BizHawk Lua implementation would be nice, currently if I accidentally close the form the script cannot have any idea of that it has happened.

The suggestion is to make this similar to the button event, meaning that a Lua function can be registered as a callback on the "closed" event, and thus get called if the form is closed.

**Comment by adelikat** [comment]
implemented in 64126fb
