### ISSUE TITLE
[minor]README.md does not use proper Markdown formatting (diff included)

### ISSUE THREAD

**Issue by evknucklehead** [TASVideos/BizHawk#475]
Obviously, this applies to the Github project page and not the actual program.

In particular, the links in the file do not appear as intended due to the formatting errors.

[Here's](https://gist.github.com/evknucklehead/9fd5dab70e0b80284fae) a Gist version of the diff file I made, since I don't know how to upload it any other way. Hopefully this makes it easy to fix the formatting.

I couldn't properly fix the Features link, as the existing file didn't have an actual URL for that, but the formatting is in place for whoever wants to add the correct link.

**Comment by zeromus** [comment]
Thanks for alerting us to this, we had pasted the markdown from googlecode without checking whether it worked on github
