### ISSUE TITLE
Bizhawk does not take simulated keypresses

### ISSUE THREAD

**Issue by cklidify** [TASVideos/BizHawk#477]
Bizhawk does not take simulated keypresses. I'm trying to make a TwitchPlays___ and I'm using [OpenTwitchPlays](https://github.com/Francesco149/OpenTwitchPlays) to do it. I've tried using PostMessage AND SendKeys to send the keypresses, but bizhawk still won't take them. Every other program I've tested it with works, but bizhawk doesn't :/

I was wondering if this was a problem on my end or a problem with the program.

If it's MY problem, how could I fix it?
If it's the program's problem, will it be fixed in the next update?

**Comment by zeromus** [comment]
bizhawk uses directinput for keystrokes. every other program youve tested probably does not use directinput for keystrokes.

WHY does it use directinput? I don't remember. But we're not changing it.

**Comment by zeromus** [comment]
Anyway I see his project is c#. You should paste his code into a modified bizhawk instead of trying to have one opensource .net program control another opensource .net program

**Comment by cklidify** [comment]
I have no idea how to do that :x

I don't know anything about C# or C++, I've only ever dipped my feet in lua :/

Could you possibly walk me through how to do that? I would greatly appreciate it!
Thanks in advanced!

**Comment by zeromus** [comment]
if you only did things you already knew how to do then you wouldnt know how to do anything at all

**Comment by cklidify** [comment]
I never really thought about it like that. I'll give it a try, thanks!

**Comment by zeromus** [comment]
check
http://pastebin.com/2xFpS1DH
and recent commit for server-side part
using this you can send keystrokes to a bizhawk process

**Comment by cklidify** [comment]
Thank you soo much!

**Comment by zeromus** [comment]
Please write back whether this works for you so I can close the issue

**Comment by cklidify** [comment]
It's all working, you can close the issue!

**Comment by zeromus** [comment]
https://github.com/AndersMalmgren/FreePIE/blob/master/FreePIE.Core.Plugins/KeyboardPlugin.cs
use this keys list as a reference (it's the slimdx internal private arbitrary keys enum)
