### ISSUE TITLE
ClientControls not subject to hotkey-over-gamepad priority control

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#478]
"hotkeys which arent handled as actions get coalesced as pollable virtual client buttons"
-> HotkeyCoalescer.Receive(ie);

Presently, only "hotkeys which are handled as actions" get priority over gamepad when requested.

We need to find a way to make ClientControls-bound buttons get intercepted earlier and blocked from the core's input

Another relevant line:

Global.ClientControls.LatchFromPhysical(GlobalWin.HotkeyCoalescer);

There you see ClientControls are set from the HotkeyCoalescer. The ClientControl bindings arent known at the point where the prioritization happens.

The whole system may need to be configured a bit to let the controllers give feedback about what bindings theyre absorbing

**Comment by adelikat** [comment]
This was "fixed" awhile back
