### ISSUE TITLE
BizHawk BEX SDL.dll_unload Crash while starting to record a new movie

### ISSUE THREAD

**Issue by purify64** [TASVideos/BizHawk#479]
Im getting a BEX error when i try to record a new movie in WipeOut64.
Here are some info:
Im using the BizHawk version 1.11.1.
Im currently using Windows 8.1 with DEP activated.
I cant add Bizhawk as exception for DEP.

Here is a screenshot of the appearing error:

![bizhawk crash](https://cloud.githubusercontent.com/assets/13812106/9290146/3eaa2dd2-4388-11e5-8ca5-ca7cd77b51f8.jpg)

I hope someone can help me, thanks in advance!

**Comment by zeromus** [comment]
See if it happens when you "reboot core" as well.
disable your security software.
turn DEP off temporarily to see if that's even related.

**Comment by purify64** [comment]
When i press "reboot core" the same crash appears, with the same error message.
i turned DEP off and rebooted my PC now it is working as intended.
Still i would like to keep my DEP on. Is there any reason why i cant add this as exception when DEP is turned on ? Thanks for the quick reply... i would be glad if you could still give me some advice :(

**Comment by zeromus** [comment]
some software is incompatible with DEP. thats why it's optional. I don't know why windows has marked emuhawk.exe as forbidden-to-disable-dep. You should ask the google (seems like there should be a way to tell windows to STFU and do it anyway), but I'll do some digging on my own. Can't promise anything though.

FWIW, it's the crusty old n64 emulator core that's violating the DEP, nothing we did.

**Comment by purify64** [comment]
I tried to edit a entry in the regestry about it but windows keeps ignoring the exception.
So I guess there is no way in editing the old n64 core ? or are there other emulation cores available?
Sorry the questions might seem stupid but im totaly new to the whole emulation stuff.
I will go on trying to find a solution to tell windows to "STFU"... otherwise i need to reboot my PC everytime i want to use BlizHawk. If you find something please contact me! As always thanks again for the quick support :)

**Comment by zeromus** [comment]
We can debug half the n64 stuff. This kind of thing is pretty easy to debug. But theres no guarantee its in the half of n64 stuff we can debug, and I doubt anyone will do it. You're abnormal for changing the windows defaults. It's easier for you to quit paddling against the current..

**Comment by zeromus** [comment]
http://stackoverflow.com/questions/350977/how-to-make-my-program-dep-compatible
This is here for my future reference.
For you I recommend trying this:
http://www.cgsoftlabs.ro/studpe.html (follow to) http://www.cgsoftlabs.ro/zip/Stud_PE.zip
This program's UI is bad. Open emuhawk.exe with it, pick the Headers tab, and look at the left of that tab.  It begins with EntryPoint (rva) and EntryPoint (raw) but that area is actually scrollable. Scroll down to DllCharacteristics and click the plus, then disable NX Compatible. Finally click SAVE to file at the bottom right of the window. Now, the file timestamp won't be modified, but it's been edited to remove the NX flag.

Let me know if youre able to fix emuhawk.exe this way

**Comment by purify64** [comment]
I will try this out. If i can fix it this way by myself i will let you know.
Thanks for all the info, your help is very appreciated!

**Comment by zeromus** [comment]
I think I have a tool made for the build process that will simply disable /NXCOMPAT on the exe. You never let me know if that's adequate for solving the problem. It may need disabling on the mupen + plugin dlls as well?

**Comment by purify64** [comment]
If you like you could send me the tool and i will test it out.
I dont need the mupen + dlls i think, they are the core for n64 games right?
Sorry for the late response but im not very active on github.

**Comment by zeromus** [comment]
https://github.com/TASVideos/BizHawk/blob/master/Build/BizHawk.Build.Tool.exe

run:
BizHawk.Build.Tool NXCOMPAT --target c:\path\to\bizhawk\emuhawk.exe --value 0

i think that should do the trick

**Comment by zeromus** [comment]
closed due to mystery
