### ISSUE TITLE
Rewinding doesn't update rerecord count

### ISSUE THREAD

**Issue by Beefster09** [TASVideos/BizHawk#480]
When recording a movie, rewinding will not update the rerecord count.

What is expected: The rerecord count should increase by one when you rewind, but only once until you advance at least one frame after rewinding.

What happens: The rerecord count remains unchanged.

How to reproduce:
Record a movie with the rerecord count showing
Rewind

**Comment by adelikat** [comment]
You can't rewind when recording a .bk2 movie.  If that is what you are doing, please explain how you are even managing to do it.

If you are using TAStudio, then rewind shouldn't increment the counter because upon stopping rewinding it goes into play mode and does not change any input
