### ISSUE TITLE
Don't reset scrolling in Hex Editor after Core Reboot

### ISSUE THREAD

**Issue by Neui** [TASVideos/BizHawk#481]
When restarting the core (CTRL + R) the Hex Editor resets itself back to top. This is annoying when hacking and wanting to look at a area of the WRAM (or whatever the user wants to looks at)

So my suggestion is not to reset it back to the top.

**Comment by zeromus** [comment]
Since this is not likely ever to get fixed (core rebooting re-initializes virtually everything) your best bet is going to be to bind a hotkey to hard reset.

**Comment by adelikat** [comment]
Actually it isn't so hard, all tools have a Restart method, and in that method we could tell it is A) the same rom B) what the scroll bar position was.  So this wouldn't be hard to do.

But also yeah, using the Power button (mappable in the Controller Config) is probably what you really want to be doing

**Comment by Neui** [comment]
Does the Power button reload the rom? I don't think so.

I do some changes, compile/assemble it and then i want to test and it is quicker to go to the emulator, press CTRL+R (maybe load a state) and try it out and look at it.

But if the Hex Editor resets it might be annoying to always go to the adress again, look at it and maybe change it.
