### ISSUE TITLE
Over-rewinding crash while recording movies

### ISSUE THREAD

**Issue by Beefster09** [TASVideos/BizHawk#482]
Rewinding past a save state while recording a movie crashes BizHawk.

Steps to reproduce:
- Open any ROM
- Start recording a movie
- Create a save state
- Let the game run for a little bit.
- Go to the saved state
- Rewind

What I would expect:
- Rewinding after loading state will stop on the saved state. This would be my preferred behavior, as I consider save states to be more deliberate. Rewinding is more like an "Oh crap, I just want to redo the last 10 frames but my last savestate was 100 frames ago." feature when it comes to recording.
- Rewinding works as it does when not recording a movie and will let you rewind into a future frame that you were on before loading state.
- Rewinding is disabled while making a movie. (If all else fails)

**Comment by adelikat** [comment]
When RECORDING a movie, rewind is disabled for this exact reason.

It is completely impossible to do any behavior other than what you see with rewinding, because it relies on delta compression to be speedy and not resource intensive.

If you want to combine rewind and movie making, use TAStudio.

**Comment by Beefster09** [comment]
That's the thing. Rewinding isn't disabled for me while recording. Is there is a setting for that I'm missing?

At any rate, I'm pretty new to TASing, but now I have a system figured out that eliminates the need for rewinding. I really only use it now if I want to re-save a few frames back.

**Comment by zeromus** [comment]
Congratulations! You're the lucky owner of the only bizhawk in existence that allows rewinding while recording movies.  Or else the unlucky older of a very old bizhawk version. Please let us know which one you discover it is.

Your first suggestion is not great. It'd have to be some new menu option to rewind to the previous loadstate. As it is now rewinding is good for undoing a loadstate. Rewound past the loadstate? Just loadstate again.

**Comment by Beefster09** [comment]
I'm on 1.5.3, Windows 8, running an SMS game. Maybe there's a bug that allows you to rewind SMS games?

**Comment by zeromus** [comment]
Issue resolved: user using a 1.5 years old build.
