### ISSUE TITLE
Problem with starting new project from selected frame

### ISSUE THREAD

**Issue by Drflash55** [TASVideos/BizHawk#485]
When I start a new project from a selected frame, it works, but when I try to do it a second time, it doesn't respond to anything...
Which is a pain, because I need to have seperate parts for my TAS because I run out of ram due to how big the project is...

**Comment by zeromus** [comment]
memo: Right click frame, pick start new movie from here.

this feature seems completely broken. I suggest you don't even try using it until you hear it's working, something bad might happen.  Newer development builds should have less problem with running out of memory....

**Comment by adelikat** [comment]
Fixed
