### ISSUE TITLE
NESHawk - screen shake on Little Ninja Bothers (E)

### ISSUE THREAD

**Issue by adelikat** [TASVideos/BizHawk#487]
Little Ninja Brothers (E) [!] - goodnes 3.14
sha1:E85469D8FE0D4C058EE6EF3EED28E2D131EC0C22

Noticeable shaking on the intro "Culture Brain" screen, then later at about 600 frames in when the trademark/license part of the title screen shows up.

Correctly running in 50fps mode.

Nintendulator, FCEUX, Nestopia, and puNES run this cart in PAL mode, and do not have this shaking.

Seems to be a PAL timing issue, hence the write up.

Possibly related:
Similar shaking in:
Pro Action Replay (E) (REVA) [!] - goodnes 3.14
sha1:A65B6BC48E05C4CDBD221B811A17FBF174B45632

**Comment by alyosha-tas** [comment]
cpu_sequence_PAL in NES.CORE.cs should be 3,3,3,3,4   not    4,3,3,3,3

The clock on PAL NES is divided into 3.2 PPU clocks per CPU clock, so we would expected the extra full PPU cycle to appear on the last CPU cycle, not the first.

**Comment by hegyak** [comment]
Closed by the above Pull Request.
