### ISSUE TITLE
Lua: working directory is incorrect for event.onexit

### ISSUE THREAD

**Issue by rodamaral** [TASVideos/BizHawk#488]
For a given Lua script, the working directory changes for event.onexit.

What is expected: The working directory (for i/o operations) should remain the same, until onexit returns.

What happens: Outside event.onexit, the working directory is the same of the script.
Inside event.onexit, the working directory changes to EmuHawk's folder.

How to reproduce:
Write a script with io.open(filename) inside event.onexit and outside it and see that they create/edit the file in different directories.

**Comment by vadosnaprimer** [comment]
zeromus fixed it in https://github.com/TASVideos/BizHawk/commit/5e89e563d03cc53d6ddfbccc5e31590286fb6b5f
