### ISSUE TITLE
Hex editor ampersand escapes output?

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#490]
![amp](https://cloud.githubusercontent.com/assets/8139496/9567759/902b5cbc-4eeb-11e5-816b-58891937478b.png)

On the righthand side of the Hex Editor window, if the number 26 appears multiple times, it will render half as many '&' as it should.

In the circled area, address #0D80, you can see 26 appears 11 times, and 00 appears 5 times. Only 5 ampersands and 5 periods are printed, leaving blank space at the end out of line.

Above that, in #0D70 you can also see the end of the line prints only 1 ampersand and an empty space where the value is 2626.

This reminds me of the way HTML is escaped, & - > &amp;amp;. Maybe this is going through some sort of sanitizer?

**Comment by zeromus** [comment]
winforms uses & as escape code for hotkeys in some cases. I needed to transform them to &&
