### ISSUE TITLE
Cheat dialog glitch

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#491]
I've encountered this glitch. I can't quite recreate it, but it happens often. Sometimes if I close the emu with the cheat dialog open, next time I open the emu, the cheat dialog starts like this: 

![ab8mmh5](https://cloud.githubusercontent.com/assets/7338867/9586312/05d8e070-4fea-11e5-8fec-d2a96731b737.png)

I'm using Bizhawk 1.11.1

**Comment by zeromus** [comment]
How do you close the emu? X, File>Close, Alt+F4? Do you ever accidentally close the console log window?

**Comment by ReyVGM** [comment]
I always press the X in the window.

Sometimes there's a power outage and I close everything (browser, folders, emu, etc) extremely quick and hit power off. The computer shuts down fine, but I've noticed it happening more when I close everything and power off quickly.

**Comment by adelikat** [comment]
Fixed.
