### ISSUE TITLE
Cheat Dialog Request

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#492]
As someone that makes a lot of cheats, this causes me minor annoyances.

You know how an active cheat is highlighted in light-blue? Well, when you click on a cheat to select it to either turn it off or edit it, it gets dark-blue. Problem is, you can't tell if that cheat is on or off when that happens.
If you only have a couple of cheats on the list, that is fine, but not when you have dozens or hundreds. It gets chaotic sometimes when you're RAM searching and you need to add hundreds of results to see which is the one that works.

Would it possible to implement a checkmark or something next to the cheat-name signaling that cheat is enabled? Sort of like the VBA cheat dialog: 

![z](https://cloud.githubusercontent.com/assets/7338867/9586349/46a30aea-4fea-11e5-8950-2d18811e3955.png)

**Comment by adelikat** [comment]
This feature already exists, and is just not on by default.  Go to columns -> On to enable the "On" column, which will display its status
