### ISSUE TITLE
Lua GUI module coordinate origin differs in NES cores

### ISSUE THREAD

**Issue by fo-fo** [TASVideos/BizHawk#498]
The coordinate origin of `gui.drawRectangle()` (and the other GUI functions) is different in QuickNES core than it is when using the NesHawk core.

How to reproduce:
- Load the *Castlevania.lua* script that ships with BizHawk.
- Load Castlevania 1 ROM.
- Switch between the QuickNES and NesHawk cores; the bounding boxes are drawn at different places 

The NesHawk behavior is correct, or at least it's what seems to be assumed by *Castlevania.lua*.

**Comment by zeromus** [comment]
nes > graphics settings > clip top and bottom.
not a bug.

**Comment by zeromus** [comment]
oops, i was wrong. don't tell anyone
