### ISSUE TITLE
BizHawk load error while opening a playstation game as .cue "System.ArgumentOutOfRangeException"

### ISSUE THREAD

**Issue by purify64** [TASVideos/BizHawk#499]
When i try to open the game Lord of Fist and Shaolin, both are the same game just from other regions, i get a "load error" from the playstation core.
The error looks like this:
![load error](https://cloud.githubusercontent.com/assets/13812106/9885670/bbcdebc0-5be6-11e5-8962-ed3a96647e05.jpg)
The german text ist saying:
"The Index was out of range. It must be non-negative and less than the listing. Parameter name: index"

After this message he simply abort the loading process.

I hope someone can help me, thanks in advance!

**Comment by hegyak** [comment]
Can you post the text from the .Cue file?  I bet the .Cue file is wrong or something.

**Comment by purify64** [comment]
So the .cue file of Lord of Fist says: 

"FILE "lord_of_fist.bin" BINARY
   TRACK 01 MODE2/2352
      INDEX 01 00:00:00"

the .cue file of Shaolin says:

"FILE "Shaolin.img" BINARY
   TRACK 1 MODE2/2352
   INDEX 1 00:00:00"

both .cues are working for my ePSXe. Is there anyway to fix the .cues ?
thanks for your quick response!

**Comment by zeromus** [comment]
yes. fix the cues by removing the ridiculous quotes from the beginning and end.
i assume you manually built these cues by pasting something from a forum.
you could avoid these problems in the future by not manually building cues.

**Comment by zeromus** [comment]
I just added code to make error handling more rigorous (it wouldve given you clues about the erroneous content of the cue) and then made the cue parsing handle the garbage you fed it.

**Comment by purify64** [comment]
i dont think you quite got me...
i quoted the .cue files so you could see what they actually say!

They are saying: 

FILE "lord_of_fist.bin" BINARY
   TRACK 01 MODE2/2352
      INDEX 01 00:00:00

**Comment by zeromus** [comment]
so then make lord_of_fist.bin exist

**Comment by purify64** [comment]
Alright sorry im really new to all of this.
I actually fixed it with a directory with only consist out of the .cue and lord_of_fist.bin.

Still tahnks for the fast response.

**Comment by zeromus** [comment]
Can you please give me a directory listing of what it looked like when it didn't work? I want to actually fix the bug

**Comment by zeromus** [comment]
Guess we'll never know

**Comment by maxsize213** [comment]
Sorry for being late, but I fixed it by downloading the BIOS files.

**Comment by zeromus** [comment]
You didn't fix that bug by using a bios file.
