### ISSUE TITLE
SNES emulation does not work on OSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by AndreiBarsan** [TASVideos/BizHawk#501]
I have installed BizHawk on OSX and while the program itself runs fine, whenever I try to load a SNES ROM, I get the following error message:

"Couldn't locate the executable for SNES emulation for profile: Performance. Please make sure you're using a fresh dearchive of a BizHawk distribution."

<img width="539" alt="screen shot 2015-09-20 at 4 42 47 pm" src="https://cloud.githubusercontent.com/assets/1260898/9981213/bb98b206-5fb6-11e5-8801-16e0ffbb05b5.png">

**Comment by Sappharad** [comment]
SNES is not supported on OSX. Please refer to the list of supported systems here:
http://tasvideos.org/forum/viewtopic.php?t=12659

**Comment by Sappharad** [comment]
To elaborate more on this (now that I'm at a computer), I managed to build the SNES cores on OS X a few months ago. But the method in which BizHawk uses to communicate with the SNES cores isn't possible on OS X or Linux, which I didn't realize when I started. The only solution would require someone (probably me) to change how SNES talks to BizHawk to work the way the other cores like Genesis do it. 

At the moment, this isn't something I'm working on. There were rumors of a different SNES core being added at some point, which would work in a manner that would be easier for me to support on OS X. As far as I know, that's not happening anytime soon.

I may revisit this in a few months.

(Should I merge this into the issue with the giant list of OS X problems, or leave it here as a separate issue?)

**Comment by AndreiBarsan** [comment]
Thanks for the reply!

I guess this could be left as a separate open issue, while the list of OS X problems could maybe depend on it. This way, we would have the option of tracking progress for this separately from other OS X features.

**Comment by zeromus** [comment]
nah, i dont want 1000 bugs for missing osx features

**Comment by Sappharad** [comment]
Sorry, I forgot this was even logged as an issue anyway. It could have been closed several releases ago when SNES was added. 

It's probably worth closing all of the OS X issues at this point, since the WinForms client won't be supported on Mac from 2.0 onwards. (Still working on the replacement, slowly.)
