### ISSUE TITLE
User interface - TAStudio opened several thousand Set Markers dialogs

### ISSUE THREAD

**Issue by qqwref** [TASVideos/BizHawk#504]
I'm on version 1.11.1 (June 30, 2015) and was using TAStudio. I had selected a little over 4000 frames that I wanted to clear the inputs of (since they were after where the end of my movie should have been). I right clicked, but I must have accidentally hit the Set Markers dialog. The problem is that that spawned a sequence of thousands of dialogs: Marker for frame 113805, Marker for frame 113806, etc. The dialogs are modal and the Ok/Cancel/X buttons would only get rid of a single dialog. So, the only way to avoid force-quitting BizHawk (and losing my work) was to click through all those dialogs.

Hopefully it will be easy enough to add either an "are you sure you want to open X dialogs?" dialog, or a "Cancel All Remaining" button to the individual dialogs.

**Comment by adituv** [comment]
For what it's worth, you can hold escape to quickly cancel through all of these.  Anyway, it seems a bit strange to actually want to open multiple marker-creation dialogs at once, so I'll look at disabling Set Markers when more than one frame is selected unless anyone has any objections.

**Comment by adituv** [comment]
I'm no longer so sure about taking that route as the text on the UI suggests multiple dialogs are indeed intended.  I have instead created three different patches:

1. On clicking cancel, all remaining Set Marker dialogs are cancelled.
2. "Are you sure you want to open X dialogs?" configurable by a class constant
3. My original proposed fix.

https://gist.github.com/adituv/8a2b218a11d8db698465

The third option seems to have introduced some potentially dirty changes and I'm not 100% sure why they're all there, particularly the RecentSubMenu.Image change, but I double-checked and all those changes are introduced just by changing the text on the context menu item.

**Comment by zeromus** [comment]
Can we do option 1 AND option 2? Except confirm with adelikat or feos first that multiple markers makes sense.

**Comment by vadosnaprimer** [comment]
this all is still true for the latest revision? I did some tweaks to markers, don't know if it changes anything related to this feature. in any case, I'll look into it.
