### ISSUE TITLE
Memory Search forgets the memory domain I used

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#508]
I'm playing a GBA game. When I select a domain other than IWRAM in memory search, then close and reopen memory search, IWRAM will be selected instead of the one I had selected before. This is a request to change it so it remembers the domain I had selected, as per [zeromus' suggestion](http://tasvideos.org/forum/viewtopic.php?p=419242#419242).

**Comment by zeromus** [comment]
I had some ideas about this.
The memory could be associated with the rom.
Or it could be associated with the core.
If we build it right, you could just make a choice in the misc gui preferences to toggle between the two.
