### ISSUE TITLE
Hex editor misalignment

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#509]
As can be seen in [this screenshot](http://i.imgur.com/JrpGyno.png), part of a column in the hex editor can be cut off. This seems to happen when you right-click an EWRAM address of sufficient size and select "view in hex editor". I reported this here as per zeromus' suggestion.

**Comment by adituv** [comment]
I tested this in release 1.11.1 and can confirm it happens.  I also tested this against the master branch and it did not happen; it appears that this may have already been fixed.

**Comment by zeromus** [comment]
Sounds good, we'll let mugg check it on the next release before we close this out

**Comment by mugg91** [comment]
This particular issue looks fixed.
