### ISSUE TITLE
Reloading lua script crashes mGBA core

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#510]
When I have a lua script loaded in the mgba core and double click on the corresponding entry in the lua console (to disable it), it still shows "(1 Active)". After that, the emulator may throw exceptions or crash when clicking on the refresh icon on the lua console, or when hard resetting / resetting the core, etc.

**Comment by mugg91** [comment]
This issue is still present in 1.11.2 as it was in 1.11.1.

Btw, I'm not sure but loaded scripts may or may not be based on savestates from what I've seen, which may or may not be unexpected/unwanted behavior.

**Comment by zeromus** [comment]
From what I can see, the MGBA is currently unusable. I suggest not touching it. The flakiness youre encountering is a symptom of a deep, deep problem. Stay away.

**Comment by hegyak** [comment]
This appears to be working in 07d4ac846b5ecd7c63a5e5b19e3d4a950430dd74

I checked a simple Display Text LUA script and enabled/disabled the script and did a reboot of the mGBA core as well.
