### ISSUE TITLE
Hex editor, the wrong character gets selected

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#512]
Using VBA-Next.
When I click on a byte in the hex editor, then the wrong character is selected in the text on the right.
Please refer to "Hex editor problem" heading in this post:
http://tasvideos.org/forum/viewtopic.php?p=419941#419941

**Comment by jdpurcell** [comment]
There is an 0x26 (ampersand) in that row so it's probably the same as issue #490.
