### ISSUE TITLE
TAStudio ignores ClientSettings.json

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#515]
I am attempting to hide particular columns in TAStudio and keep them hidden when I load that movie.  It appears that ClientSettings.json is ignored.  But, that file does have columns marked as "Visible":False

Sample:
{"_emphasis":false,"Group":null,"Width":20,"Left":86,"Right":106,"Name":"Left","Text":"L","Type":0,"Visible":false,"Emphasis":false},{"_emphasis":false,"Group":null,"Width":20,"Left":86,"Right":106,"Name":"Tab","Text":"t","Type":0,"Visible":false,"Emphasis":false},{"_emphasis":false,"Group":null,"Width":20,"Left":86,"Right":106,"Name":"Down","Text":"D","Type":0,"Visible":false,"Emphasis":false},

Sample TASProj Movie File using Apple IIe  (GreenZone file was removed)
http://1drv.ms/1G7EtO9

Version Tested against:
emuVersion GIT master#4625bdc

**Comment by hegyak** [comment]
I looked at private void SetUpToolStripColumns() and there was nothing happening with the ClientSettings.json file.  The settings file is loaded in method:
private void GetClientSettingsOnLoad(string settingsJson)

But that string is not passed to the SetUpToolStripColumns() method.

**Comment by vadosnaprimer** [comment]
this commit didn't help, right?
https://github.com/TASVideos/BizHawk/commit/099e37ad76aeeca4d44a4061f60e4998e8fdc636

**Comment by hegyak** [comment]
As far as I was able to tell, the settings from the JSON file is not being passed to anything.  The settings are there.  They are saved.  But, the settings are not being applied.

**Comment by vadosnaprimer** [comment]
Must be because SetTasMovieCallbacks() effectively does nothing. I don't understand how it works, but it really look responsible. Though its only called when engaging tastudio or starting a new project, once it's fixed, it could also be called on project load.

**Comment by vadosnaprimer** [comment]
Fixed in https://github.com/TASVideos/BizHawk/commit/72b650d60623b31749d064f0d9dc10096ca6c606

**Comment by hegyak** [comment]
Broken in 1.11.5 and newer Releases.
