### ISSUE TITLE
Bug: Screenshots error window

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#516]
Just tried the new Bizhawk.

Have a couple of bug reports:

[b]1)[/b] I was testing the ability to take multiple screenshots at the same second, and I got this error if I press the key too fast.

![new bitmap image](https://cloud.githubusercontent.com/assets/7338867/10433727/46d71fd8-70e2-11e5-8f4c-f33ebe1a183f.png)

I changed between OpenGl and directx and same thing happened. Just in case it matters, I'm using Win7 64bit, i5, Geforce GT 640

**Comment by zeromus** [comment]
fixed in bff94896f9c37610fb9dec5c978dd19320c0aa50 and can you PLEASE pick ONE of (forum,bugtracker)
