### ISSUE TITLE
PSX "Gamepad" option is not working in Bizhawk 1.11.2

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#517]
PSX "Gamepad" option is not working.

At the PSX controller/memory card settings options, if I select "Gamepad" from the P1 controller options, the controls won't work in the game. I can bind keys to it just fine and it recognizes my input, but ingame, it won't work. If I switch to Dual Shock, it works fine though.

However, I can't use anything other than "Gamepad" or else all my previous  save states won't work. "Gamepad" option worked fine on the previous version.

I tried binding the keys to the keyboard and it still doesn't work as long as "Gamepad" is selected.

Also, if I select "Dual Analog", the entry resets to "Nothing" when I reboot the emu.

**Comment by hegyak** [comment]
Which game(s) do this?

**Comment by ReyVGM** [comment]
It's not a per-game basis, it happens with any game because I assume it's an issue with the PSX Controller option.

**Comment by zeromus** [comment]
fixed in f410ac04b896b692a10cd0d7e917da493bc9fd8e
