### ISSUE TITLE
Save/loading of a state glitches in Sonic2 2P mode

### ISSUE THREAD

**Issue by Tribeam** [TASVideos/BizHawk#519]
Tested on latest revision

Steps
1. Load up 2P mode in Sonic2.
2. Save State, then Load State.
3. Screen will become a mess.

Demonstration gif:
https://dl.dropboxusercontent.com/u/49758621/Bizhawk_Bug.gif

**Comment by hegyak** [comment]
I can confirm this on Master#2ed66e9 and using ROM:
Sonic The Hedgehog 2 (W) (REV00) [!]
SHA1:14DD06FC3AA19A59A818EA1F6DE150C9061B14D4
MD5:8E2C29A1E65111FE2078359E685E7943

Also the screen during two player mode is very, jumpy.  I am not using custom filters or enhancements.

Tested against DirectX 9, OpenGL and GDI+  Same Results.

To recreate:
Power on Game.  At the Title screen, select 2 Player Vs
In the new menu, press Start.
When the level is loaded, Save State.
Then Load State.
Error.

If the screen is fully redrawn (Level change, Results Screen) by the game itself, the error is gone until the next load state.

**Comment by alyosha-tas** [comment]
I looked at this but I cannot reporduce the error. I saved and loaded states in several circumstances (getting hit, scrolling the screen, jumping, and just standing there) but there were no errors. I'm guessing this was fixed by a commit by zeromus dealing with savestates.
