### ISSUE TITLE
(Windows) switching displays causes crash with data loss

### ISSUE THREAD

**Issue by nbyarnell** [TASVideos/BizHawk#522]
Running Windows 8 and Bizhawk 1.11.2, changing screen settings in any way (changing resolution OR active monitors) throws a SlimDX.Direct3D9.Direct3D9Exception: D3DERR_DEVICELOST: Device lost (-2005530520). I would just paste the stacktrace text, but the crash window can't be copied and pasted and BizHawk doesn't seem to dump logs after a crash, so here's a screenshot: 
![a screenshot](https://cloud.githubusercontent.com/assets/4673518/10555482/db685be0-7424-11e5-95d0-52299105539b.jpg)

This crash also results in all configuration changes and/or save data (but not savestates) that have been modified or created during the current session to be lost.

Steps to recreate:
1. Start BizHawk and change a configuration setting (screen size, controller setting, hotkeys, etc)
2. Load a ROM and begin playing. Use the game's internal save mechanism to save your game
3. Change the screen resolution or active monitors
4. Bizhawk crashes
5. Start BizHawk again. The configuration changes you made during the previous session should be gone.
6. Load the ROM you used previously. The save data should be gone.

I ran into this the really hard way by losing several hours of progress through Golden Sun: TLA last night.

**Comment by zeromus** [comment]
this should have been fixed in 1.11.3. Sorry about your data loss. Theres an option for flushing SaveRAM in the file menu in the future if you're investing a lot of time into a game. I'd use it every time I saved in-game if I was playing an RPG. Now, why can't it do that automatically? That's a long story....
