### ISSUE TITLE
BizHawk crashes on start

### ISSUE THREAD

**Issue by GusCaplan** [TASVideos/BizHawk#527]
When I start Bizhawk, I get 
![Image of Error](http://static.fluffycraft.net/images/issue.png).

I am on Win10, and I have run the bizhawk dependancies installer. The thing I don't get is that DX9 is from the win98 days, and this runs on other windows 10 machines, so what is going on?

**Comment by zeromus** [comment]
A lousy GPU driver is what's going on. This problem has been fixed since the last release.

**Comment by GusCaplan** [comment]
@zeromus latest release of bizhawk, or release of directx? I have the latest bizhawk. running `dxdiag` tells me i'm running directx10

**Comment by zeromus** [comment]
last release of bizhawk
