### ISSUE TITLE
Add RAM Search for Sega CD

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/BizHawk#531]
Would it be possible to allow or add the searching of RAM addresses (for cheat making) to the Sega CD core?

Right now only MESS and the Wii version of Gens allows such a thing. Hopefully this is something someone will add to Bizhawk in the future.

**Comment by zeromus** [comment]
what's this "ram search" i see in the tools menu when running a sega cd game

**Comment by ReyVGM** [comment]
I was under the impression that the CD specific RAM is not being seen by the RAM search. The Genesis RAM is seen fine, but not the CD one.

**Comment by zeromus** [comment]
what's this "CD PRG RAM", "CD Word RAM[0] (1M)", "CD Word RAM[1] (1M)", "CD Word RAM (2M)", nd "CD BRAM" I see in the ram search?

**Comment by ReyVGM** [comment]
Errmm.... I... never figured to look in the options...

*walks away in shame*
