### ISSUE TITLE
TAStudio: Disabling autohold is halfworking

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#534]
Steps to reproduce:

->Open a GBC ROM
->Open TAStudio
-> Right click on the "L"
->Let play some frames
->Right click on the "L"
->Drag yourself with the R column for some frames

I saw the L still pressed along with R. where it shouldn't be pressed. I tried dragging with s instead, it does too. I tried the same precise steps, but with R, it does too. So it's not exclusive to L.

Here is some images. As you can see, the autohold is disabled.

![beforedragging](https://cloud.githubusercontent.com/assets/15385566/10860898/d22a5c90-7f46-11e5-9f76-cc3d90bdc794.png)
![afterdraggingwithu](https://cloud.githubusercontent.com/assets/15385566/10860899/d22b452e-7f46-11e5-9c8c-19861e11a3c6.png)

**Comment by Niamek** [comment]
More info:
->If I click anywhere after the end of the movie(last frame of the movie), it will "slide" like that. So it's not the dragging.
->If I click anywhere before the end of the movie, then try to replicate, the bug will occur.
->If I advance one single frame AFTER the last frame of the movie (before trying to replicate the bug),this bug doesn't occur.

**Comment by vadosnaprimer** [comment]
you have to emulate at least 1 frame with your autohold pattern already changed to let it catch up and actually fetch it, so that afterwards it will do what you want when you draw outside the movie.

**Comment by Niamek** [comment]
Yes, that's the trouble. I'm not sure if it should be like that or not. I figured it shouldn't be(hence the bug report). How about forcing TAStudio to emulate the frame each time you mess with the autohold pattern?

**Comment by vadosnaprimer** [comment]
It's not a problem for me at all, just advance that frame with the mouse. The reason it was done like that is the way autohold works globally, it was obviously not designed with tastudio in mind, and I had troubles in fixing it. Someone who knows its internals better could try probably.

**Comment by Niamek** [comment]
It's not really a problem indeed. I figure it would be an improvement if this were modified. ^^ Thank you for your answer!

**Comment by vadosnaprimer** [comment]
Related http://tasvideos.org/forum/viewtopic.php?p=432622#432622
