### ISSUE TITLE
Cheat Dialog not Updating for SGB/GB

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#535]
Issue:
The Cheat Dialog will not update the Domains when switching from SGB to GB/GBC.

To reproduce:
Open a GB/GBC ROM in SGB Mode.
Open the Cheat Dialog.
Then reboot the core to make EmuHawk use the Gambette Core instead of BSNES Core.

The Cheat Dialog still says:
SGB WRAM
and other SGB RAM Domains instead of the GB/GBC Domains.

**Comment by zeromus** [comment]
More specifically, the cheats dialog doesnt update _at all_ when changing cores even between different platforms entirely
