### ISSUE TITLE
Heavy CPU usage when emulation is paused

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#541]
What steps will reproduce the problem?
1. Open Bizhawk
2. Open any ROM (currently tested with Master System & N64)
3. Pause emulation

What is the expected output? What do you see instead?
I expect BizHawk to use next to no CPU time when paused, certainly not more than when emulating. Instead I see that BizHawk maxes out CPU usage for a single core, with other threads still running on other cores.

What version of the product are you using? On what operating system?
1.11.3 on Windows 10 Pro x64

**Comment by zeromus** [comment]
bizhawk will never use 0% cpu when paused. The OSD must continue animating. However as of aug/sep 2015 I changed the throttle code and accidentally made it burn major cpu when paused
