### ISSUE TITLE
Maybe a Lua function for checking if a memory address exists

### ISSUE THREAD

**Issue by Tribeam** [TASVideos/BizHawk#542]
memory.isValid(int addr, string [domain] = null)
mainmemory.isValid(int addr)

Returns true if the address is valid(exists), false otherwise

This would allow users to ignore calling memory read/write functions for an address if it doesn't exist, and not have the emulator spit out messages like "Warning: attempted read of 2097551 outside the memory size of 2097152"

**Comment by vadosnaprimer** [comment]
Isn't the point of reading addresses actually using them? If you read an invalid address, you need to fix the script, not pretend you don't need the value anymore.

**Comment by vadosnaprimer** [comment]
The best option here would be to return domain sizes, that way you can check before accessing, and it would be way more meaningful than checking every address separately. Will do.
