### ISSUE TITLE
PSX - Crash Bash is treated as a 3do game

### ISSUE THREAD

**Issue by Harley201** [TASVideos/BizHawk#544]
I have no idea why but whenever I load the game through .cue (The only way) it says I don't have the bios for the 3do and it wont load through PSX, I know its a psx game because it also runs on Epsxe oh and because I ripped it from my game disk

**Comment by zeromus** [comment]
bizhawk does not have 3do support. pics or it didnt happen.

**Comment by Harley201** [comment]
Ooops, I forgot which it said, I will get a pic up by tomorow

**Comment by zeromus** [comment]
doesnt matter, this is caused by your using a lousy rip and it not being in the psx disc database. theres a complicated way to force it, but its better to just get a rip that isnt lousy

**Comment by Harley201** [comment]
Hmm I was using a rip that works perfectly fine, The game does have this terrible Crack prevention where all the menu's turn invisible and its just bad, also I tried 2 roms, one was american and the other one was pal and I had both bios

**Comment by zeromus** [comment]
If the rip works perfectly fine, then what are you doing here? Go find the SBI file to fix the copy protection.

**Comment by Harley201** [comment]
I mean in other emulators, I can run both rips on the 2 most popular psx emulators but I was trying to use this emulator with it (Because the RTC uses Bizhawk and I like to have a emulator for most of my in 1 executable) and it just wont work

**Comment by zeromus** [comment]
other emulators are garbage and read garbage disc images and then blow up later. 
put the cue in a m3u file, that should force it to load as psx, for now
