### ISSUE TITLE
Mega Drive: Might and Magic games give RAM errors

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#548]
I can't go past the title screen menus when playing Sega Mega Drive versions of Might and Magic: Gates to Another World and Might and Magic III: Isles of Terra on Bizhawk. The games show RAM-related errors. The first one says my party's data is corrupted and the second one says "could not initialize battery RAM".

**Comment by hegyak** [comment]
Might and Magic - Gates to Another World (UE) (REV01) [!]
SHA1:52E7ADE244D48BC282DB003D87C408E96DCB3D85
MD5:3238047522CAA4E27BE2720DA924777E

Confirmed in:
4f9061c45e37acc97553ce7bce65cdafe2eba7f7

**Comment by Reinc01** [comment]
What about Isles of Terra? I reported and error with this game too.

**Comment by hegyak** [comment]
Might and Magic III - Isles of Terra (Beta)
SHA1:D366D05644EB59A14BAF3C2E7281C1584630C021
MD5:AFF745871EB8474342BFCAD745449F64

There doesn't appear to be a "Good" Dump of this.  Just the Prototype ROM?

Error Confirmed in:
4f9061c45e37acc97553ce7bce65cdafe2eba7f7

**Comment by Reinc01** [comment]
Only a prototype, as far as I am aware.

**Comment by alyosha-tas** [comment]
SRAM data for these games is missing from the ROM header (0x1B0) 
Can just add them to the list of exceptions in SRAM.c in the gensplus gx file along with other examples.
I will do so when i get the chance and figure out how to rebuild the DLL
