### ISSUE TITLE
Conditional RAM Cheat Value Compare

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#552]
I would like RAM Cheats that use Compare to have a conditional modifier.  By Conditional Modifier, I mean Is Value;
Greater then
Less Then
Greater Then or Equal To
Less then or Equal To
Not Equal To

The Cheat Tool does support Equal To.  When this is added, please make Equal To the default compare condition.

**Comment by Asnivor** [comment]
@hegyak 

Is this just a really old ticket that was never closed? it looks like this was actually implemented at some point?

![image](https://user-images.githubusercontent.com/7911038/45498979-4285ff00-b773-11e8-9249-8c90b83953f2.png)

**Comment by hegyak** [comment]
I, haven't looked at BizHawk in a while.  I forget if it's only doing a compare on the address and value.  I know some cheats set other values in other addresses if the cheat address and value reaches a match.  Pretty sure this can be closed though.

**Comment by YoshiRulz** [comment]
Already implemented.
