### ISSUE TITLE
Pausing Glitch in Paper Mario 64

### ISSUE THREAD

**Issue by malleoz** [TASVideos/BizHawk#558]
Pausing at any time in Paper Mario will cause a 7 second long wait before the pause menu shows up. Normally the menu should appear after only a few frames, rather than several seconds. This occurs no matter which graphics plugin you use.

**Comment by zeromus** [comment]
someone needs to find out which mupen version this was fixed in

**Comment by thecoreyburton** [comment]
Is it fixed in the current mupen release? or is it something that was fixed and then later broken again?

**Comment by Rainchus** [comment]
If you start the game, hit frame advance to pause the game, then hard reset, there is a frame or two where all RAM is 00. If during this time you change the entire game's ram to FF and then start up a file, pausing will be only a few frames. Not really sure why this fixes it, but it does. Although it seems that not one specific address fixes this, because I tried to narrow it down and it didn't work.

**Comment by bonecrusher1022** [comment]
I know we have nagged about this a ton in various places, but is there any chance of this getting "fixed"/improved in the upcoming bizhawk release? We didn't figure out the exact mupen release that "fixed" it, but in both the major 2.5 release and last build [I tested a few weeks back](https://bitbucket.org/ecsv/mupen64plus-mxe-daily/get/2016-11-11.zip) had pausing improved to about half of what it currently is on bizhawk. I was waiting to see if one of them was going to look into it on their [github page](https://github.com/mupen64plus/mupen64plus-core/issues/206) but I haven't had a response in almost 3 weeks :/

**Comment by zeromus** [comment]
Rainchus says he fixed it by initializing the RAM to some other value. Fixing it to run in half the time sounds more like an accident than a fix. I doubt anyone will be motivated by shrinking an 8 second delay to a 4 second delay. I suggest you forward rainchus information to the mupen devs

**Comment by richard42** [comment]
I wonder if this is an issue with bizhawk.  Have any of you tried testing with the console-ui?  I tested this on my machine and couldn't replicate the issue.  When I tested, pausing and resuming was always instant.

**Comment by vadosnaprimer** [comment]
@richard42 bizhawk is using plain 2.0, were you testing against that version?

**Comment by richard42** [comment]
Oh, Bizhawk needs to upgrade then, because 2.0 is very very old.  I tested against the current head of our repository, which is about a year or 2 newer than the last release (v2.5.0)

**Comment by vadosnaprimer** [comment]
After all the changes that @pjgat09 had to do, converting won't be easy at all.It feels easier to just bisect and copy the fix.

**Comment by bonecrusher1022** [comment]
Hey it's me again. Any word on the fix for this? It's causing desync issues in the All Cards TAS.

**Comment by zeromus** [comment]
What _is_ the fix for this? I can't make heads or tails out of the linked issues.

**Comment by Isotarge** [comment]
GLideN64 + these framebuffer settings https://twitter.com/Isotarge/status/850671733874937856

**Comment by zeromus** [comment]
then can we get someone to confirm it's possible to specify that in the gamedb_n64.txt and set it for the defaults? @pjgat09 ?

**Comment by YoshiRulz** [comment]
Looks like you can set `GLideN64_CopyColorToRDRAM` but not `GLideN64_FBInfoReadDepthChunk` in the gamedb, thankfully it seems the latter wasn't necessary to bring the pause in line with console (at least, on the US version).

**Comment by YoshiRulz** [comment]
Tested again on 41109d6fc, using rom `SHA1:3837F44CDA784B466C9A2D99DF70D77C322B97A0`. Pausing still feels slow, but I decided to look for proper console comparisons. Someone compared Mupen in EmuHawk to console and found it was slightly slower in general: [1](https://www.youtube.com/watch?v=2yLpz6Dv7Dg), [2](https://www.youtube.com/watch?v=XsJjF35xKpo). They don't seem to have done the pause menu, so I'm assuming it's now back to slightly inaccurate, like the rest of the game. This inaccuracy doesn't appear to be limited to Paper Mario. Here's a similar loading screen comparison for SM64: [3](https://www.youtube.com/watch?v=mwTZwRNYtlw). For those reasons, I'm closing this issue, and will refer future humans to the [Mupen update Milestone](https://github.com/TASVideos/BizHawk/milestone/1) and specifically to #1718.

**Comment by Heart24** [comment]
Even following all the recommendations here and settings I still get the same pause glitch.

**Comment by blueYOSHI9000** [comment]
This is still an issue in the most recent 2.10 version when using default settings. It can be fixed in Mupen64 & GlideN64 by going to "N64" -> "Plugins" -> "GlideN64" and under "Framebuffer" setting "Copy Color to RDRAM" to "SyncMode" and "Use default hacks" to "False". [Credit to Turtle on YT](https://www.youtube.com/watch?v=NFGHl5dIRNA)
Posting this here since this was the top-most search result.
