### ISSUE TITLE
[GBA] [mGBA] Combined WRAM not working

### ISSUE THREAD

**Issue by Jedal** [TASVideos/BizHawk#563]
Hello,

I tried to read the "combined VRAM" on GBA Games using Hex Editor/Ram Watch, but either all byte are set to "0x00" or values from address 0x0 to 0x3FFFF are identical (I have seen mainly three values, most of the time "0xFF", sometimes "0x40" and a few times "0x11") and all following bytes are "0x00".

![image](https://cloud.githubusercontent.com/assets/16964074/12689245/e990ff6a-c6db-11e5-9c88-d2307c49c46d.png)

![image](https://cloud.githubusercontent.com/assets/16964074/12689253/f6cd9936-c6db-11e5-928f-25a4d4a272af.png)

_Infos :_ 
Rom used : Metroid Zero Mission (USA) (I saw on at least 2 other rom that combined WRAM was not working, Metroid Fusion and Final Fantasy Tactics Advance, but none where it worked)

**Comment by AdamSturge** [comment]
I'll take a look into this when I get a chance

**Comment by zeromus** [comment]
Sorry to steal it from you, but it felt like my bug (and it was)

**Comment by AdamSturge** [comment]
Ah no problem, there's plenty of work to go around. I was beginning to feel a little bad about not getting around to it yet honestly.
