### ISSUE TITLE
Problems with lua scripts on windows 8.1

### ISSUE THREAD

**Issue by ajloveslily14** [TASVideos/BizHawk#570]
When ever I try and open a script in the lua console this error pops up: http://i.imgur.com/62DVqk2.png

The script is in the same directory as emuhawk.exe

If I change the location of the script to C:\users\alexander\desktop\emulators\NES\hi.lua which is where it seems to be looking this error pops up: http://i.imgur.com/eBraWxZ.png

It seems to me that it taking whatever directory you have the lua script in, and ads a \NES\ or whatever other kind of emulation you are running at the time, before it. I am running the latest version from sourceforge(1.11.4) and am on windows 8.1

However if I create a new script, it works fine until I close it and open it again.

**Comment by ajloveslily14** [comment]
Also in the path section of the lua console if i create the file it show C:\users\user\desktop\eumlators\Lua\NES\script.lua
but if i try and open it just shows \NES\script.lua

**Comment by zeromus** [comment]
Fixed in master; in the meantime, dont put lua scripts anywhere but where bizhawk wants them to be--under the emuhawk.exe directory
