### ISSUE TITLE
Emulating input in c#

### ISSUE THREAD

**Issue by Nerfling** [TASVideos/BizHawk#572]
Hi,

I'm developing AI that learns to play NES games.

I'm working with the BizHawk c# source code and was wondering how I can send input to the game.

I'm trying to do this in the MainForm.cs from the BizHawk.Client.EmuHawk project.

I tried Global.ClickyVirtualPadController.Click("A"); but it doesn't seem to work, i also tried SendKeys.send() & SendKeys.sendwait(), both don't work either.

Please help me out!

Thanks,
Nerfling.

**Comment by Nerfling** [comment]
I'm now using the SendInput() function to send input to the game, although this works, I can't do anything else meanwhile cause the form needs to keep focus.

If anyone knows a way to redirect SendInput to a specific window or process that would be appreciated but I would be more grateful if their is a "clean" way to do it in the right way :)

Thank again for this awesome open source emulator :)

Greetings,
Nerfling

**Comment by Hathor86** [comment]
Hi Nerfling (and other coders),

It should be discussed with the others but I think it could be a cool feature for ApiHawk.

Regards,
Hathor

**Comment by Sappharad** [comment]
Could you use Mar/IO as a reference to do what you want? It's an AI someone wrote for BizHawk to play Super Mario World. Different console, but the means of interacting with BizHawk will probably be similar.

Thread is here:
http://tasvideos.org/forum/viewtopic.php?t=16802

**Comment by Nerfling** [comment]
Hello,

My program is coded in c# and I'd like to continue with that if possible.

I've seen that video, actually it inspired me :)

together with this video https://www.youtube.com/watch?v=xOCurBYI_gY

Thanks,
Nerfling.

**Comment by Nerfling** [comment]
I solved it :)

you need to add these 2 functions to the file "Input.cs":

`public void PressKey(string key)
        {
            var ie = new InputEvent
            {
                EventType = InputEventType.Press,
                LogicalButton = new LogicalButton(key, ModifierKey.None)
            };
            InputEvents.Enqueue(ie);
        }

        public void ReleaseKey(string key)
        {
            var ie = new InputEvent
            {
                EventType = InputEventType.Release,
                LogicalButton = new LogicalButton(key, ModifierKey.None)
            };
            InputEvents.Enqueue(ie);
        }`

you then can call these functions from mainForm.cs using:

`Input.Instance.PressKey("T")`

I bound "t" to start in this case, but you need to pass the capital letter to the presskey & releasekey functions.

Be sure to keep track of when a key is pressed and released, if you release a key when it isn't pressed or the opposite, the input will only go through once.

I hope this helps some people.

If you have questions about making it work, you can contact me at savantai@outlook.com

Have fun everyone,
Nerfling.

**Comment by zeromus** [comment]
You can use the IPCKeyInput protocol too
