### ISSUE TITLE
TASstudio: Error with saving

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#580]
I just occured this immediatly after leaving TAStudio. But I don't know again how to reproduce it precisely. I just happened to do a GBA TAS, then watch the whole movie, then save the movie, then leave TASstudio.. If I find a way to reproduce it, I'll post it.
(I post this, because I don't know if the exception text only is enough)

> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Windows.Forms.ToolStripProgressBar.set_Value(Int32 value)
>    at BizHawk.Client.EmuHawk.TAStudio.<InitializeSaveWorker>b__4(Object s, ProgressChangedEventArgs e)
>    at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
>    at System.ComponentModel.BackgroundWorker.ProgressReporter(Object arg)

**Comment by vadosnaprimer** [comment]
Closing I guess, must be the same problem as the rest.
