### ISSUE TITLE
SlimDX.DirectSound.DirectSoundException: Crash at EmuHawk.exe start

### ISSUE THREAD

**Issue by antogerva** [TASVideos/BizHawk#583]
Hi,

Recently, I'm on a transition from an old hard drive to a completely new hard drive and so far everything works fine on my PC, but that's not the case of BizHawk.

Tested on :
-BizHawk-1.11.5
-BizHawk-1.11.4

System:
-Windows 8.1
-Already installed `bizhawk_prereqs_v1.2`
-VS2015 Community is installed as well (Probably not relevant)

Happen when:
I double click on `EmuHawk.exe`

The stacktrace:
```
SlimDX.DirectSound.DirectSoundException: REGDB_E_CLASSNOTREG: Class not registered (-2147221164)
   à SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   à SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   à SlimDX.DirectSound.SoundBuffer.Play(Int32 priority, PlayFlags flags)
   à BizHawk.Client.EmuHawk.DirectSoundSoundOutput.StartSound()
   à BizHawk.Client.EmuHawk.Sound.StartSound()
   à BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   à BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
Screenshot: http://i.imgur.com/2reBaeo.png

In any case, I'll keep testing other software and see if the error can be fixed by itself, since I didn't had this issue on my old hard drive.

**Comment by antogerva** [comment]
Fixed the issue with the following steps:
Right click on the sound icon > playback devices
Then disable any useless or defective devices

**Comment by Grauen** [comment]
Just for the Record - I got the same issue today and it turned out my Dolby atmos  speaker was off and windows switched the speaker settings automatically  from atmos to 7.1 which caused an error.

Maybe you should catch this error and show some more information to the user?

**Comment by YoshiRulz** [comment]
This issue is from 1.x, which if nothing else should tell you how buggy DirectSound is. It's not worth trying to discern the cause.

Future humans: use OpenAL.
