### ISSUE TITLE
Enable low-pass filter for Mega Drive

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#584]
The Genplus-gx author suggested enabling low-pass filter to avoid inaccurate sound emulation. Details can be seen here: https://github.com/ekeeke/Genesis-Plus-GX/issues/71

**Comment by vadosnaprimer** [comment]
Fixed in https://github.com/TASVideos/BizHawk/commit/c623933af1191a45cd1dc0b862ce98aba9c29076
