### ISSUE TITLE
Use the "Releases" system for our releases

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#591]
Everyone hates sourceforge and I guess github has something for binary releases now?

**Comment by vgturtle127** [comment]
@nattthebear Yay! :wink:

**Comment by zeromus** [comment]
To achieve feature parity with the current SF solution, we need 
1. a hierarchical index of files 
2. default download platform detector
3. a screen full of advertisements
Moreover auxiliary files (prerequisite installers) would have to be checked into this repository, which is bad juju.
As I said, github releases are a joke.
My best alternative is a bizhawk-releases repository where we park the files and an index on tasvideos.org and too bad about the auto platform selector, we're 99% windows users anyway, but that deprives us of an opportunity to safely drive people to the 64bit binary.

**Comment by vgturtle127** [comment]
@zeromus Number 3 is hardly needed. :wink:

**Comment by zeromus** [comment]
Seems like @hegyak decided to put this release on github, so we no longer have a default download platform detector or a hierarchical index of files.
I updated the sourceforge page and wiki to suggest SF's deprecation for everything except the prerequisites, which MUST NOT GO INTO THIS REPOSITORY (I already regret putting the prerequisite source files in this repository). They can go into a bizhawk-prerequisites repository at a point in the near future when I choose to do so.
Hope you all never have to learn the true meaning of pain, but you might be bringing it on yourselves.

**Comment by zeromus** [comment]
I had to remove the prerequisite installer from SF or else it was recommending it as the latest download. It doesnt seem possible to make it stop recommending things. So we dont have the prerequisite installer hosted anywhere right now.

**Comment by vgturtle127** [comment]
@zeromus It can be it's own download on GitHub, at least for now. Maybe it could be included in the installer version of BizHawk, as a separate installation after BizHawk, or before or something?

**Comment by zeromus** [comment]
the what version of bizhawk? I can't make any sense of what you just said. Just for now though, attaching to the release is ok

**Comment by vgturtle127** [comment]
@zeromus I mean, you could include the prerequisites with/inside the BizHawk installer and have the installer launch the prerequisite installer before or after installation.

Sorry about the previous comment, it was pretty hard to understand after re-reading it. :smile:

**Comment by zeromus** [comment]
There's no bizhawk installer.

**Comment by vgturtle127** [comment]
@zeromus Oh, OK. I thought there was. I must be thinking of something else. Oops.

**Comment by vadosnaprimer** [comment]
Isn't it fixed now?

**Comment by zeromus** [comment]
Yes. Meanwhile, SF has rewritten their ads policy to be maybe adequate. Don't be surprised if I move us back over there. I'm waiting to see how it shapes up.

**Comment by vgturtle127** [comment]
@zeromus We can always have both, that way we have a backup just in case.

**Comment by zeromus** [comment]
twice as much releasing work

**Comment by vgturtle127** [comment]
@zeromus Yeah, that too...

Although, to be fair, it is just uploading a zip to two different places instead of one..

**Comment by zeromus** [comment]
You dont release software, so you don't have the stress of making sure everything's synchronized and consistent.
