### ISSUE TITLE
TAStudio: Opening fast makes an error

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#596]
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.IO.IOException: The process cannot access the file 'C:\Users\Administrateur\Documents\Video games\Movies\buggy test3.tasproj' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at Ionic.Zip.ZipOutputStream..ctor(String fileName)
>    at BizHawk.Client.Common.IonicZipWriter..ctor(String path, Int32 compressionlevel)
>    at BizHawk.Client.Common.BinaryStateSaver..ctor(String path, Boolean notamovie)
>    at BizHawk.Client.Common.TasMovie.Write(String fn)
>    at BizHawk.Client.Common.Bk2Movie.Stop(Boolean saveChanges)
>    at BizHawk.Client.Common.MovieSession.StopMovie(Boolean saveChanges)
>    at BizHawk.Client.EmuHawk.MainForm.StopMovie(Boolean saveChanges)
>    at BizHawk.Client.EmuHawk.MainForm.CloseGame(Boolean clearSram)
>    at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args)
>    at BizHawk.Client.EmuHawk.MainForm.RebootCore()
>    at BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
>    at BizHawk.Client.EmuHawk.TAStudio.StartNewMovieWrapper(Boolean record, IMovie movie)
>    at BizHawk.Client.EmuHawk.TAStudio.HandleMovieLoadStuff(TasMovie movie)
>    at BizHawk.Client.EmuHawk.TAStudio.LoadFile(FileInfo file, Boolean startsFromSavestate)
>    at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

STEPS:

->Save as X
->Open an another movie **during** the saving process(So, preferably do something that makes saving process sufficiently long like a movie with 17 000 frames and 10 branches)

It threw me the error above.

**Comment by Niamek** [comment]
Might be related with issue #578 .

**Comment by vadosnaprimer** [comment]
Yeah, it's just an example of mis-using. Saving process must ideally ban anything else.

**Comment by vgturtle127** [comment]
@vadosnaprimer You mean the application should wait until everything else is done to allow any further action from the user?

That sounds like a good idea to me, I didn't realize you had free reign to do whatever you want while it was saving, since I rarely use the TAS features since I don't do TAS stuff. :wink:

**Comment by zeromus** [comment]
I'm sorry someone went to so much work writing asynchronous saving without having realized theres virtually nothing you can safely do to a document while it's in the middle of saving. This must be removed. 

If you really care so much about such an ill-conceived idea, theres only 2 ways you can do it:
1. journaling architecture (not going to happen)
2. copy the datastructure, and save the copy, assuming a copy is faster than saving, which should be a close call in this case. This is difficult but possible. While it will fix issues with editing a saving-in-progress datastructure, you will still have issues with the disk being in an inconsistent state with the GUI (for instance, save a file, then open it, and that file hasn't even begun writing yet) so you have to then queue all file-related operations.

In short: delete it.

**Comment by vadosnaprimer** [comment]
Yeah, doesn't look possible to freeze the entire dialog while still updating the progressbar
http://stackoverflow.com/a/2855301/2792852

**Comment by zeromus** [comment]
I'm not sure the reason this was done is just so there can be a statusbar, but it may be.

You can keep a statusbar, you just need to pop open a modal dialog box with the status bar in it, so all other input is blocked.

**Comment by vadosnaprimer** [comment]
I think progressbar was the only reason really. But having those state gaps will help anyway. And I still think it won't be needed if saving is made faster, like, a modal window will just overcomplicate the process.

**Comment by Niamek** [comment]
> ************** Exception Text **************
> System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
>    at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
>    at System.ComponentModel.BackgroundWorker.RunWorkerAsync()
>    at BizHawk.Client.EmuHawk.TAStudio.SaveTasMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
>    at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
>    at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
>    at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
>    at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
>    at BizHawk.Client.EmuHawk.TAStudio.ProcessCmdKey(Message& msg, Keys keyData)
>    at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
>    at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
>    at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
>    at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
>    at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
>    at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
>    at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
> 

Got this exactly like #578, however, instead of doing it with the mouse, I'm doing it with CTL+S (do it VERY FAST).

**Comment by Niamek** [comment]
I've not opened a new issue since it seems to be the same thing than this one and #578 .

**Comment by vadosnaprimer** [comment]
I looked at how fceux does it, and it uses no background threads, it manually updates progressbar when it wants in the main thread. I've read on SO that it can cause problems in .net, but why exactly would it?

**Comment by zeromus** [comment]
It causes hidden errors in win32. To stop hidden errors, .net throws exceptions. As to why it's illegal, it's an elementary synchronization problem. You can't have one thread doing logic and rendering of the UI while another one modifies the UI.

This isn't even the big problem!

WTF can you do in the UI while it's saving? Nothing, safely.

Burn all the code. If you must have progress, make a modal progress popup box. Get rid of the background worker garbage. Just do it in another thread (and you can use Control.Invoke to set the progressbar from the saving thread)

**Comment by vadosnaprimer** [comment]
Another option: only use progress bar for seeking, unless it also breaks stuff unfixably, and use hourglass cursor to tell that we're not frozen but processing, instead of progressbar, because you don't want to be able to interrupt that anyway.
