### ISSUE TITLE
TAStudio: Selecting a lot of frames + Copying throws an error.

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#597]
-Load a game(I tried with a GB and SNES game.
-Open TAStudio
-Let it play for a long time(about 10 000 frames)
-Select the frame 00000
-with shift, select the last frame of the movie(so that 0 to that frame is all selected
-Wait a little bit
-Copy all that.

It should throw this exception:

> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at BizHawk.Client.Common.Bk2LogEntryGenerator.CreateLogEntry(Boolean createEmpty)
>    at BizHawk.Client.Common.Bk2LogEntryGenerator.GenerateLogEntry()
>    at BizHawk.Client.EmuHawk.TAStudio.CopyMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I just came across this since I had some movies that seemed to be bugged, so I had the idea to copy only the whole movie from TAStudio(probably not a good idea). Curiously, it's the same message than one of my other bug reports(#580), but with a different length... Could be related?

EDIT: Not only copyinh throws the error, but cutting too.

**Comment by vadosnaprimer** [comment]
Not the same at all, look at all the functions that lead to this exception in both cases.

**Comment by vadosnaprimer** [comment]
I sped up selection of multiple rows (to be almost instant), but I can't get this crash when I copy, only when I paste.

**Comment by vadosnaprimer** [comment]
Attempted to fix all these, can you compile?

**Comment by Niamek** [comment]
Apologies for the delay, got carried a little bit.

I just tested this and I can confirm the error message is gone. However, in the last interim build on this post: http://tasvideos.org/forum/viewtopic.php?p=333074#333074
(I used this build in order to try that error), it seems that pasting all of these rows seems to freeze the emulator. But I doubt some people will actually copy and 10050 frames. I can check that freeze again if you need.

**Comment by vadosnaprimer** [comment]
Reopening, or I'll forget it.

**Comment by vadosnaprimer** [comment]
Doesn't freeze for me when I paste.

**Comment by Niamek** [comment]
Will try again.

**Comment by Niamek** [comment]
Just tried with the last release. I encountered no freeze. Apologies for the delay and for the false bug!
