### ISSUE TITLE
Request: Make joypad.get() to pull keys from the loaded movie

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#598]
Joypad.get() currently works only if you press keys on your keyboard while playing/TASing. But when you play back a movie, it doesn't know what is pressed.

**Comment by vadosnaprimer** [comment]
https://github.com/TASVideos/BizHawk/issues/595#issuecomment-195699622

**Comment by mugg91** [comment]
Thanks, that's what I needed.
