### ISSUE TITLE
Game Gear: Shining Force II: The Sword of Hajya doesn't start

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#600]
Shining Force II: The Sword of Hajya shows black screen when I try to play it on Bizhawk. Seems like the same issue as with Shining Force Gaiden: Final Conflict.

**Comment by Reinc01** [comment]
The game starts now, but it still has sound issues starting from the screen where you select your character's name, and then the starting cutscene becomes more and more glitched.

**Comment by alyosha-tas** [comment]
What build are you using? I made a commit a little while ago that should have fixed this, try the latest dev build.

**Comment by Reinc01** [comment]
I am using the release version, 1.11.9.1. I will take a look at the dev build later.

**Comment by alyosha-tas** [comment]
Great!
I read somewhere that the game uses 24kb or RAM and that was causing the bug. 
It pretty obviously uses 32kb in reality, so not sure where that 24 came from.
That's what I get for not thoroughly testing.
