### ISSUE TITLE
bsnes performance core + systembus memdomain + ramsearch = super slow

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#601]
This is not a bug as such, it's just an extremely complicated confluence of awfulness. Performance core uses a slower method for reading bytes from the core (more accurate). the compatibility core uses a faster method (more safety).
This method is so slow that it may take years to run.
This is all related to the madness that is 'deterministic mode'. It's an endless pile of madness that we're not dealing with right now.

**Comment by nattthebear** [comment]
Perf core is out and the old deterministic model is out, so this is no longer applicable as of 2.0
