### ISSUE TITLE
Acces final rendering in Lua

### ISSUE THREAD

**Issue by piegamesde** [TASVideos/BizHawk#608]
It would be nice to acces the last rendered frame with the Lua script. I don't think this is already possible, at least I couldn't find it.

**Comment by vadosnaprimer** [comment]
How is it different from the current frame? And access in what way?

**Comment by piegamesde** [comment]
Yes the current frame. I said the last frame because when you acces the frame, it has already been rendered and so isn't the current frame anymore.
I meant acces in form of read acces. It doesn't matter how this is implemented. It could be similar to the acces of the emulated RAM or `emu.frameadvance()` could simply return an object containing the rendered framebuffer.

**Comment by vadosnaprimer** [comment]
Try out client.screenshot() and probably client.screenshottoclipboard() and tell why they couldn't be used for what you need (if they couldn't). I guess passing the entire framebuffer just like this isn't the best idea.

**Comment by piegamesde** [comment]
Thanks, that was what I was looking for. client.screenshot(path) and io.open(path, "r") with a Lua .png decoder will do the trick. That won't be a performant solution, but I don't care.
