### ISSUE TITLE
Error when I try to open Megaman x5

### ISSUE THREAD

**Issue by antonigg1998** [TASVideos/BizHawk#609]
this only appears
[https://i.gyazo.com/7c4010b0661ca5d446ab2749e0a8c6ff.png](url)
I select "Playstation"
And later...
[https://i.gyazo.com/f45ba0c838f24bba463e0de9335d58a0.png](url)

And finally...
[https://i.gyazo.com/ecbcc09ffc3545af8fe8a1fd1d33306f.png](url)

What should I do?

**Comment by hegyak** [comment]
Open the CUE file, not the BIN.
