### ISSUE TITLE
GBA: Cannot use SRAM domain

### ISSUE THREAD

**Issue by Anty-Lemon** [TASVideos/BizHawk#612]
Neither GBA core has the option to select the SRAM memory domain

**Comment by mugg91** [comment]
I haven't seen SRAM domain in VBA memory viewer, so does it even exist? (I don't know if my comment makes sense)

**Comment by Anty-Lemon** [comment]
Although it is unlisted, you can still manually go to 0xE000000 - 0xE00FFFF. And the mirrors, too

**Comment by zeromus** [comment]
vbanext done https://github.com/TASVideos/BizHawk/commit/5ed2e46982944aeb255210bfaade0c47a0997840

**Comment by zeromus** [comment]
fixed by 
https://github.com/TASVideos/BizHawk/commit/41dd8741d59cec3b85e462835bfc2a937dc0875c
and
https://github.com/TASVideos/BizHawk/commit/75173f2596be65306ae42d6893164c2bbeaccc03
