### ISSUE TITLE
Lua: When script is reloaded, reload modules imported by the script

### ISSUE THREAD

**Issue by Warepire** [TASVideos/BizHawk#613]
If a script consists of more than one file, loaded as modules by a main script, the Lua console must be restarted for the modules to be re-loaded.

It makes it really inconvenient to write complex scripts when they reach the point where it's not sane to keep everything in the same file anymore.

So, this would be a nice feature if it's possible to do.

**Comment by Warepire** [comment]
This will reproduce the problem. Create the files `main.lua` and `module.lua` in the Lua directory.

`main.lua` contains
```
require("Lua.module")
hello()
```

`module.lua` contains
```
function hello()
	print("HELLO!")
end
```

Run `main.lua` with Lua Console, see "HELLO!". Now edit `module.lua`, for example replace the greeting print. Run script again, see how it still shows the old message.

**Comment by zeromus** [comment]
this isn't logical. several scripts run in the same vm (associated with the console). is that ideal? I don't know. anyway, modules&requires works on the whole vm. don't use modules&requires, and you won't have this problem. rather, load and run the script yourself. it will dump stuff in the global namespace and overwrite the last stuff loaded (or intersect with it oddly).

**Comment by Warepire** [comment]
Invalid issue. `loadfile` is better.
