### ISSUE TITLE
Request Update Saturn Core

### ISSUE THREAD

**Issue by wingedonezero** [TASVideos/BizHawk#616]
Can you update the Saturn core? Yabause has fixed a lot of things in the past few years and the code says your still on 3 year old version. Plus not much seems to work on it. The newer release seems to play almost everything just fine. But it doesn't support shaders like bizhawk. Also when you exit a saturn rom bizhawk crashs and you can only use bin and cue files as well. But what games do work they look great on bizhawk. Also im using 1.11.6 if you wondering.

**Comment by zeromus** [comment]
bizhawk won't support anything but bin and cue files (and .ccd as well) even with an updated saturn core

**Comment by wingedonezero** [comment]
ok well i could try to convert the iso files and see how that goes. But if you could update the core that would add a lot more compatibility. Let me know if you decide to id love to test it out.

**Comment by adelikat** [comment]
I'm going to close this ticket since it is specifically about taking a yabause update.  The eventual plan is going to be to use the mednafen saturn core which is better and has a lot more long term potential.
