### ISSUE TITLE
Region Selection for GB/GBC

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#618]
I would like the Gambatte core to allow me to specify what Region the Emulated GB/GBC is in/from.  A good test game would be Wario Land 3 as it is a Word Release and has English and Japanese text.

**Comment by zeromus** [comment]
huh? that game asks you which language to use precisely because there ARENT different GBC regions. I looked around quickly and was unable to find any reference to region info available on the GBC system. I think this request is fictitious. Do you have any more information?

**Comment by hegyak** [comment]
I think I am be wrong on that one.  Closing this out now.
