### ISSUE TITLE
Where do N64 HD rice texture packs go?

### ISSUE THREAD

**Issue by chaosdrop** [TASVideos/BizHawk#622]
The plugin documentation linked says "C:\Users\<username>\AppData\Mupen64Plus\
   hires_texture" but that doesn't work at all.

I've tried putting Rice video HD textures packs every possible place I can and nothing seems to be the right place to load them.

**Comment by hegyak** [comment]
I don't know if BizHawk's version of Rice video supports the HD Texture Packs.

**Comment by chaosdrop** [comment]
If it doesn't then shouldn't the option be removed? 
![2016-04-28_183816](https://cloud.githubusercontent.com/assets/3247343/14906478/ca4b898c-0d70-11e6-8867-e828f8402a6f.jpg)

**Comment by Sappharad** [comment]
Why don't you enable "Dump Textures to Files" and see where the files end up? That's probably where you'll need to put them.

**Comment by chaosdrop** [comment]
Thanks that worked!
Turns out it's: 
C:\Users<username>\AppData\**_Roaming_**\Mupen64Plus\
hires_texture"
