### ISSUE TITLE
TAS Studio Undo Insert/Delete doesn't update Markers

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#626]
Bizhawk 1.11.6

Insert Case:
Create a tas studio project that is 20 frames long.
Place marker on frame 10.
Insert a frame at frame 5.
Undo.
The marker is now on frame 11.

Delete Case:
Create a tas studio project that is 20 frames long.
Place marker on frame 10.
Delete frame 5.
Undo.
The marker is now on frame 9.

**Comment by vadosnaprimer** [comment]
I'm trying to implement saving markers to history during movie operations, but I keep getting errors that I don't understand. Unbind markers from input to work around this bug for now.

**Comment by SuuperW** [comment]
This used to work, so somebody broke something. I'll look into it now.

**Comment by SuuperW** [comment]
I just fixed it. If it turns out my edits introduce new bugs, let me know.
(They shouldn't; if they do then something else in the change log code is
probably also done wrong.)

**Comment by SuuperW** [comment]
Fixed the problem.
