### ISSUE TITLE
System.OutOfMemoryException?

### ISSUE THREAD

**Issue by Hubert0987** [TASVideos/BizHawk#627]
I haven't been TASing for too long, and I've had this problem occur numerous times.(video http://puu.sh/oMfmY/2dc6015516.mp4) It seems to overwrite my file whenever I try to save, but it seems to happen at random. I try to save every 10-15 minutes, but this seems to have worsened the problem. I'm not sure what exactly is going on. 

Thanks in advance, 
Hubert

**Comment by vadosnaprimer** [comment]
I don't understand well what's happening on this video, except that you save and the filesize is too small. Shouldn't it overwrite the file anyway?

**Comment by Hubert0987** [comment]
overwrite which file?
