### ISSUE TITLE
Where can I download Visual C++ 2015 Runtime? Pre-Requisite installer doesn't install it

### ISSUE THREAD

**Issue by Piko10e** [TASVideos/BizHawk#628]
The title says it all :P Thank you

**Comment by Anty-Lemon** [comment]
Issues are for reporting bugs, potential improvements, etc. to Bizhawk, not for troubleshooting.

That said, what you're looking for can be found [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by Piko10e** [comment]
Ohhh, sorry about that didn't realize

**Comment by zeromus** [comment]
which prerequisite installer doesn't install it? I've certainly made the prerequisite installer 1.3 install it. reportedly it _doesnt work_ on some systems, and I'd like to find out why.
Anyway if this issue is solved, why didnt you close it?

**Comment by Piko10e** [comment]
It still didn't work. Like I downloaded it and it said [FAILED] I'll quickly get a pic

**Comment by zeromus** [comment]
I know what bizhawk says when you start it up and the prereq isnt installed. I need to find out why the prerequisite installer failed to install it. That probably means teamviewering to your system and checking logs and poking around,if youre amenable.

**Comment by Piko10e** [comment]
Maybe I downloaded the wrong rereq? Let me check which one I downloaded

**Comment by Piko10e** [comment]
Yea so it was the file from this website, that's the prereq that I have

**Comment by zeromus** [comment]
I know. It doesn't work sometimes. I'm trying to figure out why. Get on IRC if you want me to teamviewer to your system and debug it. Otherwise I have no clue what the problem is. Honor compels me to tell you theres a thread on tasvideos.org where someone found an "all-in-one installer" which fixes it.  I'd rather you let me debug it, but that's sensitive and it's up to you.

**Comment by Piko10e** [comment]
What's irc, like taking over my computer?

**Comment by zeromus** [comment]
teamviewer is taking over your computer. webchat.freenode.net is where we organize that.

**Comment by Piko10e** [comment]
Yea i wouldn't feel comfortable with that. I'll just try ur other option and see if it works.

**Comment by vadosnaprimer** [comment]
Keep in mind though, that if you agree, it will have a chance to be fixed for other people too.

**Comment by Piko10e** [comment]
Can I get the link to the forum post with the all-in-one installer. If it doesn't work I'll see about the irc

**Comment by zeromus** [comment]
http://tasvideos.org/forum/viewtopic.php?t=17953
It will probably work.

**Comment by Piko10e** [comment]
Thanx that worked, sorry about not doing the irc. Im just really sensitive of my computer :(

**Comment by hegyak** [comment]
Going to close this issue out.  If I get a chance I will toss the 1.3 Prerequisite installer against a fresh Windows 7.  See if I can break it.

**Comment by zeromus** [comment]
Dont waste your time on windows 7. my gut tells me its got to do with a _fully updated_ **windows 10**
