### ISSUE TITLE
Clear button on Ram Search toolbar greyed out

### ISSUE THREAD

**Issue by abitalive** [TASVideos/BizHawk#629]
The clear button (tooltip Eliminate Selected Items) on the Ram Search toolbar is greyed out if shift is used to select multiple address. This behavior is not seen if ctrl is used to select multiple address, nor if ctrl+a is used. The "Remove Selected" button in the right click menu is however still functional.

**Comment by Isotarge** [comment]
Bug appears to be in RamSearch.cs line 1730 where SelectedIndices.Any() is returning false after the Shift + Click
