### ISSUE TITLE
Emulator seems to receive input when out of focus

### ISSUE THREAD

**Issue by Nerfling** [TASVideos/BizHawk#631]
Hello everyone,

I'm making a AI based on the bizhawk emulator and I simulate keypresses.

I want to run this in the background, however, the emulator seems to receive input from me typing while the emulator is not in focus. (for example, bizhawk runs on my first monitor, i search youtube on my second monitor and bizhawk receives those keys).

Can I fix this in any way?

Thanks,
Nerfling

**Comment by hegyak** [comment]
Go to Config, then Customize.  There's a check box for "Accept Background Input"  Uncheck that.

**Comment by Nerfling** [comment]
Thanks a lot Hegyak :)

**Comment by hegyak** [comment]
Alright, going to close this out.
