### ISSUE TITLE
Lua: gui.text in event.onloadstate does not draw

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#635]
While writing a small OSD script for use while TASing I ran in to this issue.
I've written a small script to replicate the bug [here](http://pastebin.com/RZwSXrtH)

1. Open any ROM
2. Open the script in the pastebin
3. A small message including framecount will be drawn to the screen
3. Save a state
4. Pause
5. Load state
6. Text is not drawn without advancing a frame

Upon loading a state I expect the text to be drawn without having to advance a frame.
My current workaround is to use a while(true) emu.yield() end block but this is killing my CPU.

Thanks for your time.

**Comment by mugg91** [comment]
I think the way it is, event.onloadstate() runs the code the 1st frame after loading a state. You do have to advance a frame in order for the code to run.

**Comment by Isotarge** [comment]
This is partially true, the function attached to onloadstate() does run instantly without advancing a frame which can be proven by using console.log() or print(), but if it calls gui.text() before advancing it won't be drawn which is the problem I've reported.
