### ISSUE TITLE
Ram Search generates unending errors very frequently

### ISSUE THREAD

**Issue by omgitsraven** [TASVideos/BizHawk#637]
I'm trying to use the Ram Search feature on a Game Boy title, but usually within a minute or so (and sometimes immediately!), the following error will appear:
![ramsearcherror](https://cloud.githubusercontent.com/assets/8540042/15635798/1046ea7c-25b7-11e6-82be-f2ef152b2243.PNG)
and clicking 'continue' will just make the same error pop right back up, forever, until I End Task on BizHawk.

**Comment by adelikat** [comment]
Just from random searches on a random Game Boy game, no exception occurs for me.

Can you elaborate on what you are doing to get the exception?
What game? What types of searches are you doing?

**Comment by adelikat** [comment]
Ok, nevermind, it is when the Diff column is displayed, I can reproduce then
