### ISSUE TITLE
[Enhancement] TAStudio : Branch names

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#646]
In the branch section, we can see the number column, the frame column and a TimeStamp column. When you over on the branch, you can then see a screenshot and lastly the branch name.

I would like to have the branch name displayed as a column.(If I could, I'd remove TimeStamp and put the branch name there, but it seems that it's not customizable.

t's just an enhancement idea.

Niamek

**Comment by vadosnaprimer** [comment]
Yes, but usertext can be very long and not just a name. Makes sense as an option though.
