### ISSUE TITLE
More Accurate SVP Chip Emulation

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#650]
In the game Virtua Racing (Genesis) there's a hidden test/debug mode.  Use this Cheat File:
[Virtua Racing (U) [!].zip](https://github.com/TASVideos/BizHawk/files/333734/Virtua.Racing.U.zip)

To access the special mode.  Or use the Game Genie code REAT-E61A or Pro Action Replay code 0201E0:4E71 and reboot the core and make sure cheats are set to Auto Load/Enable.  You should see a black and white screen that says, "TEST END" and "COMMUNICATION ERROR !!!!!"  A proper test, will show a list of tests being done and passed/failed.

More information and pictures:
https://tcrf.net/Virtua_Racing_(Genesis)

**Comment by BooBerry** [comment]
This has been fixed in Genesis Plus GX.

https://github.com/ekeeke/Genesis-Plus-GX/commit/1dac828fb555f4efcc8e537156ae388d2ff0ad5d
