### ISSUE TITLE
Improve BootGod NES Detection

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#652]
The Current system of Detecting Board Type can lead to false positives.  Example:
Board Type:
NES-TLROM 

Can be PCB
NES-TLROM-1
NES-TLROM-2
NES-TLROM-3

This caused issues with Morita Kazuo no Shougi (J) and Final Fantasy II (J).  The current solution is:
https://github.com/TASVideos/BizHawk/commit/836492a73dce640dbaaf112312bb34bce0b3efc8

Which isn't perfect as it may cause ROMs to get incorrect things.

A better solution would be to use the PCB board detection method with BootGod's DB and setup NESHawk to use the PCB detection to ensure the ROM is getting exactly what it wants and needs.

**Comment by hegyak** [comment]
Is this corrected by  https://github.com/TASVideos/BizHawk/commit/72d4ec5ad2d52a8f87eff836072a83c34201a138

Or is more work necessary?

**Comment by adelikat** [comment]
I guess no more work is necessary :)

Closing
