### ISSUE TITLE
Colons in game names behave oddly with savestate filenames on Windows.

### ISSUE THREAD

**Issue by AdmiralCurtiss** [TASVideos/BizHawk#661]
I'm gonna use "Double Dragon II: The Revenge" for NES as an example here, but I think all game names that use characters that aren't supported in filenames on Windows are affected.

If you save a state in Double Dragon II, it cuts off everything before the colon in the savestate filename, writing it as " The Revenge.QuickNes.QuickSave1.State". Note the space at the start. This looks wrong, but actually works fine as long as you don't try to mess with the savestate files directly. The default Windows Explorer does not allow you to name a file with a space at the start, so if you try to rename it to move it to another savestate slot, or, say, use a savestate from someone else, you can never get it to actually be the correct name for the emulator to find it anymore.

I suggest replacing all characters that are not supported on Windows with underscores or similar when generating filenames for saves and states.

**Comment by vadosnaprimer** [comment]
How do you even get colon in the filename of the rom?

**Comment by Sappharad** [comment]
You don't. The name is probably coming from the game DB.

**Comment by AdmiralCurtiss** [comment]
Yes, the name comes from the game database. The actual ROM filename is different and without a colon.

**Comment by AdmiralCurtiss** [comment]
While I appreciate the fix, I feel that it's somewhat incomplete. Ideally we should replace all characters that are illegal in filenames on Windows, so the set of `\/:*?"<>|`, in case any game happens to use those.
