### ISSUE TITLE
cant play hacks

### ISSUE THREAD

**Issue by goldbones1** [TASVideos/BizHawk#663]
I'm new to TASing and I would like to TAS thing like smw hacks like item abuse and things like that, and all of my smw hacks work on snes9x, but I really like the TAStudio feature on bizhawk and I would like to use that to TAS smw hacks, but every time I try to put one of my patched hacks in it just plays regular smw when I clearly selected an smw hack and then to test out to see that it just wasn't a bad rom I opened it in snes9x and it worked. I tried googling it but no answers were found for this specific emulator. its as if I'm the only onw with this problem!

**Comment by hegyak** [comment]
I can't tell what the problem is.  If the ROM Hack is loaded into BizHawk, then BizHawk will load the hack.  It won't run the Original Game/ROM unless you tell it to.

However, Some hacks are known for breaking SNES Hardware Rules.  And won't run properly/at all.

**Comment by Sappharad** [comment]
Do the filenames of the ROMs you downloaded end in .ips?

**Comment by hegyak** [comment]
I need to know what ROM Hack(s) are not working.  Or I will close this bug report out.

**Comment by hegyak** [comment]
Closing Bug Report due to a lack of Response.
