### ISSUE TITLE
Usability Issue for entering negative values in RAM Search utility

### ISSUE THREAD

**Issue by weatherton** [TASVideos/BizHawk#669]
RAM Search does not accept a "-" to start a negative value in the "Specific Value" window. You can add "-" after typing the value but not before. While I'm posting, also the "RAM Search" and "RAM Watch" window titles state "Ram" (inconsistent casing relative to the Tools menu).

**Comment by Isotarge** [comment]
Hi Weatherton, thanks for the report. I too ran in to this issue when searching for physics floats in N64 games, I pushed a fix a while ago that is available if you use a post 1.11.6 interim build. The fix will be included in 1.11.7 when it is released.

**Comment by weatherton** [comment]
Thanks Isotarge! I noticed last night this also affects the "poke" value field. Would your fix address that as well?

**Comment by Isotarge** [comment]
Good catch, specific value & poke appear to be broken in the manner you described only when the value in the text box is already negative. The fix I pushed simply squished the exception popup when the specific value text box contains only "-". I will look in to this further soon and hopefully fix the remaining issue.

**Comment by Isotarge** [comment]
I've tracked down the bug, it's in the OnKeyPress override for WatchValueBox. It's trying to stop the user from entering "-" twice but does not check whether the instance of "-" is selected beforehand. The same skeleton code is used to check for entering "." twice and as such the bug probably applies there too. I will have a fix ready soon.

**Comment by weatherton** [comment]
Thank you!
