### ISSUE TITLE
Force Determinism causes audio bug in DKC games

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#670]
Pausing any of the Donkey Kong Country games with Force Determinism enabled causes the audio to speed up.

**Comment by vadosnaprimer** [comment]
Does it happen on bizhawk versions that didn't have this option?

**Comment by lukelogiudice** [comment]
Tried to reproduce the bug in 1.7.2a before the compatibility profile was set to always run in deterministic mode and had no issues with the audio. Bug is present in 1.7.3 up to the latest release.

**Comment by vadosnaprimer** [comment]
I meant the actual "force determinism" checkbox, that I added not so long ago, not the profiles.

**Comment by lukelogiudice** [comment]
Yes, the audio bug is present from 1.7.3 forward in versions with and without the checkbox.

**Comment by nattthebear** [comment]
This should be completely fixed by 2.0
