### ISSUE TITLE
PS1 error when I tried to load Lunar Silver Star Story Complete on Bizhawk

### ISSUE THREAD

**Issue by Kasumi77** [TASVideos/BizHawk#675]
Hi,
I was trying to play Lunar Silver Star Story Complete on Bizhawk 1.11.4, but it came with error like this :
![bizhawkscreenshot2](https://cloud.githubusercontent.com/assets/20880658/17459624/d0d311ec-5c05-11e6-8e88-9b07e30d1ea0.jpg)

Can anyone help me with this error? 
Thanks!

**Comment by hegyak** [comment]
Can you post the CUE file for the game?  I am pretty sure something is wrong there.

**Comment by Kasumi77** [comment]
Hi Hegyak. Nice to meet you. Here's the Lunar PS1's CUE files:

Disc 1:
FILE Lunar Silver Star Story Complete Disc 1.bin BINARY  
 TRACK 01 MODE1/2352    
   INDEX 01 00:00:00 
 TRACK 02 AUDIO   
   INDEX 01 54:50:22  
 TRACK 03 AUDIO   
   INDEX 01 57:20:69

And Disc 2: 
FILE Lunar Silver Star Story Complete Disc 2.bin BINARY 
 TRACK 01 MODE1/2352   
   INDEX 01 00:00:00  
 TRACK 02 AUDIO   
  INDEX 01 65:32:64   
 TRACK 03 AUDIO   
   INDEX 01 68:03:36

I removed the quotes but it still give the same error.

**Comment by zeromus** [comment]
Your cue is garbage. Get better cues.
In this case, the cue is lacking quotes around the filename.

**Comment by Kasumi77** [comment]
Hi Zeromus, where can I get better CUE files for that game?

**Comment by zeromus** [comment]
ask google.
I'm kind of curious what your process was for ripping these. It'd be nice for me to know what tool went nuts, or nice for you to know what you did wrong.
