### ISSUE TITLE
[Bug] PSX Analogue Controls for Player 1 Missing

### ISSUE THREAD

**Issue by capgames** [TASVideos/BizHawk#682]
After finally getting the PSX emulator to work, i found that i could not configure the analogue controls for Player one and only player 2
![image](https://cloud.githubusercontent.com/assets/20742198/17607730/822a38c2-601f-11e6-8949-aebb1b0c8455.png)

**Comment by zeromus** [comment]
works fine for me in latest code. find a newer build somewhere

**Comment by adelikat** [comment]
Looks like you configured controller 1 as a regular Gamepad but controller 2 as a Dual shock.

You are on the analog controls tab where only controller 2 would have analog controls to configure in that set up
