### ISSUE TITLE
RAM watch : A "Size" columns

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#683]
Currently there is only one way(to my knowledge) to check the size of an address: Editing the address. It would be neat if the size was already displayed in a column like the Value, Address,Notes, Prev or the Changes columns.

**Comment by adelikat** [comment]
There's other aspects to an address too, such as whether it is big endian, and its display type.  Shouldn't those be columns too then?  That's an awful lot of columns though

**Comment by Niamek** [comment]
I don't know about these.

The reason why I was interested in the byte size is because when I was writting lua scripts, I had to check the size for every single address I found. Just having a way to display them would be nice.

You could always set them off by default.

**Comment by YoshiRulz** [comment]
Don't know why display type needs to be a column when there are only a handful. Given the limited number of options for each of size, type and endianness, using one character for each more than satisfies the use case but doesn't hog space. Examples: "4hB" for 4 byte, hex, BE; "1uL" for 1 byte, unsigned, LE

**Comment by adelikat** [comment]
I like this suggestion :)
