### ISSUE TITLE
tastudio: use divergent point for editing functions

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#688]
Right now greenzone invalidation happens from the first frame an edit is done, while it should happen on the first frame of input difference. Not high priority though.

**Comment by adelikat** [comment]
I modifed clear and paste functions
clear - go by the first non-empty frame 
paste - go by the first different frame

I think all the other functions make sense as is, as there is no way for divergent to be different than first selected frame

Try it out and let me know.  And if i missed a scenario, let me know and I'll take alook

**Comment by vadosnaprimer** [comment]
Just use the existing method for all editing functions:

https://github.com/TASVideos/BizHawk/blob/1f4a2274d3d5406f347ed282122e44e36ba4043a/BizHawk.Client.Common/movie/tasproj/TasMovie.cs#L90

**Comment by adelikat** [comment]
I don't have 2 IStringLogs to compare, and to do so would be to recreate the new movie with the new input while keeping the old, which would be expensive.

**Comment by adelikat** [comment]
This work was done, for as many edit functions as I could think of.  If there's any specific functions that need a change in modification, please add tickets for each one specifically.
