### ISSUE TITLE
Loading a game with Libretro throws a NullReferenceException, but loads anyway if you continue execution. (1.11.7)

### ISSUE THREAD

**Issue by AdmiralCurtiss** [TASVideos/BizHawk#697]
The exception occurs here: https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Client.ApiHawk/Classes/ClientApi.cs#L204

It happens because `RunningSystem` (and, in turn, `SystemInfo.FindByCoreSystem()`) returns `null` for Libretro.

Is creating those joypads even required for Libretro? It appears to work fine regardless, so maybe all we need here is add a check if the current RunningSystem is a known internal one. Or maybe make a dummy entry for Libretro in https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Client.Common/SystemInfo.cs ?

**Comment by zeromus** [comment]
libretro integration is rewritten, any bugs like this are out of date
