### ISSUE TITLE
Controller not detected unless turned on and connected before starting BizHawk

### ISSUE THREAD

**Issue by Xolroc** [TASVideos/BizHawk#698]
I use an xbox 360 controller to play games on BizHawk, and I find this bug mildly annoying, though it's by no means serious.

If a controller is plugged in and turned on before the BizHawk process is started, everything works fine. But if I plug in the xbox controller adapter thingy, then start BizHawk, and then turn on the controller, no inputs are detected--even in the keybindings screen. Same goes for if I start BizHawk before turning on the controller or plugging in the adapter.  Since I can easily just restart BizHawk to fix the problem, it's not an urgent problem to fix, but it is a bit of an annoyance.

**Comment by hegyak** [comment]
I think this applies to most games actually.  Not all of them refresh controllers or input devices outside of their startup process.
