### ISSUE TITLE
Genesis / Megadrive Crashing

### ISSUE THREAD

**Issue by NostalgicMan** [TASVideos/BizHawk#699]
When trying to run any Sega Megadrive/Genesis rom from the emulator, it crashes immediately.
Only on the 64 bit version.

The error states that there was an internal processor exception caught and cannot be handled (In a BizHawk window inside the emulator, not in a windows window outside the emulator).

The 32-bit version of BizHawk works fine, and the 64-bit version only works with NES SNES GBA but not with SEGA.

This only started from the BizHawk v1.11.7 update on 2016-09-02 and afterwards, and wasn't fixed since then.

I have deleted all emulator directories and started the emulator freshly copied, still the same error.

CPU: AMD FX Bulldozer 8xCore 4.7Ghz
GPU: NVIDIA Geforce 970 GTX 4GB DDR4 "Gigabyte Strix"
RAM: 16GB 1866Mhz "Fury" DDR RAM (2x8GB Modules)
OS: Windows 8.1 Professional

**Comment by vadosnaprimer** [comment]
You mean you're using an x64 build?

**Comment by NostalgicMan** [comment]
That is correct, this build of Bizhawk comes in 32 and 64 bit flavours. This crash only occurs on the 64-bit build/version. The 32-bit works fine, and it is what I am using now. I just posted this to let the developers know.

**Comment by NostalgicMan** [comment]
It does seem like I am the only one with this problem, indicating that it might just be my OS or software, not the emulator. Surely if others had the same problem, and if it was the emulator, there would be more posts.

**Comment by vadosnaprimer** [comment]
Others don't have it, because the x64 build is not released.
