### ISSUE TITLE
PCE CD - (USA) 4-in-1 Disc - Sound error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#70]
```
Using the the (USA) 4-in-1 Disc that has Gate of thunder, bonk 1, bonk 2, and 
bomberman.  If selecting Gate of thunder a sound effect occurs and the emulator 
then continues to linger the sound longer throughout the games menu until you 
select a mode to play.


```

Original issue reported on code.google.com by `pasky1...@gmail.com` on 5 Jun 2012 at 9:39

**Comment by alyosha-tas** [comment]
Ok, so the audio in that section is controlled by the 6280 timer. If I make the timer tick slightly faster, or I give slightly more CPU cycles per frame to work with, the bug goes away. now I just need to figure out where the error in the current set up is that would allow one of those 2 things to be true.
