### ISSUE TITLE
Fix GBA ROM Hack RTC?

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#700]
I am attempting to run Pokemon Liquid Crystal in mGBA.  The RTC functions are not working correctly though.

My User DB is setup like so:
7ACF9D4C14B570A375402CB4DD2619F910A8A45B    !   Pokemon - Liquid Crystal 3.3.00512  GBA     flashSize=131072;saveType=3;rtcEnabled=1

The GameDB for GBA is setup like so:
F3AE088181BF583E55DAF962A92BB46F4F1D07B7    !   Pokemon - Emerald Version (USA, Europe) GBA     flashSize=131072;saveType=3;rtcEnabled=1

To test this, start Liquid Crystal and enter a name and the game will ask you what time it is.  If the RTC isn't working, the game will say, "It's too dark to read."

**Comment by hegyak** [comment]
The issue is that mGBA has it's own database for ROMs.  Which caused the above problem.  This should be fixed with the release of mGBA 0.5 for BizHawk.

**Comment by nattthebear** [comment]
As far as I know, this one is done; you can now specify gamedb overrides for mgba games in the database.  You'll have to set `mgbaNeedsOverrides` on any db entry you want processed though.
