### ISSUE TITLE
TAStudio missing inputs

### ISSUE THREAD

**Issue by Drflash55** [TASVideos/BizHawk#701]
When inserting inputs into TAStudio, when the seeker is too far away from other inputs, they will simply be forgotten by the program, as if they never existed.

This seems to happen when the movie is running for about 600 frames from the last input.
And when things seem to get cleared, they actually get dumped at some random part of the movie, which appear to be the previous inputs you inserted.

There's no errors that occur, but this is still a problem.
It's just that it happens very randomly that I can't get a good idea on when it happens, and it prevents me from making TAS's since the program can't remember where the inputs should be.

[Kirby's Dream Course TASProject.zip](https://github.com/TASVideos/BizHawk/files/488197/Kirby.s.Dream.Course.TASProject.zip)

This is the project and game I used. If anyone else can figure out how to prevent this bug from happening, that would be great.

Emulator: BizHawk 1.11.7
Game: Kirby's Dream Course (Europe)

**Comment by vadosnaprimer** [comment]
It happens the same way on the interim?
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Drflash55** [comment]
@vadosnaprimer I've been trying out the interim version, and so far, inputs have not been randomized in TAStudio.

Not sure what's wrong with the current stable build.
Possibly a flaw that was fixed during dev work, or a problem on my end.

But, anyways, interim works for me.

**Comment by vadosnaprimer** [comment]
Call back if this happens again, closing for now.
