### ISSUE TITLE
Bizhawk slows down running Mario with a lot of key presses

### ISSUE THREAD

**Issue by Nerfling** [TASVideos/BizHawk#702]
Hello,

I'm working on a learning algorithm for super mario bros, all works fine until the algorithm sends a lot of key presses, for example pressing right and releasing it 30 times in a second. normally I run this in debug at 700-1000 fps, but it slow down to about half of that when a lot of key presses happen, the algorithm can not pause the game, it only has access to the D-pad and A & B buttons. I also timed the ProgramRunLoop() method inside MainForm.cs and nothing indicates where the slow down happens, usually the loop takes 1-2ms. I also cleared all hotkeys and keybinds except the ones the algorithm uses.

I made a video to make it more clear:
https://www.youtube.com/watch?v=SMQNkO_YSA0

You can see it running quite fast (for debug mode) then it slows down when Mario starts to stutter step.

I might be using a faulty method of emulating input as I think I wrote these 2 functions in Input.cs:

```
public void PressKey(string key)
{
        var ie = new InputEvent
        {
            EventType = InputEventType.Press,
            LogicalButton = new LogicalButton(key, ModifierKey.None)
        };
        InputEvents.Enqueue(ie);
}

public void ReleaseKey(string key)
{
        var ie = new InputEvent
        {
            EventType = InputEventType.Release,
            LogicalButton = new LogicalButton(key, ModifierKey.None)
        };
        InputEvents.Enqueue(ie);
}
```

Also the InputEvents list in Input.cs is full of press f10 and release f10, I don't know what causes this either. I have a gamepad too (logitech rumblepad 2) and I unplugged it just to be sure, but it keeps happening.

I'm not sure what to do anymore, hopefully someone can help me out.

Thanks!

**Comment by alyosha-tas** [comment]
Hi,

I notice from your video that you are using QuickNes core for these tests. Does the same thing happen when using NESHawk core? you can select this by going to NES>core>HesHawk after loading the ROM, then rebooting the core in Emulation>Reboot Core.

It hsould say NesHawk at the bottom of the screen instead of Quicknes once done.

NesHawk will be slower in general, but check if the same relative slowdown is happening at those inputs, might help in debugging what's wrong, whether it's in the core or in your script.

**Comment by Nerfling** [comment]
Hello,

Thanks for your advice.

I tried running it on the NesHawk core and it slowed down a lot (37fps), it is very difficult to recreate the problem as it seems to occur under weird conditions, I'm working to replicate the bug now, If I'm able to I will tell you if the slow down happens in this core too.

Is there another way of sending input to the client window maybe? cause the problem seems to be many input events that can't be handled at the speed I'm running the game.

Another weird thing is I timed the whole ProgramLoop() function in BizHawk.Client.EmuHawk.MainForm.cs and although the fps goes down, this function stays at about 1-2ms to run through, There seems to be no change in the time it takes to run the function loop once, (with or without the fps slowdown happening) So I was thinking there may be another thread, maybe input, that is slowing down the client outside the ProgramLoop() function?

Thanks for your help so far :)

**Comment by Nerfling** [comment]
Hello,

A quick update,

I've found out that the program was writing every press or release event to the console, resulting in showing in the output window in visual studio.

I don't remember if I added this code my self or it is standard in the BizHawk code:

```
// useful debugging:
Console.WriteLine(ie);
```
this was constantly writing stuff like:
Press:R
Release:I
Release:R
....
and so on, so I commented the line out and got an immediate 20-25% boost in fps and I have yet to encounter the bug about which I was talking about.

Now I don't want to say it's gone, As I said the bug only occurs on rare conditions. I will keep you up to date :)

Thanks again :)

**Comment by kylelyk** [comment]
I noticed that printing to console in a Lua script (especially printing a region of memory one byte per line) drastically slows down emulation. From what I can tell, it seems that only one or two lines of console output can be printed per frame, thus taking several seconds to print out several hundred lines.

**Comment by Invariel** [comment]
Yes, text is incredibly slow.  Remove many/most/all of your print statements and see how well things run.

**Comment by Nerfling** [comment]
Hello again,

I let my algorithm run over night, and I didn't see the drops in fps I've encountered before, so my guess is this was the problem.

Thanks for the help everyone.

Have a nice day,
Nerfling :)
