### ISSUE TITLE
Pixel font choices not listed anywhere

### ISSUE THREAD

**Issue by douglasZwick** [TASVideos/BizHawk#703]
It seems that the available choices for pixel fonts for the **gui.defaultPixelFont** and **gui.pixelText** functions are not listed anywhere.

**Comment by vadosnaprimer** [comment]
Looks like I just copied the description from drawText. Will fix this shortly.

**Comment by D0NM** [comment]
<img width="390" height="116" alt="Image" src="https://github.com/user-attachments/assets/a16ef30d-df2e-4354-a8d2-e473a3a813c5" />
somehow "gens" looks like rectangles in Linux Mint

**Comment by YoshiRulz** [comment]
CNR (not that this is legible)
<img width="480" height="432" alt="screenshot" src="https://github.com/user-attachments/assets/e82403ec-079c-4075-8b88-ad1c99af89db" />
Please open a new issue.
