### ISSUE TITLE
PCE - Setting to crop top/bottom scanlines

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#71]
```
When racing on a track (It's most noticable on the oval track), while turning 
around some corners, there is a graphical artifact at the bottom right of the 
screen that scrolls with the game that shouldn't be there.


```

Original issue reported on code.google.com by `pasky1...@gmail.com` on 5 Jun 2012 at 9:40

**Comment by adelikat** [comment]
Changed the title to reflect what needs to be done about this ticket.

We can easily add an option to crop X number of lines from the top and bottom.  However, do we know what reasonable defaults are?  Do we want it on by default?  Should we have separate top and bottom settings?  I don't have the situational awareness of the PCE to know what good decisions are here.

**Comment by alyosha-tas** [comment]
I changed the way the screen is displayed to correctly capture how offsets work. This should provide some guidence on what the best cropping settings are just by loading up some games.
