### ISSUE TITLE
Z80 core fails one ZEXALL test

### ISSUE THREAD

**Issue by iamgreaser** [TASVideos/BizHawk#712]
It is, of course, this test: `bit n,<b,c,d,e,h,l,(hl),a>`

I somehow managed to get this to pass in my own emulator. Here's my notes:
- It is likely that you still need to track the high byte of additions with 16-bit results - that is, `ADD ss, xx`, `JR n`, and any instance of `(Iz+d)`. These cases appear to be sufficient. We'll call this register `W`.
- Flag bits 3 and 5 are **directly** sourced from the input value, _except_ for the cases of `(HL)` and `(Iz+d)`, where they are sourced from `W` instead. In the case of `(Iz+d)`, you can just take it from the high byte of the result of the `Iz+d` addition.
- **`r` does not need to be equal to 3 or 5 for flag bits 3 or 5 to be set.** Sean Young's doc gets this wrong.

ZEXALL doesn't test for `EXX`, but from what I recall, there is a shadow version of `W` and `EXX` will exchange it with its shadow version.

**Comment by adelikat** [comment]
does c07e8b0a7921dca7bf7f34d885db2b0b955b1c7f fix this?

**Comment by iamgreaser** [comment]
It doesn't.

That commit fixes two things. Firstly, instruction timings have been corrected (including for a couple of documented ops), and secondly, `CALL PO, nn` actually does what it's supposed to instead of accidentally being an alias for `CALL C, nn`.

**Comment by zeromus** [comment]
Tagging with these two cores because it's most likely to affect them

**Comment by vgturtle127** [comment]
@zeromus It would also affect the Genesis/32X, C64 (potentially, it was used as a co-processor in some add-on cards and what not, and I'm not sure how much of that stuff is emulatable in BizHawk), and maybe the GB/GBC? The Game Boy and Color both used a CPU that used some of the Z80 instructions if I remember correctly. I'm not sure if ZEXALL tests for those kind of edge cases though.

**Comment by zeromus** [comment]
grep our c64 core for z80 -- no hits
the genesis/32x and gb/gbc cores are not made by us, so they do not use our z80 -- no hits

**Comment by vgturtle127** [comment]
@zeromus Alrighty. Heh.

**Comment by alyosha-tas** [comment]
Here is a useful link that details the execution of the WZ register.

http://www.grimware.org/lib/exe/fetch.php/documentations/devices/z80/z80.memptr.eng.txt

Also, WZ does not have a shadow register, despite many of the block diagrams floating around depicting one. You can see this explained here:

http://www.righto.com/2014/10/how-z80s-registers-are-implemented-down.html

I tried implementing this in our existing z80 code but it is very cumbersome and I have so far not been successful. 

This would probably workout naturally in a machine cycle level z80 implementation, but that's not on the horizon.

**Comment by alyosha-tas** [comment]
Ok it's done. The bit test passes!

I'm closing this one. There are still a few WZ register access cases I have left to implement, which I will do seperately, as there is no way to test them so they will have no effect,
