### ISSUE TITLE
N64 Goldeneye 007 - Incorrectly disassembled instructions

### ISSUE THREAD

**Issue by Wyst3r** [TASVideos/BizHawk#717]
When using the N64 disassembler with Goldeneye 007, you'll often end up with lots of sd §ra -1 instructions incorrectly showing up in the list. This happens because read_memory_32() in mupen64plus returns M64P_MEM_INVALID for addresses between 0x7F000000 and 0x80000000. The reason for this can be found in the function virtual_to_physical_address(), which contains a hack specific to Goldeneye 007. This hack is not used when using read_memory_32() however, which is why that function fails to return the proper value.

This can (seemingly) be "fixed" by adding these lines to the beginning of read_memory_32:

`uint32_t read_memory_32(uint32_t addr){`
`if ((addr >= 0x7f000000) && (addr < 0x80000000) && isGoldeneyeRom)`
`{`
`addr = virtual_to_physical_address(addr, 2);`
`}`
`...`

Though this is probably not the prettiest way to do it.

Also a quick unrelated question:
Is there a reason for N64 (?) registers being named REG1_lo etc... rather than the common §a1, §v0... ? (Other than "not yet implemented" that is, which I could fully understand). The reason I ask is because it's quite difficult to use the disassembler in it's current state, when the instruction list use one convention and the registry list another. Having to remember which number corresponds to which register is quite difficult :)

**Comment by vadosnaprimer** [comment]
Are the names i used for the trace logger correct?

**Comment by Wyst3r** [comment]
Yeah. I guess it's just a matter of using the same list for the disassembler view then.

**Comment by vadosnaprimer** [comment]
I guess I'll give them names then, since those aren't some arbitrary crap, they're official and traditional.

**Comment by vadosnaprimer** [comment]
```
uint32 read_memory_32(uint32 addr){
  if ((addr >= 0x7f000000) && (addr < 0x80000000) && isGoldeneyeRom) 
  { 
    addr = virtual_to_physical_address(addr, 2); 
  }

  const uint32 addrlow = (addr & 0xFFFF);
```
Right?

**Comment by Wyst3r** [comment]
I think the reason it doesn't work for you is that I had upgraded my mupen64plus-core project to VS2013 compiler (since I don't have 2010 installed). VS2013 apparently comes with alot of C99 features including interleaved declarations, meaning the declaration of addrlow is valid there.

Should be easy enough to make it 2010 compatible though by removing the const qualifier:

`uint32 read_memory_32(uint32 addr){`
`  uint32 addrlow;`
`  if ((addr >= 0x7f000000) && (addr < 0x80000000) && isGoldeneyeRom) `
`  { `
`    addr = virtual_to_physical_address(addr, 2); `
`  }`

`  addrlow = (addr & 0xFFFF);`

Also, thanks for the name fix :)
