### ISSUE TITLE
Gameboy Namco Gallery Vol.2 (Japan)  galaxian issue

### ISSUE THREAD

**Issue by benderscruffy** [TASVideos/BizHawk#719]
![namco gallery vol 2 japan 2016-10-27 17 01 23](https://cloud.githubusercontent.com/assets/2696404/19761235/9b8d1602-9c67-11e6-90a8-ed8da833df92.png)
using bizhawk 1.11.8.2
choose Galaxian and only the top two aliens show up on the screen

**Comment by hegyak** [comment]
This is an issue with the BSNES Core.  Not something we can handle.

To recreate, you need to run the ROM is SGB Mode.
