### ISSUE TITLE
Cant rewind since 1.11.7

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#720]
Current Rewind options:

![rewind settings](https://cloud.githubusercontent.com/assets/17708894/19770619/36d76b88-9c60-11e6-91ae-a9d27b10e5ae.png)

On the version 1.11.6 i was still be able to rewind, but now, since 1.11.7, i cant anymore

-Removed- Due i found the fix for the no sound in San Francisco Rush 2049

**Comment by iamgreaser** [comment]
Are you still able to rewind with other emulator cores?

Is it possible to use TAStudio on that game, or any other N64 games, or any other games full stop?

Is the game itself crashing?

**Comment by danylopez123** [comment]
I tried with most of the consoles from games i was having, they dont rewind, at all, i keep pressing the rewind hotkey and nothing.

As for San Francisco Rush 2049, i can use TASStudio with them and also for the others with no problems, but still without i can rewind with the rewind hotkey

The game is not crashing, is just normal without sound

**Comment by adelikat** [comment]
By default rewind would not be on for n64 games because it is very resource intensive (you likely won't get full fps).

Turn it on by turning on "Large savestates" in the rewind config

**Comment by danylopez123** [comment]
I tried with that, and yet still no rewind

**Comment by adelikat** [comment]
what key are you pressing as the "rewind hotkey"?

**Comment by danylopez123** [comment]
Shift+R

**Comment by hegyak** [comment]
If I remember right, San Francisco Rush 2049 used a special Audio format.

**Comment by danylopez123** [comment]
Well... i removed that now due i found the fix for it, sorry for that, now i only have the i cant rewind

**Comment by zeromus** [comment]
are you HOLDING DOWN the rewind hotkey?

**Comment by danylopez123** [comment]
Yes, i was holding it and nothing

**Comment by zeromus** [comment]
You turned off screenshots on savestates. Combined with the slow rewind interval (1 second) and the slow rewind speed (1x) you may need to hold down the key for several seconds before you notice anything.
