### ISSUE TITLE
1.11.8.2-mGBA is broken

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#725]
mGBA got broken somewhere between 1.11.7 and 1.11.8.2.

When opening hex editor while mGBA core is active, there is an exception.

And alternatively, there is an error when attempting to run this code:

```
print("It works now")
local a = memory.read_s8(0x48e2)
while true do
	print("Script crashes before reaching this point.")
	emu.frameadvance()
end
```

**Comment by adelikat** [comment]
Fixed in latest revision
