### ISSUE TITLE
Atari 7800 emulation lacks the difficulty switches

### ISSUE THREAD

**Issue by Rekrullurker** [TASVideos/BizHawk#726]
The Atari 7800 included two difficulty switches just like the Atari 2600. This was mainly for compatibility with 2600 games, however some 7800 games used them as well. For example, F-18 Hornet uses them for eject and dropping your payload. Toggling one of the switches (I forget which one) changes between separate shots and bombs in Xevious, or firing both with the same button. In other games, they can be used to toggle the music on/off.

As far as I can see, the difficulty switches aren't implemented in BizHawk. EMU7800, the core of the 7800 emulation DOES support the difficulty switches, however the default keys are 1 & 2, which are used to select save slots in BizHawk.

**Comment by adelikat** [comment]
I've love to add this for you, but I can't get these games to run in emu7800, which seems to have the worst rom loader in history.  I need to see what "working" looks like for a frame of reference.  Any advice?

**Comment by adelikat** [comment]
Nevermind, I got a "result" in xevious, so I think the buttons work.  Please test this commit, and tell me that it is working the way you expect

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Rekrullurker** [comment]
Close, but not quite. They do register, but they don't stay set. In other words, you have to hold down the key/button for the left difficulty switch for it to affect the firing mode in Xevious, or to turn off the music in games like Scrapyard Dog or Ikari Warriors. As soon as you release it, it returns to the previous setting.

BTW, I agree about the loader in EMU7800. I once tried to get the fixed version of Impossible Mission (NTSC) added to the CSV file so that it would load it and it took several emails to the author to get it working. That's part of the reason I'd rather use BizHawk to play them! :)

**Comment by adelikat** [comment]
Try this out :) Same link as before

**Comment by Rekrullurker** [comment]
I'm sorry I haven't replied sooner. I didn't mean to ignore you, but I wanted to give this a proper test and I have a bunch of stuff going on at the moment...

Anyway, yes, the difficulty switches work great in this last version. I noticed some other issues though. I'll make a new thread for them.
