### ISSUE TITLE
No Multiplayer Function for PCEHawk

### ISSUE THREAD

**Issue by Sonikkustar** [TASVideos/BizHawk#727]
As of the current build, there seems to be no Player 2 controls for the PCE Core. This essentially makes Multiplayer functionality practically impossible under PCE unless you make some sort of multitracking script.

If it isn't too much trouble, it would very much be appreciated.

**Comment by adelikat** [comment]
In the PCE Menu there is a controller config option.  In there you can wire up to 5 players.  By default only 1 controller is set up.
