### ISSUE TITLE
Lua request: add cryptographic hash function for memory areas

### ISSUE THREAD

**Issue by rodamaral** [TASVideos/BizHawk#730]
Sometimes while debugging, the player just wants to know if a memory region or interval has changed or not. I suggest the creation of a function like this:

Syntax: string **memory.hash_region**(number **base**, number **size**, [string **memory_area**])
Hash _size_ bytes starting from address _base_ (relative to _memory_area_) and return the SHA-256.

**Comment by adelikat** [comment]
I like this idea!

**Comment by vadosnaprimer** [comment]
FCEUX has such a thing in the latest release.
