### ISSUE TITLE
[Request] [mGBA] Disable/Enable audio channels 

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#735]
Standalone mGBA lets you disable and enable audio channels 1, 2, 3, 4, A and B.
But this option seems absent in Bizhawk.
I'm requesting that it is added in the GBA settings.

**Comment by douglasZwick** [comment]
I actually came here specifically to ask for this particular feature for SNES emulation. I'll make another thread for that request.

**Comment by nattthebear** [comment]
Added

**Comment by mugg91** [comment]
This seems buggy in 1.11.9
See bottom of this post: http://tasvideos.org/forum/viewtopic.php?p=444504#444504
