### ISSUE TITLE
[Request] Toggle individual SNES audio channels

### ISSUE THREAD

**Issue by douglasZwick** [TASVideos/BizHawk#736]
Some SNES emulators (ZSNES in particular) allow you to enable and disable each of the system's eight audio channels independently of one another. I'd like to see this functionality added to BizHawk, and I'd like to be able to bind keys to do it, or at least just to be able to do it through Lua.

**Comment by nattthebear** [comment]
The newly imported snes9x core does this; wait for 2.0 release.  If you'd like this feature in the bsnes core as well, feel free to reopen this issue.
