### ISSUE TITLE
[mGBA] Minor audio bug in Mario & Luigi

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#737]
(Confirmed in 1.11.7, 1.11.8.2)
(That means the bug is present in both the 0.4.0 and the 0.5.0 core of mgba. It has been present for quite some time though.)

When playing GBA Mario & Luigi Superstar Saga (U) on Bizhawk-mGBA core, 
when the screen is flickering as a result of the Action Command Glitch, the audio becomes increasingly low-pitched over time.

When recording AVI or WAV at the same time the flickering occurs, the audio bug doesn't occur. The recorded files are not affected.

Demo bk2
http://dehacked.2y.net/microstorage.php/info/718897758/MLSS%20Mgba%20audio%20bug.bk2

Video of the flickering on bizhawk-mgba, see at 58:28
https://www.twitch.tv/vlacksr/v/44404262

Video of the flickering on real console, see at 0:26
https://www.youtube.com/watch?v=246H7FpbKd4

**Comment by vgturtle127** [comment]
@mugg91 Does endrift know about this?

**Comment by mugg91** [comment]
@vgturtle127 I posted in the tasvideos mgba thread, so he should be aware.
http://tasvideos.org/forum/viewtopic.php?p=444451#444451

**Comment by vgturtle127** [comment]
@mugg91 Alright, thank you.

**Comment by nattthebear** [comment]
According to that forum thread, it was fixed in mgba 0.5.2 and Bizhawk has taken that so bam!

**Comment by vgturtle127** [comment]
@nattthebear 
Thanks, buddy! 😄
