### ISSUE TITLE
GBA GPU viewer crash in DBZ Legacy of Goku 2 (GBA)

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#740]
In Bizhawk 1.11.7 and 1.11.9 there is a crash with the GPU viewer. I think it doesn't matter which version of the game, and which gba core.

Repro steps:
1) Be on the pause screen while in a room (not on the map flying screen)
2) In the GPU viewer, the "Sprites" widget, press refresh
3) Bizhawk stopped working

**Comment by hegyak** [comment]
It appears that this has been fixed in newer Commits.  This will be fixed in a new release or you can use an interim build.
