### ISSUE TITLE
Tools > External Tools, throws an exception

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#741]
Playing Dragon Ball Z Legacy of Goku 2 (J) in mgba core, hovering or clicking on the menu entry
 
Tools/External Tools

makes Bizhawk throw an exception.

**Comment by mugg91** [comment]
Doesn't happen in 1.11.9.1

**Comment by mugg91** [comment]
Ok, actually it does still happen.
When I have ROMs in a directory that doesn't contain äöü, and then hover over External Tools, it will create an empty folder "ExternalTools" next to the ROM folder.

When I have ROMs in a directory that contains äöü, and then hover over External Tools, it gives an exception.

**Comment by hegyak** [comment]
Our Directory Creation Code does not support Unicode characters, it seems.  What OS are you using?

**Comment by mugg91** [comment]
Windows 7 Home Premium 64bit

**Comment by schas002** [comment]
I experience this problem, too, on Windows 7 Home Basic 64-bit. (Russian locale, if that helps.)

The exception here is about an initialiser of type `BizHawk.Client.ApiHawk.ExternalToolManager`, and the call stack references `System.Reflection.Assembly.LoadFrom()`, among others.

**Comment by coolkirby2000** [comment]
I also experience this on Windows 10 Pro 64-bit, English locale. It creates an ExternalTools folder with HelloWorld_BizHawkTool.zip and HelloWorld_BizHawkTool.dll, and throws this exception:
http://pastebin.com/fKcXHRBQ

**Comment by zeromus** [comment]
rightclick that helloworld_bizhawktool.dll and pick properties and unblock
-or-
try not running it from a directory like "shared". is that on the network? this can be caused by .net being upset by the permissions of files on the share
