### ISSUE TITLE
Intellivision game controller bug

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#747]
I just downloaded BizHawk Git (2016/12/18) and can't program the gamepad. as you can see some of it is missing. in 1.11.9 it was working
![capture12-19-2016-12 50 42 am](https://cloud.githubusercontent.com/assets/21169038/21303802/a5b9c07e-c586-11e6-8668-0b5eb23fe8e5.jpg)

![capture12-19-2016-1 02 25 am](https://cloud.githubusercontent.com/assets/21169038/21303855/0360b7d2-c587-11e6-80fb-dfef9124f9a8.jpg)

**Comment by alyosha-tas** [comment]
The disk controls were moved to the 'analog controls' tab. There you can bind it to mouse or control stick if you have a controller. 

Post back if you have other questions.

**Comment by Cibomatto2002** [comment]
I went to the analog controls tab and do not understand how to use it i'm trying to set it up on a gamepad.
SteelSeries 3GC Dual Vibration PC Gaming Controller. Trying to set up the up, down left, right directions. 

https://www.amazon.com/SteelSeries-Dual-Vibration-Gaming-Controller/dp/B0036WTVNG

**Comment by alyosha-tas** [comment]
Try binding it to an analogue stick. Hit 'Bind!' button then push the control stick in the cooresponding direction (x = left-right, y = up-down)

I don't think it will work with a gamepad.

**Comment by alyosha-tas** [comment]
Oh yeah, also you can change the controller settings to the way it was before in the menues.

To do this:

1. Load an intellivision game
2. Go to the INTV menu next to tools in the menu bar
3. Click controller settings and then change to standard controller
4. Reboot the core (emulation -> reboot core)

Then go back to controller config like before and you can map the primary directions to the game pad.

**Comment by Cibomatto2002** [comment]
Thanks so much alyosha-tas I got it working.
