### ISSUE TITLE
QuickNes. Cybernoid the Fighting Machine. Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#748]
In QuckNes the graphics are glitch as you see here.

![capture12-19-2016-2 57 21 am](https://cloud.githubusercontent.com/assets/21169038/21306587/56f12c5a-c597-11e6-857d-bffaacc23cc5.jpg)

In NesHawk it's fine. 

![capture12-19-2016-3 01 07 am](https://cloud.githubusercontent.com/assets/21169038/21306651/c064cb38-c597-11e6-9f45-f449a50a37c7.jpg)

**Comment by hegyak** [comment]
Does BizHawk run Cybernoid in NESHawk or QuickNES by Default?  Because we would need to get BizHawk to force this game to run in NESHawk.

**Comment by Cibomatto2002** [comment]
by default NesHawk will run it.

**Comment by hegyak** [comment]
Then this is not an issue, for us.  BizHawk can not control how a core handles things.

If an updated QuickNES can handle the game, then please let us know which version does support it and we may try and update the QuickNES Core to the working version.

**Comment by alyosha-tas** [comment]
It looks like since Quicknes is the default core we should add this game to the blacklist that switches it to NESHawk.

Or maybe making NESHawk the default core should be considered? By now it has much higher compatibility and acuracy, only down side is it's slower.

**Comment by alyosha-tas** [comment]
I added Cybernoid to QuickNES's blacklist, which should resolve this.
