### ISSUE TITLE
Turbo (1982) (Sega)

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#753]
The game will freeze on this screen.

![capture12-20-2016-2 36 23 am](https://cloud.githubusercontent.com/assets/21169038/21343721/bb7a681e-c65d-11e6-84e8-0b524257db2b.jpg)

**Comment by alyosha-tas** [comment]
This game requires the Turbo controller to play. It would be plugged into controller port 1. This controller is not emulated yet.

**Comment by alyosha-tas** [comment]
Turns out player 2's controller was broken , I just commited a fix that let's this game (and any other game needing the turbo controller) to at elast boot.

However you still can't play it without the turbo controller, so I'll leave the issue open.

**Comment by Cibomatto2002** [comment]
Is this the only game that needs the turbo controller?

**Comment by alyosha-tas** [comment]
Turbo Controller support is added, please test the dev build

**Comment by Cibomatto2002** [comment]
Where do I download  the Dev Build. :)

**Comment by alyosha-tas** [comment]
you need todo menu input on controller 2, as that is the controller the game reads from to go through the menues (since the turbo controller is plugged into controller 1.)

Make sure you first plug in the turbo controller under Coleco->Controller Settings
Then reboot the core
Then configure the controllers in Config->Controllers

**Comment by Cibomatto2002** [comment]
Thanks for the help I got it working I was wondering if this is a bad rom that I have see the buildings is that the way they are supposed to look?

**Comment by alyosha-tas** [comment]
that's what they look like in all the videos I see, so yes it seems correct.

Alright I'll close this issue then. If you notice a specific problem please post a new issue.
