### ISSUE TITLE
Kung-Fu Master (USA)

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#756]
Graphics not showing right.

![capture12-21-2016-10 38 58 pm](https://cloud.githubusercontent.com/assets/21169038/21415364/b0af1a7a-c7ce-11e6-8e22-50f39f954d0c.jpg)

**Comment by hegyak** [comment]
I just checked the ROM against the No-Intro Database and the MD5 isn't matching.  I trust No-Intro's hashes over what the Database we are using.

**Comment by hegyak** [comment]
I think it's related to https://github.com/TASVideos/BizHawk/issues/758  It may be how the Header is being "read"  Can you post the MD5/SHA1 of the ROM(s) you have issues with.  Don't use BizHawk's internal Hashing method, please.  I want to see the ROM(s) checksum outside of the Emulator.

**Comment by Cibomatto2002** [comment]
MD5

1D9513A8D2A837CACA7BB4E9884A87CB

SHA1

624A8F70B433F04942D5544289AC156D50B93610

**Comment by hegyak** [comment]
I compared TOSEC and No-Intro's ROMs and their hashes matches your Hashes.  But, they don't match the CSV's hash.  Which makes me wonder what is going on here.  It should be noted that the CSV uses No-Intro's Hash, but it doesn't have the header data.

**Comment by alyosha-tas** [comment]
Game has the same bug in EMU7800 V1.8, so seems to be a core issue

**Comment by alyosha-tas** [comment]
I cannot fix this issue in EMU7800, but it is fixed in A7800Hawk as of the latest commit.
