### ISSUE TITLE
Genplus-gx [BizHawk] Game Genie/ Game Shark bug

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#765]
If you go to cheats and click Game Genie the Game Shark Converter will open.

![capture1-4-2017-1 29 14 am](https://cloud.githubusercontent.com/assets/21169038/21634508/70072694-d21d-11e6-8f93-83fdf40ffb73.jpg)

**Comment by hegyak** [comment]
This is normal. I setup a single window/form. It does work the for Game Genie and most other cheat devices, for any core that supports Memory Freezing/Editing.
