### ISSUE TITLE
NesHawk [BizHawk] Game Genie Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#767]
If I click on Game Genie Encoder/Decoder The Game Shark Converter will open.

![1](https://cloud.githubusercontent.com/assets/21169038/21636063/ae323c8e-d226-11e6-888d-5736699f9049.jpg)

**Comment by hegyak** [comment]
This is normal. I setup a single window/form. It does work the for Game Genie and most other cheat devices, for any core that supports Memory Freezing/Editing.
