### ISSUE TITLE
Gambatte [BizHawk] Game Genie Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#768]
If you open Game Genie Encoder/Decoder GameShark Converter will open.

![capture1-4-2017-2 45 20 am](https://cloud.githubusercontent.com/assets/21169038/21636475/7d581f32-d228-11e6-9790-74bdf6c1a876.jpg)

**Comment by hegyak** [comment]
This is normal.  I setup a single window/form.  It does work the for Game Genie and most other cheat devices, for any core that supports Memory Freezing/Editing.
