### ISSUE TITLE
Won't load Super Mario Kart for SNES

### ISSUE THREAD

**Issue by theoneandonlyjustin** [TASVideos/BizHawk#769]
When I try to load the Super Mario Kart ROM for the SNES, it gives me this error:
![smkerror](https://cloud.githubusercontent.com/assets/22670587/21656790/817a1b46-d28d-11e6-8a90-e85240884f07.PNG)
How can I fix this?

**Comment by Cibomatto2002** [comment]
Looks like you are missing some firmware. You can find it on google put it in this folder and it should play.

![capture1-4-2017-2 47 38 pm](https://cloud.githubusercontent.com/assets/21169038/21658628/fac18134-d28c-11e6-8ec2-315e8d53ec41.jpg)

**Comment by hegyak** [comment]
You need the Big Endian ROM file.  We can not tell you how to get the ROM file.  It's copyrighted content.
