### ISSUE TITLE
NesHawk Game Genie codes will not turn off 

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#770]
Game Genie codes will not turn off even when you turn them off or delete them.

**Comment by hegyak** [comment]
Bug Confirmed on NESHawk.

Using the game genie code:
GKEPGG

The Ground Block, becomes the Cloud Blocks.   You can see this during the Demo sequence and on World 1-1.

The RAM Address in Question is:
9484 on The System Bus Domain.  Value should be 240 normally.  With the Cheat, the value is 68.

However when the cheat is disabled, the value according to RAM Watch changes back to 240 (Which is Expected) However, the Game does not reflect this change.

**Comment by alyosha-tas** [comment]
NESHawk implements it's own Watch class. When you create a cheat, a new instance of a Watch is created in NESHawk. However, when you delete a cheat, the cooresponding function to remove the Watch in NesHawk is not called. So of course, the cheat is persistent.

It looks like the NESHawk Watch class is redundant, but I haven't sorted out the details of how to bypass it so stay tuned.
