### ISSUE TITLE
PCEHawk Screen Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#771]
On the game Final Soldier (J) the title screen will jump around.

**Comment by alyosha-tas** [comment]
Ok, so what's happening here is that a scanline IRQ is happenning which updates the screen offset. The offset changes roughly 80 cycles after the IRQ occurs. 

Unfortunately, this is also the amount of time it takes for HBlank to finish, and after that happens the offset is latched for that scanline. 

So there is a race between which happens first, the update or the scanline processing. If the IRQ is delayed while another instruction is processing, this is enough to change the order events occur in.

I don't know when the scanline value is actually latched by the VDC, or alternatively, when the scanline IRQ is triggered, so I could only guess at the correct solution here.

**Comment by 007-beep** [comment]
This final blaster bug is still present in pcehawk

**Comment by YoshiRulz** [comment]
Can you elaborate? Which version of BizHawk are you using?

**Comment by 007-beep** [comment]
Latest dev build

**Comment by Cibomatto2002** [comment]
Foe me the game works correct.

**Comment by 007-beep** [comment]
> Foe me the game works correct.

So you are saying the planet on the title screen in pcehawk magically doesn't shake for you????


Its a known bug fyi

**Comment by Cibomatto2002** [comment]
I will make a video of it when I get home.

**Comment by 007-beep** [comment]
> I will make a video of it when I get home.

Set core turbonyma works perfectly 
Set core hypernyma works perfectly 
Set core pcehawk bug is present - directly related to vblank issue in pcehawk. I only mentioned the fix is gone in latest commits. And its 100% broken. Look at the planet on the title screen
On turbo and hyper and real hardware pplanet steady on pcehawk it jumps.

**Comment by Cibomatto2002** [comment]
you are correct I forgot you could change the core sorry about that.

**Comment by 007-beep** [comment]
> you are correct I forgot you could change the core sorry about that.

No need for sorry i just figured ide point out that the fix was never applied since here it says it was applied. Not a big deal.
