### ISSUE TITLE
PCEHawk trying to add cheats?

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#772]
How do I add cheats to PCEHawk? My cheats come from http://gamehacking.org/  This is the game I want to add codes to Final Soldier (J) http://gamehacking.org/game/40375 I don't really know how to add these kind of codes to PCEHawk.

**Comment by hegyak** [comment]
These are the Raw RAM addresses.  For infinite lives, you would set the address to 	
1F00FC then a single byte, then the value to 02.  What RAM Domain?  I don't know.  Experiment with that.

**Comment by Cibomatto2002** [comment]
I did every thing you said and I got this.

![1](https://cloud.githubusercontent.com/assets/21169038/21739938/0ec3f548-d46f-11e6-97a4-89a7e5c64901.jpg)

After I click OK This is what I see. 

![2](https://cloud.githubusercontent.com/assets/21169038/21739943/23a8c588-d46f-11e6-93f2-2f9c5367895d.jpg)

**Comment by Cibomatto2002** [comment]
I got it working this is how I did it I made a code for Infinite Lives then seen how it was set up next I took the Invincibility and removed 1F from the code. 
![1](https://cloud.githubusercontent.com/assets/21169038/21740057/ba0c6608-d472-11e6-9641-3ca559e9b80b.jpg)

Thanks a lot for your help :)
