### ISSUE TITLE
Won't load Super Mario Kart (BSNES) and can't find dsp1b file.

### ISSUE THREAD

**Issue by theoneandonlyjustin** [TASVideos/BizHawk#773]
I can't load Super Mario Kart on BSNES, gives me this error:
![smkerror](https://cloud.githubusercontent.com/assets/22670587/21700675/99c2c4b8-d36f-11e6-9ea7-d09b4a7a6419.PNG)
When I look for the dsp1.rom file to put dsp1b.rom next to, I can't find the folder. I have "show hidden folders" on, but can't seem to find it.
![cantfindrom](https://cloud.githubusercontent.com/assets/22670587/21700722/e0b10d76-d36f-11e6-85ff-8c493e4af96d.PNG)

**Comment by Cibomatto2002** [comment]
You will have to use google to find it. Good luck.

**Comment by theoneandonlyjustin** [comment]
I have the file, where do I put it? Like in the BizHawk folder?

**Comment by hegyak** [comment]
In the Firmware Folder.

**Comment by theoneandonlyjustin** [comment]
I don't see anything in the firmware folder. The folder is blank.

**Comment by theoneandonlyjustin** [comment]
![nofirmware](https://cloud.githubusercontent.com/assets/22670587/21722440/9ab117fe-d3fa-11e6-97e1-a00459c3af62.PNG)

**Comment by vadosnaprimer** [comment]
It remains blank even after you put the file there? That's powerful.

**Comment by theoneandonlyjustin** [comment]
Do I need a clean install of bizhawk?

**Comment by hegyak** [comment]
You will need to extract the latest BizHawk completely.  You will see a Firmware Folder.  Put your dsp1.rom in that folder.  Yes, the dsp1b.rom file can be placed into the same folder.  If you lost your Firmware folder, that isn't supposed to happen at all.

**Comment by Cibomatto2002** [comment]
I made this video for you maybe it will help.

https://www.youtube.com/watch?v=I9CrQ95HWY0&feature=youtu.be

If this doe not help you maybe you should try another Emulator like snes9x here is the updated version.

Download the one I got the arrow pointing at.
![capture1-9-2017-12 28 43 am](https://cloud.githubusercontent.com/assets/21169038/21758593/edc098a2-d602-11e6-9d87-345514c27cf0.jpg)
 

https://sites.google.com/site/bearoso/

**Comment by theoneandonlyjustin** [comment]
Will watch, thanks!

**Comment by theoneandonlyjustin** [comment]
Does snes9x support Luis?

**Comment by theoneandonlyjustin** [comment]
Lua*

**Comment by hegyak** [comment]
Ask here:
https://github.com/snes9xgit/snes9x
