### ISSUE TITLE
[VBA- Next] Trying to play Boktai: The Sun is in Your Hand (USA)

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#774]
How can I map the Solar Sensor to the game pad? On VisualBoy Advance -M I did it like this.

![capture1-5-2017-6 01 29 pm](https://cloud.githubusercontent.com/assets/21169038/21702488/47bb548a-d371-11e6-8936-51779d39797a.jpg)

**Comment by hegyak** [comment]
I don't think we are using a version of VBA-Next that supports the Solar Sensor.  I think mGBA does though.

**Comment by Cibomatto2002** [comment]
I don't see the setting on mGBA either? unless this is it and if it is I have no idea how to map it to my gamepad or keyboard. 

![capture1-6-2017-11 14 15 pm](https://cloud.githubusercontent.com/assets/21169038/21739642/52d07440-d466-11e6-9472-1156c161ecb2.jpg)

**Comment by hegyak** [comment]
I think if you used an analog Stick and Bind that to your light sensor, you can change it's value that way.

**Comment by Cibomatto2002** [comment]
I'm having no luck Bind it.

**Comment by raekuul** [comment]
Really? When I bind X1 Right Thumb to the Light Sensor, it works perfectly.

**Comment by Cibomatto2002** [comment]
I got it to work on the Right Thumb now thanks. I was trying to get it to work with pressing a button like on the top of the gamepad also I did try to map it to the keyboard but with no luck.

**Comment by zeromus** [comment]
So it's resolved? Then close it.
