### ISSUE TITLE
[VBA- Next] Game Genie codes not working but Gameshark codes do work.

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#775]
I can't get any Game Genie codes to work but codes made for Gameshark do work.

Codes come from here.

http://gamehacking.org/

Try this game Double Dragon (USA, Europe).

As you can see the Gameshark codes work but not the Game Genie codes I only tried a few Game Genie codes.

**Comment by hegyak** [comment]
As I mentioned in another ticked related to GBA Cheats, the GBA Cheat Code Handling is a Mess.  There are several devices to handle, and they are much more complex then anything else that BizHawk can handle as it relates to other cores and such.

If anyone is up for working with me on IRC to help improve/fix the GBA Cheat Code handling/behaviors, please let me know.

Also, I don't know if VBA-Next is a supported Core for BizHawk officially.  I know mGBA is released and is supported.

And, I didn't know there was a Game Genie for GBA.  GB/GBC yes.

**Comment by Cibomatto2002** [comment]
Here is where you can read about the Game Genie for the Gameboy. I had one. :) I like making my own codes so it's not like we really need it to read Game Genie codes I'M happy the way it is. :)

https://en.wikipedia.org/wiki/Game_Genie#Game_Boy

**Comment by hegyak** [comment]
If you run a GBC ROM in GBA Mode, There's no handling for that.  Due to the way the code handling is programmed.  I don't even know if a GB/GBC Game Genie works in a GBA.

**Comment by Cibomatto2002** [comment]
Game Genie Game Boy Advance SP Test. This will not work on the Game Boy Advance  but will work on the SP. Really tho who would use it it's in the way.

https://www.youtube.com/watch?v=u2CoQhazpno&spfreload=10

**Comment by hegyak** [comment]
Based on how the GBA Code handing is in general, it is unlikely to happen.  There is also the issue of how the GBA core runs GB/GBC games.  Are the RAM domains handled the same?

**Comment by Cibomatto2002** [comment]
Oh Ok I see thanks for your time.
