### ISSUE TITLE
Genplus-gx [BizHawk] Game Genie codes not working.

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#777]
Trying to get Golden Axe (World) (v1.1) codes to work in Genplus-gx but with no luck. They work fine in Kega Fusion. Here is the codes I"M using. Also I'm using the Game Genie codes are Word Sized, not Byte Sized update. 

Infinite Energy 

9TST-BCNY
GAST-BAN0
S2ST-B762

http://gamehacking.org/game/15196?game=15196

Also Streets of Rage 2 (USA) don't work either.

Infinite Energy 

9V5T-BGSE
PB5T-AAHG
975T-AAHJ
TB5T-A99L

http://gamehacking.org/game/15974

I have tried other games to and codes do not work.

**Comment by hegyak** [comment]
I am not quite sure why the Streets of Rage 2 cheats fail to work.  My guess is that the Domain needs to be different.

This Infinte Energy cheat:
FFEF80:0068 (RAW)

and this Infinte Energy cheat:
0077E6:0068  (GG)

Has the same value, but different Addresses.  My guess is that the Domain for these kinds of Codes needs to be different.

**Comment by Cibomatto2002** [comment]
This code works 0077E6:0068. Maybe This tool will help you. A utility capable of converting between game genie and rom addresses for the NES, SNES, and Genesis.

http://www.romhacking.net/utilities/23/

![1](https://cloud.githubusercontent.com/assets/21169038/21754307/308db20e-d5c3-11e6-822b-5679c6c11612.png)

**Comment by alyosha-tas** [comment]
This is a weird one. Cheats do in fact work, but only if you have hex editor turned on. 
I'm not exactly sure why, except that obviously the cheat engine alone is not doing the external write to the core.

**Comment by Cibomatto2002** [comment]
Thank you for fixing it.

**Comment by Cibomatto2002** [comment]
Downloaded the BizHawk-20170417-x86 release and problem is still there I use this code to test it and it did not work. LBFT-AEAT       Cash bag worth 25,000. code came from here. http://www.gamegenie.com/cheats/gamegenie/genesis/streets_of_rage_2.html

**Comment by alyosha-tas** [comment]
Ok try it now, thanks for the testing

**Comment by Cibomatto2002** [comment]
Seems to work now thanks A lot. Sometimes the Emulator will freeze on me I'M not sure if it's the codes I'M using or not is there a way I can send something to you when it freezes?

**Comment by alyosha-tas** [comment]
There are games that will freeze if a cheat is turned on at power on. THis is because games do a checksum of the ROM to make sure everything is consistent before loading. This happened to me when testing as well. Ideally we could avoid this by delaying the application of cheats but the machinery is not in place for that to happen. Likewise once a cheat is turned on you cannot remove it without rebooting the core. This is it's own problem and cannot be fixed in the near future.

**Comment by Cibomatto2002** [comment]
This happen after I was already on level one of Sonic 2 the game would freeze but the music keeps playing. I think it's fine now tho I'm not sure what happen.
