### ISSUE TITLE
No NES games want to play - visuals work, sound and input don't

### ISSUE THREAD

**Issue by TheRActivator** [TASVideos/BizHawk#779]
I wanted to start making a TAS of some classic NES games but none of them seem to work - I can see the game, but there is no sound and there is also no input. I am just looking at a title screen without being able to play. Even controlling using TAStudio doesn't work. Even when I downloaded an FDS BIOS, Super mario bros. 2 (Japan) had the same problem. I have the latest bizhawk version and I installed the prereq stuff.

**Comment by alyosha-tas** [comment]
First make sure you are using the most recent dev build.
You can download it here:
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

If that doesn't help you make sure you are using NESHawk and not QuickNES. (This shows up at the bottom of the BizHawk window after you load a NES rom. To change to NESHawk, first load a rom then go to NES->Core->NESHawk. then reboot the core under Emulation->Reboot Core.

If none of this helps report back with what games you tried, what OS you use, what controller settings you use, and maybe some screen shots or other helpful info.

**Comment by TheRActivator** [comment]
Updated to the dev version and changed to NESHawk, still having the problem.
I have Windows 10. I tried Super Mario Bros, Super Mario Bros 2 (Japan) and Duck Hunt. Duck Hunt seemed to work, but the sound muted when I pressed a button. Might I also add that the SNES does work for me.

https://gyazo.com/04f97a2fc611e3bfd9269d5c159e5e2a <- Input is detected, but not executed

**Comment by alyosha-tas** [comment]
Strange.

Try going to Config->Controllers and taking a screenshot of what it says there for each player. Also check your hotkeys and make sure nothing is interferring.

also Try recording a movie of Super Mario Bros and posting it here so I can see the input log and settings info. Just randomly press buttons for 30 seconds or so.

**Comment by zeromus** [comment]
@TheRActivator, that isn't a valid test. Did you try pressing down on the SMB title screen in another emulator? The game is acting normally.
