### ISSUE TITLE
Nvidia performing terribly compared to Intel GPU.

### ISSUE THREAD

**Issue by retrobenny** [TASVideos/BizHawk#782]
I don't know entirely why,but performance is terrible on my Nvidia GeForce GTX 940MX while the same thing can run Hyrule Field at 60fps in Twilight Princess on Dolphin,but it runs Banjo-Kazooie slowly on BizHawk.
Sorry for another issue by me,just having some bad luck.

Project 64 can run it better by not using "read every frame" but goes just about as slow with that enabled.
How is it that the Intel GPU runs it so incredibly fast to my dismay?
(the "read every frame" effects work on DK64 with the Intel GPU for when you pause the game and the zipper effect when picking a save file,so that's not why its faster)
The CPU is being maxed out to 30-35% usage via Nvidia compared to Intel's GPU making it 20-25% usage,what's going on here?!?

Edit: Scratch that 30% use,I set video resolution to 320x240 and it can be low while also maxing out to 40-50% when not even fast forwarding.
Does Bizhawk hate Nvidia cards? Because I can never get PJ64 to even hit more than 30% usage,and that's when causing PJ64 to hang with an unstable Gameshark code.

**Comment by hegyak** [comment]
It's not your Video Card.  It's the Core.  Try using Muppen64Plus and compare the results of that, to BizHawk.

**Comment by zeromus** [comment]
You haven't compared apples to apples. You've compared CPU usage to dolphin to bizhawk 
None of that means anything. Here's all that means something.
Run bizhawk on intel gpu. Run bizhawk on nvidia gpu same game, same system.

**Comment by retrobenny** [comment]
Kind of exactly what I did before posting this issue,but sorry I didn't mention it more clearly,I get slow speeds on BizHawk with Nvidia,then I forced the Intel GPU to be used and it gets much better performance with Bizhawk while also using less CPU.

**Comment by zeromus** [comment]
reset your nvidia driver settings or blow the dust out of your fans
