### ISSUE TITLE
N64 crash via Glide64mk2 plugin.

### ISSUE THREAD

**Issue by retrobenny** [TASVideos/BizHawk#784]
If you are using Glide64mk2 as the plugin of choice,it will crash after closing a game and going out of focus,sometimes it can crash after merely resetting the game and going out of focus.

The crash doesn't happen on GLideN64 and performance seems to be comparable or even faster,at least at 320x240 as the only way to get decent speeds.

In some cases,Glide64mk2 is preferred for some games in casual play,and Jabo is a mess on DK64 btw.

One really BIG case is the popular streamer Vinesauce running into unreasonable crashes due to Glide64mk2's misbehavior.
He does corruption streams,but the corruptions aren't causing most of those N64 crashes,only the resets and lost focus mostly due to that plugin acting up.

Glad I found out the cause of this particular crashing issue,so I hope a fix can be found.

**Comment by danne2** [comment]
To be clear, the exact issue Vinny has is NOT with the Glide64 plugin. Even if there is a bug here, that's not the issue he has on the stream.
The issue he was having was due to the way XSplit's game capture source hooks Bizhawk (specifically the real-time corrupter mod), and it's a RTC mod specific issue due to the way the RTC mod re-initializes the emulation core when loading a corruption, it'll cause the entire emulator to crash when utilizing n64 ones. It's most likely due to XSplit not freeing the video plugin. This isn't really a bug with Bizhawk itself though. It's an issue with the RTC mod.

**Comment by retrobenny** [comment]
Thanks for the info,can't argue with the 1st hand experience of the N64 plugin causing crashes without any recording software in use.

I do have a monitor displaying a 720p-ish laptop at 1080P,so there's speculation.

But...I just **tested directly on the laptop by itself** and with non-broken Nvidia drivers,and **it still crashes when using Glide64mk2 as the plugin**.
I even closed BizHawk first after changing to the plugin then cleanly opened it and ran the game for a few minutes doing a few things in Banjo-Kazooie **in windowed mode**,internal resolution at **320x240** and scale at 2x.
After closing the game,I click into the desktop and the crash occurs without any button for details.

It usually does a double-crash from this,I can upload the dump files if it will help greatly to solve the main issue.

I can't stand this issue,even though GLideN64 can be used for slightly better performance AND limitedly better accuracy anyway.

**Comment by retrobenny** [comment]
Dump files right here.

[EmuHawk.exe.5980.zip](https://github.com/TASVideos/BizHawk/files/736154/EmuHawk.exe.5980.zip)

**Comment by danne2** [comment]
N64 emulation is fairly unstable.

I'm not saying you aren't crashing, I'm just saying the issue you were mentioning where Vinny was having issues with N64 games crashing at load consistently was an RTC Mod specific issue with XSplit and that that has nothing to do with this issue.

**Comment by retrobenny** [comment]
Please don't ignore the dump files,this is about the actual on-topic BizHawk issue,so it may contain the info to help find a fix for the Glide64mk2 plugin triggering crashes on regular use when resetting or closing games and clicking out of focus.

**Comment by vgturtle127** [comment]
@retrobenny Does this happen on vanilla Mupen64Plus? I have never heard of this before.

**Comment by retrobenny** [comment]
I don't know,but another emulator at one point was having initialization issues with a Glide64 plugin as well,not sure which kind it was,most likely another Glide64mk2 copy I think.
PJ64 also has its own problems in certain conditions where it can crash upon trying to open the plugin's settings after switching the selected plugin on the same instance.

I can't find a friggin' way to download Mupen64Plus because the site is considered insecure by Chrome's privacy error and github has it in chunks with no release page.
And EmuCR is not the best option because of its download sources.
Also,the requirement of command-line hoop jumping makes it harder to try as well if you wanted me to test it in that strong of a vanilla copy.
Which GUI executable is the most standard one for the latest version of Mupen64Plus?

**Comment by retrobenny** [comment]
Tried it with qt launcher,rice was the default but I could set it to Glide64mk2.
It didn't crash at all between two different games Banjo-Kazooie 1.0 and Zelda Ocarina 1.0 with no problems from closing the first game and opening the second game.

That's the dilemma though,this is a bit different than BizHawk because what I had to use is not directly connected to Mupen like a front-end would be.
Even then,a command-line process would also be very different than BizHawk's fully featured GUI window.

**Comment by vgturtle127** [comment]
@retrobenny Yeah, the website is down and most of the mirrors are too. These work though:

https://github.com/mupen64plus/mupen64plus-core/releases

Which frontend did you try? When you say Qt launcher, which are you referring to?

**Comment by retrobenny** [comment]
Mupen64Plus-qt is the name of it and here's the github page for it.

https://github.com/dh4/mupen64plus-qt

I found the latest Mupen64Plus download on EmuTalk with the 2.5 update edited in.

http://www.emutalk.net/threads/55485-Mupen64Plus-v2-5-Mupen-s-Last-Stand-(on-Google-Code)

Darn,I forgot to test the version with "new dynarec" to see if that one would crash,I only tested the regular win32 build.

**Comment by vgturtle127** [comment]
@retrobenny Yeah, @dh4 is cool. CEN64-qt and mame64plus-qt work pretty well, minus not being optimized for 5000+ ROMs, anyway. 😉 

I'm currently using both for testing of CEN64 and Mupen64Plus.

I think the emulator crashing when the window loses focus is just weird, I can't imagine what would cause that unless it was pausing and the pause function had a bug.

Resetting or closing makes me think memory corruption, not cleaning up garbage, cache issue, etc. I'm not terribly familiar with Glide64mk2, so I can only guess right now.

**Comment by YoshiRulz** [comment]
Closing as this pre-dates 2.x and we're now recommending GLideN64.
