### ISSUE TITLE
bsnes rerecording performance mode warning not in front of tastudio

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#788]
"While the performance core is faster, it is not stable enough for movie recording. Switch to compatibility?" --> needs to be in front of tastudio also

users can accidentally make tases in performance mode

**Comment by vadosnaprimer** [comment]
I'm getting a crash if I start tastudio in compatibility mode.

**Comment by zeromus** [comment]
works fine for me....

**Comment by vadosnaprimer** [comment]
And now?

**Comment by zeromus** [comment]
It crashes now because the snes core has its profile changed suddenly without being restarted.
That would be harder to fix than changing the question to be "Want to proceed anyway?"
