### ISSUE TITLE
Scroll wheel missing from input.getMouse()

### ISSUE THREAD

**Issue by MittenzHugg** [TASVideos/BizHawk#790]
Not a major issue, but if the scrollwheel could be included with the lua input.getMouse function I would appreciate it. Working on a lua plugin that would benefit from having it.

**Comment by zeromus** [comment]
the scrollwheel doesn't have a position that can be read. Scrollwheel input is generally received on an eventwise basis. What I've done is add an accumulator for the mouse wheel. If you want to find out when the mouse wheel has changed, then record the previous value and look for differences.
the new key is "Wheel"
