### ISSUE TITLE
Feature request: Display name of loaded movie file on status bar

### ISSUE THREAD

**Issue by piratesephiroth** [TASVideos/BizHawk#791]
We're working the dream team contest and with multiple people making different branches I sometimes forget which one I loaded.
There's plenty of space in the status bar for that!

**Comment by adelikat** [comment]
It is already in the title bar, is that enough?

**Comment by piratesephiroth** [comment]
not if you have a rom with a huge filename

**Comment by zeromus** [comment]
Uhhh. I've got more room in my titlebar than I do my statusbar. This is a huge waste of statusbar space when we've already got the titlebar dedicated for this kind of thing and CANT put buttons there like we can in the statusbar. You should use smaller rom names if this is a problem, or a windows theme without a 100pt font in the titlebar

**Comment by piratesephiroth** [comment]
yeah, there's no room, really
![image of super crowded status bar](http://i.imgur.com/fOhOwyu.png)

**Comment by zeromus** [comment]
I didn't say there was no room in the status bar. Let me try explaining this again.
I said there was more room in my title bar than in my statusbar; and I said that in the future there could be more things in the statusbar, whereas in the future there is not likely to be more things in the titlebar.
I blamed the style of your titlebar, not the size of your statusbar.
If you want to post a relevant screenshot, post a screenshot of your titlebar, so I can say "see, your titlebar styling is bloated. I've even got more space in my titlebar than in my statusbar in windows 10.....

**Comment by Invariel** [comment]
As a workaround you can rename the ROM to something considerably shorter.

**Comment by vadosnaprimer** [comment]
It could also be optional what to show in the title. Like when there's a movie, we can't really forget what game we're playing, unless we're 2 years old.

**Comment by adelikat** [comment]
I think choosing what is displays in the title bar is over engineering.  Invarials suggestion is something simple that I've been doing for a decade now in all emulators.  Just do that.
