### ISSUE TITLE
Can't load virtual pad on Genplus-gx64

### ISSUE THREAD

**Issue by chozandrias76** [TASVideos/BizHawk#797]
Not a real big deal to me but, when I click on it, it throws this error:
![image](https://cloud.githubusercontent.com/assets/2087677/22856852/086d9d1a-f04f-11e6-9e90-9eb4e4ac4a4f.png)

**Comment by adelikat** [comment]
Don't mix a config.ini file from a 32bit build with a 64 bit one.  You need a fresh config.
