### ISSUE TITLE
Prints from gui.text not showing in video capture like other drawings

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#799]
When capturing a video with "Capture OSD" checked, prints from `gui.text` are not displayed in the video (I used mkv lossless), just other prints like `gui.drawText` and `gui.drawBox`, as in this image: ![](http://i.imgur.com/412D8mc.png)

**Comment by vgturtle127** [comment]
@brunovalads Huh, maybe some information is intentionally kept out of movies? Does this happen on all cores no matter what settings you use, or is there a specific instance where this happens?

**Comment by zeromus** [comment]
No, it's because different rendering mechanisms are used for different lua drawing functions. And precisely how they work may differ depending on the config > display > display method. So try changing that for a workaround, and drawing text differently (namely, dont use gui.text) as a secondary workaround

for reference, gui.text is an older canned system that kind of places labels on the screen, and gui.drawText tries to render text similarly to the other graphics

**Comment by vgturtle127** [comment]
@zeromus Ah, gotcha. When you say canned you mean it has just been abandoned? If it's still there I assume somebody kept it for a reason, but we all know what assuming does.

**Comment by zeromus** [comment]
no, abandoned is shitcanned. canned means it's designed to do one thing and get it done in its own way and it isnt really extensible or synergistic with other systems. for example, the rectangle-and-text-drawing system is engineered to be able to have transforms applied to the imagery (even if that functionality isn't exposed yet); however the canned label-on-screen system could never enjoy any of that automatic synergy.

**Comment by vgturtle127** [comment]
@zeromus Ha, you crack me up, dude. :laughing:

**Comment by brunovalads** [comment]
@zeromus @vgturtle127 I like `gui.drawText` so I might adapt this script so it will never user `gui.text`. About the the other display methods, I couldn't try yet, but I'll check later if there's a workaround. Lastly, I really like this BizHawk font for `gui.text`, don't know which is, is there a way to use this font in `gui.drawText`?

**Comment by vadosnaprimer** [comment]
Didn't know about this ticked but it's fixed in https://github.com/TASVideos/BizHawk/commit/68a0fcf408a5fad8deecc11554277ee63ceb5eaf

**Comment by brunovalads** [comment]
Oh thanks for that, and it works fine as you can see [here](https://www.youtube.com/watch?v=Eqxghx5rdUY)
It will help on some tutorials.
