### ISSUE TITLE
gpgx interlaced mode

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#803]
http://tasvideos.org/forum/viewtopic.php?p=448962#448962

> By default, Genesis Plus GX indeed keeps generating a 320x224 screen buffer on each emulated "frame" in interlaced mode 2 because that's what original VDP does and some frontend might want to do the interlacing themselves or let host video hardware handle it if can generate interlaced video from single-field framebuffers (that's the case with the Wii for example). 
> 
>  However, if config.render is set to 1, the emulator will render a 320x448 screen buffer in interlaced mode 2 with every other lines rendered on each emulated "frame", giving the illusion of interlaced screen. Tell Bizhawk devs they should have a look at the libretro port to see how this is done.

**Comment by zeromus** [comment]
re 4e2892d85277ab81696d5d93eaef098f0019359a
re 6c046a5df9439e667be383db35e38a745e6dee05
re ac2a69e7dd5b5f74f6164832ea0f5c04aad19534
I consider this issue fixed. I'm making a new issue for adding the always-double-size option which I consider optional
