### ISSUE TITLE
NES and N64 are 1 Player only

### ISSUE THREAD

**Issue by TravisDart** [TASVideos/BizHawk#804]
When I play NES or N64 games, only Player 1 shows up in the controller menu.

I couldn't find documentation saying that BizHawk only supports 1 Player for these consoles, so is there a way to fix this?

![nes](https://cloud.githubusercontent.com/assets/5155310/23090418/39a2bfb4-f563-11e6-8b67-64277ed393a8.png)

BizHawk 1.11.9.1 on Windows 8.1 on Intel i5

**Comment by jk314159** [comment]
Right now, the 2nd controller is "unplugged." Go to NES -> Controller Settings... -> NES Right Port -> ControllerNES to plug it in. After rebooting the core, the "Player 2" tab will appear in the normal Controller config.

**Comment by thelinuxtrans** [comment]
I know I'm late, but can anyone send screenshots of the fix? This is a little confusing for me
