### ISSUE TITLE
Unable to use QuickNES since 1.11.8

### ISSUE THREAD

**Issue by jk314159** [TASVideos/BizHawk#805]
Versions 1.11.8 - 1.11.9 of BizHawk give the error "unable to use quicknes, using NESHawk instead" when attempting to use QuickNES.  QuickNES worked fine in version 1.11.6. Haven't tested 1.11.7. Using Windows 10, 64 bit.

**Comment by vadosnaprimer** [comment]
QuickNES can't run any NES game at all? It can't run _some_, but should run others.

**Comment by hegyak** [comment]
Which Game(s) are giving this error?  Some games would be forced to use NESHawk due to emulator inaccuracies and such.

**Comment by jk314159** [comment]
It was a hack of Mario 1 called "Tower RE". Double-checking now, it seems the clean Mario 1 ROM works just fine. Upon further inspection, Tower RE uses mapper 4 rather than Mario 1's mapper 0. Maybe that had something to do with it?

**Comment by zeromus** [comment]
https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Emulation.Cores/Consoles/Nintendo/QuickNES/QuickNES.cs#L318
https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Emulation.Cores/Consoles/Nintendo/QuickNES/QuickNES.cs#L514
