### ISSUE TITLE
GBA - Mario vs Donkey Kong - File Select Music Issue

### ISSUE THREAD

**Issue by dotdissent** [TASVideos/BizHawk#808]
1.11.9

Open MvDK, File Select screen causes the music to clip and sound strange.

**Comment by danylopez123** [comment]
You might have the core on VBA-Next
Change it to mGBA, it worked fine for me

**Comment by dotdissent** [comment]
Yep, that did it. Is there no core auto-select per title for out of the box compatibility?

**Comment by danylopez123** [comment]
I dont think so

**Comment by zeromus** [comment]
We have the general capability of auto-selecting cores. However,
1. I don't think we've used it for GBA yet, and
2. I'm not sure we would use it in this case. It's best reserved for cases of total dysfunction. Clipping and music sounding strange isn't total dysfunction.

**Comment by mugg91** [comment]
I remember a similar issue; 
play Dragonball Z Legacy of Goku, start a new game. The part where it shows blue text boxes right at the beginning, it will have strange noise in the VBA-Next core.
