### ISSUE TITLE
N64 - Banjo-Tooie - Game crashing.

### ISSUE THREAD

**Issue by TheGoatManfan** [TASVideos/BizHawk#809]
So I decided to play Banjo Tooie on Bizhawk, until I encountered an issue - the game crashed after I got a jigsaw piece from getting a White Jinjo (creatures you collect to get jigsaw pieces for those unaware).

I know Banjo-tooie autosaves after getting major collectibles. And the game also has a strict CIC lockout checksum, going as far enough to crash when saving, and making things refuse to trigger.

My assumption is that the N64 core Bizhawk uses (Mupen, I think?) doesn't emulate the Banjo-Tooie CIC correctly yet. Something I know that some other N64 emulators do nowadays. I might be incorrect, though.

Either that, or the game just crashed without warning. Which I'd have no idea why it'd happen. I can upload a savestate if needed.

EDIT: After I loaded a quick savestate, Bizkawk undid the crash. This was after I flushed the saved RAM, if that helps with anything.

**Comment by vgturtle127** [comment]
@TheGoatManfan A few questions for you, if you don't mind.

1. Which ROM are you using? Revision/version, region, etc.
2. Have you tried the same crash with the cracked version?

**Comment by thecoreyburton** [comment]
Have you tried using the interpreter / pure interpreter as opposed to dynarec? I recall that fixing a number of problems like this at one point.

**Comment by vgturtle127** [comment]
@TheGoatManfan 
Try with the crack applied, and see if that helps. If not, try using the interpreter like @thecoreyburton 
said. It may help to use more accurate plugins and see if the crash still happens.

If you can give us a save state that would be nice too.

**Comment by YoshiRulz** [comment]
Could not reproduce on BizHawk 2.3, OS: Win10 Home 1709. Got all 9 jiggies from the Jinjos and none of them caused a crash.
