### ISSUE TITLE
Retroactively create tags for the svn era releases

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#811]
Wanna do it someday.

**Comment by zeromus** [comment]
You can use this log to cross reference revision numbers with git commits via the commit messages

[bizhawk-svn-pregit-log.zip.txt](https://github.com/TASVideos/BizHawk/files/802427/bizhawk-svn-pregit-log.zip)

(The attached file is actually a zip)

**Comment by zeromus** [comment]
Actually, dont do this yet. I plan to make a script that will merge a git log with an svn log to produce the lookup table.

**Comment by zeromus** [comment]
[svn-githash-mapping.zip.txt](https://github.com/TASVideos/BizHawk/files/805543/svn-githash-mapping.zip.txt)
(The attached file is actually a zip)

**Comment by zeromus** [comment]
relevant files are now hosted here including aforementioned lookup table
http://www.fceux.com/bizhawk-releases/

**Comment by zeromus** [comment]
done. this...was...not...easy.

see here for details.
http://tasvideos.org/Bizhawk/PreviousReleaseHistory.html

some of the versions couldnt be mapped properly, due to their being extremely cherry picked, and in release branches on svn that were deleted or otherwise didn't make it over to git, but most of them made it OK.

**Comment by vadosnaprimer** [comment]
I can restore the entire repo from svn if you want.

**Comment by zeromus** [comment]
so can i. it isn't clear how we'd move them to git.

**Comment by vadosnaprimer** [comment]
https://dominikdorn.com/2016/05/how-to-recover-a-google-code-svn-project-and-migrate-to-github/
That's how. Verified on fba-rr and mame-rr, whose entire svn history got restored and git'd. But newly exported tree won't merge, so just for the reference.

**Comment by zeromus** [comment]
be my guest. good luck moving the deleted branches over.

**Comment by vadosnaprimer** [comment]
As I said, they won't merge to this repo, as git would create entirely new commits. I tried that here with no success:
https://github.com/vadosnaprimer/fbarr/commits/restore-commit-history
Last few commits with gray mauzus pic are what was imported originally. All the rest is what I restored. I had to cherrypick the imported and artificially stick into the restored, despite of the fact that the restored repo had those cherrypicked commits too. But git didn't know.

For commits with identical changes the hash is still different. I can put this to my other fork and you could do whatever you want with it.

**Comment by zeromus** [comment]
It's not worth it. Many of our lost commits are on a release branch, which would mostly be huge merge commits. Rebuilding those will kill you, and just dumping the contents without merge tracking into git will be dozens of MBs. I dont care that much, I tagged most of them. The rest will be very costly to recreate. I don't intend to address this any further, you can close it if youre satisfied
