### ISSUE TITLE
TAStudio - input being erased when frames are added

### ISSUE THREAD

**Issue by mcwave** [TASVideos/BizHawk#816]
This is one simple flaw that's often ignored, causing confusion and frustration for some that are making long TASes. It only happens when a certain option is enabled.

Go to **Config** > **Customize...**, Click the **Advanced** tab.
Scenario A) If **Store movie working data on disk instead of RAM** is enabled, your input might get erased when frames are being added. 
Scenario B) If **Store movie working data in extended > 1GB RAM** is enabled, you will get a fatal exception if **Store movie working data on disk instead of RAM** is disabled.
Scenario C) If both **Store movie working data on disk instead of RAM** and  **Store movie working data in extended > 1GB RAM** are enabled, you may get the same result as scenario A.

**Comment by zeromus** [comment]
which bizhawk version? we just fixed bugs related to this in 1.12.0

**Comment by mcwave** [comment]
It happens in the following versions: 1.9.x, 1.10.x, 1.11.x, 1.12.0.
I turned them on, restarted the emulator, opened a ROM, opened TAStudio, I played to a certain frame without pressing any buttons (doesn't matter what frame), I paused it, placed input in several frames, unpause, and the input goes away. I don't know why it happens, but it does.

What the fixes for 1.12.0 include:
- Recording mode doesn't erase input during seeking anymore
- Stop latching user input in playback mode if new frames are generated

Input no longer latches in playback mode if new frames are generated, but they're still being erased. It only happens if Store movie working data on disk instead of RAM is turned on.

**Comment by zeromus** [comment]
I dont fully understand what you just wrote. I'm interpreting it as "I was testing on an old version before. Now I tested in 1.12.0 and the only bug is inputs mysteriously disappear when using movies-ondisk". I fixed inputs mysteriously disappearing, so I think all the bugs are fixed

**Comment by mcwave** [comment]
Well, let me demonstrate what happens if using **Store movie working data on disk instead of RAM**
![tas0001](https://cloud.githubusercontent.com/assets/25657572/23773129/7a49544e-04e3-11e7-9778-73e031af51ed.gif) ![tas0006](https://cloud.githubusercontent.com/assets/25657572/23777839/b13f08c2-04fc-11e7-92a8-201ba379cd74.gif)

**Comment by zeromus** [comment]
That's a cool video of "inputs mysteriously disappearing", which I fixed

**Comment by vadosnaprimer** [comment]
Cool indeed.

@mcwave, I'd like all your bug reports to be like this one. Right now they're just "A doesn't work, period". I can't do anything with such info, if you don't include exact reproduction steps that are 100% consistent.
