### ISSUE TITLE
Emulator crashes on startup

### ISSUE THREAD

**Issue by ThProjectShadw** [TASVideos/BizHawk#818]
The game I have been trying to play is Spyro 3, but whenever I load the rom BizHawk crashes. I have tried playing GBA games and they work fine, help?

**Comment by zeromus** [comment]
Try harder than "crashes".
Google: bizhawk firmware psx

**Comment by ThProjectShadw** [comment]
To put it simply; the emulator stops responding whenever the game is opened. I have tried playing it on ePSXe, but instead of crashing, it freezes on a logo screen. It's possible that it could be the ROM itself, but it's completely fresh so I doubt it

**Comment by zeromus** [comment]
Sounds like a pretty good theory to me. Try a different game.

**Comment by ThProjectShadw** [comment]
Tried playing Super Mario 64 and it worked fine. I just can't think of what the problem is.

**Comment by zeromus** [comment]
That was a lousy test. You should have tested another PSX game

**Comment by ThProjectShadw** [comment]
The rom itself works on ePSXe. Also, just tested Suikoden and the same thing happens

**Comment by zeromus** [comment]
Spyro 3 freezes on "a" logo screen in ePSXe (WHICH logo screen?)
If that's what you mean by "works" then I assume Suikoden freezes on a logo screen.
From that I conclude all your isos are broken.

**Comment by ThProjectShadw** [comment]
Spyro freezes on the universal logo screen and makes BizHawk crash. Suikoden just causes the emulator to crash without displaying anything. Both roms are working fine on ePSXe so the isos are fine

**Comment by zeromus** [comment]
Why are you talking about Spyro? We were talking about Spyro 3. Are you talking about Spyro 3?

You keep saying Spyro and/or Spyro 3 and/or Suikoden work in ePSXe. Before I can take that seriously, I need you to explain why you said Spyro 3 hangs at a logo screen in ePSXe, or say you were mistaken.

Write words that make sense.

Games working in ePSXe does NOT mean the isos are fine. It means only that theyre good enough to work in ePSXe. They may still be broken. They may be complete nonsense -- ePSXe supports plugins, some of which are designed to support nonsense isos.

**Comment by ThProjectShadw** [comment]
From the start then? When I open Spyro 3 in BizHawk, the emulator just crashes, when opened in ePSXe, it reaches the "Universal" logo screen and THEN crashes. It is obvious to me that the rom is the problem in this situation based on what you have told me regarding broken isos. The reason I mentioned Suikoden was because you asked me to test another PS1 rom using BizHawk, and the result was the same, BizHawk just crashed.

**Comment by zeromus** [comment]
OK that was better, but you still couldn't complete the experiment and tell me exactly what happens for suikoden then in ePSXe (from the start)
Anyway it seems clear enough all your isos are broken. About the only things that can go wrong with PSX are broken iso, missing firmware (which is not this problem), and nothing-works-at-all (definitely not the problem if n64 is working)

**Comment by ThProjectShadw** [comment]
This is probably a stupid question. But is there a way to fix a broken ISO?

**Comment by hegyak** [comment]
Dump the Game Again.

**Comment by Cibomatto2002** [comment]
Maybe you need to check your ISO. This is where I check my games and that all work fine if the CRC32 matches. http://redump.org/

**Comment by ericwendt** [comment]
Amazing how much animosity was thrown at someone just trying to fix their game. If you're going to be annoyed with every comment he makes, go find a different thread.
