### ISSUE TITLE
tastudio lua functions request

### ISSUE THREAD

**Issue by TASeditor** [TASVideos/BizHawk#821]
- int tastudio.getmarkerindex(int frame)
 Smiliar to FCEUX's int taseditor.getmarker(int frame), where it looks for the latest marker above the frame if the frame isn't marked. For TAStudio there's currently only a function to get the text of a marker AT a given frame.

- table tastudio.getselection()
 Returns the frame numbers for all selected frames

- tastudio.submitinputchange(int frame, int joypad, int input)
- tastudio.submitinsertframes(int frame, int number)
- tastudio.submitdeleteframes(int frame, int number)
- int tastudio.applyinputchanges()
- tastudio.clearinputchanges()
 Functions for lua input in TAStudio. Should be same behaviour as from FCEUX.
 Or remove the submit/apply logic and always set the input after calling the function, but the input should only be set if it is different from the current input in the piano roll. Insert and delete need to always be set, regardless of the current input.

- tastudio.applyinputchangestobranch(int slot)
Such function might be useful for threaded botting, where the input from a second BizHawk client is stored into a branch without distracting the user to much from working with TAStudio.

- tastudio.setcolor(int frame, color, column)
- tastudio.clearcolor(int frame, column)
Set a row in the piano roll with a specified color, the column argument specifies if the color should be drawn on the whole row, on the frame number column, on player 1, on player 2, ... . It will be useful to display when events happen in the game without the need of careful frame-advancing, e.g. lowering boss health. 
And clearing the color should be there aswell.

**Comment by adelikat** [comment]
onqueryitembg should be used to set color, in which case you would not need setcolor or clearcolor

**Comment by TASeditor** [comment]
But how is the color set/cleared?
And how are columns specified?

**Comment by adelikat** [comment]
onqueryitembg, onqueryitemtext, and onqueryitemicon are called everytime tastudio draws the listview.

you pass in a lua function that takes an int and string param (row index and column name) and return a value.

For bg it is a color, text is string, and icon is bitmap

For example:
function OnBGDraw(row, column)
    if (column == "P1 A") then
        return "red"
    end
end
tastudio.onqueryitembg(OnBGDraw)

**Comment by vadosnaprimer** [comment]
I think the docs need to mention what kind of function these expect.

**Comment by TASeditor** [comment]
Well I don't really understand how I would use it for my purpose.
Can either one of you provide me a script for SMB1 that sets color to red on P1 A on the frame when Mario hits ground (only color one frame); and sets color to blue on P1 B on the frame when Mario hits 0 speed.

**Comment by adelikat** [comment]
speed = 0;
speedTable = {};

function OnBGDraw(index, column)
	entry = speedTable[index];
	max = max + 1;

	if (entry ~= nil) then
		return "red";
	end
end

function OnBGText(index, column)
	if (column ~= "FrameColumn") then
		return nil;
	end
	entry = speedTable[index];
	if (entry ~= nil) then
		return "bad";
	end
end

tastudio.onqueryitembg(OnBGDraw);
tastudio.onqueryitemtext(OnBGText);

while true do
	frame = emu.framecount();
	speed = mainmemory.readbyte(0x0057);
	if (speed < 40) then
		speedTable[frame] = speed;
	else
		speedTable[frame] = nil;
	end
	gui.text(1, 60, "Speed: " .. speed)
	emu.frameadvance();
end

**Comment by adelikat** [comment]
Here's an example, this script is for smb with tastudio open.  It checks frames to see if mario's speed is less than 40 (max) and draws the bg in red and prints "bad" as the frame count.

I hope this helps

**Comment by TASeditor** [comment]
It helps. But what is the reason for not doing setColor(frame, color, column)?

**Comment by adelikat** [comment]
The internals of tastudio isn't conduscive to that?  I suspect neither is taseditor and it is doing a lot of shenanigans to make it like that.  Either way an a map of all cell,value pairs has to be tracked for that to work.  I'd rather keep that complexity script side
