### ISSUE TITLE
fresh windows 10 x86 with incomplete prerequisite install can fail to detect a properly functioning d3dx and advise the user to install prerequisites

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#823]
fresh windows 10 x86 with incomplete prerequisite install can fail to detect a properly functioning d3dx and advise the user to install prerequisites

maybe moot now that prerequisite installer is more robust.

need to debug on a fresh VM.

if anyone can reproduce, try calling other D3DX9 functions in the prereq tests to confirm whether it works, rather than going deeper into direct3d startup, bombing during D3DX9CompilerShader, stomping all over the system, and throwing exceptions .net can't catch

ALSO: if the d3dx check fails, go ahead and drop to gdi+ fallback, because some systems will crash when trying to boot d3d display method when d3dx is missing

ALSO: we could "fallback" to d3d10 but thats a lot of work

ALSO: we could precompile shaders and not use d3dx at all! this may be worth doing (it's not very hard, and I've done it before). it's more of a project-organization-build-process type problem

**Comment by nattthebear** [comment]
Is this still a problem in 64 bit?

**Comment by zeromus** [comment]
I dont know but the ALSOs are still ideas we should have written down somewhere

**Comment by YoshiRulz** [comment]
1. GDI+ fallback is already done: [Program.cs:284](https://github.com/TASVideos/BizHawk/blob/76070cd89dce2e88ebf9afc28db3239adbeae1e5/BizHawk.Client.EmuHawk/Program.cs#L284)
2. no comment beyond "OpenGL > DirectX"
3. see 2

Can this be closed?
