### ISSUE TITLE
BizHawk EmuHawk has stopped working (Windows 7)

### ISSUE THREAD

**Issue by roflcopter777** [TASVideos/BizHawk#824]
Version 1.12.0 (most recent build, vanilla)

Crash details: 

Problem Event Name:	CLR20r3
  Problem Signature 01:	EmuHawk.exe
  Problem Signature 02:	1.12.0.1
  Problem Signature 03:	58accd86
  Problem Signature 04:	EmuHawk
  Problem Signature 05:	1.12.0.1
  Problem Signature 06:	58accd86
  Problem Signature 07:	ca9
  Problem Signature 08:	9d
  Problem Signature 09:	System.TypeInitialization
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Windows 7 64-bit pro
CPU - Core i5 3570  
8 GB RAM  
Prereqs have been installed, tried making its own directory, emulator should open as well as the last version, but the bloody thing refuses to load, and it's really starting to tick me off. Why doesn't this emulator work anymore? What am I doing wrong?   The emulator immediately crashes whenever I load it, my computer is more than powerful enough, but isn't super new, so I don't know what could be the cause, and I'm the only user so account is an admin account.

**Comment by zeromus** [comment]
doesn't work any more since you updated it, or doesnt work anymore since you did nothing at all?

**Comment by roflcopter777** [comment]
I didn't think of using the most recent build, I'll try that next, no idea why it did that.
