### ISSUE TITLE
GBA Wario Ware Twisted - Motion controls for Virtual Pad & TASTudio?

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#830]
To make the spin controls works, i need to grab a gamepad, bind an Analogic Jostic to Z and then do stuff with the gamepad in-game, but can't we have a feature that we can do this for the Virtual Pad and TAStudio?

**Comment by zeromus** [comment]
Your question is unclear. Define "do stuff". Tastudio and virtual pad can do everything in-pad gamepad can.

**Comment by danylopez123** [comment]
I mean, like, use the binded analog stic to use the spin controls to play the game.
Also, there is nothing else in TAStudio and Virtual Pad
![where](https://cloud.githubusercontent.com/assets/17708894/24989908/48219a10-2010-11e7-8bce-9bd56bb13275.png)

**Comment by zeromus** [comment]
If you want a column with the analog controls in tastudio, then use the columns menu.
But... it seems we'll have to leave this bug open for the virtual pad. Dunno why it isn't there.

**Comment by danylopez123** [comment]
I just opened it, and that it

**Comment by zeromus** [comment]
whatever you just said doesn't make any sense
