### ISSUE TITLE
BizHawk crashes when loading any NES rom with EmuHawk core

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#833]
I dont get it, this was working fine before with the EmuHawk core, sure it works fine with QuickNES, but now i dont understand why it keeps crashing, i tried with most of my NES roms and keeps crashing.

Everytime it crashes, i get this (Apologizes for some Spanish text, i live in Spain and my PC is Spanish)

System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en BizHawk.Emulation.Cores.Nintendo.NES.PPU.FrameAdvance()
   en BizHawk.Emulation.Cores.Nintendo.NES.NES.FrameAdvance(Boolean render, Boolean rendersound)
   en BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   en BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   en BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by alyosha-tas** [comment]
What build / release are you working with?
Also what operating system are you using?

**Comment by danylopez123** [comment]
Latest version 1.12.1
Windows 10 x64 bits

Also, idk if is just me, or it was working before this happens

**Comment by zeromus** [comment]
what's "most of your NES ROMs"? Give the information written in the Dump Status Report under the green checkmark for one game

**Comment by alyosha-tas** [comment]
Everything works for me in both 1.12.1 and the most recent Dev Build. 

As Zeromus says try to give as much information as possible.

**Comment by danylopez123** [comment]
But how i can do that? And what i mean with most of my NES Roms is it because i tried with many of mine, but now i tried more, and still it keeps crashing, i think its affecting to all roms

**Comment by zeromus** [comment]
how can you give the information written in the dump status report under the green checkmark for one game?

tried "more" what?

if your next post is not a list of games, and the information I requested, I will close this thread.

also: try deleting your config.ini file

**Comment by danylopez123** [comment]
Close it already, this problem has been fixed with the new update, sorry for this, is just im not like a nerd
