### ISSUE TITLE
AV Super Real Pachinko

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#836]
This NES Rom, doesn't render correctly after the title screen.

From MESS:

	<software name="avsrpchi">
		<description>AV Super Real Pachinko (Jpn)</description>
		<year>1991</year>
		<publisher>Hacker International</publisher>
		<info name="serial" value="HKI-07"/>
		<info name="alt_title" value="AVスーパーリアルパチンコ"/>
		<part name="cart" interface="nes_cart">
			<feature name="slot" value="gxrom" />
			<feature name="pcb" value="2209-A" />
			<dataarea name="chr" size="65536">
				<rom name="0.chr" size="65536" crc="be68914b" sha1="c77697cfc97464cec7517f72d0824aba2e1e43e7" offset="00000" />
			</dataarea>
			<dataarea name="prg" size="65536">
				<rom name="0.prg" size="65536" crc="b66ff0f1" sha1="c11d158465475bfe8fdd950fb39180df2ef597f0" offset="00000" />
			</dataarea>
		</part>
	</software>

From BizHawk:

```
BEGIN NES rom analysis:
Found iNES header:
pr=64,ch=64,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER066,sys=
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: sha1:8928F7293C12EE7D3FC90BECC68AE5261802EAA6
headerless rom hash:  md5:519FE3E60059C972FF398DF013CD881C
Could not locate game in bizhawk gamedb
Could not locate game in nescartdb
Attempting inference from iNES header
Chose board from iNES heuristics:
pr=64,ch=64,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER066,sys=
Final game detection results:
pr=64,ch=64,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER066,sys=
""
Implemented by: class GxROM
END NES rom analysis
```

What happens after the start screen:
![av super real pachinko japan unl 2017-05-02 05 21 16](https://cloud.githubusercontent.com/assets/5711691/25617487/69c42ee4-2ef7-11e7-9768-b001991b0f4c.png)

**Comment by alyosha-tas** [comment]
This fix would be trivial....if I could find the game 0_0

**Comment by hegyak** [comment]
@alyosha-tas Do you need a headered or Unheadered ROM?

**Comment by alyosha-tas** [comment]
Either will do. The ines header appears correct from posts I've seen elsewhere.

**Comment by hegyak** [comment]
Here's the ROM I used.  It should be valid.  At least No-Intro says so.  And it has the header.

[AV Super Real Pachinko (Japan) (Unl).zip](https://github.com/TASVideos/BizHawk/files/973443/AV.Super.Real.Pachinko.Japan.Unl.zip)

**Comment by hegyak** [comment]
Re-Opening this due to a game breaking Bug.

To recreate the bug, At the start of the game, press Start.  In the Arcade area (The area with the machines) go to the Guy and press A.  Then press down once or twice.  Then press A again.  You should have balls now.

Go to any machine.  The game should crash.

**Comment by alyosha-tas** [comment]
Works fine for me, both in 1.12.2 and in dev build. I can play any mchaine I want.

what build are you using? Make sure you have the gamedb entry. It is needed since the default ines header has the wrong mirroring in it.

**Comment by hegyak** [comment]
Apparently, doing Pull and Rebase on my Sources, didn't work right.  So I added the line manually to my GameDB file.

Been a long time since I have done BizHawk stuff.
