### ISSUE TITLE
Movie system Id () does not match the currently loaded platform

### ISSUE THREAD

**Issue by Alxei200** [TASVideos/BizHawk#837]
I was making a Dr. Mario TAS with TAStudio. I stopped working on it for a while and attempted to re-open it later on and got this error:

Movie system Id () does not match the currently loaded platform (NES), unable to load

**Comment by vadosnaprimer** [comment]
Latest release?

**Comment by Alxei200** [comment]
I created a TAS in 1.12.1, but have since updated to 1.12.2.

**Comment by vadosnaprimer** [comment]
Dows it open with the latest 7zip?
