### ISSUE TITLE
run lua strings on commandline

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#842]
Running lua scripts on the commandline will enable some batch/automation scenarios which would otherwise be cumbersome or take dedicated support in the frontend

**Comment by Ashafix** [comment]
For my own project I needed this functionality and added two command line arguments.

```
--lua=
--luaconsole

```

The first one opens a console and loads the specified script.
The second one just opens the console.

Are there any other features required?

If not, I'll just make a pull request.

**Comment by zeromus** [comment]
make a PR

**Comment by Ashafix** [comment]
#905

**Comment by zeromus** [comment]
It's a wiki. You get permissions to the wiki.
Or you don't and I update it, like I just did.

**Comment by adelikat** [comment]
you have wiki edit privs now
