### ISSUE TITLE
[request] TAStudio branch lua functions

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#843]
While working on TAStudio using various branches would be nice to get information in lua, like:
- `table tastudio.getbranches()`: Returns a table with current branches, with id, frame and text;
- `table tastudio.getbranchinput(int branch_id, int frame)`: Returns a table of buttons pressed on a given frame of the chosen branch;
- some function to read greenzone data of other branches in order to know the memory state at a given frame or prior to that.

My intention is to make a ghost script to be used **while** you're TASing.

**Comment by vadosnaprimer** [comment]
Can't work on this anytime soon.

**Comment by vadosnaprimer** [comment]
BTW how are you planning to draw ghost input letters (if that's your plan)?

**Comment by brunovalads** [comment]
@vadosnaprimer My idea is to display different instances of the character, exactly like this ghost display in this video https://www.youtube.com/watch?v=Qd1y27xMIBA
The problem is that this script used to make the ghosts uses data from separate movies, you kinda need to run each movie in order to record stuff, only then you get the final result.
My idea is reading data form the branches of the tasproj you are _currently working_, in order to manipulate this data to display ghosts in realtime, to help the comparison between branches.

**Comment by vadosnaprimer** [comment]
Yeah except that doesn't answer my question. Imagine you have info about branch input. What do you do next?

**Comment by brunovalads** [comment]
I forgot what I thought for the inputs, I guess my idea was to compare inputs from different branches looking for matches and differences to develop a tree view of them.
More important than inputs, the ram data from the greenzone would be essential for this ghost idea.

**Comment by adelikat** [comment]
Implemented :)
