### ISSUE TITLE
mGBA Core - De-Sync when playing recorded input

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#844]
This happened to me 3 times:

Space Channel 5 - De-Sync when saving after the last stage in Normal mode
Mario vs. Donkey Kong - De-Sync at certain point in Stage Selection
WarioWare Minigame Mania - De-Sync at some Microgame in the opening one

I might not trust trying this but with the VBA-Next core due i saw some games that doesn't go well with this Core, take for example LEGO Drome Racers, VBA-Next freezes at the title screen but the music keeps playing with missing beats, but mGBA fixes the problem

**Comment by zeromus** [comment]
elaborate "de-sync at a certain point in stage selection".

**Comment by danylopez123** [comment]
I dont know how i can explain this but...

When i tried to choose a stage as fast posible, it was goin fine, but then, like when i enter level 1-4 or so, the input de-syncs

**Comment by zeromus** [comment]
1-4 of which game? If you have a tas which desyncs, then post it.

**Comment by danylopez123** [comment]
Mario vs Donkey Kong, ill try making it again

**Comment by zeromus** [comment]
I'm gonna close this due to @danylopez123 and this bug sounds like "mgba never ever syncs" which seems rather unlikely, and this core is now waterboxed which would likely fix it even in that unlikely event
