### ISSUE TITLE
Won't load ROMs, but savestates work

### ISSUE THREAD

**Issue by ScoutKyrre** [TASVideos/BizHawk#845]
I am trying to load an N64 (Super Smash Bros. (U)) ROM. When I do, I just get a black screen with the (red) frame count ticking, forever. However, I can get into the game by loading savestates, and then it runs fine. This is an okay workaround but I need a fresh load for some TAS movies and other things. How do I resolve this? Thanks in advance.

**Comment by vadosnaprimer** [comment]
Try other video plugins.

**Comment by zeromus** [comment]
How did you get savestates in the first place?
