### ISSUE TITLE
mgba audio bug

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#846]
In Bizhawk 1.12.2 mgba-core, in Mario & Luigi Superstar Saga when talking to NPC in the castle town and loading a state at the same time, the audio messes up. 

Video of the problem, and a .bk2 are here:
http://tasvideos.org/forum/viewtopic.php?p=452973#452973

**Comment by mugg91** [comment]
Doesn't seem to happen in 1.13.0

**Comment by vgturtle127** [comment]
@mugg91 
Is this an issue in the latest stable and nightly version of mGBA?

**Comment by nattthebear** [comment]
We've updated mgba.  Feel free to reopen if still broken on 2.0.
