### ISSUE TITLE
Crashes when I try to open using Wine with Mono and Gecko installed

### ISSUE THREAD

**Issue by agpirie** [TASVideos/BizHawk#849]
I'm having issues opening BizHawk in Wine

I have used Winetricks to install some components, I have installed Mono and Gecko, I am on Wine 2.8 please help.

OS: KDE Neon 5.9.5 (Ubuntu-based)

[Here is the log](https://hastebin.com/emodiwijic.rb)

**Comment by Sappharad** [comment]
You can't use Mono, it's missing functionality. You need to install the official .NET Framework in WINE:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=25478

**Comment by zeromus** [comment]
Bizhawk on wine isn't supported, unless a skilled and committed programmer comes on IRC and debugs and codes on it with us.
