### ISSUE TITLE
LiveSplit UI behaviour is inconsistent from time to time

### ISSUE THREAD

**Issue by RickardNi** [TASVideos/BizHawk#852]
Not sure if this is a known bug or not, haven't found anything about it.

Starting LiveSplit after using different splits sometimes causes the application to start in a mode where all UI text are scaled up, or much bigger. Exiting the application and restarting it sometimes resets it to proper behaviour.

I created a video to demonstrate the behaviour:
[https://www.youtube.com/watch?v=87sGGHcwOA8](https://www.youtube.com/watch?v=87sGGHcwOA8)

This forces me to use a new folder and LiveSplit application for each game/split I want to use, which is quite annoying.

**Comment by zeromus** [comment]
you wrote a bug to the wrong project

**Comment by RickardNi** [comment]
Sorry, not sure how I submitted this to the wrong project. Too many tabs.
