### ISSUE TITLE
need fix from gpgx upstream (Cannon Fodder glitch)

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#854]
When I look at the level map at this level, and then go back to menu, the graphics become glitched. They go back to normal once I unpause the game.
[Cannon_Fodder_glitch.zip](https://github.com/TASVideos/BizHawk/files/1022514/Cannon_Fodder_glitch.zip)

**Comment by vadosnaprimer** [comment]
Does it glitch on libretro's gpgx?

**Comment by Reinc01** [comment]
Uhh... does this emulator require gamepad? I can only use keyboard.

**Comment by vadosnaprimer** [comment]
It supports keyboard as well.

**Comment by Reinc01** [comment]
It glitches on libretro's gpgx. I open the map, then press Start to close it, an the screen turns to garbage.

[cannon_fodder.zip](https://github.com/TASVideos/BizHawk/files/1024594/cannon_fodder.zip)

**Comment by vadosnaprimer** [comment]
Alright, so your best bet is to report it to the guy who's author of the gpgx core. When he fixes it, we might pull it too.
https://github.com/ekeeke/Genesis-Plus-GX/issues

**Comment by Reinc01** [comment]
The Genplus-gx author confirmed the glitch happening, but needs to know if it happens on real hardware too.

**Comment by adelikat** [comment]
Please test this on the 2.1 release, it should be fixed there.  Note that your savestate-anchred movie will not work on the new release.

**Comment by Reinc01** [comment]
I tested it, and there is no glitch now. Although, I really wish my old input movies worked in the new releases.

**Comment by nattthebear** [comment]
Old input is fine (but may require resyncing).  Old savestates are not.

Closing since this was fixed
