### ISSUE TITLE
ROMs will be accepted into the system, but, won't load.

### ISSUE THREAD

**Issue by Kilil** [TASVideos/BizHawk#855]
I just downloaded your software, and, read the instructions, but, when I try to load ROMs, (I.E.: Super Mario World), they don't load, and, all I end up with is a blank screen.

**Comment by alyosha-tas** [comment]
Can you post a screen shot of your bizhawk program window after you load the ROM?

**Comment by Kilil** [comment]
I'm using Windows 10, and the screen is just black in Bizhawk.

**Comment by alyosha-tas** [comment]
I mean the entire program window, including the menues, it has a lot of useful information in it.

**Comment by Kilil** [comment]
How am I supposed to do that?

**Comment by alyosha-tas** [comment]
Just use print screen. 
EX:

![ex](http://i67.tinypic.com/3013vi1.png)

**Comment by Kilil** [comment]
![2017-05-26](https://cloud.githubusercontent.com/assets/28904654/26506132/6a8a5fe4-4219-11e7-8c3f-5def5a61e34d.png)

**Comment by alyosha-tas** [comment]
Is that after you already loaded the rom ? Also did you install the prerequisites?

**Comment by Kilil** [comment]
Yes and yes

**Comment by alyosha-tas** [comment]
Well, I'm stumped. Try the latest Dev Build from here:

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by hegyak** [comment]
Was the entire archive extracted or just the main EXE File?  Because that may be what is causing this issue.

**Comment by Kilil** [comment]
Nope, I've got everything

**Comment by alyosha-tas** [comment]
My only other suggestion would be to try loading a nes rom and see if that works, since that has less external dependencies then snes.
Also try the dev build I linked above

**Comment by zeromus** [comment]
Also try opening the rom different ways: drag and drop; file>open; command line.
It looks to me like the opening has been IGNORED, which would happen through drag and drop, on a system with overzealous security software or admin lockdowns

**Comment by alyosha-tas** [comment]
@Kilil are you still having issues with this?

**Comment by Kilil** [comment]
Yes

**Comment by zeromus** [comment]
List everything you tried.
The screenshot contains no text in the console window. Either your system is so screwed up that it can't print text to a console window, or that was the first time you opened the console window. Try it again now that you've surely closed bizhawk and reopened it--the console window should have text in it.

**Comment by Kilil** [comment]
I've tried manually putting it in,
I've tried getting the unstable version, and,
I've tried contacting you guys

**Comment by Kilil** [comment]
Also, I've tried putting in older games

**Comment by zeromus** [comment]
"Manually putting it in" doesn't make any sense. Use different words. For instance, copy the words I wrote for how to open roms, as you try each one, and then say "I tried that"

Who told you to try older games? We told you to try NES games.

You haven't tried everything we listed. 

1. Confirm your console log now has text in it

**Comment by Kilil** [comment]
I'm giving up on Bizhawk, I tried and tried to make it work, just so I can get some inspiration for pixel art, and, I knew that I would have problems due to my computer, so, give up on Bizhawk.

**Comment by zeromus** [comment]
Sounds like you saw this coming. Bizhawk is not tolerant of trashed computers. Try an older snes9x.

**Comment by 9math7** [comment]
Hi, i had an issue with
![bizhawk 2](https://user-images.githubusercontent.com/47719035/52915784-103e7780-32a6-11e9-8b26-a0e53784ee86.png)
![bizhawk 3](https://user-images.githubusercontent.com/47719035/52915785-103e7780-32a6-11e9-89b8-1e405a35fe93.png)
![bizhawk issue](https://user-images.githubusercontent.com/47719035/52915786-10d70e00-32a6-11e9-9739-4c4014022b8c.png)


 Bizhawk the black screen is a normal game working on my project64 but it wont open on bizhawk, the colored screen is my randomize rom for Oot, i downloaded the prerequisite, i tried the latest dev build, maybe i did something wrong theres some screenshot hope someone can help me thank you!

**Comment by YoshiRulz** [comment]
@9math7 moved this to #1489

**Comment by Milopk11** [comment]
I have the same issue, except  i get an error saying that standalone RTC isnt running, even if it is. I am desperate and ive been spending the last hour trying to get it to work, but nothing that i tried got it to work.

**Comment by zeromus** [comment]
I put as much work into helping you as you did giving me information to help you with, such as copying an exact error message or saying what rom(s) you're using.
-eof-

**Comment by YoshiRulz** [comment]
That sounds like a question for the [RTCV issue tracker](https://github.com/redscientistlabs/RTCV/issues).
