### ISSUE TITLE
Window Position Problem with Custom Size

### ISSUE THREAD

**Issue by RickardNi** [TASVideos/BizHawk#858]
I put up a feature request, #853, which was responded that such funcationality could be mimiced with custom size, which works great, except the window position is not working as intended (I think).

I recorded a demonstration of the problem:
[https://youtu.be/ruc3Mf-ywqI](https://youtu.be/ruc3Mf-ywqI)

Windows positioning seems to work okay, except when I use it with a custom size (where the height is the same as maximized or dragged to half-screeen in W10). Upon next restart, it will place the window above the screen so the menu bar isn't visible, and thus I'm unable to move it. Upon exit, it will also save a negative value to the Y position (seems reasonable and correct since the coordinate is probably the correct one), but even setting that value to 0 (which should place it at the correct and intended position), the application still starts it above the screen once again.

I should mention that my native resolution is 3840x2160, not sure if 4k monitor contributes to the problem (had a lot of weird UI bugs because of this in other applications).

**Comment by zeromus** [comment]
Please repeat the process and try moving the window slightly after setting the resolution. If it does the same thing theres no need to record another video.

**Comment by RickardNi** [comment]
Ok, thanks for your response, I will try to do that later when I come home.

But I can immediately say a couple of things (after trying around a bit more):
- First of all, I can't really move the window once it goes over the top. Not only is the window title bar not reachable, but the menu doesn't work with ALT + arrows.
- I can move the window to one side of the screen with WIN + arrows (which is the only way I can get back the title bar again). Doing so of course resizes the window, but moving it afterwards will result in an approximate correct size of the window again (I say approximate because sometimes it covers the entire height of the screen, minus the taskbar, correctly, and sometimes it misses a couple of pixels, not a big problem though).
- Loading up a ROM seem to restore the window size in the same manner as described above.

This basically means that I have a workaround for now. Start up the game, use WIN + right to set it to half-screen (Windows built-in), then move the window to restore the size, then load up the ROM, then reposition the window.

Note that window position itself is not the main problem here, but rather that the position becomes a negative Y value upon start. Of course, a precise window position would be greatly welcome, but that is less of an issue at this point.

**Comment by zeromus** [comment]
I've never heard of alt+arrows. Use alt+space, M, and then arrows.

**Comment by zeromus** [comment]
You can't set the window size to the values which would achieve the maximized results. The window is going to try displaying with the window border chrome, and it is then too large. Trying to make a program display too large counts as abusive. Everything's going to melt down. Your methodology is not good. Shrink the height by an amount to leave room for the border, or use config > display  >window > Windowed > None

**Comment by RickardNi** [comment]
I hear you, but in my book, this still counts as a bug. If you really don't think so, then fine, and I can see that the issue is already closed.

I understand what you're saying, but it's not really an excessive window size, even counting in the border. Even setting the display size to something smaller produces the same behaviour, and it seems that lowering the values more and more brings the Y position closer to 0. Setting it to a height of 1925 pixels starts BizHawk with 2/3 of the title bar over the top of the screen. I mean, why would it ever want to have a negative Y position at all?

In that specific case, it leaves out a gap in the bottom of 106 pixels between the window and the taskbar, which is far more than any border + main title would cover.

Also tried multiples of 2, didn't make a difference.

You're the developer ofc and I can't demand anything here. Lowering the size works, even if it's not ideal, so I would classify this as a minor issue or annoyance for now.

**Comment by zeromus** [comment]
It wants to have a negative Y position because windows or .net are malfunctioning trying to produce and position a window that's too large. It's pushing itself off the top of the screen when it's trying to make sure the bottom of the window is visible. 

I can only repro this when I use abusive values.

Windows is trying to push your window to -98. That means it wants 98 more pixels. Why, I don't know. Your choice of 1925 is eccentric; try 1894 (1992-98) and stare at your screen for a long time and try to determine why windows thinks thats how much room bizhawk takes up. Shadows under window? glows? bling? Beats me.
