### ISSUE TITLE
[Genesis] Can't add cheat codes using the same address multiple times

### ISSUE THREAD

**Issue by BooBerry** [TASVideos/BizHawk#864]
I'm in the middle of converting a lot of Game Genie/Pro Action Replay cheat codes from Kega Fusion .PAT files over to the Genesis Plus GX core in BizHawk's format and I've encountered a snag; I can't add multiple cheats that use the same address (and different values). Kega Fusion allows this, along with Genesis Plus GX on the Wii but BizHawk doesn't. I'm guessing this is done to prevent enabling different cheats/effects that use the same address.

PAR codes example from Sonic & Knuckles + Sonic The Hedgehog 3 (USA) which use the same addresses but different values for a different effect;

```
FFFFB2:0101	Have all Chaos Emeralds (alt) (1 of 4)
FFFFB4:0101	Have all Chaos Emeralds (alt) (2 of 4)
FFFFB6:0101	Have all Chaos Emeralds (alt) (3 of 4)
FFFFB8:0101	Have all Chaos Emeralds (alt) (4 of 4)
FFFFB2:0202	Have all Chaos Emeralds (Hidden Palace) (alt) (1 of 4)
FFFFB4:0202	Have all Chaos Emeralds (Hidden Palace) (alt) (2 of 4)
FFFFB6:0202	Have all Chaos Emeralds (Hidden Palace) (alt) (3 of 4)
FFFFB8:0202	Have all Chaos Emeralds (Hidden Palace) (alt) (4 of 4)
FFFFB2:0303	Have all Super Emeralds (alt) (1 of 4)
FFFFB4:0303	Have all Super Emeralds (alt) (2 of 4)
FFFFB6:0303	Have all Super Emeralds (alt) (3 of 4)
FFFFB8:0303	Have all Super Emeralds (alt) (4 of 4)
```
Right now I can only add once instance of these cheats once (for addresses FFFFB2, FFFFB4, FFFFB6 and FFFFB8), and I have to manually the values to change to the desired effect.

Instead of outright preventing cheats using the same address from being added, how about some sort of dialog that pops up only when enabling cheats using the same address to prevent a clash? The alternative here could be allowing multiple values to be added and can be selected (e.g. from a drop down menu, with a description for each value ala PJ64 and Regen does)?

P.S. Is multi-code cheats supported for the Genesis core? I haven't tried yet, but if so what's the correct syntax?

**Comment by hegyak** [comment]
According to the Cheat Code logic I am being shown, the game checks those four Addresses, then does something based on the value.

And, yes Multi Code cheats should work on any core, in theory.  So long as you are changing various Addresses and not attempting to write multiple values to the same address at the same time.

**Comment by BooBerry** [comment]
Yes, and the cheat codes above set the value for those four addresses to one of three possibilities, so there's 3 sets of 4 codes listed above. But I can't add additional cheats to the Cheats dialog using the same address and different value - it edits and overrides the existing cheat, renaming it and moving it down to the bottom. Editing the .cht file manually and adding the additional cheats (using the same addresses, but different values) doesn't work either. That's the issue here; I can't add cheats using the same address/different value multiple times whereas I can in Kega and Genesis Plus GX on the Wii.

**Comment by zeromus** [comment]
Calling cheats in bizhawk half-baked would be an exaggeration. This is a niche use case that stresses our one-tenth baked cheats system. Don't expect this to happen. The cheats system is always on the verge of falling apart as-is. 

This bug should be renamed "cheats should act sensibly"

**Comment by BooBerry** [comment]
I wouldn't say it's half-baked at all, actually. It's VERY functional.

I'd like to point out that I'm not trying to use all of the cheats at once (this wouldn't end well). I'm just trying to add them to the list so I can enable a set of four at a time without needing to modify the value for each code each time I want to change the effect.

The alternative would likely be enhancing the current cheat system to allow multiple choices for the values (for these special cases like this). Especially change it into a modifier-type of deal.

**Comment by zeromus** [comment]
I didn't say it's half baked either, I said it's one tenth baked.  I don't like your alternative for your niche use case. It isn't smart to spend a lot of energy porting codes into this one tenth baked system, and it isn't smart for us to help you do it. One day the cheat system will be fully baked, and that will be a better time to port codes to it.

**Comment by BooBerry** [comment]
A follow up to this, along with some observations;

1) For the time being I've worked around this issue by adding modifier values to the description of each cheat. This means I can just edit the cheat(s) and change the value to achieve whatever effect. It isn't the most ideal workaround, but it does indeed work!

2) Multi-code cheats don't seem to work at all when using GG/PAR cheats on the Genesis. *If* this is supported, a code example would be most appreciated.

3) An observation: Using the latest 64-bit 2.0 development build on Windows causes an instant crash when trying to add cheats (GG or PAR) or trying to load a cheat file with enabled cheats.

4) Another observation: The Genesis Plus GX core shipped with BizHawk seems out-of-dated compared to the Genesis Plus GX Git maintained by Eke-Eke. There's been countless emulation, accuracy and optimization improvements made that isn't part of BizHawk's GPGX's core (with hopefully more improvements eventually inbound to support the Overdrive 2 demo). Examples being [improved FIFO emulation accuracy](https://github.com/ekeeke/Genesis-Plus-GX/commit/38ffc317cb3c75ef1002cdfb13a86503b11027d6), [optimization to the 68k read/write handlers](https://github.com/ekeeke/Genesis-Plus-GX/commit/9810f9d34b5995d599886f4ad083df11db3d37ac), [YM2612 optimization](https://github.com/ekeeke/Genesis-Plus-GX/commit/4c04c8f719f0bca9fc4e856f5181bfc6e2bab1de), [multi-line cheats support with the + sign](https://github.com/ekeeke/Genesis-Plus-GX/commit/7093f1b7b2f968234aba23dbb9cb93b5427181c0), [rewritten PSG core](https://github.com/ekeeke/Genesis-Plus-GX/commit/61b10c57e244c64ce0b946bd16a6d5e3383a7fc3), etc.

See more here: https://github.com/ekeeke/Genesis-Plus-GX/commits/master

**Comment by zeromus** [comment]
2. Are multi-code PAR cheats including conditional logic and loops and such? If so, they won't work because bizhawk cheats are half baked. If not, then they're working just as well as any other cheats, which should be just fine in the case of GG, and probably just fine in case of basic PAR ram patches, and no special support for multi-line cheats is sensible, or required
3. Oops, we'll fix that
4. Let me give you a template to use in the future, to save time. "Upstream core X has fixed Y, which is important to me because of Z."
So you would have filled in the template: "Upstream core GPGX has fixed multi-line cheats, which is important to me because I'm trying to use cheats like that."
In this case, the work on cheats isn't relevant because we have no means of passing cheats to the core because our cheats system is ## _**# **HALF BAKED** # **_ ##

**Comment by BooBerry** [comment]
2. I haven't tested it, but something like 01075C:00FF+019F02:00FF would be an example of a multi-line cheat. Though, I will admit, I've seen multi-line cheats of 15+ lines in the last which is NOT possible on real hardware unless you stack Game Genies. I'll play with that one a little more, but it doesn't bother me too much.

4. Much appreciated for a template. Ignoring the GPGX multi-line cheats part, the other mentioned things are important, IMO. Especially when the stuff getting Overdrive 2 working lands (which is an amazing demo pushing the Genesis hardware to its limits). 👍

**Comment by zeromus** [comment]
The other things aren't important. "minor optimizations"? You're not helping your case by hyping it. When you don't use the template I provided, you hurt your case.

That cheat looks like basic ROM patches, actually. I dont know if those work on our GPGX due to our cheats system being half baked, but that there's two of them doesn't mean anything.

**Comment by hegyak** [comment]
PAR Cheats for Genesis, I could in theory add support for in terms of converting to a "Cheat" like the tool does for Game Genie cheats.  However, it has been quite a while since I have done anything BizHawk related.

**Comment by BooBerry** [comment]
You mean converting PAR codes to Game Genie? This would work fine for ROM codes, but very likely not RAM cheats without using a tracer to create new ROM code(s).

P.S. I just tried 2.0, and it still instantly crashes when trying to add GG/PAR cheats or trying to load a cheat file with said cheats enabled. I'll probably file another bug on this one.

**Comment by zeromus** [comment]
Guh. Ill be discussing the genesis memorydomain problems, don't need a bug.

**Comment by zeromus** [comment]
The good news: natt fixed the crash
The bad news: genesis game genie is (and many others may be) non-functional until further notice.
