### ISSUE TITLE
Bizhawk throws exception when switching between gba cores prior to loading a rom

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/BizHawk#865]
Toggling "GBA with mGBA" will prompt you to reboot the core even prior to loading a rom in Bizhawk 1.12.2. Upon rebooting the core, a message pops up with a NullReferenceException.

**Comment by alyosha-tas** [comment]
Actually, the exception pops up just by hitting Reboot core with no ROM loaded.

Fixed in Master
