### ISSUE TITLE
Upgrade GLideN64 to the latest version

### ISSUE THREAD

**Issue by thecoreyburton** [TASVideos/BizHawk#868]
Since the implementation of GLideN64, many improvements have been made to the emulation process (enough to warrant a second public release, even). I was wondering, would it be possible to update GLideN64 in Bizhawk to the latest version (both DLL and GUI for any additional features that may have been added since the last implementation)?

This falls more under the category of improvement than issue, but it does fix a number of graphical issues currently present in N64 games.

**Comment by vgturtle127** [comment]
Yeah, updagrade at least to GLideN64 public release 2, if not a newer commit. Although, newer commits do have some regressions, he has made some pretty nice improvements.

**Comment by zeromus** [comment]
work's done, test in waterbox2 branch
