### ISSUE TITLE
NES Load Error (headerless)

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#869]
Using Bizhawk 1.13.0 . When opening nes roms from No-Intro [headerless], this error occurs. The same, if you try open roms with drag & drop in Bizhawk.

Roms from GoodNES V3.23b works without this problem

![default](https://cloud.githubusercontent.com/assets/28905475/26765848/35a45c50-498d-11e7-9aeb-7f2ed59f3385.JPG)

**Comment by alyosha-tas** [comment]
As that error indicates, for a headerless ROM to load there needs to be an entry for it in the game database that tells the emulator how to load it. 
Most ROMs don't have entries so won't load.

Some day I'd like to have database entries for all the ROMs so we can do away with the messiness of headers, but it won't happen anytime soon.

That being said, if you have a specific ROM that you can't load and no version of it exists with a header, let me know and I'll add an entry into the database for it.

**Comment by RetroGameIntros** [comment]
Galaxian (Japan) (Rev A) not working, showing error "NES Load Error" (headered ROM from No-Intro) similar to headerless ROM's
![galaxian rev a](https://cloud.githubusercontent.com/assets/28905475/26786538/a71bddd6-4a0f-11e7-82d5-cd975fd80ace.JPG)

**Comment by alyosha-tas** [comment]
I fixed Galaxian and also check if a headerless ROM hash is in nescartDB before throwing an error.

I'll revisit this at some point but I think this is good for now.

**Comment by RetroGameIntros** [comment]
Pac-Man (Japan) (En) (Rev B) [headered] shows the same error
![default](https://cloud.githubusercontent.com/assets/28905475/26802172/377c2484-4a48-11e7-8f12-7e1066cf03cf.JPG)

**Comment by alyosha-tas** [comment]
Fixed in master.

By the way, you can get the always up to date dev build here:
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts
