### ISSUE TITLE
Increase speed further than 400%

### ISSUE THREAD

**Issue by Jaden-** [TASVideos/BizHawk#876]
At Config -> Speed/Skip I can set the speed to 400%. I would like to increase the speed as high as my computer can handle like some other emulators.
I'd like this because of evolutionary AI lua scripts gradually getting better at the game with machine learning takes too long. Please see MarI/O on youtube.
As of now, it requires about 10-14 hours of 400% speed for the AI to complete most levels. It would be so much better if it was possible to increase the speed to 1000%, 2000% or even better, the highest speed my computer can handle (uncapped framerate).
Please implement this feature to the emulator.

**Comment by vadosnaprimer** [comment]
Config - Speed/Skip - Unthrottled.
Config - Display - play around with Misc and Window.
Config - Sound - uncheck Enable Master Volume.
What speed do you get then?

**Comment by Jaden-** [comment]
Powerful stationary computer (GPU: GTX1080, CPU: 3930k):
Unthrottled checked on - 265 FPS average.
Unthrottled checked off with 400% speed = stable 240 FPS.
Unthrottled checked on & Display -> Misc -> Display nothing = 295 FPS average.

Weak laptop computer (GPU: Intel HD Graphics 3000, CPU: i7-2620M)
Unthrottled checked on - 200 FPS average.
Unthrottled checked on & Display -> Misc -> Display nothing = 240 FPS average.
Unthrottled checked off with 400% speed = 200 FPS average.

Changing the window size doesn't affect FPS.
Unchecking 'Sound Master Enable' increased the FPS by around 20.
Window-tab under display didn't seem to have any effect on FPS.

Technically you solved my question, unthrottled increased the FPS further than 400%.
However one would think the stationary would outperform the laptop by a bigger margin.
Stationary GPU is 38 times more powerful than laptop GPU (11 983 score vs. 313 score).
Stationary CPU is 3 times more powerful than laptop CPU (12 028 score vs. 3 827 score).
Source: http://www.videocardbenchmark.net

Any more tips? Is there a way to make EmuHawk use more computer resources?

**Comment by vadosnaprimer** [comment]
Does it calculate several cores as more powerful than one? Because bizhawk emulation doesn't seem to be utilizing more than one core. Anyway, I guess it already uses all the resources that it can use.

**Comment by zeromus** [comment]
With audio, rewind, and throttle off, Display Configuration is all that's going to help. The 400% has nothing to do with anything.

**Comment by tohnperfect** [comment]
Hi,

I am trying to train my bot as well. I wonder is there anyway I can config the replay speed via a command line because right now I run everything via command line and it run with a normal speed which is about 60 fps.

by the command line I mean [this](http://tasvideos.org/Bizhawk/CommandLine.html).

Thanks

**Comment by vaguiners** [comment]
5 years late, i face this problem. and no, 300 fps wont help. i need more.

**Comment by YoshiRulz** [comment]
`Config` > `Speed/Skip` > `Unthrottled`
