### ISSUE TITLE
Low fps in SGB

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#877]
Bizhawk 1.13.0 and dev build.

Today i opened some SGB (Super Game Boy) games, such as "Kirby's Dream Land (USA, Europe)" / "Aladdin (USA) (SGB Enhanced)" and "Bomber Man GB (Japan) (SGB Enhanced)", and tryed to play them. Low fps (~40-44) issue, sound glitches , but playable. Is there any fix for more fps?
![emuhawk_2017-06-12_11-16-20](https://user-images.githubusercontent.com/28905475/27024765-9a56f350-4f60-11e7-8d2e-d30093c1e360.png)

![emuhawk_2017-06-12_11-14-14](https://user-images.githubusercontent.com/28905475/27024684-4ae7a080-4f60-11e7-83e8-82f9f144d365.png)

**Comment by zeromus** [comment]
No. SGB is demanding. Turn off rewind or get a faster computer.

**Comment by RetroGameIntros** [comment]
Rewind are turned off, probably my computer can't handle it in 60 fps

**Comment by RetroGameIntros** [comment]
Tested again developer build - stable 55-56 fps, only sound glitches.

**Comment by zeromus** [comment]
Video of your computer going too slow. This problem is 100% resolved.
