### ISSUE TITLE
Lua Canvas with slider

### ISSUE THREAD

**Issue by Ludko444** [TASVideos/BizHawk#884]
I want write a lot of text and size of window is small +text is cutting. Example: If text is longer like width of window, a part of text will move line below. It can be something like Notepad.....

**Comment by zeromus** [comment]
1. make a larger canvas.
2. sliders are called scrollbars
3. you're asking for a scrollbar
4. then you're asking for word wrap, which would make it so you don't need a scrollbar
5. you're not getting a scrollbar
6. you can word wrap yourself in lua
7. if you can't, post a bug "wrapping for lua text drawing", and don't expect it to get worked on any time soon
