### ISSUE TITLE
[TAStudio] Greenzone and Saving needs improvement in 2.0

### ISSUE THREAD

**Issue by TASeditor** [TASVideos/BizHawk#889]
First a question: Is the memory capacity in Greenzone settings acurate?
I set it to 8 GB, but BizHawk still filled up to 16 GB (which is how much I have) and then it goes down to 8 GB, I paused emulation and after a while the process was down to 2 GB.

- Don't save Greenzone in backup files or when auto-saving.
- Don't save unchanged Greenzone data again. E.g: User loads a project that has 1000 Greenzone states, he invalidates 100 by drawing input at the 900th and then saves, now there shouldn't be any Greenzones saved, only the 100 invalidated are swept out of the tasproj file. Now he adds 50 Greenzone states by emulating and then saves, there should only be 50 Greenzone states saved (appended) to the tasproj file.
- The gap for platfroms with large savestate can be changed from 16 to 8.
- A last edited frame Greenzone. Good for platforms with analog sticks.

**Comment by vadosnaprimer** [comment]
It'd be faster if you make a pull request than if you wait for me.

**Comment by adelikat** [comment]
Can you break this up into separate issues?

Some of these I might try to tackle.

**Comment by vadosnaprimer** [comment]
> Don't save Greenzone in backup files or when auto-saving.

This is what Autosave as bk2 is for. Or you explicitly need branches in backups?

**Comment by TASeditor** [comment]
> This is what Autosave as bk2 is for. Or you explicitly need branches in backups?
What is the benefit of losing branches? 

> What does this mean?
When user edits input on frame 1253, make a temprary Greenzone on frame 1253

**Comment by adelikat** [comment]
Break this up into separate issues please
