### ISSUE TITLE
[Genplus-gx] CD Games won't load (regression)

### ISSUE THREAD

**Issue by lightgod87** [TASVideos/BizHawk#892]
Hi, guys.

The motive of this issue is to report a serious problem with the Genesis Plus GX core in BizHawk. In 1.13.0, games were loading properly, but with the new implementations in 2.0, the games won't load and BizHawk crashes. I've tested with a couple of games and the issue persists. The games being The Terminator and Heart of the Alien (both being Sega CD games).

Thanks in advance.

**Comment by nattthebear** [comment]
Fixed
