### ISSUE TITLE
[SMSHawk] Graphical Issues Since 1.11.9

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#893]
Several graphical issues have popped up in various SMS games since the "z80 accuracy improvements" implemented in 1.11.9 including:

### Lord of the Sword (UEB)
Vibrating blue mountains

![lord of the sword ue](https://user-images.githubusercontent.com/6367891/27643987-af3e7172-5c61-11e7-99b0-a15b5e8b4634.gif)

### Impossible Mission (EB)
Screen transition glitches

![impossible mission e broken](https://user-images.githubusercontent.com/6367891/27644209-1038c090-5c62-11e7-8ce8-3f54b49fea3f.gif)
![impossible mission e room](https://user-images.githubusercontent.com/6367891/27644220-1484ab8c-5c62-11e7-8893-d72160f5794a.gif)

### Castle of Illusion & Land of Illusion
Screen displacement

![land of illusion starring mickey mouse e](https://user-images.githubusercontent.com/6367891/27644468-cf1a91b4-5c62-11e7-97d4-ea022f6154d3.gif)

I decided to file these in one issue since they all popped up in the same version

**Comment by alyosha-tas** [comment]
Uh oh, that doesn't look good. I guess I somehow managed to never play / test any of the games that had bugs in them , that's an unfortunate coincidence.

I'll take a look at this.

**Comment by alyosha-tas** [comment]
All of these resulted from the same edge case, namely, interrupts were trying to be re-enabled after an interrupt had just occured. This resulted in jumping to the interrupt vector multiple times and corrupting execution. Fixed in master

**Comment by Isotarge** [comment]
Thanks for the quick response 👍
