### ISSUE TITLE
Bizhawk 2.0.XX Avi writter problem (Seems to fe fixed)

### ISSUE THREAD

**Issue by phoenix1291** [TASVideos/BizHawk#894]
EDIT: I have uninstalled both JK Lossless 32 and 64 bits dll files and Playclaw, and it seems to work now.

Bizhawk 2.0.XX versions, 64 bits. 
I have a problem with the Avi writter. I have uninstalled and reinstalled JK Lossless Video Codec 64 bits version.
But the problem still here.
So I can't use Avi writter, even I don't use JK Lossless 

File -> AVI/WAV -> Config and Record AVI/WAV -> Choose AVI Writter -> Bizhawk crash. 

`Nom de l’application défaillante EmuHawk.exe, version : 2.0.0.12387, horodatage : 0x59530fa5
Nom du module défaillant : JK-Lossless-Video-Codec.dll, version : 0.0.0.0, horodatage : 0x55b5d8c0
Code d’exception : 0xc000041d
Décalage d’erreur : 0x0000000000002b43
ID du processus défaillant : 0x3490
Heure de début de l’application défaillante : 0x01d2f00f97d9b005
Chemin d’accès de l’application défaillante : C:\Users\Phoenix\Downloads\BizHawk-Developer_3d443b3e\EmuHawk.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\JK-Lossless-Video-Codec.dll
ID de rapport : 4f65f82e-2b53-49f4-a612-94300a85fa46
Nom complet du package défaillant :
ID de l’application relative au package défaillant : `

No problem with FFmpeg writter nor Bizhawk 1.13.X versions. 

 
I have a problem with Saturn too, Avi dump are 1fps... 
Bizhawk 2.0.XX versions, 64 bits.

Two files are created on Sega Saturn video dump, one file, 0 second 
`Width                       : 320 pixels 
Height                      : 240 pixels 
Display aspect ratio        : 4:3 
Frame rate mode             : Constant 
Frame rate                  : 59.940 (59940/1000) FPS`

And another one for the rest of the video 
`Width                       : 660 pixels 
Height                      : 240 pixels 
Display aspect ratio        : 2.750 
Frame rate mode             : Constant 
Frame rate                  : 1.000 FPS`

**Comment by zeromus** [comment]
So if it's fixed, why don't you close it?

**Comment by phoenix1291** [comment]
And **how** can I close it?

**Comment by zeromus** [comment]
you'll be proud of yourself when you figure it out. keep trying.

**Comment by vadosnaprimer** [comment]
That's how.

**Comment by zeromus** [comment]
great, now every time he posts a bug and then decides it wasnt really a bug, you're going to have to ride to the rescue to fix it because he never figures it out.
