### ISSUE TITLE
Cheat codes in 2.0.1 and 1.13.1 will not load and delete

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#896]
Cheat codes in 2.0.1 and 1.13.1 will say they have loaded but when you go to see what codes you have in your list the list is empty and the codes you had on a older version on BizHawk is deleted. Just load a game that you know you have code for then go see the cheats you will see it's empty and the path you made to find the cheats the game you loaded that cheat will be deleted.

**Comment by zeromus** [comment]
on may 18 in 0d4313af918c66a282fa8ffe64e68cc9fe6be783 refactorer-in-chief changed formatting/capitalization of of Cheats.cs's COMPARISONTYPE enum which makes all existing cheats invalid

**Comment by Cibomatto2002** [comment]
OK Thanks.

**Comment by Cibomatto2002** [comment]
Is there a way that I can convert all of my codes to the new format? I have over 500 codes.

**Comment by zeromus** [comment]
yes. study the new format and the old format in a text editor and it should be obvious what you need to do.

If you dont want to waste your time, wait for adelikat to address it. He might revert the cheats to the old format.

**Comment by Cibomatto2002** [comment]
Thanks I will Wait. :)

**Comment by adelikat** [comment]
I won't be reverting sorry.  These files are just text files. Should be easy to tinker if you want

**Comment by Cibomatto2002** [comment]
ok. Why was it changed?

**Comment by zeromus** [comment]
to make the code less cryptic

**Comment by Cibomatto2002** [comment]
ok thank you.
