### ISSUE TITLE
[SMSHawk] "Software Error" Loading Wonder Boy III with V1.3 BIOS Enabled

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#898]
![wonder boy iii - the dragon s trap ue 2017-07-01 21 54 14](https://user-images.githubusercontent.com/6367891/27762028-fb7638ca-5ea7-11e7-8e04-8677591773ab.png)

BIOS SHA1: C315672807D8DDB8D91443729405C766DD95CAE7
ROM SHA1: 012AEF13338646DD6D0064BAED2567C210315D44

**Comment by alyosha-tas** [comment]
This is a strange bug. The ROM is failing to load on a checksum failure.
The game is a 256K ROM, and other games of size 256K load just fine. 
This same ROM and BIOS also load just fine in other emulators such as TwoMBit, and I didn't see any hacks in the source there specific to this game.

On a hunch though, I changed two unused bytes in the ROM header from $20 to $FF (both are common default values for these two bytes.) After this, the ROM loaded just fine. This indicates that the check sum routine is including the header in the checksum (though SMSpower states that this should not occur, stopping at $7FEF.) It seems to stop there for other games just fine.

TwoMBit loads the ROM regardless of what are in those 2 bytes, so it's clearly not including them.

So, this doesn't make a whole lot of sense, I'll have to dig around a bit.

**Comment by alyosha-tas** [comment]
That was weird, the game DB had some patch bytes associated with it, which prevented the checksum from being correct. I have no idea what there purpose was, but, removing them fixes the loading and the game seems to play just fine without them.

**Comment by Isotarge** [comment]
Thanks again :)
