### ISSUE TITLE
TAStudio Feature request: Visual cue for seperating P1 from P2

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#899]
So, I see this on TAStudio:
![bug1](https://user-images.githubusercontent.com/15385566/27839919-f996c3b8-60c2-11e7-9c09-fbc6dc0f0c6a.PNG)

It would be much better for me to have a visual cue that seperate P1 from P2. Maybe a thicker and darker line?

Concept screen:

![bug2](https://user-images.githubusercontent.com/15385566/27839932-1302cf5e-60c3-11e7-9b99-5935109c31a0.PNG)

**Comment by adelikat** [comment]
If you have any greenzone at all you have color differences between the players, is that not good enough?

**Comment by Niamek** [comment]
I'll be honest, I didn't even notice that difference at first.

When TASing existing input or frames, that won't be an issue. For TASing new frames, a workaround would be to simply record a bunch of empty frames.

**Comment by adelikat** [comment]
I think your workaround is what tastudio/taseditor users typically do as part of their workflow.

**Comment by adelikat** [comment]
Since that work around is good enough and the idea of a column separator is actually more complicated than it seems, I'm going to go ahead and close this issue.
