### ISSUE TITLE
[2.0.1] Video dumping died + Cant run N64 games

### ISSUE THREAD

**Issue by dany777** [TASVideos/BizHawk#903]
I tried to dump my TAS i made from American Gladiators for NES using Lagarith Lossless Codec, but everytime i try to dump it, it fails and it says this:

---------------------------

---------------------------
Video dumping died:

System.InvalidOperationException: Operación no válida dado el estado actual del objeto.

   en BizHawk.Client.Common.BitmapBufferVideoProvider.get_VsyncNumerator()

   en BizHawk.Client.EmuHawk.AviWriter.VideoCopy..ctor(IVideoProvider c)

   en BizHawk.Client.EmuHawk.AviWriter.AddFrame(IVideoProvider source)

   en BizHawk.Client.EmuHawk.VideoStretcher.DumpAV(IVideoProvider v, ISoundProvider syncSoundProvider, Int16[]& samples, Int32& samplesprovided)

   en BizHawk.Client.EmuHawk.MainForm.AvFrameAdvance()
---------------------------
Aceptar   
---------------------------

But also, no matter wich N64 game i try to run, it always freezes BizHawk

And dont tell me to install the 2.0 prereq installer because i already did that

**Comment by zeromus** [comment]
1. Wait for next release or use buildbot build
2. Upgrade or downgrade your video drivers or change your n64 plugins. "no matter which" is for developers to decide, not you. List which ones you tried. 
3. Install the 2.0 prereq installer.

**Comment by dany777** [comment]
As i said: "Dont tell me to install the 2.0 prereq installer because i already did that"

Also, really dumb of me, im really sorry; Turns out, i had to clear my config file

But still im having the same error when i want to dump a TAS as AVI, it fails with that error, but if i disable "Capture OSD" it can dump the AVI just fine, but i dont want that, i want my TAS to be shown with inputs

**Comment by zeromus** [comment]
As i said: "Wait for next release or use buildbot build"
