### ISSUE TITLE
emulator keeps deleting itself after a few hours

### ISSUE THREAD

**Issue by FlashlightET** [TASVideos/BizHawk#907]
every time I re-download the emulator it deletes emuhawk.exe after a few hours and I have to download it again, it doesn't do it on my main pc (I'm on another) so I need help

**Comment by thecoreyburton** [comment]
What version are you using?

In terms of basic troubleshooting, there's a big red flag on the fact it's a problem isolated to one computer. It doesn't completely rule out fault in the program itself, but it does pose the question of the difference between what programs are running on each machine - especially with something that isn't a simple crash but rather a file being deleted.

It sounds like there could be external program causing trouble on the problem PC, such as an anti-virus program that is quarantining or removing the software. This could be for any number of reasons - primarily, if it's a false positive (the anti-virus software thinks it's a threat when it isn't), or if malicious software on your machine has altered the executable in some way.

In the meantime, if you have any such software (this includes programs that come bundled with your operating system), check the logs and history and make sure that's not the cause and then hopefully someone else has some more insight into this than I do.

Best of luck solving your problem!

**Comment by zeromus** [comment]
It rules out a fault in the program itself.
It's your kid brother or antivirus.
