### ISSUE TITLE
BSNES: The Lost Vikings 2 crash

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#912]
After getting new powers on level 22, I choose Baleog and press Y+Down. Supposedly, he will pull himself up in the air (it's said to be one of the new powers). Instead, the game crashes.

[Lost Vikings 2 (USA).Compatibility.QuickSave3.zip](https://github.com/TASVideos/BizHawk/files/1138268/Lost.Vikings.2.USA.Compatibility.QuickSave3.zip)

**Comment by zeromus** [comment]
Check it in several bsnes versions including 0.87 (which we're derived from). It's probably broken in 0.87. Is it ever fixed? Does it require the accuracy profile?
Sorry it's level 22 and it may take you forever to confirm this.
There's nothing we can do about it anyway except maybe one day update the bsnes core.

**Comment by nattthebear** [comment]
You do mean that the game crashes and not the emulator crashes, right?  If it's the latter, post a crashlog and we can probably fix it.  If it's the former, there's not much of a chance

**Comment by zeromus** [comment]
I checked it, the game crashes with corrupted BG

**Comment by Reinc01** [comment]
It doesn't require accuracy profile. On Snes9x core, not only the game crashes, but the emulator freezes as well.
[Lost Vikings 2 (USA).Snes9x.QuickSave4.zip](https://github.com/TASVideos/BizHawk/files/1140719/Lost.Vikings.2.USA.Snes9x.QuickSave4.zip)

I tried it in BSNES 0.86, 0.87 and higan v103. The game crashes there too.

**Comment by zeromus** [comment]
OK, case closed. Report it to upstream. We'll probably never fix it.

**Comment by Max833** [comment]
@zeromus 
@Reinc01 

Real hardware issue: https://github.com/byuu/bsnes/issues/216
