### ISSUE TITLE
[TAStudio] Don't save Greenzone in backup files or when auto-saving

### ISSUE THREAD

**Issue by TASeditor** [TASVideos/BizHawk#913]

**Comment by zeromus** [comment]
Greenzone is SUPPOSED to be saved. If you don't like it, then what you want is an option.

**Comment by TASeditor** [comment]
I want it for manual saving (in menu or Ctrl+S). But not for autosaving, it interrupts the workflow to much. And backups don't really need greenzone imo.

**Comment by zeromus** [comment]
Backups should not save greenzone. That shouldn't be an option. It's a no-brainer.
Autosave should save greenzone, IMO. If you don't like it, it's a lower priority task to make it an option.

**Comment by adelikat** [comment]
When autosaves saves greenzone it is VERY slow, and happens in the middle of what you are doing.  It is a real drag for user experience.

There is an option though, to auto-save to .bk2, which is one of the first things I pick if I use tastudio just to avoid the ridorkulous save times happening every minute.

**Comment by TASeditor** [comment]
.bk2 don't have branches.
