### ISSUE TITLE
[TAStudio] Don't save unchanged Greenzone data again

### ISSUE THREAD

**Issue by TASeditor** [TASVideos/BizHawk#914]
E.g: User loads a project that has 1000 Greenzone states, he invalidates 100 by drawing input at the 900th and then saves, now there shouldn't be any Greenzones saved, only the 100 invalidated are swept out of the tasproj file. Now he adds 50 Greenzone states by emulating and then saves, there should only be 50 Greenzone states saved (appended) to the tasproj file.

**Comment by zeromus** [comment]
That isn't how files work. The data is all rewritten. This will automatically be solved in case anyone ever changes a tasproj to be a database. There's no use tracking this issue.
