### ISSUE TITLE
[TAStudio] The gap for platfroms with large savestate can be changed from 16 to 8

### ISSUE THREAD

**Issue by TASeditor** [TASVideos/BizHawk#915]
Check how much memory the user provides for greenzone

**Comment by zeromus** [comment]
So change it in the settings yourself

**Comment by vadosnaprimer** [comment]
Gap between states that are saved to ram as emulation runs can't be changed by the user.

**Comment by zeromus** [comment]
then this bug should be "let user choose gap"
Before closing this bug I checked and confirmed the user can choose the gap. In powers of 2 for some strange reason.
It sounded like this bug was disagreeing with our choice of _defaults_

**Comment by vadosnaprimer** [comment]
No, the option that is there is the gap for saving a tasproject. This issue is about the gap between current ram savestates.

**Comment by zeromus** [comment]
OK then this issue is still an opinion about the defaults for logic which is insanely complex in principle. And the bug should still be "let user adjust that logic"

What even motivated this bug? can be changed from 16 to 8? On what basis? @TASeditor upgraded his system ram? this bug is stupid.

**Comment by TASeditor** [comment]
No, just using x64 builds. I don't really care wheter the defaults are changed or an option in savestate history settings is provided.

**Comment by adelikat** [comment]
I think making it configurable is a nice tastudio upgrade

**Comment by vadosnaprimer** [comment]
Yeah I agree. It felt like a meaningful option for quite a while, even before this issue. I dunno if implementing it is gonna require new TSM, but I'm gonna reopen it now.
