### ISSUE TITLE
Developer Builds are immediately crashing

### ISSUE THREAD

**Issue by Trivial-Man** [TASVideos/BizHawk#919]
Starting after [this](https://github.com/TASVideos/BizHawk/commit/af7a2d8b4abca4db921c8f170340cf85430986e5) commit by @zeromus the developer builds on AppVeyor crash immediately from a System.StackOverflowException.

Here's Window's details, though I don't know how helpful they are.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	EmuHawk.exe
  Application Version:	2.0.0.12530
  Application Timestamp:	59685ed1
  Fault Module Name:	clr.dll
  Fault Module Version:	4.7.2053.0
  Fault Module Timestamp:	58fa6d2a
  Exception Code:	c00000fd
  Exception Offset:	0000000000179196
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2986
  Additional Information 2:	29860fa510de14d5dd00ca577a1ef6e5
  Additional Information 3:	8e18
  Additional Information 4:	8e18d60497276692e6e7da37f3a9fab4

**Comment by vadosnaprimer** [comment]
Quoting myself on irc.

> downloaded artifact of the latest build crashes on launch. build compiled by myself works
> zermous: are you sure lua actually switches to luainterface when that one is picked in the menu? I don't notice any effect of it being changed from nlua
> even after core reboot
> if I set it to luainterface and relaunch the emu, then try to open lua console, I get System.BadImageFormatException
> https://pastebin.com/7w70N17f
> and if I resume I get https://pastebin.com/hqq8ehYS

**Comment by zeromus** [comment]
Yes, I'm sure it switches. You must restart the whole emulator. Adelikat didnt write that in a message or in the customization dialog

**Comment by vadosnaprimer** [comment]
As I said I get exceptions if I restart the emu after that.

Also does the artifact build work for you?

**Comment by zeromus** [comment]
yes, after ae4fff522ddb97e5778fb47bcb42286b7afca265

**Comment by Trivial-Man** [comment]
Developer builds work for me now. I'll close if @vadosnaprimer gets them to work as well.

**Comment by vadosnaprimer** [comment]
It works now.
