### ISSUE TITLE
"Cycle track" option for Sega CD / Mega CD

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#922]
I think this is need to be implemented in Bizhawk, option to cycle current track (only for Sega CD / Mega CD games). To example, in "Marko's Magic Football" on first level, after track (theme) ends - there's a pause 5-10 seconds, then playing random track, and then only it plays level's track (theme)

https://youtu.be/X2Qf7fEcZb8 - watch from 7:00 to 7:20

**Comment by zeromus** [comment]
Classic sign of a bad disc image.
