### ISSUE TITLE
mGBA audio bug with BizHawk 2.0.1 and 2.1.0

### ISSUE THREAD

**Issue by GenericMadScientist** [TASVideos/BizHawk#926]
When moving on from dialogue boxes in Yu-Gi-Oh! Duel Monsters 7 Kettou Toshi Densetsu (Japan) with mGBA in BizHawk 2.0.1 and 2.1.0, there is a small crackle as shown in the video [here](https://www.youtube.com/watch?v=LlXYMyx9sXs&t=20s).

I do not get the problem if I use VBA-Next, or mGBA with BizHawk 1.12.0 or 1.13.1. I also do not get the problem if I download and use mGBA 0.6.0 directly though.

**Comment by nattthebear** [comment]
I've ported mGBA 0.6.0 into Bizhawk.  If you still have the problem after trying on our next release or dev build, feel free to reopen this.
