### ISSUE TITLE
PCE Hawk (CD-ROM troubleshooting) - Might and Magic

### ISSUE THREAD

**Issue by Morricane** [TASVideos/BizHawk#928]
Hello!

For reasons I had to try out any PCE-emu that is not Ootake (which basically means this one).
Some CD-ROM games do work just fine, but others do not. The game in question would be Might & Magic (JP). Tried with 2 different rips from the internet as well as my personal rip from original disc, result is always the same error message:
![i am error](https://user-images.githubusercontent.com/8513960/28466489-917a3c80-6e67-11e7-8aaa-cca543593077.png)

I can't make sense of this message, unfortunately.

The cue-file in question, incidentally contains (in this case personal rip) this:

FILE "magic.bin" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
  TRACK 02 MODE1/2352
    PREGAP 00:03:00
    INDEX 01 00:44:65
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 04:25:58
  TRACK 04 AUDIO
    INDEX 01 05:30:22
  TRACK 05 AUDIO
    INDEX 01 06:58:19
  TRACK 06 AUDIO
    INDEX 01 11:08:55
  TRACK 07 AUDIO
    INDEX 01 15:04:66
  TRACK 08 AUDIO
    INDEX 01 18:38:45
  TRACK 09 AUDIO
    INDEX 01 19:43:21
  TRACK 10 AUDIO
    INDEX 01 23:08:41
  TRACK 11 MODE1/2352
    PREGAP 00:03:00
    INDEX 01 23:12:62

If anyone knows how to solve this, it would be appreciated :)
I'm more of an end user than a code monkey after all.

**Comment by vgturtle127** [comment]
@Morricane I could be wrong, but this may be a bad dump, or an incorrect CUE sheet.

You may want to quickly see if the CUE sheet here fixes the issue:

http://redump.org/disc/2594/

**Comment by alyosha-tas** [comment]
Also, I would recommend you try Mednafen. The Mednafen core is more mature then ours, and generally less buggy.

**Comment by zeromus** [comment]
You didnt tell me which bizhawk version you're using so I don't know this for sure, but 
1. Personally ripped discs are always broken
2. This one seems broken by happening to have a sector marked as audio in the midst of a data track. We're trying to read a sector from that track as data, to check if it's a PCFX disc, but it isn't, and thus the exception. I'll make a note to handle this somehow, but it's such an abstruse case, it won't be a priority.
