### ISSUE TITLE
32X - Unable to change a game's region

### ISSUE THREAD

**Issue by synnae** [TASVideos/BizHawk#929]
Title says all. 32X core's region is set to "Autodetect" by default and it's impossible to change it.

This should be an essential feature, like on the Genesis and SMS cores.

**Comment by nattthebear** [comment]
Why would this be an essential feature?  Does the autodetect fail on any known good dump?

**Comment by hegyak** [comment]
I think it's a language choice issue.  Like some ROMs have both English and Japanese text in them.  The user wants to choose to play the game in their native language.  This is done by telling the Console, it's in that region.

**Comment by nattthebear** [comment]
I see, since some games support multiple regions at the same time.
