### ISSUE TITLE
Game Genie codes not working on Genplus-gx core

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#934]
BizHawk v2.1.1

Streets of Rage 2 (USA) SHA-1 8B656EEC9692D88BBBB84787142AA732B44CE0BE

Strider (USA, Europe) SHA-1 26FE42D13A01C8789BBAD722EBAC05B8A829EB37

Codes came from here.

http://www.gamegenie.com/cheats/gamegenie/genesis/streets_of_rage_2.html

http://www.gamegenie.com/cheats/gamegenie/genesis/strider.html

**Comment by zeromus** [comment]
Game genie codes are catastrophically broken by waterbox. Use 32bit version of emulator until cheat system is entirely reworked.
