### ISSUE TITLE
Address issues with codebase having other licensed libraries

### ISSUE THREAD

**Issue by superusercode** [TASVideos/BizHawk#936]
[Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) is the best way to fix this issue. Git submodules are essentially references to other repos and are cloned simultaneously with the main repository. Since it is separated, this would make the codebase MIT as the license currently suggests. 

Many other emulators, like [RPCS3](https://github.com/RPCS3/rpcs3) already use submodules in order to fix licensing issues. This is a solution used by many and I hope we do as well so this issue can be fixed as soon as possible,

CC: @zeromus

**Comment by zeromus** [comment]
Nope.
