### ISSUE TITLE
SEGA SATURN - Mortal Kombat Trilogy (US) Crashes

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#939]
Hello there! On the lastest version of Bizhawk, I recently tested my small bunch of Sega Saturn game I own and ripped them in ISO for testing. Mortal Kombat Trilogy is the only game that do not launch and immediatly crashes Bizhawk. I tried other ISO rip of the US version and I get the same result. I remember that on SSF sometimes ago the game was playable but glitched thought. The other Mortal Kombat games (UMK3 and MK2) work well.

<img width="349" alt="mk trilogy" src="https://user-images.githubusercontent.com/24578279/28626761-f33535ae-71ed-11e7-85b0-d2a8df277644.PNG">

**Comment by hegyak** [comment]
The error message tells you what's wrong.  The CUE File doesn't have a cleanly entered File name(s).

**Comment by Glitcholog** [comment]
Without you telling me the error explaination, I would have never guessed it.

the following three file name of the rip I tried were
Mortal Kombat Trilogy (U).cue
mktsaturn.cue
MKT (U).cue

All three do not work, is that what you mean by "cleany entered File names(s)"? I had many game with strange space or special character and I never saw that error before

**Comment by hegyak** [comment]
The issue is not the file's name, but the path itself.  Your error message says, "Can't find the path "C:\SATURN"  That's where the issue lies.  If the Cue file references a path that doesn't exist, it will fail to load the referenced files.

**Comment by Glitcholog** [comment]
I understand more now, thank you.
