### ISSUE TITLE
read("*number") not working in 2.1.1 (always returning 0)

### ISSUE THREAD

**Issue by sousben** [TASVideos/BizHawk#940]
I came across this issue while trying to load a previously saved state with the Mar I/O script.
Couldn't find anyone with the same issue, so I guessed it must have appeared recently.

Also, this part in the release notes of version 2.1.1 could mean someone broke something while fixing something else:

> fix io.open with mode "a"

**Comment by zeromus** [comment]
Nobody broke something while fixing that. Someone broke something while switching out the 100% of the lua implementation with another. Change the lua core in config > customize, or give me a malfunctioning test case I can a/b check between the two lua cores

**Comment by adelikat** [comment]
if it was a savestate from a 1.x release then that's the problem.  Previous SNES savestates are no longer valid in 2.x

**Comment by sousben** [comment]
@adelikat I was only trying to read a text file, not loading a savestate
@zeromus you can try the following code:
```
	console.clear()
	local fileWrite = io.open("testFile.txt", "w")
	fileWrite:write("Yellow world\n")
	fileWrite:write(18 .. "\n")
	fileWrite:write(36 .. "\n")
	fileWrite:close()
			
	local fileRead = io.open("testFile.txt", "r")
	firstLine = fileRead:read("*l")
	firstNum = fileRead:read("*n")
	fileRead:read()
	secondNum = fileRead:read("*n")
	
	console.writeline("1: " .. firstLine .. " 2. " .. firstNum .. " 3. " .. secondNum)
	fileRead:close()
```
and this is what it prints in the console:
> 1: Yellow world 2. 0 3. 0

**Comment by zeromus** [comment]
FYI, kopilua's IO library is NOT READY FOR PRODUCTION USE.
We need to pressure people to validate the old luainterface hard so we can ditch kopilua

**Comment by vadosnaprimer** [comment]
> We need to pressure people to validate the old luainterface hard so we can ditch kopilua

It's needed for the future linux port.

**Comment by zeromus** [comment]
Could use keralua for that instead. I didnt use keralua originally because it had the same problem luainterface+lua did but if I've fixed that, then I know how to fix keralua. With keralua you then build a native lua dll. Basically keralua replaces the managed c++ with more normal pinvoke, I think
