### ISSUE TITLE
Missing 2 PSX Firmwares in the Firmware Info list

### ISSUE THREAD

**Issue by LodanZark** [TASVideos/BizHawk#941]
Missing 2 PSX Firmwares in the Firmware Info list:

psone-44e.bin
SCPH-102 (Version 4.4 03/24/00 E)
crc:0bad7ea9
md5:b10f5e0e3d9eb60e5159690680b1e774
sha1:beb0ac693c0dc26daf5665b3314db81480fa5c7c

and

ps-22d.bin
DTL-H1100 (Version 2.2 03/06/96 D)
crc:decb22f5
md5:ca5cfc321f916756e3f0effbfaeba13b
sha1:73107d468fc7cb1d2c5b18b269715dd889ecef06

**Comment by zeromus** [comment]
Don't know what a D bios is. This is the only one I've ever seen. So I don't know whether to add it to J and/or U and/or E. Do YOU know what it is?

**Comment by LodanZark** [comment]
ps-22d.bin its a NTSC-J BIOS - Source: http://emulation.gametechwiki.com/index.php/File_Hashes

there are some bios that I did forgot to point it out:
ps-22j(v).bin	81328b966e6dcf7ea1e32e55e1c104bb	NTSC-J	SCPH-5903 (the psx that had CD Video support)

DTLH2000.BIN	2118230527a9f51bd9216e32fa912842	(Region Free maybe?) PlayStation 1 Dev board

ps1_rom.bin	81bbe60ba7a3d1cea1d48c14cbcc647b	(Region Free maybe?)  found on PlayStation 3.

PS: SCPH18000.BIN =ps2-50j.bin

**Comment by hegyak** [comment]
We could add these Checksums for the these Firmware files, but, the question is, will BizHawk and/or the core itself handle the Firmware that is being loaded.  Like does the PSX core handle the Developer PS1 BIOS properly?  Or at all?

**Comment by zeromus** [comment]
they're added as unacceptable variants if they won't work.

**Comment by zeromus** [comment]
I can't add the others unless I have the files, because the pattern I use for defining them, and the relative uselessness of them in the first place. For instance I can't read the version string out and I dont even have support for MD5 hashes right now.

**Comment by LodanZark** [comment]
I have those files, is there any way to sent them to you without break any rules?

**Comment by zeromus** [comment]
Nope. We should discuss this bug any more on IRC
