### ISSUE TITLE
Bizhawk crashing when changing window size

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#942]
Don't know why, writing here how it's happened:

1) Opened rom "Toy Story" (.smc , SNES-version)
2) After rom opened, going to View -> Window size. First i'm selected 4x, then 3x. Pressing "Pause" key. Then rebooting core. And its write Exception:

"System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в BizHawk.Client.EmuHawk.DisplayManager.CalculateClientSize(IVideoProvider videoProvider, Int32 zoom)
   в BizHawk.Client.EmuHawk.MainForm.FrameBufferResized()
   в BizHawk.Client.EmuHawk.MainForm.Render()
   в BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   в BizHawk.Client.EmuHawk.Program.SubMain(String[] args)"

Crashing in both **Developer build** and **Bizhawk 2.1.1**, doesn't crashing when doing "Soft Reset" or "Hard Reset" from the **Emulation** tab. Crashing also only if using Snes9x core.

**Comment by zeromus** [comment]
fixed by 94e2fe2a100e2a9aeb21add9cff7df4b57e710e6
