### ISSUE TITLE
SNES9x needs a System Bus memory domain

### ISSUE THREAD

**Issue by Trivial-Man** [TASVideos/BizHawk#943]
...or at least some sort of memory domain that allows access to the ROM itself and not just the RAM.

**Comment by zeromus** [comment]
Do you think you're going to edit the ROM? That won't work right now. The ROM is read only.

**Comment by Trivial-Man** [comment]
Not for editing, no. This would allow me to read values with the RAM search tool and lua readbyte and similar values. If File on Disk is a valid option for those I wasn't aware.

Specifically, the reason I want this is so I can have a script that (among other things) looks up the initial carrying capacity for bombs and arrows in randomized LttP ROMs. It's at location 0x308034 using the system bus with the bsnes core, or 0x180034 using the cartROM.

**Comment by Trivial-Man** [comment]
Essentially because the script I'm writing is for casual gaming. It's just a visual tracker for certain items/events. Helpful for a novice (like myself) or a streamer's audience but useless for an advanced speedrunner or TASer.

For the record I do use bsnes, but this one instance of reading values from the ROM is the only part of the code that behaves differently between the 2 cores. And since a system bus or a similar domain is present in at least a good number of the emulation cores I tested, I thought this was more of a standard feature that just hadn't been implemented yet and wanted to make the devs aware that it was wanted.
