### ISSUE TITLE
Sound issue in Saturn core!

### ISSUE THREAD

**Issue by ScHlAuChii** [TASVideos/BizHawk#944]
There is an sound issue in the Gunbird game for Saturn:
https://my.mixtape.moe/oqnqpv.mp4 (error is around 0:55)

The issue does not occur in the latest Mednafen build!

**Comment by nattthebear** [comment]
Can you reproduce this 100% of the time?

**Comment by YoshiRulz** [comment]
Could not reproduce on 2.3.1, not that anything was provided beyond "play the game".

**Comment by YoshiRulz** [comment]
@ScHlAuChii ping

If you're still having issues with Saturnus, comment with more detail or join IRC.
