### ISSUE TITLE
[bk2] Recreating archive (by command line) after update of the input log

### ISSUE THREAD

**Issue by FullMoonIssue** [TASVideos/BizHawk#945]
Hi,

With 7zip, when I decompress my .bk2 archive (`7z x game.bk2`) and then update (or not) the input log file, I recreate the archive this way :

`7za a game.bk2 Comments.txt Header.txt Input\ Log.txt Subtitles.txt SyncSettings.json`

After that, when I browse then select my new bk2 file into "Play Movie", BizHawk stops and quit.

Do I miss something ?

Config :
- BizHawk 1.13.1 (macOS)
- Mac Sierra 10.12.4

PS : I don't have any log to provide

Regards.

**Comment by nattthebear** [comment]
bk2 files are zip files, not 7z files.  The 7zip archiver can process them, but when archiving don't you need to specify something to have it write zip and not 7z?

**Comment by alyosha-tas** [comment]
use the switch -tzip and it should work

**Comment by FullMoonIssue** [comment]
Nice !

It was indeed the omitted argument.
Here is the new command :

`7za a -tzip game.bk2 Comments.txt Header.txt Input\ Log.txt Subtitles.txt SyncSettings.json`

Thank you.

Regards.
