### ISSUE TITLE
Quake 64 Issues and Glide64Mk2 instant crash

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#946]
Quake 64 has an minor but distracting issues when playing. When you are close to a door or another sector, you can see every enemy that are behind it, its certainly not something expected (at least on the Real N64) but im not sure if other emulator emulate the game properly

<img width="570" alt="222222" src="https://user-images.githubusercontent.com/24578279/28730819-7b0369ee-739f-11e7-905c-d1e3a0260313.PNG">
<img width="479" alt="111111" src="https://user-images.githubusercontent.com/24578279/28730818-7b01b61c-739f-11e7-9b68-bf07446f73ce.PNG">

Also, when I attempt to choose Glide64MK2 and I reboot, bizhawk crashes with an error saying that it failed to load it. But the problem is that Bizhawk does retain the option, so it is impossible to play N64 games unless  you download another copy of the emulator or  you mess with the config file. Although not much important, if you make it so there is no controller 1 "plugged", will cause the bizhawk to crash and brick it the same way as glide for n64 games

**Comment by zeromus** [comment]
1. "not sure if other emulator" Do your homework. We won't do it for you
2. Glide64MK2  - Can't repro. "failed to load it" -- not good enough.
3. fixed

**Comment by Glitcholog** [comment]
1. You don't have to be so rude . im just trying to contribute to the emulator with bugs In the recording I do.

2. Power up a game, then go to the plugin menus and change GlideN64 for GlideMK2
<img width="353" alt="issueman" src="https://user-images.githubusercontent.com/24578279/28748551-933f793c-7488-11e7-8c0f-d56cf81806ce.PNG">

3. What is fixed , Quake 64 and GlideMK2 or just one of them? If its only one of the two, this issue should not be closed.

Thanks in advance

**Comment by Glitcholog** [comment]
"Do your homework. We won't do it for you" Although I understand the lack of precision from my side, im pretty sure this could be rephrased to be less rude. Im just trying to help while recording the games .

Thanks for the fix thought, never thought the game would be finally fully playable.
