### ISSUE TITLE
Bizhawk Exception on drag and drog

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#947]
Due to this impossible to open any roms, try open any of your using drag and drog. Or throught "File - Open Rom" (Tested on .bin / .nes / .gbc / .smc roms, **developer build)**

![bizhawk drag drop](https://user-images.githubusercontent.com/28905475/28740392-d16b3dbc-740c-11e7-902c-9bac9d59d2e9.JPG)
![bizhawk drag drop 2](https://user-images.githubusercontent.com/28905475/28740398-e38fb810-740c-11e7-83a9-9f16620a9f9f.JPG)

**Comment by zeromus** [comment]
Works fine for me. Your GPU driver is broken. Change config > display > display method to opengl or gdi+
