### ISSUE TITLE
Lua-driven savestate jamming can wreck Gambatte core

### ISSUE THREAD

**Issue by PikalaxALT** [TASVideos/BizHawk#949]
Loading save states via lua script (`savestate.loadstate(0)`) seems to trigger a `System.IndexOutOfRangeException` at `BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy.ProcessSound`.

Steps to reproduce:
1) Clone [AutoCrystal](/pikalaxalt/autocrystal) at `130de6ad87fe51ae3b25a23790cd0fe371279108`
2) Load Pokemon Crystal (U)
3) Open the Lua console
4) Point the Open Script dialog to the directory where you cloned AutoCrystal, and open `test.lua`
5) Wait 644 frames

**Comment by zeromus** [comment]
By sloppily jacking up all the sound buffer sizes in the core I can get past this; so it doesn't seem as if this is a deeply disturbing memory corruption bug, but rather more flaky behaviour from something we already know is flaky: GB and/or gambatte's timing of audio generation vs frame advances. In particular in this case it's getting 500K some odd samples.

**Comment by nattthebear** [comment]
This is invalid and will not be changed; Bizhawk cores are not reentrant.

There's nothing flaky about our Gambatte core except the fact that Ilari doesn't like it.

**Comment by zeromus** [comment]
Oops, I was wrong.
In other words, you can't do anything from lua events. In virtually all emulators in the universe, including this one. ESPECIALLY load states. And you should never expect to be able to. 
Set flags instead and catch them from the lua main loop
