### ISSUE TITLE
[request] SMSHawk: paddle controller emulation

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#950]
Some SMS games (like Alex Kidd BMX Trial) require paddle controller and cannot be played without it.

**Comment by Glitcholog** [comment]
Just so people know, according to the Sega Retro Website, those are the game that use the paddle controller (either optional or required)

BMX Trial: Alex Kidd (required)
Galactic Protector (required)
Megumi Rescue (required)
OutRun (optional)
Super Racing (optional)
Woody Pop: Shinjinrui no Block Kuzugi (required)
