### ISSUE TITLE
[TAStudio] Font/grid size option

### ISSUE THREAD

**Issue by Scepheo** [TASVideos/BizHawk#952]
The grid is in TAStudio can be a little small, causing people to mis-click. It would be nice to have an option to increase (or decrease) the size of the grid.

**Comment by vadosnaprimer** [comment]
I want to do it, but to work properly it seems to require revising the sizing logic and all the magic numbers that invade it now. Next release probably.

**Comment by vadosnaprimer** [comment]
Dunno when this can be finished, but at least it's been started:
https://github.com/TASVideos/BizHawk/commit/890e0701b3b8cea8b057f5a3f75c093521e4216e
