### ISSUE TITLE
NESHawk: Strike Wolf RAM issue

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#953]
There is a RAM glitch in this game that makes it impossible to advance after beating the first level when playing on an emulator. This glitch doesn't have such effect on real hardware.

[Strike Wolf (MGC-014) (Unl) [!].NesHawk.QuickSave6.zip](https://github.com/TASVideos/BizHawk/files/1202456/Strike.Wolf.MGC-014.Unl.NesHawk.QuickSave6.zip)

**Comment by zeromus** [comment]
what does "ram glitch" mean? where did you hear this?

**Comment by Reinc01** [comment]
https://www.gamefaqs.com/nes/989561-strike-wolf/faqs/66616#section3

**Comment by alyosha-tas** [comment]
The game expects to read something from $4100. Presumably some kind of simple anti piracy check.
Should be an easy fix.

**Comment by zeromus** [comment]
just reference this

https://github.com/asfdfdfd/fceux/blob/master/src/boards/36.cpp
