### ISSUE TITLE
mednafen upstream issues macro-ticket

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#955]
* Clockwork Knight 2 (US) hangs when an FMV should be played after the 1st boss
* Nightmare Creatures (and several others) boot up too early, causing sounds from the bios to loop infinitely
* #944

**Comment by nattthebear** [comment]
@zeromus Is there anything still actionable in this ticket?  I just updated Saturnus to latest upstream.

**Comment by zeromus** [comment]
Nah, lets just close it
