### ISSUE TITLE
Castlevania SOTN do not saves after killing Belmont.

### ISSUE THREAD

**Issue by PinkLouie** [TASVideos/BizHawk#957]
Hi, after killing Belmont, you go to the inverted castle. In the inverted castle I use the save points, and then I try to load the save point, but it loads the last save point before I have killed Belmont (or the Shaft invocation to be exactly). 

I dragged and dropped Bizhawk 2.2 to 2.1 folder to update. Maybe this is the cause?

**Comment by zeromus** [comment]
Did you drag and drop to update immediately after killing belmont? That was quite a coincidence. 

Use process monitor to watch which files are being accessed when you save in-game. Then explore your disk. You'll probably discover what you've wrecked.

**Comment by PinkLouie** [comment]
I deleted the old save from bizhawk directory, and now it is saving again. 
How to update bizhawk safely? Thank you for your support. I will close this.

**Comment by zeromus** [comment]
To update, start from scratch with a new dearchive, and manually bring in every file you need, while conscious of exactly what you're doing.

**Comment by PinkLouie** [comment]
The problem happened again, so I download Bizhawk 2.2 again and then copied my saves files to the new and clean Bizawk folder. It saves if I have no save for SoTN, but if I already have a save, when I save again in-game, it do not overwrites the old save. The save is always the first one. I am sending you the save files, Maybe it is a bug in PSX core, maybe I did something wrong.

[PSX.zip](https://github.com/TASVideos/BizHawk/files/1215057/PSX.zip)

**Comment by zeromus** [comment]
What am I looking at here? I see a save in the upside down castle, which i loaded, and then saved again immediately, and that save worked, and could be reloaded (determined by inspecting timestamps)
