### ISSUE TITLE
Add LAN Server-Client

### ISSUE THREAD

**Issue by legionpheonix** [TASVideos/BizHawk#958]
Please add the ability to play on a local network together.
In Kega Fusion there is such an opportunity

**Comment by vadosnaprimer** [comment]
It is... very, _very_ VERY **VERY** complicated. There's no emulator with idea netplay yet. So we can't even fully base on some approach. We will have to to come up with our own, and there's no dedicated developer for this right now.

**Comment by legionpheonix** [comment]
As long as there are no plans at all? (((
