### ISSUE TITLE
mac help

### ISSUE THREAD

**Issue by jorduino** [TASVideos/BizHawk#959]
I'm having trouble with the mac install. I followed the tutorial at http://tasvideos.org/Bizhawk/Compiling.html as much as I could, minus gitTortoise, and whenever I went to build it in visual studio, it threw multiple errors and it wouldn't load

**Comment by zeromus** [comment]
You don't make mac builds in visual studio. Visual studio for mac is a joke. Building bizhawk for osx is expert-level for now.
