### ISSUE TITLE
SMS overscan propagates to SG1000, and can't be turned off from there

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#961]
When you load an SG1000 ROM, while having the Overscan on for SMS, you'll get the same overscan for SG1000, and the latter doesn't give you the Overscan option in the menu, so you can't turn it off, unless you load an SMS ROM and disable it.

I tried to make the core ignore overscan if IsSG1000, but it broke everything.

**Comment by vadosnaprimer** [comment]
Actually, since SG1000 appears to use exactly similar screen as SMS, its overscan is also the same, so we don't need to disable it. But probably it would be nice to have it in the SG1000 options anyway, even if it shares the option with SMS? I dunno.

**Comment by alyosha-tas** [comment]
@vadosnaprimer try now, I think it's fixed

**Comment by vadosnaprimer** [comment]
Yes, thank you.
