### ISSUE TITLE
Wagyan Land (J) graphics glitch

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#962]
![wagyan land j t eng100 20001223_alanmidas 2017-08-16 03 48 50](https://user-images.githubusercontent.com/28905475/29342894-3df3f7ee-8236-11e7-9a3e-2bf08e0ab95e.png)
Rom **Wagyan Land (J) [T+Eng100%20001223_AlanMidas].nes** from GoodNES V3.23b , on the first stage not playable. Using core QuickHawk.

The question is that can be fixed, or only by using another core?

**Comment by alyosha-tas** [comment]
Does it work in NESHawk? I don't maintain QuickNES, so this isn't likely to be fixed.

**Comment by RetroGameIntros** [comment]
Yes, in NESHawk working but it using more cpu / memory , i'm usually prefer to use QuickNES

**Comment by zeromus** [comment]
It takes a really good reason for us to fix quicknes or add random mapper support. This isn't a really good reason. This rom doesnt even work in FCEUX. This rom isn't even supposed to be MMC3. It's a weird miracle that it does in neshawk -- I might even call that a neshawk bug.
