### ISSUE TITLE
Latest libretro stable and nightly no longer supported.

### ISSUE THREAD

**Issue by Danfun64** [TASVideos/BizHawk#963]
"Testing is currently being done primarily on Stable release 1.2.2" of Libretro. This version is more than two years old. Running the latest stable and nightly cores results in an error saying the core version isn't compatible. There hasn't even been any news on updating the libretro backend since before the 64-bit update. I think it's time to update the libretro backend so that it's caught up with the two years of development that have passed by.

**Comment by vadosnaprimer** [comment]
I dunno what you mean but have you tried our dev build?

**Comment by zeromus** [comment]
The instructions are outdated, not the implementation
