### ISSUE TITLE
Saturn multidisc support

### ISSUE THREAD

**Issue by dokusaisha** [TASVideos/BizHawk#965]
Even though the multi-disc bundler now supports Saturn disc images, there is no apparent way to switch the inserted disc during gameplay when needed.

**Comment by nattthebear** [comment]
There are controls "Previous Disk" and "Next Disk" for this core, keybindable along with other console buttons, that will move through the disks in a collection.

**Comment by dokusaisha** [comment]
Thank you! I had no idea it would be there.  I was expecting something more like the PS1 disc interface.  Great news, sorry for the bother.

**Comment by nattthebear** [comment]
The control scheme used was adopted from the Apple II and C64 cores, and later also used in the PCFX core.  I was not aware the PSX core did something different.
