### ISSUE TITLE
better error for running GBC games in DMG/GB mode

### ISSUE THREAD

**Issue by Famulator** [TASVideos/BizHawk#966]
Recently trying to run any GBC rom in DMG/GB mode has caused this error to display:

"A core accepted the rom, but threw an exception while loading it:
System.NullReferenceException: Object reference not set to an instance of an object.
at
BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy..ctor(CoreComm comm, GameInfo game, Byte[] file, Object settings, Object syncSettings, Boolean deterministic)"

I'm not entirely sure why this is happening, as GBC games in mono mode worked perfectly fine before yesterday. Also, GBC in mono works perfectly fine on Super Game Boy.

**Comment by nattthebear** [comment]
If you have use BIOS selected, make sure you have both BIOS files available.  It should be fixed to provide a better error message...

**Comment by Famulator** [comment]
Doing that seems to have fixed the issue entirely.

**Comment by alyosha-tas** [comment]
BIOS support was removed from Gambatte so this issue is resolved
