### ISSUE TITLE
Config file has Nintendo spelled incorrectly in the Nintendo 64 Controller section

### ISSUE THREAD

**Issue by timconner** [TASVideos/BizHawk#970]
https://github.com/TASVideos/BizHawk/blob/cdc934792eb652e87705ca450decfdf90d8ed96a/BizHawk.Client.EmuHawk/config/ControllerConfig.cs#L25

Config file reads as 'Ninetento' instead of 'Nintendo'.

**Comment by zeromus** [comment]
yes, we know. it's stuck this way for various reasons. but that reminds me i need to make a list of issues that cant really be fixed until a major release

**Comment by YoshiRulz** [comment]
Fixed in eb1d87933.
