### ISSUE TITLE
A7800 impossible to replay a previously created project

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/BizHawk#974]
1. Open A7800 rom, open tastudio, save project, load project:
- constant alerts of "oops" with the message http://imgur.com/6c3k6Xr

2. Open A7800 rom, record movie, stop movie, play movie:
- 1 window of this http://imgur.com/DZDJUTF

**Comment by zeromus** [comment]
I can't make this work at all. I get hangs and crashes when I try. The problem may be related to the sync settings for the controllers not being put in the movie or read from the movie properly?

**Comment by alyosha-tas** [comment]
That's strange, when it tries to load the movie it switches back to EMU7800.
Instead of messing around with system ID stuff again, I'm just going to power through the boredom and implement the POKEY sound chip in A7800Hawk so we can finally get rid of EMU7800 completely.

**Comment by alyosha-tas** [comment]
@meshuggahtas : I disconnected EMU7800 from the Dev Build and now things seem to be working correctly with movie recording. I tested both cases you mentioned and they now work fine. Please test on your end and make sure there are no more issues.

**Comment by meshuggahtas** [comment]
BizHawk 0.0.0.1758
+ I can replay back a movie that I made in TAStudio
- I can't open TAStudio, EmuHawk slowly crashes after minutes of not responding. Same happens when trying to load it via TAStudio.

Example game One on One basketball
485478092c2f192eaf29ca199b753d16 *One-on-One Basketball (1987) (Atari).a78
tasproj file:
https://drive.google.com/open?id=0BzzBXzk5TnLYbkZaRl85S3ZmOGc

**Comment by alyosha-tas** [comment]
You willl need to delete the 'greenzone' file and the 'laglog' file from the .tasproj, this is because savestates have changed (and will continue to change until pokey is complete.) the movie otherwise still syncs though.

**Comment by meshuggahtas** [comment]
This seems to fix most of my project files, but others are either have a fail column (for example player 2's column "2" filled with "!") or the same message of oops after a bit of replaying movie through TAStudio.

**Comment by alyosha-tas** [comment]
If you have any EMU7800 files that you really want re-synced to A7800Hawk feel free to send me the bk2 and I can fix it (either here or TASvideos.) Going forward EMU7800 will be removed from BizHawk, so now is the time to switch over.

**Comment by meshuggahtas** [comment]
I'm currently not in the mood to get all the hassles of recovering my project files (making a new movie with correct settings, copy it to corrupted movie, changing mnemonics in input, deleting greenzone... long procedure and easy to make mistakes through various files).

However I would do like getting the already published TASes being compatible with the new core.

Barnyard Blaster http://tasvideos.org/2670M.html - uses light gun, light gun x y coordinates have beenswitched, requires changing the columns of the movie file with regexp or something sort of
Ninja Golf http://tasvideos.org/2899M.html - have no idea what is the problem. Probably I had luck once but the movie was obviusly desynced at every portion
Scrapyard Dog http://tasvideos.org/3407M.html - same, once i could start it, changed 1 frame, saved, couldn't load it again back

**Comment by alyosha-tas** [comment]
I'll work on Ninja Golf and Scrapyard Dog. I doubt Barnyard Blaster will sync even if x-y is fixed since the detection algorithm is likely very different between the cores.

As for the original problem in this issue, movie recording is now fixed. If you need help with anything else feel free to open a new issue, or post in the TASvideos thread.
