### ISSUE TITLE
NESHawk: America Daitouryou Senkyo glitch

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#976]
The graphics become garbled when I reach the national convention stage. I don't know what the next screen is supposed to look like, but what it looks like now is just wrong, especially the bottom half.
[America Daitouryou Senkyo glitch.zip](https://github.com/TASVideos/BizHawk/files/1250959/America.Daitouryou.Senkyo.glitch.zip)

**Comment by alyosha-tas** [comment]
I don't know, the only image I found of that screen is here and it looks the same:

http://www.geocities.jp/frnyanko/setsumei/famicom/americadaitouryousenkyo/americadaitouryousenkyo.html

If you send the complete movie I can try it in mesen and see if it looks the same there as well.

**Comment by Reinc01** [comment]
[America Daitouryou Senkyo.zip](https://github.com/TASVideos/BizHawk/files/1253311/America.Daitouryou.Senkyo.zip)

**Comment by alyosha-tas** [comment]
Well the movie played back fine in Mesen and gave the same results

![mesen_convention](https://user-images.githubusercontent.com/18286462/29737529-43e10fc6-89dd-11e7-9d73-4a07469973d6.png)

So, I don't see any evidence that this isn't how it's supposed to look. Despite looking like a garbled mess I can't find anything actually wrong here.

I'll close this for now, but if you find another source reference that shows something different, feel free to re-open it.
