### ISSUE TITLE
input.getmouse() is broken in 1.13.0 and 1.13.1

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#977]
I cannot say sure, but it seems very likely that it's gui.drawImage that's causing trouble here.

My script works consistently and fine in 1.12.0.
But in 1.13.0 and 1.13.1, it crashes always a few seconds after loading it, most often on a "file not found" error. The script only uses two image files so I'm thinking gui.drawImage is causing this in new versions.

I haven't tested thoroughly, but 1.12.1 and 1.12.2 seems fine.
Problem starts happening in 1.13.0.

You can download my script here and try to run it for yourself:

https://www.mediafire.com/file/q2g7hxhl6z597xl/game.zip
(Run it on a gameboy or gba game)

Crash pretty much happens as soon as you load the script in 1.13.0.
I'm on windows 7 64bit.
This is how it looks: http://imgur.com/hYrBuRu.png

**Comment by nattthebear** [comment]
So you'd like the fix backported to 1.13.0?  Why?

**Comment by mugg91** [comment]
Not necessarily, seeing as how 1.x is going to be dropped in favor of 2.x at some point. But when it is, might want to drop it as a bugfree and stable version?

**Comment by mugg91** [comment]
Looks like it isn't gui.drawImage() that's causing trouble.
Please see this image https://i.imgur.com/BRfO9mN.png
I disabled all instances of gui.drawImage and the problem still occurs.

**Comment by YoshiRulz** [comment]
Don't expect a new backport anytime soon. Lua can get the mouse pos just fine in 2.x currently, so I suggest you update your script.
