### ISSUE TITLE
Bizhawk 2 crashes when trying to play Mega Man X2 or X3 with internal Snes9x

### ISSUE THREAD

**Issue by AdmiralCurtiss** [TASVideos/BizHawk#978]
Tested on 0e37c12c4f9720dfe991cd1cbaa7f4f42534a27a, access violation exception in `Bizhawk.BizInvokeProxyLibSnes9x.FrameAdvance()`.

**Comment by AdmiralCurtiss** [comment]
FYI it worked fine in Bizhawk 1.12 using the Libretro Snes9x core.

**Comment by nattthebear** [comment]
@adelikat I thought we blacklisted CX4 roms for Snes9x?

**Comment by AdmiralCurtiss** [comment]
Yes, you did, you have to disable the core auto-selection to get this to happen. I still find it weird though since it worked fine with the Libretro Snes9x.

**Comment by nattthebear** [comment]
It is a known issue.  It has to do with how the Snes9x core is embedded in the waterbox environment; don't go looking for similarities with libretro.

It would have been a bit tricky to fix just for two games, two games that are not very accurately emulated in Snes9x to begin with, and that already worked perfectly in bsnes, so we decided to automatically route those two games to the bsnes core only.

If you would like this fixed for real, what is it that you need that the snes9x core has but the bsnes core does not?

**Comment by AdmiralCurtiss** [comment]
Performance on low end machines. As you may or may not be aware, we've been using Bizhawk as the emulator of choice for a livestreamed game show where contestants compete against each other in classic games -- think Nick Arcade but via Twitch. Unfortunately, as it turns out, some participants use old or weak laptop/netbook hardware, which just can't deal with bsnes while also streaming via OBS. Using Snes9x helps with that, even if it means the emulation is not quite as accurate.

It's not a huge deal, as we can just pick different games for people who can't run bsnes acceptably, but it's something we noticed and figured we'd bring up.

**Comment by maxsize213** [comment]
a year late and completely irrelevant, but megaman x5 freezes on bizhawk. help

**Comment by hegyak** [comment]
@maxsize213 Please make a separate Bug report for this.  This is for SNES9x not running Megaman X2/X3 due to the CX4 Chip Emulation not being implemented in SNES9x

**Comment by nattthebear** [comment]
Faust should work and is much faster than bsnes (but not quite as fast as snes9x)

**Comment by nattthebear** [comment]
In addition to faust, this should now work in snes9x

3bc1ed4bbca0f4c81c5
