### ISSUE TITLE
SpeedThrottle() using large portion of CPU

### ISSUE THREAD

**Issue by danebou** [TASVideos/BizHawk#991]
SpeedThrottle() was using a large portion of computation (~10 -15% of the entire program). This by some miscalculation in the sleep time being evaluated to 0.

**Comment by zeromus** [comment]
It's SUPPOSED to. In order to stop from giving up the processor when less than 1ms is required. It sleeps until near (within ~2ms) of the target time and then spins until the target time is reached.

**Comment by danebou** [comment]
Sorry, I get the purpose now. Still 12% of the program's entire usage seems way too high. I might look into it more.

**Comment by zeromus** [comment]
in case an emulator core runs instantly (GB, say), it could spin for every 2 out of 16ms --> 12%

**Comment by danebou** [comment]
So now I'm questioning why we need that resolution. In the end it only we are displaying frames to a user on their display device. The maximum refresh rate out there is 7ms (240hz). So no matter what VSYNC is going to be more out of sync with Bizhawk than the timers can produce.

**Comment by zeromus** [comment]
Suppose a frame always runs in 14ms and we decide that's close enough because you think the timing isn't important. Now the game is running ~12% faster than it should. That's comparable to the difference between 50/60 hz PAL/NTSC and nobody would propose to get rid of those.

Just so you're clear, you're not debating me for the purpose of revising bizhawk, since that is not going to happen. It doesn't matter what happens to CPU cycles spent during a throttle, whether they sleep or burn in a busy loop, unless you're on a device with a finite battery. Bizhawk is for getting work done. Battery doesn't matter and won't be optimized for.

**Comment by danebou** [comment]
You can simply make up for it on the next frame. So in the 14ms example. Frame 1 occurs and is displayed at t = 0ms. Now the sleep function attempts to run for 14ms, but say actually runs for 16ms. Frame 2 is then displayed. The StopWatch can measure this and the next time it occurs run for 14ms + (14ms - 16ms) = 12ms instead of the original 14. Repeat this and two applications running side-by side are always displaying 0 or 1 frames apart. (Same as the existing code)

> Just so you're clear, you're not debating me for the purpose of revising bizhawk

I hope I'm not coming across too pushy here. I care about improvements to BizHawk. Don't want to get into this too much into this on GH, but I've heard one of the biggest issues with BizHawk, at least on the N64 side is the performance. I'm definitely for the "don't optimize things that don't need it". But given that you could improve the user's experience, especially when they are asking for it, why wouldn't you? (Also really do appreciate your assistance so far)

**Comment by zeromus** [comment]
When the sleep function attempts to run for 14ms but actually sleeps 16ms, you miss a frame.

I'm tired of discussing this. You're welcome to implement your own throttle if you want, and we can make a mechanism to switch between them. I guarantee you havent studied it as deeply as the multiple people who have wrangled with our throttling approach for MULTIPLE DECADES have.

If you're interested in performance, then investigate performance, not this. This isn't affecting performance. I am amazed that for all your apparent sophistication in addressing this subject, you don't see that performance isnt relevant if throttling is happening. It's only relevant when people are running unthrottled or fast forwarding, in which case the throttle doesnt matter.

**Comment by danebou** [comment]
> I'm tired of discussing this.

Yeah I agree. My discussion of this has been too scattered. I'll wrap up with this for now and I'll update a my PR later with a more concise analysis and I think it will be much clearer. Makes sense to only merge things that have purpose so appreciate your feedback!

> I guarantee you haven't studied it as deeply as the multiple people who have wrangled with our throttling approach

Definitely agree. Anyone's who worked on this clearly has given it way more thought. I think the only thing that differs now is perhaps performance wasn't considered as much.

> you don't see that performance isn't relevant if throttling is happening. 

Nah with TASing people do a lot of multitasking. So freeing up BizHawk resources helps a ton. I guess I'm not really talking about performance as much as I am CPU usage.
