### ISSUE TITLE
QuickNes bug - Joe & Mac

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#993]
The bug is that you don't see your and boss health, and score too. You can beat boss, but this bug will be on others bosses until you finish this game.

Tested on rom **Joe & Mac - Caveman Ninja (U) [!].nes** from **GoodNES V3.23b**

Joe & Mac
SHA1:36BAFDF6F8D531FECB3553C1923EEAFAC4A05C28
MD5:FA45F240B40310FB3B4A7F76E7612886

![joe mac 2017-09-02 01 57 53 0](https://user-images.githubusercontent.com/28905475/29990365-6f2186ac-8f82-11e7-8f25-15aab9313447.png)

**Comment by hegyak** [comment]
Does this happen on NESHawk as well?

**Comment by RetroGameIntros** [comment]
No, only on QuickNes

**Comment by adelikat** [comment]
Should we blacklist this rom in quicknes so it fallback to neshawk?

**Comment by Tastyfish** [comment]
This seems to be a textbook reason for why the blacklisting exists.

**Comment by alyosha-tas** [comment]
This game uses an un-supported mmc3 variant, so yeah I'll add it to the blacklist.
