### ISSUE TITLE
Running Bizhawk on Windows 10

### ISSUE THREAD

**Issue by DrBombanomcon** [TASVideos/BizHawk#996]
I'm trying to run Bizhawk on windows 10 on the most resent version of Bizhawk. I run the prereq then opened the Emulator but it won't open at all. This hard drive didn't start on windows 7 and was just strage up windows 10. If theirs anything I need to get first, let says so.

**Comment by hegyak** [comment]
Have you used the Prerequisite installer Version 2.0?  And, have you extracted all the files with the folders as well?  Are you using an config file from an older version?  What video card do you have?

**Comment by DrBombanomcon** [comment]
I have use the lastest Prerequisite installer version, I've extracted all the files and is using version 2.2. But why my video card?

**Comment by DrBombanomcon** [comment]
I'm using NVIDIA NVS 3100M

**Comment by alyosha-tas** [comment]
do pre-2.0 versions work for you?

**Comment by DrBombanomcon** [comment]
I think so I don't know because I won't open at all.

**Comment by zeromus** [comment]
you're using a laptop with a crappy integrated GPU. fiddle with your optimus settings to force it to use the discrete GPU for bizhawk.

**Comment by DrBombanomcon** [comment]
Okay I did that but when I load the other file Discohawk, It says that Emuhawk.Emulation.Discsystem is not found, is that a problem?

**Comment by zeromus** [comment]
Your security software is interfering. Disable it all.

**Comment by DrBombanomcon** [comment]
WHAT? What do you mean?

**Comment by zeromus** [comment]
I mean your security software is interfering. Disable it all.

**Comment by DrBombanomcon** [comment]
Why?

**Comment by zeromus** [comment]
Because your security software is interfering.

**Comment by DrBombanomcon** [comment]
How?

**Comment by zeromus** [comment]
By making EMuhawk.Emulation.DiscSystem not be found by Discohawk.

**Comment by DrBombanomcon** [comment]
Because I have no idea how this coraltes

**Comment by zeromus** [comment]
Nor will you ever if you don't try my troubleshooting steps

**Comment by DrBombanomcon** [comment]
Okay so... how do I do that (Note: I will comment other wise)

**Comment by DrBombanomcon** [comment]
Okay so what type of security software do you mean?

**Comment by zeromus** [comment]
You disable your security software. If you're asking how to disable your security software, consult your IT admin, security software vendor, or whoever is nearby who knows how to computer, maybe whoever straged up your windows 10.

**Comment by DrBombanomcon** [comment]
No like Anti-Virus, Firewall, App controll.

**Comment by zeromus** [comment]
Choose one.
zeromus said "disable your security software".
Did he mean
A) Some of it
B) All of it

**Comment by DrBombanomcon** [comment]
It think A but he is being very vage. (Plus I didn't download one from the internet)

**Comment by zeromus** [comment]
OK, followup question.
Suppose zeromus meant (A) (some of it).
It makes sense that you would ask "which one?"
The question is now:
C) Anti-Virus
D) Firewall
E) App controll.
Let's suppose the answer is (C) Anti-Virus.

Now suppose that solves the problem. Great! We're done.
Suppose that it doesn't solve the problem.
Which of these does zeromus say to try next:
F) Disable other one security software
G) Something else entirely

**Comment by DrBombanomcon** [comment]
Makes scene. But you could just simplify it

**Comment by zeromus** [comment]
I thought _disable it all_ was pretty simple. Sorry, I can see now that I misled you.
Here's let's start over.

Choose one.
zeromus said "Your security software is interfering. Disable it all."
Did he mean
A) Disable some of your security software
B) Disable all of your security software

**Comment by DrBombanomcon** [comment]
Okay I disable all the ones I meanstion but I still won't work.

**Comment by zeromus** [comment]
redownload bizhawk. dearchive it to a folder on your desktop instead of wherever you dearchived it to. use a different program to dearchive it than you did before.

**Comment by DrBombanomcon** [comment]
No luck still won't read the file.

**Comment by DrBombanomcon** [comment]
Nevermind! Dr.Bombanomcon IS OUT!

DrDombanomcon [Level 1] Left the webstie
