### ISSUE TITLE
Libretro Save States not Retroarch compatible.

### ISSUE THREAD

**Issue by Danfun64** [TASVideos/BizHawk#997]
I'm not sure if this is possible, but while I understand, for example, savestates from BizHawk's native Snes9x core not running in Retroarch, I'm a little surprised that the save states produced by using the Retroarch Snes9x core in BizHawk don't work in Retroarch either. If there was intercompatibility between Retroarch save states and Bizhawk in Libretro mode save states, I'd probably use Bizhawk a whole lot more.

Granted, i'm not sure if this is possible, or if it would require a major rewrite or something, but it would definitely be nice to have.

**Comment by vadosnaprimer** [comment]
Are you trying to use namely libretro snes9x core in bizhawk or bizhawk's own snes9x core?

**Comment by Danfun64** [comment]
libretro snes9x core in bizhawk. The save states made from that method don't work in Retroarch, and vice versa.

**Comment by vadosnaprimer** [comment]
I think bizhawk is packing what the core returns into its own state format, while retroarch uses the core's state as is. I don't think it should ever be expected to work in both.

**Comment by Danfun64** [comment]
"I don't think it should ever be expected to work in both." Why not? I doubt BizHawk can properly be considered a "Libretro frontend" if Libretro states made in BizHawk can't be run in Retroarch or vice versa.

**Comment by vadosnaprimer** [comment]
What do your doubts have to do with if state compatibility has not ever been a goal? As I said, bizhawk adds overhead it uses for its needs, retroarch presumably doesn't.
