### ISSUE TITLE
Windows 7 issue after reinstall

### ISSUE THREAD

**Issue by luke-burton** [TASVideos/BizHawk#998]
Hello, I reinstalled windows and now I'm getting this issue.
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EmuHawk.exe
  Problem Signature 02:	2.2.1.0
  Problem Signature 03:	59861549
  Problem Signature 04:	SlimDX
  Problem Signature 05:	4.0.13.43
  Problem Signature 06:	56d39732
  Problem Signature 07:	73b
  Problem Signature 08:	3
  Problem Signature 09:	System.AccessViolationException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	2057
  Additional Information 1:	628f
  Additional Information 2:	628f774c266c82f08bb1a5be13a37935
  Additional Information 3:	1fbe
  Additional Information 4:	1fbe56082b69f3d612a58c20dc287f48

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by zeromus** [comment]
upgrade or downgrade your GPU drivers (or install them in the first place).
If you're using a laptop, make sure you've switched them to use discrete graphics for bizhawk

**Comment by luke-burton** [comment]
Hey, I reinstalled directX and it started working. Thanks.

**Comment by zeromus** [comment]
did you run the bizhawk prerequisite installer in the first place? which version?

**Comment by luke-burton** [comment]
I didn't know there was a prerequisite installer... and i was using the latest version of bizhawk
