### ISSUE TITLE
Bomberman Collection doesn't working

### ISSUE THREAD

**Issue by TheMotherBrain86** [TASVideos/BizHawk#999]
After you selected a game, the game was not starting. Instead, it restarting to main menu always. How to reproduce issue: Choose any game from main menu and press "Start" button, selected game should run

**Comment by hegyak** [comment]
I need a LOT more information then that.
What Core(s) are you using?  What system is this Game for?  Is a known good Dump?  What's it's checksum (SHA-1)?  What version(s) of BizHawk are you using?

**Comment by TheMotherBrain86** [comment]
1. Core - Gambatte
2. This game for Gameboy system
3. Yes, this is a good dump (marked as green ✔)
4. Checksum (SHA-1) below:

Bomberman Collection (Japan)
SHA1:385F8FAFA53A83F8F65E1E619FE124BBF7DB4A98
MD5:9FB9C42CF52DCFDCFBAD5E61AE1B5777

5. Bizhawk developer build with latest commit 7c1522c, i tried also on Bizhawk 2.2

**Comment by alyosha-tas** [comment]
This game uses a non-standard banking scheme (even though there is no indication of this in the header.)

It's a known and well understood issue, but not one likely to get fixed in Gambatte (at least not by me.) It works in Sameboy if you are interested. 

I'll also make sure it's working in the upcoming GBHawk.

**Comment by Tastyfish** [comment]
For specifically _Bomberman Collection_ at least, it will bank into the games if you goto the menu `GB->Settings... ` and set `Multicart Compatibility` to `true`. Not sure why this isn't done automatically based on the header.

**Comment by nattthebear** [comment]
If I remember correctly, Multicart Compat was an option in the original Gambatte API so I just brought that forward.  I don't know what the impact of turning it on all the time would be.

**Comment by alyosha-tas** [comment]
Choosing Multicart Compatibility is the correct method to make this game work. While setting the flag automatically is possible, there is no real need as multi-cart compatibility is now added to GBHawk. 

Tested ROMs include BomberMan Collection, Mortal Kombat 1 & 2, and Gekkio's test rom. (NOTE: the games have other errors but they are unrelated to the mapper.)

So, closing.
